### ISSUE TITLE
Some problems were encountered while building the effective model

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml#100]
```
$ mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for net.sourceforge.plantuml:plantuml:jar:1.2018.2-SNAPSHOT
[WARNING] 'parent.relativePath' of POM net.sourceforge.plantuml:plantuml:1.2018.2-SNAPSHOT (D:\plantuml\pom.xml) points at org.sourceforge.plantuml:plantumlservlet instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 54, column 13
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 165, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 140, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 151, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

Perhaps related to: https://github.com/plantuml/plantuml/issues/91 Prefix inlined dependencies

**Comment by arnaudroques** [comment]
Thanks for the report. Can someone help us on this one ?
Thanks!

**Comment by meua** [comment]
The problem occurs because Maven by default assumes that the parent pom is found in the parent folder of the one that contains the module pom. However, in your project that does not seem to be the case: Your parent pom is org.springframework.boot:spring-boot-starter-parent:1.5.6.RELEASE while the pom com.xxx:parent:1.0.0 in the parent folder is only used as an aggregator for the modules.

To solve this problem you need to unset the relative path in the parent declaration in the module poms like this:

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.6.RELEASE</version>
    <relativePath/>
</parent>

**Comment by Ivyx** [comment]
> Il problema si verifica perché, per impostazione predefinita, Maven presuppone che il pom principale si trovi nella cartella padre di quella che contiene il modulo pom. Tuttavia, nel tuo progetto non sembra essere il caso: il tuo genitore pom è org.springframework.boot: spring-boot-starter-parent: 1.5.6.RELEASE mentre pom com.xxx:parent:1.0.0 in la cartella principale viene utilizzata solo come aggregatore per i moduli.
> 
> Per risolvere questo problema devi disinserire il percorso relativo nella dichiarazione principale nei poms del modulo in questo modo:
> 
> ```
> <parent>
>     <groupId>org.springframework.boot</groupId>
>     <artifactId>spring-boot-starter-parent</artifactId>
>     <version>1.5.6.RELEASE</version>
>     <relativePath/>
> </parent>
> ```

Hi you can explain generic? I don't use spring and I have the same problem. Thank you

**Comment by justlostsoul** [comment]
spring-boot-maven-plugin is always red, how to do it?

**Comment by arnaudroques** [comment]
Not sure this is still valid.
Please reopen if needed.
