### ISSUE TITLE
Packages loose skinparameters with nested elements [2022.4]

### ISSUE THREAD

**Issue by spmadden** [plantuml/plantuml#1000]
Unstyled:
 * [Unstyled diagram](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuU8gpixCAqWiIinL24XCpavCJrMevb800hVyl1Bd_9py8eMYr1IuI71cLQg2aG5NBHTN0LHvIMfn2LHFSavYSJ5Om0YamY4rBmLe1m00)
 * ![unstyled](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuU8gpixCAqWiIinL24XCpavCJrMevb800hVyl1Bd_9py8eMYr1IuI71cLQg2aG5NBHTN0LHvIMfn2LHFSavYSJ5Om0YamY4rBmLe1m00)

Styled:
* [Styled diagram](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuU8gpixCAqWiIinL24XCpavCJrMevb800hVyl1Bd_9py8eMYr1IuI71cLQg2aG5NBHTN0LHvIMfn2LGFIDWXDIy5Q300)
* ![styled](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuU8gpixCAqWiIinL24XCpavCJrMevb800hVyl1Bd_9py8eMYr1IuI71cLQg2aG5NBHTN0LHvIMfn2LGFIDWXDIy5Q300)

**Comment by The-Lum** [comment]
Hello @spmadden,

See similar observation/issue here:
- #966

And:
- https://github.com/plantuml/plantuml/issues/997#issuecomment-1100606593

Here is a proposal or a workaround, with adding:
```puml
<style>
title {
    FontColor red
    FontSize 20
    Fontstyle plain
}
</style>
```
>[![](http://www.plantuml.com/plantuml/svg/ZOyn2iCm34LtdK8tQCWSIg3GkT0JY4GK4yKsbZgq8NUl2CRGBThq-7hYZsfKxBqA36eVuIjOC67S07tkATejIIfOU6xa6RwCVTVsun2pK8Ymmt2f8iWqBVHYD5Qhmab8zG2zHq6N43CLMl5HisV-xl_g3ZT78yVPQ_m0)](http://www.plantuml.com/plantuml/uml/ZOyn2iCm34LtdK8tQCWSIg3GkT0JY4GK4yKsbZgq8NUl2CRGBThq-7hYZsfKxBqA36eVuIjOC67S07tkATejIIfOU6xa6RwCVTVsun2pK8Ymmt2f8iWqBVHYD5Qhmab8zG2zHq6N43CLMl5HisV-xl_g3ZT78yVPQ_m0)

Then, @arnaudroques, and PlantUML team, like on https://github.com/plantuml/plantuml/issues/997#issuecomment-1100606593:
- Why `Package Group Header` use style for `title`? 

_If that can help,_
Regards.

**Comment by The-Lum** [comment]
Here is an answer... 👍 
In fact it uses `element  > title `, as:

```puml
<style>
element {
  title {
    FontColor red
    FontSize 20
    Fontstyle plain
  }
}
</style>
```

>[![](http://www.plantuml.com/plantuml/svg/ZOyx2iCm341tdK8tQCWSIg3GkT0JY4GK4_c3fGvjyDrhZ0bqooOz7azeLgDiRoymgNs4hy32deFX3eZcJBXDYFSOx1ObPioy7kJflepZSEmjWad8XSeA59WkFGo9berUZCPgFRe8gJOmLXLqSo5H9e-FxfwvNVxJ0-uLpHpM-jOF)](http://www.plantuml.com/plantuml/uml/ZOyx2iCm341tdK8tQCWSIg3GkT0JY4GK4_c3fGvjyDrhZ0bqooOz7azeLgDiRoymgNs4hy32deFX3eZcJBXDYFSOx1ObPioy7kJflepZSEmjWad8XSeA59WkFGo9berUZCPgFRe8gJOmLXLqSo5H9e-FxfwvNVxJ0-uLpHpM-jOF)

Regards.

**Comment by The-Lum** [comment]
Then, @arnaudroques, and PlantUML team:
- How to style only all `package` and not `frame` ?

```puml
@startuml
<style>
Package {
  FontColor red
  FontSize 20
  Fontstyle plain
}
element {
  Title {
    FontColor red
    FontSize 20
    Fontstyle plain
  }
}
</style>

title title 
package test {
    file test2
}

package test0 {
}

frame f
frame f0 {
}
frame f1 {
file a
}
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/PP11gi8m48RtSugvmUlhkaX1S2te1GOxbU0aAScuKEdT7PAuq6uIlf_vlmmPirBIknSOiZw4Tt2aouskZ2z0FCIW-oWnOUAfySaz6VkkKIdX8kG2hC32deEMxjcfLClMyslQkX1Nymr_RIdGOgidB6r5vLpVGfoTLEwjzZNGsOH5SoBFE7_kcZRuDoW2icpaCDb_l040)](http://www.plantuml.com/plantuml/uml/PP11gi8m48RtSugvmUlhkaX1S2te1GOxbU0aAScuKEdT7PAuq6uIlf_vlmmPirBIknSOiZw4Tt2aouskZ2z0FCIW-oWnOUAfySaz6VkkKIdX8kG2hC32deEMxjcfLClMyslQkX1Nymr_RIdGOgidB6r5vLpVGfoTLEwjzZNGsOH5SoBFE7_kcZRuDoW2icpaCDb_l040)

**Comment by The-Lum** [comment]
Hello all,

With last [snapshot (~v1.2022.8beta7)](https://github.com/plantuml/plantuml/releases/tag/snapshot) _(and  https://github.com/plantuml/plantuml/commit/2d07f5ae2cd39aa68998e27f2143d34bdeb45f0c)_ we can now style only all package and not frame, using:

```puml
@startuml
<style>
Package {
  FontColor red
  FontSize 20
  Fontstyle plain
  Title {
    FontColor red
    FontSize 20
    Fontstyle plain
  }
}
</style>

title title 
package test {
    file test2
}

package test0 {
}

frame f
frame f0 {
}
frame f1 {
file a
}
@enduml
```

>[![img](https://www.planttext.com/api/plantuml/svg/RP3F2i8m38VlUOgyWNFd8GF1iw0l45mgnQuTNJnCsRiRsdZmpoNX-v4l3UrdeIptCK0ton9u1qUwtEZA-0J4GugoJo5bp3mOd_o3iMsCYeHJ81yrENi9rVnrl-r__WehT1ix1AHignKcEqju5dl1-L2vLUrZeD49ZLocaT6zUqqDjWfb0MdMSnpq3ru0)](https://www.planttext.com/?text=RP3F2i8m38VlUOgyWNFd8GF1iw0l45mgnQuTNJnCsRiRsdZmpoNX-v4l3UrdeIptCK0ton9u1qUwtEZA-0J4GugoJo5bp3mOd_o3iMsCYeHJ81yrENi9rVnrl-r__WehT1ix1AHignKcEqju5dl1-L2vLUrZeD49ZLocaT6zUqqDjWfb0MdMSnpq3ru0)

Thanks to PlantUML team. 👍 
Regards.

**Comment by arnaudroques** [comment]
With last snapshot, we *try* to improve consistency.

So you can have:
```
@startuml
<style>
element{
  title {
    FontColor red
    FontSize 20
    Fontstyle plain
  }
}
</style>

title title 
package test {
    file test2
}

package test0 {
}

frame f
frame f0 {
}
frame f1 {
file a
}
@enduml
```

![image](https://www.plantuml.com/plantuml/png/LOzH2W8X443_vnHpWxRzNc8Xw0ATO6Z7a4PTTFgeyEuDgotaX_eUmnFdefJr6GIceY_X4x1muAWVG5IlmcWtMvSKzPmaPSoyxERgtupZiFFMm5N8HtCLAao7teLMQpkiT7lGtP2BzXUSbyOZLFWR66p2bCiK6DtlRBR3qM0BaBcPus9V-W80)

Tell us what you think about it, it's not the final version.

Thanks for your tests!

**Comment by arnaudroques** [comment]
It's maybe too much but we have added a `composite` property for elements that contain other element.
For example:

```
@startuml
<style>
element{
  title {
    FontColor red
    FontSize 10
    Fontstyle plain
    composite {
       FontSize 20
    }
  }
}
</style>

title title 
package test {
    file test2
}

package test0 {
}

frame f
frame f0 {
}
frame f1 {
file a
}
@enduml
```

![](https://www.plantuml.com/plantuml/png/LOzV2i8m38VVSuhSm6tFGmQ25_04OSkacBQZZGygkxjnhOCL-kVxI7vjXwoKzEa5-gmluJEmiEUW7q1Kfy9e9nlN6FGI9IPCFEtcvjwCRRFpbe6Ba0kR6wDVOdPQKmvjNMbRuJTNw4_r0L2kBIiiD3xeRiXPQyZif71dROU2nYfCpOayu_pVYwtG6cm1P6xWCDdVlm00)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @spmadden for the report.
- Thanks PlantUML team for your work.

Regards.
