### ISSUE TITLE
Missing state fork/join in plain theme

### ISSUE THREAD

**Issue by ThunderKey** [plantuml/plantuml#1008]
I've noticed that with the `plain` theme forks are not shown. They are just white boxes on white background. Is this intended?

Minimal example that shows the missing forks/joins:

```puml
@startuml Test
!theme plain

state ForkTest <<fork>>
state JoinTest <<join>>
[*] --> ForkTest
ForkTest --> State1
ForkTest --> State2
State1 --> JoinTest
State2 --> JoinTest
JoinTest --> [*]
@enduml
```
![State Diagram without Forks](https://user-images.githubusercontent.com/1478376/166651244-9c849e6b-3686-47d8-a01e-8fcd65f65f22.png)

As a workaround I've added the following `<style>` tag:

```puml
@startuml Test
!theme plain

<style>
  fork, join {
    BackgroundColor $FGCOLOR
  }
</style>

state ForkTest <<fork>>
state JoinTest <<join>>
[*] --> ForkTest
ForkTest --> State1
ForkTest --> State2
State1 --> JoinTest
State2 --> JoinTest
JoinTest --> [*]
@enduml
```
![State Diagram with Forks](https://user-images.githubusercontent.com/1478376/166651547-a384bf37-c0b9-46f4-a12c-a66b5e8063df.png)

**Comment by matthew16550** [comment]
Hi @ThunderKey

Which PlantUML version are you using?

I think this has already been fixed recently.

**Comment by ThunderKey** [comment]
Ah yes, you are right. Sorry...

I'm using the current version from the Manjaro repository, which indeed is quite a bit behind (1.2021.16-1). I did also see this behaviour in the theme gallery, but now I see that this is also not the current version (1.2022.2beta2).

With the current version it works perfectly :)

**Comment by The-Lum** [comment]
FYI, I just update the theme gallery with the last version (v1.2022.5).
_[I will plan to automate that]_
