### ISSUE TITLE
Adopt default file extension

### ISSUE THREAD

**Issue by hinell** [plantuml/plantuml#1015]
As was listed earlier [here](https://github.com/qjebbs/vscode-plantuml/issues/138#issuecomment-412721096), I suggset we adopt the following file extensions for textual plantuml files: 
```
*.wsd
*.pu
*.puml
*.plantuml
*.iuml
```

**Comment by The-Lum** [comment]
Good, that seems conform to:
- https://plantuml.com/command-line
- https://plantuml.com/sources

Regards.
