### ISSUE TITLE
Problem with the current release 1.2022.5

### ISSUE THREAD

**Issue by clickwithclark** [plantuml/plantuml#1019]
I am not sure how this happened but I am unable to get the latest build 1.2022.5 to work on my machine (Windows 10).
After some luck, I got a copy of the same version but a different build apparently.

## First: I was having this issue and no solution worked:

![image](https://user-images.githubusercontent.com/20617584/168897014-ec94ff16-0c03-4e81-bc3e-2e8790cb4ec4.png)

## Second: Even though the build is currently failing I followed the instructions on the extension marketplace and did a choco install
![image](https://user-images.githubusercontent.com/20617584/168898050-4cb39288-ae32-4a74-800a-47c06834d23f.png)

I got a plantuml.jar file from that installation with the same version number that has **no issues and works as intended.**

The problematic build is both on the plantUML official website and as the latest release in this repo, I checked them to confirm this.

![not working](https://user-images.githubusercontent.com/20617584/168898828-72fae3df-1fe1-490f-9399-673fe0d34d42.png)

![working](https://user-images.githubusercontent.com/20617584/168898921-d279da37-89ba-450d-97e8-ecfd7dd7e6fc.png)

I hope this helps with fixing the problem

**Comment by soloturn** [comment]
he @clickwithclark i extracted the jar from the vs code plugin, and it looks like version 1.2022.0, you mind trying this build?
https://github.com/plantuml/plantuml/releases/tag/v1.2022.0

as well, if you could do a "java -version"?

**Comment by clickwithclark** [comment]
The working copy I got from the choco install is PlantUML Version 1.2022.5 too that is what is so confusing.
```console
$ java -jar plantuml.jar -version
PlantUML version 1.2022.5 (Sat Apr 30 06:55:52 BOT 2022)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK


##  The 1.2022.0 version also works fine


PlantUML version 1.2022.0 (Tue Jan 11 12:16:42 BOT 2022)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK

```

Sorry for the false alarm, I have downloaded and tested again and all is working fine. I am unsure of why this happened. I did install everything at once, so if I had to guess maybe I needed to restart my system.
