### ISSUE TITLE
Display year in timing diagrams using time and date

### ISSUE THREAD

**Issue by vpoulailleau** [plantuml/plantuml#1020]
I haven't found in the documentation how to customize the display of the time axis. I want to display year instead of month/day. Is there any way to do so?

Currently my diagram is useless:

```plantuml
@startuml
scale 31536000 as 50 pixels

concise "OpenGL Desktop" as OD

@1992/01/01
OD is {hidden}

@1992/06/30
OD is 1.0

@1997/03/04
OD is 1.1

@1998/03/16
OD is 1.2

@2001/08/14
OD is 1.3

@2004/09/07
OD is 3.0

@2008/08/01
OD is 3.0

@2017/07/31
OD is 4.6

@enduml
```

![opengl_versions](https://user-images.githubusercontent.com/17438768/169264648-4478e657-3d30-4349-8711-5828932d17bb.png)

BTW I had problem configuring the scale, but I tried with the unit being seconds and it worked, that may be reflected in the document.

And also, thanks very much for plantuml, I've been a user for years.

**Comment by vpoulailleau** [comment]
The current work around I use is:

```plantuml
hide time-axis

concise "Année" as YEAR

@YEAR
1992/01/01 is 1992
1993/01/01 is 1993
1994/01/01 is 1994
1995/01/01 is 1995
1996/01/01 is 1996
1997/01/01 is 1997
1998/01/01 is 1998
1999/01/01 is 1999
2000/01/01 is 2000
2001/01/01 is 2001
2002/01/01 is 2002
2003/01/01 is 2003
2004/01/01 is 2004
2005/01/01 is 2005
2006/01/01 is 2006
2007/01/01 is 2007
2008/01/01 is 2008
2009/01/01 is 2009
2010/01/01 is 2010
2011/01/01 is 2011
2012/01/01 is 2012
2013/01/01 is 2013
2014/01/01 is 2014
2015/01/01 is 2015
2016/01/01 is 2016
2017/01/01 is 2017
2018/01/01 is 2018
2019/01/01 is 2019
2020/01/01 is 2020
2021/01/01 is 2021
2022/01/01 is 2022
```

**Comment by arnaudroques** [comment]
It's not exactly your request, but [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) allows this:

```
@startuml
scale 31536000 as 50 pixels

concise "OpenGL Desktop" as OD
manual time-axis

@1992/01/01
OD is {hidden}

@1992/06/30 as :1992
OD is 1.0

@1997/03/04 as :1997
OD is 1.1

@1998/03/16 as :1998
OD is 1.2

@2001/08/14 as :2001
OD is 1.3

@2004/09/07 as :2004
OD is 3.0

@2008/08/01 as :2008
OD is 3.0

@2017/07/31 as :2017
OD is 4.6
@enduml
```

[The result is here](https://www.plantuml.com/plantuml/uml/NSt1QeGm40RWUvvYs7kT6UEQsDCUX5uAFaFGG4DZLXe5eVJTQuZni32Nd-__cKTSpS-wpLx4qNWBak-o9I8m4Uu4YzkjZqACpp2wQE4sB3PyV49lu_VwN6wfDlHYDc4p7bOtspUpksFmuAwhaVWuCVJW8ln-kMcouU-o5YMb_NkAPuahogwG959JN5tEsNLoRelho-l3QqgFDNBUftYvpDuWTKYgU7Ewh2YxndHSNByuAoI5iZYhqvkgFTo6QPlzFm00).

Does it help?

**Comment by vpoulailleau** [comment]
@arnaudroques Thanks for the workaround.

It looks better than my workaround. Though, since I have several `concise` lanes, this workaround seems hard to be applied (if I understand it well) because several events may be in 1992, and the label doesn't start exactly at the beginning of the year.

But it seems feasible to do so:
```plantuml
@startuml
scale 31536000 as 50 pixels

concise "OpenGL Desktop" as OD
manual time-axis

@1993/01/01 as :1993
@1994/01/01 as :1994
```

Thanks for the tip, the workaround is sufficient for me, it solved my display problem.

As you mentioned, this doesn't solve the initial request to configure the display of the date automatically. You may consider to close this issue if you feel this is not necessary. I can live with the workaround.

**Comment by arnaudroques** [comment]
So we have made progress...
You can now [have this](https://www.plantuml.com/plantuml/uml/NT3DQeGm4C3nUvvYy5vdnhX-tFOWz5Bm6O9EQQX6sOcmfVJT6t5hOSESVlCdXxbgTBUupPFHmKq2bY-s8Y9m2XU2rTzbKcE69GnU1R9-bV3w1ftePrpMRC_wpimkR6w2w6TvSNUlPaljwAB0-tARNOJiAxtCc2ktRO74QKpVWLVu_l3ZAE7dt5LewR7Zd0wkaInIUJ8VtEpCrSb5ueBstnla_zeUN2ArIFM3RKu7DxWFFp7NAKNxnsLU9POmfalz0W00).
The format for the date [is defined here](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html).

Hope this helps!

**Comment by vpoulailleau** [comment]
This is perfect for me, thanks very much @arnaudroques 

I let you close the issue (in case you want to track documentation update (https://plantuml.com/fr/timing-diagram)).
