### ISSUE TITLE
Agent component cannot coexist with others

### ISSUE THREAD

**Issue by fflatorre** [plantuml/plantuml#1021]
Using version 1.2022.5

I'm experiencing problems getting a generic _"Syntax Error ?"_ when trying to add an **agent** to a diagram with other components.
This seems to be fairly easy to replicate : 

```
@startuml
agent agentName
object objectName
@enduml
```
but also : 
```
@startuml
agent agentName
entity TestEntity << (V,#EEEEEE) >>  #line.dotted:purple;back:lavenderblush {
 <i><color:SlateGray><i>(... dynamic fields ...)</color>
}
@enduml
```
I've checked the documentation and doesn't seem to mention any exception for the  **agent** component

**Comment by The-Lum** [comment]
Hello @fflatorre,

For that you must use `allow_mixing` or `allowmixing` command, as:
```puml
@startuml
allow_mixing
agent agentName
object objectName
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhCoSalZy_DhCZCI-TAJ4_DAr40atw9kQbS-KbPgSab2c0A8kAGcfS2r0O0)](http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuKhCoSalZy_DhCZCI-TAJ4_DAr40atw9kQbS-KbPgSab2c0A8kAGcfS2r0O0)

And:
```puml
@startuml
allow_mixing
agent agentName
entity TestEntity << (V,#EEEEEE) >>  #line.dotted:purple;back:lavenderblush {
 <i><color:SlateGray><i>(... dynamic fields ...)</color>
}
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/9OenQyCm48Lt_Oe3BpOKTNU5y6AwTMdfMixMrH4vIKOw9J4X_pt6USDxZuzlA89PQc25pEdw5_pDnqNXGb7Ww2yCfFRrii4F5HbVrnXeVz-QyKW7rW8qx2DfbqJ8zMlDAzF7XFEvPxnGT9GdhkK4TmN6MpCdJhd_PXJwpBZPdRLQQt1RnE1d-FV4hi2EElD-o5Ozr43HrS1F)](http://www.plantuml.com/plantuml/umla/9OenQyCm48Lt_Oe3BpOKTNU5y6AwTMdfMixMrH4vIKOw9J4X_pt6USDxZuzlA89PQc25pEdw5_pDnqNXGb7Ww2yCfFRrii4F5HbVrnXeVz-QyKW7rW8qx2DfbqJ8zMlDAzF7XFEvPxnGT9GdhkK4TmN6MpCdJhd_PXJwpBZPdRLQQt1RnE1d-FV4hi2EElD-o5Ozr43HrS1F)

See ref. here:
- https://forum.plantuml.net/2335/use-of-actor-inside-class-diagrams
- https://forum.plantuml.net/8086/allow-mixing
- https://forum.plantuml.net/search?q=allow_mixing

_If that can help,_
Regards.

**Comment by fflatorre** [comment]
Awesome ! Thanks a lot @The-Lum for the prompt response.

I was looking at the reference guide and tried to search for errors related to agents, but all these pages refer to actors and it's really not easy to get to the bottom of the problem, set aside the limited info from the error message :) 

Hope people will find this issue useful too !
