### ISSUE TITLE
Regression in skinparam participant<<stereo>> behavior losing styling

### ISSUE THREAD

**Issue by hakanson** [plantuml/plantuml#1023]
*Based on issue https://github.com/awslabs/aws-icons-for-plantuml/issues/44 (see that for additional details)*

When building out a minimal, standalone example for that issue, I uncovered the regression relates to behavior changes with `skinparam participant<<stereo>>` which is triggered in aws-icons-for-plantuml by `AWSEntityColoring(APIGateway)` then using `<<APIGateway>>` as a participant stereotype (e.g. `participant OnlyLabel as p1 << APIGateway >>`). It appears the sprite and stereotype label are "styled out" of the rendering.

The render
![Sequence Diagram - Spots and stereotypes](https://user-images.githubusercontent.com/414500/171028815-9c370565-7a05-4e2e-802e-a9f4bd4943ae.png)

Workarounds were either to prefix the stereotype label with a [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) (e.g `%chr(8203)`) or to add `!define AWSEntityColoring(stereo)` after you include AWSCommon.puml and just use default styling.

```
@startuml Bug - Sprites and Stereotypes
' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)

'''AWSEntityColoring usually defined in AWSCommon.puml
!define AWS_BG_COLOR #FFFFFF
!define AWS_BORDER_COLOR #FF9900

!definelong AWSEntityColoring(stereo)
skinparam participant<<stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}
!enddefinelong
'''

'The bug happens because of the AWSEntityColoring(APIGateway) from APIGateway.puml
'A workaround is to redefine to do nothing - uncomment line below to test
'!define AWSEntityColoring(stereo)

'''$APIGateway and AWSEntityColoring(APIGateway) defined in ApplicationIntegration/APIGateway.puml
sprite $APIGateway [64x64/16z] {
xTC5biCm30JGiIfRqjp_lcMkqWqjUzuBvvlDjTFJ4uqlQJ5QA-1yYWCQOtNkan9IBTOotqoI4X9DvfvCIaZqi4zAIFImVrT2E-lt_bn2oxnpdAV_V2zIgG_7
D5-ASlDm_CZ-_tplDji7IIgSCSjRSP95wCLcUCF16ngzm2Rx4-S6mMC1Ktqv3G4s9r2c-We9ii98Xg1EzJmMKCgPSx9dXJagIKFb34-ddjuvPta6PDdwTP_d
-_ut3yRzOTCye9I7OvhNQcptXtxa-_n1ROmtHURP1ESYXlmPGnhJH1MWg0rvqm98ZOG-5Y6PbmHdyIf8_04xnyMpyNMkdPwU7G
}

AWSEntityColoring(APIGateway)
'''

actor User as user
participant OnlyLabel as p1 << APIGateway >>
participant NoLabel as p2 << ($APIGateway, #CC2264) >>
participant Both as p3 << ($APIGateway, #CC2264) APIGateway >>
participant BothZWSP as p4 << ($APIGateway, #CC2264) %chr(8203)APIGateway >>

user -> p4: renders as expected
@enduml
```

**Comment by arnaudroques** [comment]
Thanks for the report, this should be fixed [with last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).
Tell us if it does not work for you.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @hakanson for the report.
- Thanks PlantUML team for your work.
	
Regards.
