### ISSUE TITLE
How to install plantuml on Windows-10?

### ISSUE THREAD

**Issue by it19862** [plantuml/plantuml#1029]
How to install plantuml on Windows-10?

**Comment by soloturn** [comment]
maybe try chocolatey:
https://www.youtube.com/watch?v=7Cp2LS9eE3c

then:
https://community.chocolatey.org/packages/plantuml

**Comment by soloturn** [comment]
ah, very good how you docuented this! first time i see what happens on windows :) all looks good, you open a puml file and it will generate a diagram. the syntax is described here, e.g. use case diagrams:
https://plantuml.com/use-case-diagram#d50d8f9219a41435

online you can try here:
http://www.plantuml.com/plantuml/uml

**Comment by it19862** [comment]
@soloturn 
I don't understand...

I have completed:
- I am switching to the Windows desktop;
 - I'm doing a shortcut click;
 - the program opens. (See the program interface in my last post above).


**Question:** How do I open a program that will have an interface like `plantuml` online?
http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

I want to see two panels: 
- panel with uml code;
- panel where the chart is displayed;

**Comment by OveQ** [comment]
> I want to see two panels:
> 
> * panel with uml code;
> * panel where the chart is displayed;

From my understanding you would want Visual studio code, with plantUml plugins. That gives you exactly this, with a uml editor on the left side, and when you hit "alt+d", you get the UML generated on the side.

**Comment by The-Lum** [comment]
Otherwise, you can split your screen in two and have:
- your favorite editor, on one side;
- and the `plantuml.jar`'s GUI image output, on the other side...

Regards.

**Comment by The-Lum** [comment]
See also this page, and search your favourite or better solution:
- https://plantuml.com/running

Regards.

**Comment by it19862** [comment]
@The-Lum @OveQ 

can't plantuml be used as a separate application?

In other words, should plantuml be used as a plug-in to other applications?
Plugin for applications such as Visual Studio, Visual Studio Code, PhpStorm?
Yes?

**Comment by OveQ** [comment]
> @The-Lum @OveQ
> 
> can't plantuml be used as a separate application?
> 
> In other words, should plantuml be used as a plug-in to other applications? Plugin for applications such as Visual Studio, Visual Studio Code, PhpStorm? Yes?

I run plantUml as a docker container.
Then I install a plugin for VS Code, and set that to use the docker container as a server. That way I don't need the local installation that is flagged as a virus, and my local computer is quite clean.

**Comment by evantill** [comment]
@it19862 have you found a solution ?

**Comment by evantill** [comment]
Stay tuned ! We are think about releasing a native application (`.exe`)

see https://github.com/plantuml/plantuml/issues/1344

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @it19862  for the report.
- Thanks PlantUML team for your work.

Regards.
