### ISSUE TITLE
Question about version on `snapshot` and adding _pseudo_ version of `snapshot`

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1032]
Hello all,

- Why, on each [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot),  the version on [plantuml-SNAPSHOT.pom](https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.pom) is always `1.2022.1-SNAPSHOT`?

_[Hints: it seems taken from [gradle.properties](https://github.com/plantuml/plantuml/blob/master/gradle.properties)]_

- Is it possible to add a pseudo version _(even if there is not updated on each snapshot)_ of [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot)?

_I can propose a PR..._
_(To debate even if this pseudo version (named for example ~v) is not updated on each snapshot...)_

**Comment by soloturn** [comment]
hi @The-Lum , thanks for the change of the version! i was wondering if it would make sense to have:
```
plantuml-1.2022.5-<git-hash>.jar
```
instead of:
```
plantuml-M.YYYY.m-SNAPSHOT.jar
```
?

**Comment by The-Lum** [comment]
Hello @soloturn,

- Why not?
- But: where have you observed `plantuml-M.YYYY.m-SNAPSHOT.jar`?
It seems we have _nowadays_ only `plantuml-SNAPSHOT.jar`...
And my modification is only on the `pom` file to have: `M.YYYY.mmbetaBB-SNAPSHOT`...
_See for example: [plantuml-SNAPSHOT.pom](https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.pom)_

And an absolute link, with `/snapshot/plantuml-SNAPSHOT.jar`,  as:
- [plantuml-SNAPSHOT.jar](https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.jar)
is also **appreciated**... _(to avoid to search on https://api.github.com/repos/plantuml/plantuml/releases/tags/snapshot)_

_If I understand your remark... To exchange and debate..._

**Comment by The-Lum** [comment]
_Ah, I seem to understand..._
On [`plantuml-SNAPSHOT-module.json`](https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT-module.json), we observed: `plantuml-M.YYYY.mmbetaBB-SNAPSHOT.jar`.

But with:
- https://github.com/plantuml/plantuml/blob/6a51780588417c125b87570a31e02f37d3d59cf9/.github/scripts/release-snapshot.sh#L17-L22

Those files are renamed...

_If that can help for understanding..._
