### ISSUE TITLE
Arrows overlapping boxes in activity diagram with swimlanes

### ISSUE THREAD

**Issue by ahmadeus** [plantuml/plantuml#1040]
Hi,

In an activity diagram with swimlanes, sometimes an arrow that goes from one swimlane (User) to another one (Component) overlap a box in the same swimlane (User : from "Act 04" to "Cond C") or in the other swimlane ("User" : from "Cond C" to "Act 05").
Here's the result an the code.
Is there any what to avoid that?
Thanks!

@startuml

'skinparam conditionStyle InsideDiamond
'skinparam ConditionEndStyle diamond
skinparam ConditionEndStyle hline
skinparam wrapWidth 150

|User|
start
:Act 01;
:Act 02;

|Component|
if (Cond A) then (No)
	|User|
	:Act 03;
	kill
else (Yes)
	|Component|
	if (Cond B) then (No)
		|User|
		:Act 04;
		
		|Component|
		if (Cond C) then (No)
			|User|
			:Act 05;
			kill
		else (Yes)
			|Component|
			:Act 06;
		endif
	else (Yes)
		if (Cond D) then (Yes)
			|User|
			:Act 07\nSome big text\nMultiple lines;
		else (No)
	endif
endif

|User|
:Act 08;
kill
 
@enduml
![overlappingact](https://user-images.githubusercontent.com/46747822/174077439-41ec97de-3e88-418d-a46d-bf803dcffde8.png)

**Comment by The-Lum** [comment]
Hello @ahmadeus,

>Is there any what to avoid that?

Here is a _current_ workaround by using dummy `label` just before `Act 04`, as:

```puml
'...
|Component|
if (Cond B) then (No)
|User|
label l
label l
label l
label l
:Act 04;

	|Component|
	if (Cond C) then (No)
		|User|
		:Act 05;
'...
```

>[![](http://www.plantuml.com/plantuml/svg/TP11JyCm38NFoQ_mSRrjm03HoqRX29S98QHTEkfHQwvJDQu0gJ-UKYoKeN59hFZvUozUHIqxxHlsyK3IbbtPG16a8gKWzr9jz9CHQYR1HF7UbUqpLLh3OZdtVdYAs0r-GlcRzQl2V95RSPQF_I8qRH0K7JpjOVPj0EiCj4Q1sMF8Z60Zvxa_4BD7ZWYp5upPQSBj2GANEsJW_svpk1X3kPJfVg552dNEiCxz32xpiPp2kIITEsQPzdBKebIqJpwI6DsPaRt_TRhQoYOq23jw0yKFtSf3pqej8p09njmIJ3dDPZgFTtbjkroDpRxXBm00)](http://www.plantuml.com/plantuml/uml/TP11JyCm38NFoQ_mSRrjm03HoqRX29S98QHTEkfHQwvJDQu0gJ-UKYoKeN59hFZvUozUHIqxxHlsyK3IbbtPG16a8gKWzr9jz9CHQYR1HF7UbUqpLLh3OZdtVdYAs0r-GlcRzQl2V95RSPQF_I8qRH0K7JpjOVPj0EiCj4Q1sMF8Z60Zvxa_4BD7ZWYp5upPQSBj2GANEsJW_svpk1X3kPJfVg552dNEiCxz32xpiPp2kIITEsQPzdBKebIqJpwI6DsPaRt_TRhQoYOq23jw0yKFtSf3pqej8p09njmIJ3dDPZgFTtbjkroDpRxXBm00)

Enjoy, 🎉 
Regards.

**Comment by ahmadeus** [comment]
Hi @The-Lum ,

Thanks for the workaround !
I didn't know labels could be used that way.
Have a nice day.
