### ISSUE TITLE
Cannot change surrounding characters in sequence diagram secondary label

### ISSUE THREAD

**Issue by TTWNO** [plantuml/plantuml#1044]
I use plantuml to create accessible diagrams for the blind.
I am a developer by trade, so I can fix smaller problems. Not sure what the difficulty of something like this would be.

To successfully create diagrams with braille (a tactile writing system for the blind), I need *all* text on the diagram to be in braille. Having a character or two that doesn't convert would be the same as having a few Chinese characters in an English diagram and expecting a student to understand.
This hasn't been a problem for the last few months as I got familiar with plantuml. It's amazing work!

Today, while creating a more advanced sequence diagram than I have previously, I tried to set the secondary group label to "⡪⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⡕⡅⡻", "[authorization OK]" in braille.

the labels of the sections, i.e. "[authorization OK]" and "[authorization error]" always print the exact left and right bracket characters, it appears I can't change or get rid of them.
So to a blind student, reading this diagram for the first time, the text for that group may look something like "哦[authorization OK]娜" because the physical shape of the bracket character has no meaning.

Is there a way to change, or remove the surrounding characters? i.e. [ and ]

PlantUML code, original diagram included below:

[braille_diagram.txt](https://github.com/plantuml/plantuml/files/8931468/braille_diagram.txt)
![20220617_15h36m11s_grim](https://user-images.githubusercontent.com/44244401/174405300-aac9c759-e70f-413f-9238-8f92bd79b75e.png)

**Comment by The-Lum** [comment]
Hello @TTWNO, and all,

A funny half workaround, is to adding `<color:white>` at the end of the `alt` and `else` expression, just to suppress the ending bracket `]` as:

```puml
@startuml
!theme plain

participant "⡏⠱⠀⡏⠁⠞⠊⠑⠝⠞⡊⠝⠋⠕" as pi
participant "⡙⠱⠀⡍⠑⠝⠞⠉⠁⠗⠑⠤⡙⡃" as db

group ⠁⠇⠞ [⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⡕⡅<color:white>]
  db --> pi: ⡏⠁⠞⠊⠑⠝⠞⠀⠊⠝⠋⠕
else ⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⠋⠁⠊⠇<color:white>
  db --> pi: ⡑⠗⠗⠕⠗⠀⠷⠝⠕⠀⠁⠉⠉⠑⠎⠎⠾
end

@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/ZP51IWD144NtTOeo-rmWICWznCMODAPXCjFCT71h40c9g8WCmKMa6lG0BiITXwcJMFr11eEBG35yYl_-dw8dRIoQk5oKT1BdRk4ub8MlY89j_TI7eeeyqFIeyg5o3R5IULNPgZofxBDEMuWxbMx0HSl17-8ll_XzJya6KJjith8dtG2VNH1TDlKoC0nhC_CPv3kuP-i1PxMV_U_avHubdQRRqsbTriteQkwZ6vyJMoeFXsCEViJ_Ns6az8UGArl7nxU2Mc6p_jDzM6rrkpn80_Y5XCuq4ZOOiprWlibLCwA9VUsLVW00)](http://www.plantuml.com/plantuml/uml/ZP51IWD144NtTOeo-rmWICWznCMODAPXCjFCT71h40c9g8WCmKMa6lG0BiITXwcJMFr11eEBG35yYl_-dw8dRIoQk5oKT1BdRk4ub8MlY89j_TI7eeeyqFIeyg5o3R5IULNPgZofxBDEMuWxbMx0HSl17-8ll_XzJya6KJjith8dtG2VNH1TDlKoC0nhC_CPv3kuP-i1PxMV_U_avHubdQRRqsbTriteQkwZ6vyJMoeFXsCEViJ_Ns6az8UGArl7nxU2Mc6p_jDzM6rrkpn80_Y5XCuq4ZOOiprWlibLCwA9VUsLVW00)

Then here is another workaround:
```puml
@startuml
!theme plain

participant "⡏⠱⠀⡏⠁⠞⠊⠑⠝⠞⡊⠝⠋⠕" as pi
participant "⡙⠱⠀⡍⠑⠝⠞⠉⠁⠗⠑⠤⡙⡃" as db

group ⠁⠇⠞ [\t⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⡕⡅<color:white>]
  db --> pi: ⡏⠁⠞⠊⠑⠝⠞⠀⠊⠝⠋⠕
else \t\t⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⠋⠁⠊⠇<color:white>
  db --> pi: ⡑⠗⠗⠕⠗⠀⠷⠝⠕⠀⠁⠉⠉⠑⠎⠎⠾
end
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/bP51IWD144NtTOeo-rmWICWzZ8inQKn3PwQPwU3M818IKGao11UHQj03k11t7gPEOkL330OtGZFKVFxxluiUDAceqsmQw2HDtDHn38KlYQAfVkHZKIRkQ7vKULUvnZ1NUL5PgQnLjhivhp3SgRGTBXgE_XX_tkFt1qgMYDf0UTrvyWtmyGNHPLtD8iEmC3EV3HD-ta0-MHD8A_xukH34BMfQpRUdeofKTUzgufFhdnDRBdUxVRjTZ__UmqWvh48kD8w7wJ_D8ETG5h_wZ-lN2DdiqmpyH49hCnAME6PxmFaYLuvfO1zxgcy0)](http://www.plantuml.com/plantuml/uml/bP51IWD144NtTOeo-rmWICWzZ8inQKn3PwQPwU3M818IKGao11UHQj03k11t7gPEOkL330OtGZFKVFxxluiUDAceqsmQw2HDtDHn38KlYQAfVkHZKIRkQ7vKULUvnZ1NUL5PgQnLjhivhp3SgRGTBXgE_XX_tkFt1qgMYDf0UTrvyWtmyGNHPLtD8iEmC3EV3HD-ta0-MHD8A_xukH34BMfQpRUdeofKTUzgufFhdnDRBdUxVRjTZ__UmqWvh48kD8w7wJ_D8ETG5h_wZ-lN2DdiqmpyH49hCnAME6PxmFaYLuvfO1zxgcy0)

_Just for fun,_
Awaiting fully bracket management... 
@PlantUML team: perhaps add a new parameter to toggle showing or not. `[`/`]` ...

Regards.

**Comment by TTWNO** [comment]
Interesting! So there is a way to hide the second bracket, but not the first? I even tried using `<color:white>` before the `[...]` expression and no dice!

Perhaps this is secretly a skinparam, maybe an undocumented one? I'll poke around the source and see what I can find.

**Comment by The-Lum** [comment]
Hello @TTWNO, and all,

Finally here is a real workaround, adapted from:
- https://forum.plantuml.net/15249/how-can-center-the-title-for-an-alt-block-in-sequence-diagram

with:
```puml
@startuml
!theme plain
<style>
sequenceDiagram  {
  group {
    FontColor transparent
  }
}
</STYLE>

participant "⡏⠱⠀⡏⠁⠞⠊⠑⠝⠞⡊⠝⠋⠕" as pi
participant "⡙⠱⠀⡍⠑⠝⠞⠉⠁⠗⠑⠤⡙⡃" as db

group ⠁⠇⠞ [<color:#0>⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⡕⡅</color>]
  db --> pi: ⡏⠁⠞⠊⠑⠝⠞⠀⠊⠝⠋⠕
else <color:#0>⠁⠥⠞⠓⠕⠗⠊⠵⠁⠞⠊⠕⠝⠀⠋⠁⠊⠇</color>
  db --> pi: ⡑⠗⠗⠕⠗⠀⠷⠝⠕⠀⠁⠉⠉⠑⠎⠎⠾
end
@enduml
```

Here is the expected result:
>[![](http://www.plantuml.com/plantuml/svg/dP7FIiD04CRlynHZFPTwBY4K_7FofXSH3sixr42oYRkRWqZ18b9QKIaIn4Db0_e07iIR3xDFucIW18edOGWV7_Fxvbioi4uPLsOfRBaBoWYBL2KQ8kkkKeh1qcL9UaXxYHeRbI5U0-BOv6KX2l4WrsutJtE3pYXj2sL8Eq2Sm0IYtj7noU5-3C2sIuP9eRJ3JgYVWlyC_aR4DFYtu1V1BuDVDRfUYBWFlkgWibWac_Zh6dzeAJ-Ng1TntfkT-bRmqJc054PPcF4odaR3fd9_UoSMyqCIdlaY9qYPhxPOOwxaN1NgkwWdQ7m6oD7OxSPSi8z_FuKXtxu6ABM4_paj_5ISsRh0vlsby3nDa33V0bUi1PxByDgZp0-G7i60F_ppVm40)](http://www.plantuml.com/plantuml/uml/dP7FIiD04CRlynHZFPTwBY4K_7FofXSH3sixr42oYRkRWqZ18b9QKIaIn4Db0_e07iIR3xDFucIW18edOGWV7_Fxvbioi4uPLsOfRBaBoWYBL2KQ8kkkKeh1qcL9UaXxYHeRbI5U0-BOv6KX2l4WrsutJtE3pYXj2sL8Eq2Sm0IYtj7noU5-3C2sIuP9eRJ3JgYVWlyC_aR4DFYtu1V1BuDVDRfUYBWFlkgWibWac_Zh6dzeAJ-Ng1TntfkT-bRmqJc054PPcF4odaR3fd9_UoSMyqCIdlaY9qYPhxPOOwxaN1NgkwWdQ7m6oD7OxSPSi8z_FuKXtxu6ABM4_paj_5ISsRh0vlsby3nDa33V0bUi1PxByDgZp0-G7i60F_ppVm40)

_Enjoy, 🎉 
If that can help,_
Regards.
