### ISSUE TITLE
Characters "«" and "»" not allowed in participant titles (sequence diagrams)?

### ISSUE THREAD

**Issue by TTWNO** [plantuml/plantuml#1045]
I'm creating a sequence diagram with the string "«datastore»" as part of a participant title.

Having other unicode characters don't seem to have a problem: ❤️ (red heart) works, even!
But for some reason, once I use the "«" (U+00AB) or "»" (U+00BB), either of the "french quotation marks", the diagram fails to load, citing an issue with the line where the characters appear.

Perhaps I did something else that messed it up, but I can't figure out why these characters of all of them happen to cause issues, while others don't.

```
@startuml
!theme plain

actor "Purchase Officer" as po
participant ":Order" as o
participant "Budget" as b
participant "«datastore»\nOrders" as d_o
actor "Supplier" as sup

@enduml
```

Current workaround is the use "<<" and ">>" as placeholders.

**Comment by noderat** [comment]
Looks like this was fixed in [V1.2022.7 (22 Aug, 2022)](https://plantuml.com/changes) but nobody ever came back to close this issue.
