### ISSUE TITLE
Slanted arrow doesn't work from command line

### ISSUE THREAD

**Issue by IvanPizhenko** [plantuml/plantuml#1046]
Testing with latest at the moment stable version: `plantuml-1.2022.5.jar`
Following example:
```
@startuml
A ->(10) B: text 10
B ->(10) A: text 10

A ->(10) B: text 10
A (10)<- B: text 10
@enduml
```
from [Sequence Diagram Documentation](https://plantuml.com/en/sequence-diagram) doesn't work from command line:
```shell
$ java -jar plantuml-1.2022.5.jar slanted.txt
Error line 2 in file: slanted.txt
Some diagram description contains errors
```

But the same works online on the site: [See online](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuN9KqBNJC3JGL72oKYX9hIXHC3JWSeA9EIB4i2fqL029sEWYYpcavgM030O0)
Please fix.

**Comment by The-Lum** [comment]
Hello @IvanPizhenko, and all,

You are right. This is not yet released...
Only on the snapshots after 17th May:
- https://github.com/plantuml/plantuml/releases/tag/snapshot

Regards.

**Comment by IvanPizhenko** [comment]
@The-Lum Thank you for explanation! I have a question - when there is a chance to have a next release version, which will include this?

**Comment by The-Lum** [comment]
I don't know. But usually there is a release at least once a month...

In the meantime you can use a snapshot version:
- https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.jar

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This issue can be closed.
- Thanks @IvanPizhenko for the report.
- Thanks PlantUML team for your work.

Regards.
