### ISSUE TITLE
Map can not set  color of line -> I want to set red on the black (like crt-green) but for specific elementes not all.

### ISSUE THREAD

**Issue by ChameleonRed** [plantuml/plantuml#1047]
Here is example of code:
```
@startuml
map commit #red {
  sha256 => 1
}
class x #red ##pink {
}
map commit1 #red ##pink {
  sha256 => 1
}
map commit1 #line:red {
  sha256 => 1
}
@enduml
```

I can not set colors for individual maps I want to color `line`, `font` not `background only`.

I can use skinparam but I cannot apply without use <<stereotypes>> to specific elements (I do not want to make visible stereotypes).
No idea how to apply colors with overcrowding skinparams - it need be done before every element.

Inline style is probably the best but also can be some selectors to apply style.

**Comment by arnaudroques** [comment]
Online version now [allows this](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSfDB518pi_DpImnL50kpyWiILMevb9GACv8D38rKx2rKp3agkLApaaiBbQeW2bGLYx8pCi6ggj5qcw49ejf2aAjiO9oJcPUgbLHQWeMTGwfUIb0fm40).
Is this what you are expecting?

**Comment by ChameleonRed** [comment]
It is exactly what is need.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed _(by inline style or style)_, as:
```puml
@startuml
hide stereotype
<style>
.test  {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
}
</style>
map commit1 #aliceblue {
  sha256 => 1
}
class x #aliceblue ##pink {
}
map commit2 #aliceblue ##pink {
  sha256 => 1
}
map commit3 #line:red {
  sha256 => 1
}
map commit4 <<test>> {
  sha256 => 1
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/VP31QiCm38RlVWf1xksQhJkCB7Ghx5HwsWjeZcXCP3lO2cieVVSfQw1bb5q_VVxrMviic6JmR5hN46IXH576daoLPMIgpK8e2y390EnSe6tacE2B1rBmZhOxf3Y4veBP7LhPZXXc-RDrjWkKCvHAtbAAtrVqi5Wh_8X1zkX9fmuPzZX9Cx-49chCsLJBkO_77cpqtiaA2cHdQIhpso-tMAwVuRM6bRwmZBhbU2iLHUz2f-xv9gQyQ_nDk_gFKB3-xKLx_UizGLLDjwlhEzg6GgDN_m40)](https://www.planttext.com/?text=VP31QiCm38RlVWf1xksQhJkCB7Ghx5HwsWjeZcXCP3lO2cieVVSfQw1bb5q_VVxrMviic6JmR5hN46IXH576daoLPMIgpK8e2y390EnSe6tacE2B1rBmZhOxf3Y4veBP7LhPZXXc-RDrjWkKCvHAtbAAtrVqi5Wh_8X1zkX9fmuPzZX9Cx-49chCsLJBkO_77cpqtiaA2cHdQIhpso-tMAwVuRM6bRwmZBhbU2iLHUz2f-xv9gQyQ_nDk_gFKB3-xKLx_UizGLLDjwlhEzg6GgDN_m40)

- Thanks @ChameleonRed for the report.
- Thanks PlantUML team for your work.

Regards.
