### ISSUE TITLE
wrapWidth don't work in Activity Diagram

### ISSUE THREAD

**Issue by tuliolima** [plantuml/plantuml#1052]
Hello, is there a prediction of when `wrapWidth` will works with Activity diagrams in official release, like it works in beta?

**Comment by The-Lum** [comment]
Hello @tuliolima,

Yes, for that now use `style` _(instead of `skinparam`)_ and `MaximumWidth`, as:
```puml
@startuml
<style>
element {
  MaximumWidth 100
}
</style>

start
:this is a very long component description;
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/BOr12i9034NtESM_WNMhHNe1rww7Jh21IQPCKh68TtSKuI__Us_oI2qsBJHwx8Kln8MLBV0Yu9gUeflU9CU2up3GcyR3_qS_aawnYACluS5jHwbsnrnrhVQrPFQvoHfIxKmJM-wf3m00)](http://www.plantuml.com/plantuml/uml/BOr12i9034NtESM_WNMhHNe1rww7Jh21IQPCKh68TtSKuI__Us_oI2qsBJHwx8Kln8MLBV0Yu9gUeflU9CU2up3GcyR3_qS_aawnYACluS5jHwbsnrnrhVQrPFQvoHfIxKmJM-wf3m00)

See doc. here:
- https://plantuml.com/en/style-evolution#faebbd3c7bf835b5

Regards.

**Comment by tuliolima** [comment]
It worked to me. Thanks a lot, @The-Lum !
