### ISSUE TITLE
Bug: SVG generate embedded image

### ISSUE THREAD

**Issue by davidyew** [plantuml/plantuml#1053]
Hi! Since [v1.2022.5](https://github.com/plantuml/plantuml/releases/tag/v1.2022.5), the SVG generation is inconsistent.
I have links for the SVG that become non-clickable because the section was being converted as base64 image and embedded in the SVG.

Here is the [sample](https://planttext.com/?text=bP9HQuCm58NVyoiokuSDfhwFKXfS7uIs4xKFGsH43HeQeoJNZIB-zwKjhOxHGT_koJt9TtEIfGQgeAi5Uk0o5rt1EYLm1T3gLzTLzDifELHTrcccyaO2a-3aJUsoB3kq39XoYSehNbDWTY2eXDrcxTPK_-euxH605Ck1ob8m77dXRXFuwpK98poVFzABqwqRu5yKU2FjLfc9U2lOOc4yDngppNKT9yYASjNLEE12KAKjrFS8OxtdigMArZYZ-RvKJISBhn6Dccuslb5y1XV2KnoIRHIGSBNrFbwmbIINQFIHL7QyODffL7dMzcd1gQ0MCr1KQiDbCZ_WFfwe0KzLcbhFj-Y-OQ-ys7_VtiVcvdGJzZ6Kth_M0nxh_wZaZGGnkPzA2zh2-IbwSgq7FDOdgi5EKyLsKl6YO39LlAp0nkEbZNCKVtpZc0WF0qeHMZ9Pc9_s0m00) that I am working on.

**Comment by arnaudroques** [comment]
This is a side effect of [some security fix](https://huntr.dev/bounties/27db9509-6cd3-4148-8d70-5942f3837604/).

For the record, here is a [simplified example that show the issue](https://www.plantuml.com/plantuml/uml/TOzDQuD048Rl-oi6qslYlOGGaHw4n8ZQGX4FqtNH9ViXisEXYF-zQGF1IuxFCn-yxp4m4a_M25AIqVL6GPMMx-SYEvsIieBz_WL93jeYgzXwrj_8shljIDf9FHfrEDnsdWmsvuU7HaILfCb2eOr12f6OPm4GhjgDI6ZX2-Mr9p-vBlN6q_fO03n2tFobpZwIEhla43NDm3o6rpWEVy_xINSgx3prTzx-Yzt0rcoOq8KHIJdv0tEzeWNMrBRHyqOOe2wJl2gIyYrFFuM0PH6jE2hNJTRy0W00). (and [SVG here](https://www.plantuml.com/plantuml/svg/TOzDQuD048Rl-oi6qslYlOGGaHw4n8ZQGX4FqtNH9ViXisEXYF-zQGF1IuxFCn-yxp4m4a_M25AIqVL6GPMMx-SYEvsIieBz_WL93jeYgzXwrj_8shljIDf9FHfrEDnsdWmsvuU7HaILfCb2eOr12f6OPm4GhjgDI6ZX2-Mr9p-vBlN6q_fO03n2tFobpZwIEhla43NDm3o6rpWEVy_xINSgx3prTzx-Yzt0rcoOq8KHIJdv0tEzeWNMrBRHyqOOe2wJl2gIyYrFFuM0PH6jE2hNJTRy0W00))

Unfortunately, that does not sound easy to fix...
Does anyone know if there a way to let `<image>` take into account that `xlink:href="data:image/svg+xml;base64` has itself some hyperlinks?

Are you using PlantUML from a webserver or from a local script?

**Comment by davidyew** [comment]
Hi @arnaudroques ,
I am using PlantUML via local script

**Comment by arnaudroques** [comment]
Using [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot), you can run your local script using `UNSECURE_MODE `(see https://plantuml.com/en/security ).

Your links should be working then. Tell us if it's not working for you!

**Comment by davidyew** [comment]
Hi @arnaudroques ,

Yes, it is working! Thank you!

In my context, my command line is as java -DPLANTUML_SECURITY_PROFILE=UNSECURE -jar .\plantuml-SNAPSHOT.jar .\test.puml -Tsvg


> Using [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot), you can run your local script using `UNSECURE_MODE `(see https://plantuml.com/en/security ).
> 
> Your links should be working then. Tell us if it's not working for you!

**Comment by mcraveiro** [comment]
This appears to work with release ```plantuml-1.2022.12.jar```.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @davidyew for the report.
- Thanks PlantUML team for your work.

Regards.
