### ISSUE TITLE
Namespacing breaks drawing relationships to members

### ISSUE THREAD

**Issue by ChristinWhite** [plantuml/plantuml#1063]
When drawing relationships to members within an item in another namespace PlantUML fails to parse `namespace.class::member` correctly and creates a separate `class::member` item instead. 

```plantuml
@startuml
namespace foo {
    class bar {
        field
    }
}

enum bin
foo.bar::field .right. bin
hide empty members
@enduml
```

Here's what I expect to see:

```
+-----+
| foo  \
+-------+---------+
|                 |
|   +---------+   |
|   | (C) bar |   |
|   +---------+   |   +---------+
|   | field   |---|---| (E) bin |
|   +---------+   |   +---------+
|                 |
+-----------------+
```

What I actually see is this:

```
+-----+
| foo  \
+-------+------------------------------+
|                                      |
|   +---------+   +----------------+   |   +---------+
|   | (C) bar |   | (C) bar::field |---|---| (E) bin |
|   +---------+   +----------------+   |   +---------+
|   | field   |                        |
|   +---------+                        |
|                                      |
+--------------------------------------+
```

This problem also happens if you use an automatic namespace instead of within an embedded one with `class foo.bar`. 

This is not a problem if both `bar` and `bin` are within the same namespace. It does happen if `bin` is in a different namespace like `bash.bin`. Packages instead of namespaces handle this correctly.

This could be related to #633 with creating notes on members but the behavior isn't entirely consistent with this issue.

**Comment by The-Lum** [comment]
Hi @ChristinWhite, and all,

FYI: that is now fixed with last changes on `namespaces` and `packages` _(see [news](https://plantuml.com/en/news))_.

See expected result:
```puml
@startuml
namespace foo {
    class bar {
        field
    }
}

enum bin
foo.bar::field .right. bin
hide empty members
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/BOwn2iCm34HtVOMMGhkuhRjbog_8iT8OB3lOIg2K_7iTqzkEzmvkh4f5DucGIBYkD37EEUCNi6MAL2iwAlz-PWuSVMy7702SDa4N4hILQUOmT05D2Uz5JKTBy8migtvGM1oNUjhA1P_6FkpBMCTA5kzusHiCELrlC7BoxTSF)](https://www.planttext.com/?text=BOwn2iCm34HtVOMMGhkuhRjbog_8iT8OB3lOIg2K_7iTqzkEzmvkh4f5DucGIBYkD37EEUCNi6MAL2iwAlz-PWuSVMy7702SDa4N4hILQUOmT05D2Uz5JKTBy8migtvGM1oNUjhA1P_6FkpBMCTA5kzusHiCELrlC7BoxTSF)

Thanks to the PlantUML team for the works. 👍 
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @ChristinWhite for the report.
- Thanks PlantUML team for your work.

_Will only remain the output enhancement of [ASCII Art (atxt or utext)](https://plantuml.com/en/ascii-art) format..._

Regards.
