### ISSUE TITLE
Allow to add the same note to multiple classes

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml#107]
For example, `note right of MainWindow` would add this note to `MainWindow` and this bellow:
```
  note right of MainWindow, AddObjectWindow
    This is the model viewer
    and it is an observer
    of the model
    (presentation logic)
  end note
```
Would add the same note to both `MainWindow` and `AddObjectWindow`. But not duplicating the notes, just creating one note and with two lines, one for each class.

**Comment by mhaaz** [comment]
Try the following:

```
note as MyNote
    This is the model viewer
    and it is an observer
    of the model
    (presentation logic)
  end note
MainWindow -- MyNote
AddObjectWindow -- MyNote
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @evandrocoan for the report.
- Thanks @maxaxehax for your answer.

Regards.
