### ISSUE TITLE
Add support for `title` and `footer` to JSON diagram

### ISSUE THREAD

**Issue by diguage** [plantuml/plantuml#1077]
It is recommended to add support for `title` and `footer` to JSON diagram.

**Comment by The-Lum** [comment]
Hello @diguage, and all,

See similar request here:
- [QA-15100](https://forum.plantuml.net/15100/add-a-title-to-a-json-diagram)

With a workaround:
```puml
@startuml
title This is a title

label l [
{{json
{
   "fruit":"Apple",
   "size": "Large",
   "color": ["Red", "Green"]
}
}}
]

footer This is a footer
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JSwn3i8m30JG_Rx2yjmlw5Gc5YR4LdK8r8KWarHEkX3btucAa91kkRVS3IaxozjBaNrMeSl39sfnj7T0tLMKb4QKyamne828UB7DP-xviAugtEsM_5ku9puvk__i5ZLQmv7FCdD7V3IHm1CgQiK4B35ciR_TBs2GCBTR7m00)](https://www.planttext.com/?text=JSwn3i8m30JG_Rx2yjmlw5Gc5YR4LdK8r8KWarHEkX3btucAa91kkRVS3IaxozjBaNrMeSl39sfnj7T0tLMKb4QKyamne828UB7DP-xviAugtEsM_5ku9puvk__i5ZLQmv7FCdD7V3IHm1CgQiK4B35ciR_TBs2GCBTR7m00)

_Then similar request could be ask for **YAML**, **Wire**, ..._
- [QA-14924](https://forum.plantuml.net/14924/wire-allow-title-on-wire-diagram)
-  https://github.com/plantuml/plantuml/issues/700#issuecomment-963616787

_If that can help,_
Regards

**Comment by diguage** [comment]
I test the way, it is OK. Thanks.

But I fount a new problem: my JSON diagram has 250+ fields, so the converted image can not contain the whole, it displays 200+ fields. And the svg image can contain the whole, but the footer was at the 200th field, not at the footer.

```
@startuml
title **Hessian 字节码映射**
caption "D瓜哥 · https://www.diguage.com · 出品"

label l [
{{json
{
  "0x00": "string：+0个字符",
  "0x01": "string：+1个字符",

  // ... about 250+ fileds ...

  "0xFE": "long：[1536, 2047]，+1个字节",
  "0xFF": "long：[1792, 2047]，+1个字节"
}
}}
]

footer D瓜哥 · https://www.diguage.com · 出品
@enduml
```

```bash
$ java -jar plantuml-1.2022.6.jar -tsvg -StitleFontSize=36 -SdefaultFontName='Source Han Serif SC' -SnoteFontSize=20 my.puml
```

![image](https://user-images.githubusercontent.com/2121467/183242296-ccceed57-9d8e-486a-b826-96cd1f9526a8.png)
