### ISSUE TITLE
[Bug] skinparam order sensitive

### ISSUE THREAD

**Issue by xenoterracide** [plantuml/plantuml#1084]
This works correctly
```
skinparam package {
  BackgroundColor LightSteelBlue
}

skinparam node {
  BackgroundColor SkyBlue

}
skinparam cloud {
  BackgroundColor SkyBlue
}

skinparam database {
  BackgroundColor DarkSeaGreen
}

node foo {
  package bar {
  }
}
```

This does not

```
skinparam node {
  BackgroundColor SkyBlue

}
skinparam cloud {
  BackgroundColor SkyBlue
}

skinparam database {
  BackgroundColor DarkSeaGreen
}


skinparam package {
  BackgroundColor LightSteelBlue
}


node foo {
  package bar {
  }
}
```
v2022.6

**Comment by The-Lum** [comment]
Hi @xenoterracide, and all,

- Could you now use `style`?

As:
```puml
<style>
node {
  BackgroundColor SkyBlue
}
cloud {
  BackgroundColor SkyBlue
}
 database {
  BackgroundColor DarkSeaGreen
}
package {
  BackgroundColor LightSteelBlue
}
</style>

node foo {
  package bar {
  }
}
```
>[![](https://www.planttext.com/api/plantuml/svg/ioakgSn9jUFAoqz9LQZcKb1mIapEJY_AByrBSSxFoIzI2CwkTCefJUMgvKhEoIzD8Q168IMn934fiHYxMIw9HTd1gOdkHQcfUK351K3fn7JiIdqoqpDAWajIKtEW9jleGrqASMfQVZvO7yoCfCGYCB-MgnO0)](https://www.planttext.com/?text=ioakgSn9jUFAoqz9LQZcKb1mIapEJY_AByrBSSxFoIzI2CwkTCefJUMgvKhEoIzD8Q168IMn934fiHYxMIw9HTd1gOdkHQcfUK351K3fn7JiIdqoqpDAWajIKtEW9jleGrqASMfQVZvO7yoCfCGYCB-MgnO0)


_Enjoy._

---

See also:
> Unfortunately, we won't fix issues in skinparam. Skinparam are still supported for very simple case (and for ascending compatibility) but we would like people to migrate to style instead. (The main reason is that code for skinparam is too old and not very well written).

On:
- https://github.com/plantuml/plantuml/issues/1464#issuecomment-1601464639

---

Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[Just for the record]_

---

> Unfortunately, we won't fix issues in skinparam. Skinparam are still supported for very simple case (and for ascending compatibility) but we would like people to migrate to style instead. (The main reason is that code for skinparam is too old and not very well written).

On:
- https://github.com/plantuml/plantuml/issues/1464#issuecomment-1601464639

---

Regards,
Th.
