### ISSUE TITLE
The footer is not displayed at the footer.

### ISSUE THREAD

**Issue by diguage** [plantuml/plantuml#1085]
I wanted to find a way to show the title and the footer in the JSON diagram. #1077 gave me a solution. But I found a new problem: **my JSON diagram has 250+ fields, so the converted image can not contain the whole, it displays 200+ fields. And the SVG image can contain the whole, but the `footer` was at the 200th field, not at the footer.**

```
@startuml
title **Hessian 字节码映射**
caption "D瓜哥 · https://www.diguage.com · 出品"

label l [
{{json
{
  "0x00": "string：+0个字符",
  "0x01": "string：+1个字符",

  // ... about 250+ fields ...

  "0xFE": "long：[1536, 2047]，+1个字节",
  "0xFF": "long：[1792, 2047]，+1个字节"
}
}}
]

footer D瓜哥 · https://www.diguage.com · 出品
@enduml
```

```bash
$ java -jar plantuml-1.2022.6.jar -tsvg -StitleFontSize=36 -SdefaultFontName='Source Han Serif SC'  my.puml
```

![image](https://user-images.githubusercontent.com/2121467/183242296-ccceed57-9d8e-486a-b826-96cd1f9526a8.png)

**Comment by arnaudroques** [comment]
Could you post a complete text diagram that shows the issue?
It would help. Thanks!

**Comment by diguage** [comment]
The complete text diagram: [www.diguage.com/hessian-bytecode.puml at master · diguage/www.diguage.com](https://github.com/diguage/www.diguage.com/blob/master/static/diagrams/hessian-bytecode.puml)

The converted diagram: [Hessian 协议解释与实战（五）：对象与映射 - "地瓜哥"博客网](https://www.diguage.com/post/hessian-protocol-interpretation-and-practice-5/#hessian-bytecode)

The command line:

```bash
$ plantuml -v
(0.000 - 520 Mo) 511 Mo - SecurityProfile LEGACY
(0.017 - 520 Mo) 510 Mo - PlantUML Version 1.2022.6
(0.017 - 520 Mo) 510 Mo - GraphicsEnvironment.isHeadless() false
(0.017 - 520 Mo) 510 Mo - Forcing resource load on OpenJdk
(1.701 - 520 Mo) 510 Mo - Found 0 files

$ plantuml -tsvg -SdefaultFontSize=18 -StitleFontSize=36 -SfooterFontSize=20 -StitleFontName='Source Han Sans SC' -SnoteFontName='Source Han Serif SC' -SfooterFontName='Source Han Serif SC'  hessian-bytecode.puml
```

**Comment by gliptak** [comment]
the footer might be placed where the maximum page size is. I'm not sure if/what command line options available to configure larger "canvas"

```
curl -s https://raw.githubusercontent.com/diguage/www.diguage.com/master/static/diagrams/hessian-bytecode.puml | docker run --rm -i ghcr.io/plantuml/plantuml -tsvg -SdefaultFontSize=18 -StitleFontSize=36 -SfooterFontSize=20 -StitleFontName='Source Han Sans SC' -SnoteFontName='Source Han Serif SC' -SfooterFontName='Source Han Serif SC' -pipe > hessian-bytecode.svg
```

**Comment by diguage** [comment]
```bash
$ plantuml -version
PlantUML version 1.2023.0 (Tue Jan 10 02:31:34 CST 2023)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: CN

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 7.0.6 (20230106.0513)
Installation seems OK. File generation OK
```

I test the Version 1.2023.0, it has the same problem.

**Comment by diguage** [comment]
I tested it. It is OK. Thanks
