### ISSUE TITLE
BUG: rendering state with local transition and using StateBackgroundColor style

### ISSUE THREAD

**Issue by jnwtr** [plantuml/plantuml#1090]
When the `StateBackgroundColor` style is applied on a state with a local (internal) transition, the coloring of this state is not the same as for other compound states _without_ local transitions.
For example this code
```
skinparam StateBackgroundColor green
state parent {
    parent --> child
}
```
results in 
![module-test statechart copy](https://user-images.githubusercontent.com/53007721/185591641-bd04a0db-8a5c-4209-884b-ad76ddbb6d2f.png)
while this was expected
![module-test statechart copy](https://user-images.githubusercontent.com/53007721/185592440-3cb1bd79-679b-4e3b-bcaa-f53c00e4ce6e.png)
like the following code
```
skinparam StateBackgroundColor green
state parent {
    child --> child
}
```
results in
![module-test statechart copy](https://user-images.githubusercontent.com/53007721/185593199-6d8db1c6-d229-4c38-9064-c813e9f78adb.png)

**Comment by arnaudroques** [comment]
Thanks for the report.

This has been fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and on the online server.

Tell us if you find other issues!
