### ISSUE TITLE
Arrows <-o] and <-o? are misdrawn as o<-

### ISSUE THREAD

**Issue by jhoehle** [plantuml/plantuml#1093]
The standard rendering engine misdraws right to left arrows <-o? and <-o]
It erroneously draws them to look like o<---- (rather than <----o).

![standard engine bogus output](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuL8iA4fCpqrKA4dDhr98IymfJkLooazIqBLJSCp9J4vLi5B8ICt9oUUApeS9MIduUtFPet31McnqysE1oiD3tEnXV7iOto4rBmLe6m00)

Witness this code at https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuL8iA4fCpqrKA4dDhr98IymfJkLooazIqBLJSCp9J4vLi5B8ICt9oUUApeS9MIduUtFPet31McnqysE1oiD3tEnXV7iOto4rBmLe6m00
```
@startuml
'pragma teoz false
Bob -> Alice : hello
[o-> Alice: OK
?o-> Alice: OK
Bob <-o] : WTF?
Bob <-o? : WTF?
@enduml
```

The teoz engine is not affected:
   ![teoz engine correct output](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvNBAJrBGjLDmpCbCJbMmKiX8pSd9vuhEXmbPAVXxSzcZSC5QR7JpOu7AmqFSx65yUnZV8JKl1MWP0000)

**Comment by jhoehle** [comment]
Cool, systematic testing, thank you!

[Like user mawi in the forum](https://forum.plantuml.net/13569/activation-is-offset-using-teoz) and bug #656, I wonder: Where to report bugs?
To me, the project bugtracker is the place to go, but your forum SW seems to make a good job at it too.

**Comment by arnaudroques** [comment]
Thanks for the report.

This has been fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot)  and [on the online server](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8lA4fCpqrKA4dDhr98IymfJkLooazIqBLJSCp9J4vLi5B8ICt9oUUApeS9MIduUtFPet31McnqysE1oiD3tEnXV7iOto4rBmLe6m00).

Tell us if you find other issues!

**Comment by jhoehle** [comment]
Fixed online, thus closing without waiting for official release.
