### ISSUE TITLE
& a -> b crashes teoz

### ISSUE THREAD

**Issue by jhoehle** [plantuml/plantuml#1096]
When this first happened, I thought your server was out of service, not that there was a tiny copy&paste error in my 50 line script. :-) The message "PlantUML (version) cannot parse result from dot/GraphViz" is misleading.

```
@startuml
!pragma teoz true
& A -> B
@enduml
```
[IndexOutOfBoundsException: Index -1 out of bounds for length 0](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvL9JS5JGjLDmud98pKi1AW40)

The crash happens when "&" is used in a context without another arrow above it to clinge to, e.g. when interactively modifying PlantUML scripts. Above is the simplest possible test case.

**Comment by arnaudroques** [comment]
Thanks for the report.

This has been fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and [on the online server](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvL9JS5JGjLDmud98pKi1AW40).

Tell us if you find other issues!

**Comment by jhoehle** [comment]
Thank you! Will do (report more as I find'em).

Closing now, without waiting for an official release (the Eclipse plugin is one year behind anyway...)
