### ISSUE TITLE
SCXML files generated from state diagrams don't have input/output attributes

### ISSUE THREAD

**Issue by samjohn24** [plantuml/plantuml#1100]
When generating SCXML files using -tscxml option from State diagrams the "input/output" attributes of states are not being included. 

Example:

```
@startuml

state counter{
  state count_start <<inputPin>>
  state count_done <<outputPin>>  
  state "count_val[3:0]" <<outputPin>>  
  [*] -> count_idle
  count_idle --> count_ongoing: count_start
  state count_idle: count_val := 0
  state count_ongoing: count_val := count_val +1
  count_ongoing -> count_finish: count_val != MAX_VAL
  state count_finish: count_done:=1
  count_finish -> count_idle

}

@enduml
```

Generated file:

`<?xml version="1.0" encoding="UTF-8"?><scxml xmlns="http://www.w3.org/2005/07/scxml" initial="startcounter" version="1.0">
<state id="count_start"/>
<state id="count_done"/>
<state id="count_val[3:0]"/>
<state id="startcounter">
<transition target="count_idle"/>
</state>
<state id="count_idle">
<transition event="count_start" target="count_ongoing"/>
</state>
<state id="count_ongoing">
<transition event="count_val != MAX_VAL" target="count_finish"/>
</state>
<state id="count_finish">
<transition target="count_idle"/>
</state>
</scxml>
`

**Comment by arnaudroques** [comment]
Thanks for the feedback. This should be fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Tell us if you find other issues!

**Comment by samjohn24** [comment]
Thanks @arnaudroques! I've just run the snapshot and the issue is fixed.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @samjohn24 for the report.
- Thanks PlantUML team for your work.

Regards.
