### ISSUE TITLE
SCXML files generated from state diagrams don't preserve state hierarchies

### ISSUE THREAD

**Issue by samjohn24** [plantuml/plantuml#1101]
Generated SCXML files doesn't preserve state hierarchies.

```
@startuml

state module {
state Somp {
  state entry1 <<inputPin>>
  state entry2 <<inputPin>>
  state sin
  sin -> sin2
}

state flop{
  state sig_in <<inputPin>>
  state sig_ff <<outputPin>>
  state flop_0: sig_ff := 0
  state flop_1: sig_ff := 1
  [*] -> flop_0
  flop_0 -> flop_1 : sig_in
  
}

state counter{
  state count_start <<inputPin>>
  state count_done <<outputPin>>  
  state "count_val[3:0]" <<outputPin>>  
  [*] -> count_idle
  count_idle --> count_ongoing: count_start
  state count_idle: count_val := 0
  state count_ongoing: count_val := count_val +1
  count_ongoing -> count_finish: count_val != MAX_VAL
  state count_finish: count_done:=1
  count_finish -> count_idle

}
state ex <<inputPin>>
state exitAx <<inputPin>>

exitAx --> entry1
sig_ff -> entry2 : "!" 


}
@enduml
```

Generated:

`<?xml version="1.0" encoding="UTF-8"?><scxml xmlns="http://www.w3.org/2005/07/scxml" initial="startflop" version="1.0">
<state id="entry1"/>
<state id="entry2"/>
<state id="sin">
<transition target="sin2"/>
</state>
<state id="sin2"/>
<state id="sig_in"/>
<state id="sig_ff">
<transition event="&quot;!&quot;" target="entry2"/>
</state>
<state id="flop_0">
<transition event="sig_in" target="flop_1"/>
</state>
<state id="flop_1"/>
<state id="startflop">
<transition target="flop_0"/>
</state>
<state id="count_start"/>
<state id="count_done"/>
<state id="count_val[3:0]"/>
<state id="startcounter">
<transition target="count_idle"/>
</state>
<state id="count_idle">
<transition event="count_start" target="count_ongoing"/>
</state>
<state id="count_ongoing">
<transition event="count_val != MAX_VAL" target="count_finish"/>
</state>
<state id="count_finish">
<transition target="count_idle"/>
</state>
<state id="ex"/>
<state id="exitAx">
<transition target="entry1"/>
</state>
</scxml>
`

**Comment by arnaudroques** [comment]
Thanks for the report.
It's strange, but [your diagram text does not seem to work](https://www.plantuml.com/plantuml/uml/PLBDQiCm3BxhATGSDmfnTZDBQUxRQJ06fOIoE9d1iKlYZ8xGTrzTkv6s7ahr_SYVv7Wx-iFWfzx0fV0AUzTCHk6Su9lhZmjGrWy_0fyt71U4HstXyiFr9fG5d249hN77UJ5rjRQXYN3R1apUEfStNfQOSqLmHS3kOH_YOXF4luKGA5CSq2oVRh9U3JE7zVKIQ8P8Diuguh98VX_Cxadc-omeAJqgkZ4AgCJreZZREMqxoSCeAVabBW5ywViJo4FWKS0V8qtLQgl7BzwuAl6r-gZVgnSMGKRQNPO2kFPlLJYdVdLYJ-AaVNN5aCfm3V7XGFfmDw90YTag2mTjbMsctlm2). Could you double-check your source?

And it would be nice if you could post the shortest example that shows the issue.

Thanks again!

**Comment by samjohn24** [comment]
Sorry I forgot to put the code in a Gtihub's code block, now it is working.

**Comment by samjohn24** [comment]
Thanks @arnaudroques! I've just run the snapshot and the issue is fixed.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @samjohn24 for the report.
- Thanks PlantUML team for your work.

Regards.
