### ISSUE TITLE
split and hidden not hiding all of the arrow

### ISSUE THREAD

**Issue by rkirchofer** [plantuml/plantuml#1102]
```
@startuml
'https://plantuml.com/activity-diagram-beta
!pragma useVerticalIf on

start
:first thing;
split
:second thing;
split again
-[hidden]->
:other thing;
end split
:last thing;
@enduml
```
![issue](https://user-images.githubusercontent.com/88050994/187303124-fd1e9592-12f6-4407-9f30-237c157f8f09.png)
I'm trying to introduce `other thing` as having no parent. Using `split` and `hidden` gets me close except that `hidden` doesn't hide part of the line.

**Comment by rkirchofer** [comment]
```
$ java -jar plantuml.jar -version
PlantUML version 1.2022.7 (Mon Aug 22 13:01:30 EDT 2022)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.49.3 (20211023.0002)
Installation seems OK. File generation OK
```

**Comment by The-Lum** [comment]
Hello @rkirchofer,

Here is a proposal, _to achieve your expected result_:
```puml
@startuml
split
-[hidden]->
start
:first thing;
:second thing;
split again
-[hidden]->
:other thing;
end split
:last thing;
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIekoCaiuTADpiXCIKdDYzMrum9BSLcbPHOLboYKP6JcfLjpMHMd9kVdfS2uO4qAYUc9cNaeMgtoIp9IYs2gKe4Q8CPRvIGYp780YWDj1W00)](https://www.planttext.com/?text=SoWkIImgAStDuIekoCaiuTADpiXCIKdDYzMrum9BSLcbPHOLboYKP6JcfLjpMHMd9kVdfS2uO4qAYUc9cNaeMgtoIp9IYs2gKe4Q8CPRvIGYp780YWDj1W00)

_If that can help,_
Regards,
Th.

**Comment by rkirchofer** [comment]
Interesting, thanks. I'll reopen if this doesn't solve my issue. Thanks!
