### ISSUE TITLE
GPLv3 does not require acceptance for use

### ISSUE THREAD

**Issue by curtmack** [plantuml/plantuml#1103]
In the PlantUML welcome message (PSystemWelcome.java), the text "(If you use this software, you accept its license)" appears.

Such a requirement is not imposed or supported by the GPLv3, which explicitly states:

```
  9. Acceptance Not Required for Having Copies.

  You are not required to accept this License in order to receive or
run a copy of the Program.  Ancillary propagation of a covered work
occurring solely as a consequence of using peer-to-peer transmission
to receive a copy likewise does not require acceptance.  However,
nothing other than this License grants you permission to propagate or
modify any covered work.  These actions infringe copyright if you do
not accept this License.  Therefore, by modifying or propagating a
covered work, you indicate your acceptance of this License to do so.
```

While I'm not an expert on GPLv3 compliance, I believe adding a requirement to accept the license to use the software would be an "additional restriction" per section 10, which would make PlantUML's license incompatible with the GPL. (It's not listed among the approved additional terms in section 7, for instance.) So I'm not sure that PlantUML can impose this requirement on its own in builds that claim to be compatible with the GPLv3.

Assuming this text was added due to a mistaken interpretation of the GPL, it can simply be removed, or else it can be replaced with more appropriate text advising the user of their right to modify and/or redistribute under the GPL.

**Comment by arnaudroques** [comment]
> Assuming this text was added due to a mistaken interpretation of the GPL, it can simply be removed, or else it can be replaced with more appropriate text advising the user of their right to modify and/or redistribute under the GPL.

Yes, we are not expert license either :-)
We are going to remove this sentence.

Thanks for pointing this out!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @curtmack for the report.
- Thanks PlantUML team for your work.

Regards.
