### ISSUE TITLE
Arrow direction within new PlantUML Syntax

### ISSUE THREAD

**Issue by pascalbrunner** [plantuml/plantuml#1115]
How can I make two boxes being right next to each other?
It seems that -[right]-> is not working anymore with the new synatx:
https://plantuml.com/en/activity-diagram-beta

-[hidden]-> is still working.

I would really apprepiate help.

Thank you!

**Comment by The-Lum** [comment]
Hello @pascalbrunner, and all,

FYI: [Activity-diagram-beta](https://plantuml.com/en/activity-diagram-beta) is now only top to bottom...

But you can use **_class_** or **_deployment_** _(component, usecase)_ to achieve your request, as:

```puml
@startuml
a -right-> b
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuKfKq2tAJCyeqRLJIE9oICrB0Ge20000)](https://www.planttext.com/?text=SoWkIImgAStDuKfKq2tAJCyeqRLJIE9oICrB0Ge20000)

```puml
@startuml
rectangle a
rectangle b
a -right-> b
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIfAJIv9p4lFILL8H68dSIKgw1PbfcUKwDe1EGwfUIb0nG00)](https://www.planttext.com/?text=SoWkIImgAStDuIfAJIv9p4lFILL8H68dSIKgw1PbfcUKwDe1EGwfUIb0nG00)

or just:
```puml
@startuml
rectangle a
rectangle b
a -> b
@enduml
```

_If that can help,_
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This issue can be closed.
- Thanks @pascalbrunner for the report.
- Thanks PlantUML team for your work.
	
Regards.

**Comment by mohamed-AARAB** [comment]
Issue is not fixed as of version 1.2020.02

**Comment by The-Lum** [comment]
Hi @mohamed-AARAB 

- What is your issue?

Regards,
Th.

**Comment by mohamed-AARAB** [comment]
Same as OP, I cant control the direction of arrows on activity diagrams.

The original problem is that the diagram I created is not compact enough. So I have to change some arrows directions to make it more compact. And the autorouter is not helping much.
