### ISSUE TITLE
Render w/o graphviz/dot on Windows broken since plantuml-1.2022.2

### ISSUE THREAD

**Issue by basejumpa** [plantuml/plantuml#1118]
Render w/o graphviz/dot on Windows broken since plantuml-1.2022.2.

plantuml-1.2022.1 is the youngest working one.

Reproduction:
file `some_diagram.puml`
```
@startuml
component A
@enduml
```

```
C:\>java -jar tools\plantuml-1.2022.2.jar -verbose some_diagram.puml
```
results in 
![some_diagram](https://user-images.githubusercontent.com/8762228/190086156-5bad0844-d9f4-43f6-9007-53c6e6d094ef.png)

```
C:\>java -jar tools\plantuml-1.2022.1.jar -verbose some_diagram.puml
```
results in 
![some_diagram](https://user-images.githubusercontent.com/8762228/190086284-92373dc4-49ee-41b4-8843-8c11ff77a32a.png)

**Comment by arnaudroques** [comment]
Could you check with version 1.2022.7 ?

This seems to work [on the online server](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEpot8pqlDAr5mv798pKi1YG40).

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @basejumpa  for the report.
- Thanks PlantUML team for your work.

Regards.
