### ISSUE TITLE
[perf] SkinParam abuses of regex

### ISSUE THREAD

**Issue by rmannibucau** [plantuml/plantuml#1119]
SkinParam#cleanForKeySlow (https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/SkinParam.java#L218) uses a lot of not precompiled regex so extracting them to make them static boosts the perfs (from 45s to 22s for s svg rendering in my case).

From what I saw `"_|\\."` should be extracted in `private static final Pattern P1 = Pattern.compile("_|\\.|\\s");` and the `replaceAll` line replaced by `key = P1.matcher(key).replaceAll("");` and then all other `replaceAll` should be replaced by `replace` (which does a string replacement and does not create, compile and use a new pattern each time. Same applies to `replaceSmart` which does not need `replaceAll` but just `replace` due to its usage.

Here is the patch I use - take care it is on last release and not 100% aligned with master:

```

    private static final Pattern P1 = Pattern.compile("_|\\.|\\s");
    static String cleanForKey(String key) {
        key = StringUtils.trin(StringUtils.goLowerCase(key));
        key = P1.matcher(key).replaceAll("");
        // key = replaceSmart(key, "partition", "package");
        key = replaceSmart(key, "sequenceparticipant", "participant");
        key = replaceSmart(key, "sequenceactor", "actor");
        // if (key.contains("arrow")) {
        // key = key.replaceAll("activityarrow|objectarrow|classarrow|componentarrow|statearrow|usecasearrow",
        // "genericarrow");
        // }
        key = key.replace("activityarrow", "arrow");
        key = key.replace("objectarrow", "arrow");
        key = key.replace("classarrow", "arrow");
        key = key.replace("componentarrow", "arrow");
        key = key.replace("statearrow", "arrow");
        key = key.replace("usecasearrow", "arrow");
        key = key.replace("sequencearrow", "arrow");
        final Matcher2 m = stereoPattern.matcher(key);
        if (m.find()) {
            final String s = m.group(1);
            key = key.replaceAll(stereoPatternString, "");
            key += "<<" + s + ">>";
        }
        return key;
    }

    private static String replaceSmart(String s, String src, String target) {
        if (s.contains(src) == false) {
            return s;
        }
        return s.replace(src, target);
    }
```

edit: with very last snapshot the cache makes the rendering fast enough so not that urgent

**Comment by arnaudroques** [comment]
Thanks for the suggestion!
Following your idea, we propose the following patch:

```
	private static final Pattern patternCleanUnderscoreDot = Pattern.compile("_|\\.");
	private static final Pattern patternCleanSequence = Pattern.compile("sequence(participant|actor)");
	private static final Pattern patternCleanArrow = Pattern.compile("(activity|class|component|object|sequence|state|usecase)arrow");
	private static final Pattern patternCleanAlign = Pattern.compile("align$");

	List<String> cleanForKeySlow(String key) {
		key = StringUtils.trin(StringUtils.goLowerCase(key));
		key = patternCleanUnderscoreDot.matcher(key).replaceAll("");
		key = patternCleanSequence.matcher(key).replaceAll("$1");
		key = patternCleanArrow.matcher(key).replaceAll("arrow");
		key = patternCleanAlign.matcher(key).replaceAll("alignment");

		final Matcher2 mm = stereoPattern.matcher(key);
		final List<String> result = new ArrayList<>();
		while (mm.find()) {
			final String s = mm.group(1);
			result.add(key.replaceAll(stereoPatternString, "") + "<<" + s + ">>");
		}
		if (result.size() == 0)
			result.add(key);

		return Collections.unmodifiableList(result);
	}

```

> (from 45s to 22s for s svg rendering in my case).
>
Since you are doing some perf test, we are curious to know if our own patch changes this.
Thanks again!

**Comment by rmannibucau** [comment]
@arnaudroques this is pretty close in perf yes, the diff between a precompiled pattern and a plain `replace` which does not use a pattern at all is close so it is mainly a matter of code preference since there the replacements don't really need a regex.

**Comment by The-Lum** [comment]
_[Just for traceability]_

Fixed and linked to this commit: https://github.com/plantuml/plantuml/commit/b2afe9c9165e4e5bdaa39ca975499320a0bce5a2 _(~v1.2022.8beta6)_

Thanks for the enhancement.
