### ISSUE TITLE
Use PNG metadata to prevent updating

### ISSUE THREAD

**Issue by Phaiax** [plantuml/plantuml#112]
Hi
I use plantuml within doxygen and there I generate a lot of graphs. These are rebuild every time i start doxygen and that takes more and more minutes. So now I am looking for a possibility to shorten that time.

I thought that maybe I can modify plantuml:
   - look if the output file already exists
   - if it exists, then extract the original uml source from the png metadata
   - if the previous and current source are the same, don't create the diagram and exit

Is that possible?
Can you point me to the source code where to make that change?

Thanks,
Phaiax

**Comment by arnaudroques** [comment]
That's a very good idea!
It's not very difficult to implement for us. The only issue is that this part of code is very old, and probably need some refactoring before doing the change.
If you are curious, you can start at https://github.com/plantuml/plantuml/blob/fb476d48f6ecbdfe7f69533a9ff7eb587b3156d2/src/net/sourceforge/plantuml/Run.java#L391

You'll see that at the begining of the method, metadata is read.
Then for historical reason, there are two classes `SourceFileReader` and `SourceFileReader2` that are close (and contain duplicated code, which is very bad). So those classes should probably be merged. With one difficult : `SourceFileReader` is part of the public API and cannot be changed.

The class `BlockUml` may be impacted also.

Don't take too much time on this : I think we will take the job :-)
Thanks for the idea anyway!

**Comment by arnaudroques** [comment]
In last beta http://beta.plantuml.net/plantuml.jar
we have added a flag -checkmetadata
With this flag, PNG files are not generated if metadata has not changed.
You can try it with -verbose flag. Some message is displayed when generation is skipped :
`java -jar plantuml.jar -verbose -checkmetadata demo.txt`

This has not been widely tested, so feedback is welcome!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now implemented.
- Thanks @Phaiax for the report.
- Thanks PlantUML team for your work.

Regards.
