### ISSUE TITLE
multiline in mindmap: latex/math formula can only stay in oneline

### ISSUE THREAD

**Issue by Lucid-A** [plantuml/plantuml#1123]
Hi developers:

When rendering LaTeX formula, there always be the chance that the plain text is too long to be edited in a single line, just like the first one in the example.
I wonder whether you can make the second one to be rendered correctly as the first one in future version.

The following example may be not so appropriate, but I think you can get it.

Example code: 
``` plantuml
@startmindmap
* long plain text
**: **first**
<latex> \int_{0}^{\infty} \left( \sum_{i = 0}^{n} \right) {\rm d}x </latex>
;
**: **second**
<latex> 
    \int_{0}^{\infty} \left( 
        \sum_{i = 0}^{n} 
    \right) {\rm d}x 
</latex>;
@endmindmap
```
Result: 
![image](https://user-images.githubusercontent.com/62926655/191311137-43d07351-7848-43e0-b1e0-903b43e1ae0f.png)

It seems not to be a critical issue, but however I wanted to report it as readability improvements on plantuml codes.

Best regards and thanks for your work on plantuml!

**Comment by arnaudroques** [comment]
Thanks for the suggestion, this is a nice idea.
It's now working [with last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and [on the online server](https://www.plantuml.com/plantuml/umla/TO_1oi8m48Jl-nHp_FzSz6ohz4629PYq1f9jILQeXBwxbLOy5FUqpC3tCKqMaoHwjj6Cf106xZ46undY9Y6bJb2gyocBKbG7iwGNQC_IbkDyBSlNoNE63gwJF-ZyY6tnEEDTyf8dtz_b7qMd23jFg0yhWwgDdTrjOFk54u3V0i9wEzFQx7JqyLNKEBRRq1S0).

**Comment by Lucid-A** [comment]
Just checked it out and it's working as expected. Thanks!
