### ISSUE TITLE
cannot follow extends by string in class diagram

### ISSUE THREAD

**Issue by alan-isaac** [plantuml/plantuml#1142]
Class names can be strings that include white space, but `extends` does not work with quotes. For example, the following diagram does not work, but it does if you remove the quotes around `TestOne`. (Or even, just remove them from the second instance.)
```
@startuml
scale 720 width
skinparam shadowing false
hide circle
hide empty members

class "TestOne" {
attr1
attr2
}
class "Test Two" extends "TestOne" {
symmetric
}

@enduml
```

**Comment by arnaudroques** [comment]
Thanks for the report: this is fixed in last snapshot and [on the online server](http://www.plantuml.com/plantuml/uml/LOv12i9034NtEKNe3VG4lO6RNY3EVEtWP5gII2tYtHt4XMu-7nuFtkWX5dUjvBVILZ5HzbdoifLsvOjK1yqbWrEnLByVkiRE2Zt3d2XLSUTXWiUfOU0dIOGTFdkaro_dQLi6nYFGyh_Ykoh2Ikh2s6bFUWC0).

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @alan-isaac for the report.
- Thanks PlantUML team for your work.
	
Regards.
