### ISSUE TITLE
[Bug] in Gantt chart `ressources` is a typo

### ISSUE THREAD

**Issue by huyz** [plantuml/plantuml#1146]
Should be `resources`.

Did a French coder write this? :)

**Comment by The-Lum** [comment]
Hello @huyz, @arnaudroques, and all,

👀 Good job...  _(:fr: vs 🇬🇧 or 🇺🇸)_  

I can propose a PR, to make change `ressources?` to `ress?ources?` on:
- [`ressources` on plantuml](https://github.com/plantuml/plantuml/search?q=ressources)

But:
- It is necessary or not to rename also file names?

Regards.

**Comment by arnaudroques** [comment]
> 
> Did a French coder write this? :)

Nobody's perfect! :)


> I can propose a PR, to make change `ressources?` to `ress?ources?` or `res(s)?ources?` on:
> 
> * [`ressources` on plantuml](https://github.com/plantuml/plantuml/search?q=ressources)
> 
Thanks but that's not needed: I'm working on it already!

> * It is necessary or not to rename also file names?
> 
Yes, I'm going to fix the type on filenames also.

Best regards,

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @huyz for the report.
- Thanks PlantUML team for your work.
	
Regards.
