### ISSUE TITLE
Cannot render relationship decorators (crow feet) on ER diagrams with smetana

### ISSUE THREAD

**Issue by anenviousguest** [plantuml/plantuml#1147]
Taking a latest [plantuml.jar](https://github.com/plantuml/plantuml/releases/tag/v1.2022.10) (1.2022.10), and the following snippet from the Entity Relationship diagram example:
```
@startuml
Entity01 }|..|| Entity02
@enduml
```
When I run the app using this command:
```
java -jar plantuml.jar \
    -Djava.awt.headless=true\
    -svg -o test.svg
```
I get these messages in the log:
```
CANNOT DRAW printExtremityAtStart
CANNOT DRAW printExtremityAtEnd
CANNOT DRAW printExtremityAtStart
CANNOT DRAW printExtremityAtEnd
CANNOT DRAW printExtremityAtStart
CANNOT DRAW printExtremityAtEnd
```
The decorators (crow feet) are not redenered on a resulting diagram
![image](https://user-images.githubusercontent.com/8439575/193429590-1c62ad00-d955-4872-ada7-741b1d0284b2.png)

**Comment by The-Lum** [comment]
Hello all,

_[This is an Issue Review]_
Similar to:
- [QA-17241](https://forum.plantuml.net/17241/smetana-breaks-entity-arrows)

This is now fixed (on v1.2023.1):
```puml
@startuml
!pragma layout smetana
Entity01 }|..|| Entity02
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4laSiqhoIofD31KgAtHqwkfKO3oZRWSKlDIWFe0)](https://www.planttext.com/?text=SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4laSiqhoIofD31KgAtHqwkfKO3oZRWSKlDIWFe0)

- Thanks @anenviousguest for the report.
- Thanks PlantUML team for your work.

Regards.
