### ISSUE TITLE
Cannot render a note for entity attribute on ER diagrams with smetana

### ISSUE THREAD

**Issue by anenviousguest** [plantuml/plantuml#1148]
Taking a latest [plantuml.jar](https://github.com/plantuml/plantuml/releases/tag/v1.2022.10) (1.2022.10), and the following snippet from the Entity Relationship diagram example:
```
@startuml

!pragma layout smetana

entity Entity01 {
  * identifying_attribute
}

note right of Entity01::identifying_attribute
something
end note

@enduml
```

When I run the app using this command:
```
java -jar plantuml.jar \
    -Djava.awt.headless=true\
    -svg -o test.svg
```
I get these messages in the log:
```
Error in EntityImageTips
Error in EntityImageTips
Error in EntityImageTips
```
The note is not redenered on a resulting diagram
![image](https://user-images.githubusercontent.com/8439575/193678040-aab5ed6c-587e-4ec8-bfcf-ea68f6711736.png)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/RO_12eD034Jl-OhqK6Xx45TldeJIStz0A2kkkg1PoMO5AVttnb9wwcd2X3UJr54iIvedWCF2TfWjJdOBIJ3EJYnP04VYPSFRHtA3Jq2yeEzslzyy3GyhmhvDuk05G44SiXz6mT3_gAhw3yIWDQDwMjFXpWBqGOMneNiR7Q-kmq1eiY8loioOLiyg6xecPWt4rN7qkZz-XzCPQetIZzu0)](https://www.planttext.com/?text=RO_12eD034Jl-OhqK6Xx45TldeJIStz0A2kkkg1PoMO5AVttnb9wwcd2X3UJr54iIvedWCF2TfWjJdOBIJ3EJYnP04VYPSFRHtA3Jq2yeEzslzyy3GyhmhvDuk05G44SiXz6mT3_gAhw3yIWDQDwMjFXpWBqGOMneNiR7Q-kmq1eiY8loioOLiyg6xecPWt4rN7qkZz-XzCPQetIZzu0)

- Thanks @anenviousguest for the report.
- Thanks PlantUML team for your work.

Regards.
