### ISSUE TITLE
Mainframe visual issue: Lifeline activation

### ISSUE THREAD

**Issue by Misim18** [plantuml/plantuml#1149]
When adding a mainframe to diagram, it seems the first activation 'box' (activate x) does not appear to have a top border, see image for reference:

![Example](https://www.plantuml.com/plantuml/png/9Ov12i8m44NtSuhP2O5SG8gq2xs0U80ncU90aed9L7fyZTry-8__uStTgDcM4sIIiZRAZCxrw1nUTyerCRmaCgwgzjGTO0cc3H-T6rHg9a4g5SEbrYI1JBGWzL41JdT-Rrm20mMJ3naVln7e_MMiy8mtrGDDa_T_1Z1pYJ-fBm00)

Example plantUML code:

```plantuml 
@startuml
mainframe **sd** Example
hide footbox

Actor User
participant Application as App

activate User
User --> App : Foo
User <<-- App 
@enduml
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed _(tested on v1.2024.5)_.
>[![](https://www.planttext.com/api/plantuml/svg/9OvH2iCm34F_VGf_1tA1KKRxqTvW1_0IbncIE2JUwF7Rh3y2FKcWkHir--O4cQJiZJAZSpqwX-j1kIQ6ZqJ6NTNUUW0imRJXgtE3UYqbIALYkDIQ99295gG-B005anyPt-qXwFrpPFZ0JVL6q-Jzdy7C9LvFJW00)](https://www.planttext.com/api/plantuml/txt/9OvH2iCm34F_VGf_1tA1KKRxqTvW1_0IbncIE2JUwF7Rh3y2FKcWkHir--O4cQJiZJAZSpqwX-j1kIQ6ZqJ6NTNUUW0imRJXgtE3UYqbIALYkDIQ99295gG-B005anyPt-qXwFrpPFZ0JVL6q-Jzdy7C9LvFJW00) 

- Thanks @Misim18  for the report.
- Thanks PlantUML team for your work.

_[FYI @jimnelson372 ]_
Regards.
