### ISSUE TITLE
SVG server background not transparent

### ISSUE THREAD

**Issue by LuciferUchiha** [plantuml/plantuml#1151]
I have created a [custom theme](https://raw.githubusercontent.com/LuciferUchiha/georgerowlands.ch/main/puml-theme-purplerain.puml) where the background colour is transparent. When rendering diagrams using the official server www.plantuml.com/plantuml/png/..... the background is transparent as it should be. However, when using /svg/ the background colour is changed to white instead of transparent.

Steps to reproduce:

1. Go to [http://www.plantuml.com/plantuml/uml/](http://www.plantuml.com/plantuml/uml/) and change the theme using `!theme purplerain from https://raw.githubusercontent.com/LuciferUchiha/georgerowlands.ch/main`
2. Rerender and press SVG
3. Download SVG and view in a editor and the background will not be transparent.

You can also change online server to dark theme and press svg where it will use dsvg but the background will be white.

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This should be fixed [with last online version](https://www.plantuml.com/plantuml/svg/3SwniOCm303GdYd401_t5Fz8whGPmCZ2ziMME5awCdvOuDtRXaKrxssQhL0dE5tFHXehmw7IePYTOmr1uxNaQiLt7wGeRCIseFJmSgm7wHjBBJ5a4isaShN8QInOGh-jwIax_Ft3erKaM66F-CagpWcE-gKqJnjnkXi_).

There was a `background:#00000000` in the style which was probably misinterpreted.
Tell us if it's not working for you (beware of cache issue!)

**Comment by arnaudroques** [comment]
> I am sadly still having the issue even when using incognito or a different which should clear the cache.

Ok. Is http://beta.plantuml.net/background.html working for you?
(it does for us under Firefox and Chrome, the background is transparent)

Which SVG editor are you using?

**Comment by LuciferUchiha** [comment]
Seems to have been solved :) I must have still had something cached.
