### ISSUE TITLE
pre-processor splitstr only returns the first item

### ISSUE THREAD

**Issue by JohnLeyva** [plantuml/plantuml#1156]
pre-processor splitstr only returns the first item

The following should render `abc` instead of `a`

http://www.plantuml.com/plantuml/uml/HO_HoeCm34RlynHH-kClszLkPU1xZ36gHbRMHPUcxx-ebFMYKCuvyBLFwaNpEm9KcJzvKPfmpZngM1XT3Fow_BkaqWBQgTngUi8h_gKr1ZMmqtFTrSKGeqrpFEP5o8zFT043un7lvAVQTThu4GXf5ZC5AkAf3060w0UAkEzvA2N5snQKXRuRkh65Eq1lcNtd2m00

```
!unquoted function $link2($str)
    !$parts = %splitstr($str,";")
    !$r = ''
    !foreach $i in $parts
        !$r = $r + $i 
    !return $r
!endfunction


label link2_test [
    $link2(a;b;c)
]
```

**Comment by The-Lum** [comment]
Hello @JohnLeyva, and all,

Just to add a `!endfor` to see the expected result, as:

```puml
!unquoted function $link2($str)
    !$parts = %splitstr($str,";")
    !$r = ''
    !foreach $i in $parts
        !$r = $r + $i
    !endfor
    !return $r
!endfunction

label link2_test [
    $link2(a;b;c)
]
```

>[![](https://www.planttext.com/api/plantuml/svg/HOxH2i8m34NVynNPgCoXJxuMlqI6T5s7nTBDDFr_Gpen3o79kJVShkPFtJWikDRiEMuPJOhvVJkRmZG2IdLcTyG5xtWgUueiGEcrj_rFGKA7eIthHi7v5vg8KTwfMSbVAkqYlEb3NiJIPWfSIKm4UZuo0K1oSqYeqPuS2kD33KTOPsVhHvY-)](https://www.planttext.com/?text=HOxH2i8m34NVynNPgCoXJxuMlqI6T5s7nTBDDFr_Gpen3o79kJVShkPFtJWikDRiEMuPJOhvVJkRmZG2IdLcTyG5xtWgUueiGEcrj_rFGKA7eIthHi7v5vg8KTwfMSbVAkqYlEb3NiJIPWfSIKm4UZuo0K1oSqYeqPuS2kD33KTOPsVhHvY-)

Regards.

**Comment by JohnLeyva** [comment]
Thanks
