### ISSUE TITLE
bullet list bug

### ISSUE THREAD

**Issue by user1095108** [plantuml/plantuml#1158]
If I want to make a bullet list, that itself contains *, puml won't grok it, for example

`* +, -, *, / operators`

using ~ produces no effect at all, the bullet won't show.

**Comment by The-Lum** [comment]
Helli @user1095108, and all,

Yes it is a bug.

Then: _a possible workaround solution is to use Unicode as:_
```puml
file f1 [
* a bullet list with simple 'asterisk/star' within
* <color:red>+, -, *, / operators
* ...
]
file f2 [
* a bullet list with 'asterisk/star' on **Unicode** within
* <color:green>+, -, <U+002A>, / operators
* ...
]
```

>[![](https://www.planttext.com/api/plantuml/svg/TSrB3e8m40RWVKynEv9I2x8qX8H3i38kAanrOct9T8pNjo6kVAp_n-Sf8FWz79K61-T722WGA0iyIQwGwRwMGkMo85E-DLaSLrj6iKpwEON41yPbg0ti36W33QGLsKdYN1hMMdLIVcEwVypdVugWzHHfJWjg_SLT636-mNwgsxORXv_k2m00)](https://www.planttext.com/?text=TSrB3e8m40RWVKynEv9I2x8qX8H3i38kAanrOct9T8pNjo6kVAp_n-Sf8FWz79K61-T722WGA0iyIQwGwRwMGkMo85E-DLaSLrj6iKpwEON41yPbg0ti36W33QGLsKdYN1hMMdLIVcEwVypdVugWzHHfJWjg_SLT636-mNwgsxORXv_k2m00)

Regards.

**Comment by user1095108** [comment]
Ha ha, thank you. I trust you will fix the bug as well?

**Comment by The-Lum** [comment]
Hello PlantUML team, and @arnaudroques,

It seems that this regex is too restrictive:
https://github.com/plantuml/plantuml/blob/a1a599b63385370d0802a8032c47779bb73bf526/src/net/sourceforge/plantuml/creole/legacy/CreoleStripeSimpleParser.java#L110

_If that can help (to fix this issue),_
Regards,
Th.

**Comment by The-Lum** [comment]
Then, _for testing and debugging_, here is a minimal example:
```puml
file test [
*a*
**a*
***a*
***bold**
****bold**
]
```


Extract from:
```puml
file test_bullet_list_creole [
*bullet list
*no space
* space
* space with **bold**
* **bold**
==
***bold no space**
* space with end asterik *
*no space with end asterik*
* space with middle * asterik
*no space with end * asterik
* space with middle * **asterik**
*no space with end * **asterik**
]
```

**Comment by arnaudroques** [comment]
This is somehow [fixed in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

The situation is not simple because you can use indent with bullet list:

```
@startuml
file test_bullet_list_creole [
* a
* b
** b0
** b1
*** b10
*** b11
*** b12
*** b13
** b2
]
@enduml
```

So it's a good idea to use space when you are using bullet list and asterik

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @user1095108 for the report.
- Thanks PlantUML team for your work.

Regards.
