### ISSUE TITLE
Ludicrously long inheritance lines

### ISSUE THREAD

**Issue by dylan-chong** [plantuml/plantuml#116]
When having nested packages and a piece of text on a line, using the versions of packages i have, the inheritance lines get extremely long

```plantuml
@startuml

package a {

  package b {

    package c {

      package d {
        abstract class A extends B {
        }

        class D extends A {
        }
      }
    }
  }
}

' The message below makes the inheritance lines really really long
B ..> B : some message

@enduml
```

![ludicrously-long](https://user-images.githubusercontent.com/17482349/39080811-f1cd277e-4589-11e8-9780-889ed2b445c9.png)

graphviz version 2.40.1

PlantUML Version 1.2018.03

**Comment by arnaudroques** [comment]
This is a known issue with GraphViz 2.40.1
See: http://forum.plantuml.net/5425/relation-long-with-graphviz-using-labels-relations-namespace or http://forum.plantuml.net/7564/class-diagrams-rendering-changed-images-arrows-unexpectedly
The only way to solve it is to downgrade to GraphViz 2.38
Sorry about that

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @dylan-chong  for the report.
- Thanks @arnaudroques for your answer.

Regards.
