### ISSUE TITLE
Timing diagrams: negative values not working properly

### ISSUE THREAD

**Issue by bavovanachte** [plantuml/plantuml#1166]
The following diagram:

![image](https://user-images.githubusercontent.com/5442584/197743227-7432b3c5-892d-40ce-82a1-dc0e3e509d50.png)

is generated from the following diagram description:

```
@startuml
hide time-axis
scale 100 as 100 pixels
analog  "bemf"  as out

robust "Signal1" as S1
robust "Signal2" as S2
S1 has 0,1,2,hello
S2 has 0,1,2
@0
S1 is 0
S2 is 0
@100
S1 is {0,1} #SlateGrey
S2 is {0,1}
@200
S1 is 1
S2 is 0
@300
S1 is hello
S2 is {0,2}

@0
@+0.0
out is 0.0
@+4.0
out is 18.0
@+6.0
out is 21.0
@+1.0
out is 40.0
@+3.0
out is 59.0
@+6.0
out is 69.0
@+10.0
out is 71.0
@+5.0
out is 68.0
@+5.0
out is 62.0
@+12.0
out is 54.0
@+11.0
out is 52.0
@+7.0
out is 61.0
@+9.0
out is 100.0
@+4.0
out is 84.0
@+3.0
out is 83.0
@+5.0
out is 49.0
@+9.0
out is 1.0



@+0.0
out is 0.0
@+4.0
out is "-18.0"
@+6.0
out is "-21.0"
@+1.0
out is "-40.0"
@+3.0
out is "-59.0"
@+6.0
out is "-69.0"
@+10.0
out is "-71.0"
@+5.0
out is "-68.0"
@+5.0
out is "-62.0"
@+12.0
out is "-54.0"
@+11.0
out is "-52.0"
@+7.0
out is "-61.0"
@+9.0
out is "-100.0"
@+4.0
out is "-84.0"
@+3.0
out is "-83.0"
@+5.0
out is "-49.0"
@+9.0
out is "-1.0"

@enduml
```

Also, if we take only the negative values, the output isn't very nice:

![image](https://user-images.githubusercontent.com/5442584/197743443-edc1ad8c-0862-42b7-928f-fe8a751b1bb2.png)

```
@startuml
hide time-axis
scale 100 as 100 pixels
analog  "out"  as out


@+0.0
out is 0.0
@+4.0
out is "-18.0"
@+6.0
out is "-21.0"
@+1.0
out is "-40.0"
@+3.0
out is "-59.0"
@+6.0
out is "-69.0"
@+10.0
out is "-71.0"
@+5.0
out is "-68.0"
@+5.0
out is "-62.0"
@+12.0
out is "-54.0"
@+11.0
out is "-52.0"
@+7.0
out is "-61.0"
@+9.0
out is "-100.0"
@+4.0
out is "-84.0"
@+3.0
out is "-83.0"
@+5.0
out is "-49.0"
@+9.0
out is "-1.0"

@enduml

```

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This is fixed [on the online server](http://www.plantuml.com/plantuml/uml/XP11ReCm44NtSmgBBfkfF0v9o8vT3y09dCPDa4oe0aYfgjoz0wDYn2owidd-Vx1VsVN-tWzDX6jz3gQlcu3-KNVGVVWO35bhV3SjN_KZn0xypSVsOans2irdPiRJTkW1xkrfw7gJLVM54vID1nMji1Fie29pvPtTqCPjhY765YgN49HsZDJyoLpMakmV_E7GqxnKqVVX_Hw-9ICOIZVdA9MtCvI_pGtt12Wvy6hVBF1BHinR1da2L4naduYZYL0YkRIsYUoEwzPU2Dc43Z9ejmWLYZYfkSNiN10jaAGEYvxCFYP2LhsjoDVtBhRh2-H7DOYt0FzeG-qDjJZKvb2hG-MEcPB7iK8ZhG-rFsPA86g3g1GoqmvHIqHj4IUDPRYTXoR-0W00) and [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

**Comment by bavovanachte** [comment]
Thanks for the quick fix! Would you like me to close the issue? Or do you close it when releasing?

**Comment by arnaudroques** [comment]
Yes, we can close it. We would reopen it if needed.
