### ISSUE TITLE
nested namespaces header and names resolution bugs

### ISSUE THREAD

**Issue by grivo** [plantuml/plantuml#1175]
header display and names resolution work incorrectly for namespaces

```
@startuml
namespace common {
'    header is broken
    namespace "<<profile>> profile" as profiles {
        class X <<metaclass>>
        class Y <<stereotype>> extends X
    }
    namespace classes {
        class myClass <<y>> {
            + x : str = "value"
        }
    }
'    relative resolution is broken
    classes ..> profiles : <apply>>

'    resolution works fin with absolute addresses (you'll have to comment line above first)
'    common.classes ..> common.profiles : <apply>>
}
@enduml
```

however, all works correctly with packages

```
@startuml
package common {
    package "<<profile>> profile" as profiles {
        class X <<metaclass>>
        class Y <<stereotype>> extends X
    }
    package classes {
        class myClass <<y>> {
            + x : str = "value"
        }
    }
    classes ..> profiles : <apply>>
}
@enduml
```

**Comment by The-Lum** [comment]
Hi @grivo , and all,

FYI: that seems now fixed with last changes on namespaces and packages (see [news](https://plantuml.com/en/news)).

See expected result:
```puml
@startuml
namespace common {
    namespace "<<profile>> profile" as profiles {
        class X <<metaclass>>
        class Y <<stereotype>> extends X
    }
    namespace classes {
        class myClass <<y>> {
            + x : str = "value"
        }
    }
'    relative resolution is now not broken
    classes ..> profiles : <apply>>
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/RL3RQiCm37ttLuZ0sCOWsxAtufb2Vw9xL3CLmdp3KhA6aN-V4h86oWH6npwMZexsB5Ya3zv43CGPMu8sXP0Y_1ZGs9uhQtD9vywJSx2Y2f3_CAyLSxGUcU48rWOIN6xEtR0Voh9GeIHZddlIHIX-QjdoSRgHNuh-4GdZOSdMZjfZO-TuWWliWAN0ErG3-fwgAp-jAlTpAkHHke4KSFAzTEg_OuZfMu_0gQGlYkOggcFKjTkCxy1Ypbu7C9CvfwIkuBLkNfgtkZdf0XfuXhk12clVXqUpLvkwyby0)](https://www.planttext.com/?text=RL3RQiCm37ttLuZ0sCOWsxAtufb2Vw9xL3CLmdp3KhA6aN-V4h86oWH6npwMZexsB5Ya3zv43CGPMu8sXP0Y_1ZGs9uhQtD9vywJSx2Y2f3_CAyLSxGUcU48rWOIN6xEtR0Voh9GeIHZddlIHIX-QjdoSRgHNuh-4GdZOSdMZjfZO-TuWWliWAN0ErG3-fwgAp-jAlTpAkHHke4KSFAzTEg_OuZfMu_0gQGlYkOggcFKjTkCxy1Ypbu7C9CvfwIkuBLkNfgtkZdf0XfuXhk12clVXqUpLvkwyby0)

Thanks to the PlantUML team for the works. 👍
Regards.

**Comment by grivo** [comment]
seems to be working fine,  thanks!
