### ISSUE TITLE
The actor is missing from the plain theme of the use case diagram

### ISSUE THREAD

**Issue by lgz192** [plantuml/plantuml#1182]
```puml
@startuml
!theme plain
usecase UC
Actor -> UC
@enduml
```
http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuL8ioKZDJLKeo4dCpECgBKvDJYnELGXrvd9CBialKj2r0x4TKlDIW6e1
![image](https://user-images.githubusercontent.com/39425860/199977454-2c421273-0988-4c57-a363-fa137ec11b8d.png)

This occurs when svg is rendered.

**Comment by The-Lum** [comment]
Hello @lgz192, and all,

In fact that is due to those theme lines:

- On `root`:
https://github.com/plantuml/plantuml/blob/58469686e6e38312e18e29d86f7523b5f9f9d70f/themes/puml-theme-plain.puml#L36
- And on `title`:
https://github.com/plantuml/plantuml/blob/58469686e6e38312e18e29d86f7523b5f9f9d70f/themes/puml-theme-plain.puml#L53

From:
```puml
@startuml
!theme plain

title My title
actor actor
actor/ "actor/"
agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
component component
control control
database database
entity entity
file file
folder folder
frame frame
hexagon hexagon
interface interface
label label
node node
package package
person person
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
usecase/ "usecase/"
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JP51aeGW34Nt_nGPBp1Nw0lC8I94cseQ70nLu-qdW5gzUVy9LcBCOrSkMjyHN_gKjz0MEIH0WqQXduEwW9tcGft3lsaQEO5NIKgTi5fXiGkw17EkoNCvw18uBfuQu49nrcK4NCpLBXhXSepYDEIqquVR-NlBgVMxpSwIbXpfJ7XMddaNkWJsLj23Hc09rhC1IuvU2et0KjZcxyHJ_dZDYSv4I2h5vX6w3P5dYTI9bBrG0pPsB_iNT2OsARiL6e7VAbMe4yM6uhJQnzm6suPxKQTvBgtIcQYxk3RMcTUpRUAo2Gz9tfRv3m00)](https://www.planttext.com/?text=JP51aeGW34Nt_nGPBp1Nw0lC8I94cseQ70nLu-qdW5gzUVy9LcBCOrSkMjyHN_gKjz0MEIH0WqQXduEwW9tcGft3lsaQEO5NIKgTi5fXiGkw17EkoNCvw18uBfuQu49nrcK4NCpLBXhXSepYDEIqquVR-NlBgVMxpSwIbXpfJ7XMddaNkWJsLj23Hc09rhC1IuvU2et0KjZcxyHJ_dZDYSv4I2h5vX6w3P5dYTI9bBrG0pPsB_iNT2OsARiL6e7VAbMe4yM6uhJQnzm6suPxKQTvBgtIcQYxk3RMcTUpRUAo2Gz9tfRv3m00)

A possible temporary workaround will be to add:
```puml
<style>
element {
  title {
    LineThickness 1
  }
}
</style>
```

Then:

```puml
@startuml
!theme plain
<style>
element {
  title {
    LineThickness 1
  }
}
</style>
title My title
actor actor
actor/ "actor/"
agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
component component
control control
database database
entity entity
file file
folder folder
frame frame
hexagon hexagon
interface interface
label label
node node
package package
person person
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
usecase/ "usecase/"
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JP91RWCX34Nt_nJkN23gFgfoW7RN2pYC9q4XC0MFb56LkzV0JDJD_my3DWPEHJdhSWzuqwlSXUR0Fk9OT0to0GaMYqg_85AlGHeHVVeetrVlRb5AeNUBFV74yR1jwqk_rhu7x3HbQjhvG4Ft0Nof-Pl2Jk8dcw0TS4vB73clj0CSvv6gmFdih4etk90McwWAbq8Gfpx5Gl_OulSvnLhlHHQBcbEWpJ6oyfcBq0wmLLvNweR9Myqgc58O9LCtJ9djzfhYAW--f4YRmqULRFq8lGY1pnAeAM8QXQfWPdUpkw3DCKikbgWRVXPPX9eYMrCSBtQO5y7UqjsegN7ADTFcM8gusjRc-zXUOgS19ucZVOK_)](https://www.planttext.com/?text=JP91RWCX34Nt_nJkN23gFgfoW7RN2pYC9q4XC0MFb56LkzV0JDJD_my3DWPEHJdhSWzuqwlSXUR0Fk9OT0to0GaMYqg_85AlGHeHVVeetrVlRb5AeNUBFV74yR1jwqk_rhu7x3HbQjhvG4Ft0Nof-Pl2Jk8dcw0TS4vB73clj0CSvv6gmFdih4etk90McwWAbq8Gfpx5Gl_OulSvnLhlHHQBcbEWpJ6oyfcBq0wmLLvNweR9Myqgc58O9LCtJ9djzfhYAW--f4YRmqULRFq8lGY1pnAeAM8QXQfWPdUpkw3DCKikbgWRVXPPX9eYMrCSBtQO5y7UqjsegN7ADTFcM8gusjRc-zXUOgS19ucZVOK_)

_[FYI at the author of the plain theme: @matthew16550 ]_
_Enjoy,_
Regards.

**Comment by lgz192** [comment]
Ok，thank you very much. @The-Lum
