### ISSUE TITLE
`skinparam ArrowHeadColor none` doesn't work as expected on note node

### ISSUE THREAD

**Issue by hw202207** [plantuml/plantuml#1190]
- source code

```
@startuml
skinparam ArrowHeadColor none

start
:Foo;
partition "Backend" {
fork
  partition "Before" {
    :action A;
  }
fork again
  partition "After" {
    :action B;
    note right: hello notes;
  }
end fork
}

stop
@enduml
```

- Generated result

![NOynheD034HxdyBY6D00N_hADImmi6AnaN6K8kBkCPicoNRpPcOrRWydy_kMuLYJx6IqOMUcZnlJ-ATP3KM50KeEwd_L1YBcoPCALZqDAyjOuHCcjHKGFqqEnfU7yMeQ2kwQa6U98ysKvBlKJSxss-cR8aMTqTAyU8qBvwo57EyFOmQM3UUrLdTeWyHbBm00](https://user-images.githubusercontent.com/109395773/201728197-2b05e6ad-8023-4c0e-90d8-8e2e290fcac6.png)

The problem is there is still an arrow from `Foo` to `action B`.
If I remove the `note`, it works!

- [Link](//www.plantuml.com/plantuml/png/NOynheD034HxdyBY6D00N_hADImmi6AnaN6K8kBkCPicoNRpPcOrRWydy_kMuLYJx6IqOMUcZnlJ-ATP3KM50KeEwd_L1YBcoPCALZqDAyjOuHCcjHKGFqqEnfU7yMeQ2kwQa6U98ysKvBlKJSxss-cR8aMTqTAyU8qBvwo57EyFOmQM3UUrLdTeWyHbBm00) to online server.

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This is fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and [in last online version](http://www.plantuml.com/plantuml/uml/NOynReL034HxdyBY6D00QN8D2moiM6na7AM8k7kCg___TlDcPZNkBoVpdwF2jHSvoUZ0mKn_lvdcBwrgA2eCa3c8W1SlAjYCDEqiSuD_iAZjWFXgSZ1-F8pNqfHuw4BU6KTQgSXxQLYSxRCpTYb5dT7AkdcB6zUgIQxyBrPWJhYVcNf27oHE-WS0).

**Comment by hw202207** [comment]
awesome!
