### ISSUE TITLE
Component not displayed correctly

### ISSUE THREAD

**Issue by Hipska** [plantuml/plantuml#1192]
It seems already a while like this, but was surprised to not see a bug report of it..

The component type is not rendered correctly:
[![](https://plantuml-server.kkeisuke.dev/png/RP2z3i8m38JtFCMf2rDVW05LH6BgXDYg3X4r8Q9DglmC2D5d9sq2g09lFd_dSr8vBwmFGy_0Hd6-2KaekB44ReRHQDBU5NWmn6hs4I3TWVSgwYs4GvQIagY3wWb74XtP1PdxrAOvDzf762ShjBiOEonKLZzYOciZfTAoPSzutoeBqxJxCM6BuCYnR-HVB5DW6zJYRe97pa7GisVzg7LisLnLrv5koxSfxgdYFFxX2m00.png)](https://www.plantuml.com/plantuml/png/ROqzJiGm48LxdsAKXYeNe40HbgXI8ReeXOK7Os6F8_yK296pS1PEjdQSNIkxgwdcpVVc6q8KFYPhsFyVMyJxbr087NSUWJkxE4AAeOEVVAupFMS8IG8tEjzc407sg2QDVD46uHM5HBzXPQzhOxYZc4lmvWM53-VjHkxf9Mpyw9JIf6RscpDs4CEwFjqquH5ImC2Q-ovMgVBo0KRnxLA4tGI9IkbWklBsqwUM4cdkpwNoQCX0ikO4)
This is what it used to be:
![](https://3.bp.blogspot.com/-Vbj7UpiiVpg/Webe1hnCoSI/AAAAAAAANNo/YWtGOTtOcnINW4s0rE6D05Rnh9cgktaVwCLcBGAs/s1600/hidden_001.png)

Also the default theme seems to be changed, but couldn't find out what theme to select to have the same result..

**Comment by The-Lum** [comment]
Hello @Hipska, and all,

If you want the old behaviour, you can use and add `skin rose` directive.
And `skinparam componentStyle uml1` command will be used to switch to `UML1` notation.

```puml
@startuml
skin rose
skinparam componentStyle uml1

package "Core Components" {
    [Backend Client] as BackendClient
    [File Reader] as FileReader
    [Content Transform] as ContentTransform
    [Logging]
}
 
BackendClient ~~> ContentTransform : uses
FileReader ~~> ContentTransform: uses
 
' Layout Logging under BackendClient
BackendClient -[hidden]- Logging
 
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/RP0z3i8m38NtdC9YOUh0oe0gAZ4n0LlLmMfDYMYTAac72j6pS1PEXlj7LO6on2_VUqzEw3nQNvU5SdVDO8sZ_bQXnH9IKrQ6YVtPDmM1O1kbAaplc1Ei8cC9eWbnAtYezsiuyLuWuWoYGijR0kXWb0Pb9WzQaa-46TaUw-PXd9d8i1SJN2ooknfRzkIeViMPFveyrvmdwYcQMXH3s-v-dB25sf5JS_TVRAGaSWr7R4pjOMo2cZlJSiLbRn3VT9OH9y5awe920UHRFm00)](https://www.planttext.com/?text=RP0z3i8m38NtdC9YOUh0oe0gAZ4n0LlLmMfDYMYTAac72j6pS1PEXlj7LO6on2_VUqzEw3nQNvU5SdVDO8sZ_bQXnH9IKrQ6YVtPDmM1O1kbAaplc1Ei8cC9eWbnAtYezsiuyLuWuWoYGijR0kXWb0Pb9WzQaa-46TaUw-PXd9d8i1SJN2ooknfRzkIeViMPFveyrvmdwYcQMXH3s-v-dB25sf5JS_TVRAGaSWr7R4pjOMo2cZlJSiLbRn3VT9OH9y5awe920UHRFm00)


_See also other issues: #996, #969 and #946._

_Enjoy,_
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @Hipska for the report.

Regards.
