### ISSUE TITLE
Notes do not accept stereotypes

### ISSUE THREAD

**Issue by JohnLeyva** [plantuml/plantuml#1193]
Stereotypes does not works on notes

```
    note as note33 <<steroptypenote>>
       note content
    end note
```

the following works
```
    note as note33 $steroptypenote
       note content
    end note
    remove $steroptypenote
```

**Comment by The-Lum** [comment]
_[Just for traceability]_
Here are similar requests:
- [QA-13616](https://forum.plantuml.net/13616/how-can-i-define-note-with-stereotype)
- [QA-11645](https://forum.plantuml.net/11645/style-for-note-on-component-and-deployement-diagram-class)

Regards.

**Comment by The-Lum** [comment]
Hello @JohnLeyva, and all,

FYI: this now works from [version (V1.2022.13)](https://github.com/plantuml/plantuml/releases), with:

```puml
@startuml
<style>
note {
  BackGroundColor #fff
  .steroptypenote {
        BackgroundColor green
   }
}
</style>

note as note33 <<steroptypenote>>
  note (with steroptypenote) content 
end note

note as note44
  normal note content 
end note
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/PO_F2i8m3CRlVOg05xteOJkMClJWSvGjdMANZZP3XkpTxHyHYxaavFjzNqWNM7jU9YjauDMY4kGOuIK0phf_NBrRQBWuwppiZ35nVGoCtisyplX5IoN3-6COFI8bTHERaATFVZcW0wJUD21b7QXKj6Hc_xpp3Mhr0BqZHc8GI4FcwiIspNO_QLjI_lakJl7ZDm00)](https://www.planttext.com/?text=PO_F2i8m3CRlVOg05xteOJkMClJWSvGjdMANZZP3XkpTxHyHYxaavFjzNqWNM7jU9YjauDMY4kGOuIK0phf_NBrRQBWuwppiZ35nVGoCtisyplX5IoN3-6COFI8bTHERaATFVZcW0wJUD21b7QXKj6Hc_xpp3Mhr0BqZHc8GI4FcwiIspNO_QLjI_lakJl7ZDm00)

_Thanks to PlantUML team._
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @JohnLeyva for the report.
- Thanks PlantUML team for your work.
	
Regards.
