### ISSUE TITLE
!include does not work after newpage command in Component diagrams

### ISSUE THREAD

**Issue by milanschwartz** [plantuml/plantuml#12]
Preprocessor does not seem include external files after a newpage.

@startuml
!include x  <- this works
newpage
!include x <- this fails silently
@enduml

I am using the Pycharm PlantUML integration plugin (version 1.9.0, using PlantUml library 8036)

**Comment by arnaudroques** [comment]
Actually, this is not related to "newpage". To avoid infinite recursion, we have decided to include only one time any file.
If it's an issue for you, we could think about having a "!include_many" command that would allow to include several time a file.
What do you think about it ?

**Comment by milanschwartz** [comment]
Sounds good. Thanks.

**Comment by arnaudroques** [comment]
In last beta https://dl.dropboxusercontent.com/u/13064071/plantuml.jar
We've implemented the "!include_many" command.
Tell us if's not working for you

**Comment by milanschwartz** [comment]
Thanks.
