### ISSUE TITLE
Activity (beta): multiple backward actions in repeat while loop

### ISSUE THREAD

**Issue by moritzwagner** [plantuml/plantuml#1206]
Hey everyone,
I am currently working on a activity diagram with the new beta version. When I try to implement multiple backward actions, only the last one is displayed:
```
@startuml
start
repeat 
:action;
:object]
backward: action1;
backward: action2;
repeat while (condition) is (true) not (false)
:continue action;
stop
@enduml
```

![test](https://user-images.githubusercontent.com/24846047/205590828-2c839c06-d30f-4e37-b141-f36d884fd99c.png)

I also tried to add a `particion` as backward action but then I got an error message (Cant find group)
`backward: 
partition part{
    :action;
}`

Version: v1.2022.13

Thank you for your help

**Comment by The-Lum** [comment]
Hello @moritzwagner, and all,

See similar-pseudo requests here:
- [QA-5826](https://forum.plantuml.net/5826/please-provide-action-repeat-loop-start-instead-condition?show=5838#c5838)
- [QA-15276](https://forum.plantuml.net/15276/how-to-add-multiple-backward-nodes-in-an-activity-diagram)
- [QA-16471](https://forum.plantuml.net/16471/activity-diagram-repeat-multiple-nodes-backwards)
- https://github.com/plantuml/plantuml/issues/855#issuecomment-1011355976

Then here is a possible _temporary_ workaround, using sub-diagram (`{{` and `}}`) as:

```puml
@startuml
start
repeat 
:action;
:object]
backward:{{
"action1" -up->[ ] "action2"
}};
repeat while (condition) is (true) not (false)
:continue action;
stop
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/DOwz3iCW48FtUufJ9XWoj2EHghn7bU42LvMM0e936QAyUzEVR9O_o_POXOgqLu2lWCAPIH0CMV4f3c3I_60h4ynadmiLPzOLkXyzTTYtt5-kEE7VEdUmRSDHiznzO5GsHUS_LAElgAGqrXYJeBfHgAp1x0dniJ4UirLIXf6Zsw-z0G00)](https://www.planttext.com/?text=DOwz3iCW48FtUufJ9XWoj2EHghn7bU42LvMM0e936QAyUzEVR9O_o_POXOgqLu2lWCAPIH0CMV4f3c3I_60h4ynadmiLPzOLkXyzTTYtt5-kEE7VEdUmRSDHiznzO5GsHUS_LAElgAGqrXYJeBfHgAp1x0dniJ4UirLIXf6Zsw-z0G00)

Regards.

**Comment by moritzwagner** [comment]
Perfect, thanks.

**Comment by moritzwagner** [comment]
Perfect, thanks
