### ISSUE TITLE
Don't take focus away from current window if ui is not needed

### ISSUE THREAD

**Issue by dylan-chong** [plantuml/plantuml#121]
When i call `plantuml some-file` the focus is taken away from a current window, on Mac. This is rather annoying because I have a set up in vim that automatically runs the plant UML commandline tool everytime I save the file. The focus is taken away from vim.

It would be nice if, when the UI is not needed, for example when the commandline arguments are sufficient, do not start up the UI.

**Comment by arnaudroques** [comment]
Maybe you can try the -Djava.awt.headless=true trick.
See http://forum.plantuml.net/5403/popup-icon-disrupts-gui-use-grabbing-keyboard-window-focus

**Comment by dylan-chong** [comment]
Ah, the headless option needs to become before the jar file in java -jar ...

Running plantuml using the executable from homebrew doesnt allow you to do this

```
> which plantuml | xargs cat
#!/bin/bash
GRAPHVIZ_DOT="/usr/local/opt/graphviz/bin/dot" exec java -jar /usr/local/Cellar/plantuml/1.2018.3/libexec/plantuml.jar "$@"

```

**Comment by arnaudroques** [comment]
Ok, so we've build a new beta http://beta.plantuml.net/plantuml.jar
With this beta, you can use a new `-headless` flag but it has to be set as the very first argument in the command line.
Example:
`java -jar plantuml.jar -headless -verbose some-file`
It's difficult for us to test this option, so tell us if it's working for you.
Thanks,

**Comment by dylan-chong** [comment]
The headless option is working for me!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @dylan-chong for the report.
- Thanks PlantUML team for your work.

Regards.
