### ISSUE TITLE
!Include wbs fails generating Syntax Error on line continuations

### ISSUE THREAD

**Issue by skestle** [plantuml/plantuml#1210]
Given file `a.puml`:
```
@startwbs
* Business Process Modelling WBS
** Launch \
the project
@endwbs
```

If another file tries to include, the `\` character causes a Syntax Error:
```
@startwbs
!include a.puml
@endwbs
```

See https://www.plantuml.com/plantuml/uml/SoWkIImgAKygvbBCp4lEAKr9LSWeAIaejjBNBoylrol8ISmhAStDqKlEpzM7SVH1E3W_FDlJCpVTqRiolIpBqZFOA3Mh83FFoScppDV8AChHApV88oSdCItTAx4isIybpIZRr3NN9o_GDpnLDpBGfopV8z7HsIStoImmqT7Gsw_CDp35qj8drpNTBp7DtS3PWCiXDIy5w2u0

**Comment by arnaudroques** [comment]
Thanks for the feedback and congratulation for the idea of including an URL pointing to our own server!

This is fixed now [on the online server](https://www.plantuml.com/plantuml/uml/DSw_JeGm083ndQUuUm2ls4GJd2Y4IA6GL0QYMw5_BBI5I6drxTNXXc_ujbz-UFRbutGaNdiZBb9_2tvDhjhDvkJYykdzVhm046EyxOOvVrfpcpSBxWF-6xPnnTWgrFwei6HuW6BPjIiA73e8Fr1ZtsfZc5GD2tFF9LoVAaiSxKRny4v9s6g6IcAdPyhGOzk7Zl8i8xPIFPElQPackN3y3_aB) and [with last snapshot](https://github.com/plantuml/plantuml/releases).
