### ISSUE TITLE
Hidden elements still take space in the final diagram

### ISSUE THREAD

**Issue by bmnielsen** [plantuml/plantuml#1213]
I have a diagram where I'm pulling in a lot of components defined in other files for some other diagrams, linking them, and hiding the irrelevant components through `hide @unlinked`.

This works, in as much as the unlinked components are hidden, but the diagram is laid out as if they were there and replaced with white space. This means that my diagram ends up being twice as large as it should be.

Is it possible to hide components in such a way that they don't influence the diagram layout, or am I forced to split up my components into separate files and only import the ones I am interested in showing?

**Comment by arnaudroques** [comment]
You should try [remove @unlinked](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEpot8pqlDAr40iGpH-4PeV6Cmtr11LzSEAb-KcfjVbghWK9gNavcNdPh2vP2Qbm8q6000).
Is this what you are looking for?

**Comment by The-Lum** [comment]
Hello @bmnielsen, and all,

For that, instead of:
```puml
hide @unlinked
```
You can use:
```puml
remove @unlinked
```

Enjoy,
Regards.
_(oups, @arnaudroques you are too fast)_

**Comment by bmnielsen** [comment]
Perfect, thanks both!

**Comment by dragondive** [comment]
@arnaudroques @The-Lum 

This doesn't seem to work when `newpage` is involved. I tried `hide unlinked`, `remove unlinked`, `remove @unlinked`. Also tried putting these at the "top" or "bottom" of the newpage.

Here is a sample code that shows what I'm trying to achieve: https://github.com/dragondive/plantuml_demo/tree/main/src/preprocessor#generate-multiple-customized-diagrams-from-diagram-template

Is this still a bug that needs to be fixed eventually, or have I missed something?
