### ISSUE TITLE
Appling different Style to component ignores skinparams for component

### ISSUE THREAD

**Issue by boerngen-schmidt** [plantuml/plantuml#1216]
When removing the UML styling from components as described [here](https://plantuml.com/en/component-diagram#209c2b6d887c7fde) the skinparam for a component are not applied as expected.

![Example](https://www.plantuml.com/plantuml/png/LOvHYeD038RVSuhWFhlWFiiWE-m9P0yGnY3Yc4WcbfRIkrTBeMtUyf5y_zyL9_DjoL3cILOoMZ3figgmE5u1z_cbD8-ccmnHirhRyjdPX788-AL6ClBZhlTBPZHElgFCS0EWv6huNzZWPOtDsrBzFMNOivscn1L-1531-0DmAF0x7B-nmReE1-rOXhtw7G00)
[Source](https://www.plantuml.com/plantuml/png/LOvHYeD0343_SuhWVhlWViiWE-m9P0yGnY3Yc4WcbfRIkrTBeMt-yiXxf2jEvjkIeSoJh6IqOD9bLM5nl0Bkq_ibCned9napFzWlfNaqtMI8cjNQbi_E9fH3m2-r_P3X1a39rV2_iC6h6fktfVfxYjYpdQR45Nx4g63y0JWI-1qEDpPOr-6W7Skmltu7)

When adding a `skinparm rectangle { BackgroundColor #orange }` 
![Expected Styling](https://www.plantuml.com/plantuml/png/LOz1geD038RtSuhWM_l0hcMG3Zs1z01X32AEYMHYQIczUxK8jjdbv_k_a2ORgYrJSdaSU4R52Q9Cip2nmTF1Egqz4e5IDEG-aNkv0pxY7JvZ77kLXRiWIRIkwMwaZCbx-1DTqOy0eud2DPEwuroelfRYiXUX9RqDaGhuaM66S79kKy2_txgXWhBqMzeGT-jFRm00)
[Source](https://www.plantuml.com/plantuml/png/LOz1geD038RtSuhWM_l0hcMG3Zs1z01X32AEYMHYQIczUxK8jjdbv_k_a2ORgYrJSdaSU4R52Q9Cip2nmTF1Egqz4e5IDEG-aNkv0pxY7JvZ77kLXRiWIRIkwMwaZCbx-1DTqOy0eud2DPEwuroelfRYiXUX9RqDaGhuaM66S79kKy2_txgXWhBqMzeGT-jFRm00)

Version: 1.2022.5

A guess what is happening here is, that the component gets casted to a rectangle object, but in reality only the visuals of a rectangle should have been applied. I would be interested to have a look at the code, if someone could point me to the source file.

**Comment by arnaudroques** [comment]
It would be nice if you could post the source of both diagrams so that we could investigate.
Thanks!

**Comment by boerngen-schmidt** [comment]
@arnaudroques yeah sure, i thought the grphics would automatically link. Updated the issue

**Comment by arnaudroques** [comment]
Thanks for the examples!
BTW, we are currently migrating from `skinparam` syntax to `style` syntax, but this is not working for _component style_ %-)

Here is a demo of [some working example](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpimhI2nAp5L8piyjoCzBpIjHgEPI08BWaigSL8MYrEIInBpqd5IkMYukcsAGc1qNN12gr2anEJkzAByqByKvFoU_I44vlmWe3T82DnINogBK5A0o6tseoKWQd0sHx0aov798pKi1kXW0):
```
@startuml
skinparam component {
    Style rectangle
}

<style>
rectangle {
    BackgroundColor #orange
}
component {
    BackgroundColor #red
}
</style>

component C1
rectangle R1
@enduml
```

**Comment by boerngen-schmidt** [comment]
Seems like the sterotypes are not supported with the new style syntax? 
https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpimhI2nAp5L8piyjoCzBpIjHgEPI08BWaigSL8MYrEIInBpqd5IkMYukcsAGc1qNN12gr2anEJkzAByqByKvFoU_I44vlmWe3T82DnINogBK5A0o6tseoKWQd0sHx0aov798pKi1kXW0

**Comment by arnaudroques** [comment]
> Seems like the sterotypes are not supported with the new style syntax? 

Yes, [it is](https://www.plantuml.com/plantuml/uml/TOv12eD034NtESL0zorsFOZK6xGdc6fgnKmYCRCefNVl22ApCRlyl3n-irXGIv5WcKQUWuReEecpCBAvBxWy3_iGEiNE0W-4y0FmovhLi8SRUWlTDAWaxbiXKNSIpUVrPPSUaOfzniulaIE2nk5jJqghpb-s1eMuhShbwhpFiheiUQ-WGUvJf3y0).
But there might be issue, so thanks for your tests :-)

**Comment by boerngen-schmidt** [comment]
Interesting. A quick google search yielded https://plantuml.com/en/style-evolution which is what you are refering to. A quick play around with your example made me realize, that the docs will need some information on scoping. Meaning depending on where I put the "CSS Class" aka sterotype style definition it will be applied differently. 

But it seems that I found another Bug, but with the new Style. I will open a new issue for that.

And a last question if I may conerning your commit to fix this issue, was the URL Stuff part of the Problem or just the USymbol things?

**Comment by arnaudroques** [comment]
> But it seems that I found another Bug, but with the new Style. I will open a new issue for that.

Sure, thanks!


> And a last question if I may conerning your commit to fix this issue, was the URL Stuff part of the Problem

No: the URL stuff is completely unrelated and should not have been committed here (it's another aspect we are working on).
