### ISSUE TITLE
Add auto-run mode

### ISSUE THREAD

**Issue by dylan-chong** [plantuml/plantuml#122]
So that when i save the file, plantuml automatically runs and re-exports the image

e.g `plantuml myfile.plantuml --autoreload`

**Comment by dylan-chong** [comment]
I realise that the most beneficial point in this feature is that the export will be faster. It is very slow to export using a plug-in such as this https://github.com/weirongxu/plantuml-previewer.vim in comparison with the IntelliJ plug-in. This is because the vim plug-in does the export by starting up plantuml every single time.

Perhaps an alternative solution to this problem would to be make a start up times faster

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @dylan-chong for the report and your other issue: #123.
- Thanks PlantUML team for your work.

Regards.
