### ISSUE TITLE
nwdiag: can't change nodes background color

### ISSUE THREAD

**Issue by dgutson** [plantuml/plantuml#1224]
I can't find any relevant documentation, I'm trying everything I find/imagine and nothing works:

```plantuml
@startuml
nwdiag {
    network nw {
         a [backgroundcolor = "blue", color = "blue"];
         b;
    }
}
@enduml
```

Please help. Thanks.

**Comment by The-Lum** [comment]
Hello @dgutson, and all,

See this similar request here:
- [QA-12733: ability-to-add-background-color-to-component-network-nwdiag](https://forum.plantuml.net/12733/ability-to-add-background-color-to-component-network-nwdiag)

And just FYI, see also:
- [QA-14479: style-allow-style-on-nwdiag-diagram](https://forum.plantuml.net/14479/style-allow-style-on-nwdiag-diagram)

_If that can help,_
Regards.

**Comment by dgutson** [comment]
@The-Lum do I understand correctly if:
* I conclude that the feature is not implemented yet
* the style is for all the nodes, so no ability to set different colors to the nodes

?

**Comment by The-Lum** [comment]
@dgutson: Yes, you are absolutely right.

1. That is a wanted feature not yet implemented, you can vote on it and add a +1... to confirm to the PlantUML team, that this feature is requested also for you...
2. currently style is global, perhaps ask to allow `stereotype` on `nwdiag` for that...

Regards.

**Comment by dgutson** [comment]
Thanks @The-Lum ,it's clever. We will probably use nwdiag and add it the cylinder shape, or add this feature to plantuml. We'll see. Seems shorter enhancing nwdiag, which already has the background feature.

**Comment by arnaudroques** [comment]
This should be fixed in V1.2023.0. See [this example](https://www.plantuml.com/plantuml/uml/LOv1JiCm44NtFiN8tLOcIGi21AWBRi0IeMge9sc4Cux64tM1UdTIYwgET_vFx__P9KNHQGY6Jxx73duD09EUelp01mvZe7qhaJK30FHUA2Lu1Li_DQv-U7HrvQgxPcipFyGGvKA5l3KvKagwltgVHG6uUWtWxktwfgqGsnRHVjtKp1QYQqebzDrHlyD4fUGf7QGVjO-yL3UpMi8vUybLpvqGyTjxmLORMDnM_RzoA1rnfEN4TfPoVFbnz5IMg22d4OLOSytPdCsEs4z3-0C0).

Hope this helps!

**Comment by dgutson** [comment]
@qequ watch!!

**Comment by dgutson** [comment]
Thanks!
