### ISSUE TITLE
nwdiag: Allow line border for group

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1226]
Hello PlantUML team,

- Could you allow line border for group, on nwdiag?

This example seems to not works...:
```puml
<style>
group {
  LineThickness 5
  LineColor red
}
</style>
```

Here is a full example:

```puml
@startuml
<style>
group {
  BackGroundColor palegreen
  
  LineThickness 5
  LineColor red
}
</style>

nwdiag {
  network N {
      w1;
      w2;
  }

    group {
    description = "long group label";
    w1;
    w2;
  }
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/HOzD2i9038NtEKNe1KJ1bLMABjo8AoymTi8uD6PAPaeHwTsT_c78uhsyy95KCHbDtPkXZEd3T0AdeMln2uXdKpVNxCHU0WV5rZ0v9PASvRvveSVBrurGZBXV9lEgaeK1oit21EcjDswY2gK-Q8FtoOtLRm-hsergWCd-3q6q56lrRV91y8W51t5BpkP9NCo05RHY1gX8R7xk1m00)](https://www.planttext.com/?text=HOzD2i9038NtEKNe1KJ1bLMABjo8AoymTi8uD6PAPaeHwTsT_c78uhsyy95KCHbDtPkXZEd3T0AdeMln2uXdKpVNxCHU0WV5rZ0v9PASvRvveSVBrurGZBXV9lEgaeK1oit21EcjDswY2gK-Q8FtoOtLRm-hsergWCd-3q6q56lrRV91y8W51t5BpkP9NCo05RHY1gX8R7xk1m00)

Especially to flat theme as `amiga` or other.... :

>[![](https://www.planttext.com/api/plantuml/svg/HOz13e9034NtFKNb0aQseY5nQrnnWP5fXeQXGsPA9iPmTmKXTlL_c_z-MYSrKQV1mq4x6WZDmCv0bVJbwGekXcd4Do3UMQZfkEs5Ki9oszo23n5pnqemGtNSOY3Pid5hK4XpY3q-LhTCFfrtLIvgXjN-kn0jfJRog1m4BrZu86wxU_CaN_m0EsZ7p52JsEyp7m00)](https://www.planttext.com/?text=HOz13e9034NtFKNb0aQseY5nQrnnWP5fXeQXGsPA9iPmTmKXTlL_c_z-MYSrKQV1mq4x6WZDmCv0bVJbwGekXcd4Do3UMQZfkEs5Ki9oszo23n5pnqemGtNSOY3Pid5hK4XpY3q-LhTCFfrtLIvgXjN-kn0jfJRog1m4BrZu86wxU_CaN_m0EsZ7p52JsEyp7m00)

_Thanks for the enhancement,_
Regards,

**Comment by jcralbino** [comment]
Is this planned to be implemented?

**Comment by The-Lum** [comment]
Hi @arnaudroques,

Then:
- Could you confirm this example [for group linecolor] _(with inheritance on root style)_?

```puml
@startuml
<style>
root {
  BackGroundColor palegreen
  LineThickness 5
  LineColor red
}
</style>

nwdiag {
  network N {
      w1;
      w2;
  }

    group {
    description = "long group label";
    w1;
    w2;
  }
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/DOy_2y903CNtV8eW2BgeBOg3VoWwk8YJeylPY_NecIkvqoBIx-vPsv3X9U_n2ybyK1AU3mjh7zwMjY3E1Vm0uaxbvK7Sa_NUMITOAKk5477qOXyDq_bkyfB9UrnqctzKI4C3wsc71AwrKKLBPGgran9FxVIhEbdrAlsf1jgnYAUhBgJ9vsAgO1pZ1WVMST7vLbt93lw07jHZ6hZ5NqZmmfXCqbawdonnYiCNYO-aqJWQa17h-FuN)](https://www.planttext.com/?text=DOy_2y903CNtV8eW2BgeBOg3VoWwk8YJeylPY_NecIkvqoBIx-vPsv3X9U_n2ybyK1AU3mjh7zwMjY3E1Vm0uaxbvK7Sa_NUMITOAKk5477qOXyDq_bkyfB9UrnqctzKI4C3wsc71AwrKKLBPGgran9FxVIhEbdrAlsf1jgnYAUhBgJ9vsAgO1pZ1WVMST7vLbt93lw07jHZ6hZ5NqZmmfXCqbawdonnYiCNYO-aqJWQa17h-FuN) 

Regards,
Th.

**Comment by arnaudroques** [comment]
> * Could you confirm this example [for group linecolor] _(with inheritance on root style)_?

Yes, it works! :-)

**Comment by The-Lum** [comment]
Thanks @arnaudroques,
I just update the PlantUML Gallery:
- [puml-themes-gallery/diagrams/Nwdiag](https://the-lum.github.io/puml-themes-gallery/diagrams/Nwdiag.html)
