### ISSUE TITLE
Customisation of caption using skinparam is not working

### ISSUE THREAD

**Issue by harikrishna553** [plantuml/plantuml#1227]
I tried with below commands to customzie the caption.

```
skinparam CaptionFontColor #red
skinparam CaptionFontName Papyrus
skinparam CaptionFontSize 24
skinparam CaptionFontStyle italic
```

But do not see any affect.

Complete snippet is given below.

```
@startuml

skinparam CaptionFontColor #red
skinparam CaptionFontName Papyrus
skinparam CaptionFontSize 24
skinparam CaptionFontStyle italic

caption figure 1 : Login Server

Client -> LoginServer: Enter user name
Client -> LoginServer: Enter password
Client -> LoginServer: Submit the form 
LoginServer -> ADServer: Check the credentials
ADServer -> LoginServer: Login Successful
LoginServer -> Client: Login Successful

@enduml
```
**Reference**
https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#caption

**Comment by The-Lum** [comment]
Hello @harikrishna553, and all,

For that you can **now** use `style` _(instead of all `skinparam`)_ as:
```puml
@startuml
<style>
caption {
  FontColor #red
  FontName Papyrus
  FontSize 24
  FontStyle italic
}
</style>

caption figure 1 : Login Server

Client -> LoginServer: Enter user name
Client -> LoginServer: Enter password
Client -> LoginServer: Submit the form 
LoginServer -> ADServer: Check the credentials
ADServer -> LoginServer: Login Successful
LoginServer -> Client: Login Successful

@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/VP7FQiCm38VlUWh1pcLix5HAwSYwqnY3F87dAAsOOmT9xcXBtxtkaeonVnU3VlhuBA6LcXFBNO25sZxG4hphZLF48o0-fcXL2admIgWPWsVN4RwuVYzPnwZc0-7jtLHTHCZc0diumU9wD7-gMzva8Rp1EJwb3KUiINOa05LWYeQpvP0FyHpNqKWmQtbY-Vn_h7UgxqcQlwWwltPiQ5l2Dac7yALxWUyV9hBQad_x07tPlhZO1OMf_qCyhfAz9zKsX-_YOPvVE5XHRCe9pW00)](https://www.planttext.com/?text=VP7FQiCm38VlUWh1pcLix5HAwSYwqnY3F87dAAsOOmT9xcXBtxtkaeonVnU3VlhuBA6LcXFBNO25sZxG4hphZLF48o0-fcXL2admIgWPWsVN4RwuVYzPnwZc0-7jtLHTHCZc0diumU9wD7-gMzva8Rp1EJwb3KUiINOa05LWYeQpvP0FyHpNqKWmQtbY-Vn_h7UgxqcQlwWwltPiQ5l2Dac7yALxWUyV9hBQad_x07tPlhZO1OMf_qCyhfAz9zKsX-_YOPvVE5XHRCe9pW00)


_Enjoy,_
Regards.

**Comment by harikrishna553** [comment]
@The-Lum Thanks for the work around
