### ISSUE TITLE
skinparam NoteBorderColor is not working

### ISSUE THREAD

**Issue by harikrishna553** [plantuml/plantuml#1228]
skinparam NoteBorderColor is not working, confirmed the same with below snippet.

```
@startuml

skinparam NoteBorderColor red
skinparam NoteFontStyle italic
skinparam NoteBorderThickness 3


scale 1.5

Client -> Server: Client send employees information
Server -> Client: Server process employees data and send response

note left of Client 
Sample notes
end note

@enduml
```

Reference : https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#note

**Comment by The-Lum** [comment]
Hello @harikrishna553,

Same remark as #1227, you can now use `style`, as:

```puml
@startuml
<style>
note {
  LineColor #red
  FontStyle italic
  LineThickness 3
}
</style>

scale 1.5

Client -> Server: Client send employees information
Server -> Client: Server process employees data and send response

note left of Client 
Sample notes
end note

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/HP312i9034Jl-Og0PnKHBwMKGi6Jj_e3IvlYuZOfcoWKyT_TjHLlOV9cXgHMSz4UOu1IRGvK0OiHlW3nufaQ2H9n4wbFmbdOsWoXDnTyjpBNc-_kJAfuX3UK-pK7j7C9FUnE04tmn8RR2bkAJue5heeIzqZZ56GcKlGyI1oTUM5OoEnPs6BruXIbosr_M-_CeKj9txX8EWahmN9AeC5GXbyZj2xv2FDE8VDv0gZJcDxm0G00)](https://www.planttext.com/?text=HP312i9034Jl-Og0PnKHBwMKGi6Jj_e3IvlYuZOfcoWKyT_TjHLlOV9cXgHMSz4UOu1IRGvK0OiHlW3nufaQ2H9n4wbFmbdOsWoXDnTyjpBNc-_kJAfuX3UK-pK7j7C9FUnE04tmn8RR2bkAJue5heeIzqZZ56GcKlGyI1oTUM5OoEnPs6BruXIbosr_M-_CeKj9txX8EWahmN9AeC5GXbyZj2xv2FDE8VDv0gZJcDxm0G00)

Regards.
