### ISSUE TITLE
'help preprocessors' command is not working 

### ISSUE THREAD

**Issue by harikrishna553** [plantuml/plantuml#1232]
'help preprocessors' is not working. As per help command output, it should print all the possible preprocessors.

![helpCommand](https://user-images.githubusercontent.com/4006916/209349622-e7260c0d-44ab-40ab-ac49-e0e158fbdc1f.png)

**Comment by The-Lum** [comment]
@arnaudroques, and all,

1. Unfortunately, I use it (`help themes`) for the creation of the PlantUML Theme Gallery...
See:
    - #1331
    - #652

2. And for example `help font` is also used for verification of installed fonts.

- What would be the workarounds?

Regards,
Th.

**Comment by arnaudroques** [comment]
Ok, we are going to put back `help themes` et `help font`, since they are useful.
About the other `help` directive, I'm not so sure.
