### ISSUE TITLE
Null pointer exception,  possible erroneous output from newpage

### ISSUE THREAD

**Issue by walthaas** [plantuml/plantuml#124]
The following input:
```
@startuml
package "One" {
  entity foo {
  }
}
newpage
package "Two" {
  entity bar {
  }
}
bar ||--|| foo
@enduml

```
throws a null pointer exception after producing correct output.  If the bar||--||foo line is moved inside package "Two" then the connected entity foo is shown in package "Two" which arguably it should not be.  The null pointer exception was introduced in plantuml.1.2018.5.jar, it does not occur in plantuml.1.2018.3.jar.

**Comment by arnaudroques** [comment]
Thanks for the report.
Can you try with last beta http://beta.plantuml.net/plantuml.jar ?
The NPE should be fixed there.
Thanks again !

**Comment by walthaas** [comment]
The NPE is gone from the beta.  Thanks for the fast response!
