### ISSUE TITLE
Remove directive does not work when element name starts with `$`

### ISSUE THREAD

**Issue by BenceSzalai** [plantuml/plantuml#1240]
The title says it, see example [here](http://www.plantuml.com/plantuml/uml/LSmn2a8n48JXVa_nYkWvdk01RAmb9DDj4jdDin7lRY53rd9-FcRtcMqUJKMAPlSjNOTgjktz4KCRBx0G_5PQW2M0zFV0Gl2uzmhpCWm1XKfuki4A-WoAYUHyQK-OvruN2b5aHwz7qoy0).

**Comment by The-Lum** [comment]
Hi @BenceSzalai, and all,

You are right... Because `$` is reserved for `$tag`!

Could you have a look on:
```puml
@startuml
class $Dollar $tag
remove $tag
@enduml
```

Or **_Just for Fun:_**
```puml
@startuml
class $Dollar $Dollar 
remove $Dollar
@enduml
```
---

- Do you really have class names that start with dollar?

Regards.

**Comment by BenceSzalai** [comment]
Right, I've realised myself later that $ had special meaning. So basically it is not really a bug, but maybe a nuance, that it is valid to declare a class with the name stating with $. I mean if that is reserved, it should not work. If not reserved, it should work the same way as any other names.

Answering your question, I only used $ as a prefix to indicate some extra meaning, switched to `_` and it is fine.

I've tried to add a note to the documentation on alphadoc.plantuml.com, but not sure about the process there. It let me edit the section, but there's no indication about what to do next...

**Comment by The-Lum** [comment]
>So can you tell me what really is a $tag?

Currently it is only documented on `component`, see doc. here:
- https://plantuml.com/component-diagram

See also ref. here:
- [QA-7337](https://forum.plantuml.net/7337)
- [QA-11052](https://forum.plantuml.net/11052)


Then it raises some issues about name with `$` prefix.
Regards.

**Comment by BenceSzalai** [comment]
@The-Lum Awesome, thanks for the help learning this great tool!

May I ask f the tag system is global, i mean available in all diagram types? If so probably documentation should be under https://plantuml.com/commons instead, isn't it?

I can see the documentation can be edited by anyone, but the process is not clear? Is there documentation about updating the documentation maybe?

**Comment by arnaudroques** [comment]
> I can see the documentation can be edited by anyone, but the process is not clear? Is there documentation about updating the documentation maybe?

Yes, anyone can edit the documentation. We just validate changes on your side and then publish them to the official website.

The process is not clear because there is no process :-)
We really count on people to help us on this side because we are not-so-good about doc...
If you wish, you can even create a page http://alphadoc.plantuml.com/doc/dokuwiki/en/update-documentation about updating the documentation. Please be creative :-)

Thanks!

**Comment by BenceSzalai** [comment]
I've added documentation for Class diagrams and some notes about naming for Component diagram as well.
