### ISSUE TITLE
`package` and `together` closes the parent `namespace` in class diagram

### ISSUE THREAD

**Issue by BenceSzalai** [plantuml/plantuml#1242]
See demo [here](https://www.plantuml.com/plantuml/umla/XL8zRuCm4Dtv5M-ZbP8g3Lk6AgLxktR4u0jO0HlP9bIA-E-z2of5xP09tRjx7xxZ6ABoSUZQnAgEGgygmliUrmIeMXK2yXsk4rVSEQkQy0dffGWyZf8QTJ5ky1XDR11TJR4XZuV1Lgxho4PO-eeRAAlnW_IUX1FG6alCGI1wF8ZemXUB9S0p1rZN-xcUVYDcWYJfgzPWEgCk65kZc0guapo7DMaEmGRy1Ndl_iNy4oWLJNnuQ0VhcCRoPdwBJ8Yjm2M9LyzRdCsUX9KF4UQ4aKJpB9eyhG8AxkTPmJge7GMKgfAkn9QSomtkHHEP7RRR5zm44qOoc221Lb4se0jP5dT3tKGn61NFCEWXIo9zM9yzMvtzxRRrAJcIrVntV0C0).

Basically the closing `}` of a `together { ... }` or `package PackageName { ... }` inside a `namespace NamespaceName { ... }` block closes the parent Namespace block as well. So anything added after becomes part of the grand-parent namespace.

However if we have a link, that points to the subsequent elements with their fully qualified name, the elements go back into that namespace. This however does not change the fact that the file will be technically in lack of a closing `}`. To add more items to the same Namespace it needs to be opened again (`namespace NamespaceName {`) after the `together` or `package` is closed.

**Comment by arnaudroques** [comment]
This [should be fixed in V1.2023.0](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSfBp4qjBaXCJbNmCrAevb9GICv9B2vMS39GgAu5yahoqrDBCbABm59mIKEm989l1E7N8hGRWqI0N2JZZL7CS3Q4wQdbSaZDIm6w1G00).
Tell us if you find other issues!

**Comment by BenceSzalai** [comment]
Great, thanks! I can see it made explicit that packages and namespaces don't play together as well: `Cannot mix packages and namespaces.`
