### ISSUE TITLE
Table | character can't be escaped with \ or anything else

### ISSUE THREAD

**Issue by dylan-chong** [plantuml/plantuml#125]
```
note right of B
  | A         | B   |
  | --------- | --- |
  | P(C\|D)   | E   |
end note
```

<img width="119" alt="screen shot 2018-05-20 at 7 02 42 pm" src="https://user-images.githubusercontent.com/17482349/40276517-6a36cbe2-5c60-11e8-9e15-2a2e5c2f50dd.png">

The image above shows the `\|` does not represent an escaped `|` character. You also can't escape with `&vert;`

**Comment by arnaudroques** [comment]
Thanks for the feedback.
With last beta http://beta.plantuml.com/plantuml.jar you can now have:

```
@startuml
class B
note right of B
  | A         | B   |
  | P(C\|D)   | E   |
end note
@enduml
```

Is this what you are expecting ?

**Comment by dylan-chong** [comment]
Yes! Thank you!
