### ISSUE TITLE
[v1.2023.0] Style management (error on `carbon-gray` theme)

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1250]
Hello @arnaudroques, and all,

With the update of the theme Gallery, here are first tests with the `v1.2023.0` and the theme `carbon-gray` seems to be broken...

Here is minimal example:
```puml
!theme carbon-gray
component a
```
>[![](https://www.planttext.com/api/plantuml/svg/Kop9ICrDLKXEB4hApzDDBqgiv4hEpot8pqlDAr581000)](https://www.planttext.com/?text=Kop9ICrDLKXEB4hApzDDBqgiv4hEpot8pqlDAr581000)

See also error here _(from Action on theme Gallery)_:
```r3
</themes/puml-theme-carbon-gray.puml>:770:error:Error in style definition: bad definition
net.sourceforge.plantuml.style.parser.StyleParsingException: bad definition
	at net.sourceforge.plantuml.style.parser.StyleParser.readValue(StyleParser.java:190)
	at net.sourceforge.plantuml.style.parser.StyleParser.parse(StyleParser.java:108)
	at net.sourceforge.plantuml.jsondiagram.StyleExtractor.applyStyles(StyleExtractor.java:116)
	at net.sourceforge.plantuml.jsondiagram.JsonDiagramFactory.createSystem(JsonDiagramFactory.java:94)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:[14](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:15)0)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:181)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:[16](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:17)8)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:5[19](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:20))
	at net.sourceforge.plantuml.Run.processArgs(Run.java:402)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:369)
	at net.sourceforge.plantuml.Run.main(Run.java:[20](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:21)4)
net.sourceforge.plantuml.style.parser.StyleParsingException: Cannot understand <
	at net.sourceforge.plantuml.style.parser.StyleParser.parse(StyleParser.java:256)
	at net.sourceforge.plantuml.style.parser.StyleParser.parse(StyleParser.java:61)
	at net.sourceforge.plantuml.jsondiagram.StyleExtractor.applyStyles(StyleExtractor.java:116)
	at net.sourceforge.plantuml.jsondiagram.JsonDiagramFactory.createSystem(JsonDiagramFactory.java:94)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:140)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:181)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:168)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:519)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:402)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:[36](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:37)9)
	at net.sourceforge.plantuml.Run.main(Run.java:204)
```
See all log here:
- [puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:14](https://github.com/The-Lum/puml-themes-gallery/actions/runs/3883188154/jobs/6624205160#step:4:14)

_I search what is broken..._

Regards.

**Comment by arnaudroques** [comment]
> I search what is broken...

The issue is on our side: we have completely rewritten the style parser.
Don't waste any time: we are going to investigate.

Thanks for the report!

**Comment by arnaudroques** [comment]
It [has just been fixed](https://github.com/plantuml/plantuml/commit/cc840383e3a8be213350b3e7142ac2491d6c7be6).
Some other themes may have also issues: could you tell us if you find any errors?
Thanks!

**Comment by The-Lum** [comment]
_[Just for traceability]_

FYI @bharatrajagopalan _(initial author of the `carbon-gray` theme [#1059, #1060])_
See minor change/fix _(to be conform with the new PlantUML style parser)_ on your theme here: 
- https://github.com/plantuml/plantuml/commit/cc840383e3a8be213350b3e7142ac2491d6c7be6#diff-6d50778129cdb9f327928ba10313b69d72162fdf6f9e0707ff0e0981d7c8e749

Regards.

**Comment by The-Lum** [comment]
Hi @arnaudroques,

Here is a complement:
- It seems that `style` is without effect on `JSON` or `YAML` diagram.

See example on the corresponding doc pages. and here:
```puml
@startyaml
<style>
yamlDiagram {
  node {
    BackGroundColor lightblue
    LineColor lightblue
    FontName Helvetica
    FontColor red
    FontSize 18
    FontStyle bold
    BackGroundColor Khaki
    RoundCorner 0
    LineThickness 2
    LineStyle 10;5
    separator {
      LineThickness 0.5
      LineColor black
      LineStyle 1;5
    }
  }
  arrow {
    BackGroundColor lightblue
    LineColor green
    LineThickness 2
    LineStyle 2;5
  }
}
</style>
  -
    name: Mark McGwire
    hr:   65
    avg:  0.278
  -
    name: Sammy Sosa
    hr:   63
    avg:  0.288

@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/bLB1JiCm3BtdAtn1sWwKjjEWAXEQ034a64YCuovkQxLHqmIvsQQ1zkzqJLN6j0D4IcG_syylJgQrHRPRh9ImqYg2fNvDQk8rPM0qD2k6m0lzSEG52LaCbdgGhfX9MrWJrzBe6CuwQp0SYabjjufkn9xoNcBEMC6N0D0cezO0kCMqdB5PwUpEACEWP5xOHAseZJvBJQVm1wFj2rO4ZwJMP6MAFUpIcR8UMSXFWY3wyVUY834gEwdWgS1Ijf4t1x8c1h_Nyrx8jDHKrn3scACC_Ejn2zNqWOos8NENF2xqlV41xjecgj5nW7QK7UDEk8tCPlFFqULCfFyWFsnxxSHEJ2wwXmCuRvDqC-iOviWbpDFPHhBhKN3Sd9TE8gxpnlEzy2ewgbjWLMrXOMeyh1hzheeY8QQai_rV-GO0)](https://www.planttext.com/?text=bLB1JiCm3BtdAtn1sWwKjjEWAXEQ034a64YCuovkQxLHqmIvsQQ1zkzqJLN6j0D4IcG_syylJgQrHRPRh9ImqYg2fNvDQk8rPM0qD2k6m0lzSEG52LaCbdgGhfX9MrWJrzBe6CuwQp0SYabjjufkn9xoNcBEMC6N0D0cezO0kCMqdB5PwUpEACEWP5xOHAseZJvBJQVm1wFj2rO4ZwJMP6MAFUpIcR8UMSXFWY3wyVUY834gEwdWgS1Ijf4t1x8c1h_Nyrx8jDHKrn3scACC_Ejn2zNqWOos8NENF2xqlV41xjecgj5nW7QK7UDEk8tCPlFFqULCfFyWFsnxxSHEJ2wwXmCuRvDqC-iOviWbpDFPHhBhKN3Sd9TE8gxpnlEzy2ewgbjWLMrXOMeyh1hzheeY8QQai_rV-GO0)

_Thanks for your analyse and correction..._
Regards.

**Comment by The-Lum** [comment]
Hi @arnaudroques,

_A line of research..._

Just change 
```puml
    LineStyle 10;5
```
to
```puml
    LineStyle 10-5
```
- How manage this _[not backward compatible]_ change? 
On all the doc. and all theme using this functionality...
_[to debate: it is not a big issue, but just know it]_

```puml
@startyaml
<style>
yamlDiagram {
  node {
    BackGroundColor lightblue
    LineColor lightblue
    FontName Helvetica
    FontColor red
    FontSize 18
    FontStyle bold
    BackGroundColor Khaki
    RoundCorner 0
    LineThickness 2
    LineStyle 10-5
    separator {
      LineThickness 0.5
      LineColor black
      LineStyle 1-5
    }
  }
  arrow {
    BackGroundColor lightblue
    LineColor green
    LineThickness 2
    LineStyle 2-5
  }
}
</style>
  -
    name: Mark McGwire
    hr:   65
    avg:  0.278
  -
    name: Sammy Sosa
    hr:   63
    avg:  0.288

@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/bL9HIyCm47xFhxWNONjORJkcfGmPAaxGAJWVzt9jZpOqJUIQRKpPVxThIfrZ3nf8kFlkxhilbyngYsntM2bXfLK4A_sQrCGRoi1eQ5OCWHVwuTWB4h8OhFGWNJEJjh0XhgNHCLnqrc0u5DFQxXJTY0FblSISiO8l0Q1DHgq1S8jfEMUprjcTKOP1oRomYLfJ6tsMcixX3qRR5wm87abjoCeKUzYbCsKzifIV147qunz4GM9KTbR1Ku6bR2Dl3cHD37wlvxsGQQcfhY7iCKSP-AD92zNqWOos8NENF2tqlSaHxjecgj5nX7QK7UDUk8tCPllFqULCfFyWFsnxxSLUJ2-xXmCOjKcwcNKC2-GI5kbyAzdrA3XkpYid4JTvu_bUU1sTr2sngdQmD3KULur_LqMH43FIsU6lV0C0)](https://www.planttext.com/?text=bL9HIyCm47xFhxWNONjORJkcfGmPAaxGAJWVzt9jZpOqJUIQRKpPVxThIfrZ3nf8kFlkxhilbyngYsntM2bXfLK4A_sQrCGRoi1eQ5OCWHVwuTWB4h8OhFGWNJEJjh0XhgNHCLnqrc0u5DFQxXJTY0FblSISiO8l0Q1DHgq1S8jfEMUprjcTKOP1oRomYLfJ6tsMcixX3qRR5wm87abjoCeKUzYbCsKzifIV147qunz4GM9KTbR1Ku6bR2Dl3cHD37wlvxsGQQcfhY7iCKSP-AD92zNqWOos8NENF2tqlSaHxjecgj5nX7QK7UDUk8tCPllFqULCfFyWFsnxxSLUJ2-xXmCOjKcwcNKC2-GI5kbyAzdrA3XkpYid4JTvu_bUU1sTr2sngdQmD3KULur_LqMH43FIsU6lV0C0)


Regards.

**Comment by The-Lum** [comment]
_Test by test..._

Just adding an empty style... _[and this is the drama]_
```puml
<style>
</style>
```

---
Could you compare:
```
@startyaml
!theme amiga
  -
    name: Mark McGwire
    hr:   65
    avg:  0.278
  -
    name: Sammy Sosa
    hr:   63
    avg:  0.288
@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/NOyz2uD038Rt-nNfKD2XuWTjvIQtJjB1rILgqADUXDpLuh-lIeUs6KAU5vx0MpYFuXUqe_B6ZmGrtnj7CbC74yCw6f8eZTCiIXhocDGSj4yHOWypYJCJQpX-hY0CrS4FP0dGcXuLm4bjFnWjQIXH7b2sjvSHskD1zBelvnrmxbUAe_IQ_taLMhj0DJdyjh9VAy-LAeYxhSeR)](https://www.planttext.com/?text=NOyz2uD038Rt-nNfKD2XuWTjvIQtJjB1rILgqADUXDpLuh-lIeUs6KAU5vx0MpYFuXUqe_B6ZmGrtnj7CbC74yCw6f8eZTCiIXhocDGSj4yHOWypYJCJQpX-hY0CrS4FP0dGcXuLm4bjFnWjQIXH7b2sjvSHskD1zBelvnrmxbUAe_IQ_taLMhj0DJdyjh9VAy-LAeYxhSeR)

VS

```puml
@startyaml
!theme amiga
<style>
</style>
  -
    name: Mark McGwire
    hr:   65
    avg:  0.278
  -
    name: Sammy Sosa
    hr:   63
    avg:  0.288
@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/NO-z2eD048JxUufD4T0YnX-Io271BfMaiBLPTT4ZtWbx5uDl7vKKIROOPWQ-XScjGtOpwa4uvGQ2ojnhIpnH2wE1vIH4GHp6IH3Lv32gZDSycSauc8Yj6es4_STvlYzshYTDW5frA3Bhve6k8Zj-3C11h4yDQf9G83-WQ6ulnRJLFSj5pwSjuDGjAGpYI_h7bQZr3ELeyPjAVgaq5I8dqwxRtW00)](https://www.planttext.com/?text=NO-z2eD048JxUufD4T0YnX-Io271BfMaiBLPTT4ZtWbx5uDl7vKKIROOPWQ-XScjGtOpwa4uvGQ2ojnhIpnH2wE1vIH4GHp6IH3Lv32gZDSycSauc8Yj6es4_STvlYzshYTDW5frA3Bhve6k8Zj-3C11h4yDQf9G83-WQ6ulnRJLFSj5pwSjuDGjAGpYI_h7bQZr3ELeyPjAVgaq5I8dqwxRtW00)

---

Thanks for your work...

**Comment by arnaudroques** [comment]
> * How manage this _[not backward compatible]_ change?

I'm afraid that this will be an exception where we are **not** going to be backward compatible.

This is because we are now fully supporting real CSS format:

```
<style>
yamlDiagram {
  node {
    BackGroundColor: lightblue;
    LineColor: lightblue;
    FontName: Helvetica;
    FontColor: red;
    FontSize: 18;
    FontStyle: bold;
    BackGroundColor: Khaki;
    RoundCorner: 0;
    LineThickness: 2;
    LineStyle: 10-5;
    separator {
      LineThickness: 0.5;
      LineColor: black;
      LineStyle: "1;5";
    }
  }
  arrow { BackGroundColor: lightblue; LineColor: green; LineThickness: 2; LineStyle: "2;5"; }
}
</style>
```

The legacy "close-to-CSS" format is also supported:

```
<style>
yamlDiagram {
  node {
    BackGroundColor lightblue
    LineColor lightblue
    FontName Helvetica
    FontColor red
    FontSize 18
    FontStyle bold
    BackGroundColor Khaki
    RoundCorner 0
    LineThickness 2
    LineStyle "10;5"
    separator {
      LineThickness 0.5
      LineColor black
      LineStyle "1;5"
    }
  }
  arrow {
    BackGroundColor lightblue
    LineColor green
    LineThickness 2
    LineStyle 2-5
  }
}
</style>
```

So now `LineStyle 10;5` is really too confusing for our parser, so you have to use `LineStyle 10-5` or `LineStyle "10;5"`

I think it's an acceptable solution, since it only breaks the rendering, not the diagram itself (and only if LineStyle is used).
Any though?

PS: Thanks about the `<style></style>` issue, we're going to fix it also.

**Comment by The-Lum** [comment]
Hi,

1. If that is to be fully compliant with CSS style, a **not backward compatibility** is acceptable...
2. Perhaps the `<style></style>` issue performs the `StyleParsingException: Cannot understand <`

_To be continued._

**Comment by The-Lum** [comment]
Last issue fixed by:
- https://github.com/plantuml/plantuml/commit/97c7f1ed34f1dfdf25666ef18ee01192acd8aa2b#diff-02b6ce6c93dc5672afedb3367e7a12380f610b8c32109e5f94c2f10200eb3563

Thanks, 👍 
_I can continue to improve theme..._
