### ISSUE TITLE
Docker image to support arm64 architecture

### ISSUE THREAD

**Issue by denisa** [plantuml/plantuml#1252]
while the existing docker image works on Macs with Apple Silicon (M1, M2, …), docker warns that `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Docker (and the docker-build-push action) supports multi-architecture images.

**Comment by arnaudroques** [comment]
Probably fixed by https://github.com/plantuml/plantuml/pull/1262
