### ISSUE TITLE
User defined `<<<style>>>` only works for empty elements

### ISSUE THREAD

**Issue by BenceSzalai** [plantuml/plantuml#1253]
See the subject feature [here](https://forum.plantuml.net/14692/user-defined-style-applied-on-class-also-becomes-stereotype).

See issue demo [here](http://www.plantuml.com/plantuml/uml/VOvBJe0m443NzXHp0JKit3K4yRDIO-G4JPaGOZzaMc8QmjqbjE4ZO9SpxxrEuRmWtsl5kFD1OSwa4iuzjw8XeM5WCBqlsvlwoP91WknX7jtfCFE9kDaY4v5UAUHtGt6bB84CmYpBLsjyDJTAg-hTEDA4SJgoaV7xxNdmg5g9xo7gdFDqJPwV0PL7GWiBjOVOYV6YEn_sNHZ6otJ2L_eS_i2VjzRWtowx3gz64YxvJxBT8Gnm2zsqoFxv8ed9EsW5chhNwXS0).

Notice how `AliceMyStyle` and `AliceMyStyleEmpty` are styled, but `AliceMyStyleNewLine` and `AliceMyStyleProp` are not formatted according to the assigned `<<<mystyle>>>`. Stereotype based formatting (`<<mystyle>>`) however works for both empty and non empty elements.

**Comment by BenceSzalai** [comment]
Looks like it has been fixed already! :)
Now I'm only have to wait for the release! :)

**Comment by arnaudroques** [comment]
One big question: when should we close the issue?
When it's fixed or when it's released? :-)

**Comment by BenceSzalai** [comment]
That's a good question, I don't know what is the best practice, or if there is a one size fits all answer. But I think issues are primarily a tracking device, so after the fix is verified they should be fine to be closed.

For PlantUML the development build can be tested online even before a release, so it is one more reason for immediate closing. I think many other software teams close issues as soon as possible when the dev branch has the fix and is planned for release. The actual release date is secondary (from tracking perspective).

If someone is really interested if the given fix has been released yet they can always compare the date of the latest release with the issue closing.

Not the best for visibility, but as you are a small team building a complicated tool I think minimising your overhead should be the priority, which in this case suggest to close as soon as possible.

Some tools have more detailed tagging system in place, where tags indicate which version the issue was confirmed with and which version will include / included the fix. But for your case this would not bring much benefit, so my 2cents is close them as soon as the fix has landed in the main branch and is expected to be included in the next release.

**Comment by BenceSzalai** [comment]
Fix has been confirmed in the latest [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) build on live server.

Fix is scheduled for next release, expected to be available in [v1.2023.1](https://github.com/plantuml/plantuml/releases/tag/v1.2023.1).
