### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [plantuml/plantuml#126]
Hi,

Since this app is GPL v3+ licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/), an app store with only FLOSS apps? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

There is already a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues/455) opened.

**Comment by davidhedlund** [comment]
@Poussinou Thanks.

**Comment by arnaudroques** [comment]
Hi,
Why not ? However, I'm not sure to understand the full implication of this.
Note that we are not related to ru.gelin.android.plantuml
PlantUML is written in regular Java and it does not compile on Android...

**Comment by Poussinou** [comment]
Hum I didn't really checked the source code of this repo, I just came here because of this request for packaging (I'm currently checking a lot of this requests, I do a really repetitive work here)

So this isn't an Android application, we obviously cannot include it in F-Droid...

Sorry for the inconvenience

**Comment by davidhedlund** [comment]
@Poussinou PlantUML for Android - https://play.google.com/store/apps/details?id=ru.gelin.android.plantuml&hl=en_US

**Comment by Poussinou** [comment]
In fact the source code of this application was [here](https://code.google.com/archive/p/plantuml-android/) but it's too old, the RFP has been closed.
