### ISSUE TITLE
azure stdlib is not found: cannot include <azure/AzureCommon>

### ISSUE THREAD

**Issue by ggrossetie** [plantuml/plantuml#1263]
Version: 1.2023.0

You can see an error on the documentation page:

<img width="926" alt="Capture d’écran 2023-01-13 à 20 23 49" src="https://user-images.githubusercontent.com/333276/212412488-2da1a65b-b356-40ca-8bec-3ed5788a4a51.png">

https://plantuml.com/fr/stdlib

It seems to be fixed in 1.2023.1beta1 but there's another error:

```
cannot include <azure/Analytics/AzureStreamAnalytics>
```

https://www.plantuml.com/plantuml/uml/dLB1IiGm4BtdAyPwgR2B5S63oh9YbHKL5xjwdssdDPWcIp9PqAytxLAbMK7m4fWtRzwRUMJk62txLea3gKlbAu9B_FIMZg-wzzgqhT6p_QP6zS6oT3lQpPOqB_pwJsB1bh3z1lVvEJAkqP4R_5rhN1w4XQAQWGrOsRmnLD9IoT9e8R09vf3aj9KbGI5Rhv2DJG0TL3teuB2kQo56kwOrMkhi1c02oMs0eCEIK2plp-6HAbGgsC02o_U7eAKTmIlfojYxwW9EOVNYagD8cQtSHCgh0FrVEOejTUCwIEuOiBGcdEkaRZgVCoX-D8OeK-Dvutae0-sf1s28lfiycMHP1i_zj1X2d4vd48SsQiPtYvZTiwBbHJprAocgUyxu434FsNKV-Gi0

**Comment by arnaudroques** [comment]
Thanks for the report!
@Potherca any idea?

**Comment by Potherca** [comment]
The icon for Azure Stream Analytics was present in the project twice.
The manually added duplicate `AzureStreamAnalytics` was removed, hence the error.
The correct icon to use is `<azure/Analytics/AzureStreamAnalyticsJob>`.

[![](https://www.plantuml.com/plantuml/png/dP1FImCn4CNl-HJZUgdGOaNme58gLgb_n6Ahz-bcjWRpfoIJWdvwirjMsRGWU0dCos_UpBnnOFGSZHO7ofOwIe9B_8gUZg_gzzePu-nezzEY_cHLXYrsio7BqxZy4vop9pG_uhtRqp91nYK62kqAmRWmIQ3GL36m0wzMxmnIUIfPEIi4hiWo51FQg99WhapKoCuNW05a8mOuhAfAYCwwlGezrUDQeG_5RPAWrefKp1xEuOaaQft6m1JBZyVaPGF16rdf_9syW5DOl8RYA7DchzQPyo99_tVUJQuNkb9otK8myovT79HTrQFEODxQ_ARPSv7NaTioOS-D06twTUT9VpWSmalJBTeS1uCHvBbrFlFJHKutLBQyoBlsGbdTCDr3n9YiZ4P_0m00)](https://www.plantuml.com/plantuml/uml/dP1FImCn4CNl-HJZUgdGOaNme58gLgb_n6Ahz-bcjWRpfoIJWdvwirjMsRGWU0dCos_UpBnnOFGSZHO7ofOwIe9B_8gUZg_gzzePu-nezzEY_cHLXYrsio7BqxZy4vop9pG_uhtRqp91nYK62kqAmRWmIQ3GL36m0wzMxmnIUIfPEIi4hiWo51FQg99WhapKoCuNW05a8mOuhAfAYCwwlGezrUDQeG_5RPAWrefKp1xEuOaaQft6m1JBZyVaPGF16rdf_9syW5DOl8RYA7DchzQPyo99_tVUJQuNkb9otK8myovT79HTrQFEODxQ_ARPSv7NaTioOS-D06twTUT9VpWSmalJBTeS1uCHvBbrFlFJHKutLBQyoBlsGbdTCDr3n9YiZ4P_0m00)

**Comment by craigwardman** [comment]
Looks like the "AzureCommon" issue was caused by this:
https://github.com/plantuml/plantuml-stdlib/issues/70

Which has now been fixed https://github.com/plantuml/plantuml-stdlib/pull/71

Does anyone know the timescales for when the latest plantuml-stdlib will be pulled into plantuml and released?
