### ISSUE TITLE
Gantt diagram - Can't close day in the period of opened days

### ISSUE THREAD

**Issue by mquan86** [plantuml/plantuml#1278]
In Gantt diagram. When we have a period with opened days, we can't close any day in that period.

Real life scenario:
- Sat and Sun is closed  day.
- Start for day x, we want to open overtime work on weekend.
- Then we need to close certain days or a period due to public holiday or some special circumstance.

I have below example:
```
@startgantt
project starts 2023-02-01
saturday are closed
sunday are closed

2023-02-18 to 2023-06-01 is opened
2023-02-21 is closed
2023-02-25 to 2023-03-30 is closed

[Testing] requires 60 days
@endgantt
```

https://www.plantuml.com/plantuml/uml/NOv12i8m44NtESM_G25DL5ps4Ex4HMY64f59dPailBsXQ0MtZ_Tc_gIMn9R4PcwLUgVPi255y24EFWn-T9giIKul927CZwgKdJR-8-vRZ6TO_VIdtgCewafCULV2yQV48Vgkx6Uk5r8hlDmWz6n5I77mwC_KJSHv6_i6

Of course that I can define in detail open from which day and close from which day one by one, but that is boilerplate and not convenient.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be [fixed with last version](https://www.plantuml.com/plantuml/uml/NOzD2i8m44RtSugvG20_LLps4Ex4HMY64f6apamMtjvGMYhTFjw3xnj58-iSYoeiN5yqAQv8q5iVZFN6Ef2eZLFyOcJ2wLs54aWh9m9xuMweTUi7umRCWdMXqfrTyQx3BJpWvUY22VPFWSUTH7EPdyZqQPb9y6gnBn0OgQJrmGy0).
