### ISSUE TITLE
Doc on Doxygen integration is incorrect

### ISSUE THREAD

**Issue by AndyDentFree** [plantuml/plantuml#128]
The [page on Doxygen](http://plantuml.com/doxygen) says _Doxygen does not understand the @startuml and @enduml tags_ and offers a workaround.

That is not correct and has been incorrect for a long time. See the Doxygen [startuml docs](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdstartuml)

However, there *is* a bug if you are trying to use include files, as noted [here](https://bugzilla.gnome.org/show_bug.cgi?id=795962)

**Comment by albert-github** [comment]
It appeared to be a typo in the configuration of OP.
