### ISSUE TITLE
together behaves different starting from 1.2023.0

### ISSUE THREAD

**Issue by b0riskleiman** [plantuml/plantuml#1282]
Code below starts causing an error  starting from 1.2023.0:

together {
        node "A" as a { 
        }
        node "b" as b {
        }
        node "c" as c {
        }
        node "d" as d {
        }
    }

**Comment by The-Lum** [comment]
Hi all,

Seems to be a side effect of the fixed issues:
- #1242
- #1255

See:
- https://github.com/plantuml/plantuml/commit/eac7a29c67d8810ffa2323ce66d5e00271e4586d#diff-6391965407684d8fb09e555c3de03e1871155edefda505b2866fa28aaad56799

Here is a minimal example:
```puml
@startuml
together {
  node "A" as a {
    card c
  }
  node "b" as b
}
@enduml
```

Regards.

**Comment by kickingvegas** [comment]
Dunno if this is related, but I also can not nest `together` statements. This is used by this codebase which defines a function `pair` and then uses in within a `together` statement. https://github.com/zhmylove/genealogy

Get the resultant output.

![park-family-tree](https://user-images.githubusercontent.com/395760/216702891-7fc0c2ab-ba5a-44d2-b421-63271b2ade41.svg)

**Comment by arnaudroques** [comment]
> Dunno if this is related, but I also can not nest `together` statements

Yes, you are right, this is 100% related.
We have started a big refactoring concerning together/namespace/package. (see https://plantuml.com/news )

So 1.2023.0 and 1.2023.1 are impacted by changes in `together`.
We did a too naive implementation of `together` in those versions and we are going to fix this issue and restore the ability to nest `together` / `namespace` / `package`.

In the meantime, the best option for you is to stick to 1.2022.14
Sorry about that!

**Comment by kickingvegas** [comment]
@arnaudroques thanks for confirming. Any estimate on when a fix will be rolled out?

**Comment by arnaudroques** [comment]
> @arnaudroques thanks for confirming. Any estimate on when a fix will be rolled out?
>

[Should be fixed now](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIh9JqyjoKWjKgZcKb38oqz9LL1oL598B5P818a0GN9YKOf2Cf1P2rUG15QGn5NBvP2Qbm8q1G00).

There are probably other issues: thanks for posting in that case :-)
