### ISSUE TITLE
Possible regression with class alias declaration

### ISSUE THREAD

**Issue by bkryza** [plantuml/plantuml#1284]
Before version `1.2023.2beta1` it was possible to do the following:

```plantuml
@startuml
legend
<size:8> Rendered with Plantuml Version %version() </size>
end legend

class "A" as a123

class a123 {
  int a
}
@enduml
```

which generated class named `A` on my system with version `1.2020.02`.

The latest beta version however generates from this code class named `a123` in the diagram [see here for example](http://www.plantuml.com/plantuml/uml/DOmn2W8n44NxVuhFWg2Lg8t8igmt40lxmGmQY14oKK7nxavGkpV3Vs-qAgNUBWb8Uj8Sq5jywcOzSE-N5Wryn7hcBabkEnwqMBncJkvVcCxOpvipm0N-AZWcCMEtxIX6MInN_rTZla36N2bu0wCBNlu0)

Is this change an expected behavior and the above code will not work anymore in 1.2023?

Thanks!

**Comment by arnaudroques** [comment]
Thanks for the feedback. 
It is a regression and we are going to fix it.
This is related to https://plantuml.com/news

**Comment by bkryza** [comment]
Great, thanks for clarification!

**Comment by arnaudroques** [comment]
This should [be fixed now](http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSf9JK_DI-6oASwiIhMoi5Dmown8JL4epop9K0Z8ISm3gL48IoqgpipFKr0jWp0qD1Liz44QxBY0UXMWHd0bvoGM5oieEIef91Oh91eQ6KE486o5QYu5XSoy4eL4hbek1w1weC40).
Tell us if you find other issues!
Thanks
