### ISSUE TITLE
(Activity diagram) Repeat while has no guard

### ISSUE THREAD

**Issue by 0b10** [plantuml/plantuml#129]
In an activity diagram, using repeat while has no guard, so there is no means to determine which path to take.

Current syntax:
```
repeat
    :Activity;
repeat while (Question?)
```

Desired syntax:
```
repeat
    :Activity;
repeat while (Question?) is (Yes)
```

**Comment by imshenwei** [comment]
have no clue bout the question, would you please clarify your question again?
what i have is this
<img width="144" alt="image" src="https://user-images.githubusercontent.com/64460759/188301721-3320bfdf-c116-46c9-9b3b-fac6bf8bb0c2.png">
