### ISSUE TITLE
Can we update tupadr3 in the stdlib please?

### ISSUE THREAD

**Issue by tfc** [plantuml/plantuml#1299]
Hi,

i'd like to help by doing this myself an PRing the update, but as the compression scripts aren't freely available, I can only ask via an issue.

The `tupadr` icon package .repx in the stdlib folder is ~3 years old. This way some nice icons are missing.

Can you please update this stdlib?

**Comment by arnaudroques** [comment]
> The `tupadr` icon package .repx in the stdlib folder is ~3 years old. This way some nice icons are missing.
> 
> Can you please update this stdlib?

Sorry for the delay, we've just updated the standard library.
Tell us if it's not working for you!
