### ISSUE TITLE
(timing diagram) allow to change arrow color 

### ISSUE THREAD

**Issue by Shadoxtwo** [plantuml/plantuml#130]
I would like to change the color for specific arrows in my timing diagrams (just like in sequence diagrams).
Could this be implemented please?

**Comment by bastiedotorg** [comment]
i prepared a patch to enable this functionality:
* default behavior -> takes  ColorParam.arrow
* each arrow can be styled with PartA -[#blue]> PartB
same syntax as with class diagrams.

PR https://github.com/plantuml/plantuml/pull/131

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Shadoxtwo for the request.
- Thanks @bastiedotorg for the PR: #131.
- Thanks PlantUML team for your work.

Regards.
