### ISSUE TITLE
nwdiag bug: group causes element to incorrectly connect to network

### ISSUE THREAD

**Issue by dgutson** [plantuml/plantuml#1301]
Given:
```
@startuml

nwdiag {
network net1 {
thing_1
}
network net2 {
thing_2
}
group uniqueNode {
  thing_1
}

}

@enduml
```

The following is rendered:
![image](https://user-images.githubusercontent.com/9671770/221691308-677df225-b6d6-4840-a520-d8772d46baa6.png)

Clearly, `thing1` should not be connected to `net2`.
This is correctly rendered using nwdiag:
![image](https://user-images.githubusercontent.com/9671770/221691635-4265feb1-b3bc-41db-9cb1-3c7b445413a6.png)

**Comment by dgutson** [comment]
Datum: if I write the group before the network definitions, the connections are correct, but colors and `<style>` group are ignored.

**Comment by dgutson** [comment]
@arnaudroques sorry to tag you, any chance to take a look? this is a serious bug for us. At least an initial evaluation.

**Comment by arnaudroques** [comment]
> @arnaudroques sorry to tag you, any chance to take a look? this is a serious bug for us. At least an initial evaluation.

We're going to have a look at it. It should be easy to fix.
I'll post a message here where this will be ready.

**Comment by dgutson** [comment]
> > @arnaudroques sorry to tag you, any chance to take a look? this is a serious bug for us. At least an initial evaluation.
> 
> We're going to have a look at it. It should be easy to fix. I'll post a message here where this will be ready.

Thank you so much!! We created a network diagrams exporter for structurizr that we will open source soon, and this is key for the demo this Friday to get the publication clearance.

**Comment by arnaudroques** [comment]
> Thank you so much!! We created a network diagrams exporter for structurizr that we will open source soon, and this is key for the demo this Friday to get the publication clearance.

Someday, you should tell us more about this.

We've done few tests but it [should work better now](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSehJybCJ5UevifBBIdFByfM0DA6G6v9HcPUUhmXLosoX15SmWWeaLwKNrgWK9gNMLYQwfUVaWgKL510w0CYXzIy5A0b0000). 

You can also use [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Tell us if it's not working for you!

**Comment by dgutson** [comment]
Thanks @arnaudroques , but the snapshots is not working well :( 
It is completely ignoring:
1. the style:
```
<style>
nwdiagDiagram {
  group {
    BackGroundColor cadetblue
    #LineColor black
    #LineThickness 2.0
    #FontSize 11
    FontStyle bold
    #Margin 5
    #Padding 5
  }
}
</style>
```

2. the attributes
```
group mainNode {
description = "mainNode "
  DB_Main_1 [color = "Red", description="<b>DB_Main</b>\n\nBackend DB\nCU DB\nXXX DB\nYYY DB"]
```

everything within `[ ]` gets ignored

My group definitions are after the network definitions, as shown in my original example.

**Comment by dgutson** [comment]
[Example](https://www.plantuml.com/plantuml/umla/JL1TIyCm57tFhxZKLt6su5jNHbVqnOdu0IrMHjfSkj3iPgOfGsN_tRkqgD1oSkuv8UVSrU2by-FU294E_jDW9kYejEmA_ftSmxS0w9mT3-44aCkslsDEQcsDTT1AXRun8mRrubuJJa9ZsFatVDdfjYSS1aYkhgVnhIN_hByGuZWC0ZzdWCOQDNasqdMQu6PYZr8fJLsW9t4IwMBEF8VcZ8J-Q5qFZ35JlsF_DcRlFo7v5H8MfdOZwOyH7wp2K7I-1_3MXZPBY9vGHPUWS6YTFdXjQHcbJLRasutKb2wQhAQQpkj1Kb3aDQrV0vHb6R2gAiRedP_aRyKkNliF)

**Comment by arnaudroques** [comment]
> [Example](https://www.plantuml.com/plantuml/umla/JL1TIyCm57tFhxZKLt6su5jNHbVqnOdu0IrMHjfSkj3iPgOfGsN_tRkqgD1oSkuv8UVSrU2by-FU294E_jDW9kYejEmA_ftSmxS0w9mT3-44aCkslsDEQcsDTT1AXRun8mRrubuJJa9ZsFatVDdfjYSS1aYkhgVnhIN_hByGuZWC0ZzdWCOQDNasqdMQu6PYZr8fJLsW9t4IwMBEF8VcZ8J-Q5qFZ35JlsF_DcRlFo7v5H8MfdOZwOyH7wp2K7I-1_3MXZPBY9vGHPUWS6YTFdXjQHcbJLRasutKb2wQhAQQpkj1Kb3aDQrV0vHb6R2gAiRedP_aRyKkNliF)

Thanks for the example!
It should [work now](https://www.plantuml.com/plantuml/umla/JL1TQyCm37pFhn3PwrYNmDxIKDAmlQnZx0CIbb6SMAGchjmv3cKR_UzJxS82DkVJdV19gz49wwQzZhBHVMlC8pfA9VgIhnLx-8q0UckcWty15A8R7fYJN1jjB7H2eclrX5wzUbI4GMWrE_-BRplL3OJZ2EdDRIZV6tAlwWSXINp1ytC6Q8sMmRCHjbS4Tu4z2oaLzPwUebEKBIwPBw4v8w4x6Zi0O-8ZknrtR1DspwHq9gKiXGadKbyJFXc9yqw0ZyvFj8Ju1MLy3HB7pgg3KuQMSTRcPR7T24NPeiqRQkYy8YG9PT7G-jr3LLKUwxfcZ3_vIpuhTl7c_m00).

Still one day to test :-)

**Comment by dgutson** [comment]
@arnaudroques thanks, network diagrams are now working as expected!

However, the snapshot is badly broken for other diagrams, are you running regression tests yet or tests already finished? I hope I won't need to file all those issues :(

**Comment by arnaudroques** [comment]
> However, the snapshot is badly broken for other diagrams

Could you give an simple example? Thanks

**Comment by arnaudroques** [comment]
> However, the snapshot is badly broken for other diagrams

We do have some non-regression tests for network diagrams, but on very simple diagrams. Yours seem to be more complex.
When you talk about "**other**" diagrams, do you mean non-network diagrams? Or are you talking about some other diagram networks?

Maybe you are impacted by the namespace/package simplification (see https://plantuml.com/en/news ) ?
In that case `set separator none` may help you.

**Comment by dgutson** [comment]
why such a breaking change :( 
Any way to change the default to be blackward compatible, or add a configuration file? Please note that these diagrams (not network ones) are generated by structurizr, so this should be modified by @simonbrowndotje by changing the exporter behavior depending on what plantUML version it would generate for, add a property or env var, really a hassle.
I think that with this change, suddenly all plantUML users, not only structurizr users, will suddenly get their diagrams broken.

**Comment by dgutson** [comment]
Without the `set separator none`:
![image](https://user-images.githubusercontent.com/9671770/222262561-3a15b7c7-5342-4efa-8865-b52ffafe04ff.png)

With `set separator none` (as generated in the previous version):
![image](https://user-images.githubusercontent.com/9671770/222262336-54701a75-6852-49b5-a600-badc6bae8852.png)

**Comment by arnaudroques** [comment]
> Please note that these diagrams (not network ones) are generated by structurizr, so this should be modified by @simonbrowndotje by changing the exporter behavior depending on what plantUML version it would generate for, add a property or env var

Note that previous PlantUML version should not be impacted by this `set separator none` so it can be set whatever is the version.


> I think that with this change, suddenly all plantUML users, not only structurizr users, will suddenly get their diagrams broken.

Theoretically, only those that put some dot (".") in their package names.
There is something strange in your case, but the image are too small and not readable: I don't get why relationships are impacted by this change. Probably something we should investigate.
@simonbrowndotje Any idea?

**Comment by dgutson** [comment]
Indeed the names have dots in C4 to specify the scope when there is hierarchy (softwaresystem/container/component).

Sorry about the unreadable image (this was a cheap obfuscation), this is everything I could do until I can come up with a curated example.

**Comment by simonbrowndotje** [comment]
> @simonbrowndotje Any idea?

Probably using an old version of the Structurizr export library ... I added support for `set separator none` 2 weeks ago:

- https://github.com/structurizr/export/commit/1ba181c2e5ad87aa12cb96a8c8d23a3cd44605e6
- https://github.com/structurizr/export/releases

**Comment by dgutson** [comment]
@arnaudroques @simonbrowndotje this was generated with latest structurizr-cli (docker) and latest plantUML snapshot, a dynamic view (sequence diagram mode), the error is:
![image](https://user-images.githubusercontent.com/9671770/223265041-0f65eae5-675b-4643-9dad-8fc952d9f1bf.png)

I understand I should show the source of both dsl and plantUML, but at least from the error, can you spot what the error is?

**Comment by simonbrowndotje** [comment]
Here's a simplified example:

```
@startuml
set separator none

actor "User" as User
participant "A.B" as A.B
User -> A.B : Uses

@enduml
```

[![image](https://user-images.githubusercontent.com/1009874/223333061-c53822a2-bcfa-4e3f-b825-2ae1bcb28679.png)](http://www.plantuml.com/plantuml/uml/7Oon3SCm30HxJl5GdmoG8b2oWmSWP1O2R4eWwVqjkle3xl3LWoskyo2NWCjaunW67If4t9BBvc85x4YWbKHlVR86ok_zVynQIelNDncVR9seYkxh_GO0)

**Comment by The-Lum** [comment]
Hello all,

It seems due to the type of diagram, compare:

# Actor diagram
```puml
@startuml
set separator none

actor "User" as User
'participant "A.B" as A.B
User -> A.B : Uses
@enduml
```

# Sequence diagram
```puml
@startuml
'set separator none

actor "User" as User
participant "A.B" as A.B
User -> A.B : Uses
@enduml
```
That seems `set separator`, on Sequence diagram context, which occurs the error.

_If that can help,_
Regards,
Th.

**Comment by The-Lum** [comment]
>Does it help?

@arnaudroques: Yes.

But, now that will be a new wanted feature:
- Could you allow `set separator none` on **all diagram**?
_And especially without effect on Sequence diagram._ :-)

In this case, we could include this line `set separator none` on theme, configuration file, etc... without presuppose which diagram will be used by...

_If I am clear..._
Regards.

**Comment by arnaudroques** [comment]
> If I am clear...

Very clear!
This has been implemented in last snapshot and on the online server.

**Comment by dgutson** [comment]
Just tested ~v1.2023.3beta7 and everything looks good. Please don't touch anything else :) release it.
