### ISSUE TITLE
Namespace association class connection point outside namespace

### ISSUE THREAD

**Issue by mrezabayat** [plantuml/plantuml#1302]
## Bug description

When using a namespace and having two classes with an association relationship, if there is an association class involved, the connection point of the association class is outside of the namespace.

## Steps to reproduce

Use the following code:
```
@startuml

ns1.classA "1" --> "1" ns1.classB : Used in foo method
(ns1.classB, ns1.classA) .. ns1.Exception : Exception

@enduml
```
Generate the diagram.

## Expected behavior

The connection point of the association class should be inside the namespace.

## Actual behavior

The connection point of the association class is outside of the namespace.

Additional information

Screenshots
![image](https://user-images.githubusercontent.com/32814496/221842175-4f598405-c914-4726-bc3c-5724ccc5eb5f.png)

**Comment by arnaudroques** [comment]
Many thanks for the report.
This should [be fixed now](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuSehDjHBpaaiBdPKK39KKj3LjGFJS64d1Ik5qEBK58NCF8Mq_7o5tDIIZFmKBWs40Xs4OaTD1JqzCDUr8Zcre2GpFm-e7SxcSaZDIm5Q2W00).
You can also [check last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Tell us if you find other issues!
