### ISSUE TITLE
Ability to hide empty fields for object diagrams

### ISSUE THREAD

**Issue by strongmindsram** [plantuml/plantuml#1304]
It is currently not possible to hide the empty "box" below a title for an object when creating object diagrams. The documentation for class diagrams (https://plantuml.com/class-diagram under "Hide attributes, methods...") specify different options but these only target classes and not objects.

![example](https://user-images.githubusercontent.com/112863576/222400994-4b2d3b72-3b3e-4d4d-92b9-3871a4c7f543.png)

**Comment by arnaudroques** [comment]
Thanks for the idea!
This is fixed in last snapshot and [on the online server](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIh9BCb9LSZ8J4bLo4tDJKejAkP2uUGdPQKcboWuAbHpAIYavUTprSA4dBWSKlDIW6O00000).

**Comment by jfudickar** [comment]
Cool!
