### ISSUE TITLE
PlantUML creates new SVG files although the PlantUML sources did not change

### ISSUE THREAD

**Issue by travkin79** [plantuml/plantuml#1308]
Hi,
I'm using the PlantUML library (vers. 1.2022.7) in an Eclipse IDE to automatically create SVG image files from numerous *.puml files in the Eclipse workspace (by using an incremental builder). Our teams realized that in some cases PlantUML creates new SVG files, although the PlantUML source files (*.puml) did not change at all. I hope, you can fix that.

This issue is related to #248 and #112.

I found out that there is an argument `-checkmetadata` that can be used to compare the PlantUML source code in the existing SVG (or PNG) file with the PlantUML source code from the puml file. That sounds like a solution, but it does not always work as expected. (By the way, the [documentation](https://plantuml.com/de/command-line#ce21470ab49d1d19) currently states that this option is only available for PNG files, but according to ticket #248 that feature also works with SVG files. The documentation should be updated.)

I found in the plantuml source code (in vers. 1.2022.7 as well as in vers. 1.2023.2) that the comparison involves comparing some system dependent properties like the system's country and language settings and the JDK / JRE used on the system. In our case that still leads to new SVG files although the source code (and the PlantUML version used) did not change, since our teams are spread all over the world. Running plantuml SVG generation on the same PlantUML source files on computers in the US, in China, or Germany produces different SVG files. Here is an example of the meta-data that is compared in addition to the PlantUML source code:

```
PlantUML version 1.2022.7(Mon Aug 22 19:01:30 CEST 2022)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: de
Country: DE
```
You'll find the comparison implemented in `net.sourceforge.plantuml.AbstractPSystem#getMetadata()` and in `net.sourceforge.plantuml.FileFormat#equalsMetadata(String, SFile)`.

I suggest to exclude most of the above meta-data from comparison. IMHO we only need to compare the PlantUML source code and the PlantUML library version. Do you agree? Could you please adapt the comparison in the PlantUML library?

In addition, when comparing the PlantUML version, we're facing another problem. The timestamp text given there differs depending on the local system's time zone, e.g. CEST. I suggest to unify that timestamp by always using UTC instead of the local time zone. Another option would be to exclude the timestamp from comparison (is the PlantUML library version not unique?).

Before reading about the `-checkmetadata` option, I hoped that PlantUML always creates the same output (SVG/PNG) files for the same input (puml) files. But for some reason, PlantUML sometimes creates different element IDs like in the following example. Maybe that should be changed, too. That would help to produce the same results when creating SVG files from PlantUML source code (not from PlantUML source code files with original PlantUML code, but from plain PlantUML code in memory without any meta-data). That's another use case in our company.

![file-diff-ids](https://user-images.githubusercontent.com/10887297/223131648-2fa4ceaa-cca2-4c2c-a636-1acf42eae26a.png)

Thanks a lot.
Dietrich

**Comment by arnaudroques** [comment]
Note that last versions of PlantUML change the metadata exported in SVG (see https://github.com/plantuml/plantuml/issues/1319)
So this *may* have fix your issue.
Just tell us if it works better or not.

**Comment by travkin79** [comment]
Thanks for the hint. I'll check and test the new version and will give you feedback.

**Comment by travkin79** [comment]
Hi @arnaudroques,

Thanks again for the hint and the implemented changes.

I've implemented a few tests and played around with the PlantUML vers. 1.2023.4. The issues with comparing the meta data or PlantUML source code seem to be solved.

In case it helps, you could pull my tests to the plantuml project. You'll find them here:
fork: https://github.com/travkin79/plantuml/tree/patch/1308
file: [SameImagesForSameSourcesTest.java](https://github.com/travkin79/plantuml/blob/patch/1308/test/net/sourceforge/plantuml/SameImagesForSameSourcesTest.java)

Two of the tests are disabled, since they are not successful and I'm not sure if the tested behavior is desired. For example, we could think about ignoring whitespace changes in PlantUML source code if -checkmetadata is active. But I'm not sure if that can be done for all diagrams in all cases.

Considering the generated element IDs in SVG source code, I could not find out when the IDs change and thus, couldn't reproduce the behavior. It might be, again, be something system-dependent.

I think, this ticket can be closed now. I'll come back to you in case, we encounter other non-working cases. Thank you very much.

**Comment by evantill** [comment]
Hi,
I will close this issue as "duplicate".

Thank you very much we will continue on #1319

**Comment by evantill** [comment]
https://github.com/plantuml/plantuml/issues/1319
