### ISSUE TITLE
1.2023.2 - Drastic Behavior Change of "as" Parsing with "." (period)

### ISSUE THREAD

**Issue by chrismalek** [plantuml/plantuml#1309]
There seems to be some drastic change that is reaching havoc on all my diagrams with 1.2023.2.

It is the way the "as" is parsed. I commonly use periods to basically namespace complex diagrams and those were interpreted as a single string.

I am hoping there is some way to revert this with a flag. I don't see anything in a change log so I suspect this may be a bug.

I used to be able to do this:

```plantuml
rectangle "hello" as a.hello

rectangle "world" as a.world

a.hello -> a.world

```

This would produce two rectangles connected with a line.

Now that `a.hello` and `a.world` are interpreted as a "package".

<img width="455" alt="image" src="https://user-images.githubusercontent.com/9403/223504034-696e3c4f-c821-4fce-b102-320cd291b347.png">

Now I have to replace periods with an underscore.  This is find for new diagrams but I have hundreds of previous diagrams.

```plantuml
rectangle "hello" as a_hello

rectangle "world" as a_world

a_hello -> a_world

```

<img width="335" alt="image" src="https://user-images.githubusercontent.com/9403/223504786-f11f7df0-7018-4f5b-a428-3e288bcaf422.png">

**Comment by arnaudroques** [comment]
You should use `set separator none`
Here is [the expected result](https://www.plantuml.com/plantuml/umla/LOr12e1024Ntda9cNqU8kOeqKWlJKAFh5yCGj7lyz-7LIFAy3e7WnE2JdD8SrPG1dDSatOInx2nY1IcGviu_UvjB6xOpmBZXj7nRPMrlwW40).

See https://plantuml.com/en/news

Hope this helps!

**Comment by chrismalek** [comment]
Yes it does help.  `set separator none`



## Additional Feedback.

That hurts a bit (really a lot) for me. I have a large amount of documentation floating around at client sites (wikis, documentation) that may generate diagrams by linking to the Plantuml server if there is no built in PlantUML Support.
 
`https://www.plantuml.com/plantuml/png/SoWkIImgAStDuIfAJIv9p4lFILLGoaZDoSbNKaWiLaZK0xEva6NByujoKg2oO3ON5rIPWguTNCmXDIy5Q2m0`

I do this in Github Markdown all the time so that Github Markdown rendering will render the diagram and just keep the source code of the diagram in a separate file.

Now all those diagrams are going to render all messed up and I can't go back and change all those references. Ugh!

I don't know enough about the workings of the internal libraries here to comment on a technical alternative. 

My vote would be to have this new feature disabled by default.

I absolutely love PlantUML and use it daily.

I have been looking at https://d2lang.com/tour/intro/ lately as an alternative and they also parse periods similar to what was just introduced here. I actually hate it but I think it is all personal preference. I am just one very small vote.


:-)

**Comment by arnaudroques** [comment]
There have been several complains about this.

One thing we could do is to slightly (again! :-) ) change this behavior.

  * For class diagram and object diagram, the "." would still be interpreted as a namespace separator.
  * For state, usecase, component and deployment diagrams, we could put `set separator none` as default.

Initially, we thought that having a different behavior for class/object and state/usecase/component/deployment would be confusing. But now we are not so sure...

Would that help?
Could you tell us if your diagrams are mainly class/object diagrams?

**Comment by chrismalek** [comment]
I personally mainly use Component diagrams similar to the C4 style stuff but not always the C4 templates/plugin. 

I do enterprise consulting and mostly integration work between enterprise systems for large institutions and corporations.  I end up drawing lots of "boxes" to show how systems relate and how data flows in complex mesh of corporate or university system. Or in large ERP systems, how modules inter-relate. This is used to explain concepts as people often need a high level picture to go along with technical verbiage. This is really true for non-technical people or executives. When presenting ideas for sales and tech documents for customers or internal software documentation, these can be very effective to solidify concepts to the reader/audience. 

Here is a good example of something that I am doing to show a schematic.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/9403/223577858-ccfff733-48ec-40fd-b935-e9709a6b20f2.png">



PlantUML is great for this.  I use it daily..love it.  **I appreciate everyone who keeps this thing going and the recent improvements** (I think it sort of stagnated for a few years). I am a long time user. 

https://d2lang.com really looks like it is coming up to be a valid contender to PlantUML for my use cases but I have so many legacy diagrams it is hard to shift. I know the PlantUML syntax for my use cases pretty well. 

For me I never use class diagrams. 

For me this is a a fairly major change (I might be an edge case). My gut feel is that maybe this is something that should be part of a major release and not a "dot" release. 

Again I am just one small vote but every project I am pulling up today (I juggle many different clients and projects) and all my diagrams are messed up. I am glad I got the `set separator none` setting because I got pulled into a meeting today and I had the perfect diagram to explain something and I opened it up and it was all messed up. However, the `set separator none` did the trick.

I always used the "." as a seperator because it visually worked for me as opposed to Camel case.  Underscores are just as effective. Unfortunately, I chose "." in all my diagrams and I got bit by this change.  


I need to dig into what the "namespace" really means. The Plantuml stuff has a ton of deep dark corners I don't use. Everytime I look at the docs I see stuff that I had no idea was there and I use PlantUML a lot. I think I used it for years then I discovered macros and functions and I was like "mind blown" but I often just go back to base functionality to keep it simple and have diagram fairly portable. 


Maybe more information than you wanted but I think you guys/gals might find if valuable to know people are using this stuff daily and really value it.

**Comment by alixander** [comment]
@chrismalek just fyi, as this came up for me as I get notified of d2lang.com mentions, you can just wrap in quotes to escape periods in D2: https://play.d2lang.com/?script=UkrUS9JLVlLQtVNQqtCr1KtS4gIEAAD__w%3D%3D&

PlantUML supports a lot more use cases than D2, but D2 is pre-1.0. We're still making rather radical changes in these next few months before we hit 1.0. You can see our recent releases for examples: https://github.com/terrastruct/d2/releases. It also means your small vote is a big one for us, and I'd love to chat more with you to support what you're diagramming if you're up for it (email in profile)

**Comment by arnaudroques** [comment]
> Maybe more information than you wanted but I think you guys/gals might find if valuable to know people are using this stuff daily and really value it.

Yes, thanks, it's really useful to better understand how people use PlantUML.
We've built PlantUML *with* our users, not *against* them.

So in last beta, we have put `set separator none` as default for deployment and usecase diagram.
[Your first example](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuGh9BCb9LKZBh4XDKUGgIaqkISnB1meePQJcvEGhAIGMAoJgWTd8akNvHJafK4amcmkgI47N3Yxaa9gN0hG10000) is then working again.

Hope this helps!

**Comment by chrismalek** [comment]
Great thanks.  I am will close this.
