### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by MundakaZgz** [plantuml/plantuml#1310]
Hi!

I downloaded the latest version of the plantuml's jar with `curl https://github.com/plantuml/plantuml/releases/download/v1.2023.2/plantuml.jar -o plantuml.jar` but when I ran it with `java -jar plantuml.jar someDiagram.puml` I got the following error:

> Error: Invalid or corrupt jarfile plantuml.jar

The diagram is working fine with VSCode's plugin and in the online editor but not with the downloaded version. 

Am I doing something wrong?

Thanks!

**Comment by evantill** [comment]
could you try this link ?
https://github.com/plantuml/plantuml/releases/download/v1.2023.2/plantuml-pdf-1.2023.2.jar

I have just tested it and it work for me :

```shell
wget https://github.com/plantuml/plantuml/releases/download/v1.2023.2/plantuml-1.2023.2.jar
java -jar plantuml-1.2023.2.jar essai.puml
```

content of `essai.puml`
```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
```

**Comment by MundakaZgz** [comment]
It was not a problem with the jar but with `curl` command I was using. `curl -OL https://github.com/plantuml/plantuml/releases/download/v1.2023.2/plantuml-1.2023.2.jar` works like a charm.

Thanks for the help!!
