### ISSUE TITLE
PlantUML Version 1.2023.4 report wrong Version number PlantUML Version 1.2023.3

### ISSUE THREAD

**Issue by phoro4** [plantuml/plantuml#1317]
```
plantuml-1.2023.4.jar -v -picoweb
(0.000 - 8 Mo) 6 Mo - SecurityProfile LEGACY
(0.008 - 8 Mo) 5 Mo - PlantUML Version 1.2023.3
(0.008 - 8 Mo) 5 Mo - GraphicsEnvironment.isHeadless() false
webPort=8080
```

**Comment by arnaudroques** [comment]
Thanks for the report!
We had an (minor) issue when publishing to OSSRH (see https://github.com/plantuml/plantuml/pull/1314).
`1.2023.3` and `1.2023.4` are really the same code, so don't worry about that.

It will be definitively fixed with `1.2023.5` :-)
