### ISSUE TITLE
SVG no longer embeds PlantUML code

### ISSUE THREAD

**Issue by rohitsud** [plantuml/plantuml#1319]
I am using an extension in VSCode to generate SVG code from PlantUML code embedded in my Markdown files

> Name: PlantUML
> Id: jebbs.plantuml
> Description: Rich PlantUML support for Visual Studio Code.
> Version: 2.17.5
> Publisher: jebbs
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

When I use the latest release `2023.4` the SVG files are rendered very differently without the PlantUML code embedded in them.

```
@startuml example
A->B
@enduml

```

generates

`<?xml version="1.0" encoding="us-ascii" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="108px" preserveAspectRatio="none" style="width:67px;height:108px;background:#FFFFFF;" version="1.1" viewBox="0 0 67 108" width="67px" zoomAndPan="magnify"><defs/><g><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="16" x2="16" y1="37.6094" y2="71.6094"/><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="49" x2="49" y1="37.6094" y2="71.6094"/><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="5" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="12" y="26.5332">A</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="5" y="70.6094"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="12" y="92.1426">A</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="38" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="45" y="26.5332">B</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="38" y="70.6094"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="45" y="92.1426">B</text><polygon fill="#181818" points="37.5,49.6094,47.5,53.6094,37.5,57.6094,41.5,53.6094" style="stroke:#181818;stroke-width:1.0;"/><line style="stroke:#181818;stroke-width:1.0;" x1="16.5" x2="43.5" y1="53.6094" y2="53.6094"/><!--SRC=[SzIrSm80]--></g></svg>`

whereas version `2022.13` used to generate (last version that did it this way)

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentStyleType="text/css" height="108px" preserveAspectRatio="none" style="width:67px;height:108px;background:#FFFFFF;" version="1.1" viewBox="0 0 67 108" width="67px" zoomAndPan="magnify"><defs/><g><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="16" x2="16" y1="37.6094" y2="71.6094"/><line style="stroke:#181818;stroke-width:0.5;stroke-dasharray:5.0,5.0;" x1="49" x2="49" y1="37.6094" y2="71.6094"/><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="5" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="12" y="26.5332">A</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="5" y="70.6094"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="12" y="92.1426">A</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="38" y="5"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="45" y="26.5332">B</text><rect fill="#E2E2F0" height="31.6094" rx="2.5" ry="2.5" style="stroke:#181818;stroke-width:0.5;" width="23" x="38" y="70.6094"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacing" textLength="9" x="45" y="92.1426">B</text><polygon fill="#181818" points="37.5,49.6094,47.5,53.6094,37.5,57.6094,41.5,53.6094" style="stroke:#181818;stroke-width:1.0;"/><line style="stroke:#181818;stroke-width:1.0;" x1="16.5" x2="43.5" y1="53.6094" y2="53.6094"/><!--MD5=[e11d1a8926a5283c8a9b24e6fb6d7d56]
@startuml example
A->B
@enduml

PlantUML version 1.2022.13(Sat Nov 19 05:22:17 PST 2022)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US
--></g></svg>
```

Is there a way to revert to embedding the code in the SVG like before? Or is the old format [gone for good](https://github.com/plantuml/plantuml/commit/117102bb65b007f6086838dfc058b278ca69cb38)?

**Comment by rohitsud** [comment]
This makes sense to me. The old approach did make it straightforward to see
how my diagram evolved by simply looking up the plaintext diff in git which
isn't possible anymore. But I can appreciate the problems that simple text
embedding could've posed with, say, escaping.

Just curious, did you think about escaping and embedding the source? I am
wondering what were the reasons behind the change...

**Comment by travkin79** [comment]
So, in the new PlantUML version the original source code is not embedded as plain text, but in an encoded form. Does the argument `-checkmetadata` then still work as before?

**Comment by arnaudroques** [comment]
> So, in the new PlantUML version the original source code is not embedded as plain text, but in an encoded form. Does the argument `-checkmetadata` then still work as before?

Yes, actually it should.
But tell us if it does not work... :-)

Thanks!

**Comment by travkin79** [comment]
Hi @arnaudroques,
I tried to read the PlantUML source code from an SVG file created from a PlantUML source file with plantuml.jar vers. 1.2023.4. That didn't work.

**Steps to reproduce:**

1. Create a source file test.puml with contents like
```
@startuml
  Bob --> Alice
@enduml
```
2. Translate the source file to SVG
   `java -jar plantuml-1.2023.4.jar -svg test.puml`
3. Ensure that the SVG file contains the encoded PlantUML source code, here it is the following comment at the end of the SVG file
```
<!--SRC=[Kr1moazIqDMrKt3CoKnE1G00]-->
```
4. Try to decode the PlantUML source code again with
`java -jar plantuml-1.2023.4.jar -metadata test.svg > test_reading.puml`

The `test_reading.puml` file in my case has the following content, but should contain the original PlantUML source code.
```
------------------------
test.svg

null
------------------------
```
