### ISSUE TITLE
sequenceMessageAlign direction does not center for arrow in two directions

### ISSUE THREAD

**Issue by jessetan** [plantuml/plantuml#132]
When `skinparam sequenceMessageAlign direction` is set, the text alignment of messages depends on the direction of the arrow. If the arrow points right, the text is left aligned. If the arrow points left, the text is right aligned.
However if the message has arrows pointing both ways (`Bob<->Alice`), the text is not centered, but is also left aligned.

```puml
@startuml
skinparam sequenceMessageAlign direction
Bob->Alice: This is a long message to increase the distance between Alice and Bob
Bob->Alice: should be left aligned
Alice->Bob: should be right aligned
Alice<->Bob: should be centered
@enduml
```
![Example image](http://www.plantuml.com/plantuml/png/POz1hi8m34JtFOKlq0iWL1NsxBY0cmo9zLC7ubHS7wjiW2zvONdUpCYpTMvzMyjWVw9tRhoIuR510oumuuHJaQGKfI5qgJgSwp9EVWmuq3MBaGzJgPfeVJkeLn8D3Mo-PxZPQpoH5lGdeBJRYJMIftqbMgvRYGvImQqJUxaY3hiwJav-8arI_c6E_w00xMYkpz3edxu0)

PlantUML version 1.2018.08

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by jessetan** [comment]
Verified fixed in the beta, thanks for the quick response!
