### ISSUE TITLE
smetana and ELK: both layout engine don't support comments on lines

### ISSUE THREAD

**Issue by boessu** [plantuml/plantuml#1322]
It seems as a "note on link" only works with the GraphViz engine:

Trivial example
```
@startuml

pragma layout smetana
'!pragma layout elk

a --> b
note on link
This is not visible,
neither in smetana
nor ELK.
end note

@enduml
```
[link](http://www.plantuml.com/plantuml/uml/NOun3i9030JxVSLIqH2UWD9GGSa7764HAuuFtJb8_9wZeK3QOZN5QCQMKdDR7RjdbSSgT7cNBTbMJGd1_e-hBu1m64wS42ML9UWM2swpDVPro9SrcrmF2BMSjTBYPunIURvUZj2uysl0s5zF-000)

As it doesn't work on two completely separate engines, I have a small hope it is a small problem. ;-)

**Comment by arnaudroques** [comment]
> I have a small hope it is a small problem. ;-)

Unfortunately, it's not... :-(
And it's really two separate issues.

**Comment by evantill** [comment]
Hi, @boessu
Could you open 2 seperates issues to help us ?
One for smetana (the _other_ engine) and one for GraphViz engine ?

**Comment by The-Lum** [comment]
Hi @evantill, @boessu, and all,

>Could you open 2 separates issues to help us ?

That is done:
- #1332
- #1333

Regards.

**Comment by evantill** [comment]
thank you @The-Lum

**Comment by evantill** [comment]
I will close this issue.
@boessu just leave a comment on #1332 and #1333 to  follow
