### ISSUE TITLE
Two license headers in a file in the EPL licensed plantuml source code

### ISSUE THREAD

**Issue by rahulmohang** [plantuml/plantuml#1330]
Hi,

One of our projects is using the download available under EPL v1.0. In the file, 'https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/utils/MTRandom.java', we have found that the license header for the EPL has been added on top of the header for LGPL. 

Can you please confirm whether the file, 'MTRandom' provided in the sources of plantuml, available under the EPL v1.0, is available only under the EPL v1.0 or not?

**Comment by arnaudroques** [comment]
Since MTRandom is very short, we are going to change the license for this file, and also publish it under EPL v1.0, keeping all copyright mention.

**Comment by rahulmohang** [comment]
Hi @arnaudroques, 

Thank you.

**Comment by rahulmohang** [comment]
Hi @arnaudroques, 

Since this is work in progress, I understand that the file, MTRandoim.java in the latest EPL version available in Sourcforge, i.e. https://sourceforge.net/projects/plantuml/files/1.2023.6/plantuml-epl-1.2023.6.tar.gz/download, have both the license texts. 

Is it possible to give an estimate of when the file will be available under the EPL v1.0?

**Comment by arnaudroques** [comment]
> Is it possible to give an estimate of when the file will be available under the EPL v1.0?

Yes, this will be done in next release 1.2023.7, before the end of May.
I am in contact with David Beaumont, the original author of this file MTRandom.java and he is ok to publish it under different license.

**Comment by rahulmohang** [comment]
Hi @arnaudroques, 

The EPL v1.0 and Apache v2.0 licenses are put in the file, 'https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/klimt/drawing/g2d/ExtendedGeneralPath.java'. When using plantuml-epl, I should be using the EPL v1.0, right? 

It would have been good if only one license was mentioned.

**Comment by arnaudroques** [comment]
This is fixed with v1.2024.2
Thanks for your attention!

**Comment by rahulmohang** [comment]
Thank you @arnaudroques. So, in case of the plantuml-epl, the file is licensed under EPL v1.0, right?
