### ISSUE TITLE
[V1.2023.5beta2] The command `help themes` to list all the themes of PlantUML seems broken 

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1331]
**Describe the bug**
The command `help themes` to list all the themes of PlantUML seems broken, observed on **V1.2023.5beta2**

- What will be the correct command?

**To Reproduce**
```puml
@startuml
help themes
@enduml
```

**Expected behavior**
List all the themes included on `plantuml.jar`

**Screenshots**
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuSf8pIbGACb8pKqjvd98pKi1YW40)](https://www.planttext.com/?text=SoWkIImgAStDuSf8pIbGACb8pKqjvd98pKi1YW40)

**Ref. or associated issue**
- #654
- https://github.com/plantuml/plantuml/discussions/652#discussioncomment-1280009

**Comment by The-Lum** [comment]
It seems we observe the same issue with `ditaa`:
```puml
@startuml
ditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuKh9B4bCvDBMXG9j1GK5RIGsWiDLem05sc0vi4OGsqu19bC3KXEIMb6Y01P2CQSc9JCnlIWn5wZ69J-vD3SrhmIafaOnDp4zCraHR0IAEK1GdL9RWooCgWRi309k1l6i5721E2va4ttoIueLyjCKolEBic5s89k62RIv75BpKe2X2000)](https://www.planttext.com/?text=SoWkIImgAStDuKh9B4bCvDBMXG9j1GK5RIGsWiDLem05sc0vi4OGsqu19bC3KXEIMb6Y01P2CQSc9JCnlIWn5wZ69J-vD3SrhmIafaOnDp4zCraHR0IAEK1GdL9RWooCgWRi309k1l6i5721E2va4ttoIueLyjCKolEBic5s89k62RIv75BpKe2X2000)

**Comment by arnaudroques** [comment]
About ditaa, for some historical reason, you now [have to use this](http://www.plantuml.com/plantuml/uml/SoWkIImgISaiIKpaqjQ50cq51GLjE1kPmrMZ00NQO3cmHX3RJW4cKmDI4v9QKG9aefjJavAPc5wKc0jKuvAVN9gRcbTI0n9Mp4rCpqnM1B5Hp061wfJQ6YHXD3LWPn1mCuXdfO0Bn74Xc-YJNrAia9-cK9vVb0sp0s8Q1e2Rxv2Qbm8E2000).

Tell us if it's a big issue for you.

**Comment by The-Lum** [comment]
Hi @arnaudroques,

For `ditaa`:
>Tell us if it's a big issue for you.

No: That is not an issue for me.
But, we must:
1. update the doc. [on [alphadoc/.../ditaa](http://alphadoc.plantuml.com/doc/markdown/en/ditaa)]  _(already just done, awaiting your approval)_
1. verify sub-digram management...
_But that is another wanted feature...:_
```puml
node n [
{{ditaa
+---------+  /--------\   +-------+
| cBLU    +--+cAAA    +---+Version|
|         |  |  Data  |   |   V3  |
|    +----+  |  Base  |   |cRED{d}|
|    |cPNK|  |     {s}|   +-------+
|    |    |  \---+----/
+----+----+    
}}
{{ebnf
a  = "a";
}}
]
```
>[![](https://www.planttext.com/api/plantuml/png/NK-x3i8m3Dpp5LPNg-h0Y1XIbGc4419TA8D9WzGbbPfkIVuTvxLmokDoFbriiyuQ3Bo4S_Eo4mbiAn2Wgtm2W5f1uK7rroTa3PMKil0MHxtPPJMUFHK-hO5sIYJjyS1tzc3vYnyzMLqywd4Ut1oAnwlxxP9p6Cu6_zTFYOt75AMeTtcMcWyWGk0nzSTy1RToWeQQOzJUFm00)](https://www.planttext.com/?text=NK-x3i8m3Dpp5LPNg-h0Y1XIbGc4419TA8D9WzGbbPfkIVuTvxLmokDoFbriiyuQ3Bo4S_Eo4mbiAn2Wgtm2W5f1uK7rroTa3PMKil0MHxtPPJMUFHK-hO5sIYJjyS1tzc3vYnyzMLqywd4Ut1oAnwlxxP9p6Cu6_zTFYOt75AMeTtcMcWyWGk0nzSTy1RToWeQQOzJUFm00)

Regards.

**Comment by arnaudroques** [comment]
As said in https://github.com/plantuml/plantuml/issues/1232, we are going to put back `help themes` et `help font`, since they are useful.

**Comment by arnaudroques** [comment]
This should be fixed in last snapshot.
Tell us if it's not working for you!

**Comment by The-Lum** [comment]
Thanks a lot.

If you want to suppress `Help`...
Perhaps change the name...
Like:
 - `Listfonts`
Why not:
- `Listthemes`

To debate...
Regards.
