### ISSUE TITLE
[Smetana] Allow notes (or comments) on lines or links

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1332]
**Describe the bug**
- With **Smetana**: Allow notes/comments on lines/links.

Observed on:
- V1.2023.5beta2

**To Reproduce**
```puml
@startuml

!pragma layout smetana

a --> b
note on link
This is not visible,
neither in smetana
nor ELK.
end note

@enduml
```

**Expected behavior**
- Allow notes/comments on lines/links.

**Screenshots**
>[![](https://www.planttext.com/api/plantuml/svg/FOwn2W8n44Jx_Ogn41IyKoEsnpLMMbhQR73r5dCRIN87_hsn4GOU36zW-bmubMaCH8jtukV82Fo9Kq4UfR0n4QDfEdYoM0JH4DHUT1qqewQMc3Mh3x8X4os39AZzrnOJJfTpIsBtdon4ZrYHSBDzwtRkq1vzLHssMCwIiaPRhQclUZtr1G00)](https://www.planttext.com/?text=FOwn2W8n44Jx_Ogn41IyKoEsnpLMMbhQR73r5dCRIN87_hsn4GOU36zW-bmubMaCH8jtukV82Fo9Kq4UfR0n4QDfEdYoM0JH4DHUT1qqewQMc3Mh3x8X4os39AZzrnOJJfTpIsBtdon4ZrYHSBDzwtRkq1vzLHssMCwIiaPRhQclUZtr1G00)

**Ref. or related issue**
- #1322
- https://forum.plantuml.net/17600/note-and-position-not-rendering-correctly-on-cheerpj
- http://alphadoc.plantuml.com/doc/markdown/en/notes

**Comment by evantill** [comment]
@The-Lum  is this a feature request or a bug report ?

**Comment by arnaudroques** [comment]
This [is fixed now](https://www.plantuml.com/plantuml/uml/FOsn2i9044Jx-OgnDtw2fB7IqX_Ou68Mx_RaRYFuzwvDO8fXcCURHqYFhHRWyExohC8YtxO5HzKG5q0uJMSky1RAvYpcBznN6ypao8yDMueUuMgnQgVvJdlhlDok9wW__cS5vgmf_040)!
Thanks for the report.
