### ISSUE TITLE
[ELK] Allow notes (or comments) on lines or links

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1333]
**Describe the bug**
- With **ELK**: Allow notes (or comments) on lines, links.

Observed on:
- V1.2023.5beta2

**To Reproduce**
```puml
@startuml

!pragma layout elk

a --> b
note on link
This is not visible,
neither in smetana
nor ELK.
end note

@enduml
```

**Expected behavior**
- Allow notes/comments on lines/links.

**Screenshots**
>[![](https://www.planttext.com/api/plantuml/svg/5Own2i9044Jx_Ogn41HCr8XjI6EbfQND1bUpvB8dTvU0V-yA0m-6Dp1TBfpAF0MYrIVnUs84_iQvGC98nAYg5ZrPB89e26eZtGVDy7Y9HRFsGNPaecMG13NaIGeR-oZXShlM9FRyoqBqYew4Xnthvj2SwdFlQeCzrekahD4sM-fSzqC_)](https://www.planttext.com/?text=5Own2i9044Jx_Ogn41HCr8XjI6EbfQND1bUpvB8dTvU0V-yA0m-6Dp1TBfpAF0MYrIVnUs84_iQvGC98nAYg5ZrPB89e26eZtGVDy7Y9HRFsGNPaecMG13NaIGeR-oZXShlM9FRyoqBqYew4Xnthvj2SwdFlQeCzrekahD4sM-fSzqC_)

**Ref. or related issue**
- #1322
- https://forum.plantuml.net/17600/note-and-position-not-rendering-correctly-on-cheerpj
- http://alphadoc.plantuml.com/doc/markdown/en/notes

**Comment by arnaudroques** [comment]
This [is fixed now](https://www.plantuml.com/plantuml/uml/5Or12i9G34JtESMujnv1kd6bIo-GOh2X-VdoamhUtXHcCGppU7CaZzoRqUap-DqOnh--9yGs8iOqNR6GznHqXwblz5mrKAaHNmrTJCxaehdAW3gYIR9pGGEtn_r2ug_ZB3HNAzKV)!

Thanks.
