### ISSUE TITLE
JSON diagram SVG has misplaced arrows when containing newlines

### ISSUE THREAD

**Issue by M-casado** [plantuml/plantuml#1334]
**Describe the bug**
When a JSON field contains **new lines**, the origin of the arrows coming out of the node are misplaced. 

**To Reproduce**
1. Create a plantUML file to depict JSON data
2. In one of the fields of the JSON data, add some new line characters (``\\n``). Example of an schema:
````
@startjson

{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://raw.githubusercontent.com/EbiEga/ega-metadata-schema/main/schemas/EGA.assay.json",
    "type": "object",
    "title": "EGA assay metadata schema",
    "meta:version": "0.0.0",
    "$async": true,
    "description": "Metadata schema used by the European Genome-phenome Archive (EGA) to validate \\nits assay metadata object. This object is intended to contain metadata about the \\nraw qualitative or quantitative test performed to determine any kind of \\nbiological property of a biological sample. It can be of different types: (1) \\nsequencing assay [EFO:0003740] (e.g. sequence CRAM or FastQ files); and an (2) \\narray assay [EFO:0002696] (e.g. intensity CEL files). Further details can be \\nfound in the EGA-metadata-schema GitHub repository \\n(https://github.com/EbiEga/ega-metadata-schema/tree/main/schemas) and \\nEGA-archive website (https://ega-archive.org/)",
    "required": [
        "objectId",
        "assayTypeSpecifications",
        "assayFiles"
    ],
    "additionalProperties": false,
    "properties": {
        "objectId": "{ ... }",
        "schemaDescriptor": "{ ... }",
        "objectTitle": "{ ... }",
        "objectDescription": "{ ... }",
        "assayCenter": "{ ... }",
        "assayDate": "{ ... }",
        "assayTypeSpecifications": "{ ... }",
        "assayRelationships": "{ ... }",
        "assayFiles": "{ ... }",
        "assayAttributes": "{ ... }"
    },
    "allOf": [
        "{ ... }",
        "{ ... }",
        "{ ... }"
    ]
}
@endjson
````
3. Using the plantUML file, **generate an SVG file** (attached to the issue as ``EGA.assay_small.svg``).
````
java -jar plantuml-1.2023.1.jar -tsvg -o {output_dir_svg} {file_path}
````
4. **Open the SVG** in any browser (used Google Chrome, Edge and FireFox)
5. Observe how the **origin of some arrows is misplaced**. For example, following the JSON structure above, in the given SVG example there are the following errors:
    - The arrow that ends up at the first child node (the one containing ``objectId``, ``assayTypeSpecifications`` and ``assayFiles``) should start from ``required`` in the parent node, but instead starts from the bottom half of ``description``, which is a string node.
    - The second child node (containing from ``objectId`` to ``AssayAttributes``) should start from ``properties`` in the parent node, but instead starts from ``additionalProperties``, which is a boolean instead.
    - The origin of the final arrow is just slightly above what it should be, but is still interpretable.

Additionally, creating the pre-view of the JSON diagram through Visual Studio's widget generates the same erroneous result. 

**Expected behavior**
The arrows should start from the correct property in the JSON, regardless of how wide or tall any of the sibling fields (in the example ``description``) are. 

**Screenshots**
I highlighted the wrong starting points with 2 red arrows, the rest is the same as in the SVG:
![image](https://user-images.githubusercontent.com/77288380/225694532-a1c82569-11fe-4df8-946c-767c006434ef.png)

**Desktop (please complete the following information):**

- OS: Windows 10, using WSL2 (``5.4.72-microsoft-standard-WSL2``)
- Browser: Google Chrome, Mozilla Firefox and Microsoft Edge
- Version: both manually using ``plantuml-1.2023.1.jar`` or VS's widget ``v2.17.5`` of PlantUML

**Additional context**
I am fairly sure it is that the origin of the arrows is picked based on the length of the "node" box (i.e. the parent level), and by adding newlines, this proportion is distorted and not symmetrical for each field. 

If I remove the newlines from ``description``, the arrows start where they should.

**Comment by The-Lum** [comment]
Hi @M-casado, PlantUML Team and all,

On PNG that the same:
>[![](https://www.planttext.com/api/plantuml/png/VPF1ReCm38RlF4M4TfpGpZsr6jlKqwQjjtK7avYHAWMMk9EgYdUV4q9LD01aXFvy-BSTidO4bWwkgPFaaWY-qZidApn2kX9fVBkF2rfvaPzHe7EBNccA0qgwgffCa9zUDWASWxCu8e420Z5EwENLBrgdczf_y93nVNK3TwubosHF63M5JbhTKkHXlwyB3icXE92ZvFZcg8Oy5dzEsg8l_JCeGUrBtWwj12tKkkEUFbgKkjGIl97xXpnhWouDubSq0QMqXy6ysQP5Ivg9bIZ1kA7szdRXCb49DtGHMPQ9xjQndrWU6s_i3DPdsGsZdoNoyGGdkD3Y8zQ4Srw1o87cdERck42_e-cXIhUBO3_x1M13P7LneZ4Le6xOB6DUo_7lC95jGUgtFkcIDTRAdvq_)](https://www.planttext.com/?text=VPF1ReCm38RlF4M4TfpGpZsr6jlKqwQjjtK7avYHAWMMk9EgYdUV4q9LD01aXFvy-BSTidO4bWwkgPFaaWY-qZidApn2kX9fVBkF2rfvaPzHe7EBNccA0qgwgffCa9zUDWASWxCu8e420Z5EwENLBrgdczf_y93nVNK3TwubosHF63M5JbhTKkHXlwyB3icXE92ZvFZcg8Oy5dzEsg8l_JCeGUrBtWwj12tKkkEUFbgKkjGIl97xXpnhWouDubSq0QMqXy6ysQP5Ivg9bIZ1kA7szdRXCb49DtGHMPQ9xjQndrWU6s_i3DPdsGsZdoNoyGGdkD3Y8zQ4Srw1o87cdERck42_e-cXIhUBO3_x1M13P7LneZ4Le6xOB6DUo_7lC95jGUgtFkcIDTRAdvq_)

Here is a possible minimal example _(for debugging purpose)_:
```puml
@startjson
{
    "a": true,
    "desc": "a\\nb\\nc\\nd\\ne\\nf",
    "required": [
        "r1",
        "r2",
        "r3"
    ],
    "addP": false,
    "properties": {
        "P": "{ ... }"
    },
    "allOf": [
        "{ ... }",
        "{ ... }",
        "{ ... }"
    ]
}
@endjson
```
>[![](https://www.planttext.com/api/plantuml/svg/ZL0n3iCW3Dnv1V8S8RNTEkK7xTvqeB6HKY6I0faGVwyJG5MsMhhXpkUpvJv4xUCxp4ua8Rb0mrL6lr9NA58OMG4z3Ex561d888Q1QlBqMITFoCR7hXJrLFk5dG_i0ZjvrWIDUETfesrecnS_B-JZH84RwJUw-I19fPJC9IIt46jlvdX3ytL_IUKaaKLF3hUdV040)](https://www.planttext.com/?text=ZL0n3iCW3Dnv1V8S8RNTEkK7xTvqeB6HKY6I0faGVwyJG5MsMhhXpkUpvJv4xUCxp4ua8Rb0mrL6lr9NA58OMG4z3Ex561d888Q1QlBqMITFoCR7hXJrLFk5dG_i0ZjvrWIDUETfesrecnS_B-JZH84RwJUw-I19fPJC9IIt46jlvdX3ytL_IUKaaKLF3hUdV040)

Regards.

**Comment by arnaudroques** [comment]
Thanks for the report!
This is fixed in last snapshot and [on the online server](https://www.plantuml.com/plantuml/uml/ZL0n3i8m3DppYiXpLGdOcFe3s2b3g5sfA4gBaqvH_exR94BTY7J3dS-NapiV38UtdvsAIii30rSTUAKcKoG_Y0AcxzrBC0XGG88HYedfiqvCACR7hcJrLEQPdG_i0ZjvbWI3U9VjqLXVVrvuNeZ3H5u6yRUw-I3gjcrroY6fXbXx6uyTgg_vIygLL58TEToEyWK0).
