### ISSUE TITLE
ClassAttributeFont(Style|Size|…) overrides ClassFontStyle(Style|Size|…)

### ISSUE THREAD

**Issue by nstanger** [plantuml/plantuml#1335]
## Describe the bug

From version 1.2022.2, `ClassAttributeFont(Style|Size|…)` skinparams change font attributes for *all* text in a class, not just the attributes, also overriding the effect of any explicit `ClassFont(Style|Size|…).` This didn’t happen up to version 1.2022.1.

## To Reproduce

Minimum working example:

```plantuml
@startuml
skinparam {
    ClassFontStyle bold
    ClassFontSize 14
    ClassAttributeFontStyle plain
    ClassAttributeFontSize 10
}
class Class {
    -attr1
    --
    +method1()
}
@enduml
```

## Expected behavior

Class title should be size 14 and **bold**, attributes and methods should be size 10 and *not* bold.

## Screenshots

Output of MWE using 1.2022.1 (old default rose skin):
![test_1_2022_1](https://user-images.githubusercontent.com/4316101/225803297-39273da2-79ae-4632-921a-a61b483a27bf.svg)

Class title is larger and **bold**, as expected.

Output of MWE using 1.2023.4 (new default grey skin):
![test_1_2023_4](https://user-images.githubusercontent.com/4316101/225803350-6029f2ef-63e6-4020-aaa5-fe78170e8813.svg)

Class title is the same size as the attributes and *not* bold. I’ve also confirmed the same behaviour in 1.2022.2, 1.2022.14, and 1.2023.0.

## Desktop (please complete the following information)

- OS: macOS Monterey 12.6.3 (behaviour also confirmed under a couple of different Linuxes)
- Browser Vivaldi
- Version 5.7.2921.63 (stable)

## Smartphone (please complete the following information)

N/A

## Additional context

This behaviour first appeared in version 1.2022.2 and is presumably present in all subsequent versions (definitely present in 1.2022.2, 1.2022.14, 1.2023.0, and 1.2023.3). I note that version 1.2022.2 introduced the new default skin, so I wonder whether it is somehow related to that?

It is possible to work around this using Creole and or HTML formatting in the class title, e.g.:

```plantuml
class "<size:14><b>Class2</b></size>" as c2 {
   ...
}

class "<size:14>**Class3**</size>" as c3 {
   ...
}
```

But this is a bit of a hack and regardless it still seems incorrect for `ClassAttributeFont...` to override `ClassFont...`.

I guess this will eventually be made obsolete by the new style/theme engine, but that still has a ways to go 😄.

Note that this is **not** the same thing as #1287, which as far as I’m concerned is expected behaviour and not a bug. (If you set `skinparam ClassFontStyle bold`, then *of course* all the text in the class will be bold! 😆)

**Comment by The-Lum** [comment]
Hi @nstanger, and all,

With the new versions, it is now better to use new `style` instead old `skinparam`, as:
```puml
@startuml
<style>
class {
  FontStyle plain
  FontSize 10
  header {
    FontStyle bold
    FontSize 14
  }
}
</style>

class Class {
    -attr1
    --
    +method1()
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuR8fBgdCIRNZIiv9B2vMgEPIK73Bpoi91Wag5EGaPkR1H3AhKXKC3O2yZDJ4bDGYi59anKdvEIa88R1g4o2_bgkMoqOVQWdK5cUuNGeAkeab9KM64AOkcDBEJIt9o4ynrD04QdL8pKi1EXC0)](https://www.planttext.com/?text=SoWkIImgAStDuR8fBgdCIRNZIiv9B2vMgEPIK73Bpoi91Wag5EGaPkR1H3AhKXKC3O2yZDJ4bDGYi59anKdvEIa88R1g4o2_bgkMoqOVQWdK5cUuNGeAkeab9KM64AOkcDBEJIt9o4ynrD04QdL8pKi1EXC0)

**Enjoy,**
_If that can help,_
Regards.

**Comment by arnaudroques** [comment]
As @The-Lum said, it's better to use style now.
skinparam are still supported only to keep compatibility with old diagrams, but you should not rely on it.

We have partially fix the issue: you have to [change the order of declaration](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpimhI2nAp5Mevb800kUSnE9YnvAIeioaqf9Kj_oyak2IofnKXOASnCmyN2eogr8L30qGiWXjIVavAGXnX68JhbgkP90GH09gkMuYq5X325CNJ6ddffPavASOQcW2DJYavgK0tGm0).

```
@startuml
skinparam {
    ClassAttributeFontStyle plain
    ClassAttributeFontSize 10
    ClassFontStyle bold
    ClassFontSize 14
}
class Class {
    -attr1
    --
    +method1()
}
@enduml
```

Unfortunately, we cannot do better, because now, internally, skinparam are now translated into style directives.
And order does matter for style.
