### ISSUE TITLE
PNG image truncated

### ISSUE THREAD

**Issue by kenorb** [plantuml/plantuml#135]
I've got a long sequence diagram, but it gets truncated at the bottom when converted to PNG (resolution: `1396x4096`).

How to prevent it?

Errors:
```
(2.506 - 256 Mo) 185 Mo - Height too large 5127
(2.506 - 256 Mo) 185 Mo - Creating image 1396x4096
```

**Comment by arnaudroques** [comment]
You can change PLANTUML_LIMIT_SIZE setting.
See http://plantuml.com/faq
We will probably add such message/tip in the log for next release.

**Comment by kenorb** [comment]
Thanks. Is there any auto setting, how should I know what size I would need for my diagram?

**Comment by kenorb** [comment]
For the workaround, I've changed the direction from left to right. See: GH-133
