### ISSUE TITLE
Unable to use parts of awslib in version v1.2022.13 and later

### ISSUE THREAD

**Issue by or1can** [plantuml/plantuml#1351]
**Describe the bug**
We generate diagrams using the PlantUML that include AWS components from the awslib standard library. After updating to version v1.2023.4 we're unable to generate these diagrams, even though no changes have been made to them.

It does not seem to affect all AWS components in the awslib standard library.

**To Reproduce**
1. Using this diagram:

```
@startuml
    !include <awslib/AWSCommon>
    !include <awslib/Compute/EC2.puml>
    !include <awslib/SecurityIdentityAndCompliance/WAF.puml>

    EC2(ec2, "ec2", " ")
    WAF(waf, "waf", " ")
@enduml
```

2. Generate using PlantUML v1.2022.13 or later results in the following error:

```
Error line 4 in file: [filename]
Some diagram description contains errors
```

**Expected behavior**
The digram is successfully generated.

**Desktop (please complete the following information):**

- OS: macOS
- Version 13.2.1
- openjdk version "19.0.2" 2023-01-17

**Comment by arnaudroques** [comment]
You have to use:

```
@startuml
!include <awslib/AWSCommon>
!include <awslib/Compute/EC2.puml>
!include <awslib/SecurityIdentityCompliance/WAF.puml>

    EC2(ec2, "ec2", " ")
    WAF(waf, "waf", " ")
@enduml
```

We just follow AWS convention here. Not sure why `SecurityIdentityAndCompliance` has been renamed.

BTW, version 10 and version 14 of the library are both included now.
By default, `<awslib/...>` points to the last version.
But you can select a specific version if you want to:

```
@startuml
!include <awslib10/AWSCommon>
!include <awslib10/Compute/EC2.puml>
!include <awslib10/SecurityIdentityCompliance/WAF.puml>

    EC2(ec2, "ec2", " ")
    WAF(waf, "waf", " ")
@enduml
```

It's really up to you.
Hope this helps!

**Comment by The-Lum** [comment]
Hi @or1can,

Change just _(suppress the `And`)_:
```puml
    !include <awslib/SecurityIdentityAndCompliance/WAF.puml>
```
to
```puml
    !include <awslib/SecurityIdentityCompliance/WAF.puml>
```
And see the expected result:
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL800iNClEISqfHK1Pl4ykASp2Hzn_1Wv_pStFmyE-poGCc2qf9KVLTd8xq2e2aub0Md9fSMPPPKUgQavfK0QP2sdCp4lEHK_N17DwXEi5QWGHgfoKOw2af0KWb8AIXfWYM0wZJA4zE08a0I9k6GcfS2r0i0)](https://www.planttext.com/?text=SoWkIImgAStDuL800iNClEISqfHK1Pl4ykASp2Hzn_1Wv_pStFmyE-poGCc2qf9KVLTd8xq2e2aub0Md9fSMPPPKUgQavfK0QP2sdCp4lEHK_N17DwXEi5QWGHgfoKOw2af0KWb8AIXfWYM0wZJA4zE08a0I9k6GcfS2r0i0)

_Enjoy,_
Regards.
