### ISSUE TITLE
Regarding the February update with intermediate namespaces

### ISSUE THREAD

**Issue by michaelraue** [plantuml/plantuml#1352]
[The news](https://plantuml.com/de/news) from 2 Feb, 2023 says:
> The drawing is slightly different, because we now also draw intermediate packages
> ...
> That leaves the drawing part, and let's see how you react here.

So I would like to react 😊
When I understand correctly this means that in the previous version this PUML:
```puml
@startuml
class A.B.C.D.Z {
}
@enduml
```
had printed the diagram

<img width="68" alt="image" src="https://user-images.githubusercontent.com/75360720/226914607-ca00f558-e852-4def-a5ac-c378ee0d0117.png">

whereas in the new version I get

<img width="168" alt="image" src="https://user-images.githubusercontent.com/75360720/226914486-9543f01a-5e94-4b20-b278-c91114119afc.png">

If that's right I would highly recommend to make this configurable. I have a project with many namespaces/classes and like to create diagrams with different points of view, e.g. one diagram per namespace. In the new version it I looks very cluttered:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/75360720/226921018-df9e9659-45b8-45d0-9cab-5f83aa49f372.png">

**Comment by arnaudroques** [comment]
A possible [workaround is to use](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIfEBL4eJYr8B4eioIzIoClFI-KgI4pEJanFLN3KSz9prdDHgEPApaaiBbQ80h9gWT0XDIy5g1K0):

```
@startuml
set separator none
package A.B.C.D {
  class Z {
  }
}
@enduml
```

Now I understand that this workaround may be too complicated for you.
Tell us what you think about it!

**Comment by arnaudroques** [comment]
> Btw don't get me wrong, I absolutely love PlantUML and this is by no means a show stopper, but if this thing could be configurable it would help a lot.

Don't worry, no problem!
The real fact is that we are completely out of inspiration about a **nice syntax** that would rollbacks the drawing to previous versions :-)

What about: `!pragma do_not_draw_intermediate_packages true` ? It's too long.
Any suggestion is welcome!

**Comment by michaelraue** [comment]
Based on the existing pragma `useVerticalIf` how about something like `useIntermediatePackages`?

**Comment by arnaudroques** [comment]
So with last snapshot, you can [now have this](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuL8iA4fCpqrKA2rEzSmhIItAJKt9J2n93KXCpavCJorMI4lCAKxbIiv9B2vMSDHpqdFMSz6BKgZcgkLoICrB0Pe00000):

```
@startuml
!pragma useIntermediatePackages false
class A.B.C.D.Z {
}
@enduml
```

It has not been widely tested, so any feedback is welcome!
Thanks

**Comment by michaelraue** [comment]
This is awesome, thanks a lot! First impression, it works flawlessly.

Any chance to push the snapshot as a Docker image tag on Dockerhub [plantuml/plantuml](https://hub.docker.com/r/plantuml/plantuml)? Then I could test it directly in my whole environment.

**Comment by evantill** [comment]
Hi,

I'm working on the release workflow of the [plantuml-cli docker image](https://github.com/plantuml/docker/tree/main/plantuml-cli).
I have just released a snapshot.

⚠️ It's a work in progress but you can try it .

```shell
docker pull ghcr.io/plantuml/docker/plantuml-cli:latest
```

```shell
docker run --rm -it \
                 --volume "$PWD":/wd \
                 --workdir /wd \
      ghcr.io/plantuml/docker/plantuml-cli:latest your_diagram.puml
```

> Note: this command mount the current working directory. You have to execute it in the same directory as your diagrams files

**Comment by michaelraue** [comment]
Thanks a lot! You guys are incredibly fast and did a superb job, it works very well. Now all my diagrams are nice and clean again, and on top of that I can choose for each one if `UseIntermediatePackage` should be `true` or `false`. Awesome!

The above diagram now looks like this:
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/75360720/227240886-1b0af6e6-5a8e-4d1a-8b3d-9721a64e1d00.png">

Again, thanks for the great work you do with PlantUML!
