### ISSUE TITLE
[gantt] make it possible to color last day

### ISSUE THREAD

**Issue by blacklightprism** [plantuml/plantuml#1367]
**Describe the bug**
When using the Gantt-Diagram Mode, the last day of the diagram can not be colored, it keeps its default color. You have to add a event or milestone after the day you want to color. Especially if the last day is a important milestone, it would be great if you can color this whole day.

**To Reproduce**
See online: 
[last day not colored](http://www.plantuml.com/plantuml/uml/TP2nQiGm341tVOL-8E0a7NhRKKhdma6Na44NwveKsmgMCjpVrqsuK58w6JyzusUVrIZR9oKpUC_onOFXYXHjP6oSZIWtL9wDuvLp8VKpNCYMxEckI9bn2ABiuRAa8_gHAtUgcXfDSD-rcoD1CdkS4Yg5AEaVlNMhdYWMkVkWWMoIL8wjXIyqKYJjeNjTOhpt64XBVErmYqd-yPuTtOpp1W6wDv4UHvfdJefFVvKjgdPLSy99VqTVmyBxj7M7QLa0EkmVjvFXxWASEVdrqxy1)
[workaround](http://www.plantuml.com/plantuml/uml/TP2nQiGm341tVOL-860d7NhRKKhdma6Na44NwveKsmgMCjpVDqsuK58w6JyzusUVrQZO9sKpU2_onRtXYXHjOAoT3IWtL9wCqvNBGlmpNCZc4kYkI8MnZw8Su3Bd8_gHAtUgQeyckE-QpP4eXGEE6PLYaloFthXLpvGMkVsWdcoKl1nR2rzee4JQGViwftJlC9AQedUunUJmUC-ERiPbWm3jcqY70qqJPyMdlyeMvLrLdt3Ktz7NEFC-RTnXkYm0BNQFsybmTpt0cNDOV_qR)

**Expected behavior**
The last day should be colored as mentioned in the code.

**Desktop (please complete the following information):**

- Edge Browser on windows in Web Version as well as with VSCode Extension preview.

**Additional context**

**Comment by The-Lum** [comment]
Thanks for this report.

[For PlantUML team, see a similar issue here:
- https://forum.plantuml.net/14494/is-it-possible-to-color-the-days-in-the-default-gantt-diagram?show=14569#c14569

_To help to debug._]
Regards.

**Comment by arnaudroques** [comment]
Last beta [allows this now](https://www.plantuml.com/plantuml/uml/RP31IWCn48RlynG_UF2mb4woIgz5sZx1tgI7eHksgp6HP3puzawx5YJs-isNxuTigqhHIP8gVPRy5awAAwhGSu1dtw_vQSsEQDSzGpDstGPI0auvvX96p0bndixw4hy24Rsgr7TtH9Hg3OzHlki2_V5M5hMA8nj8k9qMl-Vb0TcTCTU_ArEEuuMxXkSYQRBfHmpu298gD5k4XbLhFXmEJ4F7_p1VSDzYDjkg-zzgI2FjLxwrDio6tNtCzp3HrbhNF_y1).

```
@startgantt
project starts the 2023/04/01

D+5 to D+7 are colored in lightBlue


[task1] lasts 2 days
[task2] starts at D+1
then [task2] lasts 30 days

D+10 is colored in gold
D+11 is colored in orange

' T means today
T-1 is colored in #FF0
T+0 is colored in #F00
T+3 is colored in #0F0

' E means end
E-2 is colored in #700
E-1 is colored in #700
E-0 is colored in #700

@endgantt
```

This is not perfect, since you have to use 'E' after all tasks definition otherwise it is not accurate.
So, does is help?

**Comment by blacklightprism** [comment]
This helps.
Thank you very much for the quick fix!
I think this can be closed then.
