### ISSUE TITLE
Multible breaks in one repeat

### ISSUE THREAD

**Issue by bjoernbeuckesr** [plantuml/plantuml#1369]
**Describe the bug**
if I use multiple break conditions in a repeat while only the first
have the correct behavior and breaks the repeat loop all other 
breaks, points to nothing

**To Reproduce**
@startuml
start
  repeat
    :process data;
    if(processing fails?) then (yes)
      break
    else(no)
    endif
    :upload data;
    if(upload the data fails) then (yes)
      'arrow points to nothing
      break
    else (pass)
    endif
  repeat while (more data?)
stop
@enduml

http://www.plantuml.com/plantuml/umla/XOyn3iCW34LtJk4Hhj0EoLNSOXfK0WWJLRrzBJjBfdhwUXyzz5UUEEQn5wV10GpgX1BaRdsq9p53n8btHJdv4-RwWeIvy19WRbJ1Vuc30xt787nhfiBaQxE2Qip9r4Sl3UFLV3AnAJVzNpluZipN3sm4VBPSfD_RCECIP6RhRfLtila7

**Expected behavior**
the following breaks should point to the first break arrow

**possible workaround**
work in the second with goto and set a label by the first break. But, sometimes plantuml draws a vertical line from the end of the second arrow to the first break through the elements above (breaks are on the same level, or in other words they are in a straight line top of each other)

This occures in the plantuml webserver version

**Comment by arnaudroques** [comment]
This should [be fixed now](http://www.plantuml.com/plantuml/umla/XOyn3iCW34LtJk4Hhj0EoLNSOXfK0WWJLRrzBJjBfdhwUXyzz5UUEEQn5wV10GpgX1BaRdsq9p53n8btHJdv4-RwWeIvy19WRbJ1Vuc30xt787nhfiBaQxE2Qip9r4Sl3UFLV3AnAJVzNpluZipN3sm4VBPSfD_RCECIP6RhRfLtila7).

Tell us if it's not working for you!
