### ISSUE TITLE
Support notes on references

### ISSUE THREAD

**Issue by dgileadi** [plantuml/plantuml#1382]
This diagram:
![ref with note](https://www.plantuml.com/plantuml/png/9OxHhG9124N_gU8sy1hOZvVL6co07T4XGTZCeFNBkWa9uN1FSjUPFFBzCjfhQzETFN4nRKBSCWQkiH7z0Fx-ZmiBkfW5qP07uYDd1hXrdMZis0JX1QRKamscBfF4xoY3o2C5GvyzbzEfOHoKrWfLcIy0)

Contains [this code](https://www.plantuml.com/plantuml/uml/9OxHhG9124N_gU8sy1hOZvVL6co07T4bGTZCeFNBk0a9uN1FSjUHtFFzCZfgQzE3FN4nRKBSCZgkiH7z0Fx-vuK5kvW5KPS7uYDd1hZjEj3OiGd22mof9njCNGQ9tr46aKSAkZxtN4wdXZ4fqLgfsUOB):

```plantuml
@startuml
participant Alice
actor Bob

Alice -> Bob : hello

ref over Bob
  This can be on
  several lines
end ref

note right: This is a note
@enduml
```

I would expect the note to display to the right of the `ref` box rather than to the right of the `hello` message. Also note that if the `hello` message doesn't exist in the diagram, the note [doesn't display at all](https://www.plantuml.com/plantuml/uml/9Ov13i9024NtdEBlN7c1Bapr35w0ZcX949ePzFnIcv0G7lybVnx9FJzlewssDjtO4rVJ9iGje-CM2z7fJt2-x2Sch68MH5sUYAyS8U2-wa1Zno88Bp2adcmmTHaa_a0PH1ufwFfQSpgS6iPEQQvGjVa1).

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be [fixed with last version](https://www.plantuml.com/plantuml/uml/ROv13i9024NtdE9Vm8Kkkp3LCtY1wOYM1A6PGSylTROc98Jt-8IvHsdnVYbjsQNALYnmKQbCfOOtN7qX-W4Splk42IkhEfa7eybpZGctLJgo2dPw96hyW7zuv35yBOQ5uPQWSygYK37kn7P79kZ_pG6mknFDkPl_VW40).
