### ISSUE TITLE
YAML Highlight - Custom color for specific entries

### ISSUE THREAD

**Issue by juicybox** [plantuml/plantuml#1393]
Usually you highlight important things in your YAML diagram, but sometimes it is also useful to show a highlighted alternative or optional values with a different color.

A possible solution might be a color option like: → '#color', '#red', '#E3E3E3'

````
@startyaml

#highlight "color"
#highlight "size" #red

fruit: Apple
size: Large
color: 
  - Red
  - Green
@endyaml
````

**Comment by The-Lum** [comment]
Hi J., and a ll,

Yes, you can do that with `style`, as:
- https://forum.plantuml.net/15756/yaml-multiple-highlight-defs?show=15756#q15756

Enjoy,
Regard.

**Comment by The-Lum** [comment]
Here is an example:
```puml
@startyaml
<style>
    .h1 {
      BackGroundColor green
      FontColor white
      FontStyle italic
    }
    .h2 {
      BackGroundColor red
      FontColor white
      FontStyle bold
    }
</style>
#highlight "color" <<h1>>
#highlight "size" <<h2>>

fruit: Apple
size: Large
color: 
  - Red
  - Green
@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/ZP2n2i8m48RtFCLHvohjM4Af2dPnqYU8pTa4OrBI5AdYkvl433e81Wx2_v7lBjUCZbatiwiYT7Ipmfg0FqjHm2FU03QikxJMJ9flZJ8MUeke4ziPxTxfJKY77-ano40wfcGNusSIbp_55lcVsfDHF4dfAesz4B8NofU3h0jlCw1K5FKt6UKT8oWz86SxILV1UXWKae0gs3FR8uc22doF70vnh1pQ-Ey6DG_hUW40)](https://www.planttext.com/?text=ZP2n2i8m48RtFCLHvohjM4Af2dPnqYU8pTa4OrBI5AdYkvl433e81Wx2_v7lBjUCZbatiwiYT7Ipmfg0FqjHm2FU03QikxJMJ9flZJ8MUeke4ziPxTxfJKY77-ano40wfcGNusSIbp_55lcVsfDHF4dfAesz4B8NofU3h0jlCw1K5FKt6UKT8oWz86SxILV1UXWKae0gs3FR8uc22doF70vnh1pQ-Ey6DG_hUW40)

_Enjoy,_
Regards.

**Comment by juicybox** [comment]
@The-Lum This is great, thank you for this tip!

**Comment by The-Lum** [comment]
Hi @juicybox, and all,

Thanks,
We updated also the doc. here:
- https://plantuml.com/en/yaml#d8ffd91ff7cbc8d8
- https://plantuml.com/en/json#d8ffd91ff7cbc8d8

_So we can now close this issue._
Regards.
