### ISSUE TITLE
Start and end nodes can only be styled globally in CSS style

### ISSUE THREAD

**Issue by andreaskrauss** [plantuml/plantuml#1394]
**Describe the bug**
The start and end nodes cannot be changed between different diagram types (e.g., activity and state charts) using the CSS style, since they are defined only globally. I am not sure, whether all diagram types having start and end nodes are affected. In this issue, state charts are affected.

**To Reproduce**

1. define a `<style>` section
2. add intuitively to the style:

```puml
<style>
stateDiagram {
  circle {
    start {
      BackGroundColor "#f00"
      LineColor "#f00"
    } 
  }
}
</style>
```

or

```puml
<style>
stateDiagram {
  startColor "#f00"
}
</style>
```

or

```puml
<style>
stateDiagram {
  start {
    BackGroundColor "#f00"
    LineColor "#f00" 
  }
}
</style>
```
3. add state chart:

```puml
@startuml
[*] --> State1
State1 --> [*]
@enduml
```

4. See that the color of start and end nodes is not changed.

**Expected behavior**
The start and end nodes should receive the defined color. 

**Desktop (please complete the following information):**

- OS: Windows 10/11
- Browser: Chrome v112.0.5615.121

**Additional context**
* Creating a custom theme
* Additionally it is very unclear to me at the moment, which things are supported in CSS style, yet.
* [Current state of CSS style API](https://github.com/plantuml/plantuml/issues/880#issuecomment-1023513547)

**Existing Workaround:**

Thanks to @The-Lum, there is an already working workaround:
```puml
<style>
stateDiagram {
'...
}
start {
    BackgroundColor #palegreen
    LineColor #pink
    LineThickness 2.5
}
end {
    BackgroundColor #palegreen
    LineColor #green
    LineThickness 2.5
}
</style>
```

Based on this [example](https://www.plantuml.com/plantuml/uml/bP6nIiSm48VtFCM1Wo3y8qbraH2AEZgwYKD8ZpOqJIH91n7VtIDDYnqSp13klj_nXIDzBYQLTV5CvVBfKJC21P-T6PDPu8jTSyxPDwjZr0ATHsFdCSKr34_HnmHN7yRZc113ZLzSm3rmOJxOw-Ji731daFoUb1Y6VmiR_CEeRjiEsn9GR_6xaT0wEqLdKO1IMwLr2p0C7G1GG1NHjvjtk5pqoIMWejtn08BjzJ4gWRWyyQOctfquFK7iZlKqG3_n0m00).

> Short Remark:
> Thank you for that quick support and guidance @The-Lum .
> And also the plantUML team to provide such an versatile tool.
> Furthermore, thank you for introducing the CSS style, it is much more intuitive and simple to write ❤️ even if it is hard to guess which things work at the moment.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should [be fixed now](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuUAoAIwfp4crumAAbAIwP2Qc5oNcAbHpSO9LW1WAGE2Kc9oTNfHVcfVYd9-JNwIWN92OavfUb9gQ1v7toSnBXSbavcKZ14CoCfEpyrABYnMCz4ovE6kvE5FpKiWm5IoAnzXQBXjzg4UuehLY5NHrxHI2GJuov89GO16W39S3q050ZmC0).
