### ISSUE TITLE
When connecting attributes between object graphs, the connection error

### ISSUE THREAD

**Issue by jukkui** [plantuml/plantuml#1397]
**Describe the bug**
When connecting attributes between object diagrams, the attribute value contains other attribute name, and the connection will be incorrect.

**To Reproduce**
The example is as follows
```plantuml
@startuml
object myobj {
    attr1 = "xxxxx attr2 xxxxx"
    attr2 = "value2"
}

myobj2 -> myobj::attr2
@enduml
```

**Expected behavior**
I want myobj2 to connect to myobj's attribute attr2, but actually connected to attr1.

**Screenshots**
![image](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuSfFoafDBb78hGGo5Agv580WiQIao531La6f0WJ0N2C5C5i9Bcy4aYzBp2bDDLBYgkNY0kitKj2rWvXaPGLMnEMGcfS2j0K0)

**Comment by The-Lum** [comment]
Hi @jukkui and all,

This issue occurs with `object`, and _as well_ for `class`...
## Issue
Here are minimal issue example:
```puml
@startuml
object o {
    attr1 = "attr2"
    attr2 = "value2"
}
class c {
    attr1 = "attr2"
    attr2 = "value2"
}

myobj2 --> o::attr2
myobj2 --> c::attr2
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuSfFoafDBb78LwZcKW22n9AI8aC5MmKb4CD82Ivc118hIymfJGKArd8bvoGM5oiaawQ9AxSIQ9kHWgwkdKA-bHLO1R9OCapC8JKl1UWs0000)](https://www.planttext.com/?text=SoWkIImgAStDuSfFoafDBb78LwZcKW22n9AI8aC5MmKb4CD82Ivc118hIymfJGKArd8bvoGM5oiaawQ9AxSIQ9kHWgwkdKA-bHLO1R9OCapC8JKl1UWs0000)

## Workaround 
Here is a possible workaround using `Unicode`, as:
```puml
@startuml
object myobj {
    attr1 = "xxxxx attr<U+0032> xxxxx"
    attr2 = "value2"
}

myobj2 -> myobj::attr2
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuSfFoafDBb78hGGo5Agv580WiQIao531La6f0WJ0N9jGRGC3OoCx1R2G4boP4KXPMM9EQQgH4bSj5nVO62C5NJk8WLPMO4LS3gbvAK3B0000)](https://www.planttext.com/?text=SoWkIImgAStDuSfFoafDBb78hGGo5Agv580WiQIao531La6f0WJ0N9jGRGC3OoCx1R2G4boP4KXPMM9EQQgH4bSj5nVO62C5NJk8WLPMO4LS3gbvAK3B0000)

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @arnaudroques and PlantUML team,

Here are some similar tests.
## Note: OK
```puml
@startuml
class c0
class c1 {
    attr1 = "attr2"
    attr2 = "value2"
}

note right of c1::attr2
 note about attr2
end note

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JOz12i9034NtESMd8Eh2qexeeg0KF80NS3DjKnNg36GotOXtTrfHp2QVzyY7r46jQ7mCr0us1BJ5DvHu4j9OLIbnG3O5a_sOcTXeXyW9leYMRO7DCTrLrQo9d5U6tAytXU__16PX6n_rqqJikXaIzJujmRa9B2Dty0vbRWgppVSDgzrT74vHX9rYCRA4ktUhDTMf8Ftm1W00)](https://www.planttext.com/?text=JOz12i9034NtESMd8Eh2qexeeg0KF80NS3DjKnNg36GotOXtTrfHp2QVzyY7r46jQ7mCr0us1BJ5DvHu4j9OLIbnG3O5a_sOcTXeXyW9leYMRO7DCTrLrQo9d5U6tAytXU__16PX6n_rqqJikXaIzJujmRa9B2Dty0vbRWgppVSDgzrT74vHX9rYCRA4ktUhDTMf8Ftm1W00)


## Connecting attributes: ~KO _(this defect #1397)_
```puml
@startuml
class c0
class c1 {
    attr1 = "attr2"
    attr2 = "value2"
}

c0 -> c1::attr2
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JOz12i9034NtESMd8DM5fQteeg0KF80NS3DjKotK6SXakX7lxhIec4q-xv70hxqQqV0OgHsDzsZpRoZm9CGngbBWY6GEPV9ZvSmcCmQEy4NKvjYUubbLBPOejKuPCjpk2jV_cHIBCOqBYWzYsosKg7Tn2IwDPvcuWxCeiZ8lTzcXOJNxgyKvYB1Lh2OMFpYxtb0T7yGMRm00)](https://www.planttext.com/?text=JOz12i9034NtESMd8DM5fQteeg0KF80NS3DjKotK6SXakX7lxhIec4q-xv70hxqQqV0OgHsDzsZpRoZm9CGngbBWY6GEPV9ZvSmcCmQEy4NKvjYUubbLBPOejKuPCjpk2jV_cHIBCOqBYWzYsosKg7Tn2IwDPvcuWxCeiZ8lTzcXOJNxgyKvYB1Lh2OMFpYxtb0T7yGMRm00)

## Note + Connecting attributes:  `java.lang.IllegalStateException`
```puml
@startuml
class c0
class c1 {
    attr1 = "attr2"
    attr2 = "value2"
}

c0 -> c1::attr2

note right of c1::attr2
 note about attr2
end note

@enduml
```

```json
An error has occured : java.lang.IllegalStateException
PlantUML (1.2023.6beta5) cannot parse result from dot/GraphViz.
GraphViz version used : version 2.38.0 (20140413.2041)
```
```cy
java.lang.IllegalStateException
net.sourceforge.plantuml.svek.SvekLine.getExtremity(SvekLine.java:517)
net.sourceforge.plantuml.svek.SvekLine.solveLine(SvekLine.java:609)
net.sourceforge.plantuml.svek.DotStringFactory.solve(DotStringFactory.java:451)
net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:468)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:105)
net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:70)
net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:435)
net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:84)
net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:142)
net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:198)

```
_In order to help you for debugging..._
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all, and @arnaudroques,

With a new test:
- the note is OK ✔️ 
- but the arrow is always KO... ❌ 

```puml
@startuml
class c0 {
a
}
class c1 {
    attr1 = "attr2"
    attr2 = "value2"
}

c0::a -> c1::attr2 : <color:red>arrow to attr2 KO

note right of c1::attr2
 <color:green>note about attr2: OK
end note

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/HO-n3i8m34HtVuNL7Qdj647KlKE_mQIX88LOSbqOKFyTfr3mT7U-DrmtAuakzmGXqJnZgF451Ejk6xDeHwhIu0ch8jhgbxKbUr1QeeKhGAYT8pnu8qri1OV7m8d5IHmzYV0JbRzmFm1areXocwwAVFbpi6EJn9Zzrg8pB_f17Guzn3nYUG1q9ct56m00)](https://www.planttext.com/?text=HO-n3i8m34HtVuNL7Qdj647KlKE_mQIX88LOSbqOKFyTfr3mT7U-DrmtAuakzmGXqJnZgF451Ejk6xDeHwhIu0ch8jhgbxKbUr1QeeKhGAYT8pnu8qri1OV7m8d5IHmzYV0JbRzmFm1areXocwwAVFbpi6EJn9Zzrg8pB_f17Guzn3nYUG1q9ct56m00) 

Regards,
Th.
