### ISSUE TITLE
Labels overlapping in component diagrams (Web version)

### ISSUE THREAD

**Issue by ghost** [plantuml/plantuml#140]
Labels are overlapping each other and appear to not be considered in graphViz layout using 2.38.0 on PlantUML web version:
http://www.plantuml.com/plantuml/png/VLJDSfim4BxhANRIKmzSyWIf-vF9T3hEE3dceiB6rXWaHYnfy_RTBW8al3476tq_qYTfbxk1RAInQyrmThwtqNPGXwuF7ZqzqNkBmEIjCSuJnbTR8zmSx9yRi0Fm_qDdZmYVTgsjpxdaCUAR2-C0pv6P0KG_WmbBhjpsDSI8DM43Ch6u5aoW8iV-OSeHt9DhJs548jIdOodyiiDPcP7T_vd2DxB0qnJYnV_4zpumFOWxaGjunGZVSAYZwod4mfl1kLlEXMDIVS9qP3-YxV1MVeLDfD4M5K6npeGer_Eb9lU6kMD29i00FsQfWZdOOyJ6iInukBVa_56CmgtKn9ZDLN-kgW-4AWeiJnWsec2STvrdMcySxj5Zj1IY15g91JVAP9mfkkE9AjMWO1ngKsbvdAaH3jZPNbB8M8QcCAtBvehKI4mM-FhAYsyR8IVJb7fXvp7dgkNA95Qc8vlH6JJgH9BkkdJPdYBS0hAbRI_bMVU77Np_Iz4kEVVnjm3wmbN9R-TcHOklj57b0qW2fKlpNDADrNEevEN5fuwDsuPDy0V5L-dIicrqrMK-NQcUWQgxX424-iVdyjEm6rtRf1CGH01rG_pa4dqtkYRVHogpKgO7JZU_5US3u5JbHzFSeM_6hlq7

**Comment by arnaudroques** [comment]
Thanks for the report.
This one is difficult to fix.
With last beta http://beta.plantuml.net/plantuml.jar you can add a new skinparam:
`skinparam fixCircleLabelOverlapping true
`
This somehow improves the drawing.

**Comment by Crog** [comment]
An older version (not sure which sadly) didn't have overlap but connecting lines were wrong directions. Something has been fixed there I guess conflicting with label spacing.

**Comment by arnaudroques** [comment]
So [this works better now](http://www.plantuml.com/plantuml/uml/VLJDKjim4BxhANRegGTVU08ARHccxOG97Ba8PvDe8akUjPp2stUxLXnPMV0XiRuVwPEqwviXMKfZvyrmSA6tP3jeOzV7W24zfNUFmEHrmMxTsvsZrkDl-uf-TKJojkzTs46Y4S4O5nBIrhO8Lslxzmhi0Fp_qDaTmfTRRzj3ANaaFBeu3l1Cp0mW-XEOiUmgRNUH2Dk46v29nJLZ0Yroh1wc7D4zER-F8wQ4-dGiXJzsE2Wpili_i_2DB0W9X7y9l_2zZqmFuixa37vYXEyujEJw56dXBU3IBUV2CLExntnaFybsU2s_mcRIQ8kAOB7EX2ZNywrDxeYbOq8cm00_PgwNKx17merZMGnmRnENXXY5ErCJOwgh_jeq7mXL55YUCTo8Wd7UTPdfVEDmZm79faWIw4pCk54cuqpaTllKg0O5ur1LfPLnfaPOOsTxII5Z6Pg5wRnigSYDnEG2Fx_oudKZb6IUKY_iCkQfQhao4olpaPtG4sZKYIJTvz9vUugm1cHBTI-LMLVhM_ZnbiZEELVqAe2-S5FnrToiyBXDbQeSG1OeNLhcacvidcCZBoyXTopL3PlX3uglKQHAssYgotowKZi3NNS9WGZrZy_bf-5sT7wJJq0G0TGDyLDAzDsecd8VkSmgcHuuttmjBWV0gPOVJNE3OJDs_Xy0).
