### ISSUE TITLE
!include bugs

### ISSUE THREAD

**Issue by grivo** [plantuml/plantuml#1404]
**Describe the bug**
1. can't get **!include** working

**To Reproduce**
1. create file **include.puml**
2. insert following code here

```
@startuml index

class A

@enduml

@startuml xxx

!include_once include.puml!0

class B

@enduml
```

**Expected behavior**
diagram **xxx** should contain _class A_ from diagram **index**, but it does not

Probably, I'm using include incorrectly, but it should work according official docs

**Comment by The-Lum** [comment]
Hello @grivo,

1. What is your `plantuml.jar` version?
2. How to you call the program?

_[I just test with an old version, and I retrieve the 2 expected files:_
- `index.png` (with `Class A`)
- `xxx.png` (with the 2 classes `Class A` and `Class B`)

_with the good result.]_

Regards,
Th.

**Comment by grivo** [comment]
> What is your plantuml.jar version?

1.2023.5

> How to you call the program?

I use plantuml server, jetty version

> xxx.png (with the 2 classes Class A and Class B)

that's effect i want to get, but no luck

**Comment by grivo** [comment]
I have posted PlantUML plugin issue in case it's more client issue than server or PlantUML lib itself

https://github.com/qjebbs/vscode-plantuml/issues/543

**Comment by grivo** [comment]
seems to be rather client issue than lib, just tried to use plantuml.com as a rendering server... same negative effect

will close this ticket once client issue will be confirmed

**Comment by somecho** [comment]
I am experiencing similar issues. I am using the `plantuml/plantuml:latest` image. 

```sh
docker run plantuml/plantuml --version

PlantUML version 1.2023.12 (Fri Oct 20 13:49:54 UTC 2023)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.43.0 (0)
Installation seems OK. File generation OK
```

I have a project where the generated UML files are in a folder called `plantuml` in the root project directory. In `plantuml` there is an `include.puml`

```puml
@startuml
!include .\\.\ROOT\DataConnector.puml
!include .\\.\ROOT\Exceptions.puml
@enduml
```
Running ` docker run  -v C:\PROJ_ROOT:/data  plantuml/plantuml "plantuml/include.puml"` throws errors:
```sh
Error line 2 in file: plantuml/include.puml
Some diagram description contains errors
```
In the `output.png`, the error `cannot include ....` is rendered. 

This error does not happen when I use the standalone jar and use `java -jar plantuml.jar` in the same project.

**Comment by grivo** [comment]
it's rather an issue of VSCode PlantUML plugin for me, here is the link

https://github.com/qjebbs/vscode-plantuml/issues/543#issuecomment-1912264851

this ticket is irrelevant since it's hardly an plantuml lib issue
