### ISSUE TITLE
force notes to use inner namespaces not global namespace only

### ISSUE THREAD

**Issue by grivo** [plantuml/plantuml#1405]
**Describe the bug**
note names clash despite being declared at different namespaces

**To Reproduce**
1. this works
```
@startuml
class Cls

package X {
    class Cls
}
@enduml
```
2. that works as well
```
@startuml
class Cls

class X.Cls
@enduml
```

3. notes declaration don't work
```
@startuml
note as n
    my note
end note

package X {
    note as n
        my enother note
    end note
}
@enduml
```

4. neither this pattern works
```
@startuml
note as n
    my note
end note

note as X.n
    my enother note
end note
@enduml
```

**Comment by The-Lum** [comment]
Hello @grivo, and all,

Yes: because actually `notes` must have absolute name, _regardless of namespace usage._

_Perhaps create a `Wanted feature` to do that._

Regards.

**Comment by grivo** [comment]
hmm... can't find any namespaces restriction for comments at UML 2.5 specs

if it's rather PlantUML restriction - then you're right, it'll be wonderful to convert this issue to a type of **wanted feature**... or I can do it by myself somehow, I wonder?

**Comment by The-Lum** [comment]
>if it's rather PlantUML restriction

Yes, You are right.

This is now a _wanted feature_ for PlantUML.

---

Then, for _PlantUML team_, here is the minimal example to be manage by `plantuml`:

Could you manage:
```puml
@startuml
note as n
    my note
end note

package X {
    note as n
        my enother note
    end note
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuShBBqbLI2nMoEDI08BSIWMG05TgNWg4mLMGc9oTc9wg4A5G3LQ1gXwg9nKecf5Q1D424eFhh-Lo0BA15W40)](https://www.planttext.com/?text=SoWkIImgAStDuShBBqbLI2nMoEDI08BSIWMG05TgNWg4mLMGc9oTc9wg4A5G3LQ1gXwg9nKecf5Q1D424eFhh-Lo0BA15W40)

As:
```puml
@startuml
note as n
    my note
end note

note as X.n
    my enother note
end note
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuShBBqbLI2nMoEDI08BSIWMG05TgNWg40PUFq8EhI0MAPQGMeQbq0BA01W80)](https://www.planttext.com/?text=SoWkIImgAStDuShBBqbLI2nMoEDI08BSIWMG05TgNWg40PUFq8EhI0MAPQGMeQbq0BA01W80)

---

Regards.

**Comment by grivo** [comment]
problem remains the same for usecase diagrams, should be this ticket reopened?

**Comment by grivo** [comment]
issue eliminates ones **allowmixing** is applied and `actor` keyword is used instead of `: <value> :` 

```
@startuml
allowmixing

package x {
  note as _n
    qwerty
  end note
}

package y {
  note as _n
    asdfg
  end note
  
  actor "myActor" as a
}
@enduml
```

**Comment by grivo** [comment]
this does not work

```
@startuml
package x {
  note as _n
    qwerty
  end note
}

package y {
  note as _n
    asdfg
  end note
  
  :myActor:
}
@enduml
```

neither this works (even with **allowmixing**)

```
@startuml
allowmixing

package x {
  note as _n
    qwerty
  end note
}

package y {
  note as _n
    asdfg
  end note
  
  :myActor:
}
@enduml
```

**Comment by arnaudroques** [comment]
Using `set separator .` [improves the result](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEBL4eJYr8B4eioIzIqECgI4pEJanFLQXGgEPIKCZBBqbLI2nMYC_ZKW22mlBKef9A83CrBmKinrNB1TTHYKK7a9MIbewa0SW48glSIiTae7rMGFqEG2cWGm00).

This setting is by default for class diagrams.
Maybe we should set it also by default for usecase diagrams.

We are unsure here about what it the best behavior. Any though?

**Comment by grivo** [comment]
> Maybe we should set it also by default for usecase diagrams.

i think this is quite good option... since _package_ and _namespace_ are the same for class diagrams - so _namespace alike behaviour for package_ items anywhere else (usecases, deployment, etc) should be perfect solution

> Using `set separator .`

so i think that be turned everywhere package may be used

thanks!

**Comment by grivo** [comment]
it works now!

@startuml
note as n
    my note
end note

package X {
    note as n
        my enother note
    end note
}
@enduml

as well as

@startuml
note as n
    my note
end note

note as X.n
    my enother note
end note
@enduml
