### ISSUE TITLE
emoji support in plantuml

### ISSUE THREAD

**Issue by sebastian-schmid** [plantuml/plantuml#141]
Hello,

it would be great if the use of emojis is built in plantuml. Sometimes it is much easier and more lightweight to use icons. The open iconic icons available in plantuml are very limited so why not using the standard emoji set available on every device and lot of apps today?

Maybe it also makes sense to replace open iconic by font awesome (contains much more icons) and additional provide emojis.

What do you guys think about that?

kindly regards,
Sebastian

**Comment by arnaudroques** [comment]
That's a good idea. Note that Font Awesome library is included throuh PlantUML Standard library (see http://plantuml.com/stdlib )

However, it's difficult to find a free icon library with *vector* data (like open iconic).
It also to properly scale image http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEJin9LJ3XSifFKj2rKt3CoKnELR1Io4ZDoSctKIlFJCkqut98pKi1gWK0

About emojis support, you can use unicode characters (see https://github.com/plantuml/plantuml-server/issues/32 ) like in the following example : http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEJin9LJ3XIip9J4vLqBLJICfFKh1Ii0dLDdGpCp2qWx8i3A0i4sDJ6ClGq8xB8JKl1MWC0000

The issue with unicode characters is that  `<U+1F601> ` is not very user friendly. The suggestion to use `<U+beaming face with smiling eyes>` (which is the CLDR Short Name https://unicode.org/emoji/charts/full-emoji-list.html )  maybe too long. And printing depends on font support. But we may be interested if someone knows a short standardized name for those unicode characters.

**Comment by The-Lum** [comment]
FYI, for _emoji support in plantuml_ see _(from [v1.2021.16](https://plantuml.com/changes))_:
- #820
- https://plantuml.com/en/creole#68305e25f5788db0

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @sebastian-schmid for the request.
- Thanks PlantUML team for your work.

Regards.
