### ISSUE TITLE
Boxes in sequence diagrams should allow for creating participants after the fact

### ISSUE THREAD

**Issue by thefotios-enigma** [plantuml/plantuml#142]
I'm trying to build a sequence where I'm using a `box` to indicate 2 separate AWS accounts. I'm trying to visualize creating resources in each of them, but it appears as though once you create a `box` you can no longer add to it. 

In the following example, after creating `C` in `Box 2` I'd like to create `ZZZ` but under `Box 1`. 
 
<img width="278" alt="screen shot 2018-08-22 at 9 41 12 pm" src="https://user-images.githubusercontent.com/30440247/44499956-46cb6a80-a654-11e8-9165-8d41eb3f50a5.png">

I'm wondering if it's possible to pre-allocate the participants in the box, but flag them as hidden so that they're revealed when they're created. Maybe something like: 

```plantuml
box "Box 1"
participant A
hidden { participant ZZZ }
end box
...
box "Box 2"
create ZZZ
end box
```

**Comment by mgeorge** [comment]
You only need to declare the participants inside the box.  If you declare a participant, but delay its creation by using an explicit `create` then it does what you want.

The following works for me, and describes what you are looking for (I think):
```
@startuml

actor Foo

box
    participant A
    participant B    
    participant ZZZ
end box

box
    participant C
end box

Foo -> A++

create B
A -> B
return

Foo -> B++
create C
B -> C
return

create ZZZ
Foo->ZZZ

@enduml
```
