### ISSUE TITLE
Add support to style timeline fonts for gantt charts

### ISSUE THREAD

**Issue by hjoensson** [plantuml/plantuml#1421]
Plantuml is a great tool that is extremely flexible to configure. I recently found the gantt chart and have started to use it more and more for the planning of my product. They are great, but one thing bugs me and that is that it doesn't seem possible to change the font name and font size for the timeline.

![image](https://user-images.githubusercontent.com/810193/236767073-0a818c46-a791-4026-abeb-aaa91777f503.png)

Would it be possible to allow styling of font name and font size, perhaps sopmething like this?

```
<style>
timeline {
    BackGroundColor Grey
    FontName Helvetica
    FontSize 14
    FontColor White
}
</style>
```

**Comment by The-Lum** [comment]
_[Just for traceability]_
See similar pseudo request here:
- https://forum.plantuml.net/16401/how-to-set-fontname-for-timeline-in-ganttdiagram
- https://forum.plantuml.net/14030/how-can-the-timeline-font-color-be-changed-in-a-gantt-diagram
- https://forum.plantuml.net/13570/can-you-style-the-days-and-months-of-a-gantt-chart

Regards.

**Comment by kkrafft1999** [comment]
Hello, I found this issue and I am interested in a solution because I strongly need a sans serif font for my rendered graphics. 
Is there chance to get that fixed? 
Thanks for any response.
Kind Regards, Konrad.

**Comment by hjoensson** [comment]
I ended up exporting to svg and the a search/replace of the font elements.

**Comment by kkrafft1999** [comment]
Hello again me. :)
I found in the module _net.sourceforge.plantuml.project.draw.TimeHeader.java_ the following method:

	final protected FontConfiguration getFontConfiguration(int size, boolean bold, HColor color) {
		UFont font = UFont.serif(size);
		if (bold)
			font = font.bold();

		return FontConfiguration.create(font, color, color, null);
	}

Here you can see, that the font familiy is hard coded. in other objects like _AbstractTaskDraw.java_ the font will be genereted out of a style configuration:

	final protected FontConfiguration getFontConfiguration() {
		return getStyle().getFontConfiguration(getColorSet());
	}

Maybe there is a contributor, who is able to fix this. I hope that my analysis is not too naive.

**Comment by The-Lum** [comment]
Hi @arnaudroques and PlantUML team,

>It has not been widely tested, so feedback is highly welcome!

Is it plan to manage also those parameters?:
- LineThickness
- LineStyle
- BackgroundColor

>[![](https://www.planttext.com/api/plantuml/svg/JP3DJiGm38JlUGg_m8gsb1ChjFo84q98S4Dxi1AhQvewLMn01UsxKz9LuJYVPsoDTsgOhKCnSrkrATALA-gEiSiumBS3C1ueib0H0FT9x3R5b47mOrhHCtyHrDMg7t4WkCwCyS_oUm3OCB8ly67UkgpA55RoSc3V2wd2nSgMQ7lP5dA3lkzoUfUmf4UMVXuStT5jpqurnfpUo1kKXWfDrPnlwcPJrUxrAITBDeq4WPGxsKD4dJqrV1Brwkn00lzSFWrZ9AEmXvEpXO2JkXr9AE_w0G00)](https://www.planttext.com/?text=JP3DJiGm38JlUGg_m8gsb1ChjFo84q98S4Dxi1AhQvewLMn01UsxKz9LuJYVPsoDTsgOhKCnSrkrATALA-gEiSiumBS3C1ueib0H0FT9x3R5b47mOrhHCtyHrDMg7t4WkCwCyS_oUm3OCB8ly67UkgpA55RoSc3V2wd2nSgMQ7lP5dA3lkzoUfUmf4UMVXuStT5jpqurnfpUo1kKXWfDrPnlwcPJrUxrAITBDeq4WPGxsKD4dJqrV1Brwkn00lzSFWrZ9AEmXvEpXO2JkXr9AE_w0G00)

_[See (internally): [[Gantt] Possibilité de styler les timelines](https://github.com/orgs/plantuml/projects/6/views/1?pane=issue&itemId=25773231)]_

Regards,
Th.
