### ISSUE TITLE
Activity: Allow post-positioned `stereotype` style

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1422]
Hi PlantUML team,

- Could you allow post-positioned `stereotype` style on (beta-)Activity diagram?
_(like on Mindmap or WBS diagram...)_

Here is an example:

```puml
<style>
.test {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 1.0
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor green
  FontSize 11
  FontStyle bold
}
</style>
:a;
<<test>>:b (OK);
:c (Not yet); <<test>>
```
>[![](https://www.planttext.com/api/plantuml/svg/HSunJuH040NWVd_5D2RG89mv2o0aIcAZuGejRHOOkSsjCydiS0QD_zqbnyLollSoUNNGnMDZCiMWy6C0NXnXovu5UZzZX4Sxd2RXcSOBUpSTjLqiRUMtenjEX250aUNH7aJuwn_pR1_nYKax-uanTTP3PzVIvfUtao3I9g_k6w4ehjSw4Nhse_arzUsskBILgUjrTjEKFII7vxGovG19nmeBQbh1DJOVp8e2XpwWd744fhXrb-_kiliUrUxV2TfP14dXvemI75EIcZy0)](https://www.planttext.com/?text=HSunJuH040NWVd_5D2RG89mv2o0aIcAZuGejRHOOkSsjCydiS0QD_zqbnyLollSoUNNGnMDZCiMWy6C0NXnXovu5UZzZX4Sxd2RXcSOBUpSTjLqiRUMtenjEX250aUNH7aJuwn_pR1_nYKax-uanTTP3PzVIvfUtao3I9g_k6w4ehjSw4Nhse_arzUsskBILgUjrTjEKFII7vxGovG19nmeBQbh1DJOVp8e2XpwWd744fhXrb-_kiliUrUxV2TfP14dXvemI75EIcZy0)

---

_**Additional context & Ref.**_
## ✔️ OK Pre-positioned  `stereotype` style on (beta-)Activity diagram:
- https://forum.plantuml.net/12396/user-defined-style-targets-in-activity-diagram-beta

### Activity
>[![](https://www.planttext.com/api/plantuml/svg/HP11IyDG3CVl-HHX86p2QZkPfrAc1I_ATj2ZbzSrTe-z9f2NJgRutNrr5KyXl_m9lsGJpQaDVO0osZbG1PbHDFm2n6VFL4iGnIOCbC23snyxbO7R2mw-ErXzTZo5Nmz-VsIA4OiiJ-nULJx-OPwj4tmKjgthAKsz2xXrOsZYbxMT4l54NlmdOL7yTQCYDX9Q-8RoPZAUNozmkQpGWVkjiztJ3CjolAEg0Dv5Z1HtJIGzKOl2IM-LhswpkuRChTyOwq6LsF3gH1gzy7m16-As7__o0m00)](https://www.planttext.com/?text=HP11IyDG3CVl-HHX86p2QZkPfrAc1I_ATj2ZbzSrTe-z9f2NJgRutNrr5KyXl_m9lsGJpQaDVO0osZbG1PbHDFm2n6VFL4iGnIOCbC23snyxbO7R2mw-ErXzTZo5Nmz-VsIA4OiiJ-nULJx-OPwj4tmKjgthAKsz2xXrOsZYbxMT4l54NlmdOL7yTQCYDX9Q-8RoPZAUNozmkQpGWVkjiztJ3CjolAEg0Dv5Z1HtJIGzKOl2IM-LhswpkuRChTyOwq6LsF3gH1gzy7m16-As7__o0m00)

### Mindmap 
>[![](https://www.planttext.com/api/plantuml/svg/HP11JyCm38Nl-HM-8BMLAEtGEAnLDQZ41TGTuCWbQKqNBKsGumuDn7ydqGgxMFBtdgrdRprBuadROP8VelPyCjY8dD4pV0k0PssnTSOHA3DZ00-oFupaPZkSiT7ZdjkJj8lvTQ_xWqNleSoBmEw9tES55lawm4TdkPCJ1bLB0vsCfeMVruw4Q1VoehyGolAlYn51EJE87r7VB8apa22o35GiTHtpDyr69PrZE253TPscLT0sq8jazvHM_wOuC41a5_Jk72F1Jdca8mxWRBXcLQnkypk5BDTl5jgP22t3rH79QsUJL6mnV77vv2y0)](https://www.planttext.com/?text=HP11JyCm38Nl-HM-8BMLAEtGEAnLDQZ41TGTuCWbQKqNBKsGumuDn7ydqGgxMFBtdgrdRprBuadROP8VelPyCjY8dD4pV0k0PssnTSOHA3DZ00-oFupaPZkSiT7ZdjkJj8lvTQ_xWqNleSoBmEw9tES55lawm4TdkPCJ1bLB0vsCfeMVruw4Q1VoehyGolAlYn51EJE87r7VB8apa22o35GiTHtpDyr69PrZE253TPscLT0sq8jazvHM_wOuC41a5_Jk72F1Jdca8mxWRBXcLQnkypk5BDTl5jgP22t3rH79QsUJL6mnV77vv2y0)

Regards.

**Comment by arnaudroques** [comment]
The [first example is fixed](https://www.plantuml.com/plantuml/uml/HS_1QeGm40RW-pp57FLYzT2B1h4LUccnX_O5eWuQZ0aa8yKk--uRCRB7VFzF-AVnB1rlgmRXUTTKGyRa6M-0-AKCjLPRXxtUAC2x79R9sSsC9sirpTpkqiJoxwo6nP3tM6Hvi3VdxDyJy-mru8SrtCcLGgganauUfUZdjvCZCb5-r3zXKLolOoBsLezm1_4I5vUo0Y6EsNLTzfXyVwOLb0CcdMNSYTCAhnWQCcEuzW40).

About Mindmap, I think it is more logical to put the stereotype **after** the text.
There are some cases where the stereotype works before the text, but we keep it only for ascending compatibility.
People should not use this...

I hope this is fine for you.

**Comment by The-Lum** [comment]
Thanks a lot.

> I hope this is fine for you.
Yes. That's good. Don't modify the mindmap behaviour.

Regards.
