### ISSUE TITLE
Activity: Allow to style SDL stereotype 

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1423]
Hi PlantUML team,

## Context
To continue _(`style` on (beta-)Activity diagram)_:
- #1422
- https://forum.plantuml.net/16711/style-allow-all-style-for-stereotype-on-activity-diagram

To help to manage `style` and `theme`:
- https://forum.plantuml.net/17781/bug-in-some-themes-color-scheme
- https://github.com/bschwarz/puml-themes/issues/22

## Here is a Wanted feature
- Could you allow to style separately SDL shape by `style` _(while remaining in the philosophy of PlantUML)_?
- Could you allow to style `stereotype`? :smile:

## Here is a proposal
```puml
@startuml
'!theme cerulean
<style>
.continuous {
  FontColor red
}
.input {
  FontColor blue
}
</style>
<<continuous>>:action; 
:action text; <<continuous>>
:a}
<<input>>:other action;
:other action; <<input>>
:b<
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/NP3D2i9038JlUOfu4FMo_g67kXIXuDKNyDAVY8NjhcIpHH7VtI15qLk6cVaIiezIigJEmMGa5-e8Q-BagFHWezmTvM3guANrAQI83q0yg2o22unC3Jp1jFwQvC-gN2Brx7o0MFkbv7bMrj86lqCO9XIwoGv_KsegmRxnsWbw7-FGX5-9dnXabOLp2ABciOh4FJMe2vPcjLYjpROYAJSdZqLY9YyuxecZ8gOps9Dlz1Cl)](https://www.planttext.com/?text=NP3D2i9038JlUOfu4FMo_g67kXIXuDKNyDAVY8NjhcIpHH7VtI15qLk6cVaIiezIigJEmMGa5-e8Q-BagFHWezmTvM3guANrAQI83q0yg2o22unC3Jp1jFwQvC-gN2Brx7o0MFkbv7bMrj86lqCO9XIwoGv_KsegmRxnsWbw7-FGX5-9dnXabOLp2ABciOh4FJMe2vPcjLYjpROYAJSdZqLY9YyuxecZ8gOps9Dlz1Cl)

---

Ref. :
- #1270
- https://forum.plantuml.net/11518/issues-with-final-separator-latex-math-expression-activity?show=17284#c17284

Regards.

**Comment by The-Lum** [comment]
Here is a related issue:

## Source
```puml
@startuml
'!theme cerulean
<style>
.continuous {
  FontColor red
}
</style>

:test;
<<continuous>>:action; 
:action text; <<continuous>>
:a}
@enduml
```

## ✔️ No Error - Without any theme
>[![](https://www.planttext.com/api/plantuml/svg/LO-n2i9044Jx_Ogr4BM96j4YEK8WOEiFs5oI5GENMzZR2uhatxqY87Opp9k1gODQqJWwsApqIIDXHn8TMGycwDjH1Ld7NWSVEGRy0E8rsOOT2mhrC8FPBo0KIa5BCERNgAh2TZgmBn4MXKelBV6VIk4C3sObmLiRI2RgCR77B3_af-pIajhptMCJHSWhhYUIaCQsEwZ9z-d05m00)](https://www.planttext.com/?text=LO-n2i9044Jx_Ogr4BM96j4YEK8WOEiFs5oI5GENMzZR2uhatxqY87Opp9k1gODQqJWwsApqIIDXHn8TMGycwDjH1Ld7NWSVEGRy0E8rsOOT2mhrC8FPBo0KIa5BCERNgAh2TZgmBn4MXKelBV6VIk4C3sObmLiRI2RgCR77B3_af-pIajhptMCJHSWhhYUIaCQsEwZ9z-d05m00)

## :x: Error - With a theme _(theme `cerulean` used)_
We observed:
```diff
- No such color
```
>[![](https://www.planttext.com/api/plantuml/svg/LOwz2i9048JxVOgr4BI96j4YEK8WOEiBsEHdHE5o1tjxGP6ykrS4n6w6-MQOEcWh6aTBAtrW1FUGQD4wCa7V5XLblNVwTD77m1zYlYJRUEk51GFDP7OBI8KYQ4d6_1fLLRIzFhqhcHR5YfUM_4-bSAQxzmhXQnSW4mPEx27Bz_anEtVGzdHpt4GHEENr10bfRBEb6cv8_xy0)](https://www.planttext.com/?text=LOwz2i9048JxVOgr4BI96j4YEK8WOEiBsEHdHE5o1tjxGP6ykrS4n6w6-MQOEcWh6aTBAtrW1FUGQD4wCa7V5XLblNVwTD77m1zYlYJRUEk51GFDP7OBI8KYQ4d6_1fLLRIzFhqhcHR5YfUM_4-bSAQxzmhXQnSW4mPEx27Bz_anEtVGzdHpt4GHEENr10bfRBEb6cv8_xy0)

**Comment by arnaudroques** [comment]
The very [first example is somehow working now](https://www.plantuml.com/plantuml/uml/NOzD2i9038NtEKLSkQlxDfI2u3tw4x0mJMGc0KMykq46fUxcyRttCHcAZTbyIt0ys9Ktnfcp9nu5gDWZSG_Dh6Ahk7h19o1U8furQSRC2xoWMUNczeUcv1oCJbL2zBFqVJlEjgfq2FM5ndVhSDyA60Rww6EZyR-CTGdxYDyQj1F1mBB4JMy0). Except for "a" and "b" that we won't fix because we would like to deprecate this syntax.

Work in progress for the other diagrams :-)

**Comment by arnaudroques** [comment]
This should be fixed now!
