### ISSUE TITLE
In Object diagrams, font styles applied to map elements' headers are also applied to the element's body.

### ISSUE THREAD

**Issue by zkWildfire** [plantuml/plantuml#1425]
**Describe the bug**
When styling Object diagrams, it is possible to style the header of an object element using code such as the following:
```puml
@startuml
<style>
root {
  BackgroundColor DarkGrey
}

object {
  BackgroundColor White
  FontColor Black

  header {
    BackgroundColor Black
    FontColor White
  }
}

</style>

object user {
  name = "Dummy"
  id = 123
}

@enduml
```

This produces the expected output, where the header of the object element is black with white text and the body of the element is white with black text. However, when applying the same to a map element, font styling is not applied correctly. The background color is correctly applied to only the header, but the header's font styling gets applied to the map's body. This can be seen in the following diagram:
```puml
@startuml
<style>
root {
  BackgroundColor DarkGrey
}

object, map {
  BackgroundColor CornflowerBlue
  FontColor Black

  ' For objects, all styles here only apply to the header. For
  '   maps, the background color applies to only the header but
  '   the font styles apply to the header and body.
  header {
    BackgroundColor DarkSlateBlue
    FontColor White
    FontSize 20
  }
}

</style>

object user {
  name = "Dummy"
  id = 123
}

map foobar {
  foo => bar
}

@enduml
```

**To Reproduce**
Load the the following URL into plantuml.com's online plantuml server:
>[![](https://www.plantuml.com/plantuml/png/RL3BJiCm4BpxAqQzSAaAb6jRLMq57z03PwVPa53R6_aX553_dNLYKGwvMDxPdPdTsOUeVKpMg4s8Ww6TyimHFmeuwClrmtDozP4DUvoqlxvv6jHDAQu-wHANiBgVdJsoTutXB_87aqW6Njd5gNKmCgi4UX3GOr8AIsXZCAuGq98di3C3TD_B6ncn9O5rJNwLQICTsLwOkLVzBO3BQ9EP7GNXJaft0LGf5du66zci6C_PGOjanVMmKYZGUF5yFcUZ8vMJ_n_ztdRnZfsxRyBwIUfR3dFpMA8liIA5OkAq9MonE2LhXuK0NItby_ebqtBs3NEbfrdvOhk3bBcv9rSdQtu1)](https://www.plantuml.com/plantuml/uml/RL3BJiCm4BpxAqQzSAaAb6jRLMq57z03PwVPa53R6_aX553_dNLYKGwvMDxPdPdTsOUeVKpMg4s8Ww6TyimHFmeuwClrmtDozP4DUvoqlxvv6jHDAQu-wHANiBgVdJsoTutXB_87aqW6Njd5gNKmCgi4UX3GOr8AIsXZCAuGq98di3C3TD_B6ncn9O5rJNwLQICTsLwOkLVzBO3BQ9EP7GNXJaft0LGf5du66zci6C_PGOjanVMmKYZGUF5yFcUZ8vMJ_n_ztdRnZfsxRyBwIUfR3dFpMA8liIA5OkAq9MonE2LhXuK0NItby_ebqtBs3NEbfrdvOhk3bBcv9rSdQtu1)

This URL corresponds to the second plantuml diagram in the bug description section.

**Expected behavior**
The font styles applied to the header elements in a map should not apply to the map's body. In the example diagram that demonstrates the bug, the map's body text should not use the larger font size and should be colored black.

**Screenshots**
Output from the second plantuml diagram example: https://imgur.com/0KXHmQI  
This was generated from plantuml.com's online plantuml server on 2023-05-14.

**Additional context**
I scanned through the repository's GitHub issues using "is:issue is:open object" and "is:issue is:open map" but none of the issues appeared related based on their titles. I was also unable to find anything when googling for potential solutions. The closest link I found was this link:
https://forum.plantuml.net/14563/style-object-allow-style-on-object-diagram

The example from the thread there led me to discover that the header styling issue only applies to map elements and does not affect object elements.

I also use this link to find CSS class names to target when modifying my custom PlantUML theme:
https://github.com/plantuml/plantuml/blob/master/skin/plantuml.skin

I tried several changes to my PlantUML theme based on styles shown in the linked PlantUML theme, but none of the modifications were able to work around the issue.

**Comment by The-Lum** [comment]
Hello @zkWildfire, and all,

Yes there are some defects.
See similar request here:
- https://forum.plantuml.net/14714/can-we-apply-style-to-map?show=14809#c14809

That is now on the backlog of PlantUML Team, with a lot of other issues on `style` topics.

Regards.
