### ISSUE TITLE
Gantt: Closed days are getting ignored in following tasks

### ISSUE THREAD

**Issue by LimitlessGreen** [plantuml/plantuml#1437]
**Describe the bug**
Sometimes closed days in Gantt are getting ignored in following tasks.

**To Reproduce**
```
@startgantt
printscale weekly

Project starts the 2023-05-13

[Task 1] as [T1] starts 2023-05-15
[T1] lasts 8 weeks

[Task 2] as [T2] lasts 2 days
[T2] starts after [T1]'s end


2023-05-27 to 2023-07-04 is closed

@endgantt
```

**Screenshots**
![grafik](https://github.com/plantuml/plantuml/assets/15064073/8c652825-028f-4fc4-a70c-0e7c62a1ae48)

**Comment by The-Lum** [comment]
Hello @LimitlessGreen, and all,

It seems we must define `closed days` before we define your Gantt tasks.

- Could you put your `closed days` definition on the beginning of your file?

Regards,
Th.

**Comment by LimitlessGreen** [comment]
Yes, it works on top of the file

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @LimitlessGreen for the report.
- Thanks PlantUML team for your work.

Regards.
