### ISSUE TITLE
svglinktarget param set by FileFormatOption is overridden

### ISSUE THREAD

**Issue by hicyo** [plantuml/plantuml#144]
Hi,
It seems that the svglinktarget set with FileFormatOption class is not taken into account when generating svg files.

`new FileFormatOption(FileFormat.SVG).withSvgLinkTarget("_blank")`

I located where this custom value is overridden by another one which can be the default value "_top" or the one got from skinparam.

Class: UmlDiagram
Method: exportDiagramNow

`fileFormatOption = fileFormatOption.withSvgLinkTarget(getSkinParam().getSvgLinkTarget());
`

I expect to apply the one provided by FileFormatOption if there is no skinparam defined.

Thank you

**Comment by arnaudroques** [comment]
Many thanks for the detailled report.
This is fixed in last beta http://beta.plantuml.net/plantuml.jar and will be integrated in next official release.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @hicyo for the report.
- Thanks PlantUML team for your work.
	
Regards.
