### ISSUE TITLE
Text alignment skinparam for rnote and hnote

### ISSUE THREAD

**Issue by furato** [plantuml/plantuml#146]
I set noteTextAlignment to center and it worked for note but not for rnote nor hnote.
Is it also possible to add text alignment parameters for rnote and hnote?

(noteTextAlignment was introduced in [this thread](https://github.com/plantuml/plantuml/issues/134#issue-337856292))

**Comment by arnaudroques** [comment]
Thanks for the report.
This is fixed in last release V1.2018.12
