### ISSUE TITLE
Exception error when adding note to timing diagram

### ISSUE THREAD

**Issue by jcrummy** [plantuml/plantuml#1465]
**Describe the bug**
A `java.lang.UnsupportedOperationException` is occurring when a note is added to a timing diagram.

**To Reproduce**
This minimal example reproduces the bug:
```
@startuml
binary "A" as a
@0
a is low
note bottom of a : The note
@enduml
```

Link to this example: http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhAp4iigbHGSbHII2nMIEHoCE1ALCWiLiZ9B-VAooz9LKZABod9prN8JrD8LB1I2Cb8LG09SpcavgK0zGC0

**Expected behavior**
The diagram to be generated with the note

**Screenshots**
![image](https://github.com/plantuml/plantuml/assets/33678501/eae40717-04ed-4227-8987-12e437eae87a)

**Comment by The-Lum** [comment]
Hi @jcrummy, and all,

Thanks for your report.

As mentioned on the doc.:
>You can use the note top of and note bottom of keywords to define notes related to a single object or participant **_(available only for `concise` object)_**.
> _See: https://plantuml.com/en-dark/timing-diagram#d50d8f9219a41435_

_[Ref. [QA-6877](https://forum.plantuml.net/6877)]_

Then it is now a wanted feature. 💡 
Regards.

**Comment by jcrummy** [comment]
Ah, thank you @The-Lum , I missed that it was only available on the `concise` object. This is doing what it is supposed to do, then.

I'm ok closing this unless you want to keep this open to deal with it being a language exception and not a syntax error.

**Comment by arnaudroques** [comment]
This should work better [with last beta](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhAp4iigbHGSbHII2nMIEHoCE1ALCWiLiZ9B-VAooz9LIZ9Br38JrD8LB1IWF6v70mXYZ8oqpEu78pGT2JbbvJavy8r8OIu75BpKe2M0W00).

You can test it and tell us what you think about it!

Thanks
