### ISSUE TITLE
Qualifier labels and associations' lines not correctly drawn for qualified associations

### ISSUE THREAD

**Issue by travkin79** [plantuml/plantuml#1467]
**Problem description**
When using qualified associations the qualifier labels overlap with classes, are placed on the wrong side of an association, or the association's line between the qualifier and the target class is not visible. In addition, the length of edges cannot be modified if a direction is added to the association definition.

I have a few examples to illustrate that.

This issue is a follow up of a [previous discussion in the user forum](https://forum.plantuml.net/16397/add-qualified-associations-to-class-diagrams). That discussion contains hints to additional issues with qualified associations.

**Steps to reproduce - Example 1**

1. Create a diagram as follows

```
@startuml
    interface Map<K,V>
    class HashMap<Long,Customer>

    Map <|.. HashMap
    Shop [customerId: long] ---> "customer\n1" Customer
    HashMap [id: Long] -r-> "value" Customer
@enduml
```

2. Observe the rendered [result](https://www.plantuml.com/plantuml/uml/JOwz2i8m64NtFiMbSrDmbH8ABefr4bogmqSQRI5DIdwSV7ZJs83huPpBRPqdwyEi2W2Oj9VsIKBYGajphcuyOQ78EHp9ZIlkZ7vLX-2ycQNbHJ8YH_EfwombU1tDWbvivcdOGyNq0SOOHvdvNUzAvBdKRHlefvXqlyIkoPjKa7zoA_KGhty1). Here, the qualifier label "id: Long" overlaps with the class `Customer` and hides the association line between the classes `HashMap` and `Customer` or it doesn't exist at all. There has to be a bigger distance between the classes `HashMap` and `Customer` for the association to be drawn correctly.
Please notice that the association length between the classes `Shop` and `Customer` could successfully be drawn longer than usually by writing `--->` instead of `-->`.

![image](https://github.com/plantuml/plantuml/assets/10887297/5ed57277-6c68-40e5-bb4e-962292d29ae1)

**Expected behavior**
I expected the diagram to look something like
![image](https://github.com/plantuml/plantuml/assets/10887297/ead8bd6c-8dc8-49fd-8d84-aecb18a03d90)

**Steps to reproduce - Example 2**

1. Create a diagram as follows

```
@startuml
    class HashMap<K,V>

    HashMap [key: K] -u-> V1
    HashMap [key: K] -r-> V2
    HashMap [key: K] -d-> V3
    HashMap [key: K] -l-> V4
@enduml
```

2. Observe the rendered [result](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL80WkISnE9Y1O_4uWpVn08RRvqmEowGE4n48JexjT9AmJjMGRTKrquXp127P158qWY7P0f8qXY7P0v8qeJB8JKl1UWc0000). Here, the qualifier labels are not correctly placed in case of associations drawn in the left or up direction. In these cases the labels have to be placed near the `HashMap` class. In addition, changing the association line's length does not work with a direction hint, i.e. replacing `HashMap [key: K] -r-> V2` with `HashMap [key: K] -r----> V2` doesn't change the line's length.

![image](https://github.com/plantuml/plantuml/assets/10887297/e458572d-945e-4453-aa1d-42af4cc32d7c)

**Expected behavior**
I expected the qualified associations to be drawn the same way as the case `HashMap [key: K] -d-> V3`, but with adapted direction. The result should like something like the following. Increasing the length of the edge in source code (e.g. replacing `HashMap [key: K] -r-> V2` with `HashMap [key: K] -r----> V2`) should increase the rendered association's length.

![image](https://github.com/plantuml/plantuml/assets/10887297/eba207b1-331d-47b3-a056-c86542c08753)

**Comment by arnaudroques** [comment]
You made a good job but there were a small regression [on this diagram](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuOfspiyjoCzBpIinZ5MmiL48BaajIiqlgIn8LR2puzBGLF3C0uga9IQdWcJzIp9IYz3KEAJcfG1D0W00) (for example)

Now [my solution](https://github.com/plantuml/plantuml/commit/1b58f963692f5268eead51ce1db94d07e6fb2e9c) is not perfect because we keep running through all links when calling `isShielded()`.

However, I suggest that we first fix all qualified association issues before making any premature optimization.
I let you do some tests to see if the current code is working for you.


> Drawing arrow heads remains an issue

That's another story and you should probably open another issue for that.
Here, _maybe_ the generated **dot code** is not good.
I don't know if you are familiar with Graphviz... (but you will be if you dive in that issue :-)
We will talk about that in the new issue!

**Comment by travkin79** [comment]
Thank you. Good, you found one of the few cases where the shield size calculation was still necessary in the modified `isShielded()` method.

I'm not sure, we can avoid running through all the links (in worst case) when calling `isShielded()`, because we need to know if the current node has at least one link with a qualifier on the node's end.

I've made a few tests with a couple of diagrams. Your change fixed the component diagram examples, but didn't break my example. I think, we can close this ticket now. We'll open another issue for the arrow heads problem. Thank you for the very quick replies and merges.
I'm not familiar with Graphviz, yet, but I'm beginning to dig deeper. :-)

**Comment by The-Lum** [comment]
_[Just for the record]_
There are some new overlapping defects about "qualified association":
- https://forum.plantuml.net/19066/issues-related-to-qualified-association

Regards,
Th.
