### ISSUE TITLE
Using an external style file by pointing to a URL or by using a relative file path doesn't work

### ISSUE THREAD

**Issue by travkin79** [plantuml/plantuml#1470]
**Problem description**
I've started using the new CSS-like style format specified in an [external file](https://plantuml.com/en/style-evolution#fababa30f2c7f6f0). It works great with locally placed css files that are referenced by absolute paths. But it does not work with relative paths and more important: it does not work with files given by a URL.

I think, an external style file provided on a web server or given by some URL could be shared by many users or teams. That's exactly the goal in our company. @arnaudroques, I'm not sure if this is a bug or a feature request. I would appreciate it, if you would add support for (or fix) URLs (and relative file paths) in external style file references.

**How to Reproduce**

0. Create a plantuml-style.css with any style definition that works for you
1. Create a PlantUML diagram like the following

```
@startuml
    ' reference to a local style file
    <style file=/Users/SomeUserName/path/to/plantuml-style.css>

    ' the remainder is the actual diagram definition
@enduml
```
2. Render it with PlantUML
3. The result will be a diagram using your style, no error message

4. Create a PlantUML diagram like the following

```
@startuml
    ' reference to shared style file on a web server
    <style file=https://hostname/some-path/v1/plantuml-style.css>

    ' the remainder is the actual diagram definition
@enduml
```
5. place a plantuml-style.css on the given URL, e.g. using a (e.g. local) web server and ensure, the file is accessible, e.g. open the URL in a web browser
6. Render the diagram with PlantUML
7. The result will be an empty diagram with an error message, saying the style file cannot be read, something like

`@startuml<style file=https://hostname/some-path/v1/plantuml-style.css>Cannot read: https://hostname/some-path/v1/plantuml-style.css`

**Expected behavior**
The style file should be correctly read and used in both cases (and also in case of a relative file path like `<style file=../path/to/plantuml-style.css>).`

**Desktop:**
- OS: MacOS Ventura 13.4
- JRE: OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
- PlantUML: 1.2023.9
- GraphViz: dot - graphviz version 8.0.5 (20230430.1635)

**Comment by travkin79** [comment]
Hi @arnaudroques,

I've created a pull request for this one: #1472. Could you please review and merge it?
(Relative paths still do not work. It seems to be more complicated to find the current file's path.)

Thanks a lot. Best regards.
Dietrich

**Comment by arnaudroques** [comment]
> I've created a pull request for this one: #1472. Could you please review and merge it?
>

Thanks for your contribution. However, it would be better to use `SURL` class instead of `URL`.
The initial _S_ stands for **secure**: it checks if the corresponding URL is authorized or not.

Could you modify your pull request? Thanks!

**Comment by travkin79** [comment]
Good point. I've adapted my pull request, @arnaudroques. Thanks for the hint.
Bye
Dietrich
