### ISSUE TITLE
Class diagrams: show statement cannot be parsed

### ISSUE THREAD

**Issue by travkin79** [plantuml/plantuml#1475]
**Problem description**
Some class diagrams with `hide` and `show` keywords are not correctly parsed. A diagram that could be rendered successfully with PlantUML 1.2022.7, cannot be rendered anymore with PlantUML 1.2023.9. The `show` statement seems to produce rendering issues.

**Steps to reproduce**
1. Create a diagram with the following content and [try rendering it](https://www.plantuml.com/plantuml/uml/POx1IWCn48Rl-nG_YBH5t0VOKrqzAeZ51yYQqGII6SZCjWVHPpSDgrqmXp3y_pSVirTpnUQSkWr2z0IN4fnPYTDif73iaSc2UEtxlWFGi9hbYOgse7sRMgFkG8ESO85-rn0PRycfOcnWwyUblGWMvWwV7PPt2tQP1XoiHFxuYsyG_O0ag-WANWvoLbPmknjmbEXR-xLoZoltTvdv34uYYHp_O-zNyyFbo7SHeu8NOa-5F4xH0fwJOtjzUiIHYaPXN2_3TjVjApddz0C0)

```
@startuml
    ' hide all attributes and methods...
    hide members
    
    '... but show the methods in class B
    show B methods
    
    class A {
        - name: String
        + id: long
        # doSomething(): void
    }
    class B {
        ~run(): boolean
    }
    class C
    class D
    
    footer Rendered with PlantUML version %version()
@enduml
```

2. You'll see a syntax error in line 8, although the syntax is correct according to the PlantUML [documentation](https://plantuml.com/en/class-diagram#6a8ec84e53ede3ae).

3. Try rendering the same diagram after deleting the line `show B methods` and the diagram will be rendered correctly.

**Expected behavior**
The diagram is rendered as follows, but with the current style. Here is the diagram rendered with an earlier PlantUML version (I think, it was 1.2022.7).
![image](https://github.com/plantuml/plantuml/assets/10887297/02ae9fb6-2252-4c91-8904-4c328f3dfcb5)

**Execution environment**

- OS: macOS Ventura 13.4
- JRE: OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
- GraphViz: dot - graphviz version 8.0.5 (20230430.1635)

**Comment by The-Lum** [comment]
Hi @travkin79, and all,

Another workaround is to put all the directives at the end of the diagram, as:
```puml
@startuml
    class A {
        - name: String
        + id: long
        # doSomething(): void
    }
    class B {
        ~run(): boolean
    }
    class C
    class D
    
    ' hide all attributes and methods...
    hide members
    
    '... but show the methods in class B
    show B methods
    footer Rendered with PlantUML version %version()
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/PP31IWGn38Rl-nG_YBYBE0ymftNTeuAu-00T6ssXJQ3Dx1v4dzrESAHW3YN9__r9wBwgAphdj46Bj-HgnJq-hLhY3kmoZJXfYVpnrxv5z2EITAqhU3b99WqDtEv6d2LwKx-wsOTkzdUPUG4daKIE_x4FNNwqt9uRXEW9BYKuRMTDirA5OuzbkVWw38E1XcNA4vNQsPkCva4DSe46Mcs8l1vfeEc7LRNMkuXImGknfq8UbwW1pycnlZuzujpsH65S_oRRtMRVoFQvFm00)](https://www.planttext.com/?text=PP31IWGn38Rl-nG_YBYBE0ymftNTeuAu-00T6ssXJQ3Dx1v4dzrESAHW3YN9__r9wBwgAphdj46Bj-HgnJq-hLhY3kmoZJXfYVpnrxv5z2EITAqhU3b99WqDtEv6d2LwKx-wsOTkzdUPUG4daKIE_x4FNNwqt9uRXEW9BYKuRMTDirA5OuzbkVWw38E1XcNA4vNQsPkCva4DSe46Mcs8l1vfeEc7LRNMkuXImGknfq8UbwW1pycnlZuzujpsH65S_oRRtMRVoFQvFm00)

Regards,
Th.

**Comment by travkin79** [comment]
Thank you, @The-Lum.
