### ISSUE TITLE
Syntax error on two and more array items in macros

### ISSUE THREAD

**Issue by MOZGIII** [plantuml/plantuml#1477]
**Describe the bug**

Works:

```
!$myarray=["a"]
```

Broken:

```
!$myarray=["a","b"]
```

**To Reproduce**

Create a file with the contents above, and render it.

**Expected behavior**

No error, array is defined and available for use (i.e. looping over).

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser: -
- Version: versions from 2022 till 2023 (including latest release)

**Smartphone (please complete the following information):**

No

**Additional context**

**Comment by The-Lum** [comment]
Hello @MOZGIII, and all,

According your constat:
>Works:
>```puml
>!$myarray=["a"]
>```
>Broken:
>```puml
>!$myarray=["a","b"]
>```
@MOZGIII:
1. How to the first works?
2. Could you give an example?

Because currently only 3 kinds of type are available on PlantUML:
>There are three types of data:
>- `Integer` number(int);
>- `String`(str) - these must be surrounded by single quote or double quote;
>- `JSON`(JSON) - these must be surrounded by curly brackets.

See also doc. here:
- https://plantuml.com/en/preprocessing#788fa5fb2276ed17

---

Then here is a workaround, in order to manage `array items`, using `JSON` type, as:
```puml
@startuml
!$myarray={"key": ["a","b"]}
legend
test of JSON array:
myarray.key[0] = $myarray.key[0]
myarray.key[1] = $myarray.key[1]
endlegend
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL9KoQrCB2fAhBIjLifEhLIoKeXMIbJIKKfIYgtboabDJyrBuIf9BIvHo4zJy0hszrC0AxRYWkhI0-g9DeXLi5LGGHL1KM28eS0mbWjeCjHy1o01T0i0)](https://www.planttext.com/?text=SoWkIImgAStDuL9KoQrCB2fAhBIjLifEhLIoKeXMIbJIKKfIYgtboabDJyrBuIf9BIvHo4zJy0hszrC0AxRYWkhI0-g9DeXLi5LGGHL1KM28eS0mbWjeCjHy1o01T0i0)

_Enjoy,_
Regards,
Th.

**Comment by MOZGIII** [comment]
I see! The workaround is unexpected, because all these are valid JSON values: `"qwe"`, `123`, `[]`, `{}`, meaning only JSON *objects* (the `{ ... }` kinds of values) are supported. This could be documented better.

I have no idea how come that `["a"]` works if the JSON arrays are not supported. I just thought they were supported but the support was bugged.

Anyhow, thanks for the workaround. It is ugly to write, but if I can put it inside of a macro call (i.e. do something like `array([ .. ])` to produce the `{ "dummy": [...] }` under the hood that would be good enough). It would be better to support JSON arrays though.
