### ISSUE TITLE
Frame/border support

### ISSUE THREAD

**Issue by FredeEB** [plantuml/plantuml#148]
This is in relation to #118, as i don't know if it's used much in UML in general. But when building a system that includes both hardware and software, and many diagrams I find it useful to make a frame like figure 1 in [this article](http://agilemodeling.com/style/frame.htm). 

It's just an indicator to what kind of diagram it is, what the name of the diagram is, and what usecase it applies to.

**Comment by FredeEB** [comment]
I was unaware of the `frame` option. What's the reason that this doesn't work with sequencediagrams?

**Comment by arnaudroques** [comment]
This is not documented yet, but you can have
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSfDpCnBAqhCJLK8oSWiLW2YH0Kmdyin9pCvLTVEAJz9mKh18pKd9v_B8JKl1QW90000

```
@startuml
mainframe This is a frame
Alice->Bob : Hello
@enduml
```
Is this what you are looking for ?

**Comment by FredeEB** [comment]
That's exactly it! What version added this?

**Comment by arnaudroques** [comment]
It came with version 1.2019.1
But it's not documented yet and still under test.
Tell us if you find issues!

**Comment by FredeEB** [comment]
Great!
