### ISSUE TITLE
Activity *BETA* error start/stop/end with multiline action and subsequent whitespaces

### ISSUE THREAD

**Issue by theKBro** [plantuml/plantuml#1499]
If within a  `start/stop/end` block the last action is a multiline action and has subsequent whitespacecharacters an error is thrown.

Error:
```
@startuml
start
:Hello world;
:This is defined on
several **lines**;  
stop
@enduml
``` 

> PlantUML 1.2023.11beta2
[From string (line 4) ]
@startuml
start
:Hello world;
:This is defined on
Syntax Error?

**Comment by The-Lum** [comment]
Hello @theKBro, and all,

With:
> subsequent whitespacecharacters

You are right: if we suppress the 2 whitespaces after the semi-colon `;`, as:
```diff
@startuml
start
:Hello world;
:This is defined on
-several **lines**;  
+several **lines**;
stop
@enduml
```
We see the expected result.

And @PlantUML team: just FYI, if you put whitespace before semi-colon there no error:
```puml
@startuml
start
:Hello world;
:This is defined on
several **lines**
          ;
stop
@enduml
```


The issue is only before the semi-colon.

Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @theKBro  for the report.
- Thanks PlantUML team for your work.

Regards.
