### ISSUE TITLE
Procedures don't support JSON parameters

### ISSUE THREAD

**Issue by Numatic-Hector** [plantuml/plantuml#1508]
**Describe the bug**
JSON variables passed into procedures do not behave as objects, instead they behave as strings.

**To Reproduce**
Try this diagram:

```plantuml
@startuml

!unquoted procedure myProcedure($steps)
  !foreach $step in $steps
    :$step;
  !endfor
!endprocedure

!$mySteps = {
    "steps": 
    [
        "Stage 1",
        "Stage 2",
        "Stage 3"
    ]
}

myProcedure($mySteps.steps)

@enduml
```

**Expected behavior**
In the above example, each step should be rendered as an activity. $steps should behave as objects.

**Comment by The-Lum** [comment]
Hi @Numatic-Hector,

Just suppress the `unquoted` keyword to see the expected result.

>[![](https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuL8iACfFJaqfBKfLoAqCWB4rL8fBKWkADRaK51JJyejI4vCp5C122fbv44Onbm8GM87PrY1bgNafG9LS81fk91UNeafkPJ18kOAjGZLOYn9OjvAL0fWN3IR1ui4bYUcf2ePAEkX2HfX2nafWaLYkMYukP6V3RDE3Ejy1w1gWBm40)](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8iACfFJaqfBKfLoAqCWB4rL8fBKWkADRaK51JJyejI4vCp5C122fbv44Onbm8GM87PrY1bgNafG9LS81fk91UNeafkPJ18kOAjGZLOYn9OjvAL0fWN3IR1ui4bYUcf2ePAEkX2HfX2nafWaLYkMYukP6V3RDE3Ejy1w1gWBm40)

_Enjoy_
Regards,
Th.

**Comment by Numatic-Hector** [comment]
Thanks @The-Lum!
