### ISSUE TITLE
Russian docs page renders css file with political images

### ISSUE THREAD

**Issue by vypivshiy** [plantuml/plantuml#1513]
**Describe the bug**
When you go to the https://plantuml.com/ru page, pictures with political appeals are displayed

**To Reproduce**

1. Go to https://plantuml.com/ru page

**Expected behavior**
Just documentation!

**Screenshots**
Docs page:
![image](https://github.com/plantuml/plantuml/assets/59173419/a97b6f26-dc93-4e07-ade7-8aedb0650a72)

Css element:
![image](https://github.com/plantuml/plantuml/assets/59173419/b29f5cdf-bd46-4bf3-8551-9913d1114017)

Rendered pdf and images links:
![image](https://github.com/plantuml/plantuml/assets/59173419/57843fd9-8394-4433-ba50-cc4106031446)

**Desktop:**

- OS: linux, windows
- Browser: tested on chromium, firefox, brave, vivaldi (also in `view-source` mode) 
- Version -

**Smartphone:**
...

**Additional context**
...

**Comment by andrros3030** [comment]
Still having political issues with plant uml web site — using /ru page incorrect country flag icon selected :(
