### ISSUE TITLE
`namespace`/`package` consolidation broke existing `remove`/`restore` behaviour when using namespace separators

### ISSUE THREAD

**Issue by stephengurnett** [plantuml/plantuml#1515]
**Describe the bug**

`remove` and `restore` with separators don't match the package/namespace, breaking existing diagrams. 

**To Reproduce**

Removing namespace at Foo.Bar (works prior to 1.2023.2)

```
namespace Foo {
    namespace Bar {
        class Quz
    }

    class Quz
}

namespace Bar {}

remove Foo.Bar
```

**Expected behavior**

```
namespace Foo {
    class Quz
}

namespace Bar {}
```

**Actual behavior**

(nothing removed)

```
namespace Foo {
    namespace Bar {
        class Quz
    }

    class Quz
}

namespace Bar {}
```

**To Reproduce**

Removing package at Bar (works prior to 1.2023.2):

```
namespace Foo {
    namespace Bar {
        class Quz
    }

    class Quz
}

namespace Bar {}

removeBar
```

**Expected behavior**

(removes Bar and not Foo.Bar)

```
namespace Foo {
    namespace Bar {
        class Quz
    }

    class Quz
}
```

**Actual behavior**

(removed Bar and Foo.Bar)

```
namespace Foo {
    class Quz
}
```

**Screenshots**

Starting diagram:

<img width="282" alt="image" src="https://github.com/plantuml/plantuml/assets/78220264/6b3ced7f-f04e-4f0e-a90a-4344e164d448">

---

2023.1 - remove Foo.Bar

<img width="163" alt="image" src="https://github.com/plantuml/plantuml/assets/78220264/9feef88c-207a-44eb-9eab-0dbc0829703a">

---

2023.1 - remove Bar

<img width="222" alt="image" src="https://github.com/plantuml/plantuml/assets/78220264/e4a8b656-6e07-4883-9baa-8d45c8164f56">

---

2023.10 - remove Foo.Bar

<img width="285" alt="image" src="https://github.com/plantuml/plantuml/assets/78220264/f9455328-d5be-447e-b51e-389cd2dda819">

---

2023.10 - remove Bar

<img width="103" alt="image" src="https://github.com/plantuml/plantuml/assets/78220264/01b8d3b6-3621-4e49-82ad-034797479a54">

---

**Comment by arnaudroques** [comment]
This should be fixed with [last snapshot](https://github.com/plantuml/plantuml/issues/1515).
Tell us if it's not working for you.

**Comment by stephengurnett** [comment]
@arnaudroques  Looks good - thanks!
