### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by jawira** [plantuml/plantuml#1516]
**What is the URL of the documentation?**

- https://plantuml.com/download

**What can be improved?**

- The download link from sourceforge **[plantuml-nodot.1.2023.10.jar](http://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2023.10.jar/download)** doesn't work: 

![image](https://github.com/plantuml/plantuml/assets/496541/d92cdbc6-5d26-4169-a7b9-1dfd7f0459e9)

**Additional context**

It seems source forge files are not maintained anymore, as you can see the latest version to download is v1.2023.7, but in GitHub the latest version is v1.2023.10

This is a screenshot from <https://sourceforge.net/projects/plantuml/files/>:

![image](https://github.com/plantuml/plantuml/assets/496541/ba25e94b-aacb-4097-b0be-400703871c70)

**Comment by arnaudroques** [comment]
Would it be ok for you to use [plantuml-lgpl-1.2023.10.jar](https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-lgpl-1.2023.10.jar) instead which also does not contain embedded GraphViz ?

If that's fine for you, we will change the download link.

Thanks!

**Comment by jawira** [comment]
Yes, lgpl is ok for me :)
| Just out of curiosity, SourceForge releases are not going to be updated anymore ?

**Comment by arnaudroques** [comment]
> | Just out of curiosity, SourceForge releases are not going to be updated anymore ?

No, we are now only on Github.
Sorry about that!
