### ISSUE TITLE
plantuml-epl.jar does not render Dot diagrams

### ISSUE THREAD

**Issue by JuergenHaug** [plantuml/plantuml#1517]
**Describe the bug**
Rendering a dot diagram under Windows using the `plantuml-1.2023.10.jar` works fine. But using a different license, e.g. `plantuml-epl-1.2023.10.jar`  outputs following error in the generated diagram
```
There is an issue with your Dot/Graphviz installation
```

I dont' have Graphviz (dot.exe) on my disk. Seems like the [included Graphviz](https://plantuml.com/de/graphviz-dot) is missing ?

Running `plantuml-1.2023.10.jar -testdot`
```
Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK
```

Running `plantuml-epl-1.2023.10.jar -testdot`
```
Error: No dot executable found
Error: only sequence diagrams will be generated
```

**To Reproduce**

1. Download [plantuml-1.2023.10.jar](https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar) and [plantuml-epl-1.2023.10.jar](https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-epl-1.2023.10.jar)
2. run `-testdot`

**Expected behavior**
PlantUML jar epl renders dot diagrams like gpl variant

Environment
- No Graphviz installed
- Windows 11
- 1.2023.10

**Comment by arnaudroques** [comment]
We have just added embedded GraphViz in [the last EPL snapshot version](https://github.com/plantuml/plantuml/releases/tag/snapshot).
Could you tell us if it's working for you?
Thanks!

**Comment by JuergenHaug** [comment]
Hi, there seems not change, running `plantuml-epl-SNAPSHOT.jar -testdot` results in the same error
```
Error: No dot executable found
Error: only sequence diagrams will be generated
```

**Comment by childenProtos** [comment]
I get the same result. The graphviz.dat file is still not present in the generated epl .jar file.

**Comment by childenProtos** [comment]
The sjpp ant task generates new files to the generated build directory. Unfortunately it does not copy any thing but java files. Therefore the graphviz.dat file is not included when the jar is build
