### ISSUE TITLE
no @startuml/@enduml found (for @startregx or @startebnf) on (local installation)

### ISSUE THREAD

**Issue by Gressling** [plantuml/plantuml#1519]
---
## ERROR
---
When call local jar (via jebbs plantuml in visual code) the example:

~~~
@startregex
concatenation = (( S )( factor )( S ) ,?)+;
@endregex
~~~

throws error:  
~~~ 
no @startuml/@enduml found 
~~~ 

* Also error with  startebnf. 
* No error with startuml (normal).

---
## CONFIGURATION
---
* Reproduced with 
** latest jar plantuml-1.2023.10 
** and older plantuml-1.2021.13.
* win11
* visual code 1.8.1.1
* java version "1.8.0_381", Java(TM) SE Runtime Environment (build 1.8.0_381-b09)

**Comment by The-Lum** [comment]
Hi @Gressling, and all,

First: It is not an issue on the core PlantUML (this repo. [plantuml](https://github.com/plantuml/plantuml)), but on the use/configuration of the VSCode Extension PlantUML ([vscode-plantuml](https://github.com/qjebbs/vscode-plantuml)).

Then here some questions or hints:
- How you "call local jar (via jebbs plantuml in visual code)"?
- What is your VSCode Extension PlantUML version?
- Could you confirm your PlantUML version, on your VSCode ext., with testing:
```puml
@startuml
version
@enduml
```
- If you use `Local` conf. (on `Plantuml: Render` setting) that use an old PlantUML version embedded on the ext. (which don't manage `regex` or `ebnf`).
- To use new version, without updating `plantuml.jar` within the ext., could you perhaps populate this parameter, on the VSCode Ext. Setting on `@ext:jebbs.plantuml`:
```
Plantuml: Jar
Alternate plantuml.jar location. Leave it blank to use integrated jar.
```
with the path of your local `plantuml.jar`.

Then you can see the expected result:
![image](https://github.com/plantuml/plantuml/assets/86879521/763550f3-bd35-4b8f-8423-be1065f690de)



See also directly on the [vscode-plantuml](https://github.com/qjebbs/vscode-plantuml) repo.:
- [qjebbs/vscode-plantuml/issues](https://github.com/qjebbs/vscode-plantuml/issues)

_If that can help,_
_Enjoy,_
Regards,
Th.

**Comment by Gressling** [comment]
Fixed. I replaced the  `plantuml.jar` in `C:\Users\Admin\.vscode\extensions\jebbs.plantuml-2.17.5` with the latest version. 

So transfer this issue to @qjebbs/vscode-plantuml. Thank you!
