### ISSUE TITLE
"tagged file" releases for .war

### ISSUE THREAD

**Issue by perrinjerome** [plantuml/plantuml#153]
It would be nice if on sourceforge the .war was released for each version as a "tagged file" like it's done for .jar
 
The .war file is only distributed in https://sourceforge.net/projects/plantuml/files/plantuml.war/download and this URL changes at each release and is not available in download folder for each release (exemple: https://sourceforge.net/projects/plantuml/files/1.2018.13/ ).

It would be nice to also have this .war for each release.

Thanks in advance !

**Comment by arnaudroques** [comment]
Good idea!
We've just did it for https://sourceforge.net/projects/plantuml/files/1.2018.13 and future releases will follow the same rule.

**Comment by perrinjerome** [comment]
Thank you very much !
