### ISSUE TITLE
[Style] Allow style for `backward` element on Activity diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1531]
Hi PlantUML team,

## Context
To continue _(`style` on (beta-)Activity diagram)_:
- https://forum.plantuml.net/16711/style-allow-all-style-for-stereotype-on-activity-diagram
- #1422
- #1423

Ref. or other similar issue:
- https://forum.plantuml.net/16912/backward-in-repeat-loop-not-possible-to-set-color

## Wanted feature
- Could you allow style for `backward` element on Activity diagram?

## Source
```puml
@startuml
<style>
.save {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>
repeat
  :Generate diagrams; <<save>>
backward:Log context; <<save>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>>
backward:Log
context; <<save>>
repeat while (more data?) is (yes)
@enduml
```

## Output: The `backward` element is not styled _(tested on `1.2023.11beta2`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/dP71Ri8m44Jl_eezmeMMIbnebD8YjHV4fVs19Luv5evThJU4KFNVkr5ImPdZlXdDZELD5cHfcs2AB7sWqYmodWX-3C3EHzgca1WEeIK5RrWT7QSssX47xshPzXWdyrVjgsEadE59oIjpwgxeSR5I-9wYxB4XLJq6sEDWclWOocId-zDV29RB_skOfwfh0xBvDSN3D9Zfcr3KjVwWI8n2O3qwnYO_Gr4CpobBSz3j7R9TxvA3IlFeB3Vo609TxRLarYJM41HycOFFCEifpyqTHUQkeWr5E_p87m00)](https://www.planttext.com/?text=dP71Ri8m44Jl_eezmeMMIbnebD8YjHV4fVs19Luv5evThJU4KFNVkr5ImPdZlXdDZELD5cHfcs2AB7sWqYmodWX-3C3EHzgca1WEeIK5RrWT7QSssX47xshPzXWdyrVjgsEadE59oIjpwgxeSR5I-9wYxB4XLJq6sEDWclWOocId-zDV29RB_skOfwfh0xBvDSN3D9Zfcr3KjVwWI8n2O3qwnYO_Gr4CpobBSz3j7R9TxvA3IlFeB3Vo609TxRLarYJM41HycOFFCEifpyqTHUQkeWr5E_p87m00)

Regards,
Th.

**Comment by arnaudroques** [comment]
Thanks for the report and for your tests!
[This should be fixed in last snapshot](https://www.plantuml.com/plantuml/uml/dO-zJWCn48HxFyMMIHC84aqu7O58q4Hfu0Ksvz6T5V-WjSrn8DuTdsAKFkL-CvgPtSR4ahApgebficZLAl8dw4SHxOt7BjWWTBGP1JnpT-ebPA_Fs9f-IBk9VJM_3wOxUSH8TuKyYOJnWcvNzmM-19yEx51KmvOEF9igFuSATBtVp3TelVw_vdb5xRDbKR-gkQc31H_WL5oRLtW89v0st0kx-41DCx_JjkfOjeyiUhCFFNKb3r_f8jSG6WTZGGiN1AGvyUEIJAJ5XBXKLnIfgugsy3ex-mS0).

**Comment by LolaBeckett** [comment]
Nice to get this fix, thank you.
Then I am wondering what is the "backward" skinparam to get one SDL Output shape red and one other green for example.
I did not get "activityshape" to work

`@startuml
<style>
.output {
  BackgroundColor red
}

.sdloutputgreen {
  activityshape outputstype
  BackgroundColor lightgreen
}

</style>
repeat
  :Generate diagrams; <<save>>
backward:It is red; <<output>>
repeat while (more data?) is (yes)
repeat
  :Generate diagrams; <<save>>
backward:I want it green and with SDL Output shape; <<sdloutputgreen>>
repeat while (more data?) is (yes)
@enduml`

![image](https://github.com/plantuml/plantuml/assets/145998150/594c9b7f-c0c7-4269-acdf-9fd7dc7457f6)

**Comment by The-Lum** [comment]
Hi @LolaBeckett,

For that see issues _(and wanted features)_ here:
- #1527
- #1538

_Awaiting enhancement of those topics,_
Regards,
Th.

**Comment by gwendalrobic** [comment]
Hi,
Thanks a lot for the functionality to apply the style to a backward element. However, after downloading version 1.2023.12, I cannot style a backward element in a while loop. 

```
@startuml
<style>
.USR {
  BackgroundColor #PowderBlue
}

.SSTEM {
  BackgroundColor #LightGray
}

</style>
while (data available?)
  :read data; <<USR>>
  :generate diagrams;<<SSTEM>>
backward:Collect errors; <<USR>>
endwhile
end
@enduml
```

I tried this plantuml code on the diagram generator and it ended up like this : 

![RO_1IiSm3CRlUOg05xtC-rRcc8WN1N7w0DaQkcAsGjevXlZkjaFuN_wN4F9zoIzV5nDfsXO14zCXt4BrERpZ3o3sD7qv3Tjg7uC4nPkti5lMNZQ6Nu1g63wUNgyxNxoRqxFIKOpc_l_oFdjXlBMK2EcRlD0e_707YBKoMIn2WyRa1zgsJ1slh9GOhIUdjCJ6c9EQvJ4pTr9RPwJmb91](https://github.com/plantuml/plantuml/assets/148795554/628259ac-3ca2-4ef6-b160-04b6c5aeb286)

In that case, I was expecting the backward element to be colored in PowderBlue.

Should I open a new issue/feature or is it related to that feature ?
Thanks for your consideration.

**Comment by The-Lum** [comment]
Hi @gwendalrobic, and all,

Thanks for your report.
I just opened a new issue for that: #1632.

Regards,
Th.

**Comment by The-Lum** [comment]
Hello @arnaudroques, and PlantUML team,

_It seems there are some regression..._ 🤕 
Observed on:
- https://forum.plantuml.net/19089/backward-activity-style-overrides-diamond-style

## Source or minimal example
```puml
@startuml
<style>
.save {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>
repeat
  :Generate diagrams; <<save>>
backward:Log context; <<save>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>>
backward:Log
context; <<save>>
repeat while (more data?) is (yes)
@enduml
```

## Output: `diamond` are styled as `save` _(tested on `1.2024.6`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/dP71Ri8m44Jl_eezmeMMIbnebD8YjHV4fVs19Luv5evThJU4KFNVkr5ImPdZlXdDZELD5cHfcs2AB7sWqYmodWX-3C3EHzgca1WEeIK5RrWT7QSssX47xshPzXWdyrVjgsEadE59oIjpwgxeSR5I-9wYxB4XLJq6sEDWclWOocId-zDV29RB_skOfwfh0xBvDSN3D9Zfcr3KjVwWI8n2O3qwnYO_Gr4CpobBSz3j7R9TxvA3IlFeB3Vo609TxRLarYJM41HycOFFCEifpyqTHUQkeWr5E_p87m00)](https://www.planttext.com/?text=dP71Ri8m44Jl_eezmeMMIbnebD8YjHV4fVs19Luv5evThJU4KFNVkr5ImPdZlXdDZELD5cHfcs2AB7sWqYmodWX-3C3EHzgca1WEeIK5RrWT7QSssX47xshPzXWdyrVjgsEadE59oIjpwgxeSR5I-9wYxB4XLJq6sEDWclWOocId-zDV29RB_skOfwfh0xBvDSN3D9Zfcr3KjVwWI8n2O3qwnYO_Gr4CpobBSz3j7R9TxvA3IlFeB3Vo609TxRLarYJM41HycOFFCEifpyqTHUQkeWr5E_p87m00)

- Why the `diamond` are colored as the `save` shape? ❓ 

Regards,
Th.

**Comment by The-Lum** [comment]
Hi,

_[Just for the record]_
Regressions fixed by:
- f617c140

Thanks a lot,
Regards,
Th.
