### ISSUE TITLE
Swimlanes split bug

### ISSUE THREAD

**Issue by ko22009** [plantuml/plantuml#1533]
Is it normal?
https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuQf9hE42SxXgackuh4fIYqkikOeBSZ9Bm59MXjPSLaRMNDcPEJaGOON4zCJCFAwQ5A2aCLGYDIz50QB70SW46Wi0

**Comment by The-Lum** [comment]
Hi all,

_[Just for the record..]_
Here is the result with `V1.2024.6`:
```puml
@startuml
|a|
start
|c|
:test;
split
|a|
:1;
:2;
kill
split again
|d|
:3;
kill
end split
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuQf9hE42SxXgackuh4fIYqkikOeBSZ9Bm59MXjPSLaRMNDcPEJaGOON4zCJCFAwQ5A2aCLGYDIz50Q8dBJ-_9BL88IOlp53FoC38HCzCGLz1jQmujIWpFqz3ayi1g1HeBG00)](https://www.planttext.com/?text=SoWkIImgAStDuQf9hE42SxXgackuh4fIYqkikOeBSZ9Bm59MXjPSLaRMNDcPEJaGOON4zCJCFAwQ5A2aCLGYDIz50Q8dBJ-_9BL88IOlp53FoC38HCzCGLz1jQmujIWpFqz3ayi1g1HeBG00) 

The issue seems to be on the `split`...
_See red arrow..._
>[![](https://www.planttext.com/api/plantuml/svg/BS-z2W8n40JWVfzYGKGj_3l5uawEGrjh6xM8PWt1c4Yo7Xp6TpV4AwOPFWQc2Imylvy6Hk6XBKgwlXLi0tU6QX0trgtcRYSy8dxWe2tjdN4UFKdumdRUmoWYv2M8jmWbK-0AfgT1OfTfNK5u6SsOMMgL9xAvBvSfHGKFRKoFX1BQGfHPEY-ieZzTzOoin4pXxXoJnxCzBcV5ebZFDZZ7OKi-Q6V74sWIJTT-)](https://www.planttext.com/?text=BS-z2W8n40JWVfzYGKGj_3l5uawEGrjh6xM8PWt1c4Yo7Xp6TpV4AwOPFWQc2Imylvy6Hk6XBKgwlXLi0tU6QX0trgtcRYSy8dxWe2tjdN4UFKdumdRUmoWYv2M8jmWbK-0AfgT1OfTfNK5u6SsOMMgL9xAvBvSfHGKFRKoFX1BQGfHPEY-ieZzTzOoin4pXxXoJnxCzBcV5ebZFDZZ7OKi-Q6V74sWIJTT-) 

Regards,
Th.

**Comment by The-Lum** [comment]
Hello @ko22009 

_[Just for the record]_
See similar issue here:
- #587
- https://forum.plantuml.net/5686/activity-diagram-split-and-lanes-not-working-together
- https://forum.plantuml.net/13662/activity-diagram-split-and-swimlane-minor-layout-bug

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @ko22009 

Here is a possible workaround, ussing `fork`:
```puml
@startuml
|a|
start
|c|
:test;
fork
|a|
:1;
:2;
kill
|d|
fork again
:3;
kill
|c|
end fork
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuQf9hE42SxXgackuh4fIYqkikTBoYxB1CbQ6rbnMHjPSsPavGAKfDM0PXSJqnCmyBYjZc3XGOsfUYW9OLrf-VabgaK9CNfYXdf61aOcUcOA-WcfPQb5nPdwUXYQN0r0bq5u0)](https://www.planttext.com/?text=SoWkIImgAStDuQf9hE42SxXgackuh4fIYqkikTBoYxB1CbQ6rbnMHjPSsPavGAKfDM0PXSJqnCmyBYjZc3XGOsfUYW9OLrf-VabgaK9CNfYXdf61aOcUcOA-WcfPQb5nPdwUXYQN0r0bq5u0)

The only downside is the last black line of the fork at the bottom... :-1:

Regards,
Th.
