### ISSUE TITLE
[Style] Allow style for multi-line elements on Activity diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1534]
Hi PlantUML team,

## Context
Observed on:
- https://forum.plantuml.net/18195/activity-diagram-styles-how-to-apply-to-different-shapes?show=18202#c18202

To continue _(`style` on (beta-)Activity diagram)_:
- https://forum.plantuml.net/16711/style-allow-all-style-for-stereotype-on-activity-diagram
- #1422
- #1423

Ref. or other similar issue:
- #1527

## Wanted feature

- Could you allow style for multi-line elements on Activity diagram?

## Example source
```puml
@startuml
<style>
.test  {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
}
.save {
  FontColor navy
  BackGroundColor Cyan
}
</style>

<<test>>:multiple\nlines\nusing\nbackslash-n;
/'
<<test>>:multiple
lines
using
new lines;
'/
:multiple\nlines\nusing\nbackslash-n; <<test>>
:multiple
lines
using
new lines; <<test>>

:multiple\nlines\nusing\nbackslash-n; <<save>>
:multiple
lines
using
new lines; <<save>>
@enduml
```

## Output: The multi-line elements are not styled! _(tested on `1.2023.11beta2`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/ZP6nQiCm48RtUmfjcMgNGfR6cBI1PYcPEdfHuiCMEP-AJaem9UzUML5neKCzwhzF7_z9M_7Q-J0GLE97mXeAZ-AL-WAbtWtZpf9rwaW1O_2gJ-VEsS3jFIRJzNutQixmHszEPqOHzHIJ5-ViTOuUYtKCtopxWnumJeqcTT0JbFExr64BDoX4Np2rc2UiBsDkiV_L8XMuGLNc3Q2gfXtg-da8vCqdOSCKsqd3GGnt3H-ZGKXB_y0RA5T_Bq3Y8U70U5Nfl85L2OkawiS8_obdSh5vUfbbvankaTlunTy0)](https://www.planttext.com/?text=ZP6nQiCm48RtUmfjcMgNGfR6cBI1PYcPEdfHuiCMEP-AJaem9UzUML5neKCzwhzF7_z9M_7Q-J0GLE97mXeAZ-AL-WAbtWtZpf9rwaW1O_2gJ-VEsS3jFIRJzNutQixmHszEPqOHzHIJ5-ViTOuUYtKCtopxWnumJeqcTT0JbFExr64BDoX4Np2rc2UiBsDkiV_L8XMuGLNc3Q2gfXtg-da8vCqdOSCKsqd3GGnt3H-ZGKXB_y0RA5T_Bq3Y8U70U5Nfl85L2OkawiS8_obdSh5vUfbbvankaTlunTy0)

Regards,
Th.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed with last snapshot.
