### ISSUE TITLE
Sequence diagram: Multi-level nested boxes overlaying each other

### ISSUE THREAD

**Issue by gear4s** [plantuml/plantuml#1535]
**Describe the bug**
Multi-level nested boxes are overlaying each other in sequence diagrams

**To Reproduce**
Example below:
```puml
@startuml
  !pragma teoz true
  
  box "Micro frontend"
      box "Components"
          box "Component 1"
              entity Part1 as C1P1
              entity Part2 as C1P2
          end box
  
          box "Component 2"
              entity Part1 as C2P1
              entity Part2 as C2P2
          end box
      end box
  end box
@enduml
```

**Expected behavior**
Multi-level boxes should not overlay each other

**Screenshots**
This is the example above:
![image](https://github.com/plantuml/plantuml/assets/832900/b3394745-5964-4134-b790-f419f17433c0)

**Desktop (please complete the following information):**

- OS: macOS 13.4.1 (22F82)
- Version 1.2023.7

**Comment by loufranco** [comment]
I have confirmed that this is true in a few online editors. To be fair, the documentation only shows single level nesting. I don't know if the intention is that it is N-level nesting.

**Comment by gear4s** [comment]
@loufranco Teoz engine documentation states that multi-level nesting is possible but apparently it doesn't do the correct padding (meaning I need to do \n a few times): https://plantuml.com/teoz

**Comment by arnaudroques** [comment]
Thanks, definitively a bug.
This is [fixed in last snapshot](https://www.plantuml.com/plantuml/uml/XP1H2i8m38RVTuhVtQ0vmM3FmgvGNPM1RKQQWNfw8vIXiDBIX_Jx0XzqoEf5j_ZeWDCg_XuzDF0RAbimPlV2J_JdvIgCct3IaERUC53Ko77b59BcWWyKN77xCRZe2vFL7Np6w2PNNw6oGjsldhyL8_KiDRFKpb8b-_VQfy46-yyF).
