### ISSUE TITLE
[Style] Allow `multiple style stereotypes` for `backward` element on Activity diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1538]
Hi PlantUML team,

## Context
To continue _(`style` on (beta-)Activity diagram)_:
- https://forum.plantuml.net/16711/style-allow-all-style-for-stereotype-on-activity-diagram
- #353
- #1422
- #1423
- #1531

Ref. or other similar issue:
- https://forum.plantuml.net/16912/backward-in-repeat-loop-not-possible-to-set-color
- https://forum.plantuml.net/14327/combine-stereotypes-with-backward-keyword-activity-diagrams

Related issue/wanted feature:
- #1527

## Wanted feature
- Could you also allow `multiple style stereotypes` for `backward` element on Activity diagram?

## Source
```puml
@startuml
<style>
.color {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>

split
:Only <<save>>;
repeat
  :Generate diagrams; <<save>>
backward:Log context; <<save>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>>
backward:Log
context; <<save>>
repeat while (more data?) is (yes)

split again
:<<save>> + <<color>>; <<color>>
repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log context; <<save>> <<color>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log
context; <<save>> <<color>>
repeat while (more data?) is (yes)

end split
@enduml
```

## Output _(tested on `1.2023.11beta3`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/hLB1JiCm3BtdAtpSX3GO4fUkAeD9S9d60Nx0QwqqMffCJaefY7_7MpisQMA2YLly_FoUxNWQ8dAiAwlI45jBcHhbtdg63mKmDuvcssXfQnBW7lELPb-xeeEjqMMSjUXwyajfyfMZ4E1Qa3jct-oXgz6DW0_UnGLM95c35XQu8VLu9yfKzF6pUISOZtVHfZ_9wjeYgq-LNlOTgx2s9ghaoTaMqZJWAsNPH36j2QCK9u_aY34I50OrOnKctpIrb94Qv2APUmsvsD1RF4Xt8j2KHhm7bMSHmOYtGp011Ys5eJh3I9rdj9qJKADnAjbLmeM8RFzCXju_VzVL0V_q8ew4_s4bFvWVB-UFvkGAw4vYAa-vxIy0)](https://www.planttext.com/?text=hLB1JiCm3BtdAtpSX3GO4fUkAeD9S9d60Nx0QwqqMffCJaefY7_7MpisQMA2YLly_FoUxNWQ8dAiAwlI45jBcHhbtdg63mKmDuvcssXfQnBW7lELPb-xeeEjqMMSjUXwyajfyfMZ4E1Qa3jct-oXgz6DW0_UnGLM95c35XQu8VLu9yfKzF6pUISOZtVHfZ_9wjeYgq-LNlOTgx2s9ghaoTaMqZJWAsNPH36j2QCK9u_aY34I50OrOnKctpIrb94Qv2APUmsvsD1RF4Xt8j2KHhm7bMSHmOYtGp011Ys5eJh3I9rdj9qJKADnAjbLmeM8RFzCXju_VzVL0V_q8ew4_s4bFvWVB-UFvkGAw4vYAa-vxIy0)

_Thanks for your works_
Regards,
Th.

**Comment by The-Lum** [comment]
Hello @arnaudroques, and all,

As declared corrected on `V1.2023.13` on the [Change Log](https://plantuml.com/changes);
It seems that `SDL` stereotype (`<<save>>`) is not taken in account?

- Could you have a look?
- Is it necessary to open a new issue?

Regards,
Th.

**Comment by arnaudroques** [comment]
> It seems that `SDL` stereotype (`<<save>>`) is not taken in account?

Sorry about that!
We can still use this open ticket/issue. Could you post a short example that shows only this bug?
Thanks!

**Comment by The-Lum** [comment]
>Could you post a short example that shows only this bug?

Here is a minimal example:
```puml
@startuml
<style>
.color {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>


title <<save>> SDL + <<color>>
repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log context; <<save>> <<color>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log
context; <<save>> <<color>>
repeat while (more data?) is (yes)

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/fP8nJyCm48Lt_ufRa58XXIR04g9GA88bAaCPkroI8xNgsEXyQIY8_uxR1dLXw_Y-UtxlJlBC2xBqdL6vbvsXGiMrCuxXMm6KsjBye2hJKm2FM6zQThrjZjZeTYtp7ThH_BRMzSQIzv06yi3iXXEQnhS1FZih2-meJ3KQME3UDF9ZA5CpwgN-8aYIFxNVBqpRtY2h7vLVZHih9Lh2ACyzRgaeOFbKmcMGXqkAGZ5z44g8oLx84gCGD1fRnixVdLwT_5KuSq1kijArK8Tg-fH_ZSTW6DOwr4UTun2CWlSJq1wY7Vc9EgjSdLd-xfmGmyg-LZu6PxCaJgVfTPpSL2IOhkoyPoOhsSMMs6jdeucQaMt2V_W5)](https://www.planttext.com/?text=fP8nJyCm48Lt_ufRa58XXIR04g9GA88bAaCPkroI8xNgsEXyQIY8_uxR1dLXw_Y-UtxlJlBC2xBqdL6vbvsXGiMrCuxXMm6KsjBye2hJKm2FM6zQThrjZjZeTYtp7ThH_BRMzSQIzv06yi3iXXEQnhS1FZih2-meJ3KQME3UDF9ZA5CpwgN-8aYIFxNVBqpRtY2h7vLVZHih9Lh2ACyzRgaeOFbKmcMGXqkAGZ5z44g8oLx84gCGD1fRnixVdLwT_5KuSq1kijArK8Tg-fH_ZSTW6DOwr4UTun2CWlSJq1wY7Vc9EgjSdLd-xfmGmyg-LZu6PxCaJgVfTPpSL2IOhkoyPoOhsSMMs6jdeucQaMt2V_W5)

Mixed with a part _(Activity Diag.)_ of:
-  #1527

Regards,
Th.

**Comment by arnaudroques** [comment]
Thanks for the examples!
Last snapshot should fix the backward issue about stereotype.
Tell us if you find others! :-)

**Comment by arnaudroques** [comment]
This should be fixed now. Please reopen the issue if needed!
