### ISSUE TITLE
(gantt chart) Add "open day" feature

### ISSUE THREAD

**Issue by fairjm** [plantuml/plantuml#154]
Now we have `Close day` feature and it's very convenient to close weekend and date range.  
But in reality, there are many exceptions like we close the weekend but there is a holiday shift.  
like   
```
saturday are closed
sunday are closed
2018/12/29 is opened  
```  
Now, I remove the `saturday are closed`, and mark saturdays except `2018/12/29` to close.  
It works but feel more verbose.

**Comment by arnaudroques** [comment]
Thanks for the suggestion, this is a good idea!
So with last beta http://beta.plantuml.net/plantuml.jar you can now have:

```
@startgantt
Project starts the 5th of december 2018
saturday are closed
sunday are closed
2018/12/29 is opened
[Prototype design] lasts 3 weeks
[Test prototype] starts at [Prototype design]'s end and lasts 2 weeks
@endgantt
```

Is this what you were looking for ?

**Comment by fairjm** [comment]
It's amazing! And the jar works fine.  
Thx ^_^
