### ISSUE TITLE
Building plantuml in 2023

### ISSUE THREAD

**Issue by blinxen** [plantuml/plantuml#1542]
### Discussed in https://github.com/plantuml/plantuml/discussions/1540

<div type='discussions-op-text'>

<sup>Originally posted by **blinxen** September 18, 2023</sup>
Am I correct to assume that `gradle` is the only supported build tool for plantuml?

The reason I am asking this is because I recently took over the maintenance of plantuml in Fedora. The packaged version for fedora is `1.2023.7`. Currently the sources for plantuml are taken from https://sourceforge.net/projects/plantuml/. The latest version there (`1.2023.7`) is not in sync with GitHub. Also, the sources on sourceforge always included a `build.xml` in the `tar` archive. Is that gone now?</div>

Creating this issue  because I think creating documentation on how to build plantuml would be a good idea.

**Comment by arnaudroques** [comment]
Yes, right now `gradle` is the only supported build tool for plantuml. Is this an issue for you?

And plantuml is now fully hosted on github, so you really should switch from sourceforge.

And yes, creating documentation on how to build plantuml is a good idea, we are going to work on this :-)

Thanks!

**Comment by arnaudroques** [comment]
A first draft here https://github.com/plantuml/plantuml/blob/master/BUILDING.md
Hope this helps!

**Comment by blinxen** [comment]
> Yes, right now gradle is the only supported build tool for plantuml. Is this an issue for you?

Unfortunately yes :( `gradle` is not packaged for Fedora (long story) and therefore cannot be used to build Fedora packages. Previously `ant` was used to build `plantuml` in Fedora. Is it possible to bring that back? `maven` would be fine too.

**Comment by HusseinKabbout** [comment]
>  I Hope this is fine for you.

That would be perfect!

> However, ant will probably only build the GPL version

The initial packager of `plantuml` packaged the `LGPL` version anyway.


Thanks for the fast responses :D!

**Comment by blinxen** [comment]
> I Hope this is fine for you.

That would be perfect!

> However, ant will probably only build the GPL version

The initial packager of plantuml packaged the LGPL version anyway.

Thanks for the fast responses :D!

**Comment by arnaudroques** [comment]
The build.xml file is back. Please test it now :-D

**Comment by blinxen** [comment]
Thanks!! My local build works again :D. The documentation looks good too.
