### ISSUE TITLE
Mention of the Graphviz.dat file

### ISSUE THREAD

**Issue by rahulmohang** [plantuml/plantuml#1551]
Hi, 

It would be good if there is a mention of the file, 'https://github.com/plantuml/plantuml/blob/v1.2023.11/src/net/sourceforge/plantuml/windowsdot/graphviz.dat' in the README. It would be helpful for users concerned about license compliance and security to know the version of Graphviz used for the compressed version. 

Can you please let me know the version of Graphviz used in plantuml-epl-1.2023.11?

**Comment by arnaudroques** [comment]
This version of GraphViz is build [by this project](https://github.com/plantuml/graphviz-distributions).
We are going to update the doc about it.

**Comment by rahulmohang** [comment]
Thank you. 

So, for version 1.2023.11 of plantuml, is the version of graphviz used the current master version (or 6.0.1) from the project?

**Comment by arnaudroques** [comment]
Actually, no. For version 1.2023.11, we are still using graphviz_lite_2.44.1
(we should really document this)

There is no automatic CI/CD with https://github.com/plantuml/graphviz-distributions.
So even if [graphviz-distributions](https://github.com/plantuml/graphviz-distributions) have been changed, we did not report the change on 1.2023.11.

It's not hard to do: we have to compress it using Brotli to create a new graphviz.dat file. The real challenge is testing...

Is it an issue for you?

**Comment by rahulmohang** [comment]
Thank you. 

It is not an issue. However, it would be good from the perspective of compliance and security to document it. I wanted to know the version to do a license compliance check, as one of our projects are using the plantuml 1.2023.11 and I found the graphviz.dat file in the source distribution.

**Comment by alfonsodelavega** [comment]
Relevant pointer [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10595) ;)

Thanks for the information! I did not know that a specific graphviz distribution was packaged for plantuml.

**Comment by rahulmohang** [comment]
Thank you. It is very clear. Only thing that I felt missing is the version information. However, it may be different for different versions of plantuml, right?
