### ISSUE TITLE
ASL distribution no longer includes graphiz.dat

### ISSUE THREAD

**Issue by ahus1** [plantuml/plantuml#1556]
**Describe the bug**
PlantUML used to include a `graphiz.dat` file. See 1deedf8a6566dfab7e9176ce8ae135acd51b772c for the explanation. 

While 1.2023.7 ASL version as downloaded from SourceForge https://sourceforge.net/projects/plantuml/files/1.2023.7/ the file, the version 1.2023.10 ASL downloaded from GitHub releases and Maven Central doesn't. Same for the lastest 1.2023.12 snapshot release

**To Reproduce**
* Unzip the ASL file
* Search for graphviz.dat
* Also run on Windows:

```
@startuml
testdot
@enduml
```

![test](https://github.com/plantuml/plantuml/assets/3957921/da11a831-8a93-4e72-bbea-fdd87684c7a0)

**Expected behavior**
* graphviz.dat is present

![test](https://github.com/plantuml/plantuml/assets/3957921/ef8da15b-36d2-4468-aedd-34251cade93d)

**Comment by arnaudroques** [comment]
This should be fixed [in release 1.2023.12](https://github.com/plantuml/plantuml/releases)
Please reopen this issue if it is not working for you!
Thanks !
