### ISSUE TITLE
skinparam ResponseMessageBelowArrow interacts badly with participant lifetimes

### ISSUE THREAD

**Issue by bradleyjkemp** [plantuml/plantuml#156]
Minimal example code:
```
@startuml

skinparam ResponseMessageBelowArrow <false|true>

A -> B : Request
activate B
A <- B : Response
deactivate B
@enduml
```
With ResponseMessageBelowArrow set to false, the diagram renders properly:
![image](https://user-images.githubusercontent.com/9093713/49739971-13582e80-fc8b-11e8-90bb-42dd3e985473.png)

However with it set true, the participant lifetime no longer matches up with the response arrow:
![image](https://user-images.githubusercontent.com/9093713/49740056-48648100-fc8b-11e8-9de1-818e3320db22.png)

It appears that the logic is to move the arrow above the message text rather than the expected behaviour of keeping the arrow in the same place and moving the text below the arrow.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you !

**Comment by bradleyjkemp** [comment]
Thanks! Yes, can confirm this fixes the issue.
