### ISSUE TITLE
Creole strikeout for complete message text is not rendered

### ISSUE THREAD

**Issue by JuergenHaug** [plantuml/plantuml#1574]
**Describe the bug**
`Alice -> Bob : --stricken-out--` is rendered correctly, where  `Alice -> Bob : --strickenout--` is not

**To Reproduce**
https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBCoKnELT2rKt3AJrAmKj3LBIufoapEJitJpIyjqTN5BK-Cj499QaK9bqDgNWhGAW00
```plantuml
@startuml
Alice -> Bob : --stricken-out--
Alice -> Bob : --strickenout--
Alice -> Bob : --strickenout-- text
@enduml
```
![](https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuNBCoKnELT2rKt3AJrAmKj3LBIufoapEJitJpIyjqTN5BK-Cj499QaK9bqDgNWhGAW00)

**Comment by swmatisa** [comment]
Hello,
As workaround you can a space with <U+0020>
https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBCoKnELT2rKt3AJrAmKj3LBIufoapEJitJpIyjqTN5BG-MLh09rJOmC3Am8wIk9BMYXCiXDIy5Q2S0

Le jeu. 12 oct. 2023 à 15:51, Juergen Haug ***@***.***> a
écrit :

**Comment by JuergenHaug** [comment]
Thx, that works

**Comment by The-Lum** [comment]
Hi all,

Just for the record, it is due to `--title--` is for horizontal line title, see:
```puml
@startuml
title Horizontal line title test
Alice -> Bob : --notstrickenout--
Alice -> Bob : --not stricken out--
Alice -> Bob : --not stricken out--\n""                        ""
Alice -> Bob : ==horizontal line title==
Alice -> Bob : ==horizontal line title==\n""                        ""
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/ZP312i9044Fl_Ogmz_a1OQNrv4TugUr01zSPs4qlVhs2U96ApJ4yaf2-SQnSxwMZiIZEKUqHph6Wc2lUBhMn6ufD2ZdY55SS8EB1nchJJJrMYcmI-23OpLmy9VnGIjy9EIzRctFU3VxfwzNdrq5F)](https://www.planttext.com/?text=ZP312i9044Fl_Ogmz_a1OQNrv4TugUr01zSPs4qlVhs2U96ApJ4yaf2-SQnSxwMZiIZEKUqHph6Wc2lUBhMn6ufD2ZdY55SS8EB1nchJJJrMYcmI-23OpLmy9VnGIjy9EIzRctFU3VxfwzNdrq5F)

Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @JuergenHaug for the report.
- Thanks @swmatisa for your answer.
- Thanks PlantUML team for your work.

Regards.
