### ISSUE TITLE
using -nbthread auto hides found 0 files message if you don't use -v it dies silently with an exit status of 0

### ISSUE THREAD

**Issue by janitha09** [plantuml/plantuml#159]
`$ java -Djava.awt.headless=true -jar /usr/local/bin/plantuml.jar -v -nbthread auto ./inventorysales.pu -o ./generated_png`

```
(0.000 - 256 Mo) 250 Mo - PlantUML Version 1.2018.13
(0.004 - 256 Mo) 250 Mo - GraphicsEnvironment.isHeadless() true
(0.004 - 256 Mo) 250 Mo - Forcing -Djava.awt.headless=true
(0.004 - 256 Mo) 250 Mo - java.awt.headless set as true
(0.004 - 256 Mo) 250 Mo - Forcing resource load on OpenJdk
(1.015 - 256 Mo) 248 Mo - Using several threads: 8
```

`$ java -Djava.awt.headless=true -jar /usr/local/bin/plantuml.jar -v ./inventorysales.pu -o ./generated_png`

```
(0.000 - 256 Mo) 250 Mo - PlantUML Version 1.2018.13
(0.004 - 256 Mo) 250 Mo - GraphicsEnvironment.isHeadless() true
(0.004 - 256 Mo) 250 Mo - Forcing -Djava.awt.headless=true
(0.004 - 256 Mo) 250 Mo - java.awt.headless set as true
(0.004 - 256 Mo) 250 Mo - Forcing resource load on OpenJdk
(1.008 - 256 Mo) 248 Mo - Found 0 files
```

**Comment by arnaudroques** [comment]
Thanks for the report.
We are currently cleaning our code : we use to manage "error" and "no data" as the same thing.
Now, we are beginning to separate the two cases.
So in last beta http://beta.plantuml.net/plantuml.jar we now have 3 possibles return codes:

- `0` ok
- `1` error in some file
- `2` no input file or no diagram found

And we have fixed the `-nbthread` option.
This has not been widely tested, so do not hesitate to post any issue here!
Thanks for your tests!

**Comment by janitha09** [comment]
`$java -Djava.awt.headless=true -jar ./plantuml.jar -stdrpt -nbthread auto ./sequence_diagrams/BD/* -o ./generated_png`
```
Warning: no image in ./sequence_diagrams/BD/provisioning_UCC.rtf
protocolVersion=1
status=NO_DATA
Warning: no image in ./sequence_diagrams/BD/inventorysales.puml
protocolVersion=1
status=NO_DATA
```
```
$ echo $?
0
```
I ran this on a directory with multiple files. I think the error code should be the highest error level - meaning the biggest problem as d which you guys need to define. Per the scheme you have above I think error level 2 is a bigger problem than error level 1. 

http://man7.org/linux/man-pages/man3/errno.3.html this however states that these are thread local so returning 0 is valid but not very user friendly. 

I also think error level 2 should be split into two. I do not know which one is more severe. Maybe EINVAL is more suitable for no diagram found?(http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) This lost also implies that exit code 1 EPERM isn't the best choice.

**Comment by janitha09** [comment]
`$java -Djava.awt.headless=true -jar ~/Downloads/plantuml.jar -version`
```
PlantUML version 1.2018.14beta10 (Unknown compile time)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 11.0.1+13
Operating System: Mac OS X
OS Version: 10.14.1
Default Encoding: UTF-8
Language: en
Country: US
Machine: xxxx
PLANTUML_LIMIT_SIZE: 4096
Processors: 8
Max Memory: 4,294,967,296
Total Memory: 268,435,456
Free Memory: 262,183,800
Used Memory: 6,251,656
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/local/bin/dot
Dot version: dot - graphviz version 2.40.1 (20161225.0304)
Installation seems OK. File generation OK
```

**Comment by arnaudroques** [comment]
Ok, so now error code 100 means "no data" and 200 means "error".
You can try it on last beta http://beta.plantuml.net/plantuml.jar
We've done some refactoring, so tell us if you find some regression.

We are open to add new return code, but we're not sure to understand your suggestion.

**Comment by janitha09** [comment]
closing this issue. No longer working at the company that this was a problem at
