### ISSUE TITLE
[Style] Allow `LineThickness` style for `awesome Actor` on Component/UC/Deployment diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1596]
Hi PlantUML team,

## Context
Observed on:
- https://forum.plantuml.net/1831/border-thickness?show=18375#c18375

## Wanted feature
- Could you allow `LineThickness` style for `awesome Actor` on Component/UC/Deployment diagram?

## Input source
```puml
@startuml
title Allow LineThickness on awesome Actor
label a [{{
<style>
actor {
  BackGroundColor aliceblue
  LineColor blue
  LineThickness 4
  FontColor blue
  FontSize 15
  FontStyle italic
}
</style>

actor a
component b
a-->b: hello
}}]

label b [{{
skinparam actorStyle awesome
<style>
actor {
  BackGroundColor aliceblue
  LineColor red
  LineThickness 4
  FontColor blue
  FontSize 15
  FontStyle italic
}
</style>

actor a
component b
a-->b: hello
}}]
footer %version()
@enduml
```

## Output
The normal Actor is styled, but the `awesome Actor` is not styled with `LineThickness `! _(tested on `1.2023.12`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/nP4nImH138Nx_8eqWXQ72Dh8SPmdQ6EddLXaTYCtR3OvPh8Ukkn_T-PkHMrjBFEzoSjxp3ex9Hzw0OykZ3SYjiU7gFoqZKsdd3EQ8kqvMr_anYs1K611mkTnX6NsT-4LK5Lm1CGDDTrzia7RMvF2I6B3GGOkMZK-qX_W-z9b8NUc_kj91O_nW_7Ywckg9p5wTOO9bkTpXZa4GMFzpfJLCG0j5gjmZLikpM2QNc2E7mxnSnTrHubwFEmUdUUsV-wMkFsVQgzcpWbFtZZbQ7fw1clMjlpk9m00)](https://www.planttext.com/?text=nP4nImH138Nx_8eqWXQ72Dh8SPmdQ6EddLXaTYCtR3OvPh8Ukkn_T-PkHMrjBFEzoSjxp3ex9Hzw0OykZ3SYjiU7gFoqZKsdd3EQ8kqvMr_anYs1K611mkTnX6NsT-4LK5Lm1CGDDTrzia7RMvF2I6B3GGOkMZK-qX_W-z9b8NUc_kj91O_nW_7Ywckg9p5wTOO9bkTpXZa4GMFzpfJLCG0j5gjmZLikpM2QNc2E7mxnSnTrHubwFEmUdUUsV-wMkFsVQgzcpWbFtZZbQ7fw1clMjlpk9m00)

Regards,
Th.

**Comment by arnaudroques** [comment]
This is now fixed in last snapshot.
