### ISSUE TITLE
Run console only

### ISSUE THREAD

**Issue by shd101wyy** [plantuml/plantuml#16]
Hi,

Is there a way to disable the GUI? 
Every time when I run **plantuml** from the command line, the starting image will pop up. 
![screen shot 2016-07-11 at 11 42 49 am](https://cloud.githubusercontent.com/assets/1908863/16719419/a366ca18-475c-11e6-8b0c-3bd674ab0103.png)
Is there a way to disable it?

Thanks for your fantastic work ;)

**Comment by thetric** [comment]
Does adding `-Djava.awt.headless=true` to the commandline help?

**Comment by shd101wyy** [comment]
@thetric THANKS A LOT! 
It works now ;)
