### ISSUE TITLE
Artificat in activity diagram

### ISSUE THREAD

**Issue by lours1** [plantuml/plantuml#160]
Hello,
When i use stop in activity diagram with multiple conditions, there is a ghost arrow at the end of the schema
```
@startuml
start
if(t0) then (true)
    if (t2) then (true)
        stop
    else (false)
        if (t3) then (true)
            stop
        else (false)
            stop
        endif
    endif
else (false)
    stop
endif
@enduml

```

![image](https://user-images.githubusercontent.com/1735083/50082502-739e2180-01f1-11e9-903e-4a3e2ebccd09.png)

![image](https://user-images.githubusercontent.com/1735083/50082683-d2fc3180-01f1-11e9-9266-6720b5db6a04.png)

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @lours1 for the report.
- Thanks PlantUML team for your work.
	
Regards.
