### ISSUE TITLE
can plantuml-mit checkSyntax for graphviz style text?

### ISSUE THREAD

**Issue by zkhzkhz** [plantuml/plantuml#1600]
### Discussed in https://github.com/plantuml/plantuml/discussions/1598

<div type='discussions-op-text'>

<sup>Originally posted by **zkhzkhz** November  9, 2023</sup>
package: plantuml-mit:1.2023.9
I can validdate plantuml style code using: 
SyntaxResult checkResult = SyntaxChecker.checkSyntax(xx);

is there a way to check syntax for graphviz style text?</div>

**Comment by arnaudroques** [comment]
Sorry, it is not possible to check graphviz syntax.
