### ISSUE TITLE
Wrong note shape in sequence diagram when arrow has only one participant

### ISSUE THREAD

**Issue by timotheeandres** [plantuml/plantuml#1609]
**Describe the bug**
When using `hnote` or `rnote`, if the arrow it comes after only has one participant (i.e. `-> A` or `B ->`), the note is rendered as a standard `note`.
This happens both in the PlantUML plugin for IntelliJ and the [online server](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuTArKt3aAihBBqbLACfCpoZX2Y_ApqjN00iKPoGMf2fe56bofUQbW8KWoZFmAiz0Kixbg03KuOHYWND-KL5gSWakAs1QCZ2ruBR62QW7QabEQXe1J-1LZMcu0v0532a0).

**To Reproduce**
Compile the following graph:
```plantuml
@startuml
-> A
rnote right
Wrong note shape (r)
end note
-> A
hnote right
Wrong note shape (h)
end note

A -> B
rnote right
Correct note shape (r)
end note
A -> B
hnote right
Correct note shape (h)
end note

B ->
rnote left
Wrong note shape (r)
end note
B ->
rnote left
Wrong note shape (h)
end note
@enduml
```

**Expected behavior**
All `rnote`s should be rectangular, all `hnote`s should be hexagonal.

**Screenshots**
![image](https://github.com/plantuml/plantuml/assets/25198539/bfcfcc5d-bf91-48ee-945a-a06ff19f7ca1)

**Comment by arnaudroques** [comment]
Many thanks for the feedback. This should be fixed with last snapshot.
Tell us if it's not working for you!
