### ISSUE TITLE
Bug with activity diagram arrows fork using notation  "->", configuring its color based on activityBorderColor value and not on activityArrowColor's

### ISSUE THREAD

**Issue by PedroAlfNeto** [plantuml/plantuml#1622]
issue here is... these arrows are not regular arrows for skinparam... dunno why. so they follow the color of skinparam activityBorderColor and not skinparam activityArrowColor, which is annoying if you want to make borders invisible (e.g. white)\
(FYI, I'm new to plantuml)
Issue showcased with case:
```uml
@startuml
skinparam activityArrowColor #000000
skinparam activityBorderColor #e03c31
:foo1;
-> normal arrow with text;
fork
  ->
fork again
  ->  fork arrow with text;
end fork
->
:foo5;
@enduml
````

**Comment by The-Lum** [comment]
Hello @PedroAlfNeto, and all,

Thanks for your report.
Yes there are also even **2 issues**:
1. :x: Missing last label 
2. :x: Not good Arrow Color _(all arrows should be green)_

Here is an example with new `style` functionality, as:
```puml
@startuml
<style>
activityDiagram {
  arrow  {
    LineColor green
    FontColor blue
    LineThickness 2
}
</style>
:foo1;
-> normal arrow with text;
fork
  :fork1;
fork again
  -> txt label;
  :fork2;
  -> txt label;
fork again
  -> fork arrow with text\nmissing arrow label;
end fork
:foo5;
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/PL0xJyD03DxlLtX1We6K9699ggfI4HCI2sCMfxZfgHTRyZbz2F7VkIO12PXiV_uUbjVHK6teWrj6kmHQEToQFtgxF7di57luS02eAYSOMu0NpxIH80gT4l68FGlRXBLXe1_Qszvl3qmnGk4-tN8nHrGxaRnszojWqHx3x7_ojWUZizLk9tf8BjMrvjC8sA6_fYMPdGq2jXJgRr9H_zly5KtpxwI6Un-ZvsvUp5BYzv4-NlfOk-GbHWeDlxOng_AiU2ZAB2zRCYmRtWogrSsHD7hXspktJlhqqYy0)](https://www.planttext.com/?text=PL0xJyD03DxlLtX1We6K9699ggfI4HCI2sCMfxZfgHTRyZbz2F7VkIO12PXiV_uUbjVHK6teWrj6kmHQEToQFtgxF7di57luS02eAYSOMu0NpxIH80gT4l68FGlRXBLXe1_Qszvl3qmnGk4-tN8nHrGxaRnszojWqHx3x7_ojWUZizLk9tf8BjMrvjC8sA6_fYMPdGq2jXJgRr9H_zly5KtpxwI6Un-ZvsvUp5BYzv4-NlfOk-GbHWeDlxOng_AiU2ZAB2zRCYmRtWogrSsHD7hXspktJlhqqYy0)

For _Missing label_, see also:
- [QA-15605](https://forum.plantuml.net/15605/activity-missing-arrow-label-on-end-merge)
- And similar resolved issue: [QA-18157](https://forum.plantuml.net/18157/last-label-on-last-elseif-branch-does-not-get-rendered)

For _Color issue_ see also:
- [QA-15302](https://forum.plantuml.net/15302/why-hidden-link-is-not-honoured-in-this-diagram?show=15303#c15303)
- [QA-16403](https://forum.plantuml.net/16403/activity-diagram-colors-for-fork)

Regards,
Th.

**Comment by arnaudroques** [comment]
Last example should be working with version V1.2023.13.
Please reopen the issue if needed!
Thanks
