### ISSUE TITLE
[Wanted feature][Style] Allow full local style on Activity diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1623]
## Context
Observed on [QA-18457](https://forum.plantuml.net/18457/color-individual-conditional-in-activity-diagram?show=18458#a18458).

## Wanted feature
- Could you allow full local style on Activity diagram?

## Example source
```puml
@startuml
<style>
activityDiagram {
  diamond {
    LineColor blue
    BackgroundColor lightCyan
    LineThickness 2
    ArrowThickness 0.5
    FontName Arial Narrow
    FontColor red
    FontSize 11
    FontStyle regular
  }
}
</style>
if (decision) then (yes)
    :C1;
else (no)
endif
<style>
activityDiagram {
  diamond {
    LineColor red
    BackgroundColor pink
    LineThickness 1
    ArrowThickness 1
    FontName Courier
    FontColor blue
    FontSize 10
    FontStyle italic
  }
}
</style>
if (decision) then (yes)
    :C2;
else (no)
endif
@enduml
```

## Output (tested on `1.2023.13beta3`) :x:
>[![](https://www.planttext.com/api/plantuml/svg/dPAnJiCm48PtFyKjICaIwbGieKA582PK1XYxN9DhUgfZexDJ553VdJI5L8GkiDdVVtVoVVBS1vJGr4RDV6WDtIWi0kyujFUCbM0D7mgWPAoTBVipm2DRofrn0YlJK8_kiDXMuXfR7WF3rIRaBTgXuMN3nTQIzv3sx5R4lPtW9BdgyOEpOO4rTJcZWGKUoeRaE5oe7CWplnDeVReVbkWggiQWT7Ilzcfs-RKQho4ggM3FpiOGDcGXQid7VNUMwsj5nXD4riMARCdhVqdvVjxOoIlRxHaT-fmE_LD6xXfXaf67mVv9n6GaWWCQBlxe8VtjGQsT2oImj4yhdsGwIIVfDD7J5GMSBctUY6GNEvB3n2XMywwh-rEV)](https://www.planttext.com/?text=dPAnJiCm48PtFyKjICaIwbGieKA582PK1XYxN9DhUgfZexDJ553VdJI5L8GkiDdVVtVoVVBS1vJGr4RDV6WDtIWi0kyujFUCbM0D7mgWPAoTBVipm2DRofrn0YlJK8_kiDXMuXfR7WF3rIRaBTgXuMN3nTQIzv3sx5R4lPtW9BdgyOEpOO4rTJcZWGKUoeRaE5oe7CWplnDeVReVbkWggiQWT7Ilzcfs-RKQho4ggM3FpiOGDcGXQid7VNUMwsj5nXD4riMARCdhVqdvVjxOoIlRxHaT-fmE_LD6xXfXaf67mVv9n6GaWWCQBlxe8VtjGQsT2oImj4yhdsGwIIVfDD7J5GMSBctUY6GNEvB3n2XMywwh-rEV)

Here is the result:
- ✔️ It seems only OK for `BackgroundColor`,
- :x: but KO for all the other style parameters.

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @arnaudroques, and all,

I just changed with the correct end bracket (`}`). _[Sorry for the first mistake.]_
_The wanted feature remains..._ 😄 

Regards,
Th.

**Comment by arnaudroques** [comment]
> _The wanted feature remains..._ 😄

Well, I am confused here :-)
In the diamond, the FontColor is ok, the LineColor is ok, the BackgroundColor is ok.
Could you be more specific about what is not correct? Thanks!!

**Comment by The-Lum** [comment]
Hi @arnaudroques, and all,

Here are some more explanations:
```puml
@startuml

' Local style for the diamonds of the first if;
<style>
activityDiagram {
  diamond {
    LineColor blue
    BackgroundColor lightCyan
    LineThickness 2
    ArrowThickness 0.5
    FontName Arial Narrow
    FontColor red
    FontSize 11
    FontStyle regular
  }
}
</style>
:On the diamonds of the first if;
floating note
According the above (local) style:
* The line color is not good
it should be <color:blue>blue
* The FontColor is not good
it should be <color:red>red
* The LineThickness is not good
* The FontStyle is not good
* ...
* <b>Only the BackgroundColor is good!
end note
if (decision) then (yes)
    :C1;
else (no)
endif


' Local style for the diamonds of the second if;
<style>
activityDiagram {
  diamond {
    LineColor red
    BackgroundColor pink
    LineThickness 1
    ArrowThickness 1
    FontName Courier
    FontColor blue
    FontSize 10
    FontStyle italic
  }
}
</style>
:On the diamonds of the second if;
floating note
<b>All is good here... (like if the param will be global)
The BackgroundColor, the LineColor, the FontColor
end note
if (decision) then (yes)
    :C2;
else (no)
endif
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/dLGzRzim4DtvAwv3KRieLCj15iKmughe5CH3FMQXf9DqC4q69EL0BVBVUwHgENODnEWYY7VtJdmVqBtpqlfkfuJu10-cb0gSxnL2RIpu5g4YkJEwSc3gUAx9EWzKtub575mAMNhQa--_asoitC5l0GTKV0Tu88svKRonK1t6qZTPRXjhEbqD3KLDw_DUwX6mQQdSQdGEvh6sijQy78kpv3QMVnZj7-KEkKzy-KSPniREiDnYDLP-qY-4D3sU8rkBJQUavUghU1MBht-fPMlzZWYrCjAJRa0RZs9LbiPMuHYcP67s21CLL9qEicRYCsoufPWWbF5ov08M6cCgGHvSQpfLGO6mYFqiIBQCkWtG8wtta4nx6QWFk5DDtsAFUmSnJdj9al1pKIpNMlMHrxbtF1zcFmXanwCELCEamf8S6JqD60sJ7jqqgfxbwPr0vLWQRQO1HBMuDduEov2h_ytV8Gdd59v9RoyaBxsKlFGqTxdfBA4zYzmOz6FcPcUP8oyLbTT6xWtnqyonCokb3YP0YnRPCeuTRVaR0_XP1c5UYESu7eqo1ITIRFxryaiS7_KQZYEhgmsUNp2uDWoqyAJNXKkoD9dFvZT9UlEayyxQxECURLWscOfx1l0FwGy0)](https://www.planttext.com/?text=dLGzRzim4DtvAwv3KRieLCj15iKmughe5CH3FMQXf9DqC4q69EL0BVBVUwHgENODnEWYY7VtJdmVqBtpqlfkfuJu10-cb0gSxnL2RIpu5g4YkJEwSc3gUAx9EWzKtub575mAMNhQa--_asoitC5l0GTKV0Tu88svKRonK1t6qZTPRXjhEbqD3KLDw_DUwX6mQQdSQdGEvh6sijQy78kpv3QMVnZj7-KEkKzy-KSPniREiDnYDLP-qY-4D3sU8rkBJQUavUghU1MBht-fPMlzZWYrCjAJRa0RZs9LbiPMuHYcP67s21CLL9qEicRYCsoufPWWbF5ov08M6cCgGHvSQpfLGO6mYFqiIBQCkWtG8wtta4nx6QWFk5DDtsAFUmSnJdj9al1pKIpNMlMHrxbtF1zcFmXanwCELCEamf8S6JqD60sJ7jqqgfxbwPr0vLWQRQO1HBMuDduEov2h_ytV8Gdd59v9RoyaBxsKlFGqTxdfBA4zYzmOz6FcPcUP8oyLbTT6xWtnqyonCokb3YP0YnRPCeuTRVaR0_XP1c5UYESu7eqo1ITIRFxryaiS7_KQZYEhgmsUNp2uDWoqyAJNXKkoD9dFvZT9UlEayyxQxECURLWscOfx1l0FwGy0)

_If that is more clear_ 😄 
Regards,
Th.

**Comment by arnaudroques** [comment]
> _If that is more clear_ 😄

Yes, definitively more clear! We were lost with all those colors :-)

This might be [fixed in last snapshot](https://www.plantuml.com/plantuml/uml/dLBDRjf04BxlKqnFXQgY9LBLYY0KIjLJb1pA2wpNOtl4U2VQNITogxnxr-koIAOIA0SCyyryoD_FdG_QXQvbfTx3lHZDu4FF29Ku20r2IReLMtgGAiqLEH-0gbkrJeSRfKsWPmhz3zArqotyKN1afTy0zsHn9omE2kumGT-rETHEEbkE2wQw2RjUsqpODsGE5hs7cuHjdPEN4_XvyIN1FyM61zrYt9DcUD33MTwCV-wmpCWl-etmzJGciGxhZhMBwAjwLUjF_vIj7kq53oeM7SZMO2MWsXeZhenZkjA5F2FCU31rFhgwKXzW7rTC5i6aToC_SA4MAHK5y8rqN4A1i4xxrU3OPdYCrApgCZEgtiJFo9jOUk8UzzcCoMwnMCJdkjWyMkwJhcbqvDFjEuMs77sW2cOb6l8aTZvmBCnwzFFa-cgtl5N8FbfZPJwGg5BNji-ZYUDRwvUBC9NmHFRmd-8jpugNmLoxdNIEq6LmqlDSkUMtIUSeQ2PpRUMoy6ddOZ9RvcC8qA3361dCc0u8D9AVz63C2p4FzQXPYjX8jJ_FycCw7_tAOrPrTS0tvm7VnQ-kvRy0).
Please reopen this issue if needed!

Many thanks for your tests!
