### ISSUE TITLE
Syntax error when aliasing in nested declarations

### ISSUE THREAD

**Issue by ohunter** [plantuml/plantuml#1625]
**Describe the bug**
It seems like the parser might be struggling with aliasing on nested declarations. 
A simple example such as this works fine.
```
@startuml
package P as p {
    interface I as i
}
@enduml
```
However by just adding a class declaration it freaks out.
```
@startuml
package P as p {
    interface I as i
    class C
}
@enduml
```
It doesn't even matter if the class is declared inside of the package.
```
@startuml
package P as p {
    interface I as i
}
class C
@enduml
```
```
@startuml
class C
package P as p {
    interface I as i
}
@enduml
```
```
@startuml
package P as p {
    class C
    interface I as i
}
@enduml
```
Those last two are quite interesting as they indicate that the issue isn't necessarily the class declaration.
This can also be shown by simply removing the alias
```
@startuml
package P as p {
    class C
    interface I
}
@enduml
```

**To Reproduce**
Just try the examples above in the online demo

**Expected behavior**
It should compile without a syntax error

**Screenshots**
![image](https://github.com/plantuml/plantuml/assets/2663525/24f789a8-7e91-4524-840b-9f5ba63954c0)

**Desktop (please complete the following information):**
Shouldn't really matter as this was tested on the online demo

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by ohunter** [comment]
This might be unrelated, but it also fails with this example:
```
@startuml
allowmixing
abstract       "abstract"       as a1
abstract class "abstract class" as a2
actor          "actor"          as a3
agent          "agent"          as a4
annotation     "annotation"     as a5
artifact       "artifact"       as a6
boundary       "boundary"       as b1
card           "card"           as c1
circle         "circle"         as c2
class          "class"          as c3
cloud          "cloud"          as c4
collections    "collections"    as c5
component      "component"      as c6
control        "control"        as c7
database       "database"       as d1
diamond        "diamond"        as d2
entity         "entity"         as e1
enum           "enum"           as e2
exception      "exception"      as e3
file           "file"           as f1
folder         "folder"         as f2
frame          "frame"          as f3
hexagon        "hexagon"        as h1
interface      "interface"      as i1
label          "label"          as l1
metaclass      "metaclass"      as m1
node           "node"           as n1
package        "package"        as p1
participant    "participant"    as p2
person         "person"         as p3
protocol       "protocol"       as p4
queue          "queue"          as q1
rectangle      "rectangle"      as r1
stack          "stack"          as s1
stereotype     "stereotype"     as s2
storage        "storage"        as s3
struct         "struct"         as s4
usecase        "usecase"        as u1
@enduml
```
![image](https://github.com/plantuml/plantuml/assets/2663525/adfc954e-c3f7-4d6d-94bc-c59f9e160f96)

**Comment by The-Lum** [comment]
Hi @ohunter, and all,

See some elements here:
- [QA-18449](https://forum.plantuml.net/18449/nesting-three-levels-using-using-allowmixing-breaks-things)

From your example:
```puml
@startuml
package P as p {
    interface I as i
    class C
}
@enduml
```

If you use quote to define _label_ and no quote for _alias_, we can see the expected output:
```puml
@startuml
package P as p {
    interface "I" as i
    class C
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1ILF9P149bWuEIUnk5Z1cQkMoo4rBmMe6m00)](https://www.planttext.com/?text=SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1ILF9P149bWuEIUnk5Z1cQkMoo4rBmMe6m00)

_Enjoy._

---

For the second  example:
>This might be unrelated, but it also fails with this example
- It is normal: because `participant` is only for sequence diagram!

See this example of sequence diagram:
```puml
@startuml
'allowmixing
title Sequence Diag.
actor          "actor"          as a3
'agent          "agent"          as a4
'annotation     "annotation"     as a5
'artifact       "artifact"       as a6
boundary       "boundary"       as b1
'card           "card"           as c1
'circle         "circle"         as c2
'class          "class"          as c3
'cloud          "cloud"          as c4
collections    "collections"    as c5
'component      "component"      as c6
control        "control"        as c7
database       "database"       as d1
'diamond        "diamond"        as d2
entity         "entity"         as e1
'enum           "enum"           as e2
'exception      "exception"      as e3
'file           "file"           as f1
'folder         "folder"         as f2
'frame          "frame"          as f3
'hexagon        "hexagon"        as h1
'interface      "interface"      as i1
'label          "label"          as l1
'metaclass      "metaclass"      as m1
'node           "node"           as n1
'package        "package"        as p1
participant    "participant"    as p2
'person         "person"         as p3
'protocol       "protocol"       as p4
queue          "queue"          as q1
'rectangle      "rectangle"      as r1
'stack          "stack"          as s1
'stereotype     "stereotype"     as s2
'storage        "storage"        as s3
'struct         "struct"         as s4
'usecase        "usecase"        as u1
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/NPHDSkGW34RtdCB59hjKzSyasopc1dC2DPOTAXW8u4hdzYDi0yAzUrsl9FGXyn4JXBGkHho0CUvdqKzjPv5qCZZym-yLhSBXhuRvLO1ABWpr9pUMxG-80zoepemsSItpIRkJPgrBaBIpXrPPLkqFQI7fYJhLQWTBLkrDFDngHmY_nIhChCT5l2W8Opl883EpasLDPKq7HUCtRMFPQLVI3CJ8gsNk1rMthBbrx3JYatONoXc3AeyVTwknB1R5eTpYdQq1oygo5NkZOZO5PrhBdILl-Iv6IF20M0QLXLbe8wKnQbYShHF8WtcnyIhe23gL_CdQkSiCgHZQTU4taFbq0qZHubEXhxj1Mk4s9bAqasRNH5hcKxM9caxEZ1YOjd5tjecQJW4MvDKoznSrKTDFVC9SJaRQmJoFJsggRS90ctfKb9NR29eq0myqhOVSk6zgI5im0TitMRbLMqYpRkm2oNmAn9BcGNtHPrcrW_a8_Y9y_jQKzh1lcsHSLj9JR1v3R76Gjd6NhgVOV739gRgKiZ3RDdyNzE2i_0usxkFufW42VHfWvtBxidAB8v16ZvlwOjKsxgl5JSE0BlrwB5hX-XJ5QzPSuAaTp5EBjwo5LRK7KExSvH7f_LiZglRn3V9WNcszY0-q8xtE_m40)](https://www.planttext.com/?text=NPHDSkGW34RtdCB59hjKzSyasopc1dC2DPOTAXW8u4hdzYDi0yAzUrsl9FGXyn4JXBGkHho0CUvdqKzjPv5qCZZym-yLhSBXhuRvLO1ABWpr9pUMxG-80zoepemsSItpIRkJPgrBaBIpXrPPLkqFQI7fYJhLQWTBLkrDFDngHmY_nIhChCT5l2W8Opl883EpasLDPKq7HUCtRMFPQLVI3CJ8gsNk1rMthBbrx3JYatONoXc3AeyVTwknB1R5eTpYdQq1oygo5NkZOZO5PrhBdILl-Iv6IF20M0QLXLbe8wKnQbYShHF8WtcnyIhe23gL_CdQkSiCgHZQTU4taFbq0qZHubEXhxj1Mk4s9bAqasRNH5hcKxM9caxEZ1YOjd5tjecQJW4MvDKoznSrKTDFVC9SJaRQmJoFJsggRS90ctfKb9NR29eq0myqhOVSk6zgI5im0TitMRbLMqYpRkm2oNmAn9BcGNtHPrcrW_a8_Y9y_jQKzh1lcsHSLj9JR1v3R76Gjd6NhgVOV739gRgKiZ3RDdyNzE2i_0usxkFufW42VHfWvtBxidAB8v16ZvlwOjKsxgl5JSE0BlrwB5hX-XJ5QzPSuAaTp5EBjwo5LRK7KExSvH7f_LiZglRn3V9WNcszY0-q8xtE_m40)

_If that can help,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

Another funny example, compare _(tested on 1.2023.13beta3)_:

## Label without quote: that is a Component/Deployment diagram
```puml
@startuml
package P as p {
    interface I as i
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1K-GS2PNBPT3QbuAK3q0)](https://www.planttext.com/?text=SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1K-GS2PNBPT3QbuAK3q0)



## Label with quote: that is a Class diagram
```puml
@startuml
package P as p {
    interface "I" as i
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1ILF9P149bSjbqDgNWfG1m00)](https://www.planttext.com/?text=SoWkIImgAStDuIf8JCvEJ4zL2518B5OeKAZcKW22pBoIrAAqnEHK1ILF9P149bSjbqDgNWfG1m00)

_Funny..._ 🤣

**Comment by ohunter** [comment]
While quoting solves that example it does cause issues with others
```
@startuml
set separator ::
interface "P::I" as i
@enduml
```
vs
```
@startuml
set separator ::
interface P::I
@enduml
```
I would expect those diagrams to look the same but they dont.
So that means that I instead have to write
```
package P {
interface "I" as i
}
```



> > This might be unrelated, but it also fails with this example
> - It is normal: because participant is only for sequence diagram!

Right, but that is why the `allowmixing` instruction was there. 
Additionally, it being considered a syntax error is misleading when it is a limitation of the grammar.

**Comment by The-Lum** [comment]
Hi @ohunter, and all,

## Alias, label and namespace
It's not all done...

In fact, the similar diagram of:
```puml
@startuml
set separator ::
interface P::I
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIfEBL4eJYr8B4eioIzIiBBYoimhIIrAIqnELGYmilBaSaZDIm6g0m00)](https://www.planttext.com/?text=SoWkIImgAStDuIfEBL4eJYr8B4eioIzIiBBYoimhIIrAIqnELGYmilBaSaZDIm6g0m00)

is:
```puml
@startuml
set separator ::
interface "I" as P::I
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIfEBL4eJYr8B4eioIzIiBBYoimhIIrAIqnELL3oL598B5O8iBBov798pKi1AWS0)](https://www.planttext.com/?text=SoWkIImgAStDuIfEBL4eJYr8B4eioIzIiBBYoimhIIrAIqnELL3oL598B5O8iBBov798pKi1AWS0)

Because if there is only _alias_: the _label_  is deduced from the alias ,
but if there are _alias_ and _label_: _label_ is use to label especially to manage space within it (**not to manage namespace**) as:
```puml
@startuml
set separator ::
interface "I is the label" as P::I
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/3Skn3O0m30J0FbEyCeQhjEbOmS0Z8fc0RBC_N7yjKZtVoqem4NpKDM-7I1apwOTkHEqOWJm9qvLMeO55f9V6kV_t0m00)](https://www.planttext.com/?text=3Skn3O0m30J0FbEyCeQhjEbOmS0Z8fc0RBC_N7yjKZtVoqem4NpKDM-7I1apwOTkHEqOWJm9qvLMeO55f9V6kV_t0m00)

_If that can help._

## `allowmixing`
>Right, but that is why the allowmixing instruction was there.

Here is a precision about `allowmixing`, it is only to mix element from:
- `class`
- `object`, `map`, `json`
- `component`, `deployment`
- `state`

Not for other diagram as:
- `sequence`
- `activity`
- `timing`
- ...
_which cannot be mixed with anything else!_

See full example here:
- https://plantuml.com/en/deployment-diagram#e75c1203eb5d242a

And for:
>Additionally, it being considered a syntax error is misleading when it is a limitation of the grammar.

All proposal are welcome, and you can contribute and send a PR...

_If that can help._
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @ohunter  for the report.

Regards.
