### ISSUE TITLE
shape "activity" ist  hardly missing

### ISSUE THREAD

**Issue by boessu** [plantuml/plantuml#1631]
**Problem**
At the moment (and as far as I knoiw), Plantuml doesn't provide any form of an "activity" shape for elements (see https://plantuml.com/de/deployment-diagram). This is a common shape used to visualize Activities, Processes, Value Streams and so on.
In Edgy, it is used to display activities (Journeys, Processes, Stories)
![edgy-activity](https://github.com/plantuml/plantuml/assets/2807976/70ac3ffa-cb47-4aa7-9525-294e9ebf1464)
In archimate, it is used to visualize value streams:
![archimate_valuestream](https://github.com/plantuml/plantuml/assets/2807976/9ef547f2-9d62-4387-8e46-ef77560e0925)

**Solution**
I know these are two forms. I'm quite sure one form would help alot. My concrete proposition:
- Introduce a new shape with the keyword **activity**. As far as I see that, there is actually no allocated keyword "activity" in plantuml. Alternative keywords: **action**, **process**, **deed**, **arrow**, **cds** (shape keyword in GraphViz; don't know what it really means...)
 - The first "Edgy"-shape might be easier to integrate as it is available in GraphViz too as the node shape "cds". From the layouting-perspective it is easier and less errorprone to draw automagically the edges / links to that node shape in a graph (The concave indentation on the left side of the archimate shape is very difficult if you want appealing results).

**Alternatives**
Alternatives would be the following ones, but at the end the results are all very "baa" workarounds for the missing shape:
- hexagon
- rectangles with skinparam DiagonalCorner

**Comment by boessu** [comment]
I've had a deeper look at the rendering of the actual "rectangle" svek. I've noted "diagonalCorner" is basically a "UPath" and not a "URectangle". It also seems ot be rather hard to implement a completey new shape as it would mean to re-implement all devices (beside of Graphics2D: EPS, HTML5, SVG, Tikz...). Maybe it would make more sense to add it as a skinparam of a rectangle?

something like;
```
skinparam rectangle {
   LeftPointing 20
}
``` 

It could be a new method in URectangle. Although I'm not sure how hard it is to integrate that:
```java
	public Shadowable leftPointing(double pointing) {
		if (ignoreForCompressionOnX || ignoreForCompressionOnY)
			throw new IllegalStateException();

		if (pointing == 0)
			return this;

		final UPath result = UPath.none();
		result.moveTo(0, 0);
		result.lineTo(width - pointing, 0);
		result.lineTo(width, height / 2.0);
		result.lineTo(width - pointing, height);
		result.lineTo(0, height);
		result.lineTo(0, 0);
		return result;
	}
```
The disadvantage of that is that the existing "RoundCorner" and "DiagonalCorner" skinparams do compete with that new parameter. Quite frankly, that's already the case with the two exiting skinparams.

**Comment by arnaudroques** [comment]
In [last commit](https://github.com/plantuml/plantuml/commit/d07cda5f5f8d9b4082f46f989c5c18ec98fa0e4f), we added `process` and `action` keywords.
Not sure that these are the best keyword, we can still change them. We are reluctant to use `activity` as keyword.

Any though?

**Comment by boessu** [comment]
Thanks. I've tested a bit, and it seems to work fine. The new element shapes are a very good thing.

I think these keywords are fine. I also already thought "activity" as a keyword would be a rather bad idea. As a 1st thing, it is a "UML Word" in the uml perspective where these will live on now, and 2nd it's already used in the skins (activityDiagram.activity). Quite frankly, even if it would be a keyword, the according Java files shouldn't have the word "activity" in it as it has already a plethora of classes with the word "activity" in it (as far as I see that all depending on the UML activity diagram area). That's not very helpful for contributors either if that would result in a mess...

Actually, these are only usable as element shapes. Is it possible to use it "like" the rectangle shape, which can be used either as element shape or as grouping shape? The reason why I'm asking are pictures from the area of E2E Processes like this:
![Screenshot 2024-01-06 155448](https://github.com/plantuml/plantuml/assets/2807976/dcfb8e72-05f1-426d-876d-b1d6b0575aa1)
or this (like in edgy)
![EDGY-Process-Map_Process-Model_Process-Chart](https://github.com/plantuml/plantuml/assets/2807976/9ef3d985-2bf2-4aca-bdd0-5c975a119463)
Would that be possible?

**Comment by The-Lum** [comment]
Hi @arnaudroques, and all,

- Is it plan to have specific style for `action` or `process`?
- _Currently, it depends only of `rectangle` style?_

Regards,
Th.

**Comment by arnaudroques** [comment]
> * Is it plan to have specific style for `action` or `process`?

Yes, you are right, probably we should create `action` and `process` style.
Is this useful?

**Comment by The-Lum** [comment]
> Is this useful?

More consistent!
😏

**Comment by arnaudroques** [comment]
Sorry, we are lazy sometimes :-)
This should be fixed in last snapshot and on the [online server](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuR8fBgdCIRNZIamkoSpFKwZcKb1moyyhSSxFoIzIA4fDuQhbij57LOEa54N445t02AYve2W_ERMuM05AWtMXYHbY2e5qEgJcfG1T2000).

**Comment by The-Lum** [comment]
Hi @arnaudroques, and all,

During a test with `smetana` we observe a minor overlapping _(at the top start of the arrow)_.
Here is a minimal example:
```puml
@startuml
!pragma layout smetana
process process {
process process1
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4laAYZAJqujBbQ0qTNe8ePSjLnf-VabgKKACNc6UaO6HYPw1ab0pKOnUQfbgKN5cVbv6ffS3gbvAK1h0000)](https://www.planttext.com/?text=SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4laAYZAJqujBbQ0qTNe8ePSjLnf-VabgKKACNc6UaO6HYPw1ab0pKOnUQfbgKN5cVbv6ffS3gbvAK1h0000)



Regards,
Th.

**Comment by boessu** [comment]
Hello @The-Lum (and all)

I think the problem you've found is the same as this issue here: https://github.com/plantuml/plantuml/issues/1638
So not specific to this new shapes, but they're affected too (in a very similar manner).

Cheers
B.

**Comment by boessu** [comment]
@arnaudroques: I've added the new "action" keyword to the edgy library in https://github.com/plantuml/plantuml-stdlib. That was some sort of a test case. ;-)
It seems as everything works fine.
![image](https://github.com/plantuml/plantuml/assets/2807976/a65acfd7-05e6-43cb-84d4-91cad6758c60)
![image](https://github.com/plantuml/plantuml/assets/2807976/ad5c758d-c1a2-4529-9cff-eeafe4c60467)
