### ISSUE TITLE
[Style] Allow style for backward element on while loop, on Activity diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1632]
Hi PlantUML team,

## Context
To continue:
- #1531

## Wanted feature
- Could you allow style for `backward` element **_on while loop_** on Activity diagram?

## Source
```puml
@startuml
<style>
.save {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>

while (check filesize ?) is (not empty)
  :read file; <<save>>
  backward:log context; <<save>>
endwhile (empty)
:close file;


while (check filesize ?) is (not empty)
  :read file; <<save>>
  backward:log
context; <<save>>
endwhile (empty)
:close file;
@enduml
```

## Output: The `backward` element is not styled _(tested on `1.2023.14beta2`)_ :x:
>[![](https://www.planttext.com/api/plantuml/svg/hP51JuGm48Nl_HLpCO4BBgWN9BXAuici1ptkfPHPQ2YjcPP5DFvt1nUZLnDldMzUtvl9R7sG5CR1YCA7sM0f4Y-F2Ey2u45Rh9nn1BKPaS6TL7rBRhJD2HlTTg6QfLt5pvrMlKNl8MDoI-Ic7xH9hXZUEnjsSa3kQcbW9nVHoa-cXCrQF-atX3JzhfRnkDkEHfBu4CNvEh2OEisTI7MeUZZmsoyVRsBG7YBh0k3m4kQOVN92sNn9hg4ebaNBad7DUqsIcjou5XHduMlu9K3Rh16hKQwCytZo4V-SB_wQVt0k8C7UFjO-0MVpDCassKMINjOOPBQtrKY4DkHdHoIldOrYiMLBllad)](https://www.planttext.com/?text=hP51JuGm48Nl_HLpCO4BBgWN9BXAuici1ptkfPHPQ2YjcPP5DFvt1nUZLnDldMzUtvl9R7sG5CR1YCA7sM0f4Y-F2Ey2u45Rh9nn1BKPaS6TL7rBRhJD2HlTTg6QfLt5pvrMlKNl8MDoI-Ic7xH9hXZUEnjsSa3kQcbW9nVHoa-cXCrQF-atX3JzhfRnkDkEHfBu4CNvEh2OEisTI7MeUZZmsoyVRsBG7YBh0k3m4kQOVN92sNn9hg4ebaNBad7DUqsIcjou5XHduMlu9K3Rh16hKQwCytZo4V-SB_wQVt0k8C7UFjO-0MVpDCassKMINjOOPBQtrKY4DkHdHoIldOrYiMLBllad)

Regards,
Th.

**Comment by arnaudroques** [comment]
This should be fixed now. Please reopen the issue if needed!
