### ISSUE TITLE
Class diagram skinparam not applied for enum, interface, or abstract

### ISSUE THREAD

**Issue by judebert** [plantuml/plantuml#164]
### skinparam for enum in class diagram
In class diagrams, it can be useful to visually distinguish between enums and other classes. Normally a skinparam could be used for this case. However, skinparam blocks with an enum specifier are not applied, even if combined with a stereotype.

Skinparam blocks with interface or abstract specifiers are also not applied.

#### Example
This example extends the sample class diagram with three ways of defining an enum and skinparam blocks for various definitions of enum, interface, and abstract. If the `skinparam enum` were being applied, TimeUnit would be light green. If the `skinparam enum<<enumeration>>` were being applied, Meridian would be light green. As it is, `skinparam class<<enumeration>>` is being applied to all classes with the enumeration stereotype, regardless of whether they were defined as `enum` or `class`. This leads to both Meridian and Effect being colored light pink.  
```
@startuml

skinparam enum {
  BackgroundColor LightGreen
}
skinparam enum<<enumeration>> {
  BackgroundColor LightGreen
}
skinparam class<<enumeration>> {
  BackgroundColor LightPink
}
skinparam interface {
  BackgroundColor LightBlue
}
skinparam class<<interface>> {
  BackgroundColor LightBlue
}
skinparam abstract {
  BackgroundColor Thistle
}

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection<<interface>>

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

enum Meridian<<enumeration>> {
  AM
  PM
}

class Effect<<enumeration>> {
  POSITIVE
  NEUTRAL
  NEGATIVE
}
@enduml
```
![image](https://user-images.githubusercontent.com/2171690/50918365-e798a780-13f4-11e9-8ff6-2c0043858afd.png)

#### Workaround
This issue can be worked around by styling based on stereotype and hiding the stereotype.

**Comment by arnaudroques** [comment]
Thanks for the suggestion.
This has been done in last beta http://beta.plantuml.net/plantuml.jar
Note that only enum are taken into account (not interface, neither abstract class) and only for background color.
Is this what you are expecting ?

**Comment by judebert** [comment]
(Sorry for my delayed response.)

I tend to style enumerations with a thicker border, too. I use dotted lines for interfaces and abstract classes. 

Background color is a great start! Minimally, we should also include text color, to avoid black-on-black text.
