### ISSUE TITLE
Some usage issues about ER Diagrams

### ISSUE THREAD

**Issue by shuaixiaomi** [plantuml/plantuml#1645]
```plantuml
@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Entity01" as e01 {
  *e1_id : number <<generated>>
  --
  *name : text
  description : text
}

entity "Entity02" as e02 {
  *e2_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}

entity "Entity03" as e03 {
  *e3_id : number <<generated>>
  --
  e1_id : number <<FK>>
  other_details : text
}

e01 ||..o{ e02
e01 |o..o{ e03

@enduml
```

- For this example，how to achieve `e01.e1_id ||..o{ e02.e2_id`?

**Comment by The-Lum** [comment]
Hello @shuaixiaomi, 

Could you use:
```
e01::e1_id ||..o{ e02::e2_id
```
_If that can help,_
Regards,
Th.

**Comment by shuaixiaomi** [comment]
> Hello @shuaixiaomi, 你好 、
> 
> Could you use: 你能用
> 
> ```
> e01::e1_id ||..o{ e02::e2_id
> ```
> 
> _If that can help, 如果能帮上忙的话、_ Regards, 谢谢、 Th.

Thanks, this works, but unfortunately the formatting is not very good

**Comment by The-Lum** [comment]
Yes, it is due to:
```
skinparam linetype ortho
```

Could you test without?

Regards,
Th.

**Comment by shuaixiaomi** [comment]
> Yes, it is due to:
> 
> ```
> skinparam linetype ortho
> ```
> 
> Could you test without?
> 
> Regards, Th.

Thanks, the effect is better after deleting 'skinparam linetype ortho'

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @shuaixiaomi  for the report.
- Thanks PlantUML team for your work.

Regards.
