### ISSUE TITLE
Old version of plantuml online

### ISSUE THREAD

**Issue by boessu** [plantuml/plantuml#1647]
**What is the URL of the documentation?**
https://plantuml.com/de/stdlib#6c5e19f750e8f085

**What can be improved?**
The version active in that area is 1.2023.14beta2. The stdlib for edgy is active beginning from version 1.2024.0beta2. If you press the "Edit online" button left of the code, you'll get to the online plantuml editor, where the graphs do work as expected.
(Is there a reason for two different versions online?!)

**Additional context**
The last check-in of edgy in the stdlib has now two visual flavours of the library (because of the new "action" keyword. In for a penny, in for a pound. ;-)). I will document the 2 flavours as soon as it works online.

**Comment by The-Lum** [comment]
Hello @boessu,

Awaiting update of the plantuml version on the official doc. site;

You can update the documentation here:
- http://alphadoc.plantuml.com/doc/markdown/en/stdlib#eizp4unk92nxlribd5h5

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @boessu,

It is now updated, you can see the rendering and make further improvements:
- https://plantuml.com/de/stdlib#7c3d1cde3762ae3b
- http://alphadoc.plantuml.com/doc/markdown/en/stdlib#eizp4unk92nxlribd5h5

_Thanks to PlantUML team, and @arnaudroques,_ 👍 
Regards,
Th.

**Comment by boessu** [comment]
Hello @The-Lum and all

Yes, now it works . Thanks to all of the PlantUML Team. :+1: 
I've added what I had to add already before. Now I'm eager what happens (or not) within edgy community. ;-)

Cheers
