### ISSUE TITLE
State name with dots create composite states

### ISSUE THREAD

**Issue by tamas-p** [plantuml/plantuml#1648]
**Describe the bug**
When dots are used in a state name it creates composite states since plantuml-1.2023.2.
Before it created one state with the name with dots.

**To Reproduce**

```plantuml
@startuml T1
state L0.L1.L2
@enduml
```

**Expected behavior**
![Screenshot from 2024-01-22 23-55-34](https://github.com/plantuml/plantuml/assets/10595775/3452d2c6-2402-42a7-afd2-d1d62230d9a2)
**Actual behavior**
![Screenshot from 2024-01-22 23-56-18](https://github.com/plantuml/plantuml/assets/10595775/524f869c-521c-4663-9e26-fd29c9d9dd98)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Chrome

**Comment by The-Lum** [comment]
Hello @tamas-p, and all,

See similar issue here:
- https://github.com/plantuml/plantuml/issues/1309

Then:
- Could you use: `set separator none`?

With it we can see the expected result:
```puml
@startuml
set separator none
State L0.L1.L2
@enduml
```
And see result [here](https://www.plantuml.com/plantuml/umla/LOr12e1024Ntda9cNqU8kOeqKWlJKAFh5yCGj7lyz-7LIFAy3e7WnE2JdD8SrPG1dDSatOInx2nY1IcGviu_UvjB6xOpmBZXj7nRPMrlwW40).

If that can help,
Regards,
Th.

**Comment by tamas-p** [comment]
Thanks a lot! I tried searching around last night but missed it somehow.

 `set separator none` helps indeed, however I have similar feelings like @chrismalek regarding the importance of backward compatibility. Having the new behavior effective only by something like `set separator dot` the impact on existing diagrams and tools could have been avoided.
