### ISSUE TITLE
Request: state what `skinparams` each standard library clobbers

### ISSUE THREAD

**Issue by philCryoport** [plantuml/plantuml#1650]
**What is the URL of the documentation?**

https://plantuml.com/stdlib

**What can be improved?**

My sequence diagram had:

```puml
skinparam {
SequenceMessageAlign left 
noteTextAlignment left
wrapWidth 300
maxMessageSize 150
}

!include <awslib/AWSCommon>
```

As a result, `AWSCommon` clobbered those `skinparams`:
* SequenceMessageAlign by [here](https://github.com/plantuml/plantuml-stdlib/blob/5e10319d39e32bf3679d401d013af57c8a9e4fc9/awslib14/AWSCommon.puml#L31) (I think)
* wrapWidth by [here](https://github.com/plantuml/plantuml-stdlib/blob/5e10319d39e32bf3679d401d013af57c8a9e4fc9/awslib14/AWSCommon.puml#L35)
* maxMessageSize by [here](https://github.com/plantuml/plantuml-stdlib/blob/5e10319d39e32bf3679d401d013af57c8a9e4fc9/awslib14/AWSCommon.puml#L36)

To figure this out took me commenting out whole swaths of PlantUML code -- currently 237 lines and counting.

It would be nice if each Standard Library listed which `skinparams` it clobbers [on the Standard Libraries page](https://plantuml.com/stdlib)

Alternatively -- I can create a separate feature request for this if there is interest -- perhaps standard libraries should be refactored / adjusted so that each `skinparam x y` statement is wrapped with a "is not set" check, e.g.:

"if skinparam x is not set, then set skinparam x to y"

❓

**Additional context**

N/A

**Comment by The-Lum** [comment]
Hi @philCryoport,

To avoid the clobbered and to override style:
- Could you reverse the block as:

```puml
!include <awslib/AWSCommon>

skinparam {
  SequenceMessageAlign left 
  noteTextAlignment left
  wrapWidth 300
  maxMessageSize 150
}
```

_Enjoy,_
Regards,
Th.

**Comment by philCryoport** [comment]
Hi @The-Lum ,

I think in the end I did that...haven't looked at that diagram in almost a year now...
