### ISSUE TITLE
How to change direction of arrow in beta syntax in "Activity Diagram"?

### ISSUE THREAD

**Issue by GSebastian-Adil** [plantuml/plantuml#166]
How to change direction of arrow in beta syntax in "Activity Diagram"?

Because arrow syntax:

**Normal Syntax:** -direction->[text]

**Beta Syntax:** -[#color , type]->[text] (where is the direction)

**Comment by that-coding-human** [comment]
I think this is an issue that is bugging people for a while now (as the number of "thumbs up" shows.
I would love to have a way to force the direction of specific arrows.

For example I am having:

```
if(somecheck) then (yes)
    end
else (no)
endif
    :moreSomething;
    :moreStuff;
stop
```

In the actual plantuml version, the (yes) arrow goes right down, while the no arrow goes right and then down again. Having some of these in a diagram makes it look overly complicated. I would love to force the (yes) arrow to go just right, and directly to the end node, while the (no) arrow goes down, and continues the activity flow. 
The default behaviour might be fine in a lot of cases, but I consider forcing the direction of specific arrows quiet important to enable users to format the flow of their activity diagrams.

Are there any plans to add this as an enhancement? I love the new Activity Syntax, as it provides so much more functionality, but this is something that is really missed.

**Comment by arnaudroques** [comment]
The following example should work fine with last snapshot:

```
@startuml
if(somecheck) then (yes)
    end
else (no)
endif
    :moreSomething;
    :moreStuff;
stop
@enduml
```
