### ISSUE TITLE
sub-diagrams docs

### ISSUE THREAD

**Issue by grivo** [plantuml/plantuml#1666]
there is no explicit documentation on sub-diagrams, no explanation on nesting limitations, styling of nested diagrams, etc

**Comment by The-Lum** [comment]
Hi @grivo,

You are right; even if I started _(on 2022)_ a beginning here:
- http://alphadoc.plantuml.com/doc/markdown/en/sub-diagram

Regards,
Th.

**Comment by grivo** [comment]
should something be done here then?

**Comment by arnaudroques** [comment]
> You are right; even if I started _(on 2022)_ a beginning here:

Sorry for the delay...
It's online now https://plantuml.com/sub-diagram

Many thanks for your contributions!
Anyone can improve this doc now :-)

**Comment by grivo** [comment]
thanks!
