### ISSUE TITLE
feature: random() function -- with a way to pick a number between X & Y

### ISSUE THREAD

**Issue by philCryoport** [plantuml/plantuml#1667]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
My intended use is for MQTT Packet Identifiers in a sequence diagram.  

Brief overview of MQTT Packet Identifiers:
* MQTT Packet Identifiers range from decimal 1 to decimal 65535 and are used for traceability between:
  * Each MQTT Client -> MQTT Broker request, and 
  * The MQTT Broker's acknowledgment of a particular request in a message back to the transmitting MQTT Client
* MQTT Packet Identifiers have to be unique for each MQTT Client Request -- and with the upper limit being 65535, the Client is expected to sequentially use these Packet Identifier numbers, rolling back to 1 after 65535.

Now in a sequence diagram where I'm highlighting particular requests made by a MQTT Client to the MQTT Broker in the diagram, I _could_ illustrate the use of these MQTT Packet Identifiers by just incrementing the packet identifer by 1, 10, or 100 -- using higher increment quantities to illustrate that there were requests sent in-between the actual particularly highlighted requests.

I thought it would be more realistic to instead increment the MQTT Packet Identifier number by a random value -- say between 101 and 499.

Hence this request for a `random()` function of some sort where I could have PlantUML (semi) randomly pick a number between X & Y (in this case, between 101 and 499)

**Describe alternatives you've considered**
In theory I could hit one of the random number generator websites on the web each time I want to increment the MQTT Packet Identifier.  However, my concern is that the generator website then becomes a dependency for which I have no control.

**Additional context**
[Originally discussed in PlantUML Discord](https://discord.com/channels/1083727021328306236/1202347142161891399/1202347142161891399)

**Comment by arnaudroques** [comment]
Hi!
Implementing a random function in some software that generates documentation seems completely crazy, so I like the idea. :-)

This should be easy to do.

I propose that `%random(5)` would return an integer between 0 and 4. Note that this function will **not** be safe for cryptographic usage...
Does it match your need ?

**Comment by arnaudroques** [comment]
So you can [try this for example](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhCoKnELT2rKqZAJrAmKb0jIinBoS_LC34mqAI9d4DgNWhGNW00).
