### ISSUE TITLE
Using https for http://plantuml.com

### ISSUE THREAD

**Issue by dqdinh** [plantuml/plantuml#167]
Hi,

Could the plantuml website use HTTPS instead of HTTP?

Thanks for all your work on plantuml!

**Comment by swmatisa** [comment]
Hi,
1) My browser language is not English. When I want to see English version, the link is http://en.plantuml.com/ and not https://en.plantuml.com/
2) https://en.plantuml.com/ is not working
3) forum is not working with https

**Comment by PrinsFrank** [comment]
It would be nice if https could be enabled for the proxy as well. I am using the proxy to render a puml file from github using http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/, but that results in an unsafe include warning.

**Comment by arnaudroques** [comment]
This should be fixed now. https://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt seems to work

**Comment by PrinsFrank** [comment]
tx, fixed!

**Comment by dqdinh** [comment]
Thanks!
