### ISSUE TITLE
Grouping message grouping box does not display correctly (if the data is on the left side of the box).

### ISSUE THREAD

**Issue by devwitalik** [plantuml/plantuml#1680]
**Steps to reproduce the behavior:**

```plantuml
@startuml
skinparam {
      Maxmessagesize 200
   }

   group Grouping messages
      Test <<-- Test : The group frame does not draw a border around the text (located on the left side), but ignores its presence, and also ignores the presence of a line.
   end
@enduml
```

http://www.plantuml.com/plantuml/uml/FKwxJWD13EplAwO4AK4H9KgHZeekF-1aVSUANVjaUqK4uj_P3GakHYFFmpvua4MhPVAFB2iPLNnFkCuRNIgxqyAUlnZFkzqGVgQ1YsbRyJemouAxxvOyiWVs--tsZxtW-Cwto6nK6KdP8Hf8HfyWdDGI6wXR926wE_WIU2Xwfk04bUkoy1pmdFXnWrCBv4NKUbCEnze9ovate5v1nVKkZ-Y_39txlPA5dyQpB6awT6Yr_080

**Expected behavior**
I expect the group frame to completely enclose the text and line, not ignore their presence and not pass through them as if they didn't exist.  That is, I want the group frame to cover the useful data, and not to take the empty space on the right side into the frame.

**Screenshots**

![IMG](http://www.plantuml.com/plantuml/png/FKwxJWD13EplAwO4AK4H9KgHZeekF-1aVSUANVjaUqK4uj_P3GakHYFFmpvua4MhPVAFB2iPLNnFkCuRNIgxqyAUlnZFkzqGVgQ1YsbRyJemouAxxvOyiWVs--tsZxtW-Cwto6nK6KdP8Hf8HfyWdDGI6wXR926wE_WIU2Xwfk04bUkoy1pmdFXnWrCBv4NKUbCEnze9ovate5v1nVKkZ-Y_39txlPA5dyQpB6awT6Yr_080)

**Comment by jimnelson372** [comment]
Has anyone else worked on this?  I've have fixes for this, plus I made sure that it works with notes left and right, short arrows, and more.  There are a few cases when teoz is turned on that still aren't working correctly, and don't work correctly in the latest release, but I want to see if I can get all of this fixed.   BTW, here's the fixed output to the example above:

<img width="260" alt="image" src="https://github.com/plantuml/plantuml/assets/66284321/f7045c0a-e350-4137-8d2f-3564405ae01d">

I will provide before/after images for all the fixes when I have it finished.
