### ISSUE TITLE
`skinparam responseMessageBelowArrow true` do not make Message Below Arrow.

### ISSUE THREAD

**Issue by shutaozhenzhen** [plantuml/plantuml#1694]
**Describe the bug**
`skinparam responseMessageBelowArrow true` do not make Message Below Arrow.

**To Reproduce**
1. just use example in help book:
```plantuml
@startuml
skinparam responseMessageBelowArrow true
Bob -> Alice : hello
Alice -> Bob : ok
@enduml
```

**Expected behavior**
Message Below Arrow

**Screenshots**
![image](https://github.com/plantuml/plantuml/assets/24778590/7851550f-943a-4ef5-82fe-4811cdc3394a)
![image](https://github.com/plantuml/plantuml/assets/24778590/f875a5f3-c432-4cb0-bfd9-716ce6ac99c4)

**Desktop (please complete the following information):**

- OS: Windows jar and web server
- Browser chrome
- Version v1.2024.3 in windows.

also can be seen in help book example

**Additional context**
//www.plantuml.com/plantuml/png/9Op13S8m34Nldi8Bi40FgEsT8GnyGHGdZkn4MP-W7jzxqjkZY_THb2AdsiIbi2EQrS034VB12RLvkDlaxWD4fptvTkT3qmkyyHUgHXSj_QyRMwOTzRt6Fm00

**Comment by The-Lum** [comment]
Hello @shutaozhenzhen,

But for that you must use "response message", as:
```puml
@startuml
skinparam responseMessageBelowArrow true
Bob -> Alice : hello
Bob <- Alice : ok
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/FSp13O0W30NGErDq0HSmne1tXq3zKKAbfiMmliQ3rtTutchKUf_iBAToHOqdAUoIOfXX5dTCO6b1LHfLlU4cMQWRAN1QGJqTO9OFX-v7oSwZRE_x0000)](https://www.planttext.com/?text=FSp13O0W30NGErDq0HSmne1tXq3zKKAbfiMmliQ3rtTutchKUf_iBAToHOqdAUoIOfXX5dTCO6b1LHfLlU4cMQWRAN1QGJqTO9OFX-v7oSwZRE_x0000)

_Perhaps we must to update the doc..._

Regards,
Th.

**Comment by The-Lum** [comment]
Thanks for your report;

See complement and new behavior here:
- #1496
- #1506

**Comment by HeinrichAD** [comment]
@The-Lum I agree with you.

I am pretty sure that per definition all code arrows from right to left `<-` are response arrows and all arrows from left to right `->` request arrows. This is perhaps also good additional information that could be added to the documentation.
Before the changes, the order of the participants was decisive. That means the direction of the _rendered_ arrow determined if the arrow was a response arrow or not. This was quite impractical and stiff.

In my opinion, the example code inside the documentation should be changed (as you already noted) to:

```plantuml
@startuml
skinparam responseMessageBelowArrow true
Bob -> Alice : hello
Bob <- Alice : ok
@enduml
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @shutaozhenzhen  for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.

**Comment by olek3** [comment]
How can I have response text below arrow if I use return statement?
