### ISSUE TITLE
Smetana is not supporting colors in UML

### ISSUE THREAD

**Issue by martinviszlai** [plantuml/plantuml#1702]
When using `!pragma layout smetana`, relation tags formatting is ignored.

Example of a simple diagram:
```plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("API", $lineColor="red", $textColor="red", $lineStyle="dashed")

System(service, "service", "My awesome service")
System(client, "client", "Client service")

Rel(client, service, "make API calls", "HTTP", "calls methods from interfaces", $tags="API")
@enduml
```

**Comment by kirchsth** [comment]
with **elk layout** the colors,... are ignored too. Maybe it is the same skinparam related problem 

https://forum.plantuml.net/18723/elk-layout-ignores-arrow-skinparam

https://github.com/plantuml-stdlib/C4-PlantUML/issues/340

[![](https://www.plantuml.com/plantuml/svg/bP3DJeH048Jl_HJbUb0JyG5qGtQ1T_1WF7HaWeJvsJHDoCRuxWwpekFFPM-LhleefdQZikZaB5s1HSACSUZzWOKTvY33YE3j4NElhs5I63l0yZ7AcByu27UEJuVaqQ_Jw8ooPwBlZwQIxLPCsmHLqvObtWW0wc23u38Q3xRtvgvDDht_3__5KbJCIopihC4-qrMcwqmtH7iKJmjyUwfxBafKkCVcyVF1NzqRgb14jyQFdr-psMpNorXfAHzq6J4wtStADua_ZzmPtqxEVW00)](https://www.plantuml.com/plantuml/uml/bP3DJeH048Jl_HJbUb0JyG5qGtQ1T_1WF7HaWeJvsJHDoCRuxWwpekFFPM-LhleefdQZikZaB5s1HSACSUZzWOKTvY33YE3j4NElhs5I63l0yZ7AcByu27UEJuVaqQ_Jw8ooPwBlZwQIxLPCsmHLqvObtWW0wc23u38Q3xRtvgvDDht_3__5KbJCIopihC4-qrMcwqmtH7iKJmjyUwfxBafKkCVcyVF1NzqRgb14jyQFdr-psMpNorXfAHzq6J4wtStADua_ZzmPtqxEVW00)

Thank you and BR
Helmut

**Comment by The-Lum** [comment]
Hello @arnaudroques, and all contributors,

Here is a minimal not working example:

```puml
@startuml
'!pragma layout smetana

<style>
.a {
  LineThickness 3
  Linecolor red
}
</style>

card a
a -> b <<a>>
@enduml
```


| With GraphViz ✔️ | With Smetana ❌ |
|--------|--------|
| [![](https://www.planttext.com/api/plantuml/svg/BSqx3i8m44NHVbRngAY0WjQoiW1ADl2mHn3X3nfFYYXYxr2alTBHdORJVAb5ZeUFyLc9mhKlZb7LsIWIXgz5evo9JO3RtFJ-cjExwHYuxYNrqWscMRuIBhkGHCkW4AU81q9WZ39fo__V3m00)](https://www.planttext.com/?text=BSqx3i8m44NHVbRngAY0WjQoiW1ADl2mHn3X3nfFYYXYxr2alTBHdORJVAb5ZeUFyLc9mhKlZb7LsIWIXgz5evo9JO3RtFJ-cjExwHYuxYNrqWscMRuIBhkGHCkW4AU81q9WZ39fo__V3m00) | [![](https://www.planttext.com/api/plantuml/svg/BSqx3i8m44NHVbRnM42WeBMiB82I3Jpi4Odm1uqdHOJOEnHfhtHqv-4qtsgHqzluh4JXtZV7gEfi50d3zw9HpiH7WDlQzBwiwTLq35oFadhf1jCiNmcNGqYYPL28AUA141YZpDhoV_S3)](https://www.planttext.com/?text=BSqx3i8m44NHVbRnM42WeBMiB82I3Jpi4Odm1uqdHOJOEnHfhtHqv-4qtsgHqzluh4JXtZV7gEfi50d3zw9HpiH7WDlQzBwiwTLq35oFadhf1jCiNmcNGqYYPL28AUA141YZpDhoV_S3) |

Observed on `1.2024.5beta1`.

_If that can help for debugging..._
Regards,
Th.

**Comment by The-Lum** [comment]
FYI, it is the logical continuation of:
- #1230

@Plantuml team:
-  Thanks for your [next] works

**Comment by The-Lum** [comment]
FYI @kirchsth, 

It is planned to deliver this correction in a next release scheduled for this weekend...
In order to plan on your side a new release of C4.

Regards,
Th.

**Comment by The-Lum** [comment]
Sorry @arnaudroques:
- Were you also able to look at the same type of issue but on the `elk` engine? 😃 

```puml
@startuml
!pragma layout elk

<style>
.a {
  LineThickness 3
  Linecolor red
}
</style>

card a
a -> b <<a>>
@enduml
```

Currently, on the plantuml server, it seems that we observed: `ClassNotFoundException`...

_Ref. :_
- https://github.com/plantuml-stdlib/C4-PlantUML/issues/340
- https://forum.plantuml.net/18723/elk-layout-ignores-arrow-skinparam

**Comment by kirchsth** [comment]
Hi @arnaudroques and @The-Lum 

thank you for the fix and support.

I tested smetana and in C4-Plantuml (uses elk) context with the new released version [v1.2024.5](https://github.com/plantuml/plantuml/releases/tag/v1.2024.5) online and both are working
I think it can be closed 

BR Helmut

**Comment by kirchsth** [comment]
> Currently, on the plantuml server, it seems that we observed: ClassNotFoundException...

It exists an issue for it:  https://forum.plantuml.net/15676/layout-elk-fails-with-nullpointerexception?show=15676

**Comment by kirchsth** [comment]
Hi @arnaudroques,

if you don't have a local version of the `elk-full.jar` file.
You can download it from http://beta.plantuml.net/elk-full.jar and put it parallel to your  plantuml.jar that you have a working environment.

Thank you and best regards
Helmut

**Comment by kirchsth** [comment]
HI @arnaudroques,

I tried to merge the smetana fix to elk and during that I found out that the **font color with smetana layout is not set**, can you try to fix this too.

[![](https://www.plantuml.com/plantuml/svg/NSuz2i905CJn_frYhApKmawM9OrMTkO2O_BGaFsGtPSYY7StHK2m_F-AOPfgB3R58DlDg_0HYS0vJmODe_nHZMfC577Lvg1UziHRWEkGj7qEtPYqLXnNwNB81KNxfIyvsQy_uWxhWdGiFIZ4pkCEv-WzJcZFjrOQJVtox0i0)](https://www.plantuml.com/plantuml/uml/NSuz2i905CJn_frYhApKmawM9OrMTkO2O_BGaFsGtPSYY7StHK2m_F-AOPfgB3R58DlDg_0HYS0vJmODe_nHZMfC577Lvg1UziHRWEkGj7qEtPYqLXnNwNB81KNxfIyvsQy_uWxhWdGiFIZ4pkCEv-WzJcZFjrOQJVtox0i0)

Thank you and BR Helmut

**Comment by kirchsth** [comment]
Smetana/Elk and $FonColor are working in too [snapshot (~v1.2024.6beta8)](https://github.com/plantuml/plantuml/releases/tag/snapshot) (details see mentions above), I think it can be closed.
BR Helmut
