### ISSUE TITLE
timing diagram initial concise state

### ISSUE THREAD

**Issue by arnaudrichard** [plantuml/plantuml#1708]
**Describe the bug**
In timing diagram, the initial state does not display correctly concise state defined as a line with "{-}"

**To Reproduce**
```
@startuml
concise "Web User" as WU
'Following is bugged:
WU is {-} '

'Following is okay:
@0
WU is {-}
@enduml
```

**Expected behavior**
The diagram should start with a line

**Screenshots**
Diagram generated with plantuml.com server:
![image](https://github.com/plantuml/plantuml/assets/17612811/510a5ab8-cb49-4c61-a0dc-278afb3299fa)
![diagram](https://github.com/plantuml/plantuml/assets/17612811/620fd80e-0ecb-46e5-8618-b55e1a962b25)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed on [V1.2024.5](https://github.com/plantuml/plantuml/releases/tag/v1.2024.5).
- Thanks @arnaudrichard for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
