### ISSUE TITLE
Resource off is not propergated to tasks ends.

### ISSUE THREAD

**Issue by gmuellerinform** [plantuml/plantuml#1711]
**Describe the bug**
Resource off is not propergated to tasks ends.

**To Reproduce**

[Task1] as [T1] on {UserA} lasts 14 days
[Milestone1] as [M1] happens after [T1]'s end
{UserA} is off on sunday
{UserA} is off on saturday

**Expected behavior**
Milestone 1 should happen 4 days later

**Comment by The-Lum** [comment]
Hello @gmuellerinform,

Thanks for the report.

In fact _it is due to the linear (top to bottom) internal algo._
- Could you put your 'Resource off' definition on the beginning of your file?

Compare
```puml
@startgantt
project starts 2024-02-01
[Task1] as [T1] on {UserA} lasts 14 days
[Milestone1] as [M1] happens after [T1]'s end
{UserA} is off on sunday
{UserA} is off on saturday
@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/ROuz3i8m38NtdC8RKwKawW7A0RgLAMAmg0E5oebYTq28kvD6i34zwVryUeCe5hqYgvfSqfqk2iqIyDRtdVMTTIPCA0zt1XG8KzN4y3e9bUCRLfJQTJtC-1GJncKbqSJqROzLRvWpiG16fT801m7YsVmOYq2ASQVAnfNpBq3ToXuDTTZkVW00)](https://www.planttext.com/?text=ROuz3i8m38NtdC8RKwKawW7A0RgLAMAmg0E5oebYTq28kvD6i34zwVryUeCe5hqYgvfSqfqk2iqIyDRtdVMTTIPCA0zt1XG8KzN4y3e9bUCRLfJQTJtC-1GJncKbqSJqROzLRvWpiG16fT801m7YsVmOYq2ASQVAnfNpBq3ToXuDTTZkVW00)

With:
```puml
@startgantt
project starts 2024-02-01

{UserA} is off on sunday
{UserA} is off on saturday

[Task1] as [T1] on {UserA} lasts 14 days
[Milestone1] as [M1] happens after [T1]'s end

@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/ROun3i8m34Ltdy8RKwKawW7A0RgLAMAmg0E5AebYTwWGToT4iB7uItvFzXz4gUYLeYhaakvyKMmhGMTStndN6GlmF0cNumiNmHG2feYonPdsVu1qAny4VY9vs3EIe9zgLlZJLvBwmVPOHG4_BYkBfiXVUwnvevmv2b9GBkt0GP3Z333KsHg_0G00)](https://www.planttext.com/?text=ROun3i8m34Ltdy8RKwKawW7A0RgLAMAmg0E5AebYTwWGToT4iB7uItvFzXz4gUYLeYhaakvyKMmhGMTStndN6GlmF0cNumiNmHG2feYonPdsVu1qAny4VY9vs3EIe9zgLlZJLvBwmVPOHG4_BYkBfiXVUwnvevmv2b9GBkt0GP3Z333KsHg_0G00)

See similar pseudo-remark here:
- #1437

_If that can help,_
Regards,
Th.

**Comment by gmuellerinform** [comment]
Thanks, it works! Maybe add a bigger info box in the documentation?
