### ISSUE TITLE
Wrong component is highlighted on hover for svginteractive

### ISSUE THREAD

**Issue by rubikscuber** [plantuml/plantuml#1713]
**Describe the bug**
Hovering does not work as expected for this diagram:

```
@startuml test
!pragma svginteractive true
component rcm {
    class scf
    class sc
    sc->scf
}
class r
class cs
r -> cs
cs->scf
sc->r
@enduml
```

If class r is clicked - everything is highlighted correctly, but if class r is simply hovered, the scf class is highlighted instead of the direct neighbour sc.

The bug only occurs on hover for some of the components

related to #910 

**To Reproduce**

1. Render diagram as svg
2. open in browser
3.  hover over class r

**Expected behavior**
Only neighbours and the respective links should be highlighted

**Screenshots**
<img width="243" alt="interacive_hover_bug" src="https://github.com/plantuml/plantuml/assets/28889693/56b60006-faad-4ac2-bc74-a7df3bf47de2">

**Desktop:**
Browser: firefox, chrome, edge

**Comment by kirchsth** [comment]
I think it has the same problem which I found, but maybe you want to check if following issue contains a possible solution for you.
https://forum.plantuml.net/18112/is-possible-add-border-based-svg-interactive-mode-like-below
BR Helmut

**Comment by rubikscuber** [comment]
I am not sure about the problem you described, but I think the one I listed could be solved by making the xpath stricter in this file [svg/onmouseinteractivefooter.js](https://github.com/plantuml/plantuml/blob/7755ae5be4a38f1aaf98ff775ae7b46039fe367d/svg/onmouseinteractivefooter.js#L19) (line 19 and 23) 

so I suggest using   `[id=elem_${N2}]` instead of `[id^=elem_${N2}]`
