### ISSUE TITLE
Nested boxes for sequence diagrams

### ISSUE THREAD

**Issue by dellagustin** [plantuml/plantuml#172]
http://forum.plantuml.net/4957/why-not-to-support-nested-boxes-in-sequence-diagrams?show=4957#q4957

**Comment by sjfloat** [comment]
This is probably the only obstacle to my adopting plantuml as my general purpose diagramming tool.

**Comment by arnaudroques** [comment]
Since everyone seems to need this, [we have started to work on it.](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvKhAhr1GIixFBSZFIyqhKU9IK02B59Sc6G8vG500r9gPd5cGc5UYa0WKISrB0Qf0KcU4gIu9eGv8AO1e1o03w080)
This is really a first release, you can only have 1 nested level now. And this will probably only work with teoz engine.

```
@startuml
!pragma teoz true
box "component"
  box "sub1"
    participant a
  endbox
  box "sub2"
    participant b
  endbox
end box
@enduml
```

There are probably a lot of issues, it's only a first step

**Comment by The-Lum** [comment]
Hello @matgnt,

>Can you point us to the commit of this feature?

Here is the link: 
- d36de19c9984e13cdbc8000160c55d668295b1b1

>What is the minimum version I need for this?

This is included on:
- [v1.2022.0](https://github.com/plantuml/plantuml/releases/tag/v1.2022.0)
- and on all new [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot)

_If that can help,_
Regards.

**Comment by aidatgunes** [comment]
> Since everyone seems to need this, [we have started to work on it.](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvKhAhr1GIixFBSZFIyqhKU9IK02B59Sc6G8vG500r9gPd5cGc5UYa0WKISrB0Qf0KcU4gIu9eGv8AO1e1o03w080) This is really a first release, you can only have 1 nested level now. And this will probably only work with teoz engine.
> 
> ```
> @startuml
> !pragma teoz true
> box "component"
>   box "sub1"
>     participant a
>   endbox
>   box "sub2"
>     participant b
>   endbox
> end box
> @enduml
> ```
> 
> There are probably a lot of issues, it's only a first step

It actually works on multi-level if you put a return char, "\n", at the end of the middle box title.
```
@startuml
!pragma teoz true
box "component"
  box "sub1\n\n"
    participant a
    box "subsub1"
      participant suba
    end box
  endbox
  box "sub2"
    participant b
  endbox
end box
@enduml
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @dellagustin  for the report.
- Thanks PlantUML team for your work.

Regards.
