### ISSUE TITLE
Supporting ER diagrams

### ISSUE THREAD

**Issue by RovingSea** [plantuml/plantuml#1739]
The ER diagram case currently displayed on the official website, in my opinion, is UML, and it is not a true ER diagram.

For example, I hope to be able to complete the drawing of the following image through syntax:

![image](https://github.com/plantuml/plantuml/assets/69103691/58bd8035-90cd-4d02-af4a-989a3b9962a6)

It seems that [the syntax of the er diagram displayed on the official website](https://plantuml.com/zh/ie-diagram) cannot be completed.

Looking forward to a reply and suggestions.

**Comment by The-Lum** [comment]
_FYI, see also new Chen notation here:_
- #945
- #1718

**Comment by RovingSea** [comment]
This information is very useful to me, thanks.

**Comment by RovingSea** [comment]
> _FYI, see also new Chen notation here:_
> 
> * [Chen Notation for ER-diagrams #945](https://github.com/plantuml/plantuml/issues/945)
> * [Implement Chen Notation for ER-diagrams #1718](https://github.com/plantuml/plantuml/pull/1718)

This information is very useful to me, thanks.

**Comment by jacobmbarnard** [comment]
I'm up to date on apt package manager with PlantUML (AFAIK). I'm running version 1:1.2018.13+ds-2. Should this diagram be available in this version? Can't seem to get PlantUML to recognize it.

**Comment by RovingSea** [comment]
> I'm up to date on apt package manager with PlantUML (AFAIK). I'm running version 1:1.2018.13+ds-2. Should this diagram be available in this version? Can't seem to get PlantUML to recognize it.

I'm afraid that won't be possible. You can try updating to the latest version.

**Comment by The-Lum** [comment]
Hi @jacobmbarnard, @RovingSea,

Chen Notation for ER-diagrams is available since [V1.2024.4 _(April 2024)_](https://github.com/plantuml/plantuml/releases/tag/v1.2024.4)

FYI now the latest version is the [V1.2024.7](https://github.com/plantuml/plantuml/releases/tag/v1.2024.7).

Regards,
Th.

**Comment by jacobmbarnard** [comment]
Thanks! I guess Ubuntu Universe (maintaining the APT package) only has up thru 1.2018 version. That seems quite out of date. Does anyone know how to contribute to the APT package repo? I'm not super available to help at the moment, but if it's easy enough to update the jar or something, I could do that from time to time.
