### ISSUE TITLE
nwdiag : Group line is not visible

### ISSUE THREAD

**Issue by jcralbino** [plantuml/plantuml#1755]
**Describe the bug**
when using a group in nwdiag the line is not drawn

using this code:
````
@startuml
<style>
nwdiagDiagram {
  group {
    BackGroundColor yellow
    LineColor red
    LineThickness 2.0
  }
}
</style>
nwdiag {
  network DMZ {
      address = "y.x.x.x/24"
      web01 [address = "y.x.x.1"];
      web02 [address = "y.x.x.2"];
  }

   network Internal {
    web01;
    web02;
    db01 [address = "w.w.w.z", shape = database];
  } 

    group {
    description = "long group label";
    web01;
    web02;
    db01;
  }
}
@enduml
`````
Generates this image:
![image](https://github.com/plantuml/plantuml/assets/44149262/6a9dded2-ac16-497b-99cc-2f6e62632e51)

The group in yellow is not having a line surrounding it. 
This is even more imporant if the BackGroundColor  is set to white

**To Reproduce**

1. Go to Plantuml online server
2. upload the code above

**Expected behavior**
the line surrounding the yellow rectangle should be visible

**Screenshots**

**Comment by The-Lum** [comment]
Hello @jcralbino,

Thanks for the report, but that is already requested.

Duplicate of #1226

**Comment by The-Lum** [comment]
Duplicate of #1226

**Comment by jcralbino** [comment]
thanks for the feedback. i will close this one then.
