### ISSUE TITLE
<< style >> breaks multiline activities

### ISSUE THREAD

**Issue by gaspardpetit** [plantuml/plantuml#1762]
**Describe the bug**
Activities can be described on multiple lines, for example:

```
@startuml
:hello
world!!!;
@enduml
```

However, multiline actitivies do not work when a `<< style >>` is provided.

**To Reproduce**

1. Observe that this example results in a multi-line activity: https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuRBAICt9oUSgpo_AIL5KLBJcSaZDIm5A0000
2. Observe that this example results in a styled activity: https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuR8fBgdCIRNZIamkoIpBBAbqoKnCBqhCLQZcKb3GIqaipaXD2GQf00a0WKzcNYg4RmBartBLSjdeGqsmiL50LczdP-MHcfEJhn2UNvIJegYeQCtba9gN0hGJ0000
3. Observe that this example results in a syntax error: https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuR8fBgdCIRNZIamkoIpBBAbqoKnCBqhCLQZcKb3GIqaipaXD2GQf00a0WKzcNYg4RmBartBLSjdeGqsmiL50LczdP-MHcfEJhn2UNvIJegYeQCtba9gN0hGJ0000 

**Expected behavior**
From the following example, I was expecting to have a multiline styled activity:
```
@startuml
<style>
activityDiagram {
  .dashedStyle {
    LineStyle 4
  }
}
</style>
<< dashedStyle >>:Hello 
World!!!;
@enduml
```

**Comment by The-Lum** [comment]
Hi @gaspardpetit,

Here is the good usage of stereotype with multi-line activity:
```puml
@startuml
<style>
activityDiagram {
  .dashedStyle {
    LineStyle 4
  }
}
</style>
:Hello 
World!!!;<<dashedStyle>>
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuR8fBgdCIRNZIamkoIpBBAbqoKnCBqhCLQZcKb3GIqaipaXD2GQf00ieAFXavgL2-2P0VYrNBPUDFjG4Au_Kd9ny1Qxm_AAS54L5HMiR6oJzTdPS3gbvAK0h0G00)](https://www.planttext.com/?text=SoWkIImgAStDuR8fBgdCIRNZIamkoIpBBAbqoKnCBqhCLQZcKb3GIqaipaXD2GQf00ieAFXavgL2-2P0VYrNBPUDFjG4Au_Kd9ny1Qxm_AAS54L5HMiR6oJzTdPS3gbvAK0h0G00) 

_Enjoy,_
Regards,
Th.

**Comment by The-Lum** [comment]
_[Just for the record,]_ See also ref. here:
- https://github.com/plantuml/plantuml/issues/1534
