### ISSUE TITLE
Stereotype won't be hidden with "hide stereotype"

### ISSUE THREAD

**Issue by boessu** [plantuml/plantuml#1768]
**Describe the bug**
The stereotypes won't be hidden with `hide stereotype` always if there is a stereotype style defined.

**To Reproduce**
The following code
```
@startuml

hide stereotype

rectangle foo <<boo>> {
	rectangle bar <<boo>>
}

@enduml
```
produces in the version 1.2024.3 the following output
![image](https://github.com/plantuml/plantuml/assets/2807976/5e75e2a6-6566-47c6-8631-c81726ae2a6d)

The same code produces in version 1.2024.5beta1 (online at the moment) the following output:
![image](https://github.com/plantuml/plantuml/assets/2807976/1498b0c0-6fc4-4ef8-95ad-46bc8f4c7f50)

**Expected behavior**
In my point of view, what version 1.2024.3 produces is the expected behaviour (hide all stereotypes, no matter how the rectangle is used).

**additional context**
The problem only occurs if the element has no sprite symbol (e.g. `rectangle <$icon> foo <<boo>> {...}` doesn't have that problem). Altough it is possible that there are now plantuml-stdlib's with a bit unexpected visual behaviours in some situations (I noted the problem in the edgy lib).

**Comment by The-Lum** [comment]
Hello @boessu, and all,

See also similar remark or request here:
- https://forum.plantuml.net/18876/hide-stereotype-does-not-hide-all-stereotypes-class-diagram
- https://forum.plantuml.net/18581/unable-to-hide-stereotype-when-using-puml-online-server
- https://github.com/plantuml/plantuml/issues/1254#issuecomment-1968106963

On the same topic:
- https://forum.plantuml.net/12721/cannot-hide-specific-stereotype-multiple-stereotypes-used
- https://github.com/plantuml/plantuml/issues/1453
- https://github.com/plantuml/plantuml/issues/1254
- https://github.com/plantuml/plantuml/issues/785

PR on this same topic:
- https://github.com/plantuml/plantuml/issues/1580
- https://github.com/plantuml/plantuml/issues/1587
- https://github.com/plantuml/plantuml/issues/1735


_[FYI @travkin79]_

Regards,
Th.

**Comment by travkin79** [comment]
Thanks for the report @boessu and thanks for the hint @The-Lum,
I think, that's a regression coming from one of my last PRs #1587 and #1736.
I'll check this case, too, and will try to fix it in an additional PR.
