### ISSUE TITLE
Use graphviz-java instead of relying on an external dot installation

### ISSUE THREAD

**Issue by cosminpolifronie** [plantuml/plantuml#177]
Hello. It would be nice if the plantuml jar would use the graphviz-java library instead on relying on an external Graphviz/dot installation.

**Comment by arnaudroques** [comment]
I think that https://github.com/nidi3/graphviz-java also relies on GraphViz and is not a pure java solution. So using it will not change the need for an external Graphviz/dot installation.

**Comment by cosminpolifronie** [comment]
Oh, I didn't know that.

**Comment by nidi3** [comment]
Author here. graphviz-java can use either https://github.com/mdaines/viz.js or a native graphviz installation. So in fact, it can be used as a pure java solution.

**Comment by Woodham** [comment]
This would be great and make e.g. deploying a plantuml server much easier in environments where it's difficult to install graphviz natively.
