### ISSUE TITLE
[teoz] [bug] [sequence] Group becomes too wide when containing activations 

### ISSUE THREAD

**Issue by gustav-b** [plantuml/plantuml#1789]
**Describe the bug**
Using teoz, if a group contains messages without activation, the group gets a reasonable size with some horizontal padding around the lifelines (see `Group 1` below). But if the messages have activation, the group gets some unmotivated extra padding on the right side of the lifeline (see `Group 2` below).

This is with `v1.2024.5beta5`.

**To Reproduce**
Render the following sequence diagram to png:
```puml
@startuml
!pragma teoz true

group #ffa Group 1
    Particpant_A -> Particpant_B
    Particpant_A <- Particpant_B
end

group #ffa Group 2
    Particpant_A -> Particpant_B++
    Particpant_A <- Particpant_B--
end
@enduml
```

**Expected behavior**
`Group 2` should have about the same width as `Group 1`.

**Screenshots**
![teoz-wide-group-activation](https://github.com/plantuml/plantuml/assets/368219/ef23b954-e175-4a9b-9051-d2f9cae24626)

**Comment by The-Lum** [comment]
_[Just for the record]_

See similar report issue here:
- https://forum.plantuml.net/18627/sequence-diagram-group-wide-containing-activations-using

Regards,
Th.

**Comment by jimnelson372** [comment]
I tested all my working diagrams (those I've used during all my recent changes to groupings, arrows and timeline events) and they all seem to behave correctly still, with the 2 line change I mentioned that generates the last diagram in my previous comment.  However, if the # of active levels increases on B, the group isn't growing accordingly.   So, it still needs a little more analysis and testing.

**Comment by jimnelson372** [comment]
In my testing I fixed the right side of the group to account for the width of activation levels in the final lifeline it must enclose.   Compare Group 3 with Group 3b in the following diagram:

![testgroup_003](https://github.com/plantuml/plantuml/assets/66284321/dfa9e115-f66f-4808-9c3c-534417935544)

This looks correct to me.   The group's width with size accordingly, now.  As seen in Group 3c, the left side doesn't need further adjustment for activation levels > 1 since the activation level only adds to the right, not to the left.

I would appreciate any feedback on if this is how everyone would expect the group sizing to work.  I do not have the historical background to know how Teoz sizing was intended to be different from Puma.   Puma, as I noted, uses the sides of the Participant Header box to determine where the group's left and right sides should be, so the levels of activation are not a concern since there is so much space to move into on the left side.   

Regards,

Jim Nelson

**Comment by arnaudroques** [comment]
> I would appreciate any feedback on if this is how everyone would expect the group sizing to work. I do not have the historical background to know how Teoz sizing was intended to be different from Puma. Puma, as I noted, uses the sides of the Participant Header box to determine where the group's left and right sides should be, so the levels of activation are not a concern since there is so much space to move into on the left side.

From my perspective, this approach is perfectly fine. 

We do not expect the exact same results between Teoz and Puma. For Puma, we expect the results to be consistent with the syntax and for the code to be as clean and logical as possible.

So you've done an excellent job!

Thanks again for your contribution.

**Comment by gustav-b** [comment]
Thanks for your thorough work on this issue @jimnelson372!

From my viewpoint (as a simple user of PlantUML) this looks correct and just like what I would expect given the inputs in your scripts.

**Comment by jimnelson372** [comment]
While I was going to hold this fix to include with another grouping issue fix (#1097), I determined that I may not have a solution to that one right away so I should go ahead with the pull request on this one.   When double checking my min and max positions for the active timeline levels, I realized that to stay consistent with the margins and padding, I need to add the extra half width of the active level to the left side, when it is active.   Though I do like seeing the perfect alignment with the non-active level cases in my example, here is how the consistent version would look:

![testall_043](https://github.com/plantuml/plantuml/assets/66284321/593cb014-0c74-4a68-9e50-7dd72da5cd34)

Notice how with this change the left side of Group 1 is slightly further left than that of Group 2, and the right side of Group 2 is slightly further right than Group 1.   But also notice the padding around the center lifelines is now consistent.   Activation levels are slightly larger, which causes the result.   

Please share your thoughts.   Though I think unless there are strong objections to my latest adjustment, it is the correct layout.   The only benefit of the version I showed yesterday is that the left side would align perfectly whether there was an activation level or not.   And I think that half width of an active level is generally small enough that everything else that might depend on positioning around a lifeline (such as notes to the left and notes to the right) would not have lacked a padding. 

But again I think my corrected calculation is more consistent with expected group padding and more consistent with the logic of what counts as the left and right sides of the current lifeline.   It is definitely still much better than the current version reported in this issue where there is far too much padding on Groups when there are active levels.

Regards,

Jim N

**Comment by arnaudroques** [comment]
> Please share your thoughts. Though I think unless there are strong objections to my latest adjustment, it is the correct layout

100% agree, this is definitively the correct layout!

**Comment by gustav-b** [comment]
Thanks for all your work on this issue @jimnelson372, closing! 🙏
