### ISSUE TITLE
reduce space between boxes

### ISSUE THREAD

**Issue by mlopezgva** [plantuml/plantuml#179]
Hello!

I'm using the following code:

```plantuml
package Design <<rectangle>> {

	package Documents {
		entity "Order Form"      as OrderForm
		entity "Return Envelope" as returnEnvelope
		entity Sweep {
			* catalogId
			* prize
			letter
			purchasing_data
		}
		entity Gifts {
			* catalogId
		}
		entity Leaflet {
			* leafletId
			* catalogId
			* leafletCode
		}
	}
}

```

which produces this image (cut off, as is the above code):

![image](https://user-images.githubusercontent.com/996070/54294975-78852e00-45b2-11e9-8529-db47ae101a29.png)

Is it possible to reduce the vertical gap? It's utterly unnecessary and makes the image higher than really necessary.

Thanks.

**Comment by arnaudroques** [comment]
It sounds like http://forum.plantuml.net/7564/class-diagrams-rendering-changed-images-arrows-unexpectedly

Are you using GraphViz 2.40 ?
If you are, you have to downgrade to version 2.38

**Comment by mlopezgva** [comment]
Yes, 2.40.1-2.

I'll check how to/if I can downgrade without compile. :wink: 

Thank you.

**Comment by mlopezgva** [comment]
Tried on another computer with 2.38 (Debian Squeeze instead of Mint 19) and it renders far better.

Thank you.
