### ISSUE TITLE
display text and image on the right corner of a rectangle

### ISSUE THREAD

**Issue by rUser75** [plantuml/plantuml#1796]
I've used a rectangle and skinparan to draw a subnet 

![image](https://github.com/plantuml/plantuml/assets/75304000/c9520d0f-af96-4f93-83bd-039c695ec2a4)

The text "my Subnet" and the sprite is drawn away drawn starting from the left corner.
I would like to put them on the right corner like this 

![image](https://github.com/plantuml/plantuml/assets/75304000/6e697d46-499e-4aaf-9fa8-eaf9b25e4cdb)

there is already a way to do this or is it not possible?
If not I think that this could be a good enhancement 

Thank you.

**Comment by The-Lum** [comment]
Hi @rUser75 

See similar request here _(with tests on `center`, but same request for `right`)_:
- https://github.com/plantuml/plantuml/issues/1640

Regards,
Th.

**Comment by The-Lum** [comment]
Here is the corresponding example for the wanted feature _(similar to #1640)_:
```puml
@startuml
hide stereotype
<style>
.r {
  HorizontalAlignment right
}
.green {
  FontColor green
}
.red {
  FontColor red
}
</style>

rectangle "a\na a" as rect1 <<r>> <<green>>
rectangle "b\nb b" as rect2 <<r>> <<red>>{
  rectangle rec
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/NO_12i8m44Jl-Ogb7r3HSmWLGVo8NbAxf85q8vlrKCL_TrEaYfTbcNdCC5qHptAVavdYY5046RCiDpIso9BGcPRXQG0kcUCZa_XqJ37GZ2J0CKnYNgODZ4WhTbRab5DcMBLgCev_bYfgsDsdmJ1UnLD828tloODlm1UewXwiPUVqhd7E_R93JmCC6tlOMCrthbP-OVsqiaCQTUiR)](https://www.planttext.com/?text=NO_12i8m44Jl-Ogb7r3HSmWLGVo8NbAxf85q8vlrKCL_TrEaYfTbcNdCC5qHptAVavdYY5046RCiDpIso9BGcPRXQG0kcUCZa_XqJ37GZ2J0CKnYNgODZ4WhTbRab5DcMBLgCev_bYfgsDsdmJ1UnLD828tloODlm1UewXwiPUVqhd7E_R93JmCC6tlOMCrthbP-OVsqiaCQTUiR) 

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @rUser75 

Here is a possible workaround _(but not really good....: using `\r` and  `\t`)_:
```puml
@startuml
rectangle "\ra\na a\n\t\t\t\t\t\t\t\tmySubnet  <:sunny:>" as rect2 {
  rectangle AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIfAJIv9p4lFILLGYYbAZCbBL00ICIMeCBSok3GfBxL4GS76ghWqBw_Ioav98R5O0QJPIA6QIq41OOmZIO2hbiiXDIy5w180)](https://www.planttext.com/?text=SoWkIImgAStDuIfAJIv9p4lFILLGYYbAZCbBL00ICIMeCBSok3GfBxL4GS76ghWqBw_Ioav98R5O0QJPIA6QIq41OOmZIO2hbiiXDIy5w180)

Regards,
Th.

**Comment by rUser75** [comment]
thank you for replay but it doen't works fine 
see the below example

```
@startuml
!include <awslib/AWSCommon>
!include <awslib/Compute/all.puml>


hide stereotype
<style>
.r {
  HorizontalAlignment right
}
.red{
  FontColor green
}

</style>


rectangle "b b b" as rect2 <<r>> <<red>>{
EC2(ec2,ec2,ec2)  
}
@enduml
```

![image](https://github.com/plantuml/plantuml/assets/75304000/fccfb584-e94e-4837-82a2-3e09d2226cc9)

the "b b b" text is always on the left

**Comment by The-Lum** [comment]
Yes it is normal...
It is currently only a wanted feature or a example for the corresponding issue.

Regards,
Th.

**Comment by rUser75** [comment]
> Yes it is normal... It is currently only a wanted feature or a example for the corresponding issue.
> 
> Regards, Th.

both.
