### ISSUE TITLE
Provide ANTLR4 grammar for the PlantUML source files

### ISSUE THREAD

**Issue by lennartj** [plantuml/plantuml#18]
I think it would be much simpler to parsing and validating plantUML files if there was a .g4 file containing the grammar for them (unless I have simply been unable to find one). 
This has quite a few advantages:
1. Defining exactly which options and syntactic structure are valid is clear and simple.
2. Validating syntactically correct input files is trivial, since a Lexer and Parser can be built from the grammar file. This is nice also to create unit tests for builder-style structures.
3. Building listeners to handle the effects of parsing source files comes out of the box and are simple patterns.

**Comment by thetric** [comment]
You should probably send an e-mail to the author (plantuml at gmail dot com).
He might need about one week or so to answer.

**Comment by arnaudroques** [comment]
Since PlantUML is based on regular expression, it's very hard to do.
Sorry about that!
