### ISSUE TITLE
Allow `scale max` on JSON and YAML diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1801]
## Context
Observed on:
- #1726
- #1727
- 27dd0bc

## Wanted feature
- Could you allow `scale max` on JSON and YAML diagram?

### ✔️ on Deployment
```puml
@startuml
scale max 200*200
[a] -> b
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIfEJin9LSXDh50mCZ3G0cAkwCHO1LqxXIGkXzIy590I0000)](https://www.planttext.com/?text=SoWkIImgAStDuIfEJin9LSXDh50mCZ3G0cAkwCHO1LqxXIGkXzIy590I0000) 

### :x: on JSON or YAML diag.
```puml
@startjson
scale max 200*200
{
   "fruit":"Apple",
   "size":"Large",
   "color": ["Red", "Green"]
}
@endjson
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgoIhEp-CgJaxCILN8JQnGC38mq09Yhcek1GK5fRIYqimI9IibnuA2d5Gb7R1OSMPLAb389x4e7IQKd9-JNwHafH2j59IQegIZeEHUb9gQfnJBLSlba9gN0hO20000)](https://www.planttext.com/?text=SoWkIImgoIhEp-CgJaxCILN8JQnGC38mq09Yhcek1GK5fRIYqimI9IibnuA2d5Gb7R1OSMPLAb389x4e7IQKd9-JNwHafH2j59IQegIZeEHUb9gQfnJBLSlba9gN0hO20000) 

- Why the diagram is so big?

Regards,
Th.

**Comment by arnaudroques** [comment]
The scale feature should be working now
