### ISSUE TITLE
Extend @@@format to support more formats

### ISSUE THREAD

**Issue by cricalix** [plantuml/plantuml#1810]
**Is your feature request related to a problem? Please describe.**
The existing `@@@format` support only extends to PNG and SVG. I have a use case where it'd be nice to request ATXT or UTXT.

**Describe the solution you'd like**
`@@@format` support gets extended to cover as many of the command-line formats as possible.

**Describe alternatives you've considered**
None I can think of.

**Additional context**
I presume the minimal change is in Pipe.java, but I'm not sure if there are any other considerations; I'm not familiar with the codebase.

**Comment by cricalix** [comment]
Thank you @The-Lum  :)

**Comment by The-Lum** [comment]
Hi Plantuml team,

- Perhaps it will be good to have some other formats (`preproc`, ...).

_To debate..._

Regards,
Th.
