### ISSUE TITLE
[Style][WBS] Change (arrow) line color of a specific branch

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1812]
## Context
Same request as:
- #1440

But for **WBS**.

## Wanted feature
- Could you allow a specific (arrow) line color of a specific branch, on WBS diag.?

## Not working example _(tested on V1.2025.5)_

```puml
@startwbs
<style>
.b * {
  LineColor blue
  Arrow {
    LineColor blue
  }
}
.r * {
  LineColor red
  Arrow {
    LineColor red
  }
}
</style>

* Root
** Blue <<b>>
*** B1
*** B2
** Red <<r>>
*** R1
@endwbs
```
>[![](https://www.planttext.com/api/plantuml/svg/TO-n2eGm38RtF4Nc3eetb-BfwjGti3J3GJ6GLaGEtzrukfrEuS_7b_2tkOnIbf31vh8cSb05DFW5nE4pKS-91KEQIHTl4Lv-w0Pki44bVwfGV3HFTeYslfw3GSzSm1Ziz2vQ6vpJfB4vn-jWdg8YkP1leAKfQeaT)](https://www.planttext.com/?text=TO-n2eGm38RtF4Nc3eetb-BfwjGti3J3GJ6GLaGEtzrukfrEuS_7b_2tkOnIbf31vh8cSb05DFW5nE4pKS-91KEQIHTl4Lv-w0Pki44bVwfGV3HFTeYslfw3GSzSm1Ziz2vQ6vpJfB4vn-jWdg8YkP1leAKfQeaT) 

Pseudo related issue:
- https://forum.plantuml.net/18990/hide-entities-in-wbs-diagram

Regards,
Th.

**Comment by The-Lum** [comment]
See also related issue/request:
- https://forum.plantuml.net/14886/wbs-linecolor-cascade-bug

**Comment by arnaudroques** [comment]
Thanks!

This should be fixed in last snapshot

**Comment by The-Lum** [comment]
Hi,

_[Just for the record]_
Here is the corresponding commit:
- 72718a3

_Thanks @arnaudroques,_
Regards,
Th.
