### ISSUE TITLE
More configurable location for "dot.exe"

### ISSUE THREAD

**Issue by sharrop** [plantuml/plantuml#182]
Hi,

I understand from http://plantuml.com/graphviz-dot that PlantUML looks for "dot.exe":
Windows :
* Firstly in: ''c:\Program Files\Graphviz*\bin\dot.exe''
* Then in: ''c:\Program Files (x86)\Graphviz*\bin\dot.exe''

However in a typical "corporate laptop" both locations are admin-locked. Could it be possible to use an environment variable or cmd-line flag, or "Third: Look in the current directory" - to locate the "dot.exe" executable?

**Comment by arnaudroques** [comment]
You can set up the variable GRAPHVIZ_DOT to any .exe location.
(see http://forum.plantuml.net/7656/change-path-for-graphviz )
We will update the documentation : we agree that this is not enough documented

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @sharrop for the report.
- Thanks PlantUML team for your work.

Regards.
