### ISSUE TITLE
2024.5 breaks https includeurl

### ISSUE THREAD

**Issue by sigma67** [plantuml/plantuml#1820]
**Describe the bug**
2024.5 breaks includeurl with our internal URL in a proxy setup

**To Reproduce**

set 

```
!includeurl https://internal.gitlab.int/common/third-party/cicon-plantuml-sprites/-/raw/v1.0/sprites/file.puml
```

**Expected behavior**
No error, as is the case until 2024.4

**Screenshots**
```
b'ERROR\n2\nCannot open URL\nSome diagram description contains errors\n'
```

**Desktop (please complete the following information):**

- OS: Ubuntu 22
- Version 2024.5

**Additional context**
Our default security Profile is LEGACY.

The error goes away when setting `export PLANTUML_SECURITY_PROFILE=UNSECURE`.

Setting `export PLANTUML_ALLOWLIST_URL=https://internal.gitlab.int` has no effect by itself

This is most likely related to the recent refactoring changes in `SURL.java`.

**Comment by sigma67** [comment]
Good to hear.

1. We are using sphinxcontrib-plantuml. Our plantuml wrapper in PATH looks something like this

```sh
!/bin/sh
if [ -n "${JAVA_HOME}" ] && [ -x "${JAVA_HOME}/bin/java" ] ; then
    JAVA="${JAVA_HOME}/bin/java"
elif [ -x /usr/bin/java ] ; then
    JAVA=/usr/bin/java
else
    echo Cannot find JVM
    exit 1
fi

$JAVA -DPLANTUML_LIMIT_SIZE=16384 -jar /opt/plantuml/plantuml.jar ${@} -vmargs -Xms256m -Xmx4096m -XX:MaxPermSize=512m
```

2. Yes, it's a Gitlab Runner that is contacting the Gitlab instance to grab the sprites repo. However, no authentication or proxy should be needed as they are on the same network

**Comment by arnaudroques** [comment]
The latest [snapshot 1.2024.6beta4](https://github.com/plantuml/plantuml/releases/tag/snapshot) should now take your `PLANTUML_ALLOWLIST_URL` setting into account.

Please let us know if it's working for you!

**Comment by sigma67** [comment]
Hi, thanks for providing the fix and snapshot, we just tested it. Unfortunately it doesn't seem to work. Setup below.

Prior to 2024.5 we didn't need to set this variable. Any idea why this is the case now? Our setup hasn't changed when updating plantuml.

```
    - export plantuml_allowlist_url=https://internal.gitlab.int
    - curl --silent --show-error --location --output /opt/plantuml/plantuml.jar "https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.jar"
    - printenv
    - plantuml -v
```

Output:
```
$printenv
...
plantuml_allowlist_url=https://gitlab.vi.vector.int/
...
$plantuml -v
(0.001 - 242 Mo) 234 Mo - SecurityProfile LEGACY
(0.005 - 242 Mo) 234 Mo - PlantUML Version 1.2024.6beta4
(0.005 - 242 Mo) 234 Mo - GraphicsEnvironment.isHeadless() true
(0.005 - 242 Mo) 234 Mo - Forcing -Djava.awt.headless=true
(0.005 - 242 Mo) 234 Mo - java.awt.headless set as true
(0.005 - 242 Mo) 234 Mo - Forcing resource load on OpenJdk
(0.125 - 242 Mo) 228 Mo - Found 0 files
No diagram found
$ (run sphinx-build)
sphinx.errors.SphinxWarning: /path/to/file.rst:5:error while running plantuml
b'ERROR\n2\nCannot open URL\nSome diagram description contains errors\n'
```
(line 5 is where our test puml file is included - the only puml file in this test setup)

**Comment by sigma67** [comment]
> Yes, sorry for the inconvenience. This change was implemented due to security warnings. It's designed to enhance security, especially when the server is accessible from the Internet, and prevent users from scanning your local network using PlantUML as a proxy.

That's completely fair and understandable. I'm just trying to understand how the default behavior has changed. I couldn't find any documentation on it in the changelog (unsure if I missed something). 

Is the intent that starting with 2024.5 *any* external URL has to be whitelisted in the LEGACY and INTERNET security profiles?

In that case the documentation would need to be updated as well: https://plantuml.com/security

LEGACY:
> Right now, this mode is the default mode for PlantUML. It gives the same result as older PlantUML versions: full access to local files and full access to URL. 

INTERNET:
> However, all URLs on port 80 or 443 are accessible. If you need some specific ports (like 8080 for some Intranet server), you can also use allowlists.

**Comment by sigma67** [comment]
I have uppercased the variable now and it fixed the issue 🥳

I was under the impression that JAVA doesn't care about the casing, apparently that is not so.

**Comment by sigma67** [comment]
@arnaudroques sorry but I have to report some strangeness here. I just tried out the new version 1.2024.6.

As expected, it works when setting the environment variable using `export PLANTUML_ALLOWLIST_URL=url`.

However, it doesn't not work when using java to pass the environment variables:

```
$JAVA -DPLANTUML_LIMIT_SIZE=16384 -DPLANTUML_ALLOWLIST_URL=url -jar /opt/plantuml/plantuml.jar ${@} -vmargs -Xms256m -Xmx4096m -XX:MaxPermSize=512m
```

Any idea? Here's the output of `plantuml --version` using the above parameters:

```
PlantUML version 1.2024.6 (Sat Jul 06 11:14:38 CEST 2024)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: ANSI_X3.4-1968
Language: en
Country: US
 
PLANTUML_LIMIT_SIZE: 16384

Dot version: dot - graphviz version 2.43.0 (0)
Installation seems OK. File generation OK
```

As you can set the limit size parameter is recognized, but the allowlist is not.

**Comment by sigma67** [comment]
Is this expected behavior? I'm a bit surprised that it doesn't work for this env variable as it does for others

**Comment by trothwell** [comment]
@sigma67 `-D{key}={var}` are `system properties` not `environment variables.`

[System.getProperties()](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/System.html#getProperties()) vs [System.getenv()](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/System.html#getenv())
