### ISSUE TITLE
Note right moves preceding arrow up (teoz)

### ISSUE THREAD

**Issue by jbuhacoff** [plantuml/plantuml#183]
This diagram is fine:

```
a -> b
& b-> c
note right: ok
```

But in this diagram you can see the note has caused the b -> c arrow to move up above the a -> b arrow which is not expected:

```
a -> b: some text to stretch the diagram out horizontally
& b -> c
note right: oops
```

**Comment by swmatisa** [comment]
Hello,
On my server and on the main PlantUml server, iti is working well (version 1.2019.03)

[http://www.plantuml.com/plantuml/png/5St13S8m30NGkwVuNBYnG0-egxYjbKHAuihvaQ3JGmTuUkkW1cUhyZX3KrFG_09ZcYXURsmBXZS3xKFGCHZ6FOFPS1HDeGq-YUnHBk_KMh_on7RRNRhJ42LbBd0_XwpMZ__s0m00](url)

**Comment by jbuhacoff** [comment]
My plantuml.jar version was too old. It is fixed in the recent versions. Thanks!
