### ISSUE TITLE
[ELK][Smetana] Allow `Fontcolor` style on arrows

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1834]
Hello @arnaudroques, and all contributors,
_[FYI @kirchsth]_

For traceability about:
- #1833

And to continue:
- #1702
- https://forum.plantuml.net/18723/elk-layout-ignores-arrow-skinparam

Here is a minimal not working example _(Thanks to @kirchsth)_ about `Fontcolor`:

```puml
@startuml
'!pragma layout smetana
'!pragma layout elk

<style>
.a {
  LineThickness 3
  Linecolor red
  Linestyle 3-2

  Fontcolor green
}
</style>

card a
card b
a -> b <<a>> : Should be green
@enduml
```

| With GraphViz ✔️ | With Smetana ❌ | With ELK  ❌ |
|:--------:|:--------:|:---:|
| [![](https://www.planttext.com/api/plantuml/svg/POwx2i9054Jx-nLZPHK5qycofBAoqn-usLoIa7t8FeeW_hl1R6Srp65cc2vbZhauIyV3A_Be69RNK3AIayoU_xZOXKYbl5hHT6Ay2RZFNfxJR1OlAQ6jn0GR8g8CrVywQ9iBRU0MVDu3OnJnz25rhgDaE0xWNNfYD1ezb6AjSSLZ2iLkN6gn4pzi_xy0)](https://www.planttext.com/?text=POwx2i9054Jx-nLZPHK5qycofBAoqn-usLoIa7t8FeeW_hl1R6Srp65cc2vbZhauIyV3A_Be69RNK3AIayoU_xZOXKYbl5hHT6Ay2RZFNfxJR1OlAQ6jn0GR8g8CrVywQ9iBRU0MVDu3OnJnz25rhgDaE0xWNNfYD1ezb6AjSSLZ2iLkN6gn4pzi_xy0) | [![](https://www.planttext.com/api/plantuml/svg/NOwx2i9054Jx-nLZPHK5qycofBAoqn-usLoIa7t8FeeW_hl1R6Krp65cc2vbZhauIuTNvD4nBA-XP2GdcJtJyO-BNOXKogiLJIV6cu3xxEKvpMRnaXBQIaom8IBAKFslWxQvq0PkmUSzC4OHJnzIvpfAXkC0tgKdHgFHGodM6bSyfb3ingKME_73TlyB)](https://www.planttext.com/?text=NOwx2i9054Jx-nLZPHK5qycofBAoqn-usLoIa7t8FeeW_hl1R6Krp65cc2vbZhauIuTNvD4nBA-XP2GdcJtJyO-BNOXKogiLJIV6cu3xxEKvpMRnaXBQIaom8IBAKFslWxQvq0PkmUSzC4OHJnzIvpfAXkC0tgKdHgFHGodM6bSyfb3ingKME_73TlyB) | [![](https://www.planttext.com/api/plantuml/svg/NOuz2iCm58FtTmhr06cXsOencJfrQoxmOZ-I4CSk_Xb2wTqR6a-TX3uaeIvbZhciZawloEFASBo5af5MoUpv7ujRY5JAcnDDPyQRWCVifPzcitX92Mqb9hWG4SLM_-kWRQwqWtlm-GYCKSJJXzIbZfBXQC673CHeD0OenLhZXkSKYjkvr68dtkxllm00)](https://www.planttext.com/?text=NOuz2iCm58FtTmhr06cXsOencJfrQoxmOZ-I4CSk_Xb2wTqR6a-TX3uaeIvbZhciZawloEFASBo5af5MoUpv7ujRY5JAcnDDPyQRWCVifPzcitX92Mqb9hWG4SLM_-kWRQwqWtlm-GYCKSJJXzIbZfBXQC673CHeD0OenLhZXkSKYjkvr68dtkxllm00) |

Observed on `1.2024.5`.

Regards,
Th.

**Comment by arnaudroques** [comment]
Many thanks for this very simple example!
This should be fixed with last snapshot.

**Comment by kirchsth** [comment]
Thank you for the fix,
I tested it with elk/smetana and "combined tags" too and it is working.
BR Helmut

```plantuml
@startuml
!theme C4_united from <C4/themes>
!include <C4/C4_Component>
!pragma layout elk
'!pragma layout smetana

' $textColor is working
AddRelTag("DEF", $textColor = "#green", $lineColor = "#blue", $lineStyle = DottedLine(), $lineThickness=7)
' combined stereotypes/tags are working too
AddRelTag("DEF2",$lineColor = "#red")

Component(A, "A")
Component(B, "B")
A -[#orange,dashed]-> B
' WithoutPropertyHeader()
AddProperty("PropC1", "ValueC1")
AddProperty("PropC2", "ValueC2")
Rel(A, B, "Te<$person>st", $tags="DEF2+DEF")

SHOW_LEGEND()
@enduml
`` 

![image](https://github.com/plantuml/plantuml/assets/21959385/3af7750c-6b71-4911-bade-4972b973e3f1)
