### ISSUE TITLE
!foreach $key from %get_json_keys() is not found by %json_key_exists(), but works for element access + fix

### ISSUE THREAD

**Issue by vic123** [plantuml/plantuml#1846]
'ver. plantuml-1.2024.5.jar
```puml
@startuml
!$json = {"050": "aaa"}
!log $json
!foreach $key in %get_json_keys($json)
	!log %json_key_exists($json, $key) /' false?? '/
	!log $json[$key]
	!$key = $key + ""
	!log %json_key_exists($json, $key) /' true!! '/
	!log $json[$key]	
!endfor
@enduml
```

Output:
```
[Log] {"050":"aaa"}
[Log] 0
[Log] aaa
[Log] 1
[Log] aaa
```

**Comment by vic123** [comment]
>java --version
java 11.0.20 2023-07-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)

**Comment by The-Lum** [comment]
Hello @vic123,

- Thanks @vic123 for the report.

This is now fixed.
That will be on the [snapshot (~v1.2024.6beta12)](https://github.com/plantuml/plantuml/releases/tag/snapshot) and next release.

Regards.
