### ISSUE TITLE
namespaceSeparator = none breaks class association

### ISSUE THREAD

**Issue by voronind** [plantuml/plantuml#185]
Setting namespaceSeparator to **none** show unwanted apoint16737 class on diagram
```plantuml
@startuml

set namespaceSeparator none

class Student {
  Name
}
Student "0..*" -- "1..*" Course
(Student, Course) . Enrollment

class Enrollment {
  drop()
  cancel()
}
@enduml
```

**Comment by arnaudroques** [comment]
Thanks for the report.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @voronind for the report.
- Thanks PlantUML team for your work.

Regards.
