### ISSUE TITLE
Stereotype with plain circle: text should be elided

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#1854]
Look at this diagram:
![](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuSh8J4bLICqjAAbKo4tDJKejAkPApaaiBbRmIynDJGakIIrApI-fB4XLW00R6urW7MKtDtDp0mDDXAoT7LINStvEVb5gYdDcKN8EM0-cBhZQW9p4p3oOIXIrMDKWR8EeKK2ntY4rBmNe7m00)

Source:
```plantuml
@startuml
hide empty members
class NamedStereotype       <<(S,#FF7700)Stereotype>>
class ColoredCircle         <<(S,#FF7700)>>
class PlainCircle           <<(S)>>
class PlainCircleStereotype <<(S) Stereotype>>
@enduml
```
- OK: The top two nodes (that specify color) don't have text `(S)` in the chevrons
- NOK: The bottom two nodes have text `(S)` in the chevrons. This text is superfluous since it's expressed in the circle

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀

This is now fixed, on [v1.2024.8](https://github.com/plantuml/plantuml/releases/tag/v1.2024.8)
- Thanks @VladimirAlexiev for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
