### ISSUE TITLE
[Sprite][SVG] Manage more SVG functionalities for text

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1855]
Hello PlantUML team,

## Context
To follow:
- #1066

## Wanted feature
Could you manage more SVG functionalities _(on [`SvgNanoParser.java`](https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/emoji/SvgNanoParser.java))_:
- unit of `font-size`;
- search of `font-size`, `fill`, ... on `style` attribut;
- manage `group` for text;
- `font-family` _(and fallback for PNG output, if the font is not present)_.

### Unit of `font-size`
```puml
@startuml
sprite AA <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
  <text x="0" y="14" fill="red" font-size="14pt">42</text>
</svg>
title <$AA>
@enduml
```
Ref.:
- https://developer.mozilla.org/en-US/docs/Web/CSS/length#absolute_length_units

### Search of `font-size`, `fill`, ... on `style` attribut
```puml
@startuml
sprite AA <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20">
  <text x="0" y="14" fill="red" style="font-size:15px;font-family:Consolas;fill:#FF0000;">42</text>
</svg>
title <$AA>
@enduml
```

### `group` for text
```puml
@startuml
sprite AA <svg xmlns="http://www.w3.org/2000/svg" width="90" height="90">
  <g fill="#FF0000" font-size="30pt">
    <text x="5" y="30">A</text>
    <text x="30" y="30">B</text>
  </g>
</svg>
title <$AA>
@enduml
```

### `font-family` for text
```puml
@startuml
sprite AA <svg xmlns="http://www.w3.org/2000/svg" width="190" height="190" viewBox="0 0 190 190">
  <text x="0" y="40" fill="red" font-size="35px" font-family="Consolas">abc 123</text>
</svg>
title <$AA>
@enduml
```

_Thanks for your works,_
Regards,
Th.

**Comment by arnaudroques** [comment]
Thanks for the examples!
This should be working in last snapshot
(except for unit conversion between pt and px which is not implemented)

**Comment by The-Lum** [comment]
Hi @arnaudroques 

Thanks for this quickly implementation.

Th.
