### ISSUE TITLE
`listopeniconic` statement ignores `-nometadata` flag

### ISSUE THREAD

**Issue by mattbishop** [plantuml/plantuml#186]
I have this plantuml script:
```
@startuml
listopeniconic
@enduml
```

And I am using this command to generate diagrams from the jar:

`java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -jar /Users/matt/Projects/plantuml/plantuml.jar -nbthread auto -nometadata -tsvg -progress -r doc/**.puml`

This command autogenerates svg files for every .puml file in a doc structure. All the other plantuml files generate SVG _without_ metadata, but the `listopeniconic` one still generates the metadata, like this:

```
<svg...
<!--
@startuml
listopeniconic
@enduml

PlantUML version 1.2019.03(Sun Mar 10 04:04:44 PDT 2019)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 1.8.0_202-b05
Operating System: Mac OS X
OS Version: 10.13.6
Default Encoding: UTF-8
Language: en
Country: US
--></g></svg>
```

**Comment by arnaudroques** [comment]
Thanks for the report.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you!

**Comment by mattbishop** [comment]
👍 Works for me now.
