### ISSUE TITLE
activity diagram not work

### ISSUE THREAD

**Issue by kraymond37** [plantuml/plantuml#1871]
**Describe the bug**
When I add specific note at specific position, the activity diagram does not work.

**To Reproduce**
It could be reproduced by [PlantUML Web Server](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)

1. this does not work
```puml
@startuml

start

if (true) then (YES)
    	:do something;
endif

note right
    title
    ----
    content
end note

stop

@enduml
```
2. this can work
comment the `----`
```puml
@startuml

start

if (true) then (YES)
    	:do something;
endif

note right
    title
'    ----
    content
end note

stop

@enduml
```
3. this can work
move the note to before if statement
```puml
@startuml

start

note right
    title
    ----
    content
end note

if (true) then (YES)
    	:do something;
endif

stop

@enduml

```
**Expected behavior**
All work.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot)
