### ISSUE TITLE
`repeat` starting point is in wrong swimlane

### ISSUE THREAD

**Issue by brunofacca** [plantuml/plantuml#1874]
**Describe the bug**
In an activity diagram, the element that is the label of a `repeat` block is displayed in the wrong swimlane.

**To Reproduce**
```
@startuml
|Lane1|
:Foo;
|Lane2|
repeat :Bar (wrong lane);
|Lane1|
:Baz;
repeat while (Success) is (No)
  |Lane2|
  :Qux;
@enduml
```

**Expected behavior**
The `Bar` element should appear on `Lane2`, but it appears on `Lane1`.

**Screenshots**
![SoWkIImgAStDuQhnISnBDQpXidBBpxU6y8ngk8fI2r8JInIid1AB53JAY_BpqXLoW3AQrd3rGAagQvYwyepCd5G5ZU3IvEJKuc9DXSnY1Gs_V4qk1GMeWK2MLM1fXJMNGsfU2j1Q0000](https://github.com/user-attachments/assets/9c1aa5ec-dd25-4ab1-81d2-ae6fbabf2473)

**Desktop (please complete the following information):**
Irrelevant. The diagram was rendered on the "Online server" at https://plantuml.com/

**Comment by arnaudroques** [comment]
This is fixed in last snapshot https://github.com/plantuml/plantuml/releases/tag/snapshot

**Comment by brunofacca** [comment]
Thank you!
