### ISSUE TITLE
Generate a <svg:title> tag when generating Svg

### ISSUE THREAD

**Issue by Scal-Human** [plantuml/plantuml#1877]
Hi and thanks for all the job on PlantUml.

A suggestion as I noticed that generated svg's do not have a <[svg:title](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title)> nor <[svg:desc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc)> tag while this could serve as metadata and help people with disabilities as mentioned in [EPub3 Accessibility Guidelines](https://idpf.github.io/a11y-guidelines/).
This could be used for instance to create a table of figures when generating an ePub containing generated diagrams.
Note the svg:title is a simple tag while [the metadata in Svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata) is far more complex.

The content of the title tag could be the same as given in the title of the diagram.
Concerning the description (less obvious there), it could come from the header, footer or legend or top note.

A fan

**Comment by arnaudroques** [comment]
SVG title is implemented in last snapshot https://github.com/plantuml/plantuml/releases/tag/snapshot
(Nothing about description right now)
Tell us if it's not working for you!

**Comment by Scal-Human** [comment]
@arnaudroques Great, thank you.
I usually do not use prereleases and wait for release (by Chocolatey in the case of PlantUml) but I will see if I can test this.
Title is a great step, description is tricky and maybe less important (imho).
Nice job on Plantuml ;-)

**Comment by Scal-Human** [comment]
@arnaudroques I verified with the snapshot you point to.
```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    contentStyleType="text/css" height="636px" preserveAspectRatio="none"
    style="width:722px;height:636px;background:#666666;" version="1.1" viewBox="0 0 722 636"
    width="722px" zoomAndPan="magnify">
    <title>ArchiMate-Project-Dependencies</title>
  ...
``` 
Well done, thanks again.

**Comment by The-Lum** [comment]
See also other improvement here:
- #2292

**Comment by Scal-Human** [comment]
@The-Lum  Thanks for linking the two issues.

**Comment by The-Lum** [comment]
But preprocessing seems to not work on SVG option!
