### ISSUE TITLE
aggregations reversed

### ISSUE THREAD

**Issue by sevku** [plantuml/plantuml#188]
I've been using `*--|>` (together with `skinparam linetype ortho`) and they cause the relations to be reversed.

sample code:
```
@startuml
skinparam linetype ortho


class Forum
class Topic
class User
class Discussion
class Contribution

Forum *--|> Topic
Forum *--|> User
Topic *--|> Discussion
Discussion *--|> Contribution
User <|--|> Contribution

@enduml
```

![plantuml](https://user-images.githubusercontent.com/23403917/55821467-e105f300-5afd-11e9-9f90-b5e11a48d6a4.png)

**Comment by swmatisa** [comment]
With 1.2019.04 the direction is OK , but the result is also not correct
I see the same as @sevku  with version 1.2019.05beta 10.

There is also a space between the diamond and the arrow

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @sevku for the report.
- Thanks @swmatisa for the complement.
- Thanks PlantUML team for your work.

>[![](https://www.planttext.com/api/plantuml/svg/PP2n2i8m48RtFCKjGYkqsEfKH0gAgujkBcaRCTWcvN8f27ruqt9WnPi-ll_k3wHq995yrmhtqgQNA3jejL7qxXLOfASLecwbSt2sw3lcg-rrpNnp2XbFsjNUEMqDYwCrXBhoD2anDy0wISO3DopDt3Dh5eksBtBsKpnTmdxy3yJ3MWhPfGeRWseWt8Sf84lpJRvDiqgHtDrDL7j4PGW6XTCZ1QoOeZWMfJ9D-A0F)](https://www.planttext.com/?text=PP2n2i8m48RtFCKjGYkqsEfKH0gAgujkBcaRCTWcvN8f27ruqt9WnPi-ll_k3wHq995yrmhtqgQNA3jejL7qxXLOfASLecwbSt2sw3lcg-rrpNnp2XbFsjNUEMqDYwCrXBhoD2anDy0wISO3DopDt3Dh5eksBtBsKpnTmdxy3yJ3MWhPfGeRWseWt8Sf84lpJRvDiqgHtDrDL7j4PGW6XTCZ1QoOeZWMfJ9D-A0F)

Regards.
