### ISSUE TITLE
Make latest release point to a general release

### ISSUE THREAD

**Issue by iainelder** [plantuml/plantuml#1881]
My [PlantUML installer script](https://github.com/iainelder/dotfiles/blob/master/programs/plantuml/install.bash) gets the latest release from GitHub.

It requests this URL: `https://api.github.com/repos/plantuml/plantuml/releases/latest`

Today that points to [1.2024.7beta5](https://github.com/plantuml/plantuml/releases/tag/1.2024.7beta5), which doesn't contain `plantuml.jar`. [Today's CI run failed](https://github.com/iainelder/dotfiles/actions/runs/10572252416/job/29302973796).

The latest general release would be [v1.2024.06](https://github.com/plantuml/plantuml/releases/tag/v1.2024.6).

Please apply the latest label to the latest general release, never a beta or pre-release version.

**Comment by The-Lum** [comment]
Hi @iainelder,
Thanks for the report.

FYI I just change **manually**:
- the state of [`1.2024.7beta5: fix: repeat in wrong swimlane`](https://github.com/plantuml/plantuml/releases/tag/1.2024.7beta5)  from `Latest` to nothing :x:
- the state of [`v1.2024.6`](https://github.com/plantuml/plantuml/releases/tag/v1.2024.6) to `Latest` ✔️ 

_We must investigate and design the native output deliveries... with #1868._

Regards,
Th.

_[FYI @arnaudroques, @asm0dey]_

**Comment by asm0dey** [comment]
Sorry, I wasn't aware of such a convention in the project, I take the responsibility for the accident, I should knew better. 
Saying that, I also expected for such things to be discovered during the review of a PR.
