### ISSUE TITLE
Error occurred after text compression using Sprite

### ISSUE THREAD

**Issue by Contentsearch** [plantuml/plantuml#1891]
Reproduction steps：
1. use command get sprite "java -jar plantuml.jar -encodesprite 8z  pay.png" and result is flow:
```shell
sprite $wxpay [320x77/8z] {
xTo9Skow2eLXMF2__oFViRFLaTs4RT8varUDPt2L_1N8M4vYRyoTEtVktBdZBYaY9BcRzNF75Radr4AyeyXN2LaZDrwHGl2Eif5mEyiTpogru1sFx2UioDsw
ZRZz-UF-9oY-yOCa_VKTAREuqFPuolfnYERwpXCPq-ARzx10zaZ0jdPeNVW8yEr-3hBpG4xvve20RNwz5IRuyL_fk_rYxAUycbxvnKi_hpo04v7yRZ_0HdxA
w-akJ_9dF-cNfpVWYveS-pbauJVZcxTmGfWPwCdFmUljRzdM97E_04tyF0THetknrtuGLYxUjONmJtaG-ra4uMVP-sFYDwWzxrG0_jfFuFNJLtoL-2Xa-l6j
HWT-CTIh0uIzzake6jz-m2_01tu-rvDL1bZX1sZbTE_oAgiNTPQ0r5asee5VJBSzZrInDME5d_YKuzDZ60SrXlk1dmPwox_Wyyel2pz8-m4_m0P-msrFrLDO
WApmSyXV3qftB-fYxbTFEEhjc7iqr7iawkbBPlROYH8U6vC_py8wL04_uvSplnXCUnvVdML5FjeupTZZpxsZlK_qCtuEH558GFMUvODPETfl8S2fNoo_sFru
yajU9sP-2SJr_Ky7ecX-U5F_DLYl5i5gYzZkGZ_ZvypyubXXwipA7ja_Z7wrUSIJNsxtoREVgepySkXtsg5Hw2tsBRfIVii8j5zpSV-hvcS_ykRCRyzPRwhp
p8uhvRTUFS7tQwxvELNYkBI9d-SU7TfJnJKTltYrX21_BSzXkqPlyMDVMjZ4Jtd8vmuDRtzbgillw6w6MyB9-EUGrlRht_5E1TXt--a9AhoueEcNm6bXc6cT
HWUvaJ_xUPN--wp0jwNvmI-7Vd7rNRbefzE-_tHBIUp7zdvrVW5QjIJ8lIWTOkQNtlX0tFS3uElvOZ_Gj86VGtJAp-3OrC3GBngZOjilgFqCulZuI7tsYogd
MqPhAuiu-WN4fUVlYZUactu2el9RPyoDqRSToBQg7S0O-aNZ_-kLhGDIwVTn3XDpl_gxfq0Tlu2uD3-lD3Q-dXyGgxRyEP-LG6E_-eSKV47KVWuC_NJbY50l
-cZv9Qpuy_yZiB5V_Su3D8V2XBXqVh3IrwjtpS2-z4km9B_Ppu6DJqq_1nf-bOxgrkq_VdtpMs_r_hnNWMe_NYOxW8klzblhxFfvZH7Jd-BO_DRDUJaXplrC
aDiPSzDFGDVFeYX0PJz-sIy0VUcNEWkaLO3-mPVMzpD0NJ-zvF3ydTX5lzLfjL_OITR6MNmyrU9h-WbT-7uvYYxuUQn66_ZLW950MCDlyFry7clvvRDVWAyF
HGE_6X2GpVpUNu3g-F7ifmHylI6F_6f0jxVwAUUnXf-lXVgQ0GNfa6-il_It-bdaDDxnYrK90iWFIRS0VR-V099txNyhy-xj-05hKP3FeqA2p_sEUlYZ2FLE
FyzHmZf-0N4u7m7YP8QP-mMhxXo0U9-VnOoluwTFGW-PX3oyBSpzF3On5OArdo3ilO3MyVEp7afW-yevzzFfqF8GzT_oMyj-8w2r_0HPyArQdBp_BhnKCGis
_TmL0DPAZ9ktxjyZdxRH3D38Jy0gisEKcstf9zQGzJR0iAwVso7WczVB-jFhsCh6yt9ZfEyNrev6WqljTnfjfjBm_5IatBw80ZNxrzsAZCUOyFclCC-l-nFz
XhL6nNT7evtlJenQzqusepEzEpx2kwD5TE7lXzs9uzxcKlm_ajTsTqP_5EUEZuQwEpuRI-w4hCgTEtVktBdpRm
}
```
2. Applying Sprite to UML :
```plantuml
@startuml
sprite $wxpay [320x77/8z] {
xTo9Skow2eLXMF2__oFViRFLaTs4RT8varUDPt2L_1N8M4vYRyoTEtVktBdZBYaY9BcRzNF75Radr4AyeyXN2LaZDrwHGl2Eif5mEyiTpogru1sFx2UioDsw
ZRZz-UF-9oY-yOCa_VKTAREuqFPuolfnYERwpXCPq-ARzx10zaZ0jdPeNVW8yEr-3hBpG4xvve20RNwz5IRuyL_fk_rYxAUycbxvnKi_hpo04v7yRZ_0HdxA
w-akJ_9dF-cNfpVWYveS-pbauJVZcxTmGfWPwCdFmUljRzdM97E_04tyF0THetknrtuGLYxUjONmJtaG-ra4uMVP-sFYDwWzxrG0_jfFuFNJLtoL-2Xa-l6j
HWT-CTIh0uIzzake6jz-m2_01tu-rvDL1bZX1sZbTE_oAgiNTPQ0r5asee5VJBSzZrInDME5d_YKuzDZ60SrXlk1dmPwox_Wyyel2pz8-m4_m0P-msrFrLDO
WApmSyXV3qftB-fYxbTFEEhjc7iqr7iawkbBPlROYH8U6vC_py8wL04_uvSplnXCUnvVdML5FjeupTZZpxsZlK_qCtuEH558GFMUvODPETfl8S2fNoo_sFru
yajU9sP-2SJr_Ky7ecX-U5F_DLYl5i5gYzZkGZ_ZvypyubXXwipA7ja_Z7wrUSIJNsxtoREVgepySkXtsg5Hw2tsBRfIVii8j5zpSV-hvcS_ykRCRyzPRwhp
p8uhvRTUFS7tQwxvELNYkBI9d-SU7TfJnJKTltYrX21_BSzXkqPlyMDVMjZ4Jtd8vmuDRtzbgillw6w6MyB9-EUGrlRht_5E1TXt--a9AhoueEcNm6bXc6cT
HWUvaJ_xUPN--wp0jwNvmI-7Vd7rNRbefzE-_tHBIUp7zdvrVW5QjIJ8lIWTOkQNtlX0tFS3uElvOZ_Gj86VGtJAp-3OrC3GBngZOjilgFqCulZuI7tsYogd
MqPhAuiu-WN4fUVlYZUactu2el9RPyoDqRSToBQg7S0O-aNZ_-kLhGDIwVTn3XDpl_gxfq0Tlu2uD3-lD3Q-dXyGgxRyEP-LG6E_-eSKV47KVWuC_NJbY50l
-cZv9Qpuy_yZiB5V_Su3D8V2XBXqVh3IrwjtpS2-z4km9B_Ppu6DJqq_1nf-bOxgrkq_VdtpMs_r_hnNWMe_NYOxW8klzblhxFfvZH7Jd-BO_DRDUJaXplrC
aDiPSzDFGDVFeYX0PJz-sIy0VUcNEWkaLO3-mPVMzpD0NJ-zvF3ydTX5lzLfjL_OITR6MNmyrU9h-WbT-7uvYYxuUQn66_ZLW950MCDlyFry7clvvRDVWAyF
HGE_6X2GpVpUNu3g-F7ifmHylI6F_6f0jxVwAUUnXf-lXVgQ0GNfa6-il_It-bdaDDxnYrK90iWFIRS0VR-V099txNyhy-xj-05hKP3FeqA2p_sEUlYZ2FLE
FyzHmZf-0N4u7m7YP8QP-mMhxXo0U9-VnOoluwTFGW-PX3oyBSpzF3On5OArdo3ilO3MyVEp7afW-yevzzFfqF8GzT_oMyj-8w2r_0HPyArQdBp_BhnKCGis
_TmL0DPAZ9ktxjyZdxRH3D38Jy0gisEKcstf9zQGzJR0iAwVso7WczVB-jFhsCh6yt9ZfEyNrev6WqljTnfjfjBm_5IatBw80ZNxrzsAZCUOyFclCC-l-nFz
XhL6nNT7evtlJenQzqusepEzEpx2kwD5TE7lXzs9uzxcKlm_ajTsTqP_5EUEZuQwEpuRI-w4hCgTEtVktBdpRm
}
a-->b:<$wxpay>
@enduml
```
3. PlantUML Text Encoding(Simple HEX format):
```shell
 https://www.plantuml.com/plantuml/svg/~h73707269746520247778706179205B3332307837372F387A5D207B0A78546F39536B6F7732654C584D46325F5F6F46566952464C6154733452543876617255445074324C5F314E384D34765952796F544574566B7442645A42596159394263527A4E463735526164723441796579584E324C615A44727748476C32456966356D45796954706F677275317346783255696F4473770A5A525A7A2D55462D396F592D794F43615F564B5441524575714650756F6C666E5945527770584350712D41527A7831307A615A306A6450654E5657387945722D336842704734787676653230524E777A35495275794C5F666B5F725978415579636278766E4B695F68706F3034763779525A5F30486478410A772D616B4A5F3964462D634E66705657597665532D706261754A565A6378546D47665750774364466D556C6A527A644D3937455F303474794630544865746B6E727475474C5978556A4F4E6D4A7461472D726134754D56502D7346594477577A787247305F6A664675464E4A4C746F4C2D3258612D6C366A0A4857542D435449683075497A7A616B65366A7A2D6D325F303174752D7276444C31625A5831735A6254455F6F4167694E5450513072356173656535564A42537A5A72496E444D4535645F594B757A445A36305372586C6B31646D50776F785F577979656C32707A382D6D345F6D30502D6D737246724C444F0A5741706D5379585633716674422D6659786254464545686A6337697172376961776B6242506C524F594838553676435F707938774C30345F757653706C6E5843556E7656644D4C35466A657570545A5A7078735A6C4B5F71437475454835353847464D55764F44504554666C385332664E6F6F5F734672750A79616A553973502D32534A725F4B79376563582D5535465F444C596C35693567597A5A6B475A5F5A767970797562585877697041376A615F5A3777725553494A4E7378746F52455667657079536B5874736735487732747342526649566969386A357A7053562D687663535F796B524352797A50527768700A70387568765254554653377451777876454C4E596B424939642D53553754664A6E4A4B546C7459725832315F42537A586B71506C794D44564D6A5A344A746438766D754452747A6267696C6C773677364D7942392D455547726C5268745F3545315458742D2D613941686F756545634E6D366258633663540A48575576614A5F7855504E2D2D7770306A774E766D492D37566437724E526265667A452D5F744842495570377A647672565735516A494A386C4957544F6B514E746C58307446533375456C764F5A5F476A38365647744A41702D334F72433347426E675A4F6A696C67467143756C5A7549377473596F67640A4D715068417569752D574E346655566C595A556163747532656C395250796F44715253546F4251673753304F2D614E5A5F2D6B4C684744497756546E335844706C5F6778667130546C75327544332D6C4433512D645879476778527945502D4C4736455F2D65534B5634374B565775435F4E4A625935306C0A2D635A7639517075795F795A694235565F53753344385632584258715668334972776A747053322D7A346B6D39425F50707536444A71715F316E662D624F7867726B715F566474704D735F725F686E4E574D655F4E594F7857386B6C7A626C68784666765A48374A642D424F5F445244554A6158706C72430A61446950537A44464744564665595830504A7A2D734979305655634E45576B614C4F332D6D50564D7A7044304E4A2D7A76463379645458356C7A4C666A4C5F4F495452364D4E6D79725539682D5762542D3775765959787555516E36365F5A4C573935304D43446C7946727937636C7676524456574179460A4847455F36583247705670554E7533672D463769666D48796C4936465F3666306A7856774155556E58662D6C5856675130474E6661362D696C5F49742D6264614444786E59724B39306957464952533056522D5630393974784E7968792D786A2D3035684B50334665714132705F7345556C595A32464C450A46797A486D5A662D304E3475376D3759503851502D6D4D6878586F3055392D566E4F6F6C7577544647572D5058336F794253707A46334F6E354F4172646F33696C4F334D79564570376166572D7965767A7A4666714638477A545F6F4D796A2D387732725F304850794172516442705F42686E4B434769730A5F546D4C304450415A396B74786A795A64785248334433384A7930676973454B63737466397A51477A4A523069417756736F3757637A56422D6A4668734368367974395A6645794E7265763657716C6A546E666A666A426D5F35496174427738305A4E78727A73415A43554F7946636C43432D6C2D6E467A0A58684C366E4E54376576746C4A656E517A7175736570457A457078326B7744355445376C587A7339757A78634B6C6D5F616A54735471505F354555455A75517745707552492D7734684367544574566B74426470526D0A7D0A612D2D3E623A3C2477787061793E0A
``` 
4. open the url error:

```shell
PlantUML 1.2024.7beta5
[From string (line 2) ]
 
@startuml
sprite $wxpay [320x77/8z] {
```
![image](https://github.com/user-attachments/assets/fc83a561-524b-4357-ad1d-3231bb51b09f)

**How did the error in the fourth step occur? Why can the image be displayed normally without using Sprite?**

**Comment by The-Lum** [comment]
Hello @Contentsearch 

It seems that is due to the length of the request and to the `hex encoding` source, could you use `normal-legacy` ([Deflate-base64](https://plantuml.com/text-encoding)) encoding, as:
```puml
@startuml
sprite $wxpay [320x77/8z] {
xTo9Skow2eLXMF2__oFViRFLaTs4RT8varUDPt2L_1N8M4vYRyoTEtVktBdZBYaY9BcRzNF75Radr4AyeyXN2LaZDrwHGl2Eif5mEyiTpogru1sFx2UioDsw
ZRZz-UF-9oY-yOCa_VKTAREuqFPuolfnYERwpXCPq-ARzx10zaZ0jdPeNVW8yEr-3hBpG4xvve20RNwz5IRuyL_fk_rYxAUycbxvnKi_hpo04v7yRZ_0HdxA
w-akJ_9dF-cNfpVWYveS-pbauJVZcxTmGfWPwCdFmUljRzdM97E_04tyF0THetknrtuGLYxUjONmJtaG-ra4uMVP-sFYDwWzxrG0_jfFuFNJLtoL-2Xa-l6j
HWT-CTIh0uIzzake6jz-m2_01tu-rvDL1bZX1sZbTE_oAgiNTPQ0r5asee5VJBSzZrInDME5d_YKuzDZ60SrXlk1dmPwox_Wyyel2pz8-m4_m0P-msrFrLDO
WApmSyXV3qftB-fYxbTFEEhjc7iqr7iawkbBPlROYH8U6vC_py8wL04_uvSplnXCUnvVdML5FjeupTZZpxsZlK_qCtuEH558GFMUvODPETfl8S2fNoo_sFru
yajU9sP-2SJr_Ky7ecX-U5F_DLYl5i5gYzZkGZ_ZvypyubXXwipA7ja_Z7wrUSIJNsxtoREVgepySkXtsg5Hw2tsBRfIVii8j5zpSV-hvcS_ykRCRyzPRwhp
p8uhvRTUFS7tQwxvELNYkBI9d-SU7TfJnJKTltYrX21_BSzXkqPlyMDVMjZ4Jtd8vmuDRtzbgillw6w6MyB9-EUGrlRht_5E1TXt--a9AhoueEcNm6bXc6cT
HWUvaJ_xUPN--wp0jwNvmI-7Vd7rNRbefzE-_tHBIUp7zdvrVW5QjIJ8lIWTOkQNtlX0tFS3uElvOZ_Gj86VGtJAp-3OrC3GBngZOjilgFqCulZuI7tsYogd
MqPhAuiu-WN4fUVlYZUactu2el9RPyoDqRSToBQg7S0O-aNZ_-kLhGDIwVTn3XDpl_gxfq0Tlu2uD3-lD3Q-dXyGgxRyEP-LG6E_-eSKV47KVWuC_NJbY50l
-cZv9Qpuy_yZiB5V_Su3D8V2XBXqVh3IrwjtpS2-z4km9B_Ppu6DJqq_1nf-bOxgrkq_VdtpMs_r_hnNWMe_NYOxW8klzblhxFfvZH7Jd-BO_DRDUJaXplrC
aDiPSzDFGDVFeYX0PJz-sIy0VUcNEWkaLO3-mPVMzpD0NJ-zvF3ydTX5lzLfjL_OITR6MNmyrU9h-WbT-7uvYYxuUQn66_ZLW950MCDlyFry7clvvRDVWAyF
HGE_6X2GpVpUNu3g-F7ifmHylI6F_6f0jxVwAUUnXf-lXVgQ0GNfa6-il_It-bdaDDxnYrK90iWFIRS0VR-V099txNyhy-xj-05hKP3FeqA2p_sEUlYZ2FLE
FyzHmZf-0N4u7m7YP8QP-mMhxXo0U9-VnOoluwTFGW-PX3oyBSpzF3On5OArdo3ilO3MyVEp7afW-yevzzFfqF8GzT_oMyj-8w2r_0HPyArQdBp_BhnKCGis
_TmL0DPAZ9ktxjyZdxRH3D38Jy0gisEKcstf9zQGzJR0iAwVso7WczVB-jFhsCh6yt9ZfEyNrev6WqljTnfjfjBm_5IatBw80ZNxrzsAZCUOyFclCC-l-nFz
XhL6nNT7evtlJenQzqusepEzEpx2kwD5TE7lXzs9uzxcKlm_ajTsTqP_5EUEZuQwEpuRI-w4hCgTEtVktBdpRm
}
a-->b:<$wxpay>
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/DPNPhgl80KNV_HNteLzBZS5ChUYgZHaCnXWpGnILi04p58EPgwByUuuKvHVMqjxhxsbEntbfqM4QnchEV_snxKEAV_sJeQcTv_yKoBz-_VkmUxteDlr6vsPqLsa8UpMe7DLClUdaUCAQZhvipxG9ZvPmFwsnWtjFcODcbh94YjDObDuEiLIUTT9iF9rnZYEBDjD47hUhXcYbAjXMmPKtz9znEKxgJljLBq_R8N4I0dmLY7qCyEEImk3cdHrb-QhsqgEYYnLd6wAB_GLdX-n7YgG9LMTsRWMXW9KHCAKqQATzNNEQSgoDiBgpO1CM3HpZ_UpZzsjVkri5ow6dJYkFdGHIrsm_7pQGDWOKCnMyhM88mdZDNJ2yqiK8alVkjLeHsjibKriVrGx9xYAlGEeqOvNohldST3zCDJFU_VfXjSQSQc1CJyiziC6anl8MadtKA5WNwg9QXZdt9g2Z522kFbn33rmylQGMdP2qoRcQW9Q6r75UmBZAvl6LHCSfUNaAxC-VolBi9pMowPJdR618Bab6lPFl2fl1-BOGEU4eTunGSynQU-jt66AS8teW0cXFiALiq4wZEfhoun2UXzR5KS1yYra2HRo_F5LHolhDLz-HhzAjUKasSXxnLV2vzG87B6mcTOBBwWweYov-jmRPtMJLEby6Bqc6VKhG3Nulyw9SMLRGrBk_FcHRyGeak7HXzJsSr74vuBJsnSa6j6kCy8Rv_1q1drMXRCQ8hTXFJ996Is2ouW4lhoZQgk7CrobC-6tqNTsmfdtk7INuv0DscsYUFknre-T9SWezg2gXPidW1g1Stox4ZNDnCB6ThHmEWx2Kg-FvgilFpsrV5TEA6qaNC-3wl5SOdN7pq1oF4Ns4FsIZvciZV9U3UvsSZ3aJrdQHdPcyFXL26xTnToo9GF6r4Jdb35dbw4Kp0AbuBlibLzvMoxsYD_VsVXpxQsh0tRSj0BQ1gZThRNN01na_MiuhBuW2u7oLT7_WIRQEGSW-QzqGa1vwZ-PfpIYYPjLb5WMjZmHgjS05scoS1y0ynWkZITqdUTGL-gZVouAIHUVdAUu_sU7-jSlpKYqWj4w57w0uyTFtlD0v4XqRz_BNSRrUUdvubtg0r4eWQCnIa_Kjy3ecaWS4FtlnfJoqq8lC02GpJv15MFli3bPiO6gS0a7kte8JVml2vG8junMp53g0TxAAps7142ULn0RGNHXP2EX8Yhv1oUZZLi-3ImDoQbfHWlQmSBBn_S9ZLu3NO_-CpHS6sJpS9pZ2ihF2Umwj-B67GeF82vMxMgp9bJSo83sWxCY-aKO36Y-7LAvibyYg9WTg7aUKRH0mwPWA_BUbX4rgFXZGsi6T339b6O2iAeCpBs8HCOlQX0_TSxYxrUBH5qiGlZp0BsiSxul_x3WE9cOeijJz8YEiZfX_etLrv20yO_LmrHJ8HRGs18DlBSm7g7nLj5UCT4w5N47LUx2TVR-B2e2YuFEaDAj8EL0XgC_WbQMol7VnU1EfAbHrnwK21mIKACwxXKiCzXfGR7cp6JN_dka1Jeh_8vDMJUMWOd9jam9GrcdXMpwsXUVFok_b7lMKBuAWU_HesJnL2u4TCJsMt86epADZ7-SnwvaAFPWx3fI1JuiGu7mbH2s-gg0H3_PtN0DXeyUVaxJnUNncqW2bihjTj6ewGAyrATa-9s8pxpLEijsvCZ8Z69ZwL9DoUqzp8PAdHWo7givRCFLy-2Q116grd2ubXsSnAHHiZVdAXLzKUrrH5xNKGbPFPsaJgCJQHpATaul_mEeRNIu0WKubXwWqkSxo-7oTaP5tJ_9TfdnGY3BiTBF9hAVmA2AJk93zVKCjJ6jlyhxspq9z9LcUcp8iZWwsKtdv_BzQWzCU_dD80VZz-kiV_qlYxyFVUPVzbFA_)](https://www.planttext.com/?text=DPNPhgl80KNV_HNteLzBZS5ChUYgZHaCnXWpGnILi04p58EPgwByUuuKvHVMqjxhxsbEntbfqM4QnchEV_snxKEAV_sJeQcTv_yKoBz-_VkmUxteDlr6vsPqLsa8UpMe7DLClUdaUCAQZhvipxG9ZvPmFwsnWtjFcODcbh94YjDObDuEiLIUTT9iF9rnZYEBDjD47hUhXcYbAjXMmPKtz9znEKxgJljLBq_R8N4I0dmLY7qCyEEImk3cdHrb-QhsqgEYYnLd6wAB_GLdX-n7YgG9LMTsRWMXW9KHCAKqQATzNNEQSgoDiBgpO1CM3HpZ_UpZzsjVkri5ow6dJYkFdGHIrsm_7pQGDWOKCnMyhM88mdZDNJ2yqiK8alVkjLeHsjibKriVrGx9xYAlGEeqOvNohldST3zCDJFU_VfXjSQSQc1CJyiziC6anl8MadtKA5WNwg9QXZdt9g2Z522kFbn33rmylQGMdP2qoRcQW9Q6r75UmBZAvl6LHCSfUNaAxC-VolBi9pMowPJdR618Bab6lPFl2fl1-BOGEU4eTunGSynQU-jt66AS8teW0cXFiALiq4wZEfhoun2UXzR5KS1yYra2HRo_F5LHolhDLz-HhzAjUKasSXxnLV2vzG87B6mcTOBBwWweYov-jmRPtMJLEby6Bqc6VKhG3Nulyw9SMLRGrBk_FcHRyGeak7HXzJsSr74vuBJsnSa6j6kCy8Rv_1q1drMXRCQ8hTXFJ996Is2ouW4lhoZQgk7CrobC-6tqNTsmfdtk7INuv0DscsYUFknre-T9SWezg2gXPidW1g1Stox4ZNDnCB6ThHmEWx2Kg-FvgilFpsrV5TEA6qaNC-3wl5SOdN7pq1oF4Ns4FsIZvciZV9U3UvsSZ3aJrdQHdPcyFXL26xTnToo9GF6r4Jdb35dbw4Kp0AbuBlibLzvMoxsYD_VsVXpxQsh0tRSj0BQ1gZThRNN01na_MiuhBuW2u7oLT7_WIRQEGSW-QzqGa1vwZ-PfpIYYPjLb5WMjZmHgjS05scoS1y0ynWkZITqdUTGL-gZVouAIHUVdAUu_sU7-jSlpKYqWj4w57w0uyTFtlD0v4XqRz_BNSRrUUdvubtg0r4eWQCnIa_Kjy3ecaWS4FtlnfJoqq8lC02GpJv15MFli3bPiO6gS0a7kte8JVml2vG8junMp53g0TxAAps7142ULn0RGNHXP2EX8Yhv1oUZZLi-3ImDoQbfHWlQmSBBn_S9ZLu3NO_-CpHS6sJpS9pZ2ihF2Umwj-B67GeF82vMxMgp9bJSo83sWxCY-aKO36Y-7LAvibyYg9WTg7aUKRH0mwPWA_BUbX4rgFXZGsi6T339b6O2iAeCpBs8HCOlQX0_TSxYxrUBH5qiGlZp0BsiSxul_x3WE9cOeijJz8YEiZfX_etLrv20yO_LmrHJ8HRGs18DlBSm7g7nLj5UCT4w5N47LUx2TVR-B2e2YuFEaDAj8EL0XgC_WbQMol7VnU1EfAbHrnwK21mIKACwxXKiCzXfGR7cp6JN_dka1Jeh_8vDMJUMWOd9jam9GrcdXMpwsXUVFok_b7lMKBuAWU_HesJnL2u4TCJsMt86epADZ7-SnwvaAFPWx3fI1JuiGu7mbH2s-gg0H3_PtN0DXeyUVaxJnUNncqW2bihjTj6ewGAyrATa-9s8pxpLEijsvCZ8Z69ZwL9DoUqzp8PAdHWo7givRCFLy-2Q116grd2ubXsSnAHHiZVdAXLzKUrrH5xNKGbPFPsaJgCJQHpATaul_mEeRNIu0WKubXwWqkSxo-7oTaP5tJ_9TfdnGY3BiTBF9hAVmA2AJk93zVKCjJ6jlyhxspq9z9LcUcp8iZWwsKtdv_BzQWzCU_dD80VZz-kiV_qlYxyFVUPVzbFA_) 
_[Link [here](https://www.planttext.com/?text=DPNPhgl80KNV_HNteLzBZS5ChUYgZHaCnXWpGnILi04p58EPgwByUuuKvHVMqjxhxsbEntbfqM4QnchEV_snxKEAV_sJeQcTv_yKoBz-_VkmUxteDlr6vsPqLsa8UpMe7DLClUdaUCAQZhvipxG9ZvPmFwsnWtjFcODcbh94YjDObDuEiLIUTT9iF9rnZYEBDjD47hUhXcYbAjXMmPKtz9znEKxgJljLBq_R8N4I0dmLY7qCyEEImk3cdHrb-QhsqgEYYnLd6wAB_GLdX-n7YgG9LMTsRWMXW9KHCAKqQATzNNEQSgoDiBgpO1CM3HpZ_UpZzsjVkri5ow6dJYkFdGHIrsm_7pQGDWOKCnMyhM88mdZDNJ2yqiK8alVkjLeHsjibKriVrGx9xYAlGEeqOvNohldST3zCDJFU_VfXjSQSQc1CJyiziC6anl8MadtKA5WNwg9QXZdt9g2Z522kFbn33rmylQGMdP2qoRcQW9Q6r75UmBZAvl6LHCSfUNaAxC-VolBi9pMowPJdR618Bab6lPFl2fl1-BOGEU4eTunGSynQU-jt66AS8teW0cXFiALiq4wZEfhoun2UXzR5KS1yYra2HRo_F5LHolhDLz-HhzAjUKasSXxnLV2vzG87B6mcTOBBwWweYov-jmRPtMJLEby6Bqc6VKhG3Nulyw9SMLRGrBk_FcHRyGeak7HXzJsSr74vuBJsnSa6j6kCy8Rv_1q1drMXRCQ8hTXFJ996Is2ouW4lhoZQgk7CrobC-6tqNTsmfdtk7INuv0DscsYUFknre-T9SWezg2gXPidW1g1Stox4ZNDnCB6ThHmEWx2Kg-FvgilFpsrV5TEA6qaNC-3wl5SOdN7pq1oF4Ns4FsIZvciZV9U3UvsSZ3aJrdQHdPcyFXL26xTnToo9GF6r4Jdb35dbw4Kp0AbuBlibLzvMoxsYD_VsVXpxQsh0tRSj0BQ1gZThRNN01na_MiuhBuW2u7oLT7_WIRQEGSW-QzqGa1vwZ-PfpIYYPjLb5WMjZmHgjS05scoS1y0ynWkZITqdUTGL-gZVouAIHUVdAUu_sU7-jSlpKYqWj4w57w0uyTFtlD0v4XqRz_BNSRrUUdvubtg0r4eWQCnIa_Kjy3ecaWS4FtlnfJoqq8lC02GpJv15MFli3bPiO6gS0a7kte8JVml2vG8junMp53g0TxAAps7142ULn0RGNHXP2EX8Yhv1oUZZLi-3ImDoQbfHWlQmSBBn_S9ZLu3NO_-CpHS6sJpS9pZ2ihF2Umwj-B67GeF82vMxMgp9bJSo83sWxCY-aKO36Y-7LAvibyYg9WTg7aUKRH0mwPWA_BUbX4rgFXZGsi6T339b6O2iAeCpBs8HCOlQX0_TSxYxrUBH5qiGlZp0BsiSxul_x3WE9cOeijJz8YEiZfX_etLrv20yO_LmrHJ8HRGs18DlBSm7g7nLj5UCT4w5N47LUx2TVR-B2e2YuFEaDAj8EL0XgC_WbQMol7VnU1EfAbHrnwK21mIKACwxXKiCzXfGR7cp6JN_dka1Jeh_8vDMJUMWOd9jam9GrcdXMpwsXUVFok_b7lMKBuAWU_HesJnL2u4TCJsMt86epADZ7-SnwvaAFPWx3fI1JuiGu7mbH2s-gg0H3_PtN0DXeyUVaxJnUNncqW2bihjTj6ewGAyrATa-9s8pxpLEijsvCZ8Z69ZwL9DoUqzp8PAdHWo7givRCFLy-2Q116grd2ubXsSnAHHiZVdAXLzKUrrH5xNKGbPFPsaJgCJQHpATaul_mEeRNIu0WKubXwWqkSxo-7oTaP5tJ_9TfdnGY3BiTBF9hAVmA2AJk93zVKCjJ6jlyhxspq9z9LcUcp8iZWwsKtdv_BzQWzCU_dD80VZz-kiV_qlYxyFVUPVzbFA_)]_

_If that can help,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi @Contentsearch 

Maybe don't forget **`@startuml` / `@enduml`**:
- [Link with **`@startuml` / `@enduml`** ](https://www.plantuml.com/plantuml/svg/~h407374617274756D6C0D0A73707269746520247778706179205B3332307837372F387A5D207B0D0A78546F39536B6F7732654C584D46325F5F6F46566952464C6154733452543876617255445074324C5F314E384D34765952796F544574566B7442645A42596159394263527A4E463735526164723441796579584E324C615A44727748476C32456966356D45796954706F677275317346783255696F4473770D0A5A525A7A2D55462D396F592D794F43615F564B5441524575714650756F6C666E5945527770584350712D41527A7831307A615A306A6450654E5657387945722D336842704734787676653230524E777A35495275794C5F666B5F725978415579636278766E4B695F68706F3034763779525A5F30486478410D0A772D616B4A5F3964462D634E66705657597665532D706261754A565A6378546D47665750774364466D556C6A527A644D3937455F303474794630544865746B6E727475474C5978556A4F4E6D4A7461472D726134754D56502D7346594477577A787247305F6A664675464E4A4C746F4C2D3258612D6C366A0D0A4857542D435449683075497A7A616B65366A7A2D6D325F303174752D7276444C31625A5831735A6254455F6F4167694E5450513072356173656535564A42537A5A72496E444D4535645F594B757A445A36305372586C6B31646D50776F785F577979656C32707A382D6D345F6D30502D6D737246724C444F0D0A5741706D5379585633716674422D6659786254464545686A6337697172376961776B6242506C524F594838553676435F707938774C30345F757653706C6E5843556E7656644D4C35466A657570545A5A7078735A6C4B5F71437475454835353847464D55764F44504554666C385332664E6F6F5F734672750D0A79616A553973502D32534A725F4B79376563582D5535465F444C596C35693567597A5A6B475A5F5A767970797562585877697041376A615F5A3777725553494A4E7378746F52455667657079536B5874736735487732747342526649566969386A357A7053562D687663535F796B524352797A50527768700D0A70387568765254554653377451777876454C4E596B424939642D53553754664A6E4A4B546C7459725832315F42537A586B71506C794D44564D6A5A344A746438766D754452747A6267696C6C773677364D7942392D455547726C5268745F3545315458742D2D613941686F756545634E6D366258633663540D0A48575576614A5F7855504E2D2D7770306A774E766D492D37566437724E526265667A452D5F744842495570377A647672565735516A494A386C4957544F6B514E746C58307446533375456C764F5A5F476A38365647744A41702D334F72433347426E675A4F6A696C67467143756C5A7549377473596F67640D0A4D715068417569752D574E346655566C595A556163747532656C395250796F44715253546F4251673753304F2D614E5A5F2D6B4C684744497756546E335844706C5F6778667130546C75327544332D6C4433512D645879476778527945502D4C4736455F2D65534B5634374B565775435F4E4A625935306C0D0A2D635A7639517075795F795A694235565F53753344385632584258715668334972776A747053322D7A346B6D39425F50707536444A71715F316E662D624F7867726B715F566474704D735F725F686E4E574D655F4E594F7857386B6C7A626C68784666765A48374A642D424F5F445244554A6158706C72430D0A61446950537A44464744564665595830504A7A2D734979305655634E45576B614C4F332D6D50564D7A7044304E4A2D7A76463379645458356C7A4C666A4C5F4F495452364D4E6D79725539682D5762542D3775765959787555516E36365F5A4C573935304D43446C7946727937636C7676524456574179460D0A4847455F36583247705670554E7533672D463769666D48796C4936465F3666306A7856774155556E58662D6C5856675130474E6661362D696C5F49742D6264614444786E59724B39306957464952533056522D5630393974784E7968792D786A2D3035684B50334665714132705F7345556C595A32464C450D0A46797A486D5A662D304E3475376D3759503851502D6D4D6878586F3055392D566E4F6F6C7577544647572D5058336F794253707A46334F6E354F4172646F33696C4F334D79564570376166572D7965767A7A4666714638477A545F6F4D796A2D387732725F304850794172516442705F42686E4B434769730D0A5F546D4C304450415A396B74786A795A64785248334433384A7930676973454B63737466397A51477A4A523069417756736F3757637A56422D6A4668734368367974395A6645794E7265763657716C6A546E666A666A426D5F35496174427738305A4E78727A73415A43554F7946636C43432D6C2D6E467A0D0A58684C366E4E54376576746C4A656E517A7175736570457A457078326B7744355445376C587A7339757A78634B6C6D5F616A54735471505F354555455A75517745707552492D7734684367544574566B74426470526D0D0A7D0D0A612D2D3E623A3C2477787061793E0D0A40656E64756D6C)

This is only a test...
_If that can help_
Regards,
Th.
