### ISSUE TITLE
`rectangle` key word will reverse order in `left to right direction` layout

### ISSUE THREAD

**Issue by LY1806620741** [plantuml/plantuml#1892]
**Describe the bug**
`rectangle` key word will reverse order in `left to right direction` layout, what should i do?

**To Reproduce**

1. `vscode` install `Markdown Preview Enhanced
v0.8.13` extension.
1. download `plantuml` Release v1.2024.6 from github
1. download and install [`windows_10_cmake_Release_graphviz-install-12.1.0-win64.exe`](https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/12.1.0/windows_10_cmake_Release_graphviz-install-12.1.0-win64.exe). then config user environment `GRAPHVIZ_DOT = c:\program files\graphviz\bin\dot.exe` 
1. create a markdown file name `**.md`, write the plaintuml example
````markdown
```plaintuml
@startuml
left to right direction
actor "Food Critic" as fc
rectangle Restaurant {
usecase "Eat Food" as UC1
usecase "Pay for Food" as UC2
usecase "Drink" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml
```
````
3. see the preview. and found the image not expect.

**Expected behavior**
expect the same as `https://plantuml.com/zh/guide` page 47 say.
![image](https://github.com/user-attachments/assets/b3e48929-d578-4ba0-9c3d-58bbb9aafb38)

**Screenshots**
in fact, i get this
![image](https://github.com/user-attachments/assets/186502fc-63d4-4072-9a5b-d81a74aaf036)
we can found that element in rectangle was reverse order print.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Microsoft Windows 11 professional
- Browser [e.g. chrome, safari] chrome 128.0.6613.86
- Version [e.g. 22] plaintuml.jar  v1.2024.6

**Smartphone (please complete the following information):**

not need

**Additional context**

**Comment by The-Lum** [comment]
Hello @LY1806620741 

> [!IMPORTANT]  
> FYI: PlantUML does not preserve place of element, it depends a lot of the layout used (Graphviz, Smetana, ELK).

I think it depends of the Graphviz version, see result on `plantext server`:
>[![](https://www.planttext.com/api/plantuml/svg/JOz12i9034NtEKKe2BhemdOlXQfh4Jn0c6RgO9r09XL4lBlJ8jRT9-_daJJ9I6sy3p2mDpH13VtLi0lApe9486UYM1n5EcmrM705KaBlO6fGx0V6CsVDg1GDNp0cTfGOYmCPJcjp_z9k5tAY9_fi_QFLGlSQukqxhk4Dtc5PxcR3BrPBhC6B62kk7gmfdxpUGCEnoqzz0000)](https://www.planttext.com/?text=JOz12i9034NtEKKe2BhemdOlXQfh4Jn0c6RgO9r09XL4lBlJ8jRT9-_daJJ9I6sy3p2mDpH13VtLi0lApe9486UYM1n5EcmrM705KaBlO6fGx0V6CsVDg1GDNp0cTfGOYmCPJcjp_z9k5tAY9_fi_QFLGlSQukqxhk4Dtc5PxcR3BrPBhC6B62kk7gmfdxpUGCEnoqzz0000) 
_[Link [here](https://www.planttext.com/?text=JOz12i9034NtEKKe2BhemdOlXQfh4Jn0c6RgO9r09XL4lBlJ8jRT9-_daJJ9I6sy3p2mDpH13VtLi0lApe9486UYM1n5EcmrM705KaBlO6fGx0V6CsVDg1GDNp0cTfGOYmCPJcjp_z9k5tAY9_fi_QFLGlSQukqxhk4Dtc5PxcR3BrPBhC6B62kk7gmfdxpUGCEnoqzz0000)]_

And FYI plantext used currently this GraphViz version:
- `dot - graphviz version 2.43.0 (0)`

But the issue will be then on normal layout, as:
```puml
@startuml
'left to right direction
actor "Food Critic" as fc
rectangle Restaurant {
usecase "Eat Food" as UC1
usecase "Pay for Food" as UC2
usecase "Drink" as UC3
}
fc --> UC1
fc --> UC2
fc --> UC3
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JO_B2i9034Nt-OfG47NHXUrU2ZxM8lW1OPgfWtK2cLGGyT-T5h7kBZatXwH9Hch3lOTbpzxG13LqLyCsA3iB4e6SYM9n56bnfy62Av0IUWTZWsBNCvuvUmQbQFY28R6Zn5WSo71Sc_gNtMOc9tgYpzO_Mirqho7UlkCQtk0TbkLsClnYDSSQl8YnukB1clB9gpKq7DlyrGS0)](https://www.planttext.com/?text=JO_B2i9034Nt-OfG47NHXUrU2ZxM8lW1OPgfWtK2cLGGyT-T5h7kBZatXwH9Hch3lOTbpzxG13LqLyCsA3iB4e6SYM9n56bnfy62Av0IUWTZWsBNCvuvUmQbQFY28R6Zn5WSo71Sc_gNtMOc9tgYpzO_Mirqho7UlkCQtk0TbkLsClnYDSSQl8YnukB1clB9gpKq7DlyrGS0) 


Regards,
Th.

**Comment by LY1806620741** [comment]
@The-Lum  Okay, thanks for reply, my understanding of ` plantuml` was stuck many years ago. Is there no way we can use keywords to adjust this order?
