### ISSUE TITLE
【can the plantuml support for c/cpp language  in eclipse IDE tool? 】

### ISSUE THREAD

**Issue by piperwei** [plantuml/plantuml#1895]
**【can the plantuml support for c/cpp language  in eclipse IDE tool? 】**

**Comment by The-Lum** [comment]
Hi @piperwei,

- What is your goal?
- Could you precise your question?

If you want to see package architecture from `.c/.cpp` (and` .h/.hpp`), could you have a look on:
- https://github.com/thibaultmarin/hpp2plantuml

_If that can help,_
Regards,
Th.

**Comment by piperwei** [comment]
> Hi @piperwei,
> 
> * What is your goal?
> * Could you precise your question?
> 
> If you want to see package architecture from `.c/.cpp` (and` .h/.hpp`), could you have a look on:
> 
> * https://github.com/thibaultmarin/hpp2plantuml
> 
> _If that can help,_ Regards, Th.

sorry, I'd like to do that :  
I use eclipse-for-cpp IDE to develop my c/c++ project, and  I install plantuml dropin into my eclipse-for-cpp IDE, bu it can't not show any plantuml result  like eclipse-java-IDE does, I'd like to know ,  is the plantuml dropin installed into  cpp-eclips-ide  support c/c++ language?

**Comment by The-Lum** [comment]
Hi @piperwei 

Thanks for those precision.

>  Is the plantuml dropin installed into cpp-eclips-ide support c/c++ language?

Perhaps ask directly your question on:
- https://marketplace.eclipse.org/content/plantuml-plugin#details

Regards,
Th.

**Comment by The-Lum** [comment]
Hi @piperwei 

Perhaps also ask directly on the repo. of this plugin:
- https://github.com/hallvard/plantuml/discussions

Regards,
Th.
