### ISSUE TITLE
Layout challenges: what version do I run

### ISSUE THREAD

**Issue by SashaOv** [plantuml/plantuml#190]
I was trying to lay out this diagram:
```
@startuml
actor user

rectangle Env1 {

  agent set_up
  set_up -down-> process1
  rectangle process1 {
    rectangle Component1
  }
}

user -d-> set_up

cloud Cloud_provider {
  rectangle Env2 {
    rectangle Component2 {

    }
    rectangle Component2_1
    Component2 -d-> Component2_1
  }

  rectangle Env3 {
    rectangle Component3 {
      component TheThing {
        storage Logs
      }
      rectangle process3 {
      }
      process3 -d- TheThing: owns
    }
  }

}


set_up -right--> Component2
Component2 ---> process3
Component2_1 -right-> process3: protocol
Component1 -right-> Component2_1: protocol


@enduml
```

The online version produces [near perfect result](http://www.plantuml.com/plantuml/png/TP4nQyCm48Nt-nNl3tX8ksKmWT2jOtPZP24RR9sHv7Ge_k_LGNLHqXgCEUwz-zv9kiJKXxGjC_KcSS0MRI0ArgJUkzdYmzzF-2O2UcTzGhIfsrR2Ru5cu2_Vj5W36nlZAIiwhCqC06hXoilAFlF4lzDE9BaPrhGbWSpCsu2h_BiCkaz3TWZeQRctOxP8ec4_T7IIZtf4LdWrxFIQ-dwSMYJ0b1PkexsDatSg0J5nw9t59xieJLtpd_jJf5fKoEig_Opy555Fl1FbZyexXScDgNaw73tAehUAfleI_ifdgH8RdX_6obOFLzQBzSEsp3y0)

However with latest release (2019.5) the result is very far from perfect:

![image](https://user-images.githubusercontent.com/728345/56700312-7aacd300-66ae-11e9-9b36-93070a34c8bd.png)

How do I get the version that runs online?

Thanks for the awesome product!

**Comment by swmatisa** [comment]
Hello,
Did you use verion 2.38 of Graphviz? You can sho this with:
_@startuml
version
@enduml_

**Comment by SashaOv** [comment]
Currently using 2.40, will try with 2.38, thanks!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered and fixed _(Graphviz related)_:

>[![](https://www.planttext.com/api/plantuml/svg/TLAxZeCm4EptA_O7A4Yw5AT8qNLNfaV8M0Q9U95jSaN4lzyumTZ92Gc1sPcTsOVFFhGkpBUHMXN4yUor8t9QXTQQKVEtlTVy869kZRQ1lGxDFE7tTU2garzRVV7aH6dlQo0vEGKXm5m25xbDOg4N-GijHD4NOb1Q7KYDCdTyYUy6GlUX0-Fnfe_Y3llQXrVTqM2FqTHFg4Xvbl11MEZJzRZlcY1cbK9yxVMr7wpP88mFmyP4-KUCNuFB-lqtlooPA1k0SZVr4sCLVkiOLUEXj2Stc3vKRyrHsNULbtYaSW0fDSEdU0gYPCp4WbOc5rIYixOTRjeV)](https://www.planttext.com/?text=TLAxZeCm4EptA_O7A4Yw5AT8qNLNfaV8M0Q9U95jSaN4lzyumTZ92Gc1sPcTsOVFFhGkpBUHMXN4yUor8t9QXTQQKVEtlTVy869kZRQ1lGxDFE7tTU2garzRVV7aH6dlQo0vEGKXm5m25xbDOg4N-GijHD4NOb1Q7KYDCdTyYUy6GlUX0-Fnfe_Y3llQXrVTqM2FqTHFg4Xvbl11MEZJzRZlcY1cbK9yxVMr7wpP88mFmyP4-KUCNuFB-lqtlooPA1k0SZVr4sCLVkiOLUEXj2Stc3vKRyrHsNULbtYaSW0fDSEdU0gYPCp4WbOc5rIYixOTRjeV)

- Thanks @SashaOv for the report.
- Thanks PlantUML team for your work.

Regards.
