### ISSUE TITLE
Gantt with monthly scale doesn't show named regions

### ISSUE THREAD

**Issue by petsuter** [plantuml/plantuml#1902]
* Go to https://www.plantuml.com/plantuml/uml/
* Paste
```plantuml
@startgantt
Project starts the 2025-01-01 
[XXX] starts 2025-01-01 and requires 100 days
2025-01-18 to 2025-03-31 are colored in red
2025-01-18 to 2025-03-31 are named [YYY]
@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/VSyn2iCm30NGtQVGrYbW9nGwvWWT7K86OOicnP5RMHro-vgqWKw5F-a_3RylYg8tP5LpUaY-Kz0IC16icNLEcxb-Zh330ZeJjBOzDzRLW1czzzDH_XJ84OIUhqMeWBCM8cx57C1TGFENTqrNkH24dB9GX8NhP_nl6TSgns4O9jCJntt16m00)](https://www.planttext.com/?text=VSyn2iCm30NGtQVGrYbW9nGwvWWT7K86OOicnP5RMHro-vgqWKw5F-a_3RylYg8tP5LpUaY-Kz0IC16icNLEcxb-Zh330ZeJjBOzDzRLW1czzzDH_XJ84OIUhqMeWBCM8cx57C1TGFENTqrNkH24dB9GX8NhP_nl6TSgns4O9jCJntt16m00) 
* See YYY
* Paste instead 
```plantuml
@startgantt
projectscale monthly
Project starts the 2025-01-01 
[XXX] starts 2025-01-01 and requires 100 days
2025-01-18 to 2025-03-31 are colored in red
2025-01-18 to 2025-03-31 are named [YYY]
@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/VSyn2iCm30NGtQVG1G9sGg5ZZj3H9cGGiMXI7BcLbI6thqaRw5Jua_xJyFkYA7f7LZLFoG-Qj4oO2DRCEgVTt3v7E5m1dGbQsruQwsh03DxxyIn_2kG8Ggzj4IhWh8M8Up4dS5VG_ELTqrKk15DEMIZ2mlKp_hUCQvL3264qFN4y1hm1)](https://www.planttext.com/?text=VSyn2iCm30NGtQVG1G9sGg5ZZj3H9cGGiMXI7BcLbI6thqaRw5Jua_xJyFkYA7f7LZLFoG-Qj4oO2DRCEgVTt3v7E5m1dGbQsruQwsh03DxxyIn_2kG8Ggzj4IhWh8M8Up4dS5VG_ELTqrKk15DEMIZ2mlKp_hUCQvL3264qFN4y1hm1) 

* Observed: YYY no longer shown.
* Expected: YYY should still be shown

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 

This is now fixed, on [v1.2024.8](https://github.com/plantuml/plantuml/releases/tag/v1.2024.8)
- Thanks @petsuter for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
