### ISSUE TITLE
When using a theme in a uml file and then outputting it in png format, Chinese characters cannot be displayed.

### ISSUE THREAD

**Issue by yusifmorley** [plantuml/plantuml#1907]
this is uml that is using  amiga theme

```plantuml
@startmindmap
!theme amiga
* 2021年24节气
** 一月
*** 1月6日 小寒
*** 1月20日 大寒
** 二月
*** 2月3日 立春
*** 2月18日 雨水
** 三月
*** 3月5日 惊蛰
*** 3月30日 春分
** 四月
*** 4月4日 清明
*** 4月20日 谷雨
** 五月
*** 5月5日 立夏
*** 5月21日 小满
** 六月
*** 6月5日 芒种
*** 6月21日 夏至
** 七月
*** 7月7日 小暑
*** 7月22日 大暑
** 八月
*** 8月7日 立秋
*** 8月23日 处暑
** 九月
*** 9月7日 白露
*** 9月23日 秋分
** 十月
*** 10月8日 寒露
*** 10月23日 霜降
** 十一月
***  11月7日 立冬
*** 11月22日 小雪
** 十二月
*** 12月7日 大雪
*** 12月21日 冬至
@endmindmap
```

to png ,can not show Chinese characters

![some](https://github.com/user-attachments/assets/f356c51a-705f-493f-890a-f77ef79a870f)

**Comment by The-Lum** [comment]
Hi @yusifmorley,

- How do you use Plantuml?
- Which version and which server?
- Could you confime you have a Chinese font?
- Could you test `listfont` command?

For example, to use PNG output, you must to have a Chinese font available or mention explicitly a Chinese font, as:
```puml
@startmindmap
!$FONT_NAME=Dialog
!theme amiga
* 2021年24节气
** 一月
*** 1月6日 小寒
*** 1月20日 大寒
** 二月
*** 2月3日 立春
*** 2月18日 雨水
** 三月
*** 3月5日 惊蛰
*** 3月30日 春分
** 四月
*** 4月4日 清明
** ...
@endmindmap
```
>[![](https://www.plantuml.com/plantuml/png/SoWkIImgoStCIybDBE1IL77pzmk9ztFqTRLroKpCoK_dKYp9ICrDLKZCpKnFvD9IC38mCdowSukHoOkkfcSRfd1fQIaysT7mR4u7aAMbO0Xac3sRlbJXwOR-f-idmSMC3C22IvP311MUxEg1QJ42Cen1iizNTp-RiHGkPcW14dmvUyMp3LiWjdJ2j1W36QOWsMVDNIzcRu2B6ODj0HhojACDfENfxDamBIP0XWbOTaVhinbz85azFJqkXrIWlw5-1m00)](https://www.plantuml.com/plantuml/uml/SoWkIImgoStCIybDBE1IL77pzmk9ztFqTRLroKpCoK_dKYp9ICrDLKZCpKnFvD9IC38mCdowSukHoOkkfcSRfd1fQIaysT7mR4u7aAMbO0Xac3sRlbJXwOR-f-idmSMC3C22IvP311MUxEg1QJ42Cen1iizNTp-RiHGkPcW14dmvUyMp3LiWjdJ2j1W36QOWsMVDNIzcRu2B6ODj0HhojACDfENfxDamBIP0XWbOTaVhinbz85azFJqkXrIWlw5-1m00) 

_[Click on the image, to view the diagram on the plantuml server]_

---

For example, the `amiga` theme uses to 2 variables:
- `$FONT_NAME`
- `$FONT_NAME_MONOSPACED`

By default, there are:
| var. | value |
| --- | --- |
| `$FONT_NAME` | Verdana |
|  `$FONT_NAME_MONOSPACED` | Courier | 

---

_If that can help,_
_Enjoy,_
Regards,
Th.

**Comment by yusifmorley** [comment]
Thanks a lot, this is very useful.
