### ISSUE TITLE
Why are the rendering results different?

### ISSUE THREAD

**Issue by chenlingmin** [plantuml/plantuml#191]
```
!includeurl https://raw.githubusercontent.com/xuanye/plantuml-style-c4/master/c4_context.puml
' uncomment the following line and comment the first to use locally
'!include c4_context.puml

actor 用户 as user
actor 运营 as admin

rectangle "会员营销平台" as platform  {
    rectangle "模板管理" as template_manager
    rectangle "会员等级" as members
}

rectangle "通道" as channel {
    rectangle "email" as c_email
    rectangle "push" as c_push
    rectangle "sms" as c_sms
    rectangle "站内信" as c_inmsg
}


rectangle "大数据" as bigdata {
    rectangle "数据仓库" as dw
    rectangle "标签系统" as tsp
}

rectangle "商城客户端" as shopping {
    rectangle "购物车"
    rectangle "订单"
}


admin --right-> platform: 发起营销活动
platform -up-> bigdata: 获取用户
platform -down-> channel: 推送消息

c_email ..> user: 触达
c_sms ..> user: 触达
c_push ..> user: 触达
c_inmsg ..> user: 触达

shopping .right..> dw: 数据反哺
'user -up-> shopping
tsp -> dw: 圈人

```

* This is remote server result

![image](https://user-images.githubusercontent.com/8233283/56731066-2841e400-678c-11e9-989d-6d0efb9b78a6.png)

* This is local result
```
brew install plantuml
plantuml test.uml
```

![test](https://user-images.githubusercontent.com/8233283/56731246-9edee180-678c-11e9-812a-91047040378e.png)

Why are the rendering results different ?

**Comment by arnaudroques** [comment]
Maybe GraphViz and/or PlantUML version are different on both configuration.
Can you try:
```
@startuml
version
@enduml
```

On your configuration ?
Thanks

**Comment by chenlingmin** [comment]
Local version is 1.2019.03
![image](https://user-images.githubusercontent.com/8233283/56777369-aee5d800-6803-11e9-88d3-4b7d87dd5407.png)

Server version is 1.2019.05
![image](https://user-images.githubusercontent.com/8233283/56777385-cde46a00-6803-11e9-90e6-64e937bb1829.png)

**Comment by chenlingmin** [comment]
I think it should be caused by the difference in graphviz version

**Comment by ErikAnderson3** [comment]
@chenlingmin, it seems like there's nothing left to do for this ticket.  If you are satisfied that the difference in rendering was due to a difference in PlantUML versions, please close this ticket.
