### ISSUE TITLE
elk-full.jar included into plantuml distribution compiled with newer Java Runtime version

### ISSUE THREAD

**Issue by vlsav** [plantuml/plantuml#1931]
**Describe the bug**
 Hello! elk-full.jar included into plantuml distribution seems like compiled with newer Java Runtime version.
I have no issues with drawing plantuml diagrams, but when I tried to use ELK I got this:
java.lang.UnsupportedClassVersionError: org/eclipse/elk/graph/util/ElkGraphUtil has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0.

**To Reproduce**
Java Runtime 1.8
Add !pragma elk to diagram code.

**Expected behavior**
It is expected that whole plantuml.jar distribution will be compiled with the same Java Runtime version.

**Comment by arnaudroques** [comment]
We are doing our best to continue supporting Java 8 in PlantUML, as we understand that some users still rely on this version. However, in this specific case, there is unfortunately nothing we can do.

The `elk-full.jar` included in the PlantUML distribution has been compiled with Java 11 (not by our team). Java 8 is simply too old to handle this, as it can only run class files compiled with Java 8 or earlier versions (class file version 52.0). ELK, being compiled with Java 11 (class file version 55.0), requires a more recent runtime to function properly.

While we strive to maintain compatibility with Java 8 wherever possible, in this instance, Java 8 is too outdated to support the newer libraries, and upgrading to **Java 11 or higher** is the only feasible solution. Java 11 has been out for several years now and brings many improvements.

Really sorry about that!
