### ISSUE TITLE
[Style] Allow [all] style for `Cardinality`, `Generic`, `Qualified associations` on Class diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1945]
Hi PlantUML team,

## Context
To follow:
- #1467
- https://forum.plantuml.net/19300/styling-of-qualified-associations

And inspired by:
- #1445

## Wanted feature
- Could you allow style on Class Diagram for:
  - [ ] cardinality
  - [ ] generic
  - [ ] qualified associations 

## Simple example

```puml
@startuml
!theme crt-amber

interface Map<K,V>
class HashMap<Long,Customer>

Map <|.. HashMap
Shop [customerId: long] ---> "customer\n1" Customer
HashMap [id: Long] -r-> "value" Customer
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JSz12u9040NW-_oAIGWAT4k93Y4YT2aoEWHThCEgOmgwAxkhftvyAobqVNplCHDhmvNfsmOMfgAMC5V6usr62g0MXbJ9Sy8hxyAB-uWWRxZMUEAw6gD4YhTxxBMHBQa8m6OOVXYR0TmhsM6QJ-9S7B2nbHTwdXUXC-TFuJiupy3KnRIsFFbnDVA1DptzGIYbj0VYBTCCVHPiWntRumQN0obTIx5QGqoYiBzz0G00)](https://www.planttext.com/?text=JSz12u9040NW-_oAIGWAT4k93Y4YT2aoEWHThCEgOmgwAxkhftvyAobqVNplCHDhmvNfsmOMfgAMC5V6usr62g0MXbJ9Sy8hxyAB-uWWRxZMUEAw6gD4YhTxxBMHBQa8m6OOVXYR0TmhsM6QJ-9S7B2nbHTwdXUXC-TFuJiupy3KnRIsFFbnDVA1DptzGIYbj0VYBTCCVHPiWntRumQN0obTIx5QGqoYiBzz0G00) 

Currently for example "cardinality" and "qualified associations" inherit the arrow style... like:

```puml
@startuml
<style>
arrow {
  FontColor Blue
  FontSize 14
  FontStyle bold
  BackgroundColor pink
}
</style>

    interface Map<K,V>
    class HashMap<Long,Customer>

    Map <|.. HashMap
    Shop [customerId: long] ---> "customer\n1" Customer
    HashMap [id: Long] -r-> "value" Customer
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/JP1DQm8n54Nt-HKNGMZ1YHqH5p8CeY2MMheGt6WNSIPgCEODISRIh__Up9Y1Bj_XdijxR-QyiBw-QfOv_wbbpeIrz85l1Yp9-0LfifZhMaQmKLyIwRYR6WS7qcK0Sr5SJfPgKzwjIfaB-sNPC3Q72A2Cb_Oe2ebNKMKlWstUua8Bvx0IxjpWDPdJO54xJrTfenWuiX_Ekr0BDsUgi2jYyhcSGWVr7KcIvEXrV6_I7hgwreiTsAcWhE-ARPIR2AV-2xCZKLWORmV7aVBHqsZC9nYYVvFMAJ8FZsmcJHaU-0S0)](https://www.planttext.com/?text=JP1DQm8n54Nt-HKNGMZ1YHqH5p8CeY2MMheGt6WNSIPgCEODISRIh__Up9Y1Bj_XdijxR-QyiBw-QfOv_wbbpeIrz85l1Yp9-0LfifZhMaQmKLyIwRYR6WS7qcK0Sr5SJfPgKzwjIfaB-sNPC3Q72A2Cb_Oe2ebNKMKlWstUua8Bvx0IxjpWDPdJO54xJrTfenWuiX_Ekr0BDsUgi2jYyhcSGWVr7KcIvEXrV6_I7hgwreiTsAcWhE-ARPIR2AV-2xCZKLWORmV7aVBHqsZC9nYYVvFMAJ8FZsmcJHaU-0S0) 

Then perhaps create new `SName` for that...

_Thanks for the enhancement..._
Regards,
Th.

**Comment by arnaudroques** [comment]
With last commit, you can have:

```
@startuml
<style>
document {
  BackgroundColor red
}
arrow {
  FontColor Blue
  FontSize 14
  FontStyle bold
}
class {
  BackgroundColor yellow
  generic {
  	BackgroundColor purple
  }
  qualified {
  	BackgroundColor green
  	FontColor ivory
  }
}
</style>

    interface Map<K,V>
    class HashMap<Long,Customer>

    Map <|.. HashMap
    Shop [customerId: long] ---> "customer\n1" Customer
    HashMap [id: Long] -r-> "value" Customer
@enduml
```
No `cardinality` style has been added yet.
Should we do it ?

**Comment by The-Lum** [comment]
>No cardinality style has been added yet.
Should we do it ?

Why not?
In order to manage style on all elements...

**Comment by The-Lum** [comment]
🎉
