### ISSUE TITLE
MaximumWidth for language without spaces

### ISSUE THREAD

**Issue by avenue68** [plantuml/plantuml#1947]
**Is your feature request related to a problem? Please describe.**
I set `MaximumWidth` parameter with `style` tags but the sentence in elements wouldn't be wrapped when they doesn't contain any spaces.
In Japanese, for example, it's common not to have space in sentences so `MaximumWidth` doesn't work for Japanese unless insert unnatural spaces at points we wanna line break.

```plantuml
@startuml
<style>
element {
  MaximumWidth 10
}
</style>

:このような長い文章は折り返されない;
'This is not wrapped

:ThisIsAlsoNotWrapped;
'This is also not wrapped
@enduml
```

**Describe the solution you'd like**
Wrap sentences just by `MaximumWidth` or other parameters value, regardless wether they contain spaces or not.

**Comment by The-Lum** [comment]
Hello @avenue68,

Here are some answer elements:
- https://forum.plantuml.net/14830/something-planed-that-chinese-text-supports-word-wraps-too
- https://forum.plantuml.net/17019/prevent-wrap-for-comma-dot-etc

---

For example, currently `plantuml` manages:
- space
- https://github.com/plantuml/plantuml/blob/f8b6c43f21bdeea115b39ff46dc2089e396eff6e/src/net/sourceforge/plantuml/klimt/creole/Neutron.java#L91-L98
- and also [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space)

_If that can help,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi @avenue68 

See recent news on this subject _(from 1.2025.3b3)_ here:
- https://github.com/plantuml/plantuml/issues/2254#issuecomment-3006362855

And:
```puml
@startuml
<style>
element {
  MaximumWidth 10
}
</style>

:このような長い文章は折り返されない;
'This is not wrapped

:ThisIsAlsoNotWrapped;
'This is also not wrapped
@enduml
```
>[![](https://img.plantuml.biz/plantuml/svg/SoWkIImgAStDuUMoAIwfp4cru-LApKdDJSqhKQZcvL9Gy4sioCmjpGtFJ2d9K30quEMg1QhKXodbvR9wt3ZvSUEwnqqTZnlR7ZUkUZbr--F6bcVJsf-lNl2uSVsphXcFcxfUx9_ok77guwOUe0AWh3Klbtf8HcQn0X3bvPSeb1Sb5XIafe2D0ubx5Zlc5EVxvPU4GoIGrIS2PL0rfUNdbwGMASJa6UeP6HYPwfaafPOa6YleAwYMfHOLP-RdQMZoSZcavgK0VGa0)](https://editor.plantuml.com/uml/SoWkIImgAStDuUMoAIwfp4cru-LApKdDJSqhKQZcvL9Gy4sioCmjpGtFJ2d9K30quEMg1QhKXodbvR9wt3ZvSUEwnqqTZnlR7ZUkUZbr--F6bcVJsf-lNl2uSVsphXcFcxfUx9_ok77guwOUe0AWh3Klbtf8HcQn0X3bvPSeb1Sb5XIafe2D0ubx5Zlc5EVxvPU4GoIGrIS2PL0rfUNdbwGMASJa6UeP6HYPwfaafPOa6YleAwYMfHOLP-RdQMZoSZcavgK0VGa0)


- Is this what you wanted?

_Enjoy,_
Th.

**Comment by avenue68** [comment]
Hi @The-Lum 
Thank you so much for notifying me the update! I didn't have time to explore it for a while.
And I've just checked the update but unfortunately the update only resolves the problem for Chinese.
Japanese language partially uses the same letters as Chinese (called Kanji in Japan) so Japanese sentences are wrapped only on (or right before/after) the Chinese letters.

But as long as I explore [the commit](https://github.com/plantuml/plantuml/commit/553585557370aed797c31c29512630d2ec382744), it seems not hard to implement the code for Japanese language too!
Maybe I will make a PR when I have time.

Thank you for your comment again!

**Comment by arnaudroques** [comment]
A patch has been submitted. Please give it a try and let us know if it works better for you!

**Comment by avenue68** [comment]
@arnaudroques 
Thank you so much! Now it works perfectly for Japanese too!
