### ISSUE TITLE
Request for fixing proprietary licenses in PlantUML software package of Replicant project

### ISSUE THREAD

**Issue by kuber1111** [plantuml/plantuml#1949]
Respected team of Github,

I am a volunteer at Free software foundation.

Thank you so much for including a COPYING.LESSER file and confirming the OpenJDK build availability. I was able to continue my review for PlantUML's entry into the Free Software Directory (FSD).  This is the link for the previous issue :

- https://github.com/plantuml/plantuml/issues/1944

PlantUML is a software package in Replicant project which is a free operating system for mobile phones : 

- https://directory.fsf.org/wiki/Collection:Replicant

Unfortunately, I discovered two files which are under a nonfree proprietary license in .csv file of PlantUML.

- /src/zext/plantuml/com/ctreber/acearth/MapData.java
- /src/zext/plantuml/com/ctreber/acearth/ACearth.java

I do apologize for making a fuss over a couple of files, but technically (I believe) they are incompatible with the GPLv3 because they restrict commercial and for-profit uses. Fortunately, PlantUML had the foresight to offer other permissive licences which is useful to users; however, as a volunteer for the Free software directory (FSD) .  I have to follow the FSD requirement guidelines, and I sadly won't be able to add PlantUML as an entry if their are entries with  nonfree proprietary license.

I don't know how to assist you with resolving what the FSD considers a freedom issue. Tracking down an author for a program that is 34 years old to ask about relicensing would be challenging. I certainly would not deter anyone from trying, but it has a low chance of success. One option would be to remove the files if they are not necessary, but I have no idea if that is even possible. I also don't want to ask anyone to use their time, especially if they don't share this concern.

I've made this post with assistance from the Licensing and Compliance Lab of the Free Software Foundation. If you would like help with your free software licensing, they would be glad to help. Feel free to email licensing@fsf.org with your questions.

![plantuml proprietary license list](https://github.com/user-attachments/assets/c3cbb358-a764-48d7-a17b-2f4f5b5d6044)

****Gadgets which i use :****

I use debian mate gnu-linux operating system and Debian Bookworm release. I have two Lenovo thinkpad laptops T430 and T440p.

I use ONE PLUS mobile phone with Postmarket OS.

Please view the attached screenshot of entries with proprietary licenses in .csv file of PlantUML.

Thank you
Kuber arora kapoor

**Comment by arnaudroques** [comment]
Thank you for being a volunteer, we greatly respect your choice.

The simplest solution would be for us to remove "acearth" from PlantUML. It serves no real purpose (see https://plantuml.com/xearth), and we have only kept traces of this project written in 1993 for sentimental reasons.

So, if this resolves the licensing issue, and if no one opposes it, it will be removed in version 1.2024.8.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀

This is now fixed, on [v1.2024.8](https://github.com/plantuml/plantuml/releases/tag/v1.2024.8)
- Thanks @kuber1111 for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
