### ISSUE TITLE
Wrong Output in nwdiag

### ISSUE THREAD

**Issue by uwearzt** [plantuml/plantuml#195]
```
@startuml network
nwdiag {
  network dg {
    router;
  }
  network telekom {
    draytek;
  }
  network external {
    draytek;
    router;
    firewall;
  }
}
@endum
``` 

outputs:
![nw](https://user-images.githubusercontent.com/105293/56854967-659aa300-693f-11e9-8af2-0e4093d053df.png)

This connection is missing:

![nw-corrected](https://user-images.githubusercontent.com/105293/56854977-7b0fcd00-693f-11e9-966d-1de26cbc6544.png)

**Comment by albert-github** [comment]
I had a quick try of this problem and it looks to me that it is now working (version 1.2021.4), see http://www.plantuml.com/plantuml/uml/POn12a8n34JtFKNkuUPV9P1HIjCKOaeLwTqLQa7ykvVCcpdkmHwzAXbYD2_9XcI-qIlHVf6iayXR3_Zbm_Cd3YXAgrz7d9-1yY_X4N1ZFLjxTl4rEmQhhlvC1qnwVGC0

![image](https://user-images.githubusercontent.com/5223533/113699140-7d573600-96d5-11eb-8d35-06eb476f6c51.png)

**Comment by uwearzt** [comment]
Yes, looks fixed 👍🏼
