### ISSUE TITLE
`<<myStyle>>` shown for user defined styles in a Sequence Diagram

### ISSUE THREAD

**Issue by koppor** [plantuml/plantuml#1966]
**Describe the bug**

`<<myStyle>>` shown for user defined styles in a Sequence Diagram

**To Reproduce**

1. Go to https://plantuml.com/style-evolution
2. Scroll down to "Using user defined styles in a Sequence Diagram"
3. See following image\
    ![image](https://github.com/user-attachments/assets/01f61b20-d9f2-454b-9748-025af1d0b767)

**Expected behavior**

`<<myStyle>>` not shown.

**Screenshots**

See above

**Desktop (please complete the following information):**

(Also happens in a local installation)

- OS: Windows
- Version `1.2024.7 (Sat Sep 07 13:18:17 CEST 2024)`

**Smartphone (please complete the following information):**

**Additional context**

This somehow refs https://github.com/plantuml/plantuml/issues/1253

**Comment by koppor** [comment]
It worked with `2022.5` and stopped working at `2022.6`.

**Comment by kirchsth** [comment]
Could it be that you missed the line `hide stereotype`, with that you get the correct output. 
(the image is linked with the source)

[![](https://www.plantuml.com/plantuml/svg/RKzRJiCm4FpVK-nVVn1S8Agg5d40SW8t6LgBpJhOQvK8zUvicbH2WFyyZzcPNR6GhGv2vJtg678Ok1RiOQ6rIS2MAsZ3vVQ1Tf9ApU0UdRZOOb9gRkIMs9yhkpIwBN71HtK3dcCupR4G350hi-uF-KKE_me8dQLyjx5D8nOlBunxU7qlIUsGnB6zLApmbMXDxF4M5HnOSLcMFFZ8g2S-j2txa5AuJ6hXSt4y3jCo_hyBh-Zfdd-bvcaTJ-VOmyEHaUQgH1iUSrH3pr7vEFTQQk_JqJaxnyANACAQBdp4Jx6VMBLj49cuQTP2sotje7qTv1i0)](https://www.plantuml.com/plantuml/uml/RKzRJiCm4FpVK-nVVn1S8Agg5d40SW8t6LgBpJhOQvK8zUvicbH2WFyyZzcPNR6GhGv2vJtg678Ok1RiOQ6rIS2MAsZ3vVQ1Tf9ApU0UdRZOOb9gRkIMs9yhkpIwBN71HtK3dcCupR4G350hi-uF-KKE_me8dQLyjx5D8nOlBunxU7qlIUsGnB6zLApmbMXDxF4M5HnOSLcMFFZ8g2S-j2txa5AuJ6hXSt4y3jCo_hyBh-Zfdd-bvcaTJ-VOmyEHaUQgH1iUSrH3pr7vEFTQQk_JqJaxnyANACAQBdp4Jx6VMBLj49cuQTP2sotje7qTv1i0)

I think it is an error in the documentation.

PS.: Hiding/showing a specific stereotype is an open issue too, but it is already [reported]( https://github.com/plantuml/plantuml/issues/1953)

**Comment by The-Lum** [comment]
Hi all,

> I think it is an error in the documentation.

Yes, then I take the action to modify the doc.

Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

This is now updated:
- https://plantuml.com/style-evolution#ffdf49f8e84efbd4

Thanks to:
- @koppor for the report.
- PlantUML team for your work.

Regards.
