### ISSUE TITLE
Doubled jar size between v1.2024.5 and v1.2024.6

### ISSUE THREAD

**Issue by nbauma109** [plantuml/plantuml#1967]
I noticed a doubled jar size between v1.2024.5 and v1.2024.6.

By looking inside the jars, I noticed some libraries are repackaged:
- org/eclipse/elk
- com/google/common
- org/scilab/forge

In particular one image `images/controller.png` takes space and comes from [ELK](https://eclipse.dev/elk/img_gen/org-eclipse-elk-topdownLayout_controller.png) documentation and not sure how it's relevant for the plantuml application to have it.

To give a bit of context, I have an application with a considerable number of jars and plantuml plays a small role in it, but it's by far the biggest jar. Also I'm concerned about this repackaging which might conflict with other libraries.

**Comment by arnaudroques** [comment]
Are you using gradle or maven to build your project?

Also, can you use the [MIT](https://github.com/plantuml/plantuml/releases/download/v1.2024.7/plantuml-mit-1.2024.7.jar) release ? It does not include ELK, so it is much smaller.

**Comment by nbauma109** [comment]
Thanks, MIT release what was I needed.
