### ISSUE TITLE
sequenceArrowThickness does not work with teoz

### ISSUE THREAD

**Issue by rolo2019** [plantuml/plantuml#198]
sequenceArrowThickness does not work with teoz but works without

**Comment by arnaudroques** [comment]
Thanks for the report.
This is fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @rolo2019 for the report.
- Thanks PlantUML team for your work.

Regards.
