### ISSUE TITLE
Need Help: how to merge deployment icons in any other diagram

### ISSUE THREAD

**Issue by p00j4** [plantuml/plantuml#200]
I want to have database, cloud etc. diagrams in my Activity diagrams, but its fails with syntax error. Is it possible or any work around? my snippet (ideally want to use with the activities)
```
@startuml

database database [
This is a <b>database
----
You can use separator
====
of different kind
....
and style
]
cloud cloud

start

partition Setup {
    :CI Test Box;
    :Deploy branch (in venv);
    :Coverage Capture start;
}
stop



@enduml
```

**Comment by The-Lum** [comment]
Hello @p00j4, and all,

_[This is an Issue Review]_
And here is an answer to an old issue.

To mix deployment element with other diagram, you can **_now_** use label (`label`) and subdiagram (`{{`, `}}`), as:

```puml
@startuml

database database [
This is a <b>database
----
You can use separator
====
of different kind
....
and style
]
cloud cloud 

label label [
{{
start

partition Setup {
    :CI Test Box;
    :Deploy branch (in venv);
    :Coverage Capture start;
}
stop
}}
]

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/FL11JWCn3BpFAto40po0KbInN3YtbwhYuDruQKH8eiHPKQtsxpKiCB96rjWQZxohoaNRPm0SA_TSXVwR4mvdNycAwR5_-jDnPy0nDHeuKhF5AfaBQohO6f16SduSfKXK-l3HuTu0ZewgNeBW3KD8pT7AGE1U0grymZpZ9nLWhkhLfqXxqPPf1XaUkbSwI5LwJb-RLNcH7DA5-i9nEDEDZpH9d6v_frsQfF2xKCTPMx6yt_ORB7OdPIoB1G9s4fqzuWe0)](https://www.planttext.com/?text=FL11JWCn3BpFAto40po0KbInN3YtbwhYuDruQKH8eiHPKQtsxpKiCB96rjWQZxohoaNRPm0SA_TSXVwR4mvdNycAwR5_-jDnPy0nDHeuKhF5AfaBQohO6f16SduSfKXK-l3HuTu0ZewgNeBW3KD8pT7AGE1U0grymZpZ9nLWhkhLfqXxqPPf1XaUkbSwI5LwJb-RLNcH7DA5-i9nEDEDZpH9d6v_frsQfF2xKCTPMx6yt_ORB7OdPIoB1G9s4fqzuWe0)

Enjoy,
_If that is not too late, and if that can help,_
Regards.
