### ISSUE TITLE
.pulm files generation

### ISSUE THREAD

**Issue by e13mort** [plantuml/plantuml#204]
Is there any solution to generate a .pulm file out of internal model classes?

**Comment by Valdanitooooo** [comment]
<dependency>
            <groupId>com.structurizr</groupId>
            <artifactId>structurizr-plantuml</artifactId>
            <version>1.3.0</version>
        </dependency>

        StringWriter stringWriter = new StringWriter();
        PlantUMLWriter plantUMLWriter = new PlantUMLWriter();
        try {
            plantUMLWriter.write(workspace, stringWriter);
        } catch (Throwable e) {
            LOG.error("Write Error", e);
        }
        LOG.info("PantUML :\n" + stringWriter.toString());

**Comment by e13mort** [comment]
It's an interesting library. But, it's quite limited to the internal structurizr classes structure thus it has a very few output diagrams. For an example there's no class diagram model.
