### ISSUE TITLE
"hide empty description" in state diagram breaks sequence diagram

### ISSUE THREAD

**Issue by jessetan** [plantuml/plantuml#212]
### Reproduction

This works:
```puml
@startuml
hide empty description

[*] --> state : label
@enduml
```

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuSh8J4bLICqjAAbKI4ajJYxAB2Z9pC_ZuehMYbNGrRLJ02eiILMmKiX9J4hDuN98pKi1wW80)

This does not work:

```puml
@startuml
hide empty description

a -> b: message
return answer
@enduml
```

![](http://www.plantuml.com/plantuml/png/3Sl13OGm30J0lwlO1gw1Uw2qOiWA8X4JsOuGtSFyfqIgv-od7AqIx2CVLCRcRMIxJ4JnMx3-qHcXEyMPqmrgSTEbqEgtNm00)

Expected behavior: the `hide empty description` is ignored by the sequence diagram and there is no syntax error

### Background
I have a file with all my styling in it that I automatically include in every diagram I generate. It contains `hide empty description` to hide empty descriptions in state diagrams. If I generate a sequence diagram with this file included, I get a syntax error.

**Comment by arnaudroques** [comment]
Ok, understood.
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you!

**Comment by jessetan** [comment]
Looks fixed, thanks!
