### ISSUE TITLE
Quote in front of !include ignored

### ISSUE THREAD

**Issue by pktl** [plantuml/plantuml#213]
Hi,

it seems, `!include` statements are unaffected by a leading `'`. I expect that line to be ignored, since it should be a comment.
This happens in the latest version 1.2019.06. Not sure if older versions are affected.

I assume this isn't intentional?

Edit: This is also happening with `@startuml`, `@enduml` statements.

**Comment by arnaudroques** [comment]
> I assume this isn't intentional?

No, it's not.

Could you try with last beta http://beta.plantuml.net/plantuml.jar ?
It works for us there.
Thanks.

**Comment by pktl** [comment]
In the beta version, comments work in front of `!include`, but not in front of `@startuml` or `@enduml`.

**Comment by arnaudroques** [comment]
Could you give a simple example showing the issue ?
`@startuml/@enduml`  have been designed to be used inside various programming language comment (C/C++/Java/PHP/Perl...) so maybe there is some connection here.

**Comment by pktl** [comment]
Sorry for misleading you. It seems I was just looking at some old output...

So, `'` in front of `!include` works as expected in both versions.

`'` in front of `@startuml` and `@enduml` is ignored in a plain plantuml script (i.e. not embedded in any other language). Which makes also sense, because actual interpretation of plantuml, including comments, could only happen in between `@startuml` and `@enduml`.
In other languages I work with, no start/end statements are necessary. The whole file is interpreted as source code in that language. So that's where my confusion came from.

You can close the issue, I guess.
