### ISSUE TITLE
skinparam section: lines with comments at the end are ignored

### ISSUE THREAD

**Issue by novoid** [plantuml/plantuml#214]
When using a skinparam section, entries like the `BorderColor` below are ignored as long as there is a comment within the same line:

```
skinparam activity {

    ' following line is not ignored:
    BackgroundColor White

    BorderColor Black  ' this line is ignored
}
```

I'd like to have PlantUML to respect every config line and ignore comments at the end of a config line entry.

PlantUML version 1.2017.16

**Comment by arnaudroques** [comment]
Only lines **starting** by a quote comments. Quotes inside a line is not seen as comment.
As workaround, you can use:

```
@startuml
skinparam activity {

    ' this is a comment
    BackgroundColor White

    BorderColor Black /' this is a comment '/
}

start
:foo1;
@enduml

```

**Comment by novoid** [comment]
Hi @arnaudroques,

Thanks for the explanation.

However, since this is a totally different pattern to almost all programming and configuration languages there are, this needs to be changed or documented clearly in my opinion.
