### ISSUE TITLE
Gantt: Wednesdays Text (We) is not rendered (anymore?)

### ISSUE THREAD

**Issue by Roemer** [plantuml/plantuml#215]
As the title says, the text "We" is not rendered anymore, even on the `Calendar` example from the official site.
```
@startgantt
Project starts the 20th of september 2017
[Prototype design] as [TASK1] lasts 13 days
[TASK1] is colored in Lavender/LightBlue
@endgantt
```
![image](https://user-images.githubusercontent.com/393641/59494974-9c486080-8e8e-11e9-84bb-fe85987a694e.png)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Roemer for the report.
- Thanks PlantUML team for your work.

>[![](https://www.planttext.com/api/plantuml/svg/DSwn2i8m58NXFKznta2ZWsjrjODWjzBXsboJI4nAxbNesniAhX__WTE9KbLFMTNSQddnhDX8e85ns6j0UK9uKNu_k3Qn9pEsL8kk2yEnH9yda60SplUhdP18sjmUuMWLyzSec4igbHrYHazVpexhhey-w2Lzs7GDjYC_)](https://www.planttext.com/?text=DSwn2i8m58NXFKznta2ZWsjrjODWjzBXsboJI4nAxbNesniAhX__WTE9KbLFMTNSQddnhDX8e85ns6j0UK9uKNu_k3Qn9pEsL8kk2yEnH9yda60SplUhdP18sjmUuMWLyzSec4igbHrYHazVpexhhey-w2Lzs7GDjYC_)

Regards.
