### ISSUE TITLE
Include PlantUML version numer in testdot output

### ISSUE THREAD

**Issue by novoid** [plantuml/plantuml#216]
When testing the PlantUML installation [using testdot](http://plantuml.com/graphviz-dot), I can read "Welcome to PlantUML!" and some additional information. **I'd suggest to include at least the PlantUML version number** and probably also the version numbers for dot and so forth in this output as well.

Otherwise, I have to find out how to display the version number. In my case, I had to call `java -jar plantuml.jar` and invoke the about screen. This is tedious for me since I'm using PlantUML exclusively [within Org mode](http://eschulte.github.io/babel-dev/DONE-integrate-plantuml-support.html).

**Comment by arnaudroques** [comment]
You can also use
```
@startuml
version
@enduml

```
to print PlantUML Version number.
But we will indeed follow your suggestion and print PlantUML version to the `testdot` feature.

**Comment by arnaudroques** [comment]
We have done something really minimum in last beta http://beta.plantuml.net/plantuml.jar
Tell us if you'd like to see more information.
Thanks

**Comment by novoid** [comment]
This is looking good.
What about adding a final hint for "version" in the output of "testdot" to guide users to the full list of versions? Because I was able to find multiple pages with "testdot" where no "version" was mentioned.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @novoid for the report.
- Thanks PlantUML team for your work.

Regards.
