### ISSUE TITLE
Support multiline tables

### ISSUE THREAD

**Issue by idvorkin** [plantuml/plantuml#219]
I love Plant UML, and am excited to draw tables! Next I need multi-line support. This is provided in  creole 0.5, but I can't get it to work in PlantUML, only rendering a "\\":

From [creole](http://www.wikicreole.org/wiki/Tables):
```
Table with forced line break using the \\ syntax

|=Heading Col 1                        |= Heading Col 2
|Cell 1.1 line one \\ Cell 1.1 line two | Cell 1.2
```

Trying 

```
@startuml
title
  Example of simple table
  |= table |= header |
  |line 1\\line2 | row |
end title
@enduml
```

Renders:

![image](https://user-images.githubusercontent.com/280981/60385736-44d6f280-9a41-11e9-8ba8-1ca7f6a5c74d.png)

**Comment by arnaudroques** [comment]
We do not fully follow Creole convention here, but you can have :

```
@startuml
title
  Example of simple table
  |= table |= header |
  |line1\nline2 | row |
end title
@enduml
```

Hope this helps!

**Comment by idvorkin** [comment]
It's exactly what I needed - thank you!!

**Comment by davidyew** [comment]
Hi!

It is related to this on mindmap, the multiline table is not working.
May I request it as a feature?
https://www.planttext.com/?text=SoWkIImgoStCIybDBE3YqbO8oI_8J5OmvDBMZbUeKN1EpSbHS8Gnd1HgOefg868nUJcPUQaAXZ0fenekBbtTU8MGnAISL0LZBYw7LA2P47C1
