### ISSUE TITLE
rnote does not inherit Rounded skinparam

### ISSUE THREAD

**Issue by rtgoodwin** [plantuml/plantuml#221]
Given:

```
@startuml
skinparam RoundCorner 5
skinparam SequenceMessage {
  Margin 35
  Padding 5
  BorderColor Blue
}
Alice->Bob : hello
participant Bob
participant Alice

rnote over Bob
This should be rounded
end note
Bob->Alice: This message should be rounded 
@enduml
```
The `rnote` is not rounded, or the `message` (in the new beta where `message` can be styled) while the Participant elements are. I don't know how much of this is a "fix in current system" or "fix in future style system"...perhaps a little of both?

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.plantuml.com/plantuml/svg/POv1JWCn34NtFiM_G9TikgZQwReI0YwGJgoP2CSUd0GMYBkJHY21khE_tfFUiTJWjMMXcgemJY981MvD8qUeVL1vJRe53nbFj_Lihknu-BC_yrjZdVd2fOI5yKd09VYIj6F0OuWnwJBkoJoodqtCCKbZ-gAJf9btXycks6Db4QEjDwKvRK4h-lxl7pYHgrM6lRCFucNjrMMr9X5N_kqdreWRI9tP7OQwns3pJ-kzS-nIo_8D)](https://www.plantuml.com/plantuml/uml/POv1JWCn34NtFiM_G9TikgZQwReI0YwGJgoP2CSUd0GMYBkJHY21khE_tfFUiTJWjMMXcgemJY981MvD8qUeVL1vJRe53nbFj_Lihknu-BC_yrjZdVd2fOI5yKd09VYIj6F0OuWnwJBkoJoodqtCCKbZ-gAJf9btXycks6Db4QEjDwKvRK4h-lxl7pYHgrM6lRCFucNjrMMr9X5N_kqdreWRI9tP7OQwns3pJ-kzS-nIo_8D)

- Thanks @rtgoodwin for the report.
- Thanks PlantUML team for your work.

Regards.
