### ISSUE TITLE
New Activity diagrams don't support function calls in else branch

### ISSUE THREAD

**Issue by familom** [plantuml/plantuml#226]
Minimal example:
```
@startuml

title Example

start
:step 1

if (condition) then (Foo::foo())
    :We are in Foo::foo();
else (Bar::bar())
    :We are in Bar::bar();
endif

stop

@enduml
```

Line `else (Bar::bar())` is causing 'syntax error'. If you replace it with `else (no)` it will work and main branch will have `Foo::foo()` label.

**Comment by arnaudroques** [comment]
Thanks for the feedback !
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar

Note: There is a missing `;` in your `:step 1;`
Tell us if it's not working for you.

**Comment by imshenwei** [comment]
it is working

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/ROwn2W8n44Jx-Oejaz9shpa4_GNhw6qmaCk6P0K_tzNc6gSRteEPTLeQzjehOCMgqEMTzbu5-07mDEbqMe2IAJoqRSMAjaZsb4RXgigSLKEC80_VXD8GAeqEj43g50hdD9ZlQVoH3-IoR-JlldPWzURlFW00)](https://www.planttext.com/?text=ROwn2W8n44Jx-Oejaz9shpa4_GNhw6qmaCk6P0K_tzNc6gSRteEPTLeQzjehOCMgqEMTzbu5-07mDEbqMe2IAJoqRSMAjaZsb4RXgigSLKEC80_VXD8GAeqEj43g50hdD9ZlQVoH3-IoR-JlldPWzURlFW00)

- Thanks @familom for the report.
- Thanks PlantUML team for your work.

Regards.
