### ISSUE TITLE
Java error occurs when sequence diagram message has both note and duration

### ISSUE THREAD

**Issue by stanwest** [plantuml/plantuml#229]
In the following diagram, the "start" message is part of a duration constraint and has a related note:
````plantuml
@startuml
!pragma teoz true
{start} Alice -> Bob: start
note right: starting
{end} Bob -> Alice: finish
{start} <-> {end}: some time
@enduml
````
Given that diagram, PlantUML produces the error message

> An error has occured : java.lang.ClassCastException: net.sourceforge.plantuml.sequencediagram.teoz.CommunicationTileNoteRight cannot be cast to net.sourceforge.plantuml.sequencediagram.teoz.CommunicationTile

<details><summary>Details</summary>

![FOx13S8m34Nldk8p00jK21Ks2M1IIqs2NFT2rTrnBDJh--zP7XTBQckPwVJHb4k2SVl2T6NQOjjnc-N9E5znRuy10QasOwZaoVv4QgQDwsllLfUZ6l2MAijqtBhu4ffdhJ1C2jFem5_u0G00](https://user-images.githubusercontent.com/38358698/61149243-b043aa00-a4ae-11e9-9e5d-001fa3e8426f.png)

</details>

With `note right` replaced by `& note right of Bob`, as in
````plantuml
@startuml
!pragma teoz true
{start} Alice -> Bob: start
& note right of Bob: starting
{end} Bob -> Alice: finish
{start} <-> {end}: some time
@enduml
````
then the error becomes

> An error has occured : java.lang.NullPointerException

<details><summary>Details</summary>

![HOv13e9034NtFSLtuyuB46FGcunQXYRCr0nb8-7kbYva-rvVy_lPKhEbJ7Jwj9HBWh5-OMrXMiDjk4_oObnkUEYpGq0wewenckJHe0CE9JNJolMzxMol8kymI9Lv_3-zkeappxGmJ0fJxy2t_000](https://user-images.githubusercontent.com/38358698/61149411-18928b80-a4af-11e9-8c5d-c04d6c777941.png)

</details>

Without the note, PlantUML renders the duration:
````plantuml
@startuml
!pragma teoz true
{start} Alice -> Bob: start
{end} Bob -> Alice: finish
{start} <-> {end}: some time
@enduml
````

![SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvQe6ozKgEEPa9gSgwDefEEKdMIc01RcgK_DIQa42G7680Yk5jCoypE8Ck3ORe0nO6L1FVcwgGabcRYgN0r00Q1i0](https://user-images.githubusercontent.com/38358698/61149650-a66e7680-a4af-11e9-9fa5-d5326342a5d2.png)

and without the duration (using either `note right` or `& note right of Bob`), PlantUML renders the note:
````plantuml
@startuml
!pragma teoz true
{start} Alice -> Bob: start
note right: starting
{end} Bob -> Alice: finish
@enduml
````

![SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvQe6ozKgEEPa9gSgwDefEEKdMIc01RdoyajI5OeoqpDAe2APUUbSrQbvARKWLK3545rM2ccPUPd56LmEG2cWBG00](https://user-images.githubusercontent.com/38358698/61149745-dfa6e680-a4af-11e9-9b70-b806f636347e.png)

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you.

**Comment by stanwest** [comment]
You're welcome, and thank you for the quick fix.

Is it intentional for notes attached to messages to affect the horizontal position of the duration, as shown below?
````
@startuml
!pragma teoz true
participant David
participant Alice
participant Bob
participant Charlie
{1} Alice -> Bob: 1
& note left of David: note
{2} Alice -> Bob: 2
note left: note
{3} Alice -> Bob: 3
note left: note
{4} Alice -> Bob: 4
{5} Alice -> Bob: 5
{6} Alice -> Bob: 6
note right: note
{7} Alice -> Bob: 7
note right: note
{8} Alice -> Bob: 8
& note right of Charlie: note
{1} <-> {2}: far-left and left notes
{2} <-> {3}: two left notes
{3} <-> {4}: one left note
{4} <-> {5}: no notes
{5} <-> {6}: one right note
{6} <-> {7}: two right notes
{7} <-> {8}: right and far-right notes
@enduml
````

![server](https://user-images.githubusercontent.com/38358698/61225972-a52b8c80-a6ef-11e9-8428-bd01abaf584f.png)

**Comment by The-Lum** [comment]
_[Just for the record]_

See similar issues/requests here:
- https://forum.plantuml.net/13032/how-to-prevent-duration-arrows-to-overlap
- https://forum.plantuml.net/17929/anchors-and-duration-bad-positioning

**Comment by stanwest** [comment]
It appears that the original issue may be closed.
