### ISSUE TITLE
Teoz renderer does not support "mainframe" keyword

### ISSUE THREAD

**Issue by stanwest** [plantuml/plantuml#230]
What is needed for the *teoz* renderer to support the "mainframe" keyword (issue #148)?

**Comment by arnaudroques** [comment]
Well, this was not yet implemented.
However, you can try beta version http://beta.plantuml.net/plantuml.jar that should work with teoz and mainframe.
Tell us if it's not working for you !

**Comment by stanwest** [comment]
Thank you for the quick implementation.

Does the frame account for the positions of notes? For example, I noticed that the frame doesn't entirely enclose notes in some cases such as the following diagram:

    @startuml
    mainframe Frame
    participant Alice
    note left of Alice: note
    @enduml

*PlantUML* 1.2019.09beta5 renders the above as 

![mainframe](https://user-images.githubusercontent.com/38358698/61544483-93115d00-aa13-11e9-9698-60e2f68146ac.png)

but, with `!pragma teoz true` inserted, as

![mainframe-teoz](https://user-images.githubusercontent.com/38358698/61544495-9b699800-aa13-11e9-9d37-022b444041c6.png)

**Comment by The-Lum** [comment]
_Just to confirm or not an old issue..._
It is now fully corrected, as:

>[![](http://www.plantuml.com/plantuml/svg/9Smn3e0W38NXlQUert32nNiqM4mJMaWjYwSNulA6Boz_Ue8yXbROkjEjXC7jnV3104fYnKaPpxNGvrMoTBB0eqfci1QCbKjWAp_jk0mIspMh7m00)](http://www.plantuml.com/plantuml/umla/9Smn3e0W38NXlQUert32nNiqM4mJMaWjYwSNulA6Boz_Ue8yXbROkjEjXC7jnV3104fYnKaPpxNGvrMoTBB0eqfci1QCbKjWAp_jk0mIspMh7m00)

**Comment by stanwest** [comment]
> It is now fully corrected

Agreed; this issue seems to have been addressed between the beta and final releases, because *PlantUML* 1.2019.09 draws the example correctly using the *teoz* renderer. Thank you for following up.
