### ISSUE TITLE
Nwdiag stylesheets don't work

### ISSUE THREAD

**Issue by Dzordzu** [plantuml/plantuml#232]
They just seem to be ignored

**Comment by mblaschke** [comment]
can confirm it, is there any workaround?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed, using `style`.

- Thanks @Dzordzu, @mblaschke  for the report.
- Thanks PlantUML team for your work.

---
See full example on the [`nwdiag` doc.](https://plantuml.com/nwdiag):
>[![](https://www.planttext.com/api/plantuml/svg/XLDTIyCm57tlhxZK1rzasg8eJ4LK5C69e0z3yU6skTQmxAOacRNA_hjfMkTMfn82z_kSdjoUM8V6pQOgEhIkLdGSSIKa5kV-6fp2HmJ0v2fj9i46ECLyScdqZCMPLjf0OOWuPAubKnip91QH-nUPJvYiXMIm4w8NcjsTV2T83XP-syVuMllGt5zBvfNCBvYbv4aFiYQbTFK7wcR06O_7e5dLyEnx1DdSoD99pU1TXHcfVnXkP6f67KKqHbSTmpNJKGZJ4EXDtEzF_1Ah2TtWb62aMTiIyoKHsz9CUHqwyCBBKVuYJuw2N4TqNNzVelJ7moJVVhCLa6dLaXcXAIJ3Nd1k_ITABe8tZ-RHuVRA3gqip_deeMCB2sME8Au7RytPJdVZBbbHjfF0uu-Q97uQBfMaQqhIjcGUDNLVm5Vio32g3ZsC7oxCj3L57xCQDESztWBxWYNva4276Lfg8I1WhBp2yZRv2KfxPTfyMAnu-0_-i5FnX5Zu7_8J)](https://www.planttext.com/?text=XLDTIyCm57tlhxZK1rzasg8eJ4LK5C69e0z3yU6skTQmxAOacRNA_hjfMkTMfn82z_kSdjoUM8V6pQOgEhIkLdGSSIKa5kV-6fp2HmJ0v2fj9i46ECLyScdqZCMPLjf0OOWuPAubKnip91QH-nUPJvYiXMIm4w8NcjsTV2T83XP-syVuMllGt5zBvfNCBvYbv4aFiYQbTFK7wcR06O_7e5dLyEnx1DdSoD99pU1TXHcfVnXkP6f67KKqHbSTmpNJKGZJ4EXDtEzF_1Ah2TtWb62aMTiIyoKHsz9CUHqwyCBBKVuYJuw2N4TqNNzVelJ7moJVVhCLa6dLaXcXAIJ3Nd1k_ITABe8tZ-RHuVRA3gqip_deeMCB2sME8Au7RytPJdVZBbbHjfF0uu-Q97uQBfMaQqhIjcGUDNLVm5Vio32g3ZsC7oxCj3L57xCQDESztWBxWYNva4276Lfg8I1WhBp2yZRv2KfxPTfyMAnu-0_-i5FnX5Zu7_8J)

See also _Ref._ here:
- [QA-14516](https://forum.plantuml.net/14516/skinparam-shadowing-in-nwdiag)
- [QA-14479](https://forum.plantuml.net/14479/style-allow-style-on-nwdiag-diagram)
- [QA-14478](https://forum.plantuml.net/14478/applying-themes-on-nwdiag-has-no-effect)
---

Regards.
