### ISSUE TITLE
Template parameter boxes rendered with no lines in eps

### ISSUE THREAD

**Issue by rocher** [plantuml/plantuml#233]
Hi,

In the diagram:
```
@staruml
class Foo<Param>
class Bar<P, Q>
@enduml
```
the dashed edges of the template parameter box are not rendered in eps format. In other formats, like png, svg, dashed edges are rendered as usual.

EPS:
![Screenshot from 2019-07-18 20-17-55](https://user-images.githubusercontent.com/1971599/61481958-bdbecf80-a999-11e9-93fe-fa8428684011.png)

PNG:
![template-eps](https://user-images.githubusercontent.com/1971599/61481761-3bcea680-a999-11e9-826f-109cc22b6675.png)

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you !

**Comment by rocher** [comment]
Many thanks!!  It work fine now!!
