### ISSUE TITLE
Plantuml class diagram: line not vertical

### ISSUE THREAD

**Issue by chenzz** [plantuml/plantuml#237]
The line between Product and ConcreteProduct is not vertical, 
could you please fix this~!

example,

```plantuml
@startuml

together {
    interface Product
    Product <|.d. ConcreteProduct
}

together {
    class SimpleFactory {
        Product create()
    }
    SimpleFactory -r-> Product
    
}
@enduml
```

![image](https://user-images.githubusercontent.com/5676311/61584984-2a95bd80-ab84-11e9-807c-5ef176a813c0.png)

**Comment by skewty** [comment]
Admittedly, I am new to PlantUML, but I don't remember any assurance / guarantee of right angles in the documentation.  Are you sure this is a bug?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is a normal behaviour due to:
- the `together` directive;
- the layout engine (`Graphviz` or `smetana`).

Then:
- Thanks @chenzz for the report.
- Thanks PlantUML team for your work.

---

See code (without `together`) and expected result:
```puml
@startuml
interface Product
Product <|.d. ConcreteProduct

class SimpleFactory {
    Product create()
}
SimpleFactory -r-> Product
@enduml
```
>[![](https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuShCAqajIajCJbK8ACfFAKqkuOBI2ZOrUYbw2ixvUSb5gIMfC5ckv9p4ucA5uCpSWfnKjyJaaloYIeLgBWKWW6a4gayiITNGvAhbGbMcMwHh1xV68JKl1UW00000)](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuShCAqajIajCJbK8ACfFAKqkuOBI2ZOrUYbw2ixvUSb5gIMfC5ckv9p4ucA5uCpSWfnKjyJaaloYIeLgBWKWW6a4gayiITNGvAhbGbMcMwHh1xV68JKl1UW00000)

Regards.
