### ISSUE TITLE
Upgrade to v3.0 awslib icons

### ISSUE THREAD

**Issue by fixl** [plantuml/plantuml#241]
# Description

PlantUML currently seems to ship with v1.0 of https://github.com/awslabs/aws-icons-for-plantuml

Some of the icons we'd like to use aren't in that version.

# Solution

Ship PlantUML with v3.0 of the above icons.

# Notes

@arnaudroques  I couldn't work out how to create those `awslib-*.repx` files. If you could share how that's done (in this issue or in the wiki section), I'll put through a PR.

**Comment by arnaudroques** [comment]
The way to go is to create a PR on https://github.com/plantuml/plantuml-stdlib with the icons to be added.
The `*.repx` are created from this source.

**Comment by fixl** [comment]
Cheers @arnaudroques 

I have raised https://github.com/plantuml/plantuml-stdlib/pull/9

So I guess this can be closed?
