### ISSUE TITLE
package in deployment diagram layout issue

### ISSUE THREAD

**Issue by georgexsh** [plantuml/plantuml#242]
from doc example (http://plantuml.com/deployment-diagram):
```
@startuml
artifact Foo1 {
  folder Foo2
}

folder Foo3 {
  artifact Foo4
}

frame Foo5 {
  database Foo6
}

cloud vpc {
  node ec2 {
	stack stack
  }
}
@enduml
```
result in doc:

![result in doc](http://s.plantuml.com/imgw/deployment-diagram-0jigss3b.png)

actual result with 1.2019.08:

![test](https://user-images.githubusercontent.com/32751/62829154-f749ca00-bc29-11e9-8773-2e4055627ba1.png)

there is too little margin space for text.

**Comment by arnaudroques** [comment]
The online server gives a correct result
http://www.plantuml.com/plantuml/uml/JOuz3W9128LhEGLNSFsfj_8U26nYd5tCB6DZvkuoDDf0Fhv7ykRTgNfR2yHwBCIEDxCZVW1niI9Q1q_G0NvuIlt_SCv0fLK7NT8BETrfpyjrU2xM1DylJhsPA2fF0OSemK_C6QP7UDPDejKN

Could you double check your version and tell us more about your environment ? Thanks

**Comment by georgexsh** [comment]
@arnaudroques thanks for you reply, here is version info:
```
$ plantuml -version
PlantUML version 1.2019.08 (Sun Jul 14 03:25:14 CST 2019)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.8.0_72-ea-b05
Operating System: Mac OS X
OS Version: 10.14.6
Default Encoding: UTF-8
Language: zh
Country: CN
Machine: bogon
PLANTUML_LIMIT_SIZE: 4096
Processors: 4
Max Memory: 3,817,865,216
Total Memory: 257,425,408
Free Memory: 250,697,712
Used Memory: 6,727,696
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has been set to /usr/local/opt/graphviz/bin/dot
Dot executable is /usr/local/opt/graphviz/bin/dot
Dot version: dot - graphviz version 2.40.1 (20161225.0304)
Installation seems OK. File generation OK
```

is installed from homebrew:
```
$ brew info plantuml
plantuml: stable 1.2019.8
Draw UML diagrams
https://plantuml.com/
/usr/local/Cellar/plantuml/1.2019.8 (4 files, 7.5MB) *
  Built from source on 2019-07-31 at 13:54:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/plantuml.rb
...
```

**Comment by MOZGIII** [comment]
I have the same problem.

Same Graphviz version, PlantUML version 1.2020.07.

**Comment by MOZGIII** [comment]
Turns out adding `!pragma graphviz_dot jdot` makes the server do the same!

Without:
http://www.plantuml.com/plantuml/uml/JOvD3i9028Ntd88hM7_MNNaF19eOfyLCgHlJkmkuq5aC-VWUoHjNf-xRt01YtYTYnwlP0T-0E5aJxSa3x00_F9R-FpXLeDEiIUVoGautMcjpIS_DDi7Naqil9ehAGqAyACAFxn-yHtxKHQBP1m00

With:
http://www.plantuml.com/plantuml/uml/JOuz3i8m34Ptdy8SWV8pT-8QoCHfAIHrbBWTGBqxYHbW-QINzoAvBqfPbnXWbpADaN3CbExhzBgoA3xg0DHY6iWfNaJs-0R4GGBxtBY33U271zF_7uuMP8g-qSayazADYhsSctT15iOrETEpi4VlEWF4ekIUtwsyrRxtCzURFm00

It looks like it's a bug with `dot` that was "countered-effected" at PlantUML so that it cancels out the bug. Or something like that.

**Comment by MOZGIII** [comment]
The `dot` on the server is actually older than `2.40.1` that I have locally: `dot - graphviz version 2.38.0 (20140413.2041)`

Definitely looks like it's an issue with `dot`.

**Comment by arnaudroques** [comment]
`dot 2.38.0` is the right version to use with PlantUML
See https://plantuml.com/en/faq

**Comment by hgross** [comment]
Had to downgrade graphviz/dot to 2.38.0 on a Mac via MacPorts. Took an hour to figure out .. so I will share the solution here:
https://gist.github.com/hgross/67ea67c4fdcf5636ee2dd96e35a154b8/#file-fix-graphviz-for-plantuml-sh

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
- Thanks @georgexsh for the report.
- Thanks to the PlantUML team and everyone who replied for your work.

## OK with `GraphViz` ✔️ 
>[![](https://www.planttext.com/api/plantuml/svg/JOv13eD024NNvHHSGQkkNVKU530nZjACOpUDTvTXOpUGn_iaVzmBvNAi2NpD4t71brc3Fq2SB8dcoYsS03S-G_y_T178j6gbFhnGeJVjSHcgvsI7uFV3eJSJHUNMuU4bUC6ORauFZxg9jxe0)](url_puml)



## But KO with `smetana` :x:
>[![](https://www.planttext.com/api/plantuml/svg/JO_F2i8m3CRFzYdYGT3BSFNFUI1uzGMyP6qcmxOPRJSGsRkR5K4l8Lz-NyYN9cMCUVHEhOU83u_WyCLZXkGfOq0bjE_GPBWor_1M01qxIt7HMirA_UIXuF-5Op54zBIeK-4MCxQOokIySEDuj30Dfk30be2C5h6IREO9fGgPnTmnPpbsQnF5YInmWBhIUtsewhgLmFeUBcEC539C55ClVFDjjZlLKB3owWS0)](https://www.planttext.com/?text=JO_F2i8m3CRFzYdYGT3BSFNFUI1uzGMyP6qcmxOPRJSGsRkR5K4l8Lz-NyYN9cMCUVHEhOU83u_WyCLZXkGfOq0bjE_GPBWor_1M01qxIt7HMirA_UIXuF-5Op54zBIeK-4MCxQOokIySEDuj30Dfk30be2C5h6IREO9fGgPnTmnPpbsQnF5YInmWBhIUtsewhgLmFeUBcEC539C55ClVFDjjZlLKB3owWS0)

Regards.
