### ISSUE TITLE
Supported UML version

### ISSUE THREAD

**Issue by gAllegr** [plantuml/plantuml#246]
I was wondering what is the UML version supported by the tool.
Does it used the latest one? (2.5.1)
Or the desidered UML version can be specified somewhere?

**Comment by VladimirAlexiev** [comment]
There is no formal answer to this. The tool supports:
- a number of UML diagrams
- a variety of non-UML diagrams (graphviz, salt UI mockups, ER, C4 architecture, charts, WBS, Gantt, mindmap etc)
- a bunch of visual features, many of which are not considered by UML (eg icons, links between particular attributes of two classes, extra arrowheads etc etc)

Please close the issue.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @gAllegr for the report.
- Thanks @VladimirAlexiev for your answer.

Regards.
