### ISSUE TITLE
plantuml produces modified SVGs even when source content does not change

### ISSUE THREAD

**Issue by brianhy** [plantuml/plantuml#248]
Hi, we're using plantuml to produce quite a few SVGs.  These are all checked into git.

When we run plantuml it will produce many SVGs that basically haven't changed except for some small metadata pieces.

For example, most files only show the following change:
![image](https://user-images.githubusercontent.com/9301547/63938421-567d4c00-ca2a-11e9-99ec-f42dde45fa83.png)

I appreciate having the full version of all the components that went into producing the SVG, but if the actual SVG content didn't change I was hoping the SVG could be left alone.

I saw a similar request for PNG (https://github.com/plantuml/plantuml/issues/112).  Not sure if anything similar exists or SVG.

Another option, though I like it less, would be to have an option to not emit the OS version string (as that seems to be the bit of metadata that's most volatile).

Any help or guidance would be appreciated.  Thanks!

**Comment by arnaudroques** [comment]
Ok, thanks for your suggestion.
We've done two things with last beta http://beta.plantuml.net/plantuml.jar

- We've removed OS version (not very useful anyway)
- `-checkmetadata` flag is now working with SVG

We added some MD5 signature in SVG comment. This MD5 signature is the signature of the metadata. We have to do so, because sometimes SVG modify metadata (for example when there are some `-->` arrow because it interferes with SVG end comment tag)

Does it help ?

**Comment by brianhy** [comment]
Thanks so much, @arnaudroques.  I ran it locally.  Confirmed the OS version removal.  I also see logs like "Skipping /svg/Attribution.svg because metadata has not changed.", an I assume that this means the `-checkmetadata` flag is working as expected.

I have a question regarding the release of this beta.  We run our plantuml via docker using [think/plantuml:1.2018.5](https://hub.docker.com/r/think/plantuml/dockerfile).  This container allows overriding the version of plantuml but requires it be on sourceforge ([link](https://sourceforge.net/projects/plantuml/files/)).

I tried running the latest version on sourceforge (which is dated Aug 26), but it looks like it doesn't have the fix for removing the OS version output.

Do you know when this beta plantuml will move into sourceforge?

**Comment by arnaudroques** [comment]
> Do you know when this beta plantuml will move into sourceforge?

Yes, it will be probably around mid-september.

**Comment by brianhy** [comment]
Great, thanks.  My issue has been fixed, so I'll close this ticket out.
