### ISSUE TITLE
Logs show warning on certain arrow

### ISSUE THREAD

**Issue by eNeRGy164** [plantuml/plantuml#251]
When generating this diagram:

    @startuml
    actor A
    A -X A
    @enduml

The console shows this message:

    WARNING : CROSSX

I think this is the source, but I don't understand why it should pollute my logs.
https://github.com/plantuml/plantuml/blob/d0fdb2433b36e8bddd4b00ec113511511e3fcfb2/src/net/sourceforge/plantuml/sequencediagram/graphic/Step1Message.java#L267

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @eNeRGy164 for the report.
- Thanks PlantUML team for your work.

Regards.
