### ISSUE TITLE
Org mode mind maps (Using * notation) don't work in an org file

### ISSUE THREAD

**Issue by kreely** [plantuml/plantuml#254]
When using something like the following in an org file

#+begin_src plantuml :file Org.png
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
*** SolydXK
*** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
#+end_src

A file is generated that is kind of broken. This may be a problem in org or in plantuml.

The way to get around it, is to use the ++ style of positioning.

Just letting you know.
[bug.pdf](https://github.com/plantuml/plantuml/files/3608152/bug.pdf)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/JK_T2e8m5BxtAGvqfz0318MGNga9IT5TJ9rsO3iRSwjy-zoAyExxvNndaxHyHBfFfWCj65ad1Um651ngCsurZL4wMMQiHEebqr4C6M-HKHJ7S6dTKbXG32MIUqE5P0CjtCfQuIBBuSHLQ9TLbWUnKMBkRyKNMyvatNZ_p2RjBy4BxGCOFBcPGIWQWPZa8UqZikrWVu2wgOv_RHxGQrSbd4GLfNpP_jk_IHRYt_q0)](https://www.planttext.com/?text=JK_T2e8m5BxtAGvqfz0318MGNga9IT5TJ9rsO3iRSwjy-zoAyExxvNndaxHyHBfFfWCj65ad1Um651ngCsurZL4wMMQiHEebqr4C6M-HKHJ7S6dTKbXG32MIUqE5P0CjtCfQuIBBuSHLQ9TLbWUnKMBkRyKNMyvatNZ_p2RjBy4BxGCOFBcPGIWQWPZa8UqZikrWVu2wgOv_RHxGQrSbd4GLfNpP_jk_IHRYt_q0)
- Thanks @kreely for the report.
- Thanks PlantUML team for your work.

Regards.
