### ISSUE TITLE
New preprocessor breaks existing diagram

### ISSUE THREAD

**Issue by trothwell** [plantuml/plantuml#256]
I've got a customer that has a broken diagram from Preprocessor v2. I know it works in `v1.2018.6`. I've tested in the latest `v1.2019.10`.

Two questions:
1. Are regressions expected from preprocessor v2?
2. What is the minimum diagram change needed to resolve?

I've reduced my 369 line diagram to the following to demonstrate the issue.
```
@startuml
!define declare(macro,first,second) macro(first,second)
!define twopt(name,id = "no_id") card "**name**" as id
declare(twopt,Database Engineering,2pt_databaseengineering)
@enduml
```

**Comment by arnaudroques** [comment]
The minimum diagram change is to use :

```
@startuml
!define declare(macro,first,second) %call_user_func(macro,first,second)
!define twopt(name,id = "no_id") card "**name**" as id
declare(twopt,Database Engineering,2pt_databaseengineering)
@enduml
```

To answer your first question, we try to respect as much as possible backward compatibiliy with the old preprocessor.
Unfortunately, this cannot do at 100%. So there are some few regressions.

Dynamic method invocation is one of the things that are really different between the two preprocessors.

We understand that those changes are annoying, but we really did our best to minimize them.
Do not hesitate to post if you have other questions concerning your migration.

For the record, the complete migrated diagram:

```
@startuml
!unquoted function declare($macro,$first,$second) return %call_user_func($macro, $first, $second)
!unquoted function twopt($name,$id = "no_id") return 'card "**' + $name + '**" as ' + $id
declare(twopt,Database Engineering,2pt_databaseengineering)
@enduml
```

You can safely use both solutions.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @trothwell for the report.
- Thanks PlantUML team for your work.

Regards.
