### ISSUE TITLE
Annotation keyword breaks uml graph generation

### ISSUE THREAD

**Issue by vincentmigot** [plantuml/plantuml#260]
Hi,

I generate java UML documentation with this maven plugin: https://github.com/talsma-ict/umldoclet
It generate plantUML pseudo-code and then integrate produced images into the documentation.
According to your guide "annotation" keyword should be understand but it fails.
I tried to generate directly images with the lastest plantUML version (master) and it doesn't work either.

Bellow is the failing example and the result, do you have any idea why it's not working ?
If you remove the "annotation" block everything works fine.

```
@startuml
    namespace org.opensilex.config {

        class InvalidConfigException [[InvalidConfigException.html]] {
            +InvalidConfigException(Exception)
            +InvalidConfigException(String)
        }

        class ConfigProxyHandler [[ConfigProxyHandler.html]] {
            +ConfigProxyHandler(String, JsonNode, ObjectMapper)
            +invoke(Object, Method, Object[]): Object
            {static} +getPrimitive(String, JsonNode, Method): Object
        }

        annotation ConfigDescription [[ConfigDescription.html]] {
            {abstract} +value(): String
            {abstract} +defaultBoolean(): boolean
            {abstract} +defaultByte(): byte
            {abstract} +defaultChar(): char
            {abstract} +defaultDouble(): double
            {abstract} +defaultFloat(): float
            {abstract} +defaultInt(): int
            {abstract} +defaultLong(): long
            {abstract} +defaultShort(): short
            {abstract} +defaultString(): String
            {abstract} +defaultList(): String[]
            {abstract} +defaultMap(): String[]
            {abstract} +defaultClass(): Class<?>
        }

        class ConfigManager [[ConfigManager.html]] {
            +addSource(String): void
            +addLines(String...): void
            +addSource(InputStream): void
            +addSource(File): void
            +addSource(JsonNode): void
            +loadConfig(String, Class<T>): T
            +loadConfigPath(String, Class<T>): T
            +toYaml(OutputStream): void
            +build(Path, Iterable<OpenSilexModule>, String, File): void
        }

        java.lang.Exception <|-- InvalidConfigException
        java.lang.reflect.InvocationHandler <|.. ConfigProxyHandler
    }

    namespace java.lang {
        class Exception [[https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html?is-external=true]] {
        }
    }

    namespace java.lang.reflect {
        interface InvocationHandler [[https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/InvocationHandler.html?is-external=true]] {
            {abstract} +invoke(Object, Method, Object[]): Object
        }
    }

    center footer UMLDoclet 2.0.5, PlantUML 1.2019.08
@enduml
```

![plantUML failure](https://user-images.githubusercontent.com/42962790/65704196-5eaac480-e086-11e9-9843-397d3890c68b.png)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @vincentmigot for the report.
- Thanks PlantUML team for your work.

>[![](https://www.planttext.com/api/plantuml/svg/dPPVRzem4C3V-HH-cKHLchHxwYf6gxMhnWG5YUvXGZmuyG7k73kodOYgxNVVENyWD66XyujD_Blp-SvtnusnLDia4Xs2Gz88J4n384glF1M3D5p0nWkLNF8LUUbab1kXeCQGeKofuEmss_w-2I6sN4aodpTlU6iRYSK2zP3AE6s6kzlLoL7up6ekLplsxRsnkS1Kgytp3ogP08s6rZyUCB8E5YVso4-Zv8DYq2EJu0b2EwPn3FgTrLocwWzqSw97nc3NYfKIyyN9LR7Sath1w5WUlf7J5TYfvX6tF8M6WtDrTIKL9r0fbTE6ySdlSWScrBoCMErRinzUQ62ifg55cp0C2NJnqDoUWno39Ks4_QQK02gTG90lMoMURQO_mBcDlLrJxTWGvpRsJYM1o3IpRDN6tmj5hSENRj563sN6SjbAZfHSELIeTk_DrafdUerRjD9PH8wFpOWRkwFdYpOUd_X7y5kNW4uWM_Il1srPEgQIhYe9Mlm-a9kKiPbAT5Xc1XwKAivgq8XBC0NZUTuXhD0rb77Y70aqQY7liKYs86MgDcBugefojatjt56F0-GV3y5JQjT725ZrcqQYEqdil-yJ95omhbFQ8qCBcc9cz2VO0sQk1umLImGCUgGyiEdIbMW-qPHwWgAZTtsX_tfsTg1dDCXfM0giPHuAg30hN6NPxhzwNaCvxrHCs7MohSBAgycVMhLXhQsDpPNlCnKQJ-7h5O1TB_ATj07_CjlmQSopBxxJv-_tjMjkpc23VfDKVBKwWRrt-jPYN7dRYWWM4D1BHzKzy7y65sVuDNr7NC2DQcP_k9_jUI04TpcoLCfDay20Je6HAPffVur7vCBxV7xnnJk_93vv16Dn3yFqAGLjNAy_wTo0PFYlvIy0)](https://www.planttext.com/?text=dPPVRzem4C3V-HH-cKHLchHxwYf6gxMhnWG5YUvXGZmuyG7k73kodOYgxNVVENyWD66XyujD_Blp-SvtnusnLDia4Xs2Gz88J4n384glF1M3D5p0nWkLNF8LUUbab1kXeCQGeKofuEmss_w-2I6sN4aodpTlU6iRYSK2zP3AE6s6kzlLoL7up6ekLplsxRsnkS1Kgytp3ogP08s6rZyUCB8E5YVso4-Zv8DYq2EJu0b2EwPn3FgTrLocwWzqSw97nc3NYfKIyyN9LR7Sath1w5WUlf7J5TYfvX6tF8M6WtDrTIKL9r0fbTE6ySdlSWScrBoCMErRinzUQ62ifg55cp0C2NJnqDoUWno39Ks4_QQK02gTG90lMoMURQO_mBcDlLrJxTWGvpRsJYM1o3IpRDN6tmj5hSENRj563sN6SjbAZfHSELIeTk_DrafdUerRjD9PH8wFpOWRkwFdYpOUd_X7y5kNW4uWM_Il1srPEgQIhYe9Mlm-a9kKiPbAT5Xc1XwKAivgq8XBC0NZUTuXhD0rb77Y70aqQY7liKYs86MgDcBugefojatjt56F0-GV3y5JQjT725ZrcqQYEqdil-yJ95omhbFQ8qCBcc9cz2VO0sQk1umLImGCUgGyiEdIbMW-qPHwWgAZTtsX_tfsTg1dDCXfM0giPHuAg30hN6NPxhzwNaCvxrHCs7MohSBAgycVMhLXhQsDpPNlCnKQJ-7h5O1TB_ATj07_CjlmQSopBxxJv-_tjMjkpc23VfDKVBKwWRrt-jPYN7dRYWWM4D1BHzKzy7y65sVuDNr7NC2DQcP_k9_jUI04TpcoLCfDay20Je6HAPffVur7vCBxV7xnnJk_93vv16Dn3yFqAGLjNAy_wTo0PFYlvIy0)

Regards.
