### ISSUE TITLE
CSS over two lines

### ISSUE THREAD

**Issue by astonfe** [plantuml/plantuml#263]
CSS over two lines works in plantuml.1.2019.10 but not in plantuml.1.2019.11.

`@startmindmap
skinparam {
    backgroundcolor transparent
    defaultfontname ubuntu
    shadowing false
}

<style>
s1 {
    BackgroundColor #E74C3C
}
s2 {
    BackgroundColor #3498DB
}
</style>

* Mqwerty\npoiuyt
** Qwertyu\npoiuytr <<s1>>
** Asdfghj\nlkmnbvc <<s2>>
@endmindmap`

![plantuml 1 2019 10](https://user-images.githubusercontent.com/11715301/65954483-5d8ee400-e446-11e9-93ec-3ca4dac70f16.png)

![plantuml 1 2019 11](https://user-images.githubusercontent.com/11715301/65954495-61226b00-e446-11e9-906a-150c247b2a0b.png)

**Comment by arnaudroques** [comment]
Thanks for the report.
However, the formatting has broken your examples.
Could you repost the non-working example ? Thanks.

**Comment by astonfe** [comment]
Thanks for the answer. I have attached a screenshot, to avoid any changes in formatting.

![test](https://user-images.githubusercontent.com/11715301/66026181-87084800-e4f8-11e9-8369-25a601c3694d.png)

**Comment by arnaudroques** [comment]
Thanks for the example, and sorry for the regression.
This is fixed in last beta http://beta.plantuml.net/plantuml.jar

Tell us if it's not working for you or if you find other issues !

**Comment by astonfe** [comment]
It works great.

**Comment by astonfe** [comment]
It's ok and so I think that's possible to close this issue.
