### ISSUE TITLE
Generated images are different between Linux and macOS

### ISSUE THREAD

**Issue by Kernald** [plantuml/plantuml#266]
With the same PlantUML/Dot/Graphviz versions, the same font etc, the same graph is rendered differently on Linux and macOS:
<img width="359" alt="Screen Shot 2019-10-08 at 9 35 02 pm" src="https://user-images.githubusercontent.com/296840/66389441-19867b00-ea14-11e9-9f65-e5f466b65702.png">

(macOS on the left, Linux on the right)

**Comment by skewty** [comment]
I am not certain about the reason that is happening to you, but:

1. some font rendering techniques are highly patented (so the algorithms are not the same OS to OS).  Font rending is highly customizable.
2. font engines substitute the next best matching font if a requested font doesn't exist.  
3. fonts get revised over time.  Ensure you are using the same version of the font in both systems.  

It is possible a combination of these reasons are affecting you.
