### ISSUE TITLE
preserveAspectRatio is not configurable

### ISSUE THREAD

**Issue by sashee** [plantuml/plantuml#267]
The ```preserveAspectRatio``` is [fixed](https://github.com/plantuml/plantuml/blob/c4397fac972b9bd38779947e88fdd8ef39e56a2d/src/net/sourceforge/plantuml/svg/SvgGraphics.java#L597) as ```none``` for SVG diagrams, which makes the image skewed if the width is less than the viewbox. This can happen when the diagram has a max-width property and viewed on a mobile browser.

Please make it at least configurable.

**Comment by arnaudroques** [comment]
Ok, so with last beta http://beta.plantuml.net/plantuml.jar you can now have

```
@startuml
skinparam preserveAspectRatio xMinYMid slice
start
:foo1;
stop
@enduml
```

Is this what you were expecting ?

**Comment by sashee** [comment]
Yeah, that seems great!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @sashee for the report.
- Thanks PlantUML team for your work.

Regards.
