### ISSUE TITLE
Tilde character cannot be escaped

### ISSUE THREAD

**Issue by Kane-eNote** [plantuml/plantuml#268]
It looks like the creole support does not allow to escape the escape character.

I have tried the following scenarios

```plantuml
@startuml

cloud failure {
  rectangle "initial: test~*" as a
  rectangle "backslash: test\~*" as b
  rectangle "double-tilde: test~~*" as c
}

cloud workarounds {
  rectangle "whitespace-after: test~ *" as w_1
  rectangle "tilde character as unicode: test<U+007E>*" as w_2
}

@enduml
```

Version was: 1.2019.12beta6

**Comment by arnaudroques** [comment]
Thanks for the feeback.
With last beta http://beta.plantuml.net/plantuml.jar
You can now escape the tilde with a backslash: `\~`

Hope this makes sense.
The creole specification is not very precise on this, so any comment is welcome.

**Comment by Kane-eNote** [comment]
Thanks a lot. I can now drop the unicode variant I've just up to now. :)
