### ISSUE TITLE
Can't use a '( something )' inside another comment 

### ISSUE THREAD

**Issue by mmouatta** [plantuml/plantuml#273]
I'm trying to use parenthesis inside a comment but I keep getting errors
for example :  ( Text (1) ) , this doesn't work

**Comment by swmatisa** [comment]
Could you please provide a full example?

**Comment by mmouatta** [comment]
I'm trying to use parenthesis inside a comment but I'm not allowed
For example : ( this is my comment)  this one works but this one (this is a comment ( abc)) doesn't.

**Comment by arnaudroques** [comment]
Which version of PlantUML are you using ?
The following example is working for us :

```
@startuml
' This comment is working for us: (this is a comment ( abc))
Bob -> Alice : hello
@enduml

```

**Comment by mmouatta** [comment]
I m trying to do this
@startuml
( A (abc) ) --> (B)
@enduml
I guess it's more like a use case with parenthesis inside. is there a way to escape the characters '('  and ')' ?

**Comment by ErikAnderson3** [comment]
@mmouatta --

It seems to be possible to use the numeric ASCII codes for the parentheses to turn the parentheses into entities.  Testing the sample diagram generator at https://plantuml.com/ , the following appears to work just fine:

( A &#40;abc&#41; ) --> (B)

**Comment by mmouatta** [comment]
> @mmouatta --
> 
> It seems to be possible to use the numeric ASCII codes for the parentheses to turn the parentheses into entities. Testing the sample diagram generator at https://plantuml.com/ , the following appears to work just fine:
> 
> `( A &#40;abc&#41; ) --> (B)`

It actually worked, Thank you :)

**Comment by ErikAnderson3** [comment]
@mmouatta, glad it worked!
