### ISSUE TITLE
Typesetting problem

### ISSUE THREAD

**Issue by willin** [plantuml/plantuml#276]
```plantuml
@startuml 
skinparam rectangle {
  roundCorner<<App>> 25
  roundCorner<<BSS>> 25
	roundCorner<<OSS>> 25
}

actor 用户 as user
actor 审核员 as checker


rectangle " " <<App>> as App {
	(查看主题包相关内容) as (project_view)
	(复制场景) as (scene_copy)
	
	(scene_copy) .> (project_view) : extends
	user -> (project_view)
}

rectangle " " <<BSS>> as BSS {
	(DataSet管理) as (dataset)
	card 主题包管理 as project {
		(创建主题包) as (project_upload)
		(主题包审核) as (project_verify)
	}
	
	checker -> (dataset)
	user -> (project_upload)
	checker -> (project_verify)
	project .> (dataset) : extends
	(scene_copy) .> (project_upload): includes
}

@enduml
```

<img width="894" alt="WX20191219-154258@2x" src="https://user-images.githubusercontent.com/1890238/71154359-55408b00-2276-11ea-8323-c76b2d1e9bb8.png">

the connection lines look very strange... and  crowd together

**Comment by The-Lum** [comment]
Hello @willin,

Without answer, here is a proposal: You can add `left to right direction` and modify some `user/checker` arrows as:
```puml
@startuml
left to right direction
skinparam rectangle {
  roundCorner<<App>> 25
  roundCorner<<BSS>> 25
	roundCorner<<OSS>> 25
}

actor 用户 as user
actor 审核员 as checker


rectangle " " <<App>> as App {
	(查看主题包相关内容) as (project_view)
	(复制场景) as (scene_copy)
	
	(scene_copy) .> (project_view) : extends
	user --> (project_view)
}

rectangle " " <<BSS>> as BSS {
	(DataSet管理) as (dataset)
	card 主题包管理 as project {
		(创建主题包) as (project_upload)
		(主题包审核) as (project_verify)
	}
	
	checker --> (dataset)
	user -> (project_upload)
	checker -> (project_verify)
	project .> (dataset) : extends
	(scene_copy) .> (project_upload): includes
}
@enduml
```
>![](http://www.plantuml.com/plantuml/svg/RP3DpX8n68NNqwjuumeMi31nGyW4V_Okk03IT5vWP6WdRSUV69OG4ZNHn0K64iLeuWeN9efmEtOcteMj1UQZ-SAcd3azVSxfAKsbBgOPoN2eGGkGwMYi8KabCfqAJjGavJcLT0fEeNoK8Rma058KF7ae94VPxTxFypY6k_T2_K6_x_NeIdvybcU4KAQ5XEhzjtBv2wY2Gg4yYMQtBJ_jpRkLqzaOsGGb8QJck6D_fyUTnHuiMjGeFtwjDg_-x8z_Fw_Cwtcrtflv3xEOcztlflCrSYcU8DE3foa-QzeBviiRi_nfDeVomtVlK0mv3fZ8NzZl9Bhv7zfna00TmESQUQ98vF2XrGejhcd0xSRntFRmd_iHrRIFkjfjgxSBpv5OIQ6s48pA12wTlCTPJi-u05jakJR7myLrtRR8Cq6JflDT77xYO1MKwT3rdhdgVdVVgSRnFPqKfjSNubiYpxJjEkngld3eCBu3AMTPaQ0YCzApTuffzWy0)

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @willin for the report.

Regards.
