### ISSUE TITLE
{{ triggers a bug

### ISSUE THREAD

**Issue by techone577** [plantuml/plantuml#278]
@startuml
[*] --> LexTop
LexTop --> LexTop: {{
@enduml

**Comment by The-Lum** [comment]
Hello @techone577,

FYI, `{{` is use to manage sub-diagram as:
```plantuml
@startuml
[*] --> LexTop
LexTop --> LexTop: {{\n node n\n}}
@enduml
```

> [![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuOhMYbNGrRLJy4cj2Calu89GI29M2jNLCNaAUVafgGfvCNcrjLmEgNafG9q0)
> _See on online server_](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuOhMYbNGrRLJy4cj2Calu89GI29M2jNLCNaAUVafgGfvCNcrjLmEgNafG9q0)

Then if you want only text, you can use:
```plantuml
@startuml
[*] --> LexTop
LexTop --> LexTop: ""{{""
@enduml
```

> [![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuOhMYbNGrRLJy4cj2Calu89GI29M2afArTLAIbmEgNafG0q0)
> _See on online server_](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuOhMYbNGrRLJy4cj2Calu89GI29M2afArTLAIbmEgNafG0q0)
> 

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @techone577 for the report.

Regards.
