### ISSUE TITLE
teoz duration render throws NullPointer when any of 2 anchors is missing

### ISSUE THREAD

**Issue by akovantsev** [plantuml/plantuml#294]
```
@startuml
!pragma teoz true
{a} Bob -> Alice : hello
{a} <-> {b} : foo
@enduml
```

https://www.plantuml.com/plantuml/png/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvQfEh5LmoazIqBLJSCp9J4vLi5B8ICt9oGTBs015gvDgWM9f-VbS3gbvAK130000

here:
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/sequencediagram/LinkAnchor.java#L86-L87

called by:
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/sequencediagram/teoz/PlayingSpace.java#L119-L121

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvQfEh5LmoazIqBLJSCp9J4vLi5B8ICt9oGTBs015gvDgWM9f-VbS3gbvAK130000)](https://www.planttext.com/?text=SoWkIImgAStDuL8iA4fCpqrKA4dDhr8eAIfDvQfEh5LmoazIqBLJSCp9J4vLi5B8ICt9oGTBs015gvDgWM9f-VbS3gbvAK130000)

- Thanks @akovantsev for the report.
- Thanks PlantUML team for your work.

Regards.
