### ISSUE TITLE
Relationship to nested namespace removes the target.

### ISSUE THREAD

**Issue by glingener** [plantuml/plantuml#298]
I try to link a field to an interface in a lower namespace. But instead of getting the arrow from the field to the target interface, the interface is being removed from the display.

```
@startuml
namespace FirstLevel {
  class A {
   b: InterfaceB
   c: InterfaceC
  }

  ' BUG: Following line does not work and even worse, it removes the InterfaceB from the diagram display.
  ' Comment next line and the interfaceB is displayed.
  A::b --> FirstLevel.SecondLevel.InterfaceB

  ' Linking a field to a different namespace interface is working fine.
  A::c --> Another.InterfaceC
}

namespace FirstLevel.SecondLevel {
  interface InterfaceB {}
  class B {}
}

namespace Another {
  interface InterfaceC {}
  class C {}
}
@enduml
```

What I get:
<img width="386" alt="what-i-get" src="https://user-images.githubusercontent.com/1089098/76333490-042eb900-62f2-11ea-8af7-d74de1730cdb.png">

Expected:
<img width="482" alt="expected" src="https://user-images.githubusercontent.com/1089098/76333478-ff6a0500-62f1-11ea-8663-dd353a636aaa.png">

See:
http://www.plantuml.com/plantuml/uml/TP71JWCX68JlFCNSlDW-m1vCjvlKcFHcV02w_5HI-6c0jfhDlhj0NUMW9s32pCVyR6AI8LsS5ImTnRCS2JiJOjhJbImc0OnMneY-xd7eyCA9WiuNjqKO6s78mYm4y83jstE7dRVMtmmVOGqJbAS8zWat7qwGh90PN4wH7c4I0Zb_fOZqJWq5EdXNDMNaCKYNrtYsydDTIODtZZY1wIDLJaqkryrlX8cBYLInzLrtm6hrr7HTlzBeMTttJSSAsHi-bHuIsf3DyHuo9sfDeR2NsJNCWYmzYqiRfc_gMAaz-_p0i6ucDui_Vw1z5IOXq12Q4KtppqVLGvksqFwr3wrzkDitnEhYx1S0

**Update**: It's also happening doing a class relationship.

http://www.plantuml.com/plantuml/uml/TP71RW8X68Jl-nHpwwNw01uQTHER9jwQFW1TVYmH_jy0QXkpxrxOZSB5ooxyOUPZXdLCAgIpTnqhJ_6a1iBEXfZsT267MmSCJiM8pRJ6zmeVd2YOV71R1aCpwFDWxFBd1TklznLsufnSBH_WB1EqK0HBmbN24OerCeFBBj8hR48WBnUAI3_KK622-6cchJe4vVC_dfpwMqwaNhmdJc3wJJEdE9VZjbhOU1UHBh8D5ekt9kZoamPXFQyhUiwojtmi8HIC9PUz1IhR6KEXW6jn3s3XbP15PInJHMvOyjN2ikbix6htJwwKk-zGxTjoRkFZYQPDwtQdFPNthRoVvMjYVVRk7m00

**Comment by sjoerdtalsma** [comment]
@CGlingener could you re-test with `1.2020.15` or newer to verify that this issue is now fixed?
Mine was (#337)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @glingener for the report.
- Thanks PlantUML team for your work.

---
```puml
@startuml
namespace FirstLevel {
  class A {
   b: InterfaceB
   c: InterfaceC
  }
}

namespace FirstLevel.SecondLevel {
  interface InterfaceB {}
  class B {}
}

namespace Another {
  interface InterfaceC {}
  class C {}
}

A::b --> FirstLevel.SecondLevel.InterfaceB
A::c --> Another.InterfaceC
footer 1.2023.2beta2 / %version()
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/TL112i8m4Bpd5NiHzD2eyPQ3D1O4mPilIDCj5jga9B6NahyRIzK8zZOxpCpkREwyjFxHjKJB3bql5SAviSvVSS0MHWAWMkaSY0b3oU6YFTew2aylGYL44Ob00lcRHM-eZAw-kStRbYJ263uRf-4dJ6ZZxsYNt4NgBcQtuBo4B3ikN4AJDb6g9kcyXoR5QcCYXZrbEtQWh4Gl6MnXDQ1rZT7h3SbHL_6FJm00)](https://www.planttext.com/?text=TL112i8m4Bpd5NiHzD2eyPQ3D1O4mPilIDCj5jga9B6NahyRIzK8zZOxpCpkREwyjFxHjKJB3bql5SAviSvVSS0MHWAWMkaSY0b3oU6YFTew2aylGYL44Ob00lcRHM-eZAw-kStRbYJ263uRf-4dJ6ZZxsYNt4NgBcQtuBo4B3ikN4AJDb6g9kcyXoR5QcCYXZrbEtQWh4Gl6MnXDQ1rZT7h3SbHL_6FJm00)


Regards.
