### ISSUE TITLE
Anchors and Duration with groups: Do not work  [sequence diagram] 

### ISSUE THREAD

**Issue by AlbertMietus** [plantuml/plantuml#299]
When a duration is "plotted" using 2 anchors _INSIDE_ a **group**, that line is forgotten! 

Using the example on the website, with a group added, does trigger the flaw: everything is drawn, but the duration. Removing the "group/end" lines removed the group, and the duration becomes visual again

```
@startuml
!pragma teoz true

group #red A
 {start} Alice -> Bob : start doing things during duration
 Bob -> Max : something
 Max -> Bob : something else
 {end} Bob -> Alice : finish

 {start} <-> {end} : This is not plotted
end
@enduml
```

Hope this can be fixed

**Comment by chipbite** [comment]
Hello @AlbertMietus  - This now works as expected, I noticed. 

Can you close this?

<img src="http://www.plantuml.com/plantuml/png/HOvHQiGm34J_TOef_Uu5GYb9__lN2xYrDZ7OLh1bM7R9tLTn204ZmSmRZyQghcXBaTxMukRae2mFQ6bCD1TfAzuBUqo4PqStJ37yCpw-y2r_6D1LU0bvXYusAtmhjlVbD4YcJbhWnzttW2Jk87NX-kZKmR6ozN7ssnazIWVSGWvreUkQJpCFSi3l4YhiPL6iKLJParaqscWflW00" />

Example here: http://www.plantuml.com/plantuml/umla/HOvHQiGm34J_TOef_Uu5GYb9__lN2xYrDZ7OLh1bM7R9tLTn204ZmSmRZyQghcXBaTxMukRae2mFQ6bCD1TfAzuBUqo4PqStJ37yCpw-y2r_6D1LU0bvXYusAtmhjlVbD4YcJbhWnzttW2Jk87NX-kZKmR6ozN7ssnazIWVSGWvreUkQJpCFSi3l4YhiPL6iKLJParaqscWflW00

**Comment by AlbertMietus** [comment]
Will check soon, but it looks good 

thanks

**Comment by AlbertMietus** [comment]
It works

**Comment by gmarupilla** [comment]
Can we move/control the position of the `This is not plotted` arrow?

**Comment by The-Lum** [comment]
Hi @gmarupilla, and all,

See similar requests (and possible _not so good_ workaround) here:
- https://forum.plantuml.net/17929/anchors-and-duration-bad-positioning
- https://forum.plantuml.net/15787/placing-of-transaction-duration-in-sequence-diagram
- https://forum.plantuml.net/13604/request-sequence-diagram-style-duration-arrow

Regards,
Th.
