### ISSUE TITLE
Cannot change separator on backward items

### ISSUE THREAD

**Issue by oliv3r** [plantuml/plantuml#309]
When doing
```plantuml
start
repeat :foo as starting label;
  :read data;
  :generate diagrams>
  backward :This is backward;
repeat while (more data?)
end
```
we get a nice backward going item, however changing the `;` to for example `>` on the backwarded item, we get the following error:
``` 
start                                        
repeat :foo as starting label;               
  :read data;                                
  :generate diagrams;                        
  backward :This is backward>                
^^^^^                                        
 Syntax Error?      
```

**Comment by arnaudroques** [comment]
Thanks for the report.
It should be fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you !

**Comment by oliv3r** [comment]
Just tried it on plantuml.com/plantuml and it seems to work now :)
![backward separator](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuG8pk8fI2r8JInIiqbDBOhaKG7HUQb5YIQf2IcPYUb5YRh4TK3GfCJcxFB4eHS4g9JKd5KbI7wQ_F2Cp9rL10ogka9-joPMQbyBb02I0TW40)

Thank you for the fast response and fix!
