### ISSUE TITLE
[BUG] Mindmap color not working when using markdown syntax

### ISSUE THREAD

**Issue by bilak** [plantuml/plantuml#310]
Hello,
When I use color on sub node with markdown syntax, plantuml breaks. Color only works on first node.
example:
```
@startmindmap

*[#dd01a4] one
 *[#dd01a4] oneone
  
@endmindmap
```

**Comment by arnaudroques** [comment]
Thanks for the report!
This is fixed in last beta http://beta.plantuml.net/plantuml.jar

Tell us if it's not working for you!

**Comment by bilak** [comment]
that works!
