### ISSUE TITLE
shadow of State Chart start and end is not properly scaled

### ISSUE THREAD

**Issue by ronhippler** [plantuml/plantuml#319]
`scale 4` and png export produces clipped shadows:

![](https://i.ibb.co/2SG9Kwm/test.png)

```puml
@startuml
scale 4
[*] -> State
State -> [*]
@enduml
```

PlantUML Version 1.2020.08
openjdk/13.0.2+8_2
macOS 10.15.4

**Comment by The-Lum** [comment]
FYI, it is better with latest versions... *tested on Version 1.2021.9b2*
>[![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuIfEJin9LJ3XYjQALT2rKmWkIIn9vGAJ82vGb2ijFxyajKWX9iy_gJYrg2mrHI4_Jm48h1GCzOmCZ0prB9DIInADOl8qaakBYbBpIXJAKekAC_Fph1HKeImDJKqkXzIy5A250000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEJin9LJ3XYjQALT2rKmWkIIn9vGAJ82vGb2ijFxyajKWX9iy_gJYrg2mrHI4_Jm48h1GCzOmCZ0prB9DIInADOl8qaakBYbBpIXJAKekAC_Fph1HKeImDJKqkXzIy5A250000)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @ronhippler  for the report.
- Thanks PlantUML team for your work.

Regards.
