### ISSUE TITLE
note top of and bottom of position on class::method does not work

### ISSUE THREAD

**Issue by emiliogq** [plantuml/plantuml#325]
Hi,

The following code:
```
class Example {
 + void method()
}

note top of Example::method()
  text
end note
```

With PlantUML Version 1.2018.13 raises an error.

Shall these positions be allowed?

**Comment by The-Lum** [comment]
Currently only on `left `or `right`...
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhEIImkLd2jICmjo4bLgEPIq5OeoyzCKSXDBSd8Jz7GvAhbuihBBqbLo4bDAr78JuCfjRA2gr1GA4cj0ChbGTHmfUQbA82qG3KMPQPd4D89LOJGwW1a0Pq70000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd2jICmjo4bLgEPIq5OeoyzCKSXDBSd8Jz7GvAhbuihBBqbLo4bDAr78JuCfjRA2gr1GA4cj0ChbGTHmfUQbA82qG3KMPQPd4D89LOJGwW1a0Pq70000)

**Comment by The-Lum** [comment]
Hello @emiliogq,

For top and bottom note, a workaround is to use `floating note`, like:

```puml
@startuml
class Example {
 + void method()
}

note as T
  note on top
end note

note as B
  note on bottom
end note

T -- Example::method
Example::method -- B
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhEIImkLd2jICmjo4bLgEPIq5OeoyzCKSXDBSd8Jz7GvAhbuihBBqbLI2nM2E5IK02py_CKIl8Bk5BpKi1yX0ed91L9-IKb-Rb8Ya8KT7LXDbbPGIpWGkE3b3XnEG0r0Hq70000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd2jICmjo4bLgEPIq5OeoyzCKSXDBSd8Jz7GvAhbuihBBqbLI2nM2E5IK02py_CKIl8Bk5BpKi1yX0ed91L9-IKb-Rb8Ya8KT7LXDbbPGIpWGkE3b3XnEG0r0Hq70000)

Regards.
