### ISSUE TITLE
procedure definition is generating error

### ISSUE THREAD

**Issue by break2make** [plantuml/plantuml#326]
@startuml

!procedure msg($source, $destination)
$source --> $destination: Hello
!endprocedure

msg("foo1", "foo2")
@enduml

The above description generated the following error:
Error line 2 in file: C:\DURGA\attack_tree\plant_uml\test_custom_comp-copy.pu
Some diagram description contains errors

However, I replace procedure by function, it works. I could not find the reason behind it.

**Comment by swmatisa** [comment]
It is working on the online server.
What is your version?
```
@startuml
version
@enduml
```

**Comment by break2make** [comment]
PlantUML Version 1.2019.06

**Comment by break2make** [comment]
Use the following command:
java -jar .\plantuml.jar -v

**Comment by break2make** [comment]
I have downloaded the latest version and it worked! Thanks
