### ISSUE TITLE
Dynamically create a json structure inside the preprecessor function

### ISSUE THREAD

**Issue by break2make** [plantuml/plantuml#328]
I have an usecase where I want to find the max of an array. If I have a predefined json struct having a {"key": [12, 13, 14]}, then max() function return the max value 14. However, there are few cases, where I have to generate  {"key": [12, 13, 14]} dynamically with variable number of elements in list. Please help to generate a dynamic json structure or update an existing jason structure in plantuml preprocessor.

**Comment by abhijeet-pathak** [comment]
Can you please provide an example of your preprocessor function?

**Comment by philCryoport** [comment]
In my case, I'm tracking in a sequence diagrams two queues which would greatly benefit from the ability to (a) start with an empty JSON array, and then (b) have the ability to add and remove entries.

My queues are:
* MQTT topic subscribers
* Messages in a MQTT topic

**Comment by The-Lum** [comment]
Hello @break2make, @philCryoport, @Potherca, and all,

Available from last [snapshot (~v1.2024.5beta1)](https://github.com/plantuml/plantuml/releases/tag/snapshot),  you can now use:
- `%str2json`
- `%json_add`
- `%json_remove`

Then:
- _Could you test to confirm proper operation?_

From:
- #1742

See also:
- #1733

Regards,
Th.

**Comment by philCryoport** [comment]
Trying this out first with a "Hello World":
* I downloaded `plantuml-SNAPSHOT.jar` [from the link you provided above](https://github.com/plantuml/plantuml/releases/tag/snapshot)
* I created a simple file based upon the ["Variable Definition" example](https://plantuml.com/preprocessing#788fa5fb2276ed17)
* I ran `java -jar plantuml-SNAPSHOT.jar test.puml` -- and got a PNG file that matches the diagram in the instructions
* I then added a remove and an add command to, effectively, change the `name` attribute:

```
@startuml
!$a  = 42
!$ab = "foo1"
!$cd = "foo2"
!$ef = $ab + $cd
!$foo = { "name": "John", "age" : 30 }
%json_remove($foo,name)
%json_add($foo,name,"Sally")

Alice -> Bob : $a
Alice -> Bob : $ab
Alice -> Bob : $cd
Alice -> Bob : $ef
Alice -> Bob : Do you know **$foo.name** ?
@enduml
```

Note that I tried both `"Sally"` and `Sally` (i.e. without the double quotes.

In both cases, it threw the following error:

```
java.lang.NullPointerException: value is null
	at net.sourceforge.plantuml.json.JsonObject.add(JsonObject.java:331)
	at net.sourceforge.plantuml.tim.stdlib.JsonAdd.executeReturnFunction(JsonAdd.java:84)
	at net.sourceforge.plantuml.tim.TContext.applyFunctionsAndVariables(TContext.java:486)
	at net.sourceforge.plantuml.tim.TContext.applyFunctionsAndVariablesInternal(TContext.java:431)
	at net.sourceforge.plantuml.tim.TContext.addPlain(TContext.java:391)
	at net.sourceforge.plantuml.tim.TContext.executeOneLineNotSafe(TContext.java:360)
	at net.sourceforge.plantuml.tim.TContext.executeOneLineSafe(TContext.java:321)
	at net.sourceforge.plantuml.tim.TContext.executeLines(TContext.java:295)
	at net.sourceforge.plantuml.tim.TimLoader.load(TimLoader.java:68)
	at net.sourceforge.plantuml.BlockUml.<init>(BlockUml.java:147)
	at net.sourceforge.plantuml.BlockUmlBuilder.init(BlockUmlBuilder.java:144)
	at net.sourceforge.plantuml.BlockUmlBuilder.<init>(BlockUmlBuilder.java:102)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.<init>(SourceFileReaderAbstract.java:98)
	at net.sourceforge.plantuml.SourceFileReader.<init>(SourceFileReader.java:77)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:479)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:404)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:371)
	at net.sourceforge.plantuml.Run.main(Run.java:206)
Error line 8 in file: /foo/test.puml
Some diagram description contains errors
```

Line 8 is `%json_add($foo,name,"Sally")`

**Comment by The-Lum** [comment]
Hi @philCryoport,

Thanks a lot for your detailed tests.
	
Currently the `%json_add` runs only with JSON `Array` or `Object`, as:
```puml
@startuml
!$foo = [12, 13]
!$a  = [14, "ab"]
!$foo = %json_add($foo, $a)

Alice -> Bob : $a
Alice -> Bob : $foo
@enduml
```

```puml
@startuml
!$a  = 42
!$foo = { "name": "John", "age" : 30 }
!$foo = %json_remove($foo, name)
!$v = %str2json("[1, 2]")
!$foo = %json_add($foo, "name", $v)

Alice -> Bob : $a
Alice -> Bob : $foo
Alice -> Bob : Do you know **$foo.name** ?
@enduml
```

And there are some side effects on scalar type _(`string`, `integer`, `boolean`, `null`)_ [ -> As you point out with your tests].

Then I must to do more boundary check on that.
I must to go to new tests... on scalar...

Thanks for your tests.
_See you on next correction,_
Regards,
Th.

**Comment by philCryoport** [comment]
Thank you @The-Lum -- lemme know when you have a snapshot build ready and I'll test it on my box:
* First: the basic "Hello World" as shown above
* Then: trying it out for my scenario, where I want to
  * (a) adding a specific entry into a JSON string that's tracking unsent messages on a MQTT topic
  * (b) removing a specific entry from that same JSON string -- once we receive a Publish Acknowledgement that a particular message was delivered

**Comment by The-Lum** [comment]
Hello @philCryoport,

With the last snapshot of yesterday evening you can now test.

Good test...
Don't hesitate to make feedback...

Regards,
Th.

**Comment by philCryoport** [comment]
Hi @The-Lum 

Yep, tried out the basic stuff with `1.2024.5beta`:
```
@startuml
!$a  = 42
Alice -> Bob : Original $a
!$foo = { "name": "John", "age" : 30 }
Alice -> Bob : Original foo: $foo
!$foo = %json_remove($foo, name)
Alice -> Bob : Revised foo: $foo -- name attribute should be gone
!$v = %str2json("[1, 2]")
!$foo = %json_add($foo, "name", Sally)
Alice -> Bob : Revised foo again: $foo -- name attribute should be "Sally"
!$v = %str2json("[1, 2]")
!$foo = %json_add($foo, "new array", $v)
Alice -> Bob : Revised foo again: $foo -- should have the "new array" of [1,2]
Alice -> Bob : Do you know **$foo.name** ?
@enduml
```

The basic stuff worked fine:
![image](https://github.com/plantuml/plantuml/assets/28901899/46352e7d-5d1a-4155-b3c3-726a3d11993b)


_However_ there's no checking with a `json_add` to see if the attribute already exists :(
```
@startuml
!$a  = 42
Alice -> Bob : Original $a
!$foo = { "name": "John", "age" : 30 }
Alice -> Bob : Original foo: $foo
!$foo = %json_add($foo, "name", Sally)
Alice -> Bob : Revised foo again: $foo - should have one name attribute "Sally" - but end up with two "name" attributes
@enduml
```

Result - two "name" attributes:
![image](https://github.com/plantuml/plantuml/assets/28901899/511c5e67-cbd5-41e4-8edd-e74b7501c8c6)


I also tried removing an attribute that I had already removed:  
```
@startuml
!$a  = 42
Alice -> Bob : Original $a
!$foo = { "name": "John", "age" : 30 }
Alice -> Bob : Original foo: $foo
!$foo = %json_remove($foo, "name")
Alice -> Bob : Revised foo again: $foo - "name" attribute should be gone
!$foo = %json_remove($foo, "name")
Alice -> Bob : Revised foo again: $foo - what happens if I try to remove the "name" attribute when it's already gone?
@enduml
```

Result - No warning thrown...which might be ok...that depends on the standard being followed:
![image](https://github.com/plantuml/plantuml/assets/28901899/6cfe12fa-2155-4105-9285-124bc4537232)


The [classic sempf joke](https://www.sempf.net/post/On-Testing1) is running through my head...

**Comment by The-Lum** [comment]
Hi @philCryoport,

Good catch!

Internally plantuml use the [minimal-json](https://github.com/plantuml/plantuml/tree/34e3cfc9f4b4146410746e090f0c99397d603190/src/net/sourceforge/plantuml/json); then for:
> However there's no checking with a `json_add` to see if the attribute already exists :(

We will now create the new function `%json_set` a wrapper of `set`, in order to set the last existing attribute....

And you're right, unit tests look strangely like:
> The [classic sempf joke](https://www.sempf.net/post/On-Testing1) is running through my head...

Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now implemented, we can close this ticket.
- Thanks @break2make  for the report;
- Thanks @philCryoport  for the tests;
- Thanks PlantUML team for your work.

Regards.
