### ISSUE TITLE
Labels on lines stretch out the components

### ISSUE THREAD

**Issue by besi** [plantuml/plantuml#33]
## Good

```bash
$ plantuml -v
(0.000 - 123 Mo) 121 Mo - PlantUML Version 8031
(0.085 - 123 Mo) 119 Mo - GraphicsEnvironment.isHeadless() false

```

Every thing looks fine:

```puml
@startuml

node A{
    node B
    node C
}
node D

C <- B
B -> D

@enduml
```

![fine](https://cloud.githubusercontent.com/assets/160412/23171196/1d94066a-f852-11e6-8a00-c217023b957d.png)

## Bad

Until I ad a label to the connection between `B` and `D`

```plantuml
@startuml

node A{
    node B
    node C
}
node D

C <- B
B -> D: E

@enduml
```

![bad](https://cloud.githubusercontent.com/assets/160412/23171243/4098c8bc-f852-11e6-9844-cec896d2a021.png)

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This is usualy related to GraphViz version (2.39 or 2.40).
Which version are you using ? (You can check it with -testdot flag in the command line).
If possible, downgrade to 2.38

Regards,

**Comment by dylan-chong** [comment]
I have also a similar issue, and can confirm this works on 2.38 and not 2.40

For anyone who comes across this, you can download the right version of graphviz from here http://graphviz.org/pub/graphviz/stable/SOURCES/

**Comment by aadrian** [comment]
@arnaudroques what about https://github.com/plantuml/smetana/issues/1  ?

**Comment by evantill** [comment]
Hi all, @arnaudroques  @The-Lum  can we tag this as won't fix and close this ?
