### ISSUE TITLE
Math/LaTex resolution/dpi

### ISSUE THREAD

**Issue by r00tr4v3n** [plantuml/plantuml#333]
The math environments ignore the dpi skinparam. There is no increase in resolution.

```
@startmath
skinparam dpi 300
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
```
```
@startlatex
skinparam dpi 300
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
```
![image](https://user-images.githubusercontent.com/6073574/82741068-d1bc2600-9d4e-11ea-8386-6aa2858d2188.png)

**Comment by astonfe** [comment]
A similar problem here. The options **dpi** or **scale** works, but the results are not good.

    @startuml
    skinparam dpi 300
    :Planck;
    :<latex>{\small \mathsf{\epsilon_0=\frac{c_1}{\lambda^5 (e^{c_2 / \lambda T}-1)}}}</latex>;
    @enduml

    @startuml
    scale 5
    :Planck;
    :<latex>{\small \mathsf{\epsilon_0=\frac{c_1}{\lambda^5 (e^{c_2 / \lambda T}-1)}}}</latex>;
    @enduml

**Comment by arnaudroques** [comment]
Thanks for the report.
@astonfe Your examples should work with last beta http://beta.plantuml.net/plantuml.jar

@r00tr4v3n For math/latex, the syntax is slightly different. You should also use last beta.

```
@startmath
dpi 300
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
```

```
@startlatex
dpi 300
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
```

**Comment by astonfe** [comment]
Just downloaded the last beta. It works as expected. Thanks!

**Comment by r00tr4v3n** [comment]
> dpi 300

Great, thank you! This should be mentioned somewhere in the docs.
