### ISSUE TITLE
unable to browse source directory

### ISSUE THREAD

**Issue by rzabini** [plantuml/plantuml#335]
Starting from version 1.2020.11, files are not shown in the directory dialog.

Error in stdout is:
```
java.lang.ClassCastException: java.io.File cannot be cast to net.sourceforge.plantuml.security.SFile
        at net.sourceforge.plantuml.security.SFile.equals(SFile.java:198)
        at net.sourceforge.plantuml.swing.MainWindow2.removeAllThatUseThisFile(MainWindow2.java:383)
        at net.sourceforge.plantuml.swing.MainWindow2.refreshDir(MainWindow2.java:357)
```
It seems due to [this change](https://github.com/plantuml/plantuml/blame/3192fa218c2ad0420d03de70f57f8521e1de315d/src/net/sourceforge/plantuml/swing/MainWindow2.java#L359), which builds a list of `SFile`, while the `removeAllThatUseThisFile` method still uses the standard `File` class.

**Comment by arnaudroques** [comment]
Yes, sorry about that.
We've made some major change (see https://plantuml.com/security ) but we did not test enough.

This is just fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you

We will probaby release a official version in the incoming days.

**Comment by rzabini** [comment]
Last beta is working fine for me, thank you.
