### ISSUE TITLE
Bibliotekon.getNodeUid throws IllegalStateException

### ISSUE THREAD

**Issue by sjoerdtalsma** [plantuml/plantuml#337]
Please forgive the repost of the forum post:
https://forum.plantuml.net/10804/illegalstateexception-classes-defined-outside-namespace

as github lets me post decent images of the diagrams :+1:

The following exception regularly occurs when referring to a class in another package:
```
java.lang.IllegalStateException
	at net.sourceforge.plantuml.svek.Bibliotekon.getNodeUid(Bibliotekon.java:127)
	at net.sourceforge.plantuml.cucadiagram.Link.getEntityPort1(Link.java:251)
	at net.sourceforge.plantuml.svek.Line.<init>(Line.java:191)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:406)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:107)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:72)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:646)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:191)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:196)
        ... (many more lines)
```
_(PlantUML version 1.2020.12)_

I have extracted a simple diagram that reproduces it:

```
@startuml
    namespace issues {
        interface issues.MySupplier<T>

        class issues.MySet<T> {
            +iterator(): Iterator<T>
            +size(): int
        }

        java.util.function.Supplier <|-- issues.MySupplier
        java.util.AbstractSet <|-- issues.MySet
    }

    namespace java.util.function {
        interface Supplier<T> {
            {abstract} +get(): T
        }
    }

    namespace java.util {
        abstract class AbstractSet<E>
    }
@enduml
```

This results in the above exception and the interface `java.util.function.Supplier` completely missing from the diagram:
![image](https://user-images.githubusercontent.com/2930348/84133067-f6024d00-aa46-11ea-94ff-53e8f17d534a.png)

Again, sorry for the repost.

**Comment by sjoerdtalsma** [comment]
Leaving out the relations, give a slightly better result, although the nested namespace is not recognized unfortunately.

```
@startuml
    namespace issues {
        interface issues.MySupplier<T>

        class issues.MySet<T> {
            +iterator(): Iterator<T>
            +size(): int
        }

'        java.util.function.Supplier <|-- issues.MySupplier
'        java.util.AbstractSet <|-- issues.MySet
    }

    namespace java.util.function {
        interface Supplier<T> {
            {abstract} +get(): T
        }
    }

    namespace java.util {
        abstract class AbstractSet<E>
    }
@enduml
```

Results in:

![image](https://user-images.githubusercontent.com/2930348/84133770-dae40d00-aa47-11ea-993b-3879ab173943.png)

**Comment by sjoerdtalsma** [comment]
Adding the relations again, but this time outside the _issues_ namespace almost gives the desired effect:

```
@startuml
    namespace issues {
        interface issues.MySupplier<T>

        class issues.MySet<T> {
            +iterator(): Iterator<T>
            +size(): int
        }
    }

    namespace java.util.function {
        interface Supplier<T> {
            {abstract} +get(): T
        }
    }

    namespace java.util {
        abstract class AbstractSet<E>
    }

    java.util.function.Supplier <|-- issues.MySupplier
    java.util.AbstractSet <|-- issues.MySet
@enduml
```

![image](https://user-images.githubusercontent.com/2930348/84133931-1da5e500-aa48-11ea-9cb4-c2756f5cf36e.png)

**Comment by sjoerdtalsma** [comment]
Nesting the namespaces as follows results in the intended diagram:
```
    namespace java.util {
        abstract class AbstractSet<E>
        
        namespace function {
            interface Supplier<T> {
                {abstract} +get(): T
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/2930348/84134082-56de5500-aa48-11ea-92ec-c3b4b1a96220.png)

**Comment by sjoerdtalsma** [comment]
The funny thing is, the original diagram I started with did work, I just cannot recall in which version of PlantUML that was.

Is there some change in behaviour with regard to _namespace_ vs. _package_ I need to catch up on?

**Comment by bobjacobsen** [comment]
The problem with the test file in 1st comment _is_ present in v1.2019.9 and _not_ present in v1.2019.8.   Git bisect settles on:

```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[c10dc0a6f75a60b6f8f91ee7a9e5251075687f9d] Merge pull request #245 from leechor/master
```

**Comment by arnaudroques** [comment]
We have made some changes to prepare [this](http://alphadoc.plantuml.com/doc/asciidoc/en/poll-about-package-and-namespace).
This is indeed an unexpected regression and we are going to investigate.
Sorry about that!

**Comment by sjoerdtalsma** [comment]
Thank you for the link!
For what it’s worth, I think it is an improvement although it’s causing the regression now. 

I think Umldoclet ought to switch to the new package notation so we’re also more in line with standard UML. I think that should fix our issue by using proper diagram syntax.

In the mean time, the `IllegalStateException` probably should be fixed anyway, so I’ll leave this issue open for the moment if that is okay.

**Comment by sjoerdtalsma** [comment]
@bobjacobsen thank you for finding the version, I hadn’t gone back that far yet 😉

**Comment by sjoerdtalsma** [comment]
This could be (but might not) be related to #298 ?

**Comment by bobjacobsen** [comment]
Thank you!  That's fixed it.

**Comment by sjoerdtalsma** [comment]
> Tell us if it's not working for you !

With plantuml version `1.2020.15` I still get no nesting of namespaces even though the exception is gone.
So I get this image:

![image](https://user-images.githubusercontent.com/2930348/84133931-1da5e500-aa48-11ea-9cb4-c2756f5cf36e.png)

Where I expected this:

![image](https://user-images.githubusercontent.com/2930348/84134082-56de5500-aa48-11ea-92ec-c3b4b1a96220.png)

It could be that automatic nesting is no longer supported for namespaces, then I'll just close this issue. I just wanted to verify this is the case.

**Comment by sjoerdtalsma** [comment]
Closing this, as the behaviour in `1.2020.15` is now effectively the same as the last-known working version `1.2019.8`.

**Comment by sjoerdtalsma** [comment]
@arnaudroques Thanks again for fixing this!
