### ISSUE TITLE
Please don't strip debug info from classes

### ISSUE THREAD

**Issue by remal** [plantuml/plantuml#351]
As I can see in pom.xml, debug info isn't being included in class files: https://github.com/plantuml/plantuml/blob/55ca84b7c16e32e04bfc323de17928b50becd31e/pom.xml#L139

Could you please include debug info in class files? It will help to debug and library size by a very small amount of bytes.

**Comment by arnaudroques** [comment]
Thanks for the suggestion!
This is will changed in next official release.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @remal for the report.
- Thanks PlantUML team for your work.

Regards.
