### ISSUE TITLE
:backward on repeat loop does not fully support formatting

### ISSUE THREAD

**Issue by szymonwyrwiak** [plantuml/plantuml#353]
When using backward on repeat loop there is no way to use formatting in the way that it's possible to do outside of it:
1. Background changes like `#000000:""Black background"";` does not work

I still can do skinparam changes, but ad-hoc changes does not work.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed (using `stereotype` and `style`), see:
- https://github.com/plantuml/plantuml/issues/1531#issuecomment-1714334386
- https://forum.plantuml.net/16912/backward-in-repeat-loop-not-possible-to-set-color?show=18218#a18218
- https://forum.plantuml.net/9933/insert-box-inside-while-loop?show=18199#a18199

Thanks:
- @szymonwyrwiak for the report.
- @PlantUML team for your work.

Regards.
