### ISSUE TITLE
Syntax error when using for stereotypes for notes in State Diagrams

### ISSUE THREAD

**Issue by LilMouse** [plantuml/plantuml#356]
When trying to add a stereotype to a note in state diagram it generates a syntax error.
I'm running version 1.2020.15
```
@startuml
skinparam note {
  BackgroundColor<<Blue>> Blue
  BackgroundColor LightBlue
}
state Test1
note right of Test1 : This is a note
note <<Blue>> left of Test1 : This is a note
@enduml
```
```
Error found in diagram states-1
ERROR
7
Syntax Error?
Some diagram description contains errors
```

The same happens when using the new beta style syntax
```
skinparam useBetaStyle true
<style>
  note {
    BackgroundColor LightBlue
  }

  .Blue{
    BackgroundColor Blue
  }

</style>
state Test1
note right of Test1 : This is a note
note <<Blue>> left of Test1 : This is a note

@enduml
```

**Comment by The-Lum** [comment]
Hi @LilMouse and all,

_[This is an Issue Review]_
This is now fixed:
```puml
@startuml
<style>
  note {
    BackgroundColor LightBlue
  }
  .Blue{
    BackgroundColor Blue
    Fontcolor White
  }
</style>
state Test1
note right of Test1 : This is a note
note left of Test1 <<Blue>>: This is a note
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/RO_12i8m343l_OfyWU9LIXaJF7aSU2vRjXPh0srs6EA_cxOx20e9XEI5btIPRUBr6PJEl0Kq2Y0I8xoa0EZj-5WIhN6wKA04DxyuxiEACdrB7ahz7zqfW2j57clhxZotJNtSRQ8NsO2PJwfwKp40pQq7PnYSpo1XwrqD2ZX_CLeNbp4_R8TnajS-)](https://www.planttext.com/?text=RO_12i8m343l_OfyWU9LIXaJF7aSU2vRjXPh0srs6EA_cxOx20e9XEI5btIPRUBr6PJEl0Kq2Y0I8xoa0EZj-5WIhN6wKA04DxyuxiEACdrB7ahz7zqfW2j57clhxZotJNtSRQ8NsO2PJwfwKp40pQq7PnYSpo1XwrqD2ZX_CLeNbp4_R8TnajS-)

- Thanks @LilMouse  for the report.
- Thanks PlantUML team for your work.

---

See pseudo-similar request _(fixed on V1.2022.13 (19 Nov, 2022))_ here:
- https://forum.plantuml.net/13616/how-can-i-define-note-with-stereotype
- https://forum.plantuml.net/11645/style-for-note-on-component-and-deployement-diagram-class
- https://forum.plantuml.net/16971/how-can-apply-style-or-background-color-to-note-class-method

Regards.
