### ISSUE TITLE
Missing tokens from -language option

### ISSUE THREAD

**Issue by fuhrmanator** [plantuml/plantuml#359]
The `-language` option is not listing several tokens, including:

circle, empty, members, description, true, false, normal, italic, bold, plain

and possibly others?

It seems they're not in https://github.com/plantuml/plantuml/blob/5bd20214e252e4299cb27c77a5a378fa36612d3e/src/net/sourceforge/plantuml/code/Tokens.java

See https://github.com/qjebbs/vscode-plantuml/issues/333 for the impact.

**Comment by arnaudroques** [comment]
This is fixed in version 1.2020.18
It's very questionnable, but all keywords are listed in:
https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/syntax/LanguageDescriptor.java
You can submit PR if you find missing keywords :-)

**Comment by fuhrmanator** [comment]
I had an idea to improve maintenance. One could tag the keywords in the source (I'm not sure of the mechanism) and then generate this list automatically. It's a lot of work at first, but it's an "easy" PR for a person wanting to start contributing on the project?

**Comment by The-Lum** [comment]
> all keywords are listed in:
> https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/syntax/LanguageDescriptor.java
> You can submit PR if you find missing keywords :-)

I just create: #586

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @fuhrmanator for the report.
- Thanks PlantUML team for your work.

Regards.
