### ISSUE TITLE
move 2 doc latex examples to Overleaf 2

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#362]
http://alphadoc.plantuml.com/doc/markdown/en/latex includes 2 Latex examples (https://www.writelatex.com/read/pgkkspzgzgpb and https://www.writelatex.com/read/vmrvxnvzytbr). When I click, it asks me to login to **Move project to Overleaf v2**

**Comment by a-t-0** [comment]
I cannot download the zip to re-upload it (as I was not in the original project). 
If you still have access, you could share the zip, in which it can be (re-)uploaded to Overleaf.

It may be easier to create a new Overleaf project.

**Comment by JacobValdemar** [comment]
A web archive of the link shows some of the content https://web.archive.org/web/20141111180037/https://www.writelatex.com/read/pgkkspzgzgpb

**Comment by pascal1888** [comment]
I can't seem to find any sort of docs on how to integrate PlantUML into an Overleaf project. Is there any reference for this?

**Comment by VladimirAlexiev** [comment]
- @JacobValdemar I can't find any usable link there (just broken navigation links of the former website). Can you share a direct link?
- @pascal1888 I've added the following links to the page. `\usepackage{plantuml}`

Links:
- [Q&A 1798](http://forum.plantuml.net/1798): Latex TikZ support
- [Q&A 3558](https://forum.plantuml.net/3558): export to TikZ loses links
- [Q&A 10761](https://forum.plantuml.net/10761): Latex export limitations (font size, hyperlinks, PNG in header, scaling image to page)
- [Q&A 10788](https://forum.plantuml.net/10788): How to set Latex Font Size
- Latex PlantUML package (Oliver Kopp 2018-2023): [home](https://koppor.github.io/plantuml/), [Github](https://github.com/koppor/plantuml), [CTAN](https://ctan.org/pkg/plantuml)
- [Stackoverflow 71409448](https://stackoverflow.com/questions/71409448) PlantUML in Latex
  - Idea: use Markdown with Pandoc (LaTeX runs under the hood to generate PDF files): PlantUML diagrams work fine
- [TeX Exchange 428174](https://tex.stackexchange.com/questions/428174): Can I use the plantUML language in LaTeX:
  Yes, and lists prerequisites to install

I'll close this since the files are irretrievably lost
