### ISSUE TITLE
Lollipop notation direction does not change when parties are re-positioned

### ISSUE THREAD

**Issue by wallali** [plantuml/plantuml#365]
Hello,
I have spotted this issue when using the lollipop notation for arrows `--(0-->` and trying to reposition parties using the left, right,up,down hints for better layout. The plantuml example below highlights the issue.
In both cases A and C are interface providers and hold the lollipop (male), while B and D are consumers and hold the other end (female). When the parties are positioned using `left` and `right` hints, the rendering of the lollipop does not reverse correctly, so the C to D relationship is now incorrectly represented in the rendered diagram.

This can cause incorrect communication when diagrams are simply tweaked to re-position elements as an elements responsibility is incorrectly assigned

```
@startuml


rectangle A [
    Interface Provider A
    offers lolipop
]

rectangle B [
    Interface Consumer B
    consumes lolipop
]

rectangle C [
    Interface Provider C
    offers lolipop
]

rectangle D [
    Interface Consumer D
    consumes lolipop
]

A -right0)- B

C -left0)- D

@enduml

```

![lolipop direction](https://user-images.githubusercontent.com/612794/90380790-6b585280-e074-11ea-98cb-a0c05eb7a146.png)

**Comment by arnaudroques** [comment]
Thanks for the report.
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar and will be released in next official version.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @wallali for the report.
- Thanks PlantUML team for your work.

Regards.
