### ISSUE TITLE
Association classes does not work with quotes inside the parentheses

### ISSUE THREAD

**Issue by laurocesar** [plantuml/plantuml#366]
Association classes does not work with quotes inside the parentheses.

This works:
 ``(side1, side2) .. "base"``

But this does not work:
 ``( "side1", "side2" ) .. "base"``

It is a problem, because we can put quotes "" around non-letters class name, but it fails in association classes...

**Comment by The-Lum** [comment]
Hi @laurocesar, and all,

_[This is an Issue Review]_
From:
```plantuml
class side1
class side2
("side1", "side2") .. "base"
```
>[![](https://www.planttext.com/api/plantuml/svg/Iyv9B2vMACvCIJNaIeQpZRWqbC1YIZeAO8QHagQ2dfw2Kb9YSQeI0000)](https://www.planttext.com/?text=Iyv9B2vMACvCIJNaIeQpZRWqbC1YIZeAO8QHagQ2dfw2Kb9YSQeI0000)

Here is a workaround in order to use `double quoted class name`:
```plantuml
class "side 1" as s1
class "side 2" as s2
(s1, s2) .. "base"
```
>[![](https://www.planttext.com/api/plantuml/svg/Iyv9B2vMK2hEJ4bLC5HII2nMA3RaIaOID8886d5f51lg06bD1Jqz1QManE9K9G00)](https://www.planttext.com/?text=Iyv9B2vMK2hEJ4bLC5HII2nMA3RaIaOID8886d5f51lg06bD1Jqz1QManE9K9G00)

_Enjoy,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @laurocesar for the report.

Regards.
