### ISSUE TITLE
Arrow should point along diagonal line as well

### ISSUE THREAD

**Issue by hcl734** [plantuml/plantuml#368]
Making a class diagram the additional arrow does not point along diagonal line:

![image](https://user-images.githubusercontent.com/44197572/91704986-9cf51180-eb7c-11ea-9069-389d9e7d5778.png)

`@startuml
class "Packstation" as PackSt
class "Aktueller Kunde" as Kd
class "User Interface" as UI {
    funktionsAuswahl()
    fehlermeldungAusgeben()
    informationAusgeben()
}
'Darstellen VerEinh nutzt Fehlermeldungsmethode von UI'
class "Touch Display" as TouchDisp
class "Sprachsteuerung" as SprStrg
class "Eingabefeld" as EingFld
class "Barcode-Scanner" as BCScan
class "Verarbeitungseinheit" as VerEinh

PackSt "1" -- "1" Kd : besetzt <
PackSt o-- UI
PackSt "1" o-- "1" VerEinh

UI "1" o-- "1..2" TouchDisp
UI "1" o-- "1" SprStrg
UI "1" o-- "1..2" EingFld
UI "1" o-- "1" BCScan

Kd - UI: interagiert
UI "FrontEnd" -- "BackEnd" VerEinh

@enduml`

**Comment by starlocke** [comment]
@hcl734 -- Do you mean the directional-hint "arrow" expressed on the line `PackSt "1" -- "1" Kd : besetzt <`?

What exactly are you expecting? Is it that the "arrow" (currently a "triangle 'dingbats' character" limited to UP-DOWN-LEFT-RIGHT, I would presume) somehow be aimed directly at the same "angle" as a straight diagonal line?

What if the line was more heavily curved, as is often the case?

**Comment by hcl734** [comment]
I would expect the connection between the tip of the triangle and the
middle point of the bottom to be tangent to a curved line.

**Comment by arnaudroques** [comment]
I may be wrong, but I think this [has been implemented in last release](http://www.plantuml.com/plantuml/uml/PP0zJyCm48Rt_0eh4moj16F5qa8hHLsGGjWlzYMnwfuhVmW1uhzpTceKO6hlVHxVHwG1xqNz3FBa0mHjgHRWHQhRK5tfzXGY6eDE72CfpCPH5Tfv1Wq5T0F86NQD-Ap44EcKElfjz6ymcPjRpd3YFcSqAjB8-OWzKWAQ1klEaFn5_5MLAIysoaayQNyny9w7v2G5HMal3kJa0qPqt3rBdBN1ZKNPQngXnu7dPvpgWr45xy19gt3LIY12bvNTOwgAyOeEN8ywy02FcYR-cpK6UowhQlvqehwhnMgLVuvAR4IF7iD740z5i4oxPgdRg__JgciM-NfzNozk_iNgSkV_9-N4Fm_AMHKlb_RO24q17OmQNSZkmLaAUrBp6JjUCnLbkMy0).

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/PLBBJiCm4BpdArQv50wj1CUAGrlQIbKlIA7SdMIJM77MbHyWGFmxQxSE0Kx9pentPfoih1F6-K5bbHBMGluagfun9pNb82o4kN29NVVEer9euEYfngWureazMIOEvD0qehgGfmDyPesdFYoqQs_VHATkRhC6EzuoeAezjGotM28nBgdHPeZs4_Ghcss5iIvO4xoWsKdgWBpxSB2VRh83kaxN2A-Qs7kMaZrhNtMmbVQin7iC5f4094bnDgBgsCEZuKrHn5ZXJ9iaxDgA4XlsYdIOzsgiln6cOkzvKGaYD56oUGnJKd1oOKgKBaH5xi2lKNQjb6MNwuRyBeVvF3wEDIoXH8kXx4CIQ6PFXwbSN_NZAhxw7tonkCyddNzn-TZp_v5KyS-1QwsCmuKSIv3XgujMed5HkpUQt8xgIuqDnup366w5LFDVzmq0)](https://www.planttext.com/?text=PLBBJiCm4BpdArQv50wj1CUAGrlQIbKlIA7SdMIJM77MbHyWGFmxQxSE0Kx9pentPfoih1F6-K5bbHBMGluagfun9pNb82o4kN29NVVEer9euEYfngWureazMIOEvD0qehgGfmDyPesdFYoqQs_VHATkRhC6EzuoeAezjGotM28nBgdHPeZs4_Ghcss5iIvO4xoWsKdgWBpxSB2VRh83kaxN2A-Qs7kMaZrhNtMmbVQin7iC5f4094bnDgBgsCEZuKrHn5ZXJ9iaxDgA4XlsYdIOzsgiln6cOkzvKGaYD56oUGnJKd1oOKgKBaH5xi2lKNQjb6MNwuRyBeVvF3wEDIoXH8kXx4CIQ6PFXwbSN_NZAhxw7tonkCyddNzn-TZp_v5KyS-1QwsCmuKSIv3XgujMed5HkpUQt8xgIuqDnup366w5LFDVzmq0)

- Thanks @hcl734 for the report.
- Thanks PlantUML team for your work.

Regards.
