### ISSUE TITLE
How to get visible double quotes in state diagram?

### ISSUE THREAD

**Issue by peiyuanzheng** [plantuml/plantuml#373]
I am using plantuml to draw state diagram. How could I get visible double quotes in state node?

For example, by writing:
`state "@Named("someResult") Result" as NodeA`
I expect I can see `@Named("someResult") Result` inside NodeA, but I get "syntax error" hit.

**Comment by swmatisa** [comment]
As workaround you can use Unicode:
state "@Named(<U+0022>someResult<U+0022>) Result" as NodeA

Le jeu. 17 sept. 2020 à 12:33, peiyuanzheng <notifications@github.com> a
écrit :

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @peiyuanzheng for the report.
- Thanks @swmatisa for your answer.
- Thanks PlantUML team for your work.

Regards.
