### ISSUE TITLE
Gantt chart feature request: automatically pause tasks when days are closed

### ISSUE THREAD

**Issue by RohanTalip** [plantuml/plantuml#376]
At the moment it is possible to "close" days and "pause" days, but they don't seem to interact, at least not visually:
![Screen Shot 2020-09-18 at 2 41 05 PM](https://user-images.githubusercontent.com/7445140/93647353-1a15e880-f9bd-11ea-860a-6d09d4c8a3b1.png)

It would be great if the closed days also resulted in tasks being displayed as being paused, with the dashes that appear for paused tasks.

**Comment by arnaudroques** [comment]
Thanks for the report: this is fixed in last beta http://beta.plantuml.net/plantuml.jar and on the online server

**Comment by RohanTalip** [comment]
Thanks!
