### ISSUE TITLE
SVG export with ditaa syntax

### ISSUE THREAD

**Issue by roipoussiere** [plantuml/plantuml#38]
Many PlantUML tools uses PlantUML SVG export. Since ditaa diagrams can only be exported as PNG, many tools can not use the uselful ditaa syntax, such as the [Atom markdown-preview-enhanced
 plugin](https://github.com/shd101wyy/markdown-preview-enhanced/issues/258).

**Comment by roipoussiere** [comment]
Oops, this issue is actually Ditaa related.

**Comment by roipoussiere** [comment]
(svg export reported [here](https://github.com/stathissideris/ditaa/issues/23))

**Comment by JoruusK** [comment]
It seems ditaa implemented that feature. However in plantuml svg export of ditaa content still fails. Is there some additional integration required?

**Comment by liskin** [comment]
Yeah, additional integration seems necessary indeed. There's some old snapshot of ditaa in plantuml git which should be upgraded, and then `SVGRenderer` should be used at https://github.com/plantuml/plantuml/blob/857ec10b8b5b32d1b9b72ea6427ad7d26eb070de/src/net/sourceforge/plantuml/ditaa/PSystemDitaa.java#L129

**Comment by liskin** [comment]
Something along these lines:
upgrade: https://salsa.debian.org/liskin-guest/plantuml/commit/5ee7fe82b098fa1402eb43acfff0fcc1bd19dbc4
integration: https://salsa.debian.org/liskin-guest/plantuml/commit/616dad29fd4de543985296a48166f68cec0dd780

branch with debian package and additional fixes to svg support in ditaa: https://salsa.debian.org/liskin-guest/plantuml/commits/ditaa
