### ISSUE TITLE
Gantt chart: allow closed days to be coloured

### ISSUE THREAD

**Issue by RohanTalip** [plantuml/plantuml#381]
I'm not sure if this is a feature request or a bug ...

Anyway, closed days seem to override any colours that are specified:
```
@startgantt
Project starts the 20th of september 2018
Saturdays are closed
Sundays are closed
2018-09-21 to 2018-09-23 are colored in salmon
2018-09-21 to 2018-09-30 are named [Vacation in the Bahamas]

today is 30 days after start and is colored in #AAF
[Foo] happens 40 days after start
[Dummy] lasts 10 days and starts 10 days after start
@endgantt
```
[online](http://www.plantuml.com/plantuml/uml/TP11IyD048Nl-oiUU2uahGUzjI8z2mKl8OSnEpMHx4pOcHpwxrqJAgBsk8_luys-lJbbVoTn3ozPFxXpB971UyQsyXvwXl7adDuubwH-22VoEKUw62Wpkb6DOpZDyZlwWZVLusPRmnNVhztAwAYP8mQ1qPXKRk2xQi65Ke6RL-h81vMYBHS-KK-9h0t1jTHZC1HXFUJidDVVWAGKsS_EkyFX69gZQekUfed5SFzN3CtpdDAbnKZcXlfAIBpELFyZxLdYikad)

Note that Saturday 2018-09-22 is *not* coloured in salmon and "today" (2018-10-20) is not coloured in #AAF; they instead have the closed colour.

**Comment by arnaudroques** [comment]
Thanks for the report: this is fixed in last beta http://beta.plantuml.net/plantuml.jar and on the online server

**Comment by RohanTalip** [comment]
Thanks!
