### ISSUE TITLE
Use the GraalVM JavaScript engine instead of the Nashorn JavaScript Engine (removed in Java 15)

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#394]
According to https://golb.hplar.ch/2020/04/java-javascript-engine.html

> You don't have to run your application on the Graal virtual machine to use the new Javascript engine. The GraalVM JavaScript engine is a regular Java library hosted on the Maven central repository.

Currently, PlantUML will produce the following warning when using AsciiMath formulas in Java 11+: `Warning: Nashorn engine is planned to be removed from a future JDK release`

I need to do further testing, but the code will probably throw an exception in Java 15 because the JDK does not provide a JavaScript engine out-of-the-box (i.e. Nashorn is removed in Java 15).

Arguably, adding a JavaScript engine as a dependency "just" for AsciiMath is unfortunate but I think we should at least explain how to enable this feature in Java 15+.

Thoughts?

**Comment by arnaudroques** [comment]
This is weird, because we try to be portable here. I don't think there is any explicit dependency to Nashorn in PlantUML code.

See https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/math/AsciiMath.java#L82

I *think* that `new ScriptEngineManager().getEngineByName("JavaScript");` should work fine with Java 15+ and GraalVM, assuming js-scriptengine is somewhere.

Any idea about how we could improve our code so that it works with old Java releases and Java 15+ ?

**Comment by Mogztter** [comment]
You might be right, the warning message is a bit misleading...
Perhaps the reason is that, even if we are not explicitly declaring Nashorn, `new ScriptEngineManager().getEngineByName("JavaScript");` will return the Nashorn JavaScript Engine (built-in, default and deprecated JavaScript Engine) in Java 11 and thus issue a warning.

I will do some testing tomorrow and I will report back 👍🏻

**Comment by Mogztter** [comment]
My findings:

- Java 11+: `new ScriptEngineManager().getEngineByName("JavaScript");` returns the Nashorn JavaScript Engine and issues a warning
- Java 15+: `new ScriptEngineManager().getEngineByName("JavaScript");` returns null


Now, if the following dependencies are added:

```xml
<dependency>
  <groupId>org.graalvm.js</groupId>
  <artifactId>js</artifactId>
  <version>20.2.0</version>
</dependency>
<dependency>
  <groupId>org.graalvm.js</groupId>
  <artifactId>js-scriptengine</artifactId>
  <version>20.2.0</version>
</dependency>
```

Then:

- Java 11+: `new ScriptEngineManager().getEngineByName("JavaScript");` returns the GraalVM JavaScript Engine and does not issue a warning
- Java 15+: `new ScriptEngineManager().getEngineByName("JavaScript");` returns the GraalVM JavaScript Engine

I can also confirm that AsciiMath is working fine with the GraalVM JavaScript Engine.

Maybe we should add a notice at https://plantuml.com/ascii-math, what do you think?

**Comment by arnaudroques** [comment]
> Maybe we should add a notice at https://plantuml.com/ascii-math, what do you think?

Good idea...
We are **very** lazy. Would you mind [update the page for us](http://alphadoc.plantuml.com/doc/asciidoc/en/ascii-math) ?
Thanks :-)

**Comment by Mogztter** [comment]
No worries, I will!
I wasn't sure if I was allowed to make some changes :sweat_smile:

**Comment by Mogztter** [comment]
I've updated the documentation, I think we can close this issue.
Thanks for your help.

![doc](https://user-images.githubusercontent.com/333276/97781367-0e583d00-1b8b-11eb-84e1-cd2b5cc4e85d.png)

**Comment by arnaudroques** [comment]
Many thanks.
https://plantuml.com/en/ascii-math is now up to date :-)
