### ISSUE TITLE
Add option to prevent !include with URLs

### ISSUE THREAD

**Issue by Death111** [plantuml/plantuml#397]
I would like to have a flag  to prevent the plantUML application to make external requests for security reasons. Issue is that users can define URLs which the server/application will call from his IP.

Option OptionFlags.ALLOW_INCLUDE exists suggesting to (dis)allow the use of `!include` statements. However, even if set to false (default) !include statements are executed if they refer to an URL. File includes are being denied with message 'Cannot include <filename>' correctly.

1. Example with URL (will render html content in image)
````
@startuml
left header
    !include https://www.google.com/
endheader
@enduml
````

2. Example with File  (will show error)
````
@startuml
left header
    !include test.txt
endheader
@enduml
````

Wanted:
Flag to disable also !includes with an URL e.g. ALLOW_URL_INCLUDE

**Comment by arnaudroques** [comment]
These "OptionFlags.ALLOW_INCLUDE" are somehow legacy.

I think you should be interested by https://plantuml.com/en/security
You should probably set your profile to ALLOWLIST or SANDBOX

Tell us if it helps!

**Comment by Death111** [comment]
Hey @arnaudroques,
this is exactly what I was looking for. Thank you!
