### ISSUE TITLE
Deprecated `additionalparam` in maven-javadoc-plugin

### ISSUE THREAD

**Issue by HongxuChen** [plantuml/plantuml#398]
When using `mvn package` with openjdk11, it emits the messages like below:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project plantuml: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /home/hongxu/tools/plantuml/src/net/sourceforge/plantuml/png/PngIOMetadata.java:47: error: package com.sun.imageio.plugins.png is not visible
[ERROR] import com.sun.imageio.plugins.png.PNGMetadata;
[ERROR]                               ^
[ERROR]   (package com.sun.imageio.plugins.png is declared in module java.desktop, which does not export it)
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/hongxu/tools/plantuml/target/apidocs' dir.
```
It tells that `com.sun.imageio.plugins.png` is no longer visible in new jdks therefore the javadoc generation fails. The procedure is done by `maven-javadoc-plugin`; however, the configuration `<additionalparam>${javadoc.opts}</additionalparam>` is deprecated and there are no effects for compatibility settings.

Changing that to `<source>1.7</source>` (the same as what `maven-compiler-plugin` specifies), solves the issue.

**Comment by matthew16550** [comment]
Fixed in `1.2020.24` & #815
