### ISSUE TITLE
migrate documentation

### ISSUE THREAD

**Issue by albfan** [plantuml/plantuml#4]
since sourceforge is down, there's no access to docs and even readme urls point to sourceforge

**Comment by arnaudroques** [comment]
Yes, sorry about that.
There is a mirror on http://www.plantuml.com/ and http://www.plantuml.com/PlantUML_Language_Reference_Guide.pdf
I hope that sourceforge will be up some days...

**Comment by albfan** [comment]
Yes, thanks.

Just consider to create a plantuml.github.io page

https://pages.github.com/
