### ISSUE TITLE
Unable to use macros argumets for "around" concatenation

### ISSUE THREAD

**Issue by MOZGIII** [plantuml/plantuml#40]
With this code:
```
!definelong TEST(name)
  !define JOIN(a,b,c) ##a##b##c
  JOIN(A,name,C)
!enddefinelong
TEST(B)
```

I get `AnameC`, but I want it to be `ABC`. How can I fix this?

**Comment by arnaudroques** [comment]
If possible, change the macro definition order:
```
@startuml
!definelong TEST(name)
  JOIN(A,name,C)
!enddefinelong
!define JOIN(a,b,c) ##a##b##c
Alice-> Bob : TEST(B)
@enduml
```

Result: http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL9CIKtBp4lDoSzBLmXn3GxHo4lCJTNaKb3mylVqqt3K0N5rd3Mv55FpKX1AOTeWgX9radIIDHMKbHELbPEKbPEv77CoarDrxHISyfCKh236EcboEG2D05e90000

**Comment by MOZGIII** [comment]
I see the problem, I'll try that.

**Comment by MOZGIII** [comment]
It worked, thank you.
