### ISSUE TITLE
Certain characters seem to be allowed for a name, but not as a reference to it in a link

### ISSUE THREAD

**Issue by benthillerkus** [plantuml/plantuml#401]
*To avoid the [XY-problem](http://xyproblem.info/):*
### I need to put an `{abstract}` under an abstract classes name.

To achieve that, I named the class `abstract class artikel\n❴abstrakt❵ {...}`.
This worked.

Unfortunately I can't reference this class in links, so `artikel\n❴abstrakt❵ --o tree` wouldn't work.

The issue isn't the line break, which seems to be fine, but the `❴`, which is my surrogate for a `{`. <br>*other XY-problem: you can't escape such characters in names via `\{`*

For reference, this is what my class looks like:
![image](https://user-images.githubusercontent.com/29630575/98126860-555d6f80-1eb6-11eb-959b-f948a4ece2ba.png)

And this is the code:
```plantuml
abstract class artikel\nabstrakt {
    artikelnummer: ""number(12)""
    preis: ""(4,2)""
    bezeichnung: ""varchar(25)""
    beschreibung: ""varchar(500)""
    bilder: ""list<bild>""
}
```

**Comment by swmatisa** [comment]
You should use alias with the as keyword:

@startuml
abstract class *"artikel\nabstrakt" as Ar *{

    artikelnummer: ""number(12)""

    preis: ""(4,2)""

    bezeichnung: ""varchar(25)""

    beschreibung: ""varchar(500)""

    bilder: ""list<bild>""

}
class tree

Ar --o tree
@enduml

Le mer. 4 nov. 2020 à 16:02, Bent Hillerkus <notifications@github.com> a
écrit :

**Comment by benthillerkus** [comment]
That doesn't work for me, unfortunately.
![image](https://user-images.githubusercontent.com/29630575/98141840-5fd43500-1ec7-11eb-919d-7371724c3aa3.png)

I'm using the plantuml version distributed on the Arch Repositories, which is slightly out of date, so maybe that issue has already been fixed.

**Comment by swmatisa** [comment]
Hello,
 After "as Ar" it is "{" not *
You can try on the PlantUML server: This example on PlantUML Server
<http://www.plantuml.com/plantuml/png/NOz12i8m44NtEKN8geA5Mkn6HEezt4pImOQcKMQcBXJlRaA4Ybdb__SWFpqBa2npK61P29ne5u1PcrJx2SCb5Z29qS3wJFgbb4xdo-CopqW7RKowMQHgrswCASgTq7D6rNwxjXQVwDqObtZDx07aHg2gxNuCTYEXjtzArpIhuyDGtWsUvPZZAREtAlk549LAS-lwLaAFSKWV_G00>


Le mer. 4 nov. 2020 à 18:00, Bent Hillerkus <notifications@github.com> a
écrit :

**Comment by benthillerkus** [comment]
```plantuml
abstract class "artikel\n{abstrakt}" as artikel {
    artikelnummer: ""number(12)""
    preis: ""number(4,2)""
    bezeichnung: ""varchar(25)""
    beschreibung: ""varchar(500)""
    bilder: ""list<bild>""
}
```
Oh, you're right, that does work!
I was a bit confused, because in your initial response you've used the `*`.

![image](https://user-images.githubusercontent.com/29630575/98252968-cf572c80-1f7a-11eb-9da7-797c78209cd2.png)

Thanks for the help!

**Comment by swmatisa** [comment]
Hello,
*I was a bit confused, because in your initial response you've used
the *.  *
I check in my previous mail and I never use the *

Le jeu. 5 nov. 2020 à 15:24, Bent Hillerkus <notifications@github.com> a
écrit :

**Comment by benthillerkus** [comment]
I guess you have a tool to delimit code blocks via `**`. Unfortunately that doesn't transfer to GitHubs UI, where it's just displayed as a *

**Comment by benthillerkus** [comment]
![Screenshot_2020-11-05-18-54-58-603_com.github.android.jpg](https://user-images.githubusercontent.com/29630575/98278150-7b5b4080-1f98-11eb-82b8-33be2d6ec085.jpg)

**Comment by swmatisa** [comment]
OK I understand. In gmail:
[image: image.png]

Le jeu. 5 nov. 2020 à 18:55, Bent Hillerkus <notifications@github.com> a
écrit :
