### ISSUE TITLE
Gantt Chart request: style months/days/dates, closed days, task closed sections

### ISSUE THREAD

**Issue by Phrogz** [plantuml/plantuml#404]
I'd like to be able to style the following on a Gantt Chart:

* Font name/color size used for month/year name, day name, day number
* Font color used for closed day name, day number
* Background color used for closed day columns
* Background color used for the sections of tasks shown during closed days
* Line style used for the borders of tasks shown during closed days

One of the biggest issues I have is the background color for closed days, since having them forced white prevents me from using a white/light colored font:

![image](https://user-images.githubusercontent.com/14778/98726067-3bf37200-2353-11eb-936d-0de875001a51.png)

Thanks for a great Gantt Chart experience so far :)

**Comment by Phrogz** [comment]
Other things I'd like to style:
* Line color for day columns. (I'd like to make it transparent/none.)
* Font name/color/size for sections
* Line color for sections

**Comment by Nordes** [comment]
For days to be colored (like `saturday are colored in #dddddd` => it will be possible with #440 (PR merged) & #432 (issue). 
Day closed = bug to go over the item. 

To have line colored around for closed day / inner of the item, it might not be a good idea. Remember that we can state that the task is n% completed and a bar fills the whole thing. So how would it behave in such a scenario?

Regarding the fonts and style of the text, I guess it's possible to implement.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Phrogz for the request, and: _Do not hesitate to re-post and report if there are any not implemented/missing requirement..._
- Thanks PlantUML team for your work.

See doc. here:
- https://plantuml.com/en/gantt-diagram#f80ba0c004d810f7

See also ref. here:
- #438
- https://forum.plantuml.net/10835/add-style-style-in-gantt
- https://forum.plantuml.net/11877/how-to-change-color-or-thickness-style-arrows-gantt-diagram
- https://forum.plantuml.net/12045/add-style-for-gantt-separator-and-arrow-v1-2020-16
- https://forum.plantuml.net/13570/can-you-style-the-days-and-months-of-a-gantt-chart
- https://forum.plantuml.net/15013/gantt-chart-with-style-renders-with-wrong-colors

Regards.
