### ISSUE TITLE
[nwdiag] grouping does not work properly

### ISSUE THREAD

**Issue by smoebody** [plantuml/plantuml#408]
From the docs this should do:

```
@startuml
nwdiag {
    internet [ shape = cloud];
    internet -- ingress;

    group {
      app;
      db;
    }

    network proxy {
    	app;
        ingress;
    }

    network default {
    	app;
        db;
    }
  }
}
@enduml
```

But it looks like this:
![image](https://user-images.githubusercontent.com/991327/100341033-575dae80-2fdc-11eb-85d2-fd44eb19c989.png)

Without `group` the structure is ok:
```
@startuml
nwdiag {
    internet [ shape = cloud];
    internet -- ingress;

    network proxy {
    	app;
        ingress;
    }

    network default {
    	app;
        db;
    }
  }
}
@enduml
```
produces:
![image](https://user-images.githubusercontent.com/991327/100341157-7ceab800-2fdc-11eb-9066-70cc989fbea6.png)

**Comment by Code-m0nk3y** [comment]
I have another example:

`
@startuml

title = My buggy nwdiag

nwdiag {
   network A1 {
        Entity_1
		Entity_2
		
    }

    network A2 {
        Entity_2 
		Entity_3
    }
	
    network AB {
        Entity_3
        Entity_4
    }

    group {
        Entity_2
        Entity_1
	Entity_3
    }
}


@enduml
`
Which produces:
![image](https://user-images.githubusercontent.com/109208992/178688796-8896ba5a-6755-40fc-b7f0-10a86393fea7.png)

Where Entity_1 and Entity_2 should not be connected to network AB.

Removing the group like so:

'
@startuml

title = My OK nwdiag 

nwdiag {
    network A1 {
        Entity_1
		Entity_2
		
    }

    network A2 {
        Entity_2 
		Entity_3
    }
	
    network AB {
        Entity_3
        Entity_4
    }

}

@enduml
'

Provides the correct structure.
![image](https://user-images.githubusercontent.com/109208992/178689383-ca10183d-f91b-4a1b-9889-0586f94d55ed.png)

**Comment by The-Lum** [comment]
See also similar reported issue here:
- http://alphadoc.plantuml.com/doc/asciidoc/en/nwdiag-issues#t5kosjvoljq6krhkpcmd
- https://forum.plantuml.net/12655/nwdiag-overlapp-problem-with-3-newtorks?show=12661#c12661

Regards.

**Comment by The-Lum** [comment]
Hi @smoebody, @Code-m0nk3y, and all,

That is now fixed with:

- https://github.com/plantuml/plantuml/issues/1301#issuecomment-1450504388
- https://github.com/plantuml/plantuml/commit/f4221e340aa1e8106ec87476444593ee8273eb5d
- and https://github.com/plantuml/plantuml/commit/690fa349bac4bbb01efb9267db3f72d7d003c2db

```puml
@startuml
nwdiag {
    internet [ shape = cloud];
    internet -- ingress;

    group {
      app;
      db;
    }

    network proxy {
    	app;
        ingress;
    }

    network default {
    	app;
        db;
    }
  }
}
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/RK_D2i8m33xRfyX5qCEcRdWQmjv3F7GscyFPbBHrYkpThQumXGK27tn_IMcTPETldT2zQcK3Bm5XMksGDJeuWhr8Wt20SqTUdOf_Eaa2RXYjBSINQPYyYI40qfWYGbMDQ1XrmTmJNy4mFPvHl_YHmvGxur9OIz-vMTzKzDb1r4JXMDYbsJRBqxpQmmQMTsJRabwjHObQXVVV)](https://www.planttext.com/?text=RK_D2i8m33xRfyX5qCEcRdWQmjv3F7GscyFPbBHrYkpThQumXGK27tn_IMcTPETldT2zQcK3Bm5XMksGDJeuWhr8Wt20SqTUdOf_Eaa2RXYjBSINQPYyYI40qfWYGbMDQ1XrmTmJNy4mFPvHl_YHmvGxur9OIz-vMTzKzDb1r4JXMDYbsJRBqxpQmmQMTsJRabwjHObQXVVV)

Or:
```puml
@startuml

title = My buggy nwdiag

nwdiag {
   network A1 {
        Entity_1
		Entity_2
		
    }

    network A2 {
        Entity_2 
		Entity_3
    }
	
    network AB {
        Entity_3
        Entity_4
    }

    group {
        Entity_2
        Entity_1
	Entity_3
    }
}

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuIh9BCb9LR1LyArKI2fDJwzKo2jFoKnCv-A2q0hLN0eA2dcf9UNvHTaAZeOGFXYuvW7rLiORSd5oGfb6G2POkfOBJC6r6M5gCr90w3E6Qk94rUM4gSiONS04sRxqelpI0YnMON4ocisrN6dv-IMfHGg6UaO6HiPwnacc2leAgcMfHSMP-NaQcbmEgNafmE020000)](https://www.planttext.com/?text=SoWkIImgAStDuIh9BCb9LR1LyArKI2fDJwzKo2jFoKnCv-A2q0hLN0eA2dcf9UNvHTaAZeOGFXYuvW7rLiORSd5oGfb6G2POkfOBJC6r6M5gCr90w3E6Qk94rUM4gSiONS04sRxqelpI0YnMON4ocisrN6dv-IMfHGg6UaO6HiPwnacc2leAgcMfHSMP-NaQcbmEgNafmE020000)

_Thanks to PlantUML team, 👍_ 
Regards.
