### ISSUE TITLE
[Feature] Clickable/ing (in) (interactive) diagrams

### ISSUE THREAD

**Issue by oliv3r** [plantuml/plantuml#411]
Creating PlantUML diagrams is amazing, however one feature that is slightly lacking, is as mermaid calls it 'interactive' diagrams.

Having the possibility to add URL/links to documents makes PlantUML even more powerful. Especially in context of markdown rendered documents, where one can have a high-level overview, with clickable area's that can be used to 'zoom-in'. Also linking to documentation or implementation makes this extremely powerful.

Implementation wise it could be a simple keyword (url maybe even) that could be added anywhere, a title, a group, a class etc etc.

**Comment by swmatisa** [comment]
Hello,
It is already possible to do this with svg. https://plantuml.com/en/link
I use it and it is working well

Le lun. 30 nov. 2020 à 11:45, Olliver Schinagl <notifications@github.com> a
écrit :

**Comment by oliv3r** [comment]
You are right, I think it was a fairly new feature. I think you can only add it to strings, and not to whole blocks/images but this is more then adequate. Thank you for that hint!
