### ISSUE TITLE
When is the next release on maven central? 

### ISSUE THREAD

**Issue by YunaBraska** [plantuml/plantuml#412]
Hi, just wanted to know when I can expect a fresher version on maven central?
Latest is from 2017 https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml

**Comment by arnaudroques** [comment]
Actually, [last version 1.2020.20 is available there](https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml/1.2020.20).
The alphabetic order used for display is confusing.

**Comment by YunaBraska** [comment]
Omg thx!!! this maven central sorts it from the numbers -_- wasn't that obvious. sorry.

**Comment by monrealis** [comment]
:( I missed it too. I wonder if something can be done so that the newest versions are on top.
