### ISSUE TITLE
Table Syntax on Entity Class for ERM

### ISSUE THREAD

**Issue by tkoelpin** [plantuml/plantuml#415]
Dear Developers,

I want to use the table of the creole syntax in the entity class.

```plantuml
@startuml
entity "Table 1" as table {
  | PK | id | INT UNSIGNED AUTO INCREMENT |
  | U  | name | VARCHAR(50) NOT NULL |
  |    | comment | VARCHAR(256) |
} 
@enduml
```

This will way better for everybody to read and mark the version changes in the entity class.

I may support you if you need help for this task.

Happy coding everyone.

Yours sincerely
Toby

**Comment by arnaudroques** [comment]
Sure, thanks for the idea !
This is fixed in last beta http://beta.plantuml.net/plantuml.jar

Tell us if it's not working for you.

**Comment by tkoelpin** [comment]
Many thanks for implementing the solution so quickly, it looks so much better now.
