### ISSUE TITLE
[Bug] Sequence diagram: ascii art output includes html-style tags for messages to self

### ISSUE THREAD

**Issue by mgaffney** [plantuml/plantuml#416]
I love using PlantUML, especially for sequence diagrams. Great tool, thanks for making it!

When I generate ASCII art for sequence diagrams, I noticed that the message sequence numbers are surrounded by the `<b> </b>` html tag. This seems like a bug to me. 

It would be great if no html tags were included in the output by default. It would be nice to be able to configure a separator value like a `:`.

## PlantUML input file

```plantuml
@startuml
autonumber
Self -> Self: callSelf
@enduml
```

## ASCII Art output
```
     ,----.           
     |Self|           
     `-+--'           
       |----.         
       |    | <b>1</b>
       |<---' callSelf
       |              
     ,-+--.           
     |Self|           
     `----'           
```
`java -jar plantuml.jar -ttxt seq-bug.puml`

## ASCII Art using Unicode Characters output
```
     ┌────┐           
     │Self│           
     └─┬──┘           
       │────┐         
       │    │ <b>1</b>
       │<───┘ callSelf
       │              
     ┌─┴──┐           
     │Self│           
     └────┘           
```
`java -jar plantuml.jar -tutxt seq-bug.puml`

**Comment by arnaudroques** [comment]
Thanks for the report.
This is fixed in last beta http://beta.plantuml.net/plantuml.jar
We did not put any separator (yet).

About Unicode, we find that there are some **bold** digits (example https://www.fileformat.info/info/unicode/char/1d7cf/index.htm ). So we took advantage of this is last beta:

```
     ┌────┐          ┌─────┐
     │Self│          │Alice│
     └─┬──┘          └──┬──┘
       │────┐           │   
       │    │ 𝟏         │   
       │<───┘ callSelf  │   
       │                │   
       │                │   
       │    𝟐 hello!    │   
       │  ─ ─ ─ ─ ─ ─ ─>│   
     ┌─┴──┐          ┌──┴──┐
     │Self│          │Alice│
     └────┘          └─────┘
```

Do you think it's a good idea ?

**Comment by mgaffney** [comment]
Thanks for the quick reply. No separator is better than html tags :) 

As for the Unicode bold digits, if it is optional and not the default then it sounds like a good idea. If not, I think it will be an unexpected change that could cause problems for some users. For example, running `grep -E '\<2' *.utxt` to find all messages starting with 2 will no longer work.

**Comment by arnaudroques** [comment]
Right.
To remove bold digit, [you can have ](https://plantuml.com/en/sequence-diagram#ce3f7eb577ad5f4d) :

```
@startuml
autonumber "0"
Self -> Self: callSelf
@enduml
```

I agree that it's an unexpected change, but it sounds minor to us.

**Comment by mgaffney** [comment]
It does sound minor especially since you can override it. Thanks for sharing.

**Comment by mgaffney** [comment]
@arnaudroques, I just tried this with version 1.2021.00 (Sun Jan 10 05:25:05 EST 2021) and the html-style tags are gone. However, I noticed that setting `autonumber "0"` does not remove the bold digit in the Unicode output. Do you want me to open a separate issue for that?

**Comment by arnaudroques** [comment]
We can reuse the same issue...
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if it's not working for you or if you find other issues !

**Comment by mgaffney** [comment]
@arnaudroques I'm closing this issue. I tested this on `PlantUML version 1.2021.01 (Tue Feb 02 02:55:08 EST 2021)`. Setting `autonumber "0"` **does** remove the bold digit in the Unicode output. Thanks again for such a great tool!
