### ISSUE TITLE
Github and Sourceforge versions of plantuml sources are different. What sources should be used?

### ISSUE THREAD

**Issue by SpyrosKou** [plantuml/plantuml#424]
Hello and thanks for the great work, I have been using Plantuml for years and it is very useful.

I recently tried to compile the Github but without success, however the sourceforge version compiles successfully.  
I compared the folders and noticed some differences. Is this difference intended? Is there any specific process that needs to be followed in order to use the GitHub version?

After cloning [Github Plantuml](https://sourceforge.net/projects/plantuml/) [PlantUML 1.2020.24-SNAPSHOT 56cd2269dd6b95925e8a8c44102002d5749549bc](https://github.com/plantuml/plantuml/tree/56cd2269dd6b95925e8a8c44102002d5749549bc) and trying to compile it fails. In particular t seems that there are some sources missing.
For instance the command:
`mvn compile`
returns
`plantuml\src\gen\lib\gvc\gvtextlayout__c.java:[52,21] error: package gen.annotation does not exist`

However after checking out the sources from [Sourceforge Plantuml](https://sourceforge.net/projects/plantuml/) compiles succesfully:
`mvn compile`
returns
`Build Success`

After comparing the latest versions I saw that there are differences in the included source files and also in the folder structure.
I am not really sure on how to proceed to acquire the latest version. Is it the union of all files? Is it the same PlantUml project in these two places or are they forks?

**Comment by arnaudroques** [comment]
This is the same project. Sourceforge is the main repository and github is supposed to be a copy.
**But** there was an issue in the .gitignore file: the "gen" folder which contains some important files was ignored.

We've just fixed it.

Thanks for the report and sorry about that!

**Comment by SpyrosKou** [comment]
Thank you for the clarification and the quick response.
