### ISSUE TITLE
Smetana does not support hidden connections

### ISSUE THREAD

**Issue by costateixeira** [plantuml/plantuml#425]
Per https://forum.plantuml.net/12685/smetana-doesnt-allow-hide-in-connections?show=12694#a12694
When converting to smetana, the hidden connections start appearing gain. 
This was confirmed as a bug.
Thank you!

**Comment by The-Lum** [comment]
Hello @costateixeira, and all,

_[Just for the record]_
This is now fixed _(tested on last version v1.2024.5)_: 
```puml
@startuml
!pragma layout smetana

package Package1 {
  package Package3 {
    class Class3
    class Class4
  }
  package Package2 {
    class Class1
    class Class2
  }
}

Class1 -down[hidden]- Class2
Class3 -down[hidden]- Class4
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4lauYf8JCvEJ4zL283GXWhLN0eAQ8B6O445XUISnE9Y1MSGQOmkO08KgCNKQeIfrH1Tm0YijPQB2oAje9kINvuNdP6PafAQ5wiBKmEn5gka2PT3QbuAq9S0)](https://www.planttext.com/?text=SoWkIImgAStDuL8iA4fCpqrKo4cip2yjKIZEJIr9p4lauYf8JCvEJ4zL283GXWhLN0eAQ8B6O445XUISnE9Y1MSGQOmkO08KgCNKQeIfrH1Tm0YijPQB2oAje9kINvuNdP6PafAQ5wiBKmEn5gka2PT3QbuAq9S0) 


- Thanks @costateixeira  for the report.
- Thanks PlantUML team for your work.

Regards.
