### ISSUE TITLE
how partititon contains while

### ISSUE THREAD

**Issue by damozhiying** [plantuml/plantuml#427]
the below is error,syntax error?,  how to code while loop into partition

``` 
@startuml


  end partition

partition videside
 (*) --> "revice" as req1 #FFAAAA
--> "save"
-->"other"

while (Condition?) is (true)
    :Do something;
endwhile (false)

 -->[success] (*)



end partition
@enduml
```

**Comment by The-Lum** [comment]
Hi @damozhiying 

Here is a proposal:
```puml
@startuml

partition videside
start
#FFAAAA:revice;
:save;
:other;

while (Condition?) is (true)
    :Do something;
endwhile (false)
->[success];
stop

@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/BOxH2i8m34NVynK5NxO7Vw05dIZxYU53QQCDTEreilhxnk65a0lt7fA9nJVPrmomgI6XMaodYAm3HmYdURwfRCDE0HrOzlstgYHi3k2JAACPxhN4Wx-EXjWCqdOSmQZiengkAqgYydQ09VwHby-idVDbuJq4P7uwlLatW4bB-jKN)](https://www.planttext.com/?text=BOxH2i8m34NVynK5NxO7Vw05dIZxYU53QQCDTEreilhxnk65a0lt7fA9nJVPrmomgI6XMaodYAm3HmYdURwfRCDE0HrOzlstgYHi3k2JAACPxhN4Wx-EXjWCqdOSmQZiengkAqgYydQ09VwHby-idVDbuJq4P7uwlLatW4bB-jKN) 

_Enjoy,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @damozhiying  for the report.
- Thanks PlantUML team for your work.

Regards.
