### ISSUE TITLE
MIT release seems to have some issues

### ISSUE THREAD

**Issue by costateixeira** [plantuml/plantuml#430]
(apologies if this report is incorrect but I did a simple test and I confirmed)

In version 20202.26, the MIT edition is giving me some problems. It crashes when I try to generate a simple 
```
@startuml
version
@enduml
```
and just opening the GUI and clicking "about" does not work. 
Perhaps this is something that happened during packaging - the GPL and ASL editions seem to work fine.
I only notice this on 2020-26 version. 
Thanks!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
It seems that is now fixed.
- Thanks @costateixeira  for the report.
- Thanks PlantUML team for your work.

Regards.
