### ISSUE TITLE
Remove the diagram source code (and all comments) from rendered SVG diagrams

### ISSUE THREAD

**Issue by SpyrosKou** [plantuml/plantuml#431]
Hello and many wishes for a happy new year! 

I use the plantuml jar to create diagrams.

I would like to be able to remove the diagram source code (and perhaps all comments) from the SVG, as it increases the diagram size and also takes more time (in my use case I need to generate a lot of diagrams one after the other, so efficiency matters).

Is it already possible to do something like that? If not  I could try to add support for this if it is OK. Would you be interested to accept a pull request with this functionality?

**Comment by tianyu94** [comment]
Me too.

**Comment by matthew16550** [comment]
I think the `-nometadata` option will solve this for you.

**Comment by SpyrosKou** [comment]
Thanks! Great hint, I am using plantuml in java and was not aware of this option. I will check it.

**Comment by monksy** [comment]
@SpyrosKou There's no documentation for that which is probably why it was missed.

This probably can be closed.

**Comment by SpyrosKou** [comment]
@monksy You are right. I also agree it can be closed.
