### ISSUE TITLE
[gantt] thursday are colored in #AAF

### ISSUE THREAD

**Issue by liuzhaowei55** [plantuml/plantuml#432]
How to do this?

**Comment by Nordes** [comment]
As of now, in the code we can see that we can only mark the day "as closed". 

![image](https://user-images.githubusercontent.com/446572/103963775-118e1d00-5128-11eb-85ae-327ba87f5b95.png)

File: src/net/sourceforge/plantuml/project/lang/SubjectDayOfWeek.java

In order to specify color like `2021-01-04 to 2021-01-10 are colored in #d2d2d2`, the author (or someone) would have to add the "NLP" part. My guess is that it would be not "so" complicated.

**Comment by Nordes** [comment]
I've done a PR, so maybe it will be merged soon so you can use the feature ;)

![image](https://user-images.githubusercontent.com/446572/103971159-d4318b80-5137-11eb-8edf-c90bb1569f7c.png)

**Comment by Nordes** [comment]
@liuzhaowei55 this will normally be part of the next version of plantuml (merge request was completed)

**Comment by arnaudroques** [comment]
It's [available online](http://www.plantuml.com/plantuml/uml/LP0nQyD034Rt-nKVT0xa3DdZePaB7Os7htTAxFIgCoUPud_Vu0PADMZIUmzqDcVp6zKT-mvBczKjiGWovxA5yDRgNP9ZFpNu98Zcg5VSgIlRXkxOnM2hPcvW4wHQQfECMV7IF-Po2M7eLwzVz3dXer7J1ESDLT6a24r6q31O79-TNNeunaCyWPfHQ6w8-1Rv33w9OdWNNnVyUViY3_0fwiR_I1XUDO-Ok2oYXdWw8dCpyEhIVflXB9htB_m0), and on the last beta http://beta.plantuml.net/plantuml.jar

Thanks to @Nordes for the code !

**Comment by Nordes** [comment]
You're welcome

**Comment by liuzhaowei55** [comment]
@Nordes @arnaudroques Thank you so much for solving this problem so quickly and getting online. I use plantuml in my DoukuWiki.

**Comment by ctr** [comment]
I'm not sure where to leave my comment, but just to say this is a great idea but it isn't working in monthly view for me. Could this be added too?

http://www.plantuml.com/plantuml/uml/LP11QyCm38Nl_XKFTYxO3RitX_Kys37aeDbgdSwLWwKmyk_NfYjZGZmGwBqFta6Dcfr9pB2fcziaff4Aurh5SbcTUs_rmj6mFIiiCu8QwWaNaeNQYhtV1tUNdRylhE9nTRlEWneZrb8R9qo2b_usnwDpGxzOlP9D4P-D96OOdL45ZGkJyWXI31h69_b92AyWIIYafWZuPlvobbamVB0jC_vo-y8tus_GVlnlSSERf16Pvfb5qNcFHAk2JiRjmNG7bhGrymC0

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @liuzhaowei55  for the request.
- Thanks @Nordes for the PR https://github.com/plantuml/plantuml/pull/440.
- Thanks PlantUML team for your work.

---

And FYI @ctr: 
> it isn't working in monthly view for me

This is now fixed:
>[![](http://www.plantuml.com/plantuml/svg/LP11QyCm38Nl_XKFTYxO3RitX_Kys37aeDbgdSwLWwKmyk_NfYjZGZmGwBqFta6Dcfr9pB2fcziaff4Aurh5SbcTUs_rmj6mFIiiCu8QwWaNaeNQYhtV1tUNdRylhE9nTRlEWneZrb8R9qo2b_usnwDpGxzOlP9D4P-D96OOdL45ZGkJyWXI31h69_b92AyWIIYafWZuPlvobbamVB0jC_vo-y8tus_GVlnlSSERf16Pvfb5qNcFHAk2JiRjmNG7bhGrymC0)](http://www.plantuml.com/plantuml/uml/LP11QyCm38Nl_XKFTYxO3RitX_Kys37aeDbgdSwLWwKmyk_NfYjZGZmGwBqFta6Dcfr9pB2fcziaff4Aurh5SbcTUs_rmj6mFIiiCu8QwWaNaeNQYhtV1tUNdRylhE9nTRlEWneZrb8R9qo2b_usnwDpGxzOlP9D4P-D96OOdL45ZGkJyWXI31h69_b92AyWIIYafWZuPlvobbamVB0jC_vo-y8tus_GVlnlSSERf16Pvfb5qNcFHAk2JiRjmNG7bhGrymC0)

Regards.
