### ISSUE TITLE
JSON diagrams not rendering via proxy server

### ISSUE THREAD

**Issue by Piotr1215** [plantuml/plantuml#433]
Hi everyone,

I just wanted to say, thank you for amazing work. I'm using PlantUML diagrams both at work and privately and it's a great product.

Once issue I've encountered today is around rendering JSON data diagram via proxy. 
I'm rendering all of my PlantUML diagrams in markdown via proxy, like so:

Sample rendered diagram: ![sample icons](http://www.plantuml.com/plantuml/proxy?cache=yes&src=https://gist.githubusercontent.com/Piotr1215/f83233f689dc682b392912436cd9bc72/raw/5d62fd1c7e85a19b8290f452608cc33b0f82580f/working-test.puml&fmt=png). 
URL: http://www.plantuml.com/plantuml/proxy?cache=yes&src=https://gist.githubusercontent.com/Piotr1215/f83233f689dc682b392912436cd9bc72/raw/5d62fd1c7e85a19b8290f452608cc33b0f82580f/working-test.puml&fmt=png

This works as expected with all diagram types except JSON. 

![Sample JSON data diagram](http://www.plantuml.com/plantuml/proxy?cache=no&src=https://gist.githubusercontent.com/Piotr1215/0fbd88c20076f194c6e6492b7a10ffb6/raw/d5f19bf0ffab71367eca4f806307448de840dd15/json-data.pumll&fmt=png) - expectation is that this should render like other diagrams
URL: http://www.plantuml.com/plantuml/proxy?cache=no&src=https://gist.githubusercontent.com/Piotr1215/0fbd88c20076f194c6e6492b7a10ffb6/raw/d5f19bf0ffab71367eca4f806307448de840dd15/json-data.pumll&fmt=png

The diagram itself renders correctly on [PlantUML server](http://www.plantuml.com/plantuml/uml/RP4zRuCm48PtVeNbkP620qJgbAXR1vPCKTM1ugDsQsna7wsYAl-zldC_bYoWU-xUXrVYa728-9Q2hxug8UHaOy9-c47U2_aOZ9TtXDtmJq-pHLEmJKTdFuXYN87Hy4gZsfT1wmWfPK3o319603p-OQbgeRmM9-OafQlHueMMFNoASuZlXLDwGE35-HSj8KFt43JpUhjLzMQNNpAlhznXCS53lyul4EcBJvGhTIYFbuMJ9inGd4GzdvT-IhHjkwdLhY4dMMyRmZJPyQQZQpfsD6st_t7avpEt6urrEeAdPeMa9Qo9Z7vrhhfM1_2Q_iyt) without proxying

Thanks

**Comment by arnaudroques** [comment]
Many thanks for the feedback. This should be fixed now:
http://www.plantuml.com/plantuml/proxy?cache=no&src=https://gist.githubusercontent.com/Piotr1215/0fbd88c20076f194c6e6492b7a10ffb6/raw/d5f19bf0ffab71367eca4f806307448de840dd15/json-data.puml

Note that there might be some cache issue.
And there is a typo in your URL (json-data.pumll with two l )

Tell us if it's not working for you !

**Comment by Piotr1215** [comment]
Thank you @arnaudroques, it seems to be working now.

Below is the diagram I was trying to render. It works now on my site :)

![K8s Deployment Spec](http://www.plantuml.com/plantuml/proxy?cache=yes&src=https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/k8s-deployment-spec.puml&fmt=png)

**Comment by Piotr1215** [comment]
It's working now 👍
