### ISSUE TITLE
[Bug] HyperLinkColor ignored on overridden skinparam definitions

### ISSUE THREAD

**Issue by DaveFoxOpenGI** [plantuml/plantuml#436]
HyperLinkColor only processed on 'top-level' skinparam definitions and has no effect if defined in any overriden skinparam definition.
Hyperlink color on below example does not apply to the rectangle <<1>>, but if moved to the top level it does affect the link colour.

e.g.
```
@startuml
title Software System - System Context
caption An example of a System Context diagram.

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0B4884
  HyperlinkColor #ffffff
}
rectangle "==Software System\n<size:10>[Software System]</size>\n\nMy software system.\n\n<size:10>[[http://example.com (more)]]</size>" <<1>> as 1
@enduml
```

**Comment by The-Lum** [comment]
Hi all,

_See also similar issue/request here:_ [QA-8071](https://forum.plantuml.net/8071/have-more-than-one-hyperlink-text-color)

Regards.

**Comment by The-Lum** [comment]
Hello @DaveFoxOpenGI, and all,

With last snapshot _(v.1.2022.beta2)_, and correction of [QA-8071](https://forum.plantuml.net/8071/have-more-than-one-hyperlink-text-color?show=15836#c15836), we can now use:

```puml
<style>
.1 {
  rectangle {
    BackgroundColor #1168bd
    FontColor #ffffff
    BorderColor #0B4884
    HyperlinkColor #ffffff
  }
}
</style>
```

And observe the expected result:
>[![](http://www.plantuml.com/plantuml/svg/NL9DQzmm4BthLmpffJrqrowXBC4n-O3IIqufz93DOMADlM8bZP5cyReb_xrZrql0FfZHU_EUtZ2wou99Ji4RSU89dhcL0PCMOnOAyFLIF78KEejfi1V74UuZq1b3hnfk0LTjO1rs2SF6c7nqiKUjuQy1o0UqFBZOGOi-aoAO4Wy_LFRi_X2KXKAMMZnv-QL6zzvrCL0KQFH7ITaXOV_RMJd0jsBg3dX-efoneyMXCE_cu2n1LW6nZ3qPuHw4uOr5E6YwHCqqXgcoZ9vgioddU1ECiVCqdm0Ui3bsYK_HFhBd19_AyllkpSxSb7b1s_dxh-1aAIruyN2zsrtF-4zDaRoBnxNaNTDMsoN6n_rNjxUhNUnZbNN0cxAeNrRKgneeLU_ZFZwDa2zidjdD17zeNmuY_Srskwnlqt20pu4JVNcz-5n1LPLr3PYXD7SKhJwGVm00)](http://www.plantuml.com/plantuml/uml/NL9DQzmm4BthLmpffJrqrowXBC4n-O3IIqufz93DOMADlM8bZP5cyReb_xrZrql0FfZHU_EUtZ2wou99Ji4RSU89dhcL0PCMOnOAyFLIF78KEejfi1V74UuZq1b3hnfk0LTjO1rs2SF6c7nqiKUjuQy1o0UqFBZOGOi-aoAO4Wy_LFRi_X2KXKAMMZnv-QL6zzvrCL0KQFH7ITaXOV_RMJd0jsBg3dX-efoneyMXCE_cu2n1LW6nZ3qPuHw4uOr5E6YwHCqqXgcoZ9vgioddU1ECiVCqdm0Ui3bsYK_HFhBd19_AyllkpSxSb7b1s_dxh-1aAIruyN2zsrtF-4zDaRoBnxNaNTDMsoN6n_rNjxUhNUnZbNN0cxAeNrRKgneeLU_ZFZwDa2zidjdD17zeNmuY_Srskwnlqt20pu4JVNcz-5n1LPLr3PYXD7SKhJwGVm00)

_Thanks to @arnaudroques, and PlantUML team._ 👍 
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @DaveFoxOpenGI  for the report.
- Thanks PlantUML team for your work.

Regards.
