### ISSUE TITLE
Usecases ignoring sterotype font skinparams

### ISSUE THREAD

**Issue by mgeorge** [plantuml/plantuml#44]
Setting the font skinparams for usecase diagrams seems to have no effect.  The skinparams do seem to be listed in the language.
```
@startuml

skinparam {
  UsecaseStereotypeFontSize 20
  UsecaseStereotypeFontColor Red
  UsecaseStereotypeFontStyle bold
}

usecase (foo) <<bar>>
@enduml
```
![usecase-stereotypes](https://cloud.githubusercontent.com/assets/799737/23985273/043491ec-0a83-11e7-9c1e-0992fc7cad55.png)

As you can see, the stereotype is not big, red, and bold.

**Comment by arnaudroques** [comment]
Thanks for the report. This has just been fixed in last beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

**Comment by mgeorge** [comment]
Confirmed - I can now make ugly big red bold sterotypes on usecase diagrams.  :)

Thank you as always.
