### ISSUE TITLE
Prevent automatic GraphViz (dot.exe) install

### ISSUE THREAD

**Issue by mjfs** [plantuml/plantuml#442]
Since the version 1.2020.21 PlantUML tries to automatically install minimal set of GraphViz files. This is extremely problematic for security focused environments

1. Only approved executables are allowed to run in such environments, therefore installing one into AppData will certainly not enable PlantUML to function. Going further, in certain environments even the attempt of installing an executable can result in immediate blacklisting.

2. Moreover, even installing and loading a (not explicitly trusted) library from AppData is usually disabled in many environments. This means that any approach in providing plugin functionally for an application should be carefully planned - just in case it is PlantUML's ambition to provide something like this in the future.

3. Use of an application in a multi-user environment as well as its upgrades (e.g. applying patches) is carefully managed. There should never be any doubt as to what version is installed and who is allowed to use it. By using another executable (or library) in PlantUML this type of policy provisions could also be considered breached.

4. The approach of using the least possible amount of new code is usually taken when considering new applications or libraries and their updates. This is usually underpinned by a code review, an audit or other measures. Bundling unverified executable and forcing a black box approach could also result in a blacklisting.

There are other points to list, but the key message is hopefully captured via the ones above. A couple of proposals on how to proceed to still allow use of GraphViz in security focused environments (if the decision is made to address this issue):

a) Completely remove GraphViz from PlantUML package.

b) If previous point is considered unacceptable, the second best option would be to have 2 distribution packages (one with automatic GraphViz install and one without it).

c) If both previous points are considered unacceptable then at least trigger GraphViz install via explicit command line switch passed on to PlantUML (e.g. something like -installGraphVizFromDistributionServerOfPlantUML) which would perform download and install on first use. External connections as well as downloading an executable / library will raise alarms and can also result in a blacklisting, but it is at least not a deal breaker from the start.

**Comment by arnaudroques** [comment]
We understand the issue.
We have decided to integrate GraphViz inside PlantUML package because we received too many emails per week of users failing to install GraphViz (especially under Windows)

Anyway, the good news is that, starting with last version 1.2021.0, there is now another option (we did not document it yet):

- Setup `GRAPHVIZ_DOT` environment  variable to some working graphviz `dot.exe` file. This was (somehow) the default behavior before 1.2020.21.  Note that it's your responsibility to properly install GraphViz: we won't support people on this.

Tell us if it helps and if it solves your issue.

Thanks!

**Comment by mjfs** [comment]
Let me first thank you for your prompt reply and provided update. The latest version of PlantUML does run when GraphViz is provided via GRAPHVIZ_DOT environment variable. Although an import step towards, this unfortunately only partially alleviates the concerns, but it at least leaves more options on the table.

It is of course a perfectly legitimate and understandable stance that your largest user base prefers the approach that you have chosen with regard to inclusion of GraphViz. On the other hand PlantUML is integrated into many solutions (e.g. it is even a config option in GitLab install) and offering a final package with less surprises would be preferable in many enterprise environments.

Additional support or maintenance burden is undesirable, but often unavoidable and compromises are made. On the other hand, as already mentioned, lack of control and transparency are usually deal breakers and key concern in security aware environments.

One other option would perhaps be providing PlantUML compiled distributable and a separate installer that would bundle GraphViz. Apart from that, the most elegant way to address the issue raised and at the same time not compromise on user friendliness would be native Java GraphViz/dot. But one can imagine that it is probably not very realistic in short term.

Regardless of the outcome, I would like to thank all of the PlantUML developers for an extremely useful tool. It that makes life in many areas a lot easier when it comes communicating various models and representations.

**Comment by arnaudroques** [comment]
Ok, so here is a new distribution named "IGY" (Install GraphViz by Yourself) http://beta.plantuml.net/plantuml-beta-igy.zip

This compiled distribution does not include any GraphViz install (you can check this using @startuml / license / @enduml )
You can check it and tell us if it helps.
If it does, we will distribute it in next releases (in addition to GPL, LGPL, GPLv2, Apache, ECL and MIT distributions). 

PS: About a native Java GraphViz/dot, [we are working on it through the Smetana project](https://plantuml.com/smetana02). This won't be completely ready until several years, so please be patient :-)

**Comment by mjfs** [comment]
After going through a set of tests I can say that everything seems to be working as expected. GraphViz install that is set in GRAPHVIZ_DOT variable is used, AppData folder is not touched and alarms from previously included binaries are not triggered.

Thank you again for your effort and especially for making it possible to continue using such a valuable tool!

After reading about Smetana project (which would of course be ideal) I began thinking what other options might be available outside of porting GraphViz/Dot to Java that is probably quite time consuming.

I noticed in a few projects recently that WebAssembly is more often mentioned in discussions as a possible bridge between domains (e.g. in connection to GraalWasm and other engines). I also saw that there are already attempts to run GraphViz/Dot via WebAssembly (e.g. dot-svg).

I do not know how difficult it would be to run PlantUML via WebAssembly or to use GraphViz/Dot as an WebAssembly library in PlantUML, but at least on the surface this seems like a target that would be easier to achieve (than porting externals to Java).

**Comment by arnaudroques** [comment]
This special build is now officially available on the https://plantuml.com/download page
It is named `plantuml-nodot.1.2021.1.jar`

**Comment by boessu** [comment]
@mjfs We also have that WebAssembly approach too: https://plantuml.com/de/vizjs . However, it needs a very performant JavaScript Engine. The included JavaScript engine Nashorn in JRE 8 up to JDK 14 was just way too slow to execute that. And finally was removed in JDK 15, which terminates the pure native approach; at least until Graal arrives.
At the moment you have to install a native JavaScript engine for performance reasons anyway. We used V8 for that. Although I got some problems with the WebAssembly approach. Sometimes it doesn't result in the exact same drawings and I got to the point where I also got a few, non-reproducible crashes (not the V8, the WebAssembly of GraphViz crashed). So quite frankly even if Graal will fix the performance problems, you won't get the perfect solution that way.
The WebAssembly version is quite good, but it is simply not as perfect and stable as the original GraphViz Engine, which is still the rocket solid solution!

Smetana would be the best solution for plantuml hands down. Hopefully we'll see a stable implementation anytime in the future. As you guessed it seems to be still a long way on the road. Until that time, we just can try to support people with quite a lot of workarounds now to point to a GraphViz installation of your choice.
