### ISSUE TITLE
bug or feature? sequence diagram: 2 * "__" in participant name are rendered as underline; how to disable markdown?

### ISSUE THREAD

**Issue by aisbergde** [plantuml/plantuml#444]
"[repo_sys].[usp_RepoObjectSource__first_result_set__update]" 
is has 2 * "__" and this is rendered as underline:
![image](https://user-images.githubusercontent.com/9020187/104648763-f5ecbe80-56b3-11eb-8e2b-f955209732ad.png)

Is it a bug or a feature?
I think this is the Creole markdown engine
if it is a feature, how to disable markdown in participant names?

From the example in the documentation I would think:
- markdown can be used in notes
- when markdown in used in participant then an explicit declaration should be used: 
  `participant "The **Famous** Bob" as Bob`
- if it is enabled by default, then there should be a way to disable:
  - not using escape characters (it would be to complicated to find all possible combinations)
  - but using a skinparam
    - It is hard to find the possible skinparam in the PDF documentation. It is a picture and only some paramaters with "A" are visible. There is no searchable list in PDF.
    - I also tried https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#  
      but each letter must be investigated separately. And there is no search.

How to reproduce

use http://www.plantuml.com/plantuml

```
@startuml
-> "[repo].[usp_aaa_all]"
activate "[repo].[usp_aaa_all]"
"[repo].[usp_aaa_all]" -> "[repo_sys].[usp_RepoObjectSource__first_result_set__update]"
activate "[repo_sys].[usp_RepoObjectSource__first_result_set__update]"
 <- "[repo].[usp_aaa_all]"
deactivate "[repo].[usp_aaa_all]"
@enduml
```

look at the result

**Comment by Deteriorator** [comment]
@aisbergde Hi, you can use a "~" before two "_" , just like the follows, it's useful.

```uml
@startuml
-> "[repo].[usp_aaa_all]"
activate "[repo].[usp_aaa_all]"
"[repo].[usp_aaa_all]" -> "[repo_sys].[usp_RepoObjectSource~__first_result_set__update]"
activate "[repo_sys].[usp_RepoObjectSource~__first_result_set__update]"
 <- "[repo].[usp_aaa_all]"
deactivate "[repo].[usp_aaa_all]"
@enduml
```

**Comment by aisbergde** [comment]
@Deteriorator Thank you! I think, this could work, when I just replace "__" by "~__" creating the scripts. But I did not find this in any documentation.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @aisbergde for the report.
- Thanks @iloeng for your answer.

Regards.
