### ISSUE TITLE
JSON: skinparam has no effect (dpi and probably others)

### ISSUE THREAD

**Issue by habamax** [plantuml/plantuml#446]
Tried the following snippet with different DPIs:

```
skinparam monochrome true
skinparam shadowing true
skinparam dpi 600
skinparam backgroundcolor transparent

@startjson
#highlight "lastName"
#highlight "address" / "city"
#highlight "phoneNumbers" / "0" / "number"
{
  "firstName": "John",
  "lastName": "Smith",
  "isAlive": true,
  "age": 28,
  "address": {
    "streetAddress": "21 2nd Street",
    "city": "New York",
    "state": "NY",
    "postalCode": "10021-3100"
  },
  "phoneNumbers": [
    {
      "type": "home",
      "number": "212 555-1234"
    },
    {
      "type": "office",
      "number": "646 555-4567"
    }
  ],
  "children": [],
  "spouse": null
}
@endjson
```

![image](https://user-images.githubusercontent.com/234774/104887650-b0aee200-597c-11eb-9848-a70ea90eb9df.png)

As you can see DPI change has no effect (if you export to png). Other diagrams works:

```
skinparam monochrome true
skinparam shadowing true
skinparam dpi 600
skinparam backgroundcolor transparent

A -> B : hello
B -> C : world
C -> D : great
D -> A : times
```

![image](https://user-images.githubusercontent.com/234774/104888191-772aa680-597d-11eb-93f2-58b880d650e2.png)

PS, other skin params don't work: shadowing, monochrome.

**Comment by habamax** [comment]
I would use svg, but for some reason checkboxes and `null` are not properly rendered with asciidoctor-diagram

**Comment by The-Lum** [comment]
Hello @habamax, and all,

`skinparam` is not fully implemented with JSON or YAML (only `scale` and `handwritten` _[See [QA-14131](https://forum.plantuml.net/14131/allow-scale-or-dpi-for-json-or-yaml-diagram?show=17141#a17141)]_)

Then here are some workarounds  for each of your requested `skinparam`:

| Wanted Request | Workaround | Example |
|-|-|-|
| `skinparam monochrome true` | `!theme plain` | [![](https://www.planttext.com/api/plantuml/svg/RP8nRyCW48Lt_uehNHtLTkoqofIeMmSlcQAg0xL9eCLW0MuLLVxlFSvsf4WP0DttuF4uiVE1k_3bhKcIXo159w3NN67rADLPQXm1cEO-rBmJx8RojdN2UmPFm1eLBhTgBwqHzT1z2ZTjoMWsH5Zobm2matApyHROcvM6fH5VhqDww5IG4rP-hzLFfC4DWX0_nx9ucOevpnQYEG8Vd11XVyMioA4mBHo8aodCqL6inIyShVjUE7OcK8JwkA3U8jIljYMUPrcHhzQuC9H7od3pwYsyqxaf3ghXqjD9QV5nwKBdbb2-0gggMkN5kcGaZ-bz1tiwgUQknwRSa4TPRPvd3vm_A5qZbSPcc9Xi8hwtWu-EPj0w6PETC6ty3Vy0)](https://www.planttext.com/?text=RP8nRyCW48Lt_uehNHtLTkoqofIeMmSlcQAg0xL9eCLW0MuLLVxlFSvsf4WP0DttuF4uiVE1k_3bhKcIXo159w3NN67rADLPQXm1cEO-rBmJx8RojdN2UmPFm1eLBhTgBwqHzT1z2ZTjoMWsH5Zobm2matApyHROcvM6fH5VhqDww5IG4rP-hzLFfC4DWX0_nx9ucOevpnQYEG8Vd11XVyMioA4mBHo8aodCqL6inIyShVjUE7OcK8JwkA3U8jIljYMUPrcHhzQuC9H7od3pwYsyqxaf3ghXqjD9QV5nwKBdbb2-0gggMkN5kcGaZ-bz1tiwgUQknwRSa4TPRPvd3vm_A5qZbSPcc9Xi8hwtWu-EPj0w6PETC6ty3Vy0) |
| `skinparam shadowing true` | _No Workaround: not yet implemented_ |  [![](src_image)](url_puml) |
| `skinparam dpi 600` | `scale 2` |  [![](https://www.planttext.com/api/plantuml/svg/RP8nRyCW48LtViM9heuQ4zkDCYNgri5BfgZguDeaq1Am0BUAAl_t7cSdKgGCWFWUztYSs8RO-FWLd6Kij8sH81XxKlga38u8t3GXrirPyZlQT9sN8N1u1jxgUBbNU-Mih8Vpf_JJaINDbWXdVmo07xMVZJV0tvooF4luTXtI_Lb7DM4TTaR_91hz80arfxGLwsapvzb0CaSGefSoxcwOYno4xM1Fd4nXZevYBN_XuFptbMDJ8aMe3rVKEuJcrNN4y-LIv8iLBXpbaJBSlNe3xrGtnK4rNdggL0uVbrtft1BA9w0ioqKkLWKdUSmUExZZKRSFFQgY8e-Yh5vc3vm_A5shjC5cs9Hi8g5tGqYETZ26ZMmhRPS-mZy0)](https://www.planttext.com/?text=RP8nRyCW48LtViM9heuQ4zkDCYNgri5BfgZguDeaq1Am0BUAAl_t7cSdKgGCWFWUztYSs8RO-FWLd6Kij8sH81XxKlga38u8t3GXrirPyZlQT9sN8N1u1jxgUBbNU-Mih8Vpf_JJaINDbWXdVmo07xMVZJV0tvooF4luTXtI_Lb7DM4TTaR_91hz80arfxGLwsapvzb0CaSGefSoxcwOYno4xM1Fd4nXZevYBN_XuFptbMDJ8aMe3rVKEuJcrNN4y-LIv8iLBXpbaJBSlNe3xrGtnK4rNdggL0uVbrtft1BA9w0ioqKkLWKdUSmUExZZKRSFFQgY8e-Yh5vc3vm_A5shjC5cs9Hi8g5tGqYETZ26ZMmhRPS-mZy0) |
| `skinparam backgroundcolor transparent` | use `style` |  [![](https://www.planttext.com/api/plantuml/svg/RP8nRy8m48Lt_ugJku8WWT0AeGhAKAb35YPKTN1ZWrqSExATLgZYl_To2PMG6EB8tyizlpjd7PC8wIjwnzWgfhDLpqpwggsLI_3B05v4TNeDldLowwqFa89miH41TNPXgybGmnwqEMgBJm9kHKobg1M_eKBAe6BaC05UcNI-LHljdIhR-bE5_fCfhOu8PrqKVZ1XC5u2V_FQyL67_uz3kgjDqZqsSMFDTqTJQ1KXSUos-LE_6V8igKy4CGMbqkOVypo3t4dO4ITJ6AAZMAeVsFjmkd8SPA88vVwA6e_GRhqadasdUJQUuOkZVA4CDrqluPtg-ZYefdD3bTfZSwCh7KP2-N8eYcASvRCv9_aokk_W3mTJtVLOp1VaCIyMZuC7hX-KhjB6uZ1SbwmdiV5jx1nTQotU_revsVqyVm00)](https://www.planttext.com/?text=RP8nRy8m48Lt_ugJku8WWT0AeGhAKAb35YPKTN1ZWrqSExATLgZYl_To2PMG6EB8tyizlpjd7PC8wIjwnzWgfhDLpqpwggsLI_3B05v4TNeDldLowwqFa89miH41TNPXgybGmnwqEMgBJm9kHKobg1M_eKBAe6BaC05UcNI-LHljdIhR-bE5_fCfhOu8PrqKVZ1XC5u2V_FQyL67_uz3kgjDqZqsSMFDTqTJQ1KXSUos-LE_6V8igKy4CGMbqkOVypo3t4dO4ITJ6AAZMAeVsFjmkd8SPA88vVwA6e_GRhqadasdUJQUuOkZVA4CDrqluPtg-ZYefdD3bTfZSwCh7KP2-N8eYcASvRCv9_aokk_W3mTJtVLOp1VaCIyMZuC7hX-KhjB6uZ1SbwmdiV5jx1nTQotU_revsVqyVm00) |

_Enjoy._
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @habamax for the report.
- Thanks PlantUML team for your work.

Regards.
