### ISSUE TITLE
[plantuml.com] Link to PlantUML plugins for "Nikola" static site generator

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#449]
I have created two plugins for [Nikola](https://getnikola.com/):
* [plantuml](https://plugins.getnikola.com/v8/plantuml/)
* [plantuml_markdown](https://plugins.getnikola.com/v8/plantuml_markdown/)

Could someone please add them to https://plantuml.com/running - I guess in the "Generated Documentation" section.

Have not found a git repo for the website so could not made a PR 😢.

**Comment by arnaudroques** [comment]
Sure ! That's nice.
We've just updated https://plantuml.com/running

Thanks for your work.

**Comment by Huluvu424242** [comment]
Nice!

There is an long list of issues - this could be closed?
