### ISSUE TITLE
database box too wide

### ISSUE THREAD

**Issue by tianyu94** [plantuml/plantuml#451]
`scale 100 width` not working.

![image](https://user-images.githubusercontent.com/37231629/105275750-f4068c00-5bda-11eb-994f-49862d6381db.png)

```
@startuml
left to right direction
scale 100 width

package db {
class t1
class t2
class t3
class t4
class t5
class t6
class t7
class t8
class t9
class t10
class t11
class t12
class t13
class t14
class t15
class t16
class t17
class t18
class t19
class t20
class t21
class t22
class t23
class t24
class t25
class t26
class t27
class t28
class t29
class t30
class t31
class t32
class t33
class t34
class t35
class t36
class t37
class t38
class t39
class t40
class t41
class t42
class t43
class t44
class t45
class t46
class t47
class t48
class t49
class t50
class t51
class t52
class t53
class t54
class t55
class t56
class t57
class t58
class t59
class t60
class t61
class t62
class t63
class t64
class t65
class t66
class t67
class t68
class t69
class t70
class t71
class t72
class t73
class t74
class t75
class t76
class t77
class t78
class t79
class t80
class t81
class t82
class t83
class t84
class t85
class t86
class t87
class t88
class t89
class t90
class t91
class t92
class t93
class t94
class t95
}

@enduml
```

Is there any way to solve it, thx.

**Comment by albert-github** [comment]
- Which version of plantuml are you using?
- why doesn't it work, when I try it on the plantuml server as http://www.plantuml.com/plantuml/uml/1C713O0m20NGErFy4Ue6he8KMo9QKp0UNDxtraYU-PnEhdiY1wQrdgWsLTB6HI7iYgKKl5Qp4zqi1pT5tV2HE4VWxvbU3GA8eG08-gicUPyavoW6B0fBxs0oRjog_PaNSP4NTT4Nws9Vd8ltOWwQ59HKrBHeqo6D63GfAAceQT6cGnevQ59GKb7Jeas7D6hGfA2aegP5cmvfzA19GKb5JOis7T9OWoO59HKrBTfqI6CFcXIKLDIqQDCXZJDeKb1IKTEYJOSqta6JWfAA-lbzFhw-F_zd_mC0
  and I play around with the scale I do see different size images.

**Comment by tianyu94** [comment]
My mistake.

I just hope it can be like this:

![105275750-f4068c00-5bda-11eb-994f-49862d6381db](https://user-images.githubusercontent.com/37231629/105509250-485b5a00-5d08-11eb-939e-170c09095f73.png)

**Comment by albert-github** [comment]
- please specify the used plantuml and dot version
- do you want to have a 5 column page? or do you want to have something else?
- how did you generate image in your comment
- I get with the code you provided in your question an image similar to the image in the question.
