### ISSUE TITLE
skinparam ArrowFontColor<<StyleName>> is ignored

### ISSUE THREAD

**Issue by slezhnin** [plantuml/plantuml#465]
Example:
```
skinparam Arrow {
    Color<<Write>> Red
    FontColor<<Write>> Red
}
(1) --> (2) <<Write>> : Text 12
```
The Text is displayed in the default color (black) instead of red.
When the style from FontColor is removed then it works but for all arrow text.
Example:
```
skinparam Arrow {
    Color<<Write>> Red
    FontColor Red
}
(1) --> (2) <<Write>> : Text 12
(2) --> (3) : Text 23
```
I suppose it's a bug?

**Comment by The-Lum** [comment]
Hello @slezhnin, and all,

FYI, it is now fixed:
See:
```puml
skinparam Arrow {
    Color<<Write>> Red
    FontColor<<Write>> Red
}
(1) -> (2) <<Write>> : Text 12
```
>[![](https://www.planttext.com/api/plantuml/svg/AyxEp2j8B4hCLN0iAielLwZcKW02v_oS_28Rc_2Yp99KEpk5eDGKiB1RVbu95gbQBWr3JGLTEmKD8qq5X9ILGaXgHOc2eH40)](https://www.planttext.com/?text=AyxEp2j8B4hCLN0iAielLwZcKW02v_oS_28Rc_2Yp99KEpk5eDGKiB1RVbu95gbQBWr3JGLTEmKD8qq5X9ILGaXgHOc2eH40)

See also example using `style`:
```puml
<style>
.Write {
  Arrow {
    LineColor Red
    FontColor Red
  }
}
</style>

(1) -> (2) <<Write>> : Text 12
```
>[![](https://www.planttext.com/api/plantuml/svg/ioakgSn9jUFI2o_AB4bLgEPIK70iAiel1xCK57moyrATytFoYnI2KbF08cxvUIN88hLSjLms-b1Jk3GCDHLqxHGqZ3GLR6p0HjhPALWfXAHMb2WO6W40)](https://www.planttext.com/?text=ioakgSn9jUFI2o_AB4bLgEPIK70iAiel1xCK57moyrATytFoYnI2KbF08cxvUIN88hLSjLms-b1Jk3GCDHLqxHGqZ3GLR6p0HjhPALWfXAHMb2WO6W40)

_Enjoy,_
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @slezhnin for the report.
- Thanks PlantUML team for your work.

Regards.
