### ISSUE TITLE
Yaml support

### ISSUE THREAD

**Issue by ruanfi** [plantuml/plantuml#467]
Hi,
First of all, thank you for your work. It's nice that you are moving forward and this json/yaml support idea is brilliant.
I checked the one of issues related to Yaml, and understand why you are creating your own library. I think you could manage to not to distribute a snakeyaml, but to allow the user to provide the library by themselves. But in this case your own library should be compatible with snakeyaml interface.
The main reason of this issue is - I found this problem with your Yaml implementation. To reproduce the error this simple valid yaml is enough:
```
@startyaml
databaseChangeLog:
    - changeSet:
        aaa: 22
@endyaml
```
Thanks.

**Comment by arnaudroques** [comment]
Thanks for the report.
It is possible that this issue has already been fixed with last beta. It seems to work on the online server;
http://www.plantuml.com/plantuml/uml/SoWkIImggKpCpU5AIIn9J4eiJdNEICnBJ_N9JxVYKW02NOLai41mQWbG00eI4nEj58oCZBWSKlDIGBe1

**Comment by ruanfi** [comment]
Yes, it looks like it was solved. Thank you.
