### ISSUE TITLE
Can I use words like "import" to reuse plantuml code? 

### ISSUE THREAD

**Issue by 57Hao** [plantuml/plantuml#468]

**Comment by The-Lum** [comment]
Yes, you can, with `include` keyword...

See also doc. here:
- https://plantuml.com/en/preprocessing#393335a6fd28a804
- https://plantuml.com/en/command-line#85c7e8fde73fc8d8
- https://plantuml.com/sources

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @57Hao for the report.

Regards.
