### ISSUE TITLE
'hide members' break when a note is attached to a member

### ISSUE THREAD

**Issue by hipnoizz** [plantuml/plantuml#470]
Using `hide members` and attaching a note to a class member seems to make PlantUML fail. You can see an example on http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh8J4bLo4tDJKejAkRYIiv9B2vMSClFLwZ[…]ooz9LSX9JIjHo4y3ILbPWIH2CZAB5O2eE3ytLG4eeCULcfS2Kihb06G0JGO0.

The code:
```
@startuml
hide members
class Foo {
	bar
}
note left of Foo::bar
This is some bar.
endnote
@enduml
```
The output:
![image](https://user-images.githubusercontent.com/1545320/108526928-fd663f80-72d1-11eb-97ef-0beb5426043b.png)

**Comment by arnaudroques** [comment]
Thanks for the report: this has been fixed in last beta http://beta.plantuml.net/plantuml.jar

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @hipnoizz for the report.
- Thanks PlantUML team for your work.

Regards.
