### ISSUE TITLE
CJK char rendered as '####' in pdf  while `-charset UTF_8 ` already passed

### ISSUE THREAD

**Issue by jilen** [plantuml/plantuml#477]
<img width="359" alt="Screen Shot 2021-03-04 at 14 56 49" src="https://user-images.githubusercontent.com/546573/109923537-e07e3300-7cf9-11eb-9f51-e6a9c76ca764.png">

**Comment by jilen** [comment]
Fixed after using Unifont

**Comment by RickyLiu0w0** [comment]
I would like to know how to fix it?

I have the same problem and it say: 

```
org.apache.fop.fonts.Typeface warnMissingGlyph
Warning: Glyph 31867 (0x7c7b, ) not available in font Times-Bold
```

**Comment by jilen** [comment]
I fix it by force use GNU Unifont.
