### ISSUE TITLE
CucaDiagramFileMakerSmetana margin strangeness

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#497]
The default margins when using `CucaDiagramFileMakerSmetana` have a similar problem to #494 but it's not a recent regression, both `v1.2021.2` and latest are identical for this.

![comparison-latest](https://user-images.githubusercontent.com/39400458/111863804-b8f1c080-89b1-11eb-9452-cf0ac2dc9627.png)

And when we specify a margin there is extra space added at the top.  e.g. these rows use `margin 0`, `margin 20` & `margin 40`:

![margin-comparison-latest](https://user-images.githubusercontent.com/39400458/111863798-b4c5a300-89b1-11eb-80e3-f7f62879cd20.png)

Think the top space issue can be fixed by using `LimitFinder` directly in`CucaDiagramFileMakerSmetana.createFileLocked()` instead of via `ImageBuilder.getFinalDimension()`.

I'm cautious about backwards compatibility here, can the current behaviour be changed?

**Comment by arnaudroques** [comment]
> I'm cautious about backwards compatibility here, can the current behaviour be changed?

Yes, the current behaviour for Smetana could (and should) be changed.
Smetana is really a beta feature: it uses a Java implementation of dot.
(That is, you do not need to install GraphViz to run PlantUML!)

So margin was clearly not managed by Smetana.
Now that the code is clearer, it's time to fix that !

Thanks!
