### ISSUE TITLE
Another tables rendering bug

### ISSUE THREAD

**Issue by MOZGIII** [plantuml/plantuml#50]
This code does not work right:
```
@startuml
state X {
  state Y
}
X: |= header 1 |= header 2 |= header 3 |
X: | //A// | abc | def |
X: | //B// | qwe | |
@enduml
```

![image](https://cloud.githubusercontent.com/assets/265507/24456606/33f1e970-149c-11e7-9bad-490df08e56cf.png)

At the same time, without inner state it works:
```
@startuml
state X {
}
X: |= header 1 |= header 2 |= header 3 |
X: | //A// | abc | def |
X: | //B// | qwe | |
@enduml
```
![image](https://cloud.githubusercontent.com/assets/265507/24456630/4f90806a-149c-11e7-9a2d-06b492d6796e.png)

Could you please fix the first case?

**Comment by arnaudroques** [comment]
This one is one our side : we're going to have a look on this

**Comment by arnaudroques** [comment]
Thanks for the feedback. This should be ok in last beta:
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

**Comment by MOZGIII** [comment]
Great, I'll try it tomorrow.

**Comment by MOZGIII** [comment]
With this version I have different errors in many of my diagrams, preventing them from building at all.
A simple test with table and states in a state works though.

**Comment by MOZGIII** [comment]
Well, there we really not much errors. However, another problem is introduced: in a component diagram I have a set of macros, which sometimes end up in rendering the same interfaces twice (exact same definition but multiple times, depending on what is needed to be generated). It used to work ok, but now it fails with error saying `This element (ElementNameHere) is already defined`

**Comment by arnaudroques** [comment]
We've made some modification recently to be more strict on redefining elements
(see http://plantuml.sourceforge.net/qa/?qa=5760/error-message-if-same-name-is-used-for-different-objects )
But probably we've been too strict here, so we will allow to have interfaces and classes to be defined multiple times.

**Comment by MOZGIII** [comment]
Oh, I think that change is great, however it should block usage of the same name for *different* object. If objects are exactly the same, there should be no problem at all with allowing this behavior. My workflow would benefit from this too, as it would allow less silent mistakes, while the whole approach would work.

**Comment by arnaudroques** [comment]
Should be fixed 
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

**Comment by aadrian** [comment]
@arnaudroques sorry but why binary in Dropbox? Why don't just just configure PlantUML to publish to Sonatype Snapshots all the time, so that it's built all the time, so you just commit (to github)?

**Comment by prost3tnik** [comment]
it's the lone "x" ("x1" is good):
<pre>
@startuml
namespace X.y {  
}
hide X.y
@enduml
</pre>
<pre>
cat test.txt | java -jar plantuml.jar -syntax
CLASS
(2 entities)
</pre>

<pre>
@startuml
namespace A.y {  
}
hide A.y
@enduml
</pre>
<pre>
(0 entities)
</pre>

using the current version from plantuml.org:
<pre>
java -jar plantuml.jar -version
PlantUML version 1.2018.01 (Sun Jan 28 19:08:22 CET 2018)
</pre>

an even more simple example. this one should error:
<pre>
@startuml
hide X.y
@enduml
</pre>
instead it produces two classes

maybe just document it? oh, and add @startuml/ @enduml tags to .iuml example on the preprocessing page.
