### ISSUE TITLE
Website http://plantuml.com/ language options

### ISSUE THREAD

**Issue by aadrian** [plantuml/plantuml#51]
The website http://plantuml.com/ seems to render with different languages based on browser hints, without the user having the possibility to change it. This is extremely annoying.

Please let the default language to English for everybody, and add links to the other languages (considering the it has many pages and not everything is translated completely)

Thank you.

**Comment by arnaudroques** [comment]
We've published an English only version here http://en.plantuml.com/
Hope this helps!

**Comment by aadrian** [comment]
@arnaudroques yes, this helps. Thank you!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @aadrian for the report.
- Thanks PlantUML team for your work.
	
Regards.

**Comment by botkero** [comment]
Hi,

Can we reopen this issue? How does the website actually determine which default language I'd like to use? It always switches to German for me, and it's annoying. I have nothing against the translations, but the English version seems to be much more up to date than the German one.

(OS and my browser (firefox) are in english).

**Comment by The-Lum** [comment]
Hi @botkero 

Here is a possible workaround:
- Could you go directly to: https://plantuml.com/en/ ?

Regards,
Th.

**Comment by botkero** [comment]
@The-Lum 

Hmm, I hadn't thought about that. Yeah, that works too. Thanks!!!
