### ISSUE TITLE
Gantt Diagrams should push task to its earliest start point

### ISSUE THREAD

**Issue by pjcuadra** [plantuml/plantuml#52]
When a task has multiple task dependencies the task should start after fulilling both dependencies.

For example in;

```
@startuml
[1] lasts 3 days
[2] lasts 8 days
[3] lasts 5 days

[3] starts at [2]'s end
[3] starts at [1]'s end
@enduml
```

```[3]``` should start after ```[1]``` and ```[2]``` are finished. This is not actually working.

A temporal workaround is;

```
@startuml
[1] lasts 3 days
[2] lasts 8 days
[3] lasts 5 days

[3] starts at [1]'s end
[3] starts at [2]'s end
@enduml
```

**Comment by The-Lum** [comment]
Hi all, and @pjcuadra,

This is now fixed.

Here is the expected result:
```puml
@startgantt
[1] lasts 3 days
[2] lasts 8 days
[3] lasts 5 days

[3] starts at [2]'s end
[3] starts at [1]'s end
@endgantt
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgIK_CAodXYZQCLSX9B2ufLZ1MI4ciBEQADe89M405Z642fX01i0ZOY6A5n185e0RrOeNKl1HqSKEOk0EG0Di60000)](https://www.planttext.com/?text=SoWkIImgIK_CAodXYZQCLSX9B2ufLZ1MI4ciBEQADe89M405Z642fX01i0ZOY6A5n185e0RrOeNKl1HqSKEOk0EG0Di60000)

And similar corrected issue with `milestone`:
- [QA-10764](https://forum.plantuml.net/10764/gantt-multiple-tasks-as-prerequisite-for-a-milestone)

Regards.

---

Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @pjcuadra for the report.
- Thanks PlantUML team for your work.

Regards.
