### ISSUE TITLE
IndexOutOfBoundException in ditaa

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#530]
#### Reproduction case

```
@startuml
ditaa() -> hello
@enduml
```

http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKh9B4bCrD1KqBLJo4ZDoSddSaZDIm5A0000

**Comment by a-krawciw** [comment]
What do you expect the output to be? I have found the code that causes the exception and refactored it but currently, everything on the line with ditaa is ignored.

Are you expecting 
![ditaa](https://user-images.githubusercontent.com/11967679/140213542-144e129b-9aed-489c-93c9-6edc841e74ff.png)
As the output? i.e. The rest of the line after ditaa is the first line of the file?

**Comment by Mogztter** [comment]
> I don't think this makes much sense because the first line of the file defines the ditaa command as well as arguments. The code should simply be moved to the newline.

I think that's reasonable 👍🏻

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Mogztter for the report.
- Thanks @a-krawciw for your PR.
- Thanks PlantUML team for your work.

Regards.
