### ISSUE TITLE
Feature request: support for sankey diagramms

### ISSUE THREAD

**Issue by Barry1** [plantuml/plantuml#541]
Maybe you know sankey diagrams - a nice way to visualize flows.
![Example sankey diagram](http://sankeymatic.com/gallery/monthlybudget-step9.png)
There is already a textual syntax for describing such and it is even here <https://github.com/nowthis/sankeymatic> .
The owner is @nowthis .
The detailed syntax is described here <http://sankeymatic.com/manual/syntax.html> .

Another implementation is shown [here](https://observablehq.com/@d3/sankey-diagram). This one is realized by @d3 with the code in <https://github.com/d3/d3-sankey>.

You you please support it?
Thanks in advance.

**Comment by Barry1** [comment]
Hi @all,

now more than 600 days are gone without any action. @arnaudroques , could be please comment? Or do you know someone, to assign this?

Thanks in advance and all a happy and healthy new year

Bastian

**Comment by arnaudroques** [comment]
Sorry for the delay!
It's difficult for us to support *all* existing diagram types.
Even if those diagrams are interesting, we cannot implement them right now. Sorry about that!

One feasible option would be to integrate this to https://kroki.io/ 
@Mogztter This looks like a good idea. Do you think it's feasable to add this in kroki?

**Comment by Mogztter** [comment]
> One feasible option would be to integrate this to [kroki.io](https://kroki.io/)
@Mogztter This looks like a good idea. Do you think it's feasable to add this in kroki?

It seems feasible, please open a new issue at https://github.com/yuzutech/kroki

**Comment by Barry1** [comment]
> Sorry for the delay! It's difficult for us to support _all_ existing diagram types. Even if those diagrams are interesting, we cannot implement them right now. Sorry about that!
> 
> One feasible option would be to integrate this to https://kroki.io/ @Mogztter This looks like a good idea. Do you think it's feasable to add this in kroki?

Dear @arnaudroques ,

thank you for the quick reply. I did not want to blame on you, just asking again.

**Comment by Barry1** [comment]
As @Mogztter proposed I opened an [issue for kroki.io](https://github.com/yuzutech/kroki/issues/1417).

**Comment by alik1006** [comment]
Is this idea dead or still can happen? It seem it was not added to kroki either...

**Comment by ggrossetie** [comment]
These are open-source projects, there are no promises or schedules, things are accomplished as people find time, energy, and interest to work on them. The best way to make sure progress is made on something is to either work on it yourself, or hire a company that does contracting in that area to work on it for you.
