### ISSUE TITLE
Escape hyphen for nodes in a deployment diagram

### ISSUE THREAD

**Issue by mentaal** [plantuml/plantuml#543]
Hi there, 
I have a node which contains a hyphen in its name. Is it possible to escape it?
I have tried `\` and `~` already but no joy. 

Thanks!

**Comment by The-Lum** [comment]
Hello @mentaal,

Just to enclose with double quote, as:

```puml
@startuml
node "n-o-d-e"
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuShBJqbLKChJpTTDqKrLud98pKi12WC0)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuShBJqbLKChJpTTDqKrLud98pKi12WC0)

If that can help,
Regards.

**Comment by mentaal** [comment]
Sweet! Thanks!
