### ISSUE TITLE
define json variable too long 

### ISSUE THREAD

**Issue by jesshaw** [plantuml/plantuml#544]
When I defined the json variable, an error was reported due to the json being too long

e.g.

http://www.plantuml.com/plantuml/uml/j5dTJXj75BxdALohbwWFKAbIexGNg4MbSdjj3Tu9B7XttTqn1KMLaa8eQWEb1KAWLDIq94WfXWkI9dOYNiQxQr_r5Jfcv7BuEDkOZXr5i7k-7P_l_7p7Cyk7aHAXgdhbaNVULJ9I7zpDkxwIOVxzkoCv-9Ulk5wn5FZHGgIaVY3l2q__lceUpPV5f2nhSxor76_SRvtNalidyTxHnVzJyrC_vSYef1-Q20EdMbAvCVzE47f2kO6V6nU-c9AUz5Mkzx5AUdgDlbF2ToaxOFYrd2nwRYaCYfhK9KMmynpJUYrTNovCtCgFvl9AbgOrFbULxyr4Ua5K2LqbZIN_pIXu9_c9P3ZdbaXwhfZ_qtMojnf_NoFUPyISeBxDVIzrsJHCJYCfmj9qiIHDFGaV3aTYoVfUUdRGUdaSdoyEZ5BH2JpX-aY684WZtjyVjFUYCqcR5x7h51eRsgOCW_65mkUVKWhUGlHL-QsUh-IQ8y0ymbV4YerknEdg9FWtHiwZhdxxpPzzUMGTNhSopFAUY7J4t611XF3RRwIrUs-PBUCNomS_MWmjHoX1kB8m4awsJfFLklsWSTmfLuboKKIHv4I5E4ZBq6W_Nserdbe934hOZPbXmw1yOkovyBa1oMSzmIV8Hd0OEJBXSJuvmvPXDM952FPBRkdcKRBoLwRuljJB1YEtq9sQLX5XX10jtA-BdPrrMu6PP32TJCp4QUkrdfIx9X-MBGpUeLyGm68CVL9BRv9l4aHeSdRZdnvdpsYzqA9H22dOvY20ZEntDenxK3T2F8TXLqs9Q9Qf6TZ9qAdl9jilMisctencrkqBlVZ6fPgVdo_E12H5bwPBzyPnilOqNdaH_tXgNo6ZbwwNY7gcPZvuYnQ1iClQ3MoxY97tFkos45N7LLnV043PrThrMh9z69zlPpR6BRswRn436HouO4SczlL1vpXl4U5pCUnA1Q73Jbq02Bjs_I1UtSgiqMUXCwWlvy0ZeW8xyh7-MZO1wyCASyg-Zg5xSvePr25R1yYo86O-Vai2q1Ke6R0Z1Rlj2GcTogHdG6SsEsSJ1IadUEHWlk33LgVhpsa9XS42er00GQMQMNoSlJKQkrWRX0isIdLx7y9q2cBNgTbt2th12SkXI6FuBo32MSb-5I92EcpziBDvBtjRUx7GzQS6z38p3Bn0kG4f7uiYF_k9--zdCyEE0Na2jlCEc60dCnZoiEvaXW5qCgAmuJzVr3I6ljKFXS_qCTW9gyOVoUEDx4s-NXQ9aksRC-tTaTSEQ617KlQREtIEnpD4U0R3BbatVT9dfmz2T30kFuZhhp8BTzkip7d_lsY-g1Hx18JZKRqn63Ap6JoG5smRHD2rAPjv8NB3lPQeL9Bzm_R9mUtnWlcmlry_J4usuoVV9e--Iv_zrhqzquUpeqxjkRxkF7caBynRw3u3mLncu7nGvaNJ3OEArzVIPoUT1wlfcpebd3Cc4rXVx4503CRH7hw4f5lXv4FDXDd7OnEyRWncC-YqHrE_OaLC4Ig009l-jGBJZcV0V54JC-lRJYpTX9wyYXkRwUxIHC4qbnP7_FF3pi5IkhMZh_L5--ou7zQe3mRa8h1GnaGXNckcpPrk62k_nCq6iDONhURlSVsWzV87VQYmwbH7AC6qAjZnxn2PxVgHNcRJhxFYpgouf67kYVjFp7qlcuMIA5z9P_-v6BcQcRoS_wUTExO140210DWx1Gl82CPXj5ChtTz8XJ5kS7GaNn3gov-40M506106X05XG1WG1eG1OK0O40Q40M506106X05XG1WG1eG1OK0O40Q40M5067o7C20C20F2W33utwhQ8AlO8BiboEUi6AVeWNhLAp7Cwx5S-tO3

**Comment by The-Lum** [comment]
Similar to https://forum.plantuml.net/13729/there-intentional-limit-number-lines-variable-definition
It is now corrected: the limitation was lifted in the version V1.2021.6 (14 May, 2021);
Thanks for your report.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @jesshaw for the report.
- Thanks PlantUML team for your work.

Regards.
