### ISSUE TITLE
build fails: svg does not exist

### ISSUE THREAD

**Issue by judaew** [plantuml/plantuml#545]
plantuml 1.2021.5 [fails to build](https://github.com/judaew/macports-ports/runs/2437842020) with apache-ant on MacPorts:

```console
:info:build      [copy] Copying 5 files to /opt/.../work/plantuml-plantuml-4d8d2ab/build/skin
:info:build BUILD FAILED
:info:build /opt/.../work/plantuml-plantuml-4d8d2ab/build.xml:79: /opt/.../work/plantuml-plantuml-4d8d2ab/svg does not exist.
```

The error points to the following part of the build.xml: 
https://github.com/plantuml/plantuml/blob/fcf10ee0a9a94f45dff62195bfa99c508aaad6d7/build.xml#L79-L84

The build directory in the working directory has the following structure:

```console
$ tree -L 1 work/plantuml-plantuml-4d8d2ab/build
work/plantuml-plantuml-4d8d2ab/build
├── ext
├── gen
├── h
├── jcckit
├── net
├── org
├── skin
├── smetana
├── sprites
└── stdlib
```

**Comment by arnaudroques** [comment]
Thanks for the report and sorry about that !
Indeed, a [new svg folder](https://github.com/plantuml/plantuml/tree/master/svg) was missing.
We've just pushed it.
I don't know if you would need a new release/tag to make it work.

Keep us informed !
Regards

**Comment by judaew** [comment]
Thank you so much. I think the new tag will be preferable for other package managers who haven't caught this error yet. Anyway, I can use a commit as a patch in MacPorts.
