### ISSUE TITLE
listthemes command

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#552]
Would it help if I make a `listthemes` command similar to `listsprites` ?

**Comment by arnaudroques** [comment]
Sure, that's a good idea!
Thanks for your help

**Comment by arnaudroques** [comment]
> @arnaudroques
> I wonder if `help themes` would be better?

Yes, maybe.
When we are not sure, we usually implements all options just to see the result.
So maybe we should enable:

- `listthemes`
- `list themes`
- `help themes`

And do the same thing for `listsprites`

**Comment by matthew16550** [comment]
I've just done `help themes` in #554.

I think `list*` and `list *` are a separate issue as there's also `keywords`, `colors` etc to consider.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @matthew16550 for the report, and your PR: #554.
	
Regards.
