### ISSUE TITLE
Mixed incompatible licenses

### ISSUE THREAD

**Issue by SeltsamGestreifterOktopus** [plantuml/plantuml#556]
https://plantuml.com/download provides several versions of the PlantUML software with different licenses to choose from. 

I really appreciate the time and effort spent to make this possible and I hate to be the party pooper, but unfortunately I had to remove a component based on PlantUML from a project due to licensing issues recently.

Problems I found in the MIT version (source code package downloaded from https://plantuml.com/download):

Several files state that they are licensed under EPL 1.0 instead of MIT:

```
/src/h/*.java
/src/gen/plugin/dot_layout/*.java
/src/gen/lib/pathplan/*.java
/src/gen/lib/pack/*.java
/src/gen/lib/label/*.java
/src/gen/lib/gvc/*.java
/src/gen/lib/dotgen/*.java
/src/gen/lib/common/*.java
/src/gen/lib/cgraph/*.java
/src/gen/lib/cdt/*.java
```

The following files don’t contain any license headers at all:

`/src/gen/annotation/*.java`

The following files contain two licenses (MIT and APL 2.0) also the author and the original author are not identical:

`/src/net/sourceforge/plantuml/zopfli/*.java`

This file is licensed under the LGPL instead of MIT:

`/src/net/sourceforge/plantuml/math/AsciiMathParser.js `

The following files contain two copyright headers with different copyright holders:

```
/src/net/sourceforge/plantuml/json/*.java
/src/net/sourceforge/plantuml/evalex/*.java
/src/net/sourceforge/plantuml/brotli/*.java
```

I also had a short look at the GPL version and I noticed that it mixes GPL and EPL which are not compatible, see: https://resources.whitesourcesoftware.com/blog-whitesource/top-10-eclipse-public-license-questions-answered (5.  Is Eclipse Public License compatible with the GNU GPL?)

**Comment by SeltsamGestreifterOktopus** [comment]
Thank you very much for your detailed reply. Your proposed solution sounds fine to me.

You know better than me if the removal of code means any limitations to the general usefulness of the MIT version of PlantUML, but for my use case it sounds like a good solution.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @SeltsamGestreifterOktopus for the report.
- Thanks PlantUML team for your work.
	
Regards.
