### ISSUE TITLE
-computeurl does not work with -pipe

### ISSUE THREAD

**Issue by alexbestul** [plantuml/plantuml#56]
It appears that the `-computeurl`/`-encodeurl` arguments are not honored when using the `-pipe` argument.

I read through some of the source code, and it looks like `-pipe` triggers a code path that completely ignores the `-computeurl` option.

Can you make `-pipe` honor `-computeurl`? If you can't do that, can you at least update the help content to say that they don't work together?

**Comment by arnaudroques** [comment]
Thanks for the report.
Sure, this is fixed in last beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
Now `-pipe` and `-computeurl` can be used together.
This will be released in next official release.

**Comment by alexbestul** [comment]
Wow, that was fast.

I tried your beta build, and confirmed that `-pipe` and `-computeurl` now work together as I expected.

Thanks, and keep up the good work!
