### ISSUE TITLE
Override default style with a theme

### ISSUE THREAD

**Issue by ldeluigi** [plantuml/plantuml#561]
I'd like to have the possibility to set a default theme that overrides the classic one, for example by a command line option --defaultTheme or by a property like plantuml.theme.default=...

**Comment by VladimirAlexiev** [comment]
@ldeluigi You have that, see https://plantuml.com/theme and
```
puml -help|grep -i them
    -theme xxx\t\tTo use a specific theme
```

**Comment by ldeluigi** [comment]
I don't want to override the default theme for a single uml . I want to override the default theme used by the jar if no !theme is found inside a uml block

**Comment by VladimirAlexiev** [comment]
You first asked for a command line option?
Modifying the jar is a bad idea.

**Comment by ldeluigi** [comment]
Yes. Sorry, I didn't understand your answer at first glance.

The option I was looking for was, in fact, `-theme xxx`.

Thanks for your help.
