### ISSUE TITLE
Add documentation to the site and man page for nometadata

### ISSUE THREAD

**Issue by monksy** [plantuml/plantuml#563]
The nometadata command line argument is not mention on the site nor the man page. It is mentioned in the help documentation.

Please add this.

**Comment by VladimirAlexiev** [comment]
It is described in https://plantuml.com/command-line.
Did you miss that page, or the bullet?
Does the site map or the page need some editing?

**Comment by The-Lum** [comment]
FYI, I had made the modification on https://plantuml.com/command-line with adding '`nometadata`' mention only on 2021-05-31.
Thanks for the report; It is now done.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @monksy for the report.
- Thanks @VladimirAlexiev  for your answer.
- Thanks PlantUML team for your work.

Regards.
