### ISSUE TITLE
entryPoint stereotype incorrectly attach to outermost state instead the nested one

### ISSUE THREAD

**Issue by jan-matejka** [plantuml/plantuml#564]
```
   state Foo {

      qux --> barEntry

      state Bar {


         state barEntry <<entryPoint>>
      }
   }
```

renders as
![plantuml-entry](https://user-images.githubusercontent.com/455474/120452191-52662700-c392-11eb-9ff8-7f79950ef006.png)

I expect the entryPoint to be attached on Bar instead.

1. Is plantuml wrong?
2. Is my expectatio wrong?
3. How can I work around this?

**Comment by yaccz** [comment]
```
Package: graphviz
Version: 2.40.1-6+deb10u1
```

**Comment by The-Lum** [comment]
Hello @jan-matejka, and all,

>Is plantuml wrong?

_Yes or not._.. It depends of the implementation :-)

> Is my expectation wrong?

No.

>How can I work around this?

In fact don't mix declaration and link... But:

1. **First** define `declaration`.
1. **Then** define `link`....

and you can observe a expected result... as:
```puml
@startuml
state Foo {
  state qux
  state Bar {
    state barEntry <<entryPoint>>
  }
}

qux --> barEntry
@enduml
```

>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuG8oIb8LtFBp5Qgv51GWlCBI2ZZRAR48B0FZ9oKMkUQL55KgsDYaWkY0_Coy4Zixe8fQhbekBg1M1LrTExWoBeVKl1IWFG00)](https://www.planttext.com/?text=SoWkIImgAStDuG8oIb8LtFBp5Qgv51GWlCBI2ZZRAR48B0FZ9oKMkUQL55KgsDYaWkY0_Coy4Zixe8fQhbekBg1M1LrTExWoBeVKl1IWFG00)

_Enjoy,_
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @jan-matejka for the report.

Regards.
