### ISSUE TITLE
Feature Request: click to copy

### ISSUE THREAD

**Issue by Piotr1215** [plantuml/plantuml#568]
## Abstract
It would be great to have a way of copying text from a rendered diagram that is somehow marked in the diagram source code as copy able.

## Use case
I'm working currently on an action diagram describing a "decision tree" on when to use which kubectl commands. It would be very useful if someone could just follow the diagram and without leaving it, have an ability to copy a command and apply it straight away.

## Possible implementation

This could work very similar to how hyperlinks work right now.
http://www.plantuml.com/plantuml/uml/VO-nQWGn34HxVyLyWQ_VwjBa2z8SnnLYBQzDR6knjTaS8VyU9qimX72WOZHedfXpKwgwvMIcPv795556OgyGZ-xWUWsgwtGwxVjk5v4biPqbtsxc9SI6FeJlaE7Y3d4mQbp2ByHSM47T3boHOdc5FW236XndiUOY6sOgeDJ-tDyfY5XVqLQUex-3eFokFUobGWF_lB7cgJZm6vV_qn-ZWeeaZUidoBcnTfxAm8sEvwwsdBu0

Diagram code with a new "copy" tag.
@startuml
Alice -> Bob : hello
\<copy>
kubectl get pods
\</copy>
@enduml

### A few requirements
- text should be marked a bit differently to add a "click to copy" look and feel.
- text should be copied directly to the clipboard
- nesting tags should result in error
- maybe add option to the tag to format text as code using styles?

## Workaround
For now as a workaround I can embed html links and link to gists. It is not the best as one needs to leave the diagram but should work.

**Comment by VladimirAlexiev** [comment]
@Piotr1215 if you render as SVG, the user can copy any text they like.
Please Close if you're happy with this solution.

**Comment by Piotr1215** [comment]
SVG copying works, but it's pretty clunky. 
It is not as easy nor intuitive and sometimes, while selecting text, the mouse moves line up or down, but I think this is just svg thing.

Here is a working example
https://www.plantuml.com/plantuml/proxy?cache=yes&src=https://raw.githubusercontent.com/Piotr1215/dca-prep-kit/master/diagrams/cks-pods-escalation.puml&fmt=svg

While it works on the direct link to the svg, it doesn't work on rendered web page. I'm using same link as above to render my web site using [docsify](https://docsify.js.org/#/), but once the site is rendered, text copying doesn't work.
Here live link for reference: https://www.itcertificationsguide.com/#/cks_guide?id=pod-decision-tree.

If there are no plans to introduce this type of feature, I will close the issue.

**Comment by VladimirAlexiev** [comment]
I also notice the rendering is not faithful when embedded:
![Screenshot_20210714-021411_Chrome.jpg](https://user-images.githubusercontent.com/536250/125536905-27f017d4-53a6-4fec-b182-fa68b1958610.jpg)

Maybe try to nest the img in an iframe?

**Comment by Piotr1215** [comment]
Thanks, iframe works, it has some issues when resizing the window, but I can experiment with that.

Weird rendering issues, I couldn't reproduce it.
