### ISSUE TITLE
I had a problem

### ISSUE THREAD

**Issue by diguage** [plantuml/plantuml#570]
I use PlantUML with AsciiDoctor Diagram in my project.

The document is: https://github.com/diguage/spring-framework/blob/analysis/truman/src/docs/asciidoc/index.adoc

![image](https://user-images.githubusercontent.com/2121467/120968809-f0476080-c79b-11eb-8d90-8809e13cbfda.png)

The converted document is hosted: http://diguage.github.io/spring-framework/

![image](https://user-images.githubusercontent.com/2121467/120968876-0ce39880-c79c-11eb-8162-d0d0304ad959.png)

**The text was squeezed into a ball, making it difficult to read.** There is no problem when these diagrams were converted locally.

I use GitHub Action, Gradle AsciiDoctor Plugin, and AsciiDoctor Diagram to convert the diagram.

GitHub Action: https://github.com/diguage/spring-framework/blob/analysis/.github/workflows/ci.yml

Gradle Task Config: https://github.com/diguage/spring-framework/blob/analysis/truman/build.gradle#L51

**Comment by diguage** [comment]
I resolved the problem.

The problem is that there is no suitable font.

```bash
# Install fonts on Linux
$ mkdir $HOME/.fonts
$ cd $HOME/.fonts
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceHanSerifSC-Regular.otf
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceHanSansSC-Regular.otf
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceCodePro-Regular.otf
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceCodePro-It.otf
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceCodePro-Bold.otf
$ wget https://github.com/diguage/open-fonts/releases/download/latest/SourceCodePro-BoldIt.otf
```

PlantUML configuration is as following:

```
skinparam defaultFontSize 20
skinparam defaultFontName Source Han Serif SC

skinparam titleFontSize 36
skinparam titleFontName Source Han Sans SC

skinparam footerFontSize 18
skinparam footerFontName Source Han Sans SC

skinparam classFontSize 20
skinparam classFontName Source Code Pro

skinparam noteFontSize 20

skinparam nodesep 80
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @diguage for the report and the answer.
	
Regards.
