### ISSUE TITLE
UML with single database node renders two nodes

### ISSUE THREAD

**Issue by l0co** [plantuml/plantuml#572]
For:

```
@startuml
database SQL
@enduml
```

I have as an result:

![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKf9B4bCIYnELGWEzE5oICrB0Ge20000)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @l0co for the report.
- Thanks @mbajolek for your answer.


Regards.
