### ISSUE TITLE
Salt Tree font size

### ISSUE THREAD

**Issue by OleBae** [plantuml/plantuml#573]
I have added a salt tree diagram and would like to increase the font size slightly. Various attempts to do that have failed, including skinparam defaultFontSize NN which seems to have no effect . I finally fount the (undocumented) <size:NN> that can be put in front of each string, but not really what I want/need. 

In the end it works ok with the default font size of 12, so if it is not possible to adjust the font size that is ok. But it would be very good if the possibilities **and limitations** to adjust font size (and perhaps for some other stuff) for salt diagrams could be added to the salt documentation at https://plantuml.com/salt That way the next person with my problem will not spend an hour on trial-and-error.

As usual thanks for a great software!

**Comment by The-Lum** [comment]
_Awaiting FontSize management on Salt;_
A possible workaround is to use zoom with **scale** or **DPI**.
I had updated (_with **scale** and **DPI** mention_) the doc. here: https://plantuml.com/en/salt#fee470bd71039c80
See also another request here: https://forum.plantuml.net/3538/how-to-scale-a-salt-diagram

**Comment by OleBae** [comment]
The scale is very good!

But I still think it would be useful to mention which skinparams **don't** work for salt. Or which does work, if that is easier. These (at least for font size) are documented for all diagrams types, so the impression is that they should work as long as the right keyword is provided. Easy to waste an hour or two trying to find the right combination. 

That said I see now that https://plantuml.com/en/skinparam contains a lot of skinparams and a link to https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html so perhaps this is mostly me not reading the docs carefully enough. But even having had a look at that it would be good to have an explicit statement about which of these are usable in salt-diagrams.

**Comment by The-Lum** [comment]
Hello @OleBae: Thanks a lot.

Two paragraphs were add on the salt doc. page:
- [Skinparam](https://plantuml.com/en/salt#7aa53dbdfc2137bf)
- [Style](https://plantuml.com/en/salt#ae284f900f9d6e21)

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @OleBae  for the report.
- Thanks PlantUML team for your work.
	
Regards.
