### ISSUE TITLE
No way to add a note text next to a switch case branch in activity diagrams beta

### ISSUE THREAD

**Issue by CMCDragonkai** [plantuml/plantuml#577]
I've been trying to add a note text next to a switch case, but it doesn't work.

Example:

```
start
:Home Page;
note left: This is a note
floating note right: This is a note

switch (action)
note left: WHAT
case ( click - linka )
   note left: WHAT
  :Page 1.1;
case ( click - linkb )
  :Page 1.2;
  switch (action)
  case ( click - linkdsfsdf )
    :first;
    stop
  case ( click - linkb )
    :second;
    floating note right: what
  endswitch
endswitch
floating note left: This is a note
:someending;
floating note left: This is a note
stop
```

Can't use `note left` or anything next to the `:Page 1.1;`.

**Comment by stulluk** [comment]
+1

**Comment by arnaudroques** [comment]
Thanks for the report.
[This has been slightly improved](https://www.plantuml.com/plantuml/uml/ROszQiGm48JxVOejxI81fvGQftEP8f1QbbQEi7uExvfx_PDr7CSTxcRW-sP65hF9dYAq06egYV37BAG1-1h4_cDdh8IIUyX522DvKVWtVVyEO0qJTcXZi2j-O0nvDTW3eZeMSFWSz1aplp1VkfRtAyGJpx5dvvjSTHys5jqoIxcSA_E3Ph8bkmEdxEvly4oAIw9QGruqjBMnjZt56m00) with last snapshot.

Hope this helps!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @CMCDragonkai for the report.
- Thanks PlantUML team for your work.
	
Regards.
