### ISSUE TITLE
[DOC] copy example text vs open on server

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#579]
All documentation examples show the source, and a rendered diagram from the same source.
These examples are extremely valuable and make the use of PlantUML a breeze!

Clicking on the source jumps directly to the plantuml server and renders that diagram.
Unfortunately this makes copying from the source very hard: I cannot do it from the original page but have to wait for the server page to show up (which puts undue stress on the server as well).

@arnaudroques Please:
- don't add any JS over the entire source of each example, to allow the reader to copy the parts he wants
- add two separate buttons on top right of the example source:
  - ![image](https://user-images.githubusercontent.com/536250/124100037-c7e31700-da66-11eb-8804-aa486f919654.png) to open the plantuml server
  - ![image](https://user-images.githubusercontent.com/536250/124100209-f2cd6b00-da66-11eb-9dd0-da6e45b0c0a0.png) to copy the whole example to clipboard (like Github does)

Thanks in advance!

**Comment by arnaudroques** [comment]
Thanks for the suggestion, we've just added a button for copying to clipboard.

Please tell us if you have other ideas of improvement!

Thanks.

**Comment by VladimirAlexiev** [comment]
@arnaudroques can I copy only **selected lines** without jumping out to the server?

I can't check right now because I'm on mobile phone

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed, _with 2 buutons (`Copy` and `Edit`)_:
- Thanks @VladimirAlexiev for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
