### ISSUE TITLE
Hide sterotype on sequence diagram

### ISSUE THREAD

**Issue by trothwell** [plantuml/plantuml#58]
`hide sterotype` will cause most diagrams to hide the sterotype, but it doesn't in sequence diagrams.

![image](http://www.plantuml.com/plantuml/png/AqWiAibCpYn8p2jHSCfFKh2nyKtCIRMpuof0ad3CoKnE1KgvfUP2944gTUsWubOA6QavEVbSNEeb6Pd52YdvgSKAUVb0TbuwLqPcIgf2SKbgKMf-IML1AW00)
* [Link](http://www.plantuml.com/plantuml/uml/LOqn2iCm40JxUyLrgVm1OuIT8fqVeLXBT73M2UjIvFUHSPfqmyx0pitZuUzTYMe7sQJ6udot9q_J6XKX_8b5PKDN3-oNFCiX_FQHCrIDwEPP6YT3usATouko971p733_L13DAAaVVm40)

```
@startuml
participant Bob <<Male>>
participant Alice <<Female>>
Bob -> Alice : hello

'this does nothing
hide stereotype
@enduml
```

**Comment by arnaudroques** [comment]
Thanks for the report.
This is fixed in last beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
It will be released in next official version
