### ISSUE TITLE
enable `pragma` from command line

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#582]
There are command line options to set preprocessor vars and styles:
```
 -DVAR1=value        To set a preprocessing variable as if '!define VAR1 value' were used
 -Sparam1=value      To set a skin parameter as if 'skinparam param1 value' were used
 -theme xxx          To use a specific theme
```

@arnaudroques could you add similar option for `pragma`? Else I need to make Include files just to try different pragmas.

```
 -Ppragma1=value     Emit pragma, eg -Playout=elk, -Pteoz=true, -PuseVerticalIf=on. Put in quotes if the value has spaces.
                     Can be used multiple times, eg "-PsvgSize=<U+1F610> XX" "-PsvgSize=<U+1F611> I" 
```

**Comment by arnaudroques** [comment]
Thanks for the suggestion, this is a nice idea.
You can try last beta http://beta.plantuml.net/plantuml.jar
It should work with `-Ppragma1=value` option.
This has not been widely tested, so please tell us if you find issues!

**Comment by VladimirAlexiev** [comment]
Thanks for the super fast implementation!

1. It would be nice to add some validation:
```
puml.bat -Playoutzz=elkzz diagram.puml   # ignores the invalid pragma silently
puml.bat -P layout=jsdot  diagram.puml   # just hangs
```

2. I guess there's no space to add the extra explanation in `-help` ?

`Put in quotes if the value has spaces. Can be used multiple times, eg "-PsvgSize=<U+1F610> XX" "-PsvgSize=<U+1F611> I"`

**Comment by VladimirAlexiev** [comment]
Added to doc:
- http://alphadoc.plantuml.com/doc/markdown/en/command-line#5wpexad33pz4k362kjbc (refreshed `-help` text)
- http://alphadoc.plantuml.com/doc/markdown/en/svg#8obdgsm6ej13kixla94f
- http://alphadoc.plantuml.com/doc/markdown/en/activity-diagram-beta#affka97ox88lk362kj56
- http://alphadoc.plantuml.com/doc/markdown/en/sequence-diagram#qb7wj0yamucxk362kjlz
- http://alphadoc.plantuml.com/doc/markdown/en/smetana02#k5ixul8j71wck362kjmr
- http://alphadoc.plantuml.com/doc/markdown/en/elk#nc96mv18s1scko0fe544
- (there is no such pragma for http://alphadoc.plantuml.com/doc/markdown/en/vizjs)

**Comment by The-Lum** [comment]
@VladimirAlexiev, @arnaudroques, and all,

I just added to the doc.:
- http://alphadoc.plantuml.com/doc/markdown/en/teoz
