### ISSUE TITLE
Can we support additional descriptions？

### ISSUE THREAD

**Issue by LY1806620741** [plantuml/plantuml#590]
demand：when I use color classification system, Look forward to telling each other the exact information in the picture.
like this
![image](https://user-images.githubusercontent.com/25952861/125220834-dac4d980-e2f9-11eb-9632-6515b84761ac.png)

**Comment by The-Lum** [comment]
Hello @LY1806620741,

One suggestion for this would be to use the `legend`, like:
```puml
@startuml
legend top right
|<#red>   | <color:red>red color means...|
|<#blue>  | <color:blue>blue color means out of system|
end legend

a->b
a<-b
a-[#red]>b
a<-[#blue]b
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/JOr1oiCW44RtSueF_hKUu4SazmXPQ3DD2ngBZek2Xw-QJHRpmOF7lAM8or9ZeC07dpiaVP3VnqkecR_CkmNGO1uffFm_k1yc8R8xYzQw3TM7olQcJXvpbv6g83rHlaKuDXh1gqlabFNaZEgZrb7UBbxdwytJqhKQmmy0)](http://www.plantuml.com/plantuml/uml/JOr1oiCW44RtSueF_hKUu4SazmXPQ3DD2ngBZek2Xw-QJHRpmOF7lAM8or9ZeC07dpiaVP3VnqkecR_CkmNGO1uffFm_k1yc8R8xYzQw3TM7olQcJXvpbv6g83rHlaKuDXh1gqlabFNaZEgZrb7UBbxdwytJqhKQmmy0)

See also doc. here:
- https://plantuml.com/creole
- https://plantuml.com/commons

If that can help,
Regards.

**Comment by LY1806620741** [comment]
Think you for your replay. It's really useful, although the picture looks ... low.



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 12, 2021 20:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [plantuml/plantuml] Can we support additional descriptions？ (#590)




 
Hello @LY1806620741,
 
One suggestion for this would be to use the legend, like:
 @startuml legend top right |<#red&gt;   | <color:red&gt;red color means...| |<#blue&gt;  | <color:blue&gt;blue color means out of system| end legend a-&gt;b a<-b a-[#red]&gt;b a<-[#blue]b @enduml
  

  
See also doc. here:
  
https://plantuml.com/creole 

https://plantuml.com/commons 
 
If that can help,
 Regards.
