### ISSUE TITLE
Hyperlinks in JSON diagrams not clickable

### ISSUE THREAD

**Issue by xnd1124** [plantuml/plantuml#592]
Hyperlinks in JSON diagrams are visible but not clickable
Example:
@startjson
{
   "fruit [[https://www.google.com]]":"Apple",
   "size":"Large",
   "color":"Red"
}
@endjson
![image](https://user-images.githubusercontent.com/6578710/125573576-0c50035a-1557-4bcb-9846-cb0818131e30.png)

**Comment by swmatisa** [comment]
All Hyperlinks are not working with png, but work well with svg:
http://www.plantuml.com/plantuml/svg/SoWkIImgoIhEp-Egvb9AAohDB568ZiueAIaejjBNBoylrqlFpq_FITLBpi-DZLMoKd8iACX9LTBXKYhEh4e5ydqIYzB1_EJydFmYe41GQeeILosNGsfU2iXO0000
