### ISSUE TITLE
State Diagram: Horizontal connections overlap with connections to self

### ISSUE THREAD

**Issue by jeffrey-d-m** [plantuml/plantuml#594]
@startuml
[*] -> start
start -> A : a
start --> start : b
@enduml

This causes the connection from start to A to overlap with the connection from start back to start. Using "-->" intuitively makes me think the connection will go up or down to connect to itself, not horizontally.

http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuOhMYbNGjLC0yxd098Zhg62ba0ZZmgI1OabS3gbvAK1z0000

**Comment by The-Lum** [comment]
Hello @jeffrey-d-m,

Unfortunately this is not yet possible to change _(the message to self is always on right...)_;
See similar request here:
- [QA-2820/move-transition-arrow-to-self-in-state-diagram](https://forum.plantuml.net/2820)
- [QA-5742/state-transition-to-self-on-another-edge](https://forum.plantuml.net/5742)
- [QA-8188/you-make-arrow-the-same-state-appear-left-side-instead-right](https://forum.plantuml.net/8188)

A possible workaround is to change the layout to vertical, like:
```puml
@startuml
[*] --> start
start --> A : a
start -> start : b
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuOhMYbNGrRLJ00jmWKamtr71IY4HoeT90uMIk1nIyrA06W40)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuOhMYbNGrRLJ00jmWKamtr71IY4HoeT90uMIk1nIyrA06W40)

_See also request for class/component/... diagram here:_
- [QA-12282/how-change-the-position-association-same-class-class-diagram](https://forum.plantuml.net/12282)

Regards.

**Comment by jeffrey-d-m** [comment]
Ah, sorry, I didn't find those entries. Thanks for your response!
I don't see any other issues here on GitHub about this problem, but it is already known on the forum, should I leave this open or close it?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @jeffrey-d-m  for the report.
- Thanks PlantUML team for your work.

Regards.
