### ISSUE TITLE
[doc] Update Release v1.2021.9

### ISSUE THREAD

**Issue by kirchsth** [plantuml/plantuml#595]
Can you add [Upgrading C4 library to 2.3.0](https://github.com/plantuml/plantuml-stdlib/pull/42)?

Additional I think https://github.com/plantuml/plantuml-stdlib/issues/32 can be added/closed too.

Thank you and best regards
Helmut

**Comment by arnaudroques** [comment]
I may be wrong, but I think that V1.2021.9 includes C4 library 2.3.0

Can you double-check this ?
Thanks!

**Comment by kirchsth** [comment]
Sorry you are right, I checked it with plantuml.1.2021.9.jar and it is NOT in.
But I see it on http://www.plantuml.com/plantuml/.

What is required that I get a https://github.com/plantuml/plantuml-stdlib PR 
into https://github.com/plantuml/plantuml?

Thank you
Helmut

**Comment by kirchsth** [comment]
@arnaudroques: 
Maybe my issue was unclear. I thought you can update the release notes and add the "Upgrading C4 library to 2.3.0" link the release notes.
Thank you and BR Helmut

**Comment by The-Lum** [comment]
Hello PlantUML team,

If you update the [Release Note or the Change log](https://plantuml.com/changes), perhaps could you add also:
- Udpate of some stdlib _(archimate, azure, C4, cloudinsight, kubernetes, logos)_
- Adding new Preprocessing Builtin functions _(%dec2hex, %hex2dec, %hsl_color) [cf. [QA-14128](https://forum.plantuml.net/14128) (ever if it is not fully developed...)] _
- Management on CLI of `-P`option (To set pragma as if `'!pragma pragma1 value'` were used) 
_[cf. GH-582]_
- _more if we have forgotten others..._


Regards.

**Comment by The-Lum** [comment]
Thanks @arnaudroques for the [Release Note or the Change Log](https://plantuml.com/changes) update.
