### ISSUE TITLE
Can I customise the size of an Object?

### ISSUE THREAD

**Issue by ilaipi** [plantuml/plantuml#6]
For example
I am writing a use-case diagram
a case named `My Case`, and it is a top-level menu,so I want it to be a larger size.

**Comment by Huluvu424242** [comment]
Maybe you can use skanparams. Here an example:

```
@startuml
skinparam usecase {
  BackgroundColor<<Main>> red
  FontSize<<Main>> 50
  FontName Aapex
}

(First usecase) as (Use) << Main >>
(Another usecase) as (UC2)
usecase UC3
usecase (Last\nusecase) as UC4
@enduml
```

Yout can play it here: http://plantuml.com/plantuml
Doku is here: https://plantuml.com/de/skinparam

I hope it helps
