### ISSUE TITLE
Is there a way to use different Graphviz engine other than dot language.

### ISSUE THREAD

**Issue by shd101wyy** [plantuml/plantuml#60]
Hello,

The library [viz.js](https://github.com/mdaines/viz.js), which is a build of Graphviz in JavaCcript, supports multiple Graphviz engines such as `circo`, `dot`,  `neato`, `osage`, or `twopi`.  

I know in PlantUML, I can define dot language like below:   
```
@startdot 
... my code 
@enddot
```
So is there a way to use other Graphviz engines other than `dot`?  

Thank you :)

**Comment by arnaudroques** [comment]
Hello,
Unfortunately, t's not possible : only dot is supported right now.
As you said, since viz.js supports other engines, it should be theoretically possible to extends this on PlantUML part, but this is not something we are working on right now.

Sorry!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
- Wanted feature not planified

Regards.

**Comment by BenceSzalai** [comment]
On a sidenote you can try to use an alternative layout engine ELK or alternative implementations of GraphViz as described here to achieve different layout results:
- https://plantuml.com/elk
- https://plantuml.com/smetana02
- https://plantuml.com/vizjs
