### ISSUE TITLE
Archimate 3 Specifications

### ISSUE THREAD

**Issue by kiebor** [plantuml/plantuml#61]
I've been using the Archimate feature solidly for a while now and would like to see it keep in line with the current specification.

The icon sets for Strategy and Physical layers are missing. Please find them below.

![strategy-capability](https://user-images.githubusercontent.com/14198213/27326519-941da670-55a3-11e7-8530-b3d8d10f2173.png "strategy-capability")
![strategy-course-of-action](https://user-images.githubusercontent.com/14198213/27326520-94208944-55a3-11e7-92dd-88bbc458267f.png "strategy-course-of-action")
![physical-equipment](https://user-images.githubusercontent.com/14198213/27326523-94258232-55a3-11e7-8954-2a77650aeb92.png "physical-equipment")
![physical-facility](https://user-images.githubusercontent.com/14198213/27326521-94222c68-55a3-11e7-9719-6bf055f4e23c.png "physical-facility")
![physical-distribution-network](https://user-images.githubusercontent.com/14198213/27326524-9425902e-55a3-11e7-9564-ba89bffda861.png "physical-distribution-network")
![physical-material](https://user-images.githubusercontent.com/14198213/27326522-9422b87c-55a3-11e7-9f12-f53ff0fb23b1.png "physical-material")
![strategy-resource](https://user-images.githubusercontent.com/14198213/27326525-944141ca-55a3-11e7-9a06-0c3d225a9b47.png "strategy-resource")

**Comment by kiebor** [comment]
Also missing is outcome: ![outcome](https://user-images.githubusercontent.com/14198213/27326802-6cf7ca8e-55a4-11e7-811b-70bb469eba1d.png "outcome")

In addition, I'd be happy to align the icons you have semantically to the correct layers if you need.

**Comment by arnaudroques** [comment]
Nice idea!
And thanks for the icons!

So the last beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

allows now this:

```
@startuml
rectangle "business strategy-capability" <<$archimate/strategy-capability>>
rectangle "business strategy-course-of-action" <<$archimate/strategy-course-of-action>>
rectangle "business strategy-equipement" <<$archimate/strategy-equipement>>
rectangle "business strategy-facility" <<$archimate/strategy-facility>>
rectangle "business strategy-distribution-network" <<$archimate/strategy-distribution-network>>
rectangle "business strategy-material" <<$archimate/strategy-material>>
rectangle "business strategy-resource" <<$archimate/strategy-resource>>
rectangle "business strategy-outcome" <<$archimate/strategy-outcome>>
@enduml
```

This will be released in next official release.

**Comment by kiebor** [comment]
That's great. However, some icons are misaligned.

should be:
archimate/strategy-capability
archimate/strategy-course-of-action
archimate/strategy-resource
archimate/physical-facility
archimate/physical-material
archimate/physical-equipment
archimate/physical-distribution-network
archimate/motivation-outcome

As an added note, I have a massive definitions file I include with every diagram that aligns the icons to the correct scope and colorizes the artifacts to match. There are 2 scopes commented out due to the missing icons. Is there any way you could make it more official as part of the PlantUml build (exact naming conventions not withstanding). Also feel free to ignore the macros.

[archimate.txt](https://github.com/plantuml/plantuml/files/1092145/archimate.txt)

I love the archimate notation, but not the official tools -- and have been writing a plantuml plugin for visio to help avoid having to use them. This update will help greatly in achieving that.

Thanks.

**Comment by arnaudroques** [comment]
Sorry, I do not understand the "misaligned" word. All icons are 16x16 pixels. Is this related to their colors ?
Or do you want to rename some icon names ?
It would be nice if you could give more precise suggestions!

Regards,

**Comment by kiebor** [comment]
Apologies. I meant the names. I've scoped the icons to layers per archimate 3 specification in my definitions file.

**Comment by arnaudroques** [comment]
So you want to rename "archimate/strategy-capability" right ? It would be great if you could provide something like:

archimate/strategy-capability --> archimate/new-name-for-strategy-capability

Otherwise, we are confuse about the real need.
Thanks!

**Comment by kiebor** [comment]
For renaming the icons:

archimate/strategy-capability --> OK
archimate/strategy-course-of-action --> OK
archimate/strategy-resource --> OK
archimate/strategy-facility --> archimate/physical-facility
archimate/strategy-material --> archimate/physical-material
archimate/strategy-equipment --> archimate/physical-equipment
archimate/strategy-distribution-network --> archimate/physical-distribution-network
archimate/strategy-outcome --> archimate/motivation-outcome

Does that make sense?

In terms of a change to syntax, it would be nice if I could type something like:
Archimate <SCOPE>  <NAME> <ICON>

and that would produce the same result as:
rectangle <NAME> <ICON> <COLOUR>

I attached my definitions file a few posts up to give an indication of what I'm using to simplify my usage.
I have there the layers colour coded as:
BUSINESS #yellow
APPLICATION #A9DCDF
MOTIVATION #B19CD9
STRATEGY #F6E4CC
TECHNOLOGY #lightgreen
PHYSICAL #CCFFCC
IMPLEMENTATION #FFA6BF

Example syntax could be:
Archimate APPLICATION DoSomething <<$application-function>>

to give the same result as currently:
rectangle DoSomething <<$archimate/application-function>>  #A9DCDF

I hope that clarifies a few things.

**Comment by arnaudroques** [comment]
> Does that make sense?

Yes, that's perfect, thanks!

So in last beta https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
- We have fixed the icon names
- We have added a new command: `archimate #APPLICATION DoSomething <<application-function>>`

Note that we treat #BUSINESS / #APPLICATION / ... as regular colors (it's just new color names to us).
It's really a draft and a first proposal : feel free to make other suggestions, especially if you want to change the order of arguments in the new "archimate" command.

So now the following examples are working:
```
@startuml
rectangle "business strategy-capability" <<$archimate/strategy-capability>>
rectangle "business strategy-course-of-action" <<$archimate/strategy-course-of-action>>
rectangle "business physical-equipment" <<$archimate/physical-equipment>>
rectangle "business physical-facility" <<$archimate/physical-facility>>
rectangle "business physical-distribution-network" <<$archimate/physical-distribution-network>>
rectangle "business physical-material" <<$archimate/physical-material>>
rectangle "business strategy-resource" <<$archimate/strategy-resource>>
rectangle "business motivation-outcome" <<$archimate/motivation-outcome>> #MOTIVATION
@enduml
```

```
@startuml
archimate #APPLICATION DoSomething <<application-function>>
archimate #MOTIVATION  SomeMotivation
@enduml
```

**Comment by kiebor** [comment]
The new command works great. I have noticed that I can't use aliases or names with spaces.
For example:
'archimate #APPLICATION "Some Function" <<application-function>>'
and
'archimate #APPLICATION SomeFunction as App_Func1 <<application-function>>'

produce errors.

**Comment by arnaudroques** [comment]
Thanks for your tests, it really helps!
We've fixed those in last beta
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

There are probably some other issues, so do not hesitate to post again here!
Regards,

**Comment by aadrian** [comment]
@arnaudroques Any chance committing (those) changes to GitHub instead of just providing binaries from a private DropBox?

https://github.com/plantuml/plantuml/commits/master does not seems to contain "individual commits" but "source backups" on each release :(. 

Also the https://github.com/plantuml/plantuml/pulls seems to be totally ignored :( .

Thank you.

**Comment by kiebor** [comment]
That's working great now. I also have some other suggestions.

2 important and useful features of Archimate are grouping and junctions. 
Groups are used to show how multiple artefacts aggregate or compose under another concept, artefact or scope. I can use the built-in frame, package, rectangle etc command, but the results are not perfect:

`@startuml
archimate #Motivation "Secure Data Transfer" as dataTrans <<requirement-filled>>
frame "VPN Solution" as vpnSolution {
archimate #Technology "VPN Server" as vpnServerA <<technology-device>>
archimate #Technology "Client Server" as vpnServerB <<technology-device>>
archimate #Technology "VPN Gateway" as softwareA <<technology-system-software>>
archimate #Technology "VPN Client" as softwareB <<technology-system-software>>
archimate #Technology "Network Path" as coms <<technology-communication-path>>
archimate #Technology "Internet / Cloud" as network <<technology-network>>
archimate #Technology "VPN Service" as vpnService <<service>>
}
vpnSolution .up.|> dataTrans
vpnService <|.down. coms
coms -left- softwareA
coms -right- softwareB
vpnServerA *-up-> softwareA
vpnServerB *-up-> softwareB
network -left- vpnServerA
network -right- vpnServerB
network .up.|> coms
@enduml`

![vpnSolution@1-21](http://www.plantuml.com/plantuml/svg/dPDHJuCm4CVVIVWEpNmpANw1XSnfOdnmMRB5zmQEqGWjjbV8ulpkjgKCMDH5t-Z_Uh__tVLOQMGAJLt54LDPoMk6G6vU9FAM8PU2B7QG6GNaaI4ZUyM4Ba0j2DCajueNo7AfuDrm1JK8f0MlAiZJD8uAnMeWYzVjXknaPHpFPxQD6CxaOsQyXwmKifA7OqW3rGOxb-HFzzOFp_Te3YtFmDdzm7cek2thMzJwZoXNqfDLEtRq82qBx9Y2YvBqKIFKT8XU0VRrpNZh__8sW9rKRsJBiFJ4JDPw3hDARGJF_FFInbxyXVSi49G097UsJ6bopnJ1P8ODufLUtTZjYAUlO8-MfFilb_uPHzC5IKoJdD9ns_hea7XASjc9nFSPHxvRMa61T7oRGLRyK4xqzHdaLkgMceQcqwJ9abm4RUOmWk0rWYQXu3TonbZegIzw1IAtF-0N "vpnSolution@1-21")

The group should be handled the same way as an individual artefact with the arrow centered on the side it comes from rather than being constrained to the corners. Also, aggregate groups should have a dashed outline, composition groups a full line.

It would be nice if I could have the syntax to specify.

e.g.

`Archigroup <NAME> <GROUPTYPE: Aggregate / Composite> {
<OTHER OBJECTS>
}`

--------------------------

Junctions indicate decisions and conditions and I would normally implement as below:
`@startuml
allow_mixing
circle JunctionAnd #black
circle JunctionOr #whitesmoke
rectangle GO #lightgreen
rectangle STOP #red
rectangle WAIT #orange
GO -up-> JunctionOr
STOP -up-> JunctionOr
STOP -down-> JunctionAnd
WAIT -down-> JunctionAnd
@enduml`

![junctions@1-12](http://www.plantuml.com/plantuml/svg/TO_12iCW44JlWlyWUCulbEHKsek51d8iLXSZqRLi5FlvbPo4jiUTjpCxE-vPKounSAP3IFKH_TkZuynuCW74jQ39Fk64LiXdq6RxGeg4hAlFiCUq0MS49cjqRUEiX0pUhTaH0FRaFgkRa0Is5vVfCWkPg4qjffc7yXfEtHtE3jy_sQQA7MYLEJioVv8HqBQ_Fm00 "junctions@1-12")

The problem with the new Archimate command is that it produces an error if I mix with Circle.

It would also be nice if we could have an Archimate specific syntax to create the Junctions:
`Junction-Or <NAME>`
`Junction-And <NAME>`

Also that the border colour defaults to black in both cases.

I hope that explains the requirement adequately and is not too much of an ask.

Thanks.

**Comment by kiebor** [comment]
I've updated the issue title to better reflect the ongoing conversation.

**Comment by arnaudroques** [comment]
@aadrian Yes, those changes will be committed in next release in GitHub. I understand that this way of working is strange, but right now, we are sticking to this. Sorry about that

@kiebor 
The "Archigroup" feature is somehow more difficult to implement. It would be better if you create a new issue with this only subject.

About function, we are trying to minimize the number of keywords. For "archimate" keyword, there was no other option than adding a new keyword.
For function, we slightly change the way of defining circle:
* You can now use them without "allow_mixing"
* You can use color definition right after "circle" (or any other keywords BTW)

So now, you can have with last beta
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

```
@startuml
!define Junction_Or circle #black
!define Junction_And circle #whitesmoke

Junction_And JunctionAnd
Junction_Or JunctionOr

archimate #Technology "VPN Server" as vpnServerA <<technology-device>>

rectangle GO #lightgreen
rectangle STOP #red
rectangle WAIT #orange
GO -up-> JunctionOr
STOP -up-> JunctionOr
STOP -down-> JunctionAnd
WAIT -down-> JunctionAnd
@enduml
```

Even if we focus on UML, we are happy to help Archimate users, as long as we can keep this consistent with UML diagrams.
So you can go on with suggestions, even if we do not promise to implement them all :-)

**Comment by kiebor** [comment]
That's great. I can live with using a macro for junctions now that allow_mixing is no longer necessary.

Thanks.
