### ISSUE TITLE
Salt runtime exception

### ISSUE THREAD

**Issue by trothwell** [plantuml/plantuml#62]
http://www.plantuml.com/plantuml/png/AqxCAU6gvghMud9Kg55mud86abfSjLor0000

Actual exception (will work once issue is fixed)
![error](http://www.plantuml.com/plantuml/png/AqxCAU6gvghMud9Kg55mud86abfSjLor0000)

```
@startuml
salt
{
{*
A | B
C | *
}
}
@enduml
```

**Comment by danwos** [comment]
Any updates on this?
I'm not able to to get any salt interface running with the latest plantuml version (1.2017.20)

**Comment by arnaudroques** [comment]
Ok, we'll look into this.
But there is a syntax error in your diagram. I am not sure about you are trying to do.
Are you trying to draw a table or a menu ?

The following example are working fine:

http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEp2dXgkQgLkPoLAXHSE9o1f9QNBL0w92Qbm9K0G00

```
@startuml
salt
{
{#
A | B
C | *
}
}
@enduml
```


http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIfEp2dXgkQgrb9mLAXHS5AevNBcgWL2XzIy5A0y0000

```
@startuml
salt
{
{* A | B }
C
}
}
@enduml
```

**Comment by danwos** [comment]
Thanks for the fast response.
After a small research of my error, it may not be related to the one of the issue reporter. 

**Error reason:** If "salt" starts with leading whitespaces, an error gets thrown:
```
@startuml
   salt
{
  Just plain text
}
@enduml
```
If using "@startsalt", it's working and the content itself can have leading whitespaces.

**Why this may be important?**
I'm using plantuml inside sphinx.
And normally a plantuml code integration looks like this:
```
.. uml::

    @startuml
        node test
        node test2
        test -> test2
    @enduml
```
Trying to use "salt", this kind of text structuring is not possible. 
This does not work, as "salt" has leading whitespaces:
```
... uml::
    
    @startuml
        salt
        {
            Just plain text
        }
    @enduml
```
Currently it must look like this:
```
... uml::
    
@startuml
salt
   {
      Just plain text
   }
@enduml
```
or you sue @startsalt instead:
```
... uml::
    
    @startsalt
    {
        Just plain text
    }
    @endsalt
```

**Preferred change**: As the error message is not really telling what went wrong, leading whitespaces in front of "salt" should be automatically removed. (This seems to be already done for each other plantuml command).

**Comment by arnaudroques** [comment]
Thanks for the detailed report.
Last beta http://beta.plantuml.net/plantuml.jar ignores leading whitespaces in front of "salt".
Tell us if it's not working for you!

**Comment by danwos** [comment]
Works! Thanks for fixing this.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @trothwell, @danwos for the report.
- Thanks PlantUML team for your work.
	
Regards.
