### ISSUE TITLE
mindmap: Markdown syntax does not support space indentation

### ISSUE THREAD

**Issue by chenshanhai-mc** [plantuml/plantuml#622]
Markdown syntax supports '\t' indentation, but does not support space indentation

**Comment by The-Lum** [comment]
Hello @chenshanhai-mc,
- What is your PlantUML version?

With the _(last)_ version (V1.2021.9), it seems OK:
```puml
@startmindmap
* r
 * d1
  * e1
  * e2
 * d2
@endmindmap
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgoStCIybDBE3IKYZYKj1II37aKW1IgL3A22ncnEMGcfS2LGa0)](http://www.plantuml.com/plantuml/uml/SoWkIImgoStCIybDBE3IKYZYKj1II37aKW1IgL3A22ncnEMGcfS2LGa0)

See similar request here [QA-12230](https://forum.plantuml.net/12230/allow-significant-indentation-beginning-mindmap-diagram)

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @chenshanhai-mc for the report.
- Thanks PlantUML team for your work.

Regards.
