### ISSUE TITLE
Services in PlantUML

### ISSUE THREAD

**Issue by nathanvercaemert** [plantuml/plantuml#628]
I apologize if this is made clear somewhere. I've looked on the website and in napkin as well, and I didn't find anything.

I'm studying services, and sequence diagrams are very useful. I'm wondering if PlantUML has functionality to express one message "overtaking" another: one arrow from an entity begins before another arrow but reaches its destination afterwards. Does this make sense? The horizontal arrows in a basic diagram would cross each other.

**Comment by The-Lum** [comment]
Hello @nathanvercaemert,

You can request this as a wanted feature; and see similar request here, _if that seems the same meaning..._:
- https://forum.plantuml.net/6684/non-instantaneous-messages-in-sequence-diagram
- https://forum.plantuml.net/7884/non-instantaneous-activities
- https://forum.plantuml.net/13361/non-instantaneous-request-transmission-time
- https://forum.plantuml.net/1072/sequence-diagram-crossed-arrows
- https://forum.plantuml.net/14145/plantuml-draw-odd-line?show=14151#c14151

Regards,
Th.

**Comment by nathanvercaemert** [comment]
Thanks for looking into this. That post about non-instantaneous-activities is what I was asking about. Seems like sequence diagrams are the wrong medium for this. Closing issue.
