### ISSUE TITLE
Plantuml grammars and syntax

### ISSUE THREAD

**Issue by kiebor** [plantuml/plantuml#63]
I'm writing a plantuml parser and lexer for .net. Is there a master file or default keywords overview, BNF or AST?

**Comment by aadrian** [comment]
@kiebor 
This old documentation seems detailed:
https://github.com/arnaudroques/plantumlguide
(a more actual one would be nice however)

and than there's this:
http://plantuml.com/developpers
Where it's described how to check stuff from tools.

**Comment by kiebor** [comment]
This did it for me: `java -jar plantuml.jar -language`

Thanks.

**Comment by jgoppert** [comment]
I wrote a code generator using Antlr4 here and have a grammar file that I came up with that works for my purposes: https://github.com/jgoppert/plantuml_codegen/blob/master/src/plantuml_codegen/Plantuml.g4 It focuses on class diagrams as that is my main use case right now.

**Comment by aadrian** [comment]
@jgoppert if the grammars are Atlr based, than the best place for them is: https://github.com/antlr/grammars-v4 , not a private repo, since this way, they get reviewed/fixed/updated by other users and by the authors too.

**Comment by jgoppert** [comment]
Since I added some arbitrary structure to the connector comments for my use case, I was hoping to get some feedback from the authors of plantuml to make sure the grammar is stable before we make a PR to antlr.

**Comment by kiebor** [comment]
In the end there was an easier way to do this. I used text mate for visual studio plus a grammars file. The result is a plantuml plugin for visual studio 2017 [here](https://github.com/kiebor/PlantUml-Language-Service). 

Thanks, @aadrian for the assistance!
