### ISSUE TITLE
Allow nesting automatic namespaces

### ISSUE THREAD

**Issue by pawelszramowski** [plantuml/plantuml#634]
As shown in [the manual](https://plantuml.com/class-diagram#13d28e8dfc702e34), automatic namespaces are not nested if they have a common segment (`net` there). An option to nest them would be useful:
```plantuml
@startuml
' c1 will be in foo namespace
class foo.c1

' CURRENT: c2 will be in foo.bar namespace
' REQUEST: c2 will be in bar namespace nested in foo namespace
class foo.bar.c2
@enduml
```

In other words, the previous diagram is currently equivalent to this diagram:
```plantuml
@startuml
set namespaceSeparator none

namespace foo {
    class c1
}
namespace foo.bar {
    class c2
}
@enduml
```
and this new option (e.g. `set namespaceNesting true`) would make it equivalent to this one:
```plantuml
@startuml
namespace foo {
    class c1
    namespace bar {
        class c2
    }
}
@enduml
```

**Comment by Amegatron** [comment]
Agree. Such feature would be useful.

**Comment by BenceSzalai** [comment]
It also breaks diagrams when later in the same file those nested namespaces are declared explicitly. Some parts of the engine recognises that they are the same (linking works and the other one defined with proper explicit nesting is not rendered as a duplicate) but the referenced namespace is rendered in the root namespace. As a workaround I can move the reference with the multilevel nested workspace later in the file, that way the issue can be worked around.

E.g. this works:
```wsd
namespace a {
    namespace b {
        namespace c {
            class D
        }
    }
}
class X

X --> a.b.c.D
```

But this is broken:
```wsd
class X

X --> a.b.c.D

namespace a {
    namespace b {
        namespace c {
            class D
        }
    }
}
```

This makes diagram editing quite painful sometimes, because one cannot maintain the links next to the related classes, sometimes they have to be moved to a separate section at the end of the diagram file. In complex diagrams with multiple namespaces it can get hard to manage.

**Comment by The-Lum** [comment]
Hi @pawelszramowski, @BenceSzalai, and all,

Similar to:
- https://github.com/plantuml/plantuml/issues/632#issuecomment-1418254779

With last changes on namespaces and packages (see [news](https://plantuml.com/en/news)): _it seems quasi fixed._
```puml
@startuml
' c1 will be in foo namespace
class foo.c1

' REQUEST: c2 will be in bar namespace nested in foo namespace
class foo.bar.c2
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuL9NI3PKAC_CoL58IbN8p5D8oyzNo4lCJIqkI4nEvKhEIImk1edf9Hjo0TK6kGQ6kWQ7M2aa6o5hIaeiGcXIo4ijBabDmMSOKBrUiX6NGsfU2j0D0000)](https://www.planttext.com/?text=SoWkIImgAStDuL9NI3PKAC_CoL58IbN8p5D8oyzNo4lCJIqkI4nEvKhEIImk1edf9Hjo0TK6kGQ6kWQ7M2aa6o5hIaeiGcXIo4ijBabDmMSOKBrUiX6NGsfU2j0D0000)


@arnaudroques:
- Perhaps only the name (`foo.bar` instead only `bar` on the header of `bar` package) is now **wrong**...
- See also the remark of @BenceSzalai here:
  - https://github.com/plantuml/plantuml/issues/632#issuecomment-1418285740

Regards.

**Comment by arnaudroques** [comment]
This should be [fixed now](https://www.plantuml.com/plantuml/umla/SoWkIImgAStDuIh9BCb9LKZBh4XDKUHILqWsL2ZFpCbHI4fLoCnJIClFLyXBp4qjBaXCJkLApaaiBWQ9wIKRSW7L1ha6Xhe6XrWf91iXQqfAB49eKiXBBIv9JS5d652zNh8HbqDgNWhGGG00).
There must be some other issues, so please post when you'll find some.
Thanks!

**Comment by pawelszramowski** [comment]
Fixed since 1.2023.2beta2 without a new option. Thanks!

However, it should be noted that adding `set separator none` suggested in the news is not going to fix old diagrams in new PlantUML. The following diagram will consist of classes named `foo.c1` and `foo.bar.c2` without any namespaces:
```plantuml
@startuml
set separator none

class foo.c1
class foo.bar.c2
@enduml
```

**Comment by Amegatron** [comment]
I looks like a correct behaviour, because this option tells PlantUML that there is not separator. And thus, those are just independent class names.

**Comment by pawelszramowski** [comment]
@Amegatron I'm not saying it's incorrect. I'm saying the news entry is somewhat misleading:
> You can also[ disable namespace management](https://www.plantuml.com/plantuml/umla/1S714S8m30J0lwgu2gWX1V2ZWXiZCWP7yKXdFWozPtShCRMEOUL2-MHIPoBES6k3LNWeU-nca-t3tV7cbxUbFl0pe8SyNsoEUo-P_MtpUAvZN000) using `set separator none`, in which case you get back a behavior similar to older versions of PlantUML.

It may make users think `set separator none` is going to fix the old diagrams in the new PlantUML which isn't the case.
