### ISSUE TITLE
Link in `ref` element not displayed

### ISSUE THREAD

**Issue by redcatbear** [plantuml/plantuml#635]
## Situation

When adding a link `[[...]]` in a `ref` element of a sequence chart, that link does not appear unless it is prefixed by regular text.

Since links are especially useful in `ref` sections, I think this should work.

## Steps to reproduce

```
@startuml
Participant A
ref over A : [[link does not work]]
ref over A : [[link neither does this]] here
ref over A : see [[link this works]]
@enduml
```

### Reproducibility

100%

### Environment

* Plantuml 8059
* dot - graphviz version 2.43.0 (0)
* Linux 5.11.0-31-generic `#33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by gwilherm** [comment]
Are ref supposed to manage links in a special way ?
Because I found a fix for this issue but a removed some code that I don't understand what is it supposed to do.
I believe that I may have break something :D

![image](https://user-images.githubusercontent.com/1017720/160493034-7a00288a-b2c3-4a2d-9f2b-e9b6a0dfe9b7.png)

https://github.com/gwilherm/plantuml/commit/429f4b1598bc7f51f1f35ce963a422fd04750b81

**Comment by The-Lum** [comment]
@gwilherm: _Good, but..._

I liked the idea of setting the link at the beginning for the whole shape of the ref., as:

```puml
@startuml
title test of link on ref
ref over A : [[link]] (Link on the whole shape)\n with words on ref
ref over A : [[https://plantuml.com/link]] (Link on the whole shape)\n with words on ref
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/dSsn3i8m40FGlL_X4HQwToexVr0wHFIgHAHtKSwGtwULM5aOFDbw7fsXyhNbZebPG772LkIaJvYYojhjWRsbuee1qtHKyupJxJjX5BHeMU0n53dV5IqnebbT_8SHoU93tvSSz7Y_F6ph_u97qMK7FW00)](http://www.plantuml.com/plantuml/uml/dSsn3i8m40FGlL_X4HQwToexVr0wHFIgHAHtKSwGtwULM5aOFDbw7fsXyhNbZebPG772LkIaJvYYojhjWRsbuee1qtHKyupJxJjX5BHeMU0n53dV5IqnebbT_8SHoU93tvSSz7Y_F6ph_u97qMK7FW00)

_Click to the image to go to the PlantUML Online server, then see the link in action..._

_An hackathon or a review of link management must be perhaps plan to improve that..._

Regards.

**Comment by The-Lum** [comment]
Hello @gwilherm, @arnaudroques, and all,

_After second analyse..._
In fact the better syntax _(consistent with other link examples)_ for that _(link on whole shape)_ is perhaps:
```puml
@startuml
title test of link on ref
ref over A [[link]] : (Link on the whole shape)\n with words on ref
ref over A [[https://plantuml.com/link]] : (Link on the whole shape)\n with words on ref
@enduml
```

Then perhaps change only the order of those lines and re-test your change:
https://github.com/plantuml/plantuml/blob/b38adcfcdcf2b1f0f0c8424c2b51e3f7a75a6e3f/src/net/sourceforge/plantuml/sequencediagram/command/CommandReferenceOverSeveral.java#L70-L76

to:

```java
new RegexLeaf("PARTS",
		"(([%pLN_.@]+|[%g][^%g]+[%g])([%s]*,[%s]*([%pLN_.@]+|[%g][^%g]+[%g]))*)"), //
RegexLeaf.spaceZeroOrMore(), //
new RegexOptional(new RegexLeaf("URL", "\\[\\[([^|]*)(?:\\|([^|]*))?\\]\\]")), //
RegexLeaf.spaceZeroOrMore(), //
new RegexLeaf(":"), //
new RegexLeaf("TEXT", "(.*)"), RegexLeaf.end());
```

_If that can help._
Regards.

---

_Just for traceability; Here is a similar request here about the general issue:_
- https://forum.plantuml.net/10403/unable-to-link-inside-a-ref-if-the-content-is-the-link-alone

**Comment by gwilherm** [comment]
Hello, I also found one working pretty well : 
`\[\[([^\s\{]*)(?:\s*\{(.*?)\})?(.*?)?\]\]`
That you can test here : https://regex101.com/r/jaD6G6/1

![link-in-ref](https://user-images.githubusercontent.com/1017720/160706729-45433696-484c-4980-af26-65aacfc53083.svg)

Gwilherm.

**Comment by The-Lum** [comment]
Hello @gwilherm, and all,

About URL and regex topic, see also:
- https://forum.plantuml.net/13489/error-in-sharepoint-url-containing
- https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/UrlBuilder.java
- https://github.com/plantuml/plantuml/blob/master/test/net/sourceforge/plantuml/UrlBuilderTest.java

Regards.

**Comment by The-Lum** [comment]
In fact the big 🧹 'spring cleaning'  will be to replace all pseudo `matching URL regex` on `RegexLeaf("URL", ...)` by `UrlBuilder.getRegexp()`!

_Go to open an hackathon..._

**Comment by gwilherm** [comment]
Ok next round with UrlBuilder :D 

With this simple Regex:
```
RegexLeaf.spaceZeroOrMore(), //
new RegexLeaf(":"), //
RegexLeaf.spaceZeroOrMore(), //
new RegexOptional(new RegexLeaf("URL", "(\\[\\[.*?\\]\\])")), //
new RegexLeaf("TEXT", "(.*)"), RegexLeaf.end());
```

And the builder:
```
final UrlBuilder b = new UrlBuilder(null, UrlMode.STRICT);
Url u = null;
if(url != null) {
	u = b.getUrl(url);
}
```

This works pretty well !

**Comment by arnaudroques** [comment]
> Ok next round with UrlBuilder :D

Thanks all for your tries!
This makes indeed sense to use `UrlBuilder` here.

The reason why we don't right now is just because `CommandReferenceOverSeveral` class has been written a long time ago, even before we introduce `UrlBuilder`.

Since we are very lazy :-) , would you mind pushing a pull request ?

**Comment by gwilherm** [comment]
After 3 oopsies in my repo here it is :  #976
