### ISSUE TITLE
Error in creole example on website

### ISSUE THREAD

**Issue by Poddster** [plantuml/plantuml#64]
Not sure if this is the right place for a bug report, as it's about your website rather than the tool, but the list example on the creole webpage doesn't correctly render the sub list:

http://plantuml.com/creole

![image](https://user-images.githubusercontent.com/3941642/28238407-b20b0870-694a-11e7-8312-4a87d023c2b8.png)

**Comment by VladimirAlexiev** [comment]
This is now fixed

**Comment by evantill** [comment]
Feel free to reopen if the problem still exists. Thank you.
