### ISSUE TITLE
Backward in activity (beta) break in swim lanes

### ISSUE THREAD

**Issue by IrhamMaulani** [plantuml/plantuml#641]
In the beta version of activity diagrams, the combination of a backward reference and swim lanes does not work.

This is the combination that produces a broken diagram (the backward node flows somewhere in the middle)

There is another same question from 2020 in here https://forum.plantuml.net/12427/backward-in-activity-beta-does-not-work-with-swim-lanes

Here is the example
`|#AntiqueWhite|Sistem|
|Admin|
repeat :Generate Again;
:Generate Foo;
|Sistem|
:Bar;
backward: Do bar;
repeat while (Is foo?)  is (yes)
->no;
:finish foo;
stop`

And here is the diagram
![image](https://user-images.githubusercontent.com/33886979/131380267-3b20d8fa-ec73-4690-8639-dcd678c97609.png)

**Comment by The-Lum** [comment]
See also:
- `QA-14473` - https://forum.plantuml.net/14473/backward-in-activity-beta-break-in-swim-lanes

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @IrhamMaulani for the report.
- Thanks PlantUML team for your work.

Regards
