### ISSUE TITLE
bottom or top for note on method or field is not working

### ISSUE THREAD

**Issue by adrhc** [plantuml/plantuml#660]
e.g. the following fails:

```
abstract SectionsOwners {
AbstractComponent[] components
Map<partName, AbstractComponent> parts
+initOwners(stateHolder)
{abstract}+createOwner(partName, 
  statePart, dontInitializeState)
+getStateParts(): Map<partName, value>
}

note bottom of SectionsOwners::initOwners
- iterates stateHolder parts
- creates each part
  (aka section)
  owning component
- sets each owner state
- init owners
end note
```

**Comment by The-Lum** [comment]
Hello @adrhc,

You can see this same topic here:
- https://github.com/plantuml/plantuml/issues/325#issuecomment-878513174

Regards.

**Comment by The-Lum** [comment]
Hello @adrhc,

For **top** and **bottom** note, a workaround is to use `floating note`, like:

```puml
@startuml
abstract SectionsOwners {
AbstractComponent[] components
Map<partName, AbstractComponent> parts
+initOwners(stateHolder)
{abstract}+createOwner(partName, 
  statePart, dontInitializeState)
+getStateParts(): Map<partName, value>
}

note as B
- iterates stateHolder parts
- creates each part
  (aka section)
  owning component
- sets each owner state
- init owners
end note

SectionsOwners::initOwners -- B
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/PP5DIyD048RlyolUOqARFn2aLBtemG_8KJoCoL0NazsmCxLWwNztyn5YyHRc_TY7DtirZdRiMk8FjSYrePBQNF3wSl8I5MUwdPNxqFN1YxUtTzJBjz8JzpTzAddcJhRuPzvX49KspZkREZCrDda8RICnf_FoycLJHqd2QChMIWB6m6kwRD44Ru-fod7hVgGQX9ms1x5gyMYMbxYc-kRsA3kw4FbW0bRSKG5d4bD6yOTdfYqmiIY4wy_nI436NmoTzia922Vl_64T8yLKRCuaKU9KFRoLaAUJalW60mVHzTPbkMw4eaYC-sHDF-SN)](http://www.plantuml.com/plantuml/uml/PP5DIyD048RlyolUOqARFn2aLBtemG_8KJoCoL0NazsmCxLWwNztyn5YyHRc_TY7DtirZdRiMk8FjSYrePBQNF3wSl8I5MUwdPNxqFN1YxUtTzJBjz8JzpTzAddcJhRuPzvX49KspZkREZCrDda8RICnf_FoycLJHqd2QChMIWB6m6kwRD44Ru-fod7hVgGQX9ms1x5gyMYMbxYc-kRsA3kw4FbW0bRSKG5d4bD6yOTdfYqmiIY4wy_nI436NmoTzia922Vl_64T8yLKRCuaKU9KFRoLaAUJalW60mVHzTPbkMw4eaYC-sHDF-SN)

If that can help,
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @adrhc for the report.
- Thanks PlantUML team for your work.

Regards.
