### ISSUE TITLE
Include additional themes (from community)

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#667]
https://github.com/Drakemor/RedDress-PlantUML and https://github.com/isaaceindhoven/plantuml-styler both provide PlantUML themes that are quite nice (and relatively popular):

**Gray tone**
![graytone](https://user-images.githubusercontent.com/333276/132810498-59040dce-8937-4ddb-bd57-dad96501919d.png)

**Isaac**
![isaac](https://user-images.githubusercontent.com/333276/132810501-715c1543-6857-49ff-8d00-1e68c330126f.png)

**Deep sea**
![deepsea](https://user-images.githubusercontent.com/333276/132810502-88cf1989-1f51-42e8-9545-2156669bb71e.png)

**Black and white**
![blackwhite](https://user-images.githubusercontent.com/333276/132810503-25db0e78-982f-4449-8ea5-bee95c4a3a3a.png)

**Dark blue**
![DARKBLUE](http://www.plantuml.com/plantuml/png/hSqn3e9044RXdbF00MHwApHOYOaXuG0Z-ol4tO7Cp4QzlJJUmEfrtslCMJsdM5G1zrbGjeV-VEo6Kr7DCiOSK4xkg-s9b5_rO_Oftx91nqKSulMu96gLdqYBKe_GAinsryZYmwMZnEPGClz4rEis-g-BDwVr9pUGiFKB)

**Light blue**
![LIGHTBLUE](http://www.plantuml.com/plantuml/png/hSmn3e9040NGdbF00MHxAs8mQeA9CNA0aVqASMSWCxDHRw-DDx1wtMlCIJrpAgg8soGekyDkVzbq_RQe9XbIZYX7zyNM8IWzw_laOxvcWmwpECJhOURGAZt0iuOpOgimMvqIYVV7BZ2PGuFvEw5UCgV_ldWHBx-vWSIl7m00)

**Dark red**
![DARKRED](http://www.plantuml.com/plantuml/png/hSmn3i8m30NGlQTe3q2pCnKfJ824Ad40qtneHUn6jYFWzh1m0wQtlS6Sr2ldfakuBO8sxiR3k8zDjyYKQq8xknVRXg3qxE-Bp_LQ3JgjuX3lfvL3L7g0LmqZKbIORSwPn2-dOs0oXmRpTqPVAkV_ldWHbzyyGDBN3m00)
### LIGHTRED
![LIGHTRED](http://www.plantuml.com/plantuml/png/hSqn3e9044RXdbF00MHwAmgCcc1YY1vWP7-5k3kGcTcejvV66rYzxdkDEQld58igu3u9okwuFrpwNLjKammn1vIZ-s9R8kLN_PXypBTiq64MXtWzp8bQvIVIhDGZj0gppJco-FNKKM9pA9b_8kfb7VtNnPlJyfCRI5Zx1G00)

**Dark green**
![DARKGREEN](http://www.plantuml.com/plantuml/png/hSqz3e9044VndbF00MHwAqmW5dx4a7Y0aVqhnDs1pCn6lRqqti3gTR_NcBDwJh6e0kwJe6nt_M7VTzsvg2OPOWueH_V5jaJAh_en-PXlsQ33B0xnUfWJjSfFf5cfHsWLPfjBPF7hwKY9pQ5a_eceb_NqNnTlJijFRY1XxHS0)

**Light green**
![LIGHTGREEN](http://www.plantuml.com/plantuml/png/hSqnhe9048VndbF00HxRlue2WYPe3D43ZEnV8UuEcvdPgBUNnXjOVTtlQzH8BCTGL1wtXL4E-tvtxiUkEnRLmbF87kLiblJVEQ5dVLzipjUia6bb0rizhT6rGW_4LTm8tmfK_qw1s2w7mKLIWpYrTq2TjjLlNRmefg_SWFtM3m00)

**Dark orange**
![DARKORANGE](http://www.plantuml.com/plantuml/png/hSqzpe9048VndbF00LwcVoj8C1P-Q4WymCZ-5UBkG6PcezvU6czWzNI_fp5dzPnYKGNS9a7PjVtkrBV7xQQe9XbY3YX7zyN-YPIVzNtoCL-pGOTP7EBrC2Vgb1z8irAFq2dC_iwHnI-7FIKsXvBvEw9UrjLlNRmuBL-vWOIr7m00)

**Light orange**
![LIGHTORANGE](http://www.plantuml.com/plantuml/png/hSqz3e9044VndbF00MHxAqmmQ88V8Ng0aVqhnDs1pCn6lRqqti3gTRzNgP5OYY4hFEuZ8s_tpUvowZR7PfiL8_SXUUI3sQnhvuHUvMEq8TsIGlg93MnbFqLN2pqH9t4TV2rGNPq3iLqFhOka1d5gdu1oNbx_TV6cEF_a2koNVW40)

Would you accept a pull request that adds the above themes (in https://github.com/plantuml/plantuml/tree/master/themes)?

Thanks!

**Comment by arnaudroques** [comment]
Sure, you can go ahead!

**Comment by Mogztter** [comment]
Actually, plantuml-styler does not use `skinparam` commands but update the SVG DOM: https://github.com/isaaceindhoven/plantuml-styler/blob/05d01f6a79967c0b4bb99336fb19da2c66766dfa/src/app/services/generate.service.ts#L127-L188

So it's not possible to include them as PlantUML themes.
