### ISSUE TITLE
Theme procedures like $success("") don't work after a newline

### ISSUE THREAD

**Issue by erodewald** [plantuml/plantuml#694]
## using <color> tags

I often describe interactions between nodes like this: 

### example
```
node NodeA
node NodeB

NodeA -> NodeB: <color:red>1</color> Start of really long test \n<color:red>2</color> and a new line describing more things
```

### screenshot
![image](https://user-images.githubusercontent.com/1534259/136093806-08ac7375-388d-46e1-9c45-5f2bc02d43ea.png)

## using procedures

With the procedures found in themes, I started adopting `$failure("2")` in lieu of the more clunky html syntax. https://github.com/plantuml/plantuml/blob/c8748421584d3c0edb734c271721ed0a0b8e79a0/themes/puml-theme-materia.puml#L69-L71

 However, When I do that, nothing after the linebreak seems to be preprocessed: 

### example

```
node NodeC
node NodeD

NodeC -> NodeD: $failure("1") Start of really long test \n$failure("2") and a new line describing more things

```

### screenshot
![image](https://user-images.githubusercontent.com/1534259/136093731-bdabe0d2-0fba-4359-adfc-47b6fb9024e2.png)

Am I using this incorrectly, or is this a bug?

**Comment by The-Lum** [comment]
Hello @erodewald,

A possible workaround is to use instead a return `function`:
```puml
!function $failure($msg) 
!return "<font color=red><b>" + $msg + "</font>"
!endfunction
```
Then we observed the expected result:

```puml
@startuml
!function $failure($msg) 
!return "<font color=red><b>" + $msg + "</font>"
!endfunction

node NodeC
node NodeD

NodeC -> NodeD: $failure("1") Start of really long test \n$failure("2") and a new line describing more things
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/HOz1IyH038Nl-HMlmnvSH4IFKik2dhruzJBRIUl0D85C1l7VErMab-Gb-KZoBjMZUTiA3KkJsRCAJalCfHdVdBQwda63iJSJX75HSSnQr9wDqpHUfu1Rx5XFORpVvrEWWINzRoCIJOot7buE-Khqsy7Tz5S_7LV3GpZZVNyBki0ublADehB2kJe-v20VEnab8KBu2oKB8t6TBLzpnpSrXdzsMUd2ahhB7m00)](http://www.plantuml.com/plantuml/uml/HOz1IyH038Nl-HMlmnvSH4IFKik2dhruzJBRIUl0D85C1l7VErMab-Gb-KZoBjMZUTiA3KkJsRCAJalCfHdVdBQwda63iJSJX75HSSnQr9wDqpHUfu1Rx5XFORpVvrEWWINzRoCIJOot7buE-Khqsy7Tz5S_7LV3GpZZVNyBki0ublADehB2kJe-v20VEnab8KBu2oKB8t6TBLzpnpSrXdzsMUd2ahhB7m00)

See also doc. here:
- https://plantuml.com/preprocessing

If that can help,
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @erodewald for the report.
- Thanks PlantUML team for your work.
	
Regards.
