### ISSUE TITLE
Dividing diagram not working

### ISSUE THREAD

**Issue by Konafets** [plantuml/plantuml#7]
According the documentation the keyword `newpage` splits a big diagram into several pages. This only works with an empty diagram 

```
@startuml

newpage

@enduml
```

This above code produces two empty pages, but produces an error when I add `newpage` between two classes:
`Error line 3 in file: demo.puml
Some diagram description contains errors`

**Comment by arnaudroques** [comment]
Ok, thanks for the report.
It does not work with class diagrams.
This has been fixed in last beta https://dl.dropboxusercontent.com/u/13064071/plantuml.jar
It will be released in next official release.

Regards,

**Comment by useltmann** [comment]
I run into this as well (sequence diagram). This is three years old. Is it still coming?

**Comment by arnaudroques** [comment]
It should be working now.
For us:
```
@startuml
class foo
newpage
class bar
@enduml
```
is working.

Could you post here a non working example ?
Thanks!

**Comment by useltmann** [comment]
Your example is not working for me. When exporting it to txt, png or svg it produces two files but the content is always the first page. I am using the latest docker-image, version is

    PlantUML Server 20190209-2159 / version 1201901

**Comment by arnaudroques** [comment]
Which tool are you using with PlantUML ? 
The webserver does indeed only show the first page.
But some other tools show all pages.

Note sure about the last docker image, but the online server the expected result:

- http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLaZBp-VAIoqlI4nFXOea9HPnEQJcfG3L0000
- http://www.plantuml.com/plantuml/png/1/SoWkIImgAStDuKhEIImkLaZBp-VAIoqlI4nFXOea9HPnEQJcfG3L0000

**Comment by useltmann** [comment]
When i address the server like you do then i get the right images - i wasn't aware of that possibility.

I am using [this VisualStudio Code extension](https://github.com/qjebbs/vscode-plantuml/issues). I will try there then. Thanks for helping.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Konafets for the report.
- Thanks PlantUML team for your work.

Regards.
