### ISSUE TITLE
Theme Gallery is broken (https://plantuml.com/theme-gallery)

### ISSUE THREAD

**Issue by kkweon** [plantuml/plantuml#700]
## Current

- Theme Gallery is broken (https://plantuml.com/theme-gallery) which is linked from 
![image](https://user-images.githubusercontent.com/2981167/136680139-38153f7a-c1c4-48c8-a930-fa5c948877b7.png)

- The alternative gallery[^1] by @bschwarz has only a few subset of what's available today.

## Expected

- There is a theme gallery that shows all available themes by default.

## Related issues

- https://github.com/bschwarz/puml-themes/issues/18

[^1]: https://bschwarz.github.io/puml-themes/gallery.html

**Comment by The-Lum** [comment]
Hello all,

After this time...
_(Before a real announcement)_ Here is my WIP for first public release 🎉...   on this page:
- [PlantUML themes Gallery](https://the-lum.github.io/puml-themes-gallery/) 


Don't hesitate to post questions/remarks on the [discussion page](https://github.com/The-Lum/puml-themes-gallery/discussions).

And special credit to @arnaudroques, @bschwarz and @matthew16550  _(and all the others for the future works to do together...)_

**Comment by arnaudroques** [comment]
Hello @The-Lum 
Your gallery is really great and far better than our own.
So your page [is now referenced here](https://plantuml.com/en/theme#7c37bb7776a666a8). 

Some suggestion: you should make all images clickable (and redirect to the source code of the diagram).

**Comment by bschwarz** [comment]
Looks good, thanks for your work.


A few comments/observations:

   1. +1 on the link to source
   2. I need to update my themes for mindmap, wbs, gnatt, timing,
   wireframe, network diagrams. I will try to update soon.
   3. Question @arnaudroques <https://github.com/arnaudroques>: for *gnatt*,
   *timing*, *wireframe*, *network diagrams*, is there theming for these
   now?
   4. Some of my themes are meant for dark backgrounds. These are:
   *black-knight*, *cyborg*, *cyborg-outline*, *hacker*, *superhero*,
   *superhero-outline*. It would be nice if your gallery could put a dark
   background for these.
   5. You have *resume-light* theme in there. That should be removed. I
   will remove it from the plantuml repo as well.
   6. For the future, I think it would be nice to have brief summaries of
   the themes, so people can browse quickly. Kind of like what I did here
   <https://bschwarz.github.io/puml-themes/gallery.html>.

Cheers,
Brett

**Comment by arnaudroques** [comment]
> 3. Question @arnaudroques <https://github.com/arnaudroques>: for *gantt*, *timing*, *wireframe*, *network diagrams*, is there theming for these now?

- **gantt** : [Work is in progress](https://plantuml.com/en/gantt-diagram#f80ba0c004d810f7)
- **timing** : [Work is in progress](https://plantuml.com/en/timing-diagram#bb2ede32ce6accb8)
- **network diagrams** : [Work is in progress](https://plantuml.com/en/nwdiag#bb2ede32ce6accb8)
- **wireframe** : Nothing started here. This is really different from other, so it's not planned right now.

About style for *gantt*, *timing*, *network diagrams*, this is quite beta, some features are probably missing or not working. We are waiting for user requests or reports to fix them :-)

Regards,
Arnaud

**Comment by The-Lum** [comment]
Hello all,

@bschwarz:
Thanks for your comments/observations.

1. OK, I create the task to [add source link to the diagram](https://github.com/The-Lum/puml-themes-gallery/projects/1#card-71991180)  ↪️But I have no idea for to do that.
_[Hints: as on [real-world-plantuml site](https://real-world-plantuml.com): I need some help ;), or as in the PlantUML doc. site]_
2.  OK, good job...
3. See above answer; And: 
For **Network (nwdiag) diagrams** see: [QA-14478](https://forum.plantuml.net/14478/applying-themes-on-nwdiag-has-no-effect?show=14577#a14577)
for **Wireframe** or **salt** see: [QA-14752](https://forum.plantuml.net/14752) :zany_face:
4. OK; As it is auto-generated, it is difficult to add some additional info... But I understand, they are initially design for dark background, even if the background will be transparent. (Perhaps I must add an exception (to impose a dark background) for those theme: *black-knight*, *cyborg*, *cyborg-outline*, *hacker*, *superhero*, *superhero-outline*)
5. Ok, as you want.
6. Task [Add Brief summaries of the themes](https://github.com/The-Lum/puml-themes-gallery/projects/1#card-72378497) added
But as it is auto-generated, it is difficult to add some additional info.
Perhaps add this directly on the theme (as the `$THEME` variable), _[Hints: why not on a variable like `$THEME_DESC` or other?...]_
Or I create a table with those additional info. only for few themes...


@arnaudroques:

>About style for gantt, timing, network diagrams, this is quite beta, some features are probably missing or not working. We are waiting for user requests or reports to fix them :-)

- Timing diag
For **Timing** style: perhaps add style for label or text (font, color, ...) and for line or arrow and back-color of `concise`, and also color of background for each row separately _(cf. [QA-14388](https://forum.plantuml.net/14388/can-you-color-participant-backgrounds-in-a-timing-diagram))_...
- `JSON` and `YAML` diagram
Then the big issue is for `JSON` and `YAML` diagram... They accept style... but no `include <path_to_theme>` or `!theme` directive... _See [QA-14131](https://forum.plantuml.net/14131)..._

**Comment by bschwarz** [comment]
#4) Yeah, I add a tag to the themes that are dark mode, but I am using
Jekyll on Github pages, and read in a config file.
#6) What I mean by this is, just have a "gallery" page. On the gallery
page, just put one diagram for each theme, so the user has an idea on the
theme. If they like the theme, they can click on that to take them to get
all the diagrams for that theme.

**Comment by arnaudroques** [comment]
> * `JSON` and `YAML` diagram
>   Then the big issue is for `JSON` and `YAML` diagram... They accept style... but no `include <path_to_theme>` or `!theme` directive... _See [QA-14131](https://forum.plantuml.net/14131)..._

It's a hack, [but you can now have](https://www.plantuml.com/plantuml/uml/SoWkIImgoIhEp-DIBCb8pKrLICpDJ4_agkPI00AbjABIp18bAmKbnuA2d5Gb7OXeSMPLAaZG9x4e7IwOd9-JNmGI3KfDKUAgvN98pKi1cmi0) `!theme` with `JSON `and `YAML`.
This is really dirty coding here.

**Comment by The-Lum** [comment]
Thanks for your hack.
I can go to the test.
Then I will create template for `JSON` and `YAML` for the next Gallery...

**Comment by The-Lum** [comment]
Sorry, but here is a first counter example ...  _(Just on testing diagram to adding title...)_

```puml
@startuml
node n [
{{yaml
!theme amiga
fruit: Apple
size: Large
color:
 - Red
 - Green
}}
]
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuShBJqbLo5E8vggkham4yXLBCb9pKnKISpFJ4xdIYaepIwmK70iASbAvYZEhKgqKV1ABqbEvalDpyekik1Hq5O9IKq2KUr5gQXvNRIrNB9T3QbuAq6G0)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuShBJqbLo5E8vggkham4yXLBCb9pKnKISpFJ4xdIYaepIwmK70iASbAvYZEhKgqKV1ABqbEvalDpyekik1Hq5O9IKq2KUr5gQXvNRIrNB9T3QbuAq6G0)

And all unhappy... 😢 
I will also use `title` on `JSON` or `YAML` diagram... (as on Wire diagram! _cf. [QA-14924](https://forum.plantuml.net/14924)_)

It may be too much... _I ask maybe a little too much..._
Thanks for your works.
Regards.

**Comment by bschwarz** [comment]
Ok, latest pull request, <https://github.com/plantuml/plantuml/pull/753> I
updated so that mindmap, wbs diagrams will render in theme colors. It also
*partially* renders the network diagrams, gnatt and timing

I also removed the *resume-light *theme

**Comment by arnaudroques** [comment]
> And all unhappy... 😢

Thanks for the feedback.
[This is fixed in last beta!](https://www.plantuml.com/plantuml/uml/5Sqn3i8m38NX_Pt2780BP2eJ2nChOh38euta99Nh3b3rxfJfrpzzmnBgiLP3wvdIv85j--ZnfvXOALhBg8WIHfberl7sjKIIopmRiPGlazpKH-BLhNk2dENE_C_LoOPznnC3MpwK7m00)

You can go on with you tests :-)

**Comment by The-Lum** [comment]
Thanks a lot @arnaudroques,

In fact now the problem, _for tonight_, is `!pragma layout smetana`:

```puml
@startyaml
!pragma layout smetana
fruit: Apple
size: Large
color:
 - Red
 - Green
@endyaml
```

>[![](https://www.plantuml.com/plantuml/svg/5Soz3G8n30NWtbEO0LWWrL7HKB714_SuHN9-v3X5c1wb-hhl606FXM9owuwhG0shpT1H6AYGhyySIH-z6sNa7vE-u1Vbqwnv4hthc-VcwMILW_NStny0)](https://www.plantuml.com/plantuml/uml/5Soz3G8n30NWtbEO0LWWrL7HKB714_SuHN9-v3X5c1wb-hhl606FXM9owuwhG0shpT1H6AYGhyySIH-z6sNa7vE-u1Vbqwnv4hthc-VcwMILW_NStny0)

But that doesn't make too much sense !!! (because YAML is already layouted by smetana, with or without this directive!)
I will manage otherwise...
_I'm going step by step ..._

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @kkweon  for the report.
- Thanks PlantUML team for your work.

Regards.
