### ISSUE TITLE
Which Unicode font?

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#72]
What Unicode font do you use at http://www.plantuml.com/plantuml?

[this diagram](http://www.plantuml.com/plantuml/png/NP3B2i8m44Nt_OgXMn7QYg8G0WNRbQ88Vi0q3ZQQFaYYuj_RsdUp2_USkPEayaQGKPQGDavQNuJKGf5nX49Z0CkIb48hYnpGWCkkYs3ZnHp28N2XEOoDQCxR2LhUKziIxGJF2tSSBdNGkTs4FzsxAAnyI_iTkNwyNWTLVPku8xUZUxrKA6XQxSShRy_XN2VkjFfF3zNQVWhzdBdXbiCHy-KHgvyw9GyIzGkgweRkxUnbw9NDcwDgyGFTKK6KstvvnXgQyny0) shows fine on your server, but on our installation is missing the 5-digit Unicode chars such as `<U+1F552>`. 

Our setup:
- linux 3.5.0-28-generic, java 1.6.0_25-b06, default encoding: UTF-8
- plantuml 1.2017.16 (20170903), confluence plugin 6.8-SNAPSHOT by avono AG (approx 20170907), graphviz 2.38.9 (20140413)

I thought it's a problem with the default encoding but after setting it to UTF-8 we still have the problem.

**Comment by arnaudroques** [comment]
There is a special command that helps to solve fonts issue.
For example, you can try:
@startuml
listfont This is a test for <U+1F3E2>
@enduml
This diagram will test all fonts available on your server.
On the official server, it gives 
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh9B2v9oyyhKGZ9o2nM0A94XPBKuXA5jFmY1PjGRKCtOrSZEow7rBmKe6e0

So it seems that you need the "Segoe UI Emoji" or "Segoe UI Symbol" font.
Hope this helps!

**Comment by VladimirAlexiev** [comment]
I find "Dialog" most readable (and I think this is the default font). But on our linux installation, "Dialog" doesn't have those unicode chars. We'll investigate where to get a richer font.

**Comment by VladimirAlexiev** [comment]
Here's the first diagram. I want to see how Github renders it:
```
@startuml
hide members
hide circles
class appellation as "<U+260F> Appellation"       <<appellation>>
class right       as "<U+00A9> Right"             <<right>>
class activity    as "<U+1F552> Activity"         <<activity>>
class place       as "<U+1F30D> Place"            <<place>>
class artwork     as "<U+1F3A8> Man-Made Object"  <<artwork>>
class museum      as "<U+1F3E2> Legal Entity"     <<museum>>
@enduml
```

**Comment by VladimirAlexiev** [comment]
- asked https://twitter.com/valexiev1/status/1646492952930164738
- https://superuser.com/questions/876572/how-do-i-find-out-which-font-contains-a-certain-special-character discusses a similar question, but in 2015-2017
- https://www.fileformat.info/info/unicode/char/1F3F7/fontsupport.htm shows 3 fonts that support this particular char:
![image](https://user-images.githubusercontent.com/536250/231772312-560c21b6-7709-4241-b413-5244a3b64dfb.png)

**Comment by VladimirAlexiev** [comment]
I tried to express 3 icons using 3 different styles as per https://plantuml.com/creole:
- `<U+xxxxx>` hex [special chars](https://plantuml.com/creole#5d5a654fa7b639a4)
- `&#nnnnnnn;` decimal [special chars](https://plantuml.com/creole#5d5a654fa7b639a4)
- `<:emoji:>` [emoji names](https://plantuml.com/creole#68305e25f5788db0)

Results:
- Github (PNG preview) shows hex and emoji ok:
```
@startuml
hide empty members
hide empty attributes
hide circle

class "<U+1F3F7> U+1F3F7\n<U+1F527> U+1F527\n<U+1F6E0> U+1F6E0"
class "&#127991; 127991\n&#128295; 128295\n&#128736; 128736"
class "<:label:> label\n<:wrench:> wrench\n<:hammer_and_wrench:> hammer_and_wrench"
@enduml
```

- Plantuml SVG shows hex and emoji ok:
![](http://www.plantuml.com/plantuml/svg/PSr12uCW6CRnkvz26kooooggrIAwh6-mMn1cBnJuob1ZxDlFr6Amq_Fd9o-ssZ1bLXHaNYQWW2_peGWuWjA_n8nHoxWQ2CeNnGKGmWNJcaRryn9tQLSqD4Gl7MM99HyxvO-h9H_HVdy-nKbHbl6T-ktb9hUapAou3LAakHMtnt5T2JQ2g1hgrlvJlHL8FblniT7C444DJ4x3yVfd4Mb1JYkABm00)

- PlantUML PNG shows emoji ok, but chars are missing from hex:
![](https://www.plantuml.com/plantuml/png/PSr12uCW6CRnkvz26kooooggrIAwh6-mMn1cBnJuob1ZxDlFr6Amq_Fd9o-ssZ1bLXHaNYQWW2_peGWuWjA_n8nHoxWQ2CeNnGKGmWNJcaRryn9tQLSqD4Gl7MM99HyxvO-h9H_HVdy-nKbHbl6T-ktb9hUapAou3LAakHMtnt5T2JQ2g1hgrlvJlHL8FblniT7C444DJ4x3yVfd4Mb1JYkABm00)

- The decimal doesn't show on any of the platforms. I used the windows calculator in Programmer notation and I think my decimal char codes are correct?

---

So I'll use the `<:emoji:>` notation, which works for both PNG and SVG output. 
An extra benefit is that emoji are already colored (on the other hand, you cannot recolor them using `<color:colorName>...</color>`).

One can pick emoji from the [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md) or the [Unicode full-emoji-list](https://unicode.org/emoji/charts/full-emoji-list.html)

I'll update the documentation.

**Comment by VladimirAlexiev** [comment]
> Github/PNG preview: can you post a screenshot

Both images above: https://github.com/plantuml/plantuml/issues/72#issuecomment-1507022544 and https://github.com/plantuml/plantuml/issues/72#issuecomment-1506888642 are generated by Github.
If you hover, you can Copy out the source that I put in Github, but Github is smart enough to show PlantUML source as an image.

BTW, it also reprocesses PlantUML image links to "githubusercontent" image links.
Eg `http://www.plantuml.com/plantuml/png/PSr12eCm40NGVKuHB7JJJLNKQaNSr1jq9qYC0mgPK998wUqRfwaKklgV5twcjKuOjw9Yyp811tou5qV04Opz9U6SMSRLGL2v6Ac0CQc4jJogxwUuIxkYuQ7qcYXBYAW4oc_dZQX4t_tnGAih3sFk8IdAClP2sUjDBacPUQ4CKgIv5yhzjxfIOWHLDPpI7wwU1hISlNpAHhD013C8FGtxwvz5h0KzhQZU` 
is rendered as this image on Github: note the URL is different, and what it shows in Github vs PlantUML server is different:
![](http://www.plantuml.com/plantuml/png/PSr12eCm40NGVKuHB7JJJLNKQaNSr1jq9qYC0mgPK998wUqRfwaKklgV5twcjKuOjw9Yyp811tou5qV04Opz9U6SMSRLGL2v6Ac0CQc4jJogxwUuIxkYuQ7qcYXBYAW4oc_dZQX4t_tnGAih3sFk8IdAClP2sUjDBacPUQ4CKgIv5yhzjxfIOWHLDPpI7wwU1hISlNpAHhD013C8FGtxwvz5h0KzhQZU)

**Comment by VladimirAlexiev** [comment]
@arnaudroques https://github.com/plantuml/plantuml/tree/master/src/net/sourceforge/plantuml/emoji/data shows 1177 files.
- But the doc on [emoji](https://plantuml.com/creole#68305e25f5788db0) talks about a much smaller number "Over 580 emojis" and lists 6 Unicode blocks
- Which is the right number? And maybe there are missing Unicode blocks in the documentation?

**Comment by VladimirAlexiev** [comment]
I updated the documentation with the new numbers, added a link to Block 27, counts per block, and links between Emoji and Unicode special chars.
Pleasure working with you!!!

**Comment by VladimirAlexiev** [comment]
@arnaudroques Maybe it's not Github but this Chrome addon that does the visualization:
![image](https://user-images.githubusercontent.com/536250/232326079-d5246a78-b518-4ecb-b8ee-4ab2f2cf6b6c.png)

**Comment by claudio-salvio** [comment]
Hello @VladimirAlexiev 

As far as I know, Github does not render PlantUML code.
Surely your diagram view is produced by the Chrome extension that you mention.

I use another extension called "Markdown Diagrams".
It is available -at least- for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/markdown-diagrams/), [Chrome](https://chrome.google.com/webstore/detail/markdown-diagrams/pmoglnmodacnbbofbgcagndelmgaclel?hl=en) and [Edge](https://microsoftedge.microsoft.com/addons/detail/markdown-diagrams/hceenoomhhdkjjijnmlclkpenkapfihe).

I mentioned this extension in a January 2022 issue because I had been using it for a while and found it very useful.
The issue mentioned is [ [ERD] The size of horizontal lines is not modified according to the number of characters #874](https://github.com/plantuml/plantuml/issues/874), and there you can see a mixture of PlantUML code and images of diagrams.

In my case, since I have the extension active, when I access the issue I see the duplicate diagrams by default but if I double click on the images rendered by the addon, it shows the PlantUML code.

Kind regards,
Claudio Salvio

I💙PlantUML
🙏Thanks to all who make this useful software possible, especially @arnaudroques

**Comment by VladimirAlexiev** [comment]
Thanks @claudio-salvio, you are right!
I use a plugin called "PlantUML Visualizer" (see issue linked above)
