### ISSUE TITLE
Class Diagram skinparam groupInheritance and other relations together bug

### ISSUE THREAD

**Issue by Cavitedev** [plantuml/plantuml#729]
On this code

```
@startuml
skinparam groupInheritance 2

Parent <|-- Child1
Parent <|-- Child2
Composed --* Parent
Aggregated --o Parent
Arrow --> Parent
@enduml
```

![image](https://user-images.githubusercontent.com/52750778/138938900-165520ca-edff-45f8-ab93-ed9a242be050.png)

The point of any kind of arrow should be just next to Parent class. I think the code as it is should be working fine so it looks like bug. Removing the group inheritance solves the issue but both of them should be able to work together I think.

Thank you for your attention in advance.

**Comment by The-Lum** [comment]
Hello @Cavitedev,

FYI, I just add your issue on this page _(in order to keep in mind, for PlantUML team)_:
- http://alphadoc.plantuml.com/doc/markdown/en/class-diagram-issues

Regards.
