### ISSUE TITLE
Using fallback fonts

### ISSUE THREAD

**Issue by jessetan** [plantuml/plantuml#73]
Is it possible to define a font stack like in CSS where multiple font names are given, and the first one that matches an installed font is used?
For example, I might prefer Helvetica, but that is not available on my colleagues Windows or Linux computer.
I would expect something like this to work:
```
skinparam defaultFontName Helvetica, Arial, "Open Sans"
```
Is this not implemented or is there a special syntax?

**Comment by arnaudroques** [comment]
Thanks, this is a good suggestion!
Are you talking about PNG export ? (and not SVG/EPS)

**Comment by jessetan** [comment]
I was thinking about all output formats. In my use case, I have a Git repo with documentation containing uml diagrams that may be rendered by multiple people. Most people will have the required custom font, but not all.

For PNG, it would up to PlantUML to determine the most suitable font.
For SVG, PlantUML could just provide output the entire font stack, since [SVG permits authors to specify multiple fallback fonts](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family)
For EPS rendered to outlines, it would up to PlantUML to determine the most suitable font.
For EPS rendered as text (using `eps:text`), I don't think there is a way to define multiple fonts, so probably the first one should be used. Embedding the font in the diagram would be overkill I think.

**Comment by trothwell** [comment]
For SVG, I'd much prefer an option to embed the font or reference a web font. This would likely be a new feature request though. :)
https://github.com/BTBurke/svg-embed-font

**Comment by hcoona** [comment]
This is especially useful for multi-linguist users. For example,  I'd like to show the diagram in Chinese but somehow there are some components named in English (because we code it in English).

**Comment by arnaudroques** [comment]
This has been finally released in last version V1.2019.13.
See https://forum.plantuml.net/10498/is-there-a-supported-way-to-specify-fall-back-fonts

Tell us if it's not working for you.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @jessetan for the report.
- Thanks PlantUML team for your work.
	
Regards.

**Comment by rben01** [comment]
I'd consider this issue only sort of resolved. When exporting to SVG, PlantUML only includes the single font that it fell back to for elements’ `font-family`. So if you write `skinparam defaultFontName NotARealFont, Helvetica, Arial, "Open Sans"` and then export to SVG, your SVG will contain `font-family="Helvetica"` (assuming Helvetica was installed, which it most likely was), and _won't_ include the whole stack `NotARealFont, Helvetica, Arial, "Open Sans"` in the SVG. This is problematic if you generate and view the SVG on different systems, as fonts present on one might not be present on the other. I think it's important to keep the whole font fallback stack that the user provides in the SVG.
