### ISSUE TITLE
Joining github sponsors program

### ISSUE THREAD

**Issue by berndschatz** [plantuml/plantuml#760]
Our company financially supports third-party Open Source projects which we use in our software,
the employees can suggest their favorite projects.

Unfortunately the sponsorship is (as of now) restricted of projects on github that are joined the GitHub Sponsors program.
(Don't really understand why my company cannot directly sponsors projects, 
and if there are any drawbacks for a project to join this sponsors program.)

Is it possible that the plantuml project is joining this program ?

**Comment by arnaudroques** [comment]
> Is it possible that the plantuml project is joining this program ?

We've just join the GitHub Sponsors program. I'm not sure about what that exactly means but we'll see.
There is some manual approval on github staff side. I don't know how long it can take.
We'll post a message here when this will be complete.

Thanks again for your contributions!

**Comment by arnaudroques** [comment]
https://github.com/sponsors/plantuml has been validated and is now online.
