### ISSUE TITLE
Setting plantuml.include.path using a function call.

### ISSUE THREAD

**Issue by mskyaxl** [plantuml/plantuml#763]
I am not using the regular CLI entry point but rather a java wrapper for plantuml.

I am trying to set the ``plantuml.include.path`` programmatically, via a function call but I saw that this is only taken from the env.
I could not find a function to do that.  

Is there such a function? Have you considered creating one?

**Comment by arnaudroques** [comment]
I am be wrong, but I think you can use [System.setProperty](https://www.tutorialspoint.com/java/lang/system_setproperty.htm).
Tell us if it's not working for you.

**Comment by mskyaxl** [comment]
it works! thanks. I should have known this!
