### ISSUE TITLE
Multiroot Mindmap

### ISSUE THREAD

**Issue by chapterjason** [plantuml/plantuml#773]
While I was planing a presentation with multiple topics, I just thought about the multiple mind maps.
But I get an error which disallow multiple roots.

![image](https://user-images.githubusercontent.com/1337562/141773078-84676de9-1778-4aaf-bd2f-9fe77a8bbe8a.png)

As the result says, here is my idea how to represent multiple roots:

**Input:**
```planuml
@startmindmap
* Root 1
** Foo
** Bar
* Root 2
** Lorem
** Ipsum
@endmindmap
```

**Output:**
![image](https://user-images.githubusercontent.com/1337562/141773529-48d3cb9c-994b-4c43-b348-dc7527791599.png)
![image](https://user-images.githubusercontent.com/1337562/141773587-91857b8c-4258-43f5-8832-62f5b9310831.png)

(Both in one image)

**Comment by The-Lum** [comment]
Hello @chapterjason,

Awaiting a implementation _(by the "PlantUML team" :-))_ to create directly a multi-root diagram, here is a workaround using **sub-diagram** _([see QA-11895](https://forum.plantuml.net/11895))_, as:

```puml
@startuml
label l [
{{mindmap
* Root 1
** Foo
** Bar
}}
{{mindmap
* Root 2
** Lorem
** Ipsum
}}
]
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuSf9J4hDKSXHYEQghixDp4l9JIpWqb88oiylKJ3aqj9ISClF1r5EYKLSjRMOQen0aZxvHQcv88PdGN5fBaXTB9T3QbuAq7m0)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSf9J4hDKSXHYEQghixDp4l9JIpWqb88oiylKJ3aqj9ISClF1r5EYKLSjRMOQen0aZxvHQcv88PdGN5fBaXTB9T3QbuAq7m0)

Enjoy 🥳,
Regards.

**Comment by The-Lum** [comment]
FYI, this new feature is now available from the [V1.2021.15 (30 Nov, 2021)](https://plantuml.com/changes).

## Input
```puml
@startmindmap
* Root 1
** Foo
** Bar
* Root 2
** Lorem
** Ipsum
@endmindmap
```

## Output
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgoStCIybDBE3IKWZApozHCEJIqb9moyy7KKw9HJ1X8n3V9xyeDHV4y2meBitbSaZDIu7g1W00)](http://www.plantuml.com/plantuml/uml/SoWkIImgoStCIybDBE3IKWZApozHCEJIqb9moyy7KKw9HJ1X8n3V9xyeDHV4y2meBitbSaZDIu7g1W00)

**Comment by AbeEtan** [comment]
Is it possible to rotate the diagram to display vertically?
Please advise.
Thank you.

**Comment by The-Lum** [comment]
Hello @AbeEtan and all,

Yes, for that you can use `top to bottom direction` directive like:
```puml
@startmindmap
top to bottom direction
* Root 1
** Foo
** Bar
* Root 2
** Lorem
** Ipsum
@endmindmap
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgoStCIybDBE0goIzGACbNICelASdFLKZ9B4fDBidCp-FIKWZApozHCEJIqb9moyy7KKw9HJ1X8n3V9xyeDHV4y2meBitbSaW5cWWn5G00)](https://www.planttext.com/?text=SoWkIImgoStCIybDBE0goIzGACbNICelASdFLKZ9B4fDBidCp-FIKWZApozHCEJIqb9moyy7KKw9HJ1X8n3V9xyeDHV4y2meBitbSaW5cWWn5G00)

_[FYI: @PlantUML team, @arnaudroques: There is a minor overlapping on this configuration... Minor Issue...]_

Ref.:
- https://github.com/plantuml/plantuml/issues/43#issuecomment-1507479047
_[Thanks to @johny-tee]_

Regards.

**Comment by AbeEtan** [comment]
Hello @The-Lum,

Thank you so much, is it possible to add some margin space between the two such that bar and Root 2 edges don't touch each other?

**Comment by The-Lum** [comment]
Hi @AbeEtan,

As mentioned:
> [FYI: @plantuml team, @arnaudroques: There is a minor overlapping on this configuration... Minor Issue...]

I can open an issue for that.
