### ISSUE TITLE
Very empty in Preview window, without a word.

### ISSUE THREAD

**Issue by Jovons** [plantuml/plantuml#777]
![image](https://user-images.githubusercontent.com/3646400/141939179-9a3e366e-4484-4ac5-a6c8-36ef05021aa6.png)
Very empty in Preview window, without a word.
Win10, v2.16.0

**Comment by The-Lum** [comment]
Hello @Jovons,

Please better ask your question on the [`PlantUML VSCode extension` project](https://github.com/qjebbs/vscode-plantuml/issues).

And see perhaps similar issues here:
- https://github.com/qjebbs/vscode-plantuml/issues/435
- https://github.com/qjebbs/vscode-plantuml/issues/270

_If that can help,_
Regards.

**Comment by Jovons** [comment]
@The-Lum  Thank you, problem solved. There is no Log dropdown menu in my VC, but I installed Java environment and problem is gone.
