### ISSUE TITLE
{abstract} and {static} not handled in class diagram for latex output

### ISSUE THREAD

**Issue by BlueAndi** [plantuml/plantuml#79]
Using PlantUML version 1.2017.18 (Fri Oct 06 18:56:32 CEST 2017) to generate UML class diagrams in latex.

Using e.g.
```
@startuml
class A {
    - {abstract} test() : void
    - {static} m_instance : A
}
@enduml
```

doesn't generate a cursive text for {abstract} or a underlined text for {static}.

**Comment by arnaudroques** [comment]
Any idea on how have cursive text and underlined text in latex ? :-)
I would help!
Thanks...

**Comment by BlueAndi** [comment]
No problem. ;-)

To underline text use `\underline{ ... } ` and put the text inside the braces.
For cursive text use `\textit{ ... }` and put the text as well inside.

**Comment by arnaudroques** [comment]
Ok,
Fixed in last beta (beta18)
http://beta.plantuml.net/plantuml.jar
Thanks for your help!

**Comment by BlueAndi** [comment]
Tested the beta18 successful.

Thanks for the very fast support!
