### ISSUE TITLE
Changing the color of both fork and join states

### ISSUE THREAD

**Issue by philippemerle** [plantuml/plantuml#794]
In following example, both `a` and `b` states are in blue, but both `f` and `j` are still in black:
```
@startuml
state f <<fork>> #green
state a #blue
state b #blue
state j <<join>> #orange
f --> a
f --> b
a --> j
b --> j
@enduml
```

Is there a way to change the color of both fork and join states?

**Comment by philippemerle** [comment]
I tried:
```
@startuml
skinparam state {
  BackGroundColor<<MyState>> blue
  BackGroundColor<<fork>> green
  BackGroundColor<<join>> orange
}
state f <<fork>>
state a <<MyState>>
state b <<MyState>>
state j <<join>>
f --> a
f --> b
a --> j
b --> j
@enduml
```
but `f` and `j`are still in black.

Do I make a mistake? or is it a missing feature?

**Comment by The-Lum** [comment]
Hello @philippemerle,

On `state` diagram, it is not yet manage...

But a possible workaround is to use `ActivityBarColor` [sic], and you must to choose between `green` or `orange`, because it is managed by the same parameter, as:
```puml
@startuml
skinparam state {
  BackGroundColor<<MyState>> blue
}
skinparam ActivityBarColor green

state f <<fork>>
state a <<MyState>>
state b <<MyState>>
state j <<join>>
f --> a
f --> b
a --> j
b --> j
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/RSyz3i8m30NWtQVm1Ng3A2fbO6BY14wReFmqGMw2L27kJYX1C7HwqcVxIUwNJ9pB763nDjw8QSPAMUC340SQ_ObJYTCnXSH2dDVBUoWbgb0qFF-k3cEsTvlNWNXRnYjh7G4-RGQ5C8czb0q8VsrVKplcghbaOmM3NIUHMYgWBHsebhsEK_ta1G00)](http://www.plantuml.com/plantuml/uml/RSyz3i8m30NWtQVm1Ng3A2fbO6BY14wReFmqGMw2L27kJYX1C7HwqcVxIUwNJ9pB763nDjw8QSPAMUC340SQ_ObJYTCnXSH2dDVBUoWbgb0qFF-k3cEsTvlNWNXRnYjh7G4-RGQ5C8czb0q8VsrVKplcghbaOmM3NIUHMYgWBHsebhsEK_ta1G00)

@arnaudroques: On the style improvement, could you add `fork` or `join` as separate parameters 😉...

_If that can help,_
Regards.

**Comment by philippemerle** [comment]
Thank you very much: this should resolve my need. I tried
```plantuml
@startuml
skinparam state {
  BackGroundColor<<MyState>> blue
}
skinparam ActivityBarColor<<fork>> green
skinparam ActivityBarColor<<join>> orange

state f <<fork>>
state a <<MyState>>
state b <<MyState>>
state j <<join>>
f --> a
f --> b
a --> j
b --> j
@enduml
```
and now `f` is in green and `j` in orange:

![](http://www.plantuml.com/plantuml/png/VOzDheCm38JtFeKlm0qGul4MNNNL4pXWKFYnAvDKGbNlthGD4ekggv6-V9cHwpMGXRZCi4vUhcIqO4A1yGw83RNJoJHAzw-pMbcUjylhiQhGpP7XSVZrrmP_ys5hoBBSgqt978nPVegZUacY6id009_z7lU630WF-vcvBsp4lH5wB8eAAQS3UkS8BcVDqgNRdm00)

**Comment by arnaudroques** [comment]
> @arnaudroques: On the style improvement, could you add `fork` or `join` as separate parameters 😉...

With last release, you can have:

```
@startuml
<style>
state {
  BackGroundColor: blue;
}
activityBar {
  .fork {
    BackGroundColor: green;
  }
  .join {
    BackGroundColor: orange;
  }
}
</style>
state f <<fork>>
state a <<MyState>>
state b <<MyState>>
state j <<join>>
f --> a
f --> b
a --> j
b --> j
@enduml
```

The syntax (use of `activityBar`) is a bit weird. We cannot simply use `state` because the default color of those bars is
black, which is different from regular state background color.
Any suggestion to improve this syntax is welcome!

**Comment by StefH** [comment]
Adding a color to `<<sdlreceive>>` does not seem to work?

``` plantuml
@startuml
<style>
activityBar {
  .fork {
    BackGroundColor: green;
  }
  .join {
    BackGroundColor: orange;
  }
  .a {
    BackGroundColor: yellow;
  }
}
state {
  .a {
    BackGroundColor: yellow;
  }
  .sdlreceive {
    BackGroundColor: lightgreen;
  }
}

</style>
state f <<fork>>
state a <<a>>
state b <<a>>
state j <<join>>
state g <<sdlreceive>>
f --> a
f --> b
a --> j
b --> j
b --> g
@enduml
```

Shows:
![image](https://github.com/user-attachments/assets/d67cc1ae-52da-44ce-976c-081a5a047055)
