### ISSUE TITLE
Online service down

### ISSUE THREAD

**Issue by rodrigoprestesmachado** [plantuml/plantuml#797]
Hello all, 

I was using the online service to integrate with GitHub, for example:

http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/rodrigoprestesmachado/pw2/master/docs/topicos/jpa/uml.puml

However, something has changed, is this service still available? if yes, what I have to chance to generate an image of my diagram?

thanks !

**Comment by arnaudroques** [comment]
> However, something has changed, is this service still available? if yes, what I have to chance to generate an image of my diagram?

Sorry about that, we have indeed broken something.
We are going to restore this service in the incoming hours.
In the meantime, your diagram is still available [here](http://www.plantuml.com/plantuml/uml/TT2n2i9030RWFKyHRXIkwEeW1MTTn0U8RMXFsXIQ50JntRqhnCbk_yzz_0UfrMYsPHm0xiepXaF064yOzbMr2tXXLUeOZwWixKhyAKPFvvv4UCZeEIK1hvjJpIH6IHIW6KWLrzKtOCJhCZvoJcqfDvkJT2WqCdpS-dZX_tHFsl-q_xcfZLzMTCtIvXjy0G00).

**Comment by arnaudroques** [comment]
@rodrigoprestesmachado This is fixed now
Thanks for the report
