### ISSUE TITLE
Dashed line is not generated for latex output

### ISSUE THREAD

**Issue by BlueAndi** [plantuml/plantuml#80]
Using PlantUML version 1.2017.18 (Fri Oct 06 18:56:32 CEST 2017) to generate UML class diagrams in latex.

Using e.g.
```
@startuml
class A
class B

A ..> B
@enduml
```

doesn't generate a dashed line. The keyword 'dashed' should be added to the \draw command.

**Comment by arnaudroques** [comment]
Thanks for the report!
It should be fixed in last beta (beta17)
http://beta.plantuml.net/plantuml.jar

**Comment by BlueAndi** [comment]
I checked it with PlantUML version 1.2017.19beta17 and it works. Thanks.
