### ISSUE TITLE
Hide footbox breaks network diagram

### ISSUE THREAD

**Issue by marvids** [plantuml/plantuml#800]
We are using a file with common settings for our diagram (such as skinparams and some other options). This works well for all our diagrams except for network diagrams, where the diagram generation fails on the nwdiag block with a syntax error.

We have narrowed it down to one line in our included files:
`
hide footbox
`

Just having this line seem to break the network diagrams.
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh8J4bLIClFBqdAh-3AAq_9J4nNgEPIKCXBBIdFByfM24ajBW49045mQb5PQX6GMSjLo-MGcfS2r0y0

**Comment by arnaudroques** [comment]
Thanks for the feedback.
This has been fixed [in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and [on the online server](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSh8J4bLIClFBqdAh-3AAq_9J4nNgEPIKCXBBIdFByfM24ajBd7Bh4XD0Oa2GN1gKLbg4P1PorNBvP2Qbm8q1000).

**Comment by marvids** [comment]
That was quick! Works great!
