### ISSUE TITLE
Special characters & and ~ not handled in latex output

### ISSUE THREAD

**Issue by BlueAndi** [plantuml/plantuml#81]
Using PlantUML version 1.2017.18 (Fri Oct 06 18:56:32 CEST 2017) to generate UML class diagrams in latex.

Example UML diagram:
@startuml
class A {
    + A()
    + ~A()
    + A(in a : const A&)
}
@enduml

The ~ should be converted to` \~{}`, the & should be converted to` \&` to be handled correct in latex.

**Comment by arnaudroques** [comment]
Thanks for the report!
The ~ issue should be fixed in last beta (beta17)
http://beta.plantuml.net/plantuml.jar

About & it seems that \& is needed for us.
See https://www.overleaf.com/read/myvpxjrpcndr
Any thought ?

**Comment by BlueAndi** [comment]
I checked it with the PlantUML version 1.2017.19beta17 and both is looking good for me.

Regarding the & in my previous comment, the backslash was not shown, because I forgot to mark them as code. :-)

Perfect! Thanks.
