### ISSUE TITLE
Graph direction is not working

### ISSUE THREAD

**Issue by MarioCuljak** [plantuml/plantuml#814]
Direction is not working in v1.2021.11 version.
`top to bottom direction`

**Comment by arnaudroques** [comment]
Could you post some non working example ?
[This](http://www.plantuml.com/plantuml/uml/LSYn3O0W40NG_gQuKWeA6C2mX0CWN442dE4--vlO-SgN37bXZqvewC8GGo3emr2-5T31jIqfQ3ffcwp0tfzyN2Obct1mtyR_HaT9PjsZlm00) and [this](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIh9BCb9LIX9BIunuif9JIjHACbNACfCpoXHICaiIaqkoSpFuoejJYqoLD3LjLFG22rEJKuiJbKmr0IB6g6A6cboEQJcfG3D1G00) are working for us.
Thanks!

**Comment by MarioCuljak** [comment]
> Could you post some non working example ? [This](http://www.plantuml.com/plantuml/uml/LSYn3O0W40NG_gQuKWeA6C2mX0CWN442dE4--vlO-SgN37bXZqvewC8GGo3emr2-5T31jIqfQ3ffcwp0tfzyN2Obct1mtyR_HaT9PjsZlm00) and [this](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIh9BCb9LIX9BIunuif9JIjHACbNACfCpoXHICaiIaqkoSpFuoejJYqoLD3LjLFG22rEJKuiJbKmr0IB6g6A6cboEQJcfG3D1G00) are working for us. Thanks!

Yea, it was on my side. I found what was the problem. Sorry to bother you.
