### ISSUE TITLE
src is using a few things from java 1.8 

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml#817]
We saw java version compatibility problems in #809 but they were only apparent when building with java 8.

I've been trying the maven-compiler-plugin [release](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release) option to make this sort of problem visible when building with newer java versions.

Added this to `pom.xml`:

```
<profile>
  <id>ensure-runnable-on-java-7</id>  <!-- See https://stackoverflow.com/a/65655542/1848731 -->
  <activation>
    <jdk>[9,)</jdk>
  </activation>
  <properties>
    <maven.compiler.release>7</maven.compiler.release>
    <maven.compiler.testRelease>8</maven.compiler.testRelease>
  </properties>
</profile>
```

And used java 17 to run `mvn compile` which reports some problems of the current code using 1.8 things:

* A few files use `java.time` & `java.time.format` packages
* `net.sourceforge.plantuml.elk.proxy.Reflect` uses `getParameters()`
* `smetana.core.debug.Purify` uses `getDeclaredAnnotation()`

Have not looked closely, some looks to be debugging code so probably will not affect anyone running on java 7 but perhaps some is a problem?

**Comment by arnaudroques** [comment]
> Have not looked closely, some looks to be debugging code so probably will not affect anyone running on java 7 but perhaps some is a problem?

[elk](https://plantuml.com/elk) and [smetana](https://plantuml.com/smetana02) are used with some specific settings, so it's probably not an issue (we could ask to user to avoid Java 7 for this).

About java.time usage, it seems to be used only for Gantt diagram. Here again, we could impose Java 8 here.

Since Java 7 adoption is probably very weak now, I think we can ignore this.

Thanks for pointing out this anyway!

**Comment by matthew16550** [comment]
Shall I add the `release` option to `pom.xml` set to `8` for src & test ?
That should catch the sort of problem from #809 but will not bother us about the 3 points I listed above.

**Comment by arnaudroques** [comment]
> Shall I add the `release` option to `pom.xml` set to `8` for src & test ?

Doing so will not prevent people using Java 7 to run PlantUML ?

**Comment by matthew16550** [comment]
Upon further reading, `--release` seems to prevent use of `--add-exports` which would be annoying for #698 so now I don't want to do it!

Though I'm fairly sure it would not break 7 for us.

**Comment by arnaudroques** [comment]
So let's go!
