### ISSUE TITLE
Sequence-group text styles not behaving correctly

### ISSUE THREAD

**Issue by codemedic** [plantuml/plantuml#821]
Combination of `SequenceGroupFontStyle Normal` and `SequenceGroupHeaderFontStyle Bold` does not create the expected effect. For example in the diagram below I would expect group text elements to be bold while the individual alternatives' headers to be normal.

```
@startuml
skinparam {
    SequenceGroupFontStyle Normal
    SequenceGroupHeaderFontStyle Bold
}

A->B: Hi
alt morning
  A->B: good morning
else afternoon
  A->B: good afternoon
end
@enduml

```

![image](https://user-images.githubusercontent.com/691011/144825994-44b73d25-ee19-41c9-aa2b-6f5f5c3aabcb.png)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed:
>[![](https://www.planttext.com/api/plantuml/svg/POv12i9034NtEKKku0LSIEr2ktBJ4mGdbc8cgPdCeeXtTq2mY7_n5u_tuNSboADcWNAVTI6dZ4_0bf4VbVNAPxUwd4nZZ5KOB-QPvDyOc1BxvlKc2Lu0nzsXt-Cm0qbWDjTPfxR-uCaiVI5BOQHRiAkP_ZeRPatGjMgNtm00)](https://www.planttext.com/?text=POv12i9034NtEKKku0LSIEr2ktBJ4mGdbc8cgPdCeeXtTq2mY7_n5u_tuNSboADcWNAVTI6dZ4_0bf4VbVNAPxUwd4nZZ5KOB-QPvDyOc1BxvlKc2Lu0nzsXt-Cm0qbWDjTPfxR-uCaiVI5BOQHRiAkP_ZeRPatGjMgNtm00)

- Thanks @codemedic for the report.
- Thanks PlantUML team for your work.

Regards.
