### ISSUE TITLE
Gantt: Option to hide resource usage?

### ISSUE THREAD

**Issue by darrenkenny** [plantuml/plantuml#825]
There is the ability to hide the footbox, but there doesn't appear to be any way to hide the resource usage information.

Would it be possible to add an option like `hide resourceusage` or similar?

**Comment by The-Lum** [comment]
Hello @darrenkenny,

FYI, _with last [snapshot (1.2021.17beta7)](https://github.com/plantuml/plantuml/releases/tag/snapshot)_, we can now use `hide ressources footbox`, as:

```puml
@startgantt
hide ressources footbox
[Task1] on {Alice} lasts 10 days
[Task2] on {Bob:50%} lasts 2 days
then [Task3] on {Alice:25%} lasts 1 days
@endgantt
```
>[![](https://www.plantuml.com/plantuml/svg/JSynYuD040NWtbynZQ2Dk7k8OENT7xWcNKonwqwYH7PXPfI4aF-Uw2OXtIi-tkErB8RaPBn8CemEWP0vpDGZmp44iU6Ix7U6p-e0mSFjTnfxlCDaM1XK2SvSEG8TmL-mJLMcRwAZa04zREpdgwVHrGUg2DTD9EZylsMa1TrJDm2W2brgLQZQefYwyra_4w4NM91uN4twIbcU9orwjtrw0000)](https://www.plantuml.com/plantuml/uml/JSynYuD040NWtbynZQ2Dk7k8OENT7xWcNKonwqwYH7PXPfI4aF-Uw2OXtIi-tkErB8RaPBn8CemEWP0vpDGZmp44iU6Ix7U6p-e0mSFjTnfxlCDaM1XK2SvSEG8TmL-mJLMcRwAZa04zREpdgwVHrGUg2DTD9EZylsMa1TrJDm2W2brgLQZQefYwyra_4w4NM91uN4twIbcU9orwjtrw0000)

See also change request here: 
- [QA-15211](https://forum.plantuml.net/15211/question-related-working-with-resources-feature-gantt-charts?show=15229#c15229)

👍 _Thanks to PlantUML team,_
Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered and fixed: see `hide ressources footbox` and `hide ressources names`.
- Thanks @darrenkenny for the report.
- Thanks PlantUML team for your work.

Regards.
