### ISSUE TITLE
TXT output support for PicoWeb

### ISSUE THREAD

**Issue by fabiospampinato** [plantuml/plantuml#833]
It'd be nice to have support for the txt and utxt formats in PicoWeb mode. I'm currently using those so I can't quite switch to the built-in PicoWeb server.

**Comment by arnaudroques** [comment]
This is a good suggestion.
It should be working [with last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Tell us if it's not working for you.
Thanks,

**Comment by fabiospampinato** [comment]
That seems to work for me, thank you!
