### ISSUE TITLE
There is a problem with svg rendering latex

### ISSUE THREAD

**Issue by holmofy** [plantuml/plantuml#834]
```puml
@startmindmap
* 排列组合问题
** 基础概念
***_ <latex>C_{n-1}^{m-1}</latex>
***_ 环形排列
****_ n个主体环形排列有<latex>A_{n-1}^{n-1}</latex>种可能
@endmindmap
```

png rendering no problem

![image](https://user-images.githubusercontent.com/19494806/146759745-033761b1-a638-4726-97b5-05bc552bf97a.png)

svg render failed

![image](https://user-images.githubusercontent.com/19494806/146759916-aafd7635-f475-4b1d-9fc6-4c8a5ee3bd77.png)

svg url : http://www.plantuml.com/plantuml/svg/SoWkIImgoStCIybDBE3IKdZMD-bfn_JdkrkUJkXuENtToqKpkBIq59xEt_LyOSEpPKrFzsy5yhNY5Mno4ajIA-oSuwlpT0rhuwfpWQIDFaGGek9vt_gdUnT1p0EAW8JodknOzMJ7xYTx9oDBFflJ2JND4MPQ7f9fpvVtFkrV_w9vBvT3QbuArAK0

**Comment by The-Lum** [comment]
Hello all,
See similar request here:
- [QA-13562: Allow math or latex on SVG output](https://forum.plantuml.net/13562/allow-math-or-latex-on-svg-output?show=13562#q13562)

Regards.

**Comment by holmofy** [comment]
> Hello all, See similar request here:
> 
> * [QA-13562: Allow math or latex on SVG output](https://forum.plantuml.net/13562/allow-math-or-latex-on-svg-output?show=13562#q13562)
> 
> Regards.

thank you
