### ISSUE TITLE
Feature request : titles in timing diagrams

### ISSUE THREAD

**Issue by Lucas-C** [plantuml/plantuml#84]
Hi.

Could you please add support for titles in timing diagrams ?

There are some creations I recently made with this feature:

![partnercall_ok](https://user-images.githubusercontent.com/925560/32851818-5dc27f62-ca36-11e7-9e9c-8be9eb7c918d.png)
![partnercall_fallback](https://user-images.githubusercontent.com/925560/32851817-5da5870e-ca36-11e7-8483-34f142d65b3f.png)
![partnercall_timeout](https://user-images.githubusercontent.com/925560/32851819-5dd6d8f4-ca36-11e7-9ef1-018f3f0674c0.png)

**Comment by arnaudroques** [comment]
There are some lag in the documentation...
With last version, you can have:
```
@startuml
Title this is my title
header: some header
footer: some footer
legend
Some legend
end legend
caption some caption

robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU is Waiting
WB is Processing

@300
WB is Waiting
@enduml
```

http://www.plantuml.com/plantuml/uml/JL3D2i8m3BxdAO9FCF7cgVJcJT3HSzV5hR0jqcI8RszBjo4ayFq5Fc94VT9rdk0PTIBKCGhccR-eHO2HV4_fYi8pOINmOjP3gmGc6cZfuL6a3UVTOV1lZRpKYuq09EvMKJmvwj0c_WYb4tf1Po7m4g9GzTh3Q05C0wuj5MzzhkVi0S6SczrpFcfSXis-9muaKWGmbnAo_o6J6-OF_000

Is this what you are expecting ?

**Comment by Lucas-C** [comment]
Yes, thank you !

**Comment by arnaudroques** [comment]
Btw, we are setting up a collaborative way of updating the documentation.
Your diagrams are nice, if you can add them to http://wiki.plantuml.net/site/timing-diagram and create a paragraph about title, it would be very useful for other users.
Thanks for your contribution!

**Comment by Lucas-C** [comment]
Done :)

**Comment by nakic** [comment]
@Lucas-C There's something wrong with the [timing-diagram](http://wiki.plantuml.net/site/timing-diagram) page. Can anyone do anything about it?
