### ISSUE TITLE
new doc page "layout"

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#840]
@arnaudroques Thanks for the wonderful community doc editing system! This is the only project I know of that allows online editing of its documentation, in a choice of  wiki syntaxes :-)

However, afaik I can't make a new page.

I think we need a new page "layout" to collect info on all layout related options, alternative layout engines, and advice:
- **Layout** section of #261 that lists about 15 options
- Choice of Class/Object/Deployment diagram layout engines, with some comparison between them (and what is the limitation of each)
  - https://plantuml.com/graphviz-dot
  - https://plantuml.com/smetana02
  - https://plantuml.com/vizjs
  - https://plantuml.com/elk
- Choice of Sequence diagram layout engines: `puma` vs `teoz`, with links to:
  - http://plantuml.com/teoz
  - http://forum.plantuml.net/tag/teoz
  - http://wiki.plantuml.net/site/sequence-diagram#anchors_and_duration
- Advice:
  - [PlantUML GraphViz Layout](https://isgb.otago.ac.nz/infosci/mark.george/Wiki/wiki/PlantUML%20GraphViz%20Layout) by Mark George at University of Otago

**Comment by arnaudroques** [comment]
> However, afaik I can't make a new page.

Actually, you can, but it's not so obivous.
Just go to http://alphadoc.plantuml.com/doc/markdown/en/anything_you_want.
For example: http://alphadoc.plantuml.com/doc/markdown/en/layout

> I think we need a new page "layout" to collect info on all layout related options, alternative layout engines, and advice:

That's a great idea. As you know, the documentation is not perfect...
Thanks for your help!

**Comment by The-Lum** [comment]
Hi @VladimirAlexiev 

FYI, we just create this entry:
- http://alphadoc.plantuml.com/doc/markdown/en/index#l5po19ebyibum0pbokms

_In order to improve doc..._
Regards,
Th.

**Comment by VladimirAlexiev** [comment]
@arnaudroques @The-Lum updated http://alphadoc.plantuml.com/doc/markdown/en/index#l5po19ebyibum0pbokms

**Comment by The-Lum** [comment]
Hi @VladimirAlexiev,

Thanks for your contribution.

@arnaudroques  divided your contribution between:
- http://alphadoc.plantuml.com/doc/markdown/en/index#l5po19ebyibum0pbokms
- https://plantuml.com/layout-engines

_Thanks a lot, 👍 
Regards,_
Th.
