### ISSUE TITLE
Multiline backward statements in Activity Diagram

### ISSUE THREAD

**Issue by dchirgwin** [plantuml/plantuml#855]
Maybe a bug, maybe a feature request, or maybe I'm missing something - you decide!

I can write a multiline statement like this:
```
start
:single line statement works fine;
:multiline
statement also works fine;
end
```

However, it seems that multiline statements are not supported in the backward path of a repeat loop:
```
start
repeat
  :Do something;
  backward:single line statement works fine;
repeat while (you want to)
:Just a gap between the repeat loops;
repeat
  :Do something;
  backward: multiline
  statement throws a syntax error;
repeat while (you want to)
end
```

Also, there doesn't appear to be a way to have multiple statements in the backward path (which would have been a good workaround):
```
start
repeat
  :Do something;
  backward: first statement is overridden;
  backward: second statement replaces first statement;
repeat while (you want to)
end
```

**Comment by arnaudroques** [comment]
Thanks for the report.
[Multilines statements](https://www.plantuml.com/plantuml/uml/VP0nJWGn34NxdEANK48vqsn1nIsyhDb4ayGZsr6OssFG5510OrbF_rjFlfYJ-cWrVIz9UMVo12ml0fF6dak_Fwr1hlIsJTBROa4gevREY9Ppu-wOeflXFU1wNi7C9N8FXmnCYeZBOrfUXpa8TzfnPP_C7PuPPwMAxBR-eV7yImDjL2zV5Wa_F3ohJ0F1Zkxq0LOL_LU9-orTOiGNFW40) are now possible [with last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Is this what you were expecting?

Multiple statements in the backward path is another story so we keep it for latter.

**Comment by dchirgwin** [comment]
That's brilliant - thank you so much. Exactly what I needed.
