### ISSUE TITLE
Let people choose between portrait and landscape layout

### ISSUE THREAD

**Issue by DoctorSclero** [plantuml/plantuml#860]
In some projects, landscape layout may be better, for example in a PowerPoint presentation where the slides are always landscape by default.

**Comment by The-Lum** [comment]
Hello @DoctorSclero,

Perhaps, for that, you can use: `left to right direction`.

Compare:
### - Normal layout (portrait)
```puml
@startuml
title "Normal layout (portrait)"
[a1] --> [b]
[a2] --> [b]
[f] --> [g]
[b] --> [c]
[c] --> [d]
[g] --> [d]
@enduml
```
>[![](https://plantuml.io/plantuml/svg/SoWkIImgAStDuIh9BCb9LL3ooo_AJSnHo4cip2yjKT0eo2ygAKhCBD5KuefED8nLqDMrKuXEYWLoZ90uQL1sEf2T16Kd0zd9K7OAa9sEO3kavgK0hGG0)](https://plantuml.io/plantuml/uml/SoWkIImgAStDuIh9BCb9LL3ooo_AJSnHo4cip2yjKT0eo2ygAKhCBD5KuefED8nLqDMrKuXEYWLoZ90uQL1sEf2T16Kd0zd9K7OAa9sEO3kavgK0hGG0)

### - Layout with `left to right direction` (landscape)
```puml
@startuml
left to right direction
title "With left to right direction"
[a1] --> [b]
[a2] --> [b]
[f] --> [g]
[b] --> [c]
[c] --> [d]
[g] --> [d]
@enduml
```
>[![](https://plantuml.io/plantuml/svg/SoWkIImgAStDuSf9JIjHACbNACfCpoXHICaiIaqkoSpFuoh9BCb9LL0Apop9KC2XHeahEj4mLa5NrquXEYaMo352ugH1sUb0TXAKdGna9qFPAK1sEeBja9gN0dGE0000)](https://plantuml.io/plantuml/uml/SoWkIImgAStDuSf9JIjHACbNACfCpoXHICaiIaqkoSpFuoh9BCb9LL0Apop9KC2XHeahEj4mLa5NrquXEYaMo352ugH1sUb0TXAKdGna9qFPAK1sEeBja9gN0dGE0000)

---

See also `left to right direction` on the docs here:
- https://plantuml.com/class-diagram
- https://plantuml.com/use-case-diagram
- https://plantuml.com/component-diagram

_If that can help,_
Regards.
