### ISSUE TITLE
Generate image with invalid code consumes a lot of memory

### ISSUE THREAD

**Issue by swiftech** [plantuml/plantuml#862]
I wrote following code to test: 

```

public class PlantUmlTest {
    static String code = """
            @startuml
            Alice->Alice: This is a signal to self.\\nIt also demonstrates\\nmultiline \\ntext
            @enduml
            """;

    static String codeWithError = """
            @startuml
            Alice->Alice: This is a signal to self.\\nIt also demonstrates\\nmultiline \\ntext
            x
            @enduml
            """;

    public static void main(String[] args) {
        try {
            while (true) {
                int read = System.in.read();
                if ('1' == read) {
                    generate(code);
                }
                else if ('2' == read) {
                    generate(codeWithError);
                }
                else if ('0' == read) {
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void generate(String text) {
        System.out.println("Generate: \n" + text);
        SourceStringReader reader = new SourceStringReader(text);
        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            DiagramDescription diagramDescription = reader.outputImage(os, 0);
            System.out.println(diagramDescription);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

After the program start, I press 1, which means generate image with compliant plantuml code, the memory consumption is normal:

<img width="700" alt="Screen Shot 2022-01-15 at 4 42 30 PM" src="https://user-images.githubusercontent.com/3277107/149616030-245f73ba-c8e7-419e-a709-f1537e7e0484.png">

but instead if I press 2, which means generate image with invalid plantuml code, the memory consumption increased more than 150MB instantly, and  never be recycled:

<img width="710" alt="Screen Shot 2022-01-14 at 10 25 19 PM" src="https://user-images.githubusercontent.com/3277107/149616036-577e0e5e-0cd0-4f88-abf5-0ecb3f5b9705.png">

It seems  memory leak or something, please check that up. 
or provides an API that check the syntax before actually generating image is useful.

**Comment by swiftech** [comment]
environment:

MacOS Big Sur 11.6.2
JVM: Java HotSpot(TM) 64-Bit Server VM (17.0.1+12-LTS-39, mixed mode, sharing)
Java: version 17.0.1, vendor Oracle Corporation
PlantUML: 1.2022.0

**Comment by arnaudroques** [comment]
Thanks for the feedback and sorry for the delay, this should be [fixed in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).
Tell us if it's not working for you!

**Comment by arnaudroques** [comment]
Yes, it should.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @swiftech for the report.
- Thanks PlantUML team for your work.
	
Regards.
