### ISSUE TITLE
skinparam Dpi causes exception

### ISSUE THREAD

**Issue by patrickp-at-work** [plantuml/plantuml#867]
I had originally reported this bug [over here](https://github.com/esteinberg/plantuml4idea/issues/343).
However, it turned out that the reported exception originates from PlantUML / GraphViz and is reproducible without the intelliJ plugin.
[See a minimal example on PlantUML online server](https://www.plantuml.com/plantuml/uml/RSqn3i8m38NXtQVmnbJQkGDg4IVW1cvgKOl42R5pVr9cvlSz_OivLMyfWhr52rLA-2Y2qmINmxtOF8ubafxa6d8QZJ-DDV2m2xsw1g3cMLlQk0AiKGBZSCDxtcPScn-iBe5SikBpl9f3tt3eveV_A2jPZM5XtNlr2m00).

**Comment by arnaudroques** [comment]
Thanks for the report.
This is fixed in last snapshot https://github.com/plantuml/plantuml/releases/tag/snapshot and on the online server.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @patrickp-at-work for the report.
- Thanks PlantUML team for your work.
	
Regards.
