### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [plantuml/plantuml#870]
Hey there!

I belong to an open source security research community, and a member (@b1nslashsh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by arnaudroques** [comment]
Done (https://github.com/plantuml/plantuml/blob/master/SECURITY.md)
Thanks !

**Comment by mfhepp** [comment]
@JamieSlome Can you disclose if the issue has been addressed in the meantime?

**Comment by JamieSlome** [comment]
@mfhepp - all of the issues have either been addressed by the maintainer(s) or are currently being addressed 👍

**Comment by mfhepp** [comment]
Thanks! Maybe the issue can be closed then?
