### ISSUE TITLE
Color state diagram "choice"

### ISSUE THREAD

**Issue by xeruf** [plantuml/plantuml#880]
Reading through https://plantuml.com/state-diagram there seems to be no way to style a "choice"-element, i.e. change background and border color?

I had assumed `skinparam state` would then apply to it as well, but it doesn't...

**Comment by The-Lum** [comment]
Hello @xeruf,

For that you can use **`style`** as:
```puml
@startuml
<style>
  diamond {
    BackgroundColor #palegreen
    LineColor #green
    LineThickness 2.5
}
</style>
state state1
state state2 
state choice1 <<choice>>
state end3    <<end>>

state1  --> choice1 : 1
choice1 --> state2  : 2
choice1 --> end3    : 3
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/LOqnYiCm44LxdUB3rjv5DjiimfXDcp8N4D9W2yjIaEGYXDmzWws4k1dUVv-P6NBHgQoB5ogNcwTU0DRf9GQBEpFmhyqyfhW6Uue-9dnTjQSn4OMjFhj0jJZAo-JC72XdjD-_uY7KJtt07mjXc_8pjAZ9JD4Pab1gf_wrGy5s0BXWOhjh2JHD_zxwWnILDrzlisyFlXvZtuc1mxhu9m00)](http://www.plantuml.com/plantuml/uml/LOqnYiCm44LxdUB3rjv5DjiimfXDcp8N4D9W2yjIaEGYXDmzWws4k1dUVv-P6NBHgQoB5ogNcwTU0DRf9GQBEpFmhyqyfhW6Uue-9dnTjQSn4OMjFhj0jJZAo-JC72XdjD-_uY7KJtt07mjXc_8pjAZ9JD4Pab1gf_wrGy5s0BXWOhjh2JHD_zxwWnILDrzlisyFlXvZtuc1mxhu9m00)


_If that can help,_
Regards.

**Comment by xeruf** [comment]
Thank you very much! Please add that to the documentation :)

Though I am a little confused that there are html-like `<style>` blocks in addition to `skinparam` - is there any system in that? They seem to overlap in some places as well.

**Comment by arnaudroques** [comment]
> Though I am a little confused that there are html-like `<style>` blocks in addition to `skinparam` - is there any system in that? They seem to overlap in some places as well.

Yes, we are **very** slowly moving from `skinparam`  to  `<style>` but right now, not everything is possible through `<style>` so that's why `skinparam`  is still there and that they overlap.

In some far future,  `skinparam`  will be deprecated (although we will still support it) and users will be encouraged to use only `<style>`. But right now, this is not ready :-)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now answered.
- Thanks @xeruf for the report.
- Thanks PlantUML team for your work.


Regards.
