### ISSUE TITLE
how to make a graph symmetrical

### ISSUE THREAD

**Issue by holmofy** [plantuml/plantuml#883]
```startuml
@startuml
skinparam componentStyle rectangle

together {
  [所有A都是B]
  [有的A是B]
  [a是B]
}

together {
  [所有A都不是B]
  [有的A不是B]
  [a不是B]
}

[所有A都是B] .right. [所有A都不是B]:反对
[所有A都是B] -- (矛盾)
(矛盾) -- [有的A不是B]
[所有A都不是B] -- (矛盾)
(矛盾) -- [有的A是B]
[有的A是B] .right. [有的A不是B]:下反对
[所有A都是B] --> [a是B]:从属
[a是B] --> [有的A是B]:从属
[所有A都是B] --> [有的A是B]:从属
[所有A都不是B] --> [有的A不是B]:从属
[所有A都不是B] --> [a不是B]:从属
[a不是B] --> [有的A不是B]:从属
@enduml
```

![image](https://user-images.githubusercontent.com/19494806/151226613-64660641-fe60-43e2-81e6-93e2959bc4fc.png)

How to make this square outside the line. Please save my obsessive-compulsive disorder :)

**Comment by The-Lum** [comment]
Hello @holmofy,

_That is not your goal, but..._
A possible workaround is to change the `together group` as:
```puml
@startuml
skinparam componentStyle rectangle

together {
  [a是B]
  (矛盾)
  [a不是B]
}

[所有A都是B] .right. [所有A都不是B]:反对
[所有A都是B] -- (矛盾)
(矛盾) -- [有的A不是B]
[所有A都不是B] -- (矛盾)
(矛盾) -- [有的A是B]
[有的A是B] .right. [有的A不是B]:下反对
[所有A都是B] --> [a是B]:从属
[a是B] --> [有的A是B]:从属
[所有A都是B] --> [有的A是B]:从属
[所有A都不是B] --> [有的A不是B]:从属
[所有A都不是B] --> [a不是B]:从属
[a不是B] --> [有的A不是B]:从属
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuIhEpimhI2nAp5L8piyjoCzBpIi9BgdCILKeIaqkISnBpqdbuYh9JqyjoKWjKgZcKb28JdmsOxrJB92byNp-xEUpzsc21P_iw8M8rt9nHJ_hR7WsfzFnPVDUi9Y2Nb5cUaQ9dWAI14ozrTF-tgVhTsBgqTL5M01ZW0IZWQgUpsfnX5k8QIXXpL2T21x2aHWMM3tPqOtRaNP0lqELxUvxkd4U5v0Bbq9OW520OWXXbPW-iqDt8M7rYHWg4uaoq24rBmMOI000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpimhI2nAp5L8piyjoCzBpIi9BgdCILKeIaqkISnBpqdbuYh9JqyjoKWjKgZcKb28JdmsOxrJB92byNp-xEUpzsc21P_iw8M8rt9nHJ_hR7WsfzFnPVDUi9Y2Nb5cUaQ9dWAI14ozrTF-tgVhTsBgqTL5M01ZW0IZWQgUpsfnX5k8QIXXpL2T21x2aHWMM3tPqOtRaNP0lqELxUvxkd4U5v0Bbq9OW520OWXXbPW-iqDt8M7rYHWg4uaoq24rBmMOI000))

_If that can help,_
Regards.

**Comment by holmofy** [comment]
Thank you. I found a solution, although not perfect. 

```plantuml
@startuml
skinparam componentStyle rectangle

[所有A都是B] . [所有A都不是B]:反对
[所有A都是B] -- (矛盾)
(矛盾) -- [有的A不是B]
[所有A都不是B] -- (矛盾)
(矛盾) -- [有的A是B]
[有的A是B] . [有的A不是B]:下反对
[所有A都是B] --> [a是B]:从属
[a是B] --> [有的A是B]:从属
[所有A都是B] --> [有的A是B]:从属
[所有A都不是B] --> [有的A不是B]:从属
[所有A都不是B] --> [a不是B]:从属
[a不是B] --> [有的A不是B]:从属
[a是B]-[hidden]-(a)
[a不是B]-[hidden]-(b)
hide a
hide b
@enduml
```

![image](https://user-images.githubusercontent.com/19494806/151295726-5e49204f-b31e-40da-99c2-c259d8e24f03.png)
