### ISSUE TITLE
Labels above binary in timing diagram wanted

### ISSUE THREAD

**Issue by innovation-plantation** [plantuml/plantuml#888]
Labels can appear above concise and robust waveforms but not above binary in timing diagrams. 

I'd like to label bits like idle, start, lsb, bit1, bit2,..., stop for example in a serial protocol illustration.
I don't see why the labels capability offered in the other diagrams should be missing for binary.

I've been working around it using robust instead of binary, but there are limitations, for example, the 
signal always starts in the low level.

Could this functionality be added for binary as well?

Test case:

```puml
    @startuml 
    binary  "Binary"  as B
    concise "Concise" as C
    robust  "Robust"  as R

    @0
    B is high: idle
    C is hello: what
    R is state0: init

    @100
    B is low: start
    C is world: who
    R is state1: run
    @enduml 
```

![image](https://user-images.githubusercontent.com/26174810/151749405-8f6f587b-48e8-4c2c-b292-c81eb935680d.png)

**Comment by The-Lum** [comment]
Hi @innovation-plantation,

_[This is an Issue Review]_ 👀

FYI: That is now available since **V1.2022.3** _(March 29, 2022)_.

>[![](https://www.planttext.com/api/plantuml/svg/JOvB3iCW34JtFiM84oHRLb6u0JSW2If8BfQ0AEhjowUBxiQZz-JPIdMvtcy67J6v_07KFe82NC5EfwGp5WzbPb2zDfJbk4jjj1rXqfPeMsX7B0Zn5JJYnPxCk3spQ3p1LRAzQ8-hNngIOctQkln4baTZh9hY8vclBigVjshaEz7cqzMtVm40)](https://www.planttext.com/?text=JOvB3iCW34JtFiM84oHRLb6u0JSW2If8BfQ0AEhjowUBxiQZz-JPIdMvtcy67J6v_07KFe82NC5EfwGp5WzbPb2zDfJbk4jjj1rXqfPeMsX7B0Zn5JJYnPxCk3spQ3p1LRAzQ8-hNngIOctQkln4baTZh9hY8vclBigVjshaEz7cqzMtVm40)

See also similar request:
- https://forum.plantuml.net/15762/annotate-binary-waveforms

_Enjoy,_
Regards,
Th.
