### ISSUE TITLE
Line type ortho leads to EmptySvgException - but also some package names

### ISSUE THREAD

**Issue by de-jcup** [plantuml/plantuml#890]
## Situation
I have rendered a class diagram with plantuml (I tried different versions - also with latest one) on my Linux maschine.
It fails with an `EmptySvgException`. It appeared that changing from line type `ortho` but also renaming a package name lead to correct rendering - so seems to be a bug.

## Example
Here my example - it  fails on multiple plantuml versions.
```plantuml
@startuml
skinparam linetype ortho
package com.mercedesbenz.sechub.domain.scan.product.sereco{
   class SerecoFalsePositiveFinder ##[bold]black {
    ~SerecoFalsePositiveCodeScanStrategy : codeSCanStrategy
  }
  SerecoFalsePositiveFinder *-- SerecoFalsePositiveCodeScanStrategy
   class SerecoFalsePositiveCodeScanStrategy{
    ~SerecoSourceRelevantPartResolver : relevantPartResolver
    {static} -Logger : LOG
  }
  
  SerecoFalsePositiveCodeScanStrategy .[#green]. com.mercedesbenz.sechub.domain.scan.project.FalsePositiveMetaData
  SerecoFalsePositiveCodeScanStrategy .[#green]. com.mercedesbenz.sechub.sereco.metadata.SerecoVulnerability
   class SerecoSourceRelevantPartResolver{
    {static} -Pattern : P

  }
    SerecoFalsePositiveCodeScanStrategy *-- SerecoSourceRelevantPartResolver
  
}

@enduml
```
Then I got
![image](https://user-images.githubusercontent.com/11644753/151818403-d75d0975-8261-4a8d-84d9-1bda2e8ff8c0.png)

## Playing around and found some odd behaviour
I played around and deleted some parts to find out the problem, but... it was a little bit odd: 

1. Dropped `ortho` linetype and it worked. 
2. Renamed "com.daimler" to "com.mercedesbenz" ... and it worked with `ortho` enabled ?!?!?!

### Drop Ortho and it works
When enabling skin parameter line type `ortho`, it does not work. If drop the skin parameter (so it returns to default behaviour) all works fine. So seems to be a problem with line type handling. 

### Changed name of package
I changed all package names from "com.daimler." to "com.mercedesbenz." and it worked with linetype ortho !?!
```plantuml
@startuml
skinparam linetype ortho
package com.mercedesbenz.sechub.domain.scan.product.sereco{
   class SerecoFalsePositiveFinder ##[bold]black {
    ~SerecoFalsePositiveCodeScanStrategy : codeSCanStrategy
  }
  SerecoFalsePositiveFinder *-- SerecoFalsePositiveCodeScanStrategy
   class SerecoFalsePositiveCodeScanStrategy{
    ~SerecoSourceRelevantPartResolver : relevantPartResolver
    {static} -Logger : LOG
  }
  
  SerecoFalsePositiveCodeScanStrategy .[#green]. com.mercedesbenz.sechub.domain.scan.project.FalsePositiveMetaData
  SerecoFalsePositiveCodeScanStrategy .[#green]. com.mercedesbenz.sechub.sereco.metadata.SerecoVulnerability
   class SerecoSourceRelevantPartResolver{
    {static} -Pattern : P

  }
    SerecoFalsePositiveCodeScanStrategy *-- SerecoSourceRelevantPartResolver
  
}

@enduml

```

**Comment by arnaudroques** [comment]
It's working on t[he online server](https://www.plantuml.com/plantuml/uml/hPBFQi904CRl-nG3tWhk0_GaMEp5qc2W5_4msHtYrirkc9q8LkopTqq3Of6GGo6dR_vyNtuxYoJ8qZLUfOCBBJ8su5qWERK4aMKVLOlcW3M1YOrkY0rPIXM5Bvt8xBjAszYW2peP3BhbQ3iZkSHauba1WF6O4fIzi4AVg8Z9YJlIoWLB3BFPjehUxYgVVQ0VWUy7xSjegJGOIc4Kga_m3EOgBMzIdhqe6F5wcizXmkfRx0dDTudBsB6X3NawOf02MJQKeZyIvxZyGEw7pqbGdBd0V1thkkzTlxyEVvE_AJJqTbOpKTZfgG_rIKRqtT8t4dn1mN-p7EuWbmGj2khVjH-T3yHOEU_a7lOemlCVM0MA48TCgr03h4d1XpCODxkIloYre62xnly0).

I think it's related to the GraphViz version 2.43.0
Could you try with another version (2.38.0 or 2.44.0) ?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is answered: with a GraphViz issue.
- Thanks @de-jcup for the report.
- Thanks PlantUML team for your work.
	
Regards.
