### ISSUE TITLE
Can't see what numbers to enter for forum captcha

### ISSUE THREAD

**Issue by aucampia** [plantuml/plantuml#900]
When I try to post something in the forum this is what I see:

![image](https://user-images.githubusercontent.com/4481387/152508784-8b089659-e6d4-42bd-9ebf-0c9a968d163e.png)

I have no idea what numbers to enter there.

**Comment by aucampia** [comment]
i see this in console:

![image](https://user-images.githubusercontent.com/4481387/152510509-3a953a4c-0042-40b3-81ea-0908f1607d45.png)

**Comment by aucampia** [comment]
Using latest chrome

**Comment by The-Lum** [comment]
249....
But with very good eyes.... :-)

**Comment by aucampia** [comment]
Oh wow, I thought it wanted me to enter some completely different numbers that would complete a sequence, apologies.
