### ISSUE TITLE
JSON functions: Get all keys, check if key exists in JSON, default  value in get_variable_value

### ISSUE THREAD

**Issue by tom10271** [plantuml/plantuml#905]
Functions to: 

 - Check if key exist in JSON object

 - Get all keys in JSON object that can loop with foreach

 - get_variable_value with default value if not exist, so that this would work

http://www.plantuml.com/plantuml/uml/hP5FJuD04CNl-occ4uv8OezBD8MBLwFrZn8EKzXQ57ORTj5MmdTtTzk4zTuJC-_zUCmBAsseDqFNiaLKaw6R4VTMQ8L43hZ46F23Ek6ME_kyRqawskgUQwfcRnLj_OADAC_ewzixGepaT3mSVnrk17LkpN2A0_JXSJsZlJOXclz7dvvVPdJu_WdHzQxHy2MEK2kXGIe3uj1e0uq4LokfLAjwdCgOuMdaC6Bclobg5vIxUTCE0YSsCSOfPOkjwWLLEuXiLHyL-QomE0FWtaxSbK0QJXlfr5dNG5Kbj0QZu5ChoQ68vdkIB8PmpSlpswuLNDs69gXjOFhmvSN2YzafRMyXQrkTyKtALdQs__iF

**Comment by The-Lum** [comment]
_Just to traceability_, see exchange here:
- [QA-15423](https://forum.plantuml.net/15423/functions-check-exists-default-value-get_variable_value)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed _(from 2761d1e)_
- Thanks @tom10271  for the report.
- Thanks PlantUML team for your work.

_Ref:_
- [QA-15423](https://forum.plantuml.net/15423/functions-check-exists-default-value-get_variable_value)
- [QA-15360](https://forum.plantuml.net/15360/ideas-for-2-new-json-builtins)
- [`%json_key_exists` builtin function](https://plantuml.com/en/preprocessing-json#f46c01e11a227cd8)
 
Regards.
