### ISSUE TITLE
Prefix inlined dependencies

### ISSUE THREAD

**Issue by SevereOverfl0w** [plantuml/plantuml#91]
As you include your dependencies source code, when using this library with maven there are classpath conflicts. This results in using a version of the code that is unexpected if you wish to use plantuml as a library.

The simple solution here is to sed all references in the project to have the prefix plantuml. Or you could use jarjar as part of the build process https://code.google.com/archive/p/jarjar/#!

**Comment by arnaudroques** [comment]
Thanks for pointing this out.
We have not though about this...
As you have suggested, we are going to modify all external library by adding some prefix (something like ext.plantuml) so that classpath conflicts will be removed.
Regards,

**Comment by thetric** [comment]
In #93 I'm trying to replace the external libs with Maven dependencies which is in my opinion a better approach than merely prefixing as it's easier to update them. 

@SevereOverfl0w what packages are conflicting in your build? Perhaps I can declare them as maven dependencies too

**Comment by SevereOverfl0w** [comment]
Working from memory, it was a Google one.
 Having them as a maven dependency would be great.

I recently learned of the maven shade plugin which can prefix maven dependencies. This is useful for distributing a fat jar on the plantuml website for those not using maven.

On 3 January 2018 22:38:48 GMT+00:00, Dominik Broj <notifications@github.com> wrote:
>In #93 I'm trying to replace the external libs with Maven dependencies
>which is in my opinion a better approach than merely prefixing as it's
>easier to update them. 
>
>@SevereOverfl0w what packages are conflicting in your build? Perhaps I
>can declare them as maven dependencies too
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/plantuml/plantuml/issues/91#issuecomment-355147873

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thetric** [comment]
Ok, in my PR the Google lib zxing is already a maven dependency. The only problem is that a dependency of zxing doesn't work with Java 9 (see my first comment in the PR).

Are you sure that it is still necessary to prefix all external libs in the fat jar? The PR updated zxing to the latest version and should not cause problems

**Comment by SevereOverfl0w** [comment]
I'm guessing a little at how the distributed jars work. Prefixing is only useful if plantuml want to offer a single jar outside of maven.

On 4 January 2018 00:18:22 GMT+00:00, Dominik Broj <notifications@github.com> wrote:
>Ok, in my PR the Google lib zxing is already a maven dependency. The
>only problem is that a dependency of zxing doesn't work with Java 9
>(see my first comment in the PR).
>
>Are you sure that it is still necessary to prefix all external libs in
>the fat jar? The PR updated zxing to the latest version and should not
>cause problems
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/plantuml/plantuml/issues/91#issuecomment-355164934

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arnaudroques** [comment]
In last release (V1.2018.1) we have prefixed some dependencies with "ext.plantuml"
Is this better for you ?

**Comment by SevereOverfl0w** [comment]
This has absolutely resolved my issue. We're now running against the latest on maven. Thank you!

As an aside the maven page is confusing due to the old releases. https://search.maven.org/#search|ga|1|plantuml plantuml shows an old release: 8059 as "latest". It might be worth adjusting the versioning to something like 10000.2018.1 in order to avoid this issue, as it confused me until I clicked through.
