### ISSUE TITLE
Generate SVG without attribute contentScriptType

### ISSUE THREAD

**Issue by ewie** [plantuml/plantuml#918]
It would be great to generate SVG without attribute `contentScriptType` which is always emitted right now:
https://github.com/plantuml/plantuml/blob/4534dc4ee2414d61faa2d3cea856ebb912628e13/src/net/sourceforge/plantuml/svg/SvgGraphics.java#L683

I'm uploading those diagrams to a MediaWiki which rejects SVG files containing this attribute. Right now I'm manually removing it from the generated SVG.

I don't see the necessity to include this attribute at all. My diagrams contain no scripting. At the least, this attribute should be behind a flag.

I assume it's necessary for interactive diagrams. But the flag controlling this is always `false` as far as I can see:
https://github.com/plantuml/plantuml/blob/4534dc4ee2414d61faa2d3cea856ebb912628e13/src/net/sourceforge/plantuml/svg/SvgGraphics.java#L132

**Comment by BBX999** [comment]
Apparently, contentScriptType is also a deprecated attribute:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/contentScriptType

**Comment by arnaudroques** [comment]
Ok, thanks all.
We have [simply removed it](https://github.com/plantuml/plantuml/commit/8015ed12853b5e52c643b78ea218e327604a6d73).
[Last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) should reflect this.

**Comment by ewie** [comment]
Thanks for the swift change.
