### ISSUE TITLE
[mindmap] how to apply style to all of a branch

### ISSUE THREAD

**Issue by hyansuper** [plantuml/plantuml#920]
how can I do something like the following so that b1, b11 and b12 are all in color lightgreen?
```
@startmindmap
<style>
mindmapDiagram {
	b1{
	BackgroundColor lightgreen
	}
}
</style>
+ root
++ b1
+++ b11
+++ b12
++ b2
@endmindmap
```

**Comment by The-Lum** [comment]
Hello @hyansuper,

_It is not yet implemented._
See _Wanted features od Defect_ here:
- [QA-12422](https://forum.plantuml.net/12422/beta-style-improve-descendant-pseudo-selector-on-mindmap)
- https://github.com/plantuml/plantuml/issues/43#issuecomment-588209385

---

But, here is a possible workaround:
```puml
@startmindmap
+ root

<style>
node {
     BackgroundColor lightgreen
}
</style>

++ b1 
+++ b11
+++ b12

'Then goto normal BackgroundColor 
<style>
node {
     BackgroundColor #f1f1f1
}
</style>

++ b2
@endmindmap
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgoStCIybDBE3ILYZApo_Xuh8fBgdCIRNZoijFILMevb800QV4vEpqelpIl1Jd_9py8eMSpFICalIYrDGyhbek6tse3YvjROKaGo09ec2q4N4cAgSPWY26SKPS3gbvAL0t0W00)](http://www.plantuml.com/plantuml/umla/SoWkIImgoStCIybDBE3ILYZApo_Xuh8fBgdCIRNZoijFILMevb800QV4vEpqelpIl1Jd_9py8eMSpFICalIYrDGyhbek6tse3YvjROKaGo09ec2q4N4cAgSPWY26SKPS3gbvAL0t0W00)

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed _(from 2022 Summer)_ with:
```puml
@startmindmap
<style>
mindmapDiagram {
  .lg * {
    BackgroundColor lightgreen
  }
}
</style>
+ root
++ b1 <<lg>>
+++ b11
+++ b12
++ b2
@endmindmap
```
>[![](https://www.planttext.com/api/plantuml/svg/BOt12i8m44Jl-nLxDg2qvr2A-YDh6zRW9YlRU13flpV4d6RU3CpCMo4hAUOrqHlyLhuI9kXyZyH62N-0U1R6KtE8LrfURFh9wqr53INoix25a6kzmmx-qeSScce1v_0neFV2KyqQ3Lt7LeumXthvlpq0)](https://www.planttext.com/?text=BOt12i8m44Jl-nLxDg2qvr2A-YDh6zRW9YlRU13flpV4d6RU3CpCMo4hAUOrqHlyLhuI9kXyZyH62N-0U1R6KtE8LrfURFh9wqr53INoix25a6kzmmx-qeSScce1v_0neFV2KyqQ3Lt7LeumXthvlpq0)


- Thanks @hyansuper for the report.
- Thanks PlantUML team for your work.

Regards.
