### ISSUE TITLE
Preserve element group structure in svg output to allow more intelligent post-processing 

### ISSUE THREAD

**Issue by blipper** [plantuml/plantuml#924]
Currently SVG output loses the grouping structure

@startuml
package Z {
    A->B
    A->C
}
C->D
D->A
E->F
F->B
@enduml

So cluster Z for example has a text 
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/928893/154120325-3ea5ffd5-a238-432f-baeb-80e74af383cb.png">

The primitive elements that make up the cluster Z have no easy way of identifying a connection between them. 

It would make more sense to group them with a g element and give them a unique ID to allow more intelligent post-processing and/or dynamic interaction.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/928893/154120846-294d9621-439e-4a78-a132-e9e8da4d8982.png">

**Comment by blipper** [comment]
PR in #925

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed: with your PR #925.
- Thanks @blipper for the report.
- Thanks PlantUML team for your work.
	
Regards.
