### ISSUE TITLE
`GraphvizVersionFinder` fails to parse version for graphviz 3.0.0

### ISSUE THREAD

**Issue by carlocab** [plantuml/plantuml#940]
Hi there, we're trying to update Homebrew's version of `graphviz` at Homebrew/homebrew-core#95933.

While testing packages that depend on `graphviz`, we encountered a failure in `plantuml`. Trying to run `plantuml -testdot` appears to fail because it is unable to parse the new version scheme.

This failure seems to come from here:

https://github.com/plantuml/plantuml/blob/87d472f1228e8da7f00ccc873030fe2077e9322a/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizVersionFinder.java#L75

We'd greatly appreciate it if a new jar could be published that fixes this.

**Comment by arnaudroques** [comment]
Ok, so we have pushed a new [snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) that should parse 3.0.0.

Having said that, we have never tested PlantUML with Graphviz 3.0 so we have no idea if this will be working. You will tell us :-)

**Comment by cho-m** [comment]
Can you also update these lines:
https://github.com/plantuml/plantuml/blob/d38782814758038df5c52a7f8c20872b853e5b33/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils.java#L198-L203

**Comment by arnaudroques** [comment]
Thanks for your patch.
You can try [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot). It should be fine.

**Comment by chenrui333** [comment]
@arnaudroques actually running into the issue again with [graphviz 4.0.0 ](https://github.com/Homebrew/homebrew-core/pull/102587), can you create another patch? Thanks!

**Comment by arnaudroques** [comment]
Here is [another patch](https://github.com/plantuml/plantuml/commit/26f5b7f1fd5be26389b80b92de70b9f63659476d).
Tell us if [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) is not working.
Thanks

**Comment by chenrui333** [comment]
@arnaudroques The patch works for me, thanks!

**Comment by chenrui333** [comment]
@arnaudroques we ran into the issue again, proposing a more permanent solution with #1164

**Comment by arnaudroques** [comment]
Out of curiosity, which version of GraphViz are you using?
