### ISSUE TITLE
1.2022.2 regression - black backgrounds

### ISSUE THREAD

**Issue by fcorneli** [plantuml/plantuml#947]
The following file `plantuml-1.2022.2-regression.puml` does give a regression on version 1.2022.2. I.e., the package is rendered completely black:
```
@startuml

:User:
package "RBAC Roles" {
    :Admin: --|> :User:
}

@enduml
```
Reproduce via:
```
java -jar plantuml-1.2022.2.jar -DPLANTUML_LIMIT_SIZE=8192 -Djava.awt.headless=true -charset UTF-8 -tlatex plantuml-1.2022.2-regression.puml
pdflatex plantuml-1.2022.2-regression.latex
open plantuml-1.2022.2-regression.pdf
```

**Comment by arnaudroques** [comment]
Sorry for the regression and thanks for the report.
This should be [fixed in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).
Tell us if it does not work for you.
Thanks!

**Comment by fcorneli** [comment]
Tested out the SNAPSHOT, all diagrams show up as expected. New theme looks very slick. Nice work!

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @fcorneli for the report.
- Thanks PlantUML team for your work.
	
Regards.
