### ISSUE TITLE
Plantuml russian docs defaced ?

### ISSUE THREAD

**Issue by Danpiel** [plantuml/plantuml#950]
Hello, I was wandering what features got Plantuml but instread of docs got, seems like, defaced page.

Is it on purpose ?

![Screenshot from 2022-03-10 15-33-20](https://user-images.githubusercontent.com/367141/157674186-2f9a43d8-7046-495f-ab97-26b12b79f936.png)

**Comment by Venthe** [comment]
It looks like it. If this is an action of PlantUML maintainers, I think it would be best to release it as an official statement. If not, a revert should happen ASAP
