### ISSUE TITLE
Gantt chart parses task name for dates

### ISSUE THREAD

**Issue by Venthe** [plantuml/plantuml#956]
Input:
`[name with keywords lasts 10 days] lasts 1 days`

Actual duration: 10 days
Expected duration: 1 day

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed, see example here:
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgIK_CAodXYivBp4rLACyioL38JgqipozAALR8IImkALOmD518IQmiZeLnmJmkXzIy5B1E0000)](https://www.planttext.com/?text=SoWkIImgIK_CAodXYivBp4rLACyioL38JgqipozAALR8IImkALOmD518IQmiZeLnmJmkXzIy5B1E0000)

- Thanks @Venthe for the report.
- Thanks PlantUML team for your work.

Regards.
