### ISSUE TITLE
together or package hides quoted name of a class

### ISSUE THREAD

**Issue by jfudickar** [plantuml/plantuml#958]
When using the together or the package command the quoted name of a class will no longer be shown, only the as part is shown.
Classes which are not in a package/together are shown correct.

Simple Example:
```
@startuml

package "A B" as a_b {
  class a
  class b
}

class "long name b" as b{
}
class "long name a" as a{
}

together cd {
  class c
  class d
}

class "long name c" as c{
}
class "long name d" as d{
}

class "long name e" as e{
}

@enduml

```

**Comment by jfudickar** [comment]
![grafik](https://user-images.githubusercontent.com/3485451/157977220-06f1d058-c8a2-4767-bd18-586ef223ec1b.png)

**Comment by The-Lum** [comment]
A possible workaround is:

```puml
@startuml
package "A B" as a_b {
class "long name b" as b
class "long name a" as a
}

together cd {
class "long name d" as d
class "long name c" as c
}

class "long name e" as e
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/RSv13W8X50FGVK_HS9BHYvZo-S54XZ43hWntr-0IrwzjkhMkix_sWgVieUmC5ru3rQXRv1jMr1f3EMfcrUwC4-CA-hKmW7vaxtS_QUdVH9h9j89DC0oivjCSczVq_Vi1)](http://www.plantuml.com/plantuml/umla/RSv13W8X50FGVK_HS9BHYvZo-S54XZ43hWntr-0IrwzjkhMkix_sWgVieUmC5ru3rQXRv1jMr1f3EMfcrUwC4-CA-hKmW7vaxtS_QUdVH9h9j89DC0oivjCSczVq_Vi1)

_If that can help,_
Regards.

**Comment by jfudickar** [comment]
Yes this helps for the moment.
I'm generating the code, so this can be done !

Thanks a lot.

But i still find it unlogical as it is working now :-)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @jfudickar for the report.
- Thanks PlantUML team for your work.
	
Regards.

**Comment by BenceSzalai** [comment]
> But i still find it unlogical as it is working now :-)

The first declaration of an element defines its alias. From any further declarations of the same element only the properties are merged, but the alias has been already set by the first appearance in the code.

That is fine as it is imho.

What may be an inconsistency is that stereotypes however work the other way around: later declarations override previous ones. This inconsistency may worth an issue on it's own, but generally speaking both approach are fine: first or last taking precedence, doesn't matter which one. But probably should be consistent.
