### ISSUE TITLE
AmazonS3_LARGE seems to be an error in 1.2022.2

### ISSUE THREAD

**Issue by hokorobi** [plantuml/plantuml#960]
```
@startuml
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
AMAZONS3(s3_internal)
AMAZONS3(s3_partner,"Vendor's S3")
s3_internal <- s3_partner
@enduml
```

![reference_27-03-2_AWS-library](https://user-images.githubusercontent.com/99910/158015632-3ee6f1f9-3aa6-45ec-9112-653b0cd0a338.png)

**Comment by arnaudroques** [comment]
It seems to work [with very last beta](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuLBCp4lEAKr9LR19B2_MJyxFpStFiqCJ3Ix9BqfCJzLtp4sioiyBDeOpxBWSVHsZ_Fs2ZJMAZUCpyqfIY_8ISpHHH0k05kMb5kaeXQNcfUGNgHSh11ihQN8XgLUmqLL0AEHo0Ae3kGm0).

Could you try [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and tell us the result?
Thanks!

**Comment by hokorobi** [comment]
Sorry, I pasted the wrong source.

```
@startuml
!include <aws/common>
!include <aws/Storage/AmazonS3/AmazonS3>
!include <aws/Storage/AmazonS3/AmazonS3_LARGE>
skinparam nodeBackgroundColor White
skinparam storage<<**AmazonS3**>> {
	backgroundColor #F9DFDC
}
AMAZONS3(s3_internal,"Default S3")
AMAZONS3(s3_internal2,"S3 as node",node)
AMAZONS3_LARGE(s3_partner,"Large S3")
s3_internal2 <-r- s3_partner
s3_internal <-l- s3_partner
@enduml
```
![reference_27-03-2_AWS-library](https://user-images.githubusercontent.com/99910/158059114-15a76da1-9775-45d8-8d29-ddc15dfbbd30.png)

**Comment by arnaudroques** [comment]
Ok, thanks.
We've just [published a new snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).
It should work.
Tell us if you find other issues!

**Comment by hokorobi** [comment]
Thank you!　Resolved.
