### ISSUE TITLE
1.2022.1 creates coloured UML diagram, 1.2022.2 suddenly grey-scaled ones

### ISSUE THREAD

**Issue by kriegaex** [plantuml/plantuml#969]
I just bumped the dependency in a PlantUML Maven plugin, and now the same UML component diagram which was previously created with colours by default using the Smetana engine, is now rendered in black & white (or rather grey-scale). This is a breaking change. Is there anything I need to do, like set an option, in order to get the same result as with 1.2022.1 and older versions?

![image](https://user-images.githubusercontent.com/1537384/160231170-d37f2b67-05f6-4d24-9f68-cad17662955b.png)

![image](https://user-images.githubusercontent.com/1537384/160231188-492daaa3-94eb-4d40-9108-f9a1ef5e6a38.png)

```
@startuml

!pragma layout smetana

skinparam component {
  BackgroundColor<<Using Aspects>> #EEEEFF
  BorderColor<<Using Aspects>> black
}

node poms {

    component "rootParentPOM"
    component "aspectParentPOM"

    [rootParentPOM] <|.. [aspectParentPOM]
}

node aspect_definition_projects {

    component "validation-api"
    component "validation-aspect"

    [rootParentPOM] <|... [validation-api]
    [rootParentPOM] <|.. [validation-aspect]
    [validation-api] *-- [validation-aspect]
    [validation-aspect] *-- [aspectParentPOM]
}

component "mavenProjectWithAspects"<<Using Aspects>>
[aspectParentPOM] <|.. [mavenProjectWithAspects]

@enduml
```

**Comment by arnaudroques** [comment]
You can add `skin rose` to your diagram.
Result [here](https://www.plantuml.com/plantuml/uml/VP51JiCm44NtFiKGTaZf2QAgWEWEaGrYKKNL49jWQizOjbC90NSdgH5AaoPP-hyyVyziGaGVMsj4E6W2pq69A-UniGW6FxcD4AoAI2XEX4EF5cgsZabHX2y1S8VreV7SahndmxuedeEc1cw3KtKCwpLSFtJVTjkZxANoCzYhwKJYHmXYgS2n3PrU0C3WlimpnnAzebW-FMRZ57lPC3y1kxEVAYY-LolOZTZg_-OKxALwqwIZPjexpn_TqQK-HpHQOa_bw7Is42VjVAM-qxcjMcW_4ITuR82RF5-4H-U9lpIQmQCi7XMLQIOlEhx_hJ2Rh5GaqxJzZA4IOgD8jjRy0W00).
Hope this helps!

**Comment by kriegaex** [comment]
Yes, it does. Thank you so much. 😊
