### ISSUE TITLE
Buggy links in sequence groups

### ISSUE THREAD

**Issue by gwilherm** [plantuml/plantuml#970]
In sequence diagram, links are not well rendered in group labels.
### Code
```
@startuml
group [[link My own label]] [My own label 2]
  Alice -> Bob
end
group [[link]] My own label [My own label 2]
    Alice -> Bob
end
group My own label [[link]] [My own label 2]
  Alice -> Bob
end
@enduml
```
### Render
![](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuU9AByelBL28Zix9pCjMyArKo2_FKyX9J4hDYOrLY4RcAnZ5Sd4wvcGcfohesYauvITnfUQbeEe7Qa7MGRn-56rmmuZIxm0aWHu10000)

**Comment by gwilherm** [comment]
I tried to change the regex from `^(.*?)\\[(.*)\\]$` to `^(.*)\\[(.*)\\]$`
But it changes the behavior that people can rely on for instance to create more labels:
![](https://www.plantuml.com/plantuml/png/SoWkIImgAStDuKeloYyjKF2jLCWlprF8IKnApL68Hk4PnQ896CToAIWuvcGcfohesYauvITnfUQbS3a02Q1v0000)
Becomes:
![image](https://user-images.githubusercontent.com/1017720/160295576-a6b22e2a-2718-4574-8382-25ea0e5e7aaf.png)

That is maybe not suitable

**Comment by gwilherm** [comment]
I found another regex a bit more complex that seems to work:
```
^(.*(?:\[\[.*\]\]).*?|.*?)\[(.*)\]$
```
![image](https://user-images.githubusercontent.com/1017720/160296516-75adc450-6a0f-47e7-be91-e4e4874211dd.png)

I'm opening a pull request.

**Comment by gwilherm** [comment]
Pull request #971

**Comment by gwilherm** [comment]
Pull request #972

**Comment by The-Lum** [comment]
See also, on a similar topic, this defect:
- #635
Regards.

**Comment by gwilherm** [comment]
Thanks !
