### ISSUE TITLE
component-diagram example uses non-working syntax

### ISSUE THREAD

**Issue by Sweepi** [plantuml/plantuml#975]
The example "Skinparam" on https://plantuml.com/component-diagram does not work as intended (the lower one of the 2). The boxes/compents do not have the custom colors set in the code.
I tried some things and observed that "stereotyped" names do not work if they contains spaces. 

I fixed the doc by replacing the spaces with underscores, which make the example work as intended, but the change got declined:
http://alphadoc.plantuml.com/history/asciidoc/en/component-diagram
http://alphadoc.plantuml.com/history/asciidoc/en/component-diagram/3qu1yv5e4bzkl1c44epf

**Comment by The-Lum** [comment]
Yes, it seems there is a bug, with white-space management on stereotype.

See the same example with `style`, as:
```puml
@startuml
<style>
.static lib {
    backgroundColor DarkKhaki
}
.shared lib {
    backgroundColor Green
}
</style>

[AA] <<static lib>>
[BB] <<shared_lib>>
[CC] <<static_lib>>
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuR8fBgdCIRNZqWEAb6GcA-Ha9YbKSoa0GL9YSdPwKNvfNefpVav-aO9BOb6sTqPYTYPNBL1rHc9HQWeUrUv5gQbvG9Ks-b0BkA8T7MCLR6mGzjZPSKKxEO748AR5GyMSdH7ge69S3gbvAK3d0W00)](http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuR8fBgdCIRNZqWEAb6GcA-Ha9YbKSoa0GL9YSdPwKNvfNefpVav-aO9BOb6sTqPYTYPNBL1rHc9HQWeUrUv5gQbvG9Ks-b0BkA8T7MCLR6mGzjZPSKKxEO748AR5GyMSdH7ge69S3gbvAK3d0W00)

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Sweepi for the report.
- Thanks PlantUML team for your work.
	
Regards.
