### ISSUE TITLE
1.2022.2 regression: SVG does not include connections if notes are used

### ISSUE THREAD

**Issue by stephannielsen** [plantuml/plantuml#983]
## Problem

When using `note` elements, the rendered SVGs don't render connections between elements. This happens with plantuml-server versions `>= v1.2022.2`. Before that, SVGs were rendered correctly.

## Reproduce

Use plantuml-server version 1.2022.2 or 1.2022.3, e.g. here the public server: [https://www.plantuml.com/plantuml/uml/](https://www.plantuml.com/plantuml/uml/)

Render this diagram:

```plantuml
@startuml BrokenSVG

class User {
  email: String
  username: String
  password: String
}

note right of User::username {
  This breaks connections
}

class Role {
  email: String
  name: String
}

User -- Role
Role -- Role

@enduml
```

Per default PNG is generated which shows the connections. Select SVG, the lines are not rendered between User and Role.

Remove the `note` element from the diagram and render SVG again -> now the lines are rendered.

## Workaround

Go back to version v1.2022.0 of plantuml-server, check SVG. Lines are rendered correctly.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @stephannielsen  for the report.
- Thanks PlantUML team for your work.
	
Regards.
