### ISSUE TITLE
1.2022.4 defaults to monochrome output 

### ISSUE THREAD

**Issue by mbihoop** [plantuml/plantuml#996]
I've attached the same diagram generated within intellij (plugin uses 1.2022.1) and on command line (plantuml from homebrew is 1.2022.4).

```
@startuml

title show monochrome output

cloud github {
[foo]
[bar]
foo -> bar
}

@enduml
```

```
plantuml -tpng ./demonstrate.mono.component.puml
```

```
plantuml -version
PlantUML version 1.2022.4 (Sat Apr 09 14:29:17 BST 2022)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: GB
 
PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 3.0.0 (20220226.1711)
Installation seems OK. File generation OK
```

![demonstrate mono component-show_monochrome_output](https://user-images.githubusercontent.com/93931851/163384361-37d47811-8443-4e11-a2d5-5ab11c060f58.png)
![demonstrate mono component](https://user-images.githubusercontent.com/93931851/163384364-ed6e6d1d-9758-469d-a58d-9a248787ed86.png)

**Comment by The-Lum** [comment]
Hello @mbihoop,

- What are your problems?

If you want the old behaviour, you can use and add `skin rose` directive.

See also:
- #969
- #946

And the release note:
- https://plantuml.com/news
- https://plantuml.com/changes

Without:

```puml
@startuml

title show monochrome output

cloud github {
[foo]
[bar]
foo -> bar
}

@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/3Soz3O0W40RG_gQu1Lp1i0UXu0U51FWCtCN2vQLxrJDB_1JjZQHAoxmANkuOY6MYPuRAeq8K6pJnNQLeu8_i1JYomKz7ctoSl4qcZxIl7m00)](http://www.plantuml.com/plantuml/uml/3Soz3O0W40RG_gQu1Lp1i0UXu0U51FWCtCN2vQLxrJDB_1JjZQHAoxmANkuOY6MYPuRAeq8K6pJnNQLeu8_i1JYomKz7ctoSl4qcZxIl7m00)

With `skin rose`:
```puml
@startuml
skin rose
title show old colored output

cloud github {
[foo]
[bar]
foo -> bar
}

@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/3Son3S8m40NG_a_n5s05b3sY54biYCNXZtntec1vtBtgBHxxY7mR_DKwXxmYMbYbN_fILdZAD6gXCZuPm6dAmcUBAm_-i3wa3UknZmsJlDqvZQNsCji_)](http://www.plantuml.com/plantuml/uml/3Son3S8m40NG_a_n5s05b3sY54biYCNXZtntec1vtBtgBHxxY7mR_DKwXxmYMbYbN_fILdZAD6gXCZuPm6dAmcUBAm_-i3wa3UknZmsJlDqvZQNsCji_)

_If that can help,_
Regards.

**Comment by mbihoop** [comment]
Much appreciated - I found the list of themes but I couldn't figure out which one to get the old default behavior.
