### ISSUE TITLE
The message is located in the wrong position with its arrow when use most themes

### ISSUE THREAD

**Issue by quinnInChina** [plantuml/plantuml#997]
this is the result when i use lastest version of plantuml server
```
@startuml
!theme united

note "must on_time < off_time" as n1
state waiting {
	state first : **// create_time == update_time //**
	state second : **// create_time != update_time //**
}
waiting : **// now < on_time && is_delete == 0 //**

[*] --> first : <color #3820e7>export</color>

waiting -> working : <color #3820e7>auto</color>
working : **// now >= on_time //**
working : **// && now <= off_time //**
working : **// && is_delete == 0 //**

working -> second : <color #3820e7>modify</color>
note bottom of working: create rule

working -> offline : <color #3820e7>manual</color>
offline : **// now >= off_time //**
offline : **// && is_delete == 0 //**

offline -> second : <color #3820e7>modify</color>

waiting --> deleted : <color #3820e7>delete</color>
deleted : **// is_delete == 1 //**

deleted -> [*]

@enduml
```

will see 
1、the message "auto" far away from its arrow
2、the title "waiting" has wrong color

**Comment by The-Lum** [comment]
Hello @quinnInChina and all,

>1、the message "auto" far away from its arrow

It seems due to the normal location, see without any theme:

>[![](http://www.plantuml.com/plantuml/svg/XP9HIyCm4CUVpQSu9-oXKBhfWpBQikyXCcARIZ39ZJIXYlZTFPhrf1hqBSl-lxlVNNeSW_GXMYCS1WKR6yS0w4v1MmKru33Cnmt84TnUK9fIazH1knVu45VfOj2Ui0CKHLL1vnNTfGfD0_7Syy-gAeg56LM7hiz1rndeKonDBu332MestMv1ZwTU6HNcfhj4YSVY2SgoPS6wGuCURkuURdVglbLlP_IXhkRRLd0F8YRqhtJypSWOa8dl54kr3LlD3ki8cIRrXdURZ-K7ubZPyW9_2bhizV3EYlExFcC8QAdbCjVXid7mqQXLMT8osgbCNUcYD5oNS-lHLqDnvi-XEFRlK9cN8YOLp43f3uOubsnMAlkamXagIz-EE2hNHsk-0000)](http://www.plantuml.com/plantuml/uml/XP9HIyCm4CUVpQSu9-oXKBhfWpBQikyXCcARIZ39ZJIXYlZTFPhrf1hqBSl-lxlVNNeSW_GXMYCS1WKR6yS0w4v1MmKru33Cnmt84TnUK9fIazH1knVu45VfOj2Ui0CKHLL1vnNTfGfD0_7Syy-gAeg56LM7hiz1rndeKonDBu332MestMv1ZwTU6HNcfhj4YSVY2SgoPS6wGuCURkuURdVglbLlP_IXhkRRLd0F8YRqhtJypSWOa8dl54kr3LlD3ki8cIRrXdURZ-K7ubZPyW9_2bhizV3EYlExFcC8QAdbCjVXid7mqQXLMT8osgbCNUcYD5oNS-lHLqDnvi-XEFRlK9cN8YOLp43f3uOubsnMAlkamXagIz-EE2hNHsk-0000)

>2、the title "waiting" has wrong color

A possible workaround (on V1.2022.4--) is to use:

```puml
<style>
title {
  fontcolor white
}
</style>
```

>[![](http://www.plantuml.com/plantuml/svg/ZP91QuD048NFtLynII478PYqXvQWalzHIh1nR9QkEq5diQ7altTmama6ARtf-jwRxyswxRXiEJJEpFY03KBmbh4oMSSdXuLXomxXnm3Kv7bFZbhe3o8nPvEb5v7nn0Zp9dGCv7Ti9IS3gklXSGvb1tvjP9Ae-jAozPyI-H0FQjkARGD9agQmRr7EOaAUGpXM-fgcINBrTBWdNqsPPXEcixaClHeyzP0fwM81jjjLw927eQleCc_9EooNXG9ciVtZy-lJ2byA_3vIorawd1P6PuYZf_OhZhlpb8597JULGXMvKWqCTn8X7T1ptUsqRBgGoeHG5tW7s51bwvCY3lVwGSpKoCXhhyrbuz06XwDOmNBMuqHkwKFfD5Tre-gZKghvkvJA_b_gTbFYYO4JflX1JQeRQCOewuYY6ecLVyTiqLUXSRy0)](http://www.plantuml.com/plantuml/uml/ZP91QuD048NFtLynII478PYqXvQWalzHIh1nR9QkEq5diQ7altTmama6ARtf-jwRxyswxRXiEJJEpFY03KBmbh4oMSSdXuLXomxXnm3Kv7bFZbhe3o8nPvEb5v7nn0Zp9dGCv7Ti9IS3gklXSGvb1tvjP9Ae-jAozPyI-H0FQjkARGD9agQmRr7EOaAUGpXM-fgcINBrTBWdNqsPPXEcixaClHeyzP0fwM81jjjLw927eQleCc_9EooNXG9ciVtZy-lJ2byA_3vIorawd1P6PuYZf_OhZhlpb8597JULGXMvKWqCTn8X7T1ptUsqRBgGoeHG5tW7s51bwvCY3lVwGSpKoCXhhyrbuz06XwDOmNBMuqHkwKFfD5Tre-gZKghvkvJA_b_gTbFYYO4JflX1JQeRQCOewuYY6ecLVyTiqLUXSRy0)

Then:
- Why `State Group Header` use style for `title`?
- And, it seems some issues on theme or on the `GroupHeader` or `State` definition ; compare:

```puml
@startuml
skin debug

state waiting {
	state first : first 
	state second : second 
}
waiting : waiting label

'[*] --> first : export
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuIhEpinJI4bDAatduW8AbgGgb2TcbcJcfIjKSt521D8oYufB5AoWD4oqE3KvFoy5A0nbSDLomNHQmSt8IKnApU7YKe_MYbNGrRM36vLQKP1VLCBba9gN0dG40000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpinJI4bDAatduW8AbgGgb2TcbcJcfIjKSt521D8oYufB5AoWD4oqE3KvFoy5A0nbSDLomNHQmSt8IKnApU7YKe_MYbNGrRM36vLQKP1VLCBba9gN0dG40000)

```puml
@startuml
skin debug

state waiting {
	state first : first 
	state second : second 
}
waiting : waiting label

[*] --> first : export
@enduml
```

>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuIhEpinJI4bDAatduW8AbgGgb2TcbcJcfIjKSt521D8oYufB5AoWD4oqE3KvFoy5A0nbSDLomNHQmSt8IKnApU7YYjQALT3LjOERb5fHa5zKmkMGcfS2T0C0)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIhEpinJI4bDAatduW8AbgGgb2TcbcJcfIjKSt521D8oYufB5AoWD4oqE3KvFoy5A0nbSDLomNHQmSt8IKnApU7YYjQALT3LjOERb5fHa5zKmkMGcfS2T0C0)

_If that can help for debugging... (for PlantUML team)_
Regards.

**Comment by The-Lum** [comment]
Hello @quinnInChina, 

Here is another layout, see:
- https://plantuml.com/elk

With _(and some arrow direction modifications)_, here is the result:

>[![](http://www.plantuml.com/plantuml/svg/bPBHQi8m58QlbwSuEl2YKAhRnOROudkC8PazTS4aHz8Jd8oz-qAg1ofbiBic_R-Jxs-wxLa7ZiwgsIdeWzDWzOKY0zgZcl4dEeJe3MEhL8eombaRDlu0t-fXsEXCw1dMK1HL1Vk0QM_79d5r3V7KohAgYkB6zBWdtqv1imdeHzqElGAUph01yaDciG3JxrgqoFdGvK0fJsazTx5dYIQew_BZ77GFVgNUYdSeoqPQRFPaAS3Zy-lJ4byQ_3fHu4sLTnib8eauKpXcftj6HoOX92NcqDJYaqNl8gbExbUBwtHikdKk_K7Cv19_arnVlp64Q579g3AMZTp5VGr7hUakKcGC9JLhF4vGsaTjXPBSkFwec6J-B2QnVqdBVILc63a13Iy4abps6Ski1Xd9fB7f3r9Rz6rqzXS0)](http://www.plantuml.com/plantuml/uml/bPBHQi8m58QlbwSuEl2YKAhRnOROudkC8PazTS4aHz8Jd8oz-qAg1ofbiBic_R-Jxs-wxLa7ZiwgsIdeWzDWzOKY0zgZcl4dEeJe3MEhL8eombaRDlu0t-fXsEXCw1dMK1HL1Vk0QM_79d5r3V7KohAgYkB6zBWdtqv1imdeHzqElGAUph01yaDciG3JxrgqoFdGvK0fJsazTx5dYIQew_BZ77GFVgNUYdSeoqPQRFPaAS3Zy-lJ4byQ_3fHu4sLTnib8eauKpXcftj6HoOX92NcqDJYaqNl8gbExbUBwtHikdKk_K7Cv19_arnVlp64Q579g3AMZTp5VGr7hUakKcGC9JLhF4vGsaTjXPBSkFwec6J-B2QnVqdBVILc63a13Iy4abps6Ski1Xd9fB7f3r9Rz6rqzXS0)

Regards.

**Comment by quinnInChina** [comment]
> Hello @quinnInChina,
> 
> Here is another layout, see:
> 
> * https://plantuml.com/elk
> 
> With _(and some arrow direction modifications)_, here is the result:
> 
> > [![](https://camo.githubusercontent.com/706f4e2bc0fea7a03f9550d9eade8d5e7471d87e7091d85be7dca4bf3305cdef/687474703a2f2f7777772e706c616e74756d6c2e636f6d2f706c616e74756d6c2f7376672f625042485169386d3538516c62775375456c32594b4168526e4f524f75646b433850617a54533461487a384a64386f7a2d714167316f6662694269635f522d4a78732d77784c61375a69776773496465577a44577a4f4b59307a675a636c346445654a65334d45684c38656f6d626152446c7530742d6658734558437731644d4b31484c31566b30514d5f37396435723356374b6f684167596b42367a42576474717631696d6465487a71456c47415570683031796144636947334a787267716f466447764b30664a73617a5478356459495165775f425a3737474656674e55596453656f715051524650614153335a792d6c4a346279515f3366487534734c546e6962386561754b70586366746a36486f4f5839324e6371444a5961714e6c3867624578625542777448696b644b6b5f4b37437631395f61726e566c703634513537396733414d5a547035564772376855616b4b634743394a4c68463476477361546a585042536b46776563364a2d4232516e5671644256494c6336336131334979346162707336536b693158643966423766337239527a3672717a585330)](http://www.plantuml.com/plantuml/uml/bPBHQi8m58QlbwSuEl2YKAhRnOROudkC8PazTS4aHz8Jd8oz-qAg1ofbiBic_R-Jxs-wxLa7ZiwgsIdeWzDWzOKY0zgZcl4dEeJe3MEhL8eombaRDlu0t-fXsEXCw1dMK1HL1Vk0QM_79d5r3V7KohAgYkB6zBWdtqv1imdeHzqElGAUph01yaDciG3JxrgqoFdGvK0fJsazTx5dYIQew_BZ77GFVgNUYdSeoqPQRFPaAS3Zy-lJ4byQ_3fHu4sLTnib8eauKpXcftj6HoOX92NcqDJYaqNl8gbExbUBwtHikdKk_K7Cv19_arnVlp64Q579g3AMZTp5VGr7hUakKcGC9JLhF4vGsaTjXPBSkFwec6J-B2QnVqdBVILc63a13Iy4abps6Ski1Xd9fB7f3r9Rz6rqzXS0)
> 
> Regards.

using <style> is good for the group header, but the "auto" is still not in the correct position, maybe i should change to another layout.
thanks for your help
