### ISSUE TITLE
Sequence diag misplaced note when nested in activate/deactivate

### ISSUE THREAD

**Issue by Lecrapouille** [plantuml/plantuml#998]
Hi !

Current code:
```
@startuml
actor "Internaute 1 Groupe A" as I1A

rnote over I1A
 Rechercher des informations sur Internet
endrnote

I1A -> I1A : une URL est découverte
activate I1A
rnote over I1A
 Enregistrer une URL
endrnote
deactivate I1A

@enduml
```

does not give the expecting result:
![expected](https://user-images.githubusercontent.com/17874458/163684210-c0860c8c-4c7f-4128-961d-9ffda2fe7141.png)

but gives:
![seq2](https://user-images.githubusercontent.com/17874458/163684261-3dee7971-688b-4ebc-a959-f43faf98b742.png)

While working better with `++--` like:
```
@startuml
actor "Internaute 1 Groupe A" as I1A

rnote over I1A
 Rechercher des informations sur Internet
endrnote

I1A -> I1A ++: une URL est découverte
rnote over I1A
 Enregistrer une URL
endrnote

@enduml
```
which gives
![seq3](https://user-images.githubusercontent.com/17874458/163684341-3ea5d5e1-fadd-43d3-a51e-b9f4f4e4dea3.png)

but I dunno how to call `deactivate I1A`

**Comment by jhoehle** [comment]
>but I dunno how to call deactivate I1A
Please add, after your last endrnote:
I1A -[hidden]> I1A --
This will give the placement you want. With the hidden arrow, ordering becomes explicit.
I can't comment on whether the placement order you observe is a bug or not.

**Comment by Lecrapouille** [comment]
@jhoehle thanks so much. This is exactly what I wanted. I give back the complete fixed code. This kind of hack should be added as example in the official doc (or I missed it).

```
@startuml
actor "Internaute 1 Groupe A" as I1A

rnote over I1A
 Rechercher des informations sur Internet
endrnote

I1A -> I1A ++: une URL est découverte
rnote over I1A
 Enregistrer une URL
endrnote
I1A -[hidden]> I1A --

@enduml
```
